"""Cubit license activation must happen per-user, in the user's session.

Coreform Cubit's RLM license stack stores per-user state in
``%LOCALAPPDATA%\\Coreform\\`` (LAYOUT CHANGED in 2025.12 -- see
LICENSE_2025_12_TOKEN_AUTH below).  The headline rule is:

    Each user activates their own license, in their own Windows
    session.  Admin cannot do it for them.  Admin trying to "help"
    by writing into another user's AppData breaks the cache and
    leaves no obvious symptom -- Cubit silently falls through to
    a slow / failing cold checkout.

This module documents:

    LICENSE_PER_USER_RULE          -- the headline rule (still applies
                                       across all versions).
    LICENSE_2025_12_TOKEN_AUTH     -- 2025.12 cache-layout change,
                                       token-based auth, 2026-06-05
                                       old-portal retirement, and the
                                       "cached-license + login -> HTTP
                                       500" twin-issue hypothesis.
"""

LICENSE_PER_USER_RULE = """
# Cubit license activation must be per-user, in the user's session

The headline rule:

    **Each user activates Cubit's license in their OWN account.**
    Admin cannot bootstrap it for them.

## Why per-user is the only correct path

Coreform Cubit's RLM license stack stores per-user state in:

    %LOCALAPPDATA%\\Coreform\\Cubit\\Coreform\\licenses\\renewals

This file is bound to the **user's own logon token**: it is
generated by ``rlm_activate.exe --login <email> <password>`` running
inside that user's session, and the embedded UUID / hostid /
timestamp combination is only valid for the originating session.
Cubit reads it at startup to confirm the seat is still valid.

A copy from another user (even bit-identical, even on the same
machine) will not validate.

## CORRECT: each user runs the lab launcher themselves

Lab convention (since 2026-04-24):

Place the per-user launcher on a managed internal share or an
equivalent per-site software distribution path.  The public package
must not hard-code host names, drive letters, account rosters, or
private launcher paths.

The launcher script:

  1. Looks for ``%LOCALAPPDATA%/Coreform/Cubit/Coreform/licenses/
     renewals`` in the *current user's* AppData.
  2. If absent, or older than 7 days, runs
     ``rlm_activate.exe --login <email> <password>`` -- still in
     the user's own session.
  3. Launches Cubit.

Because step (2) runs under the user's token, the renewals file
ends up owned by the user, ACL-clean, and accepted by Cubit.  The
launcher must be invoked **by the user themselves** -- double-clicking
the ``.cmd`` wrapper, running it from their VSCode terminal,
opening it from a Public Desktop shortcut.  It cannot be invoked
"on behalf of" the user from an admin SSH session.

## ANTI-PATTERN: admin writes / copies the renewals file

If an admin SSH session writes / copies a ``renewals`` file into
another user's AppData (SMB write, scp, ``Copy-Item``, or any other
admin-side file operation), the file appears at the right path but
Windows assigns it the **wrong owner**:

    Owner: BUILTIN\\Administrators (or NT AUTHORITY\\SYSTEM)

The target user's later **read** still works (admin grants
``Users:R`` by default), but **rlm_activate refuses to update a
renewals file it did not create**.  Three things happen:

  1. ``rlm_activate --login`` no-ops on the foreign-owned cache.
  2. Cubit silently falls through to cold license checkout (slow:
     > 60 s before "ready") OR fails outright with "License Error:
     No license found" if the lab license server is unreachable.
  3. The foreign-owned file looks "present and valid" so neither
     the user nor the next admin notices anything is wrong.

## What admin CAN safely do

Admin's role is **infrastructure setup only**:

  - Install ``coreform_cubit.exe`` and ``rlm_activate.exe`` under
    ``C:\\Program Files\\Coreform Cubit ...\\bin\\`` (machine-wide,
    Users:RX).
  - Place the per-user launcher script on the managed internal share
    so each user
    can read + execute it from their own session.
  - Place a ``.cmd`` wrapper alongside the ``.ps1`` so users do not
    need to type ``pwsh -NoProfile -ExecutionPolicy Bypass``.
  - Optionally create a Public Desktop shortcut
    (``C:\\Users\\Public\\Desktop\\``) pointing at the ``.cmd``.

That is the complete admin task list for Cubit license setup.  The
license activation itself MUST be left to the user.

## Diagnostic checklist (admin SSH, READ-ONLY)

When asked "does Cubit work for user X on host Y", an admin SSH
session can verify infrastructure state without writing:

1. **Plugin deploy state** (machine-wide)::

       cubit-plugin-install --verify-only

   Verifies .ccm / .pyd binaries match package source by sha256 and
   reports any stale retired Qt5 .ccl files.

2. **Per-user .cubit init script**::

       Get-Content C:/Users/<u>/.cubit

   Should contain a ``play "...radia_startup.py"`` line.  For
   ``--all-users`` installs this should point under
   ``C:/ProgramData/Radia/Cubit/``; for current-user installs it should
   point under ``%LOCALAPPDATA%/Radia/Cubit/``.

3. **Per-user Cubit.ini plugin path**::

       Get-Content C:/Users/<u>/AppData/Roaming/Coreform/Cubit.ini |
         Select-String 'plugin'

   Should show
   ``plugin\\paths=C:/Program Files/Coreform Cubit 2025.12/bin/plugins``.

4. **Per-user license renewals cache**::

       Test-Path C:/Users/<u>/AppData/Local/Coreform/licenses/renewals
       (Get-Acl C:/Users/<u>/AppData/Local/Coreform/licenses/renewals).Owner

   Existence is required for fast Cubit launch.  Owner MUST be the
   user themselves -- if it is ``BUILTIN\\Administrators`` or
   ``NT AUTHORITY\\SYSTEM``, the cache was written by an admin and
   needs to be deleted (see cleanup below) so the user's launcher
   can rebuild it.

What admin CANNOT verify from SSH: that the user's actual Cubit
launch succeeds and the panel toolbar loads.  That requires either
the user to report back, or the SSH-pubkey impersonation bootstrap
(``debug-remote-user`` skill, 2026-04-24).

## If you find a foreign-owned renewals file

```powershell
# As Administrator on the target host:
$f = "C:\\Users\\<u>\\AppData\\Local\\Coreform\\licenses\\renewals"
takeown /F $f /A
icacls $f /grant Administrators:F
Remove-Item $f -Force
# Tell the user to launch via the lab launcher (their own session
# will rebuild the cache with correct ownership).
```

Do NOT replace the file with another admin-written copy -- that
just repeats the original mistake.

## Failure-mode cheatsheet

| Symptom                              | Likely cause                          | Fix                                                  |
|--------------------------------------|---------------------------------------|------------------------------------------------------|
| User's first Cubit launch is > 60 s  | No renewals cache (cold checkout)     | User runs lab launcher once                          |
| "License Error: No license found"    | Cache missing AND license server down | User runs launcher; if still fails, network issue    |
| Cache exists but Cubit still slow    | Cache too old (> 7 d) or corrupted    | User runs launcher (force re-login)                  |
| Cache exists, owned by Admin/SYSTEM  | Admin tried to "help"                 | Delete file, user re-runs launcher                   |
| Per-user launcher hangs              | rlm server unreachable, user offline  | Network / VPN check                                  |

## References

- ``debug-remote-user`` skill, "The 2026-04-21 false-path (do not
  repeat)" -- the original incident.
- ``debug-remote-user`` skill, "Cubit license: each user launches
  explicitly (2026-04-24 retire)" -- when the lab moved off the
  logon-trigger Scheduled Task model.
- ``radia_mcp.cubit.license_warmup`` -- the runtime warmup module
  that runs INSIDE the user's own session.  It is safe to invoke
  because it does not write into other users' AppData; it ONLY
  refreshes the calling user's own renewals cache.
"""


LICENSE_2025_12_TOKEN_AUTH = """
# Cubit 2025.12 license cache layout + token-based auth

**Coreform Cubit 2025.12 changed the license cache layout.**  The old
file paths and the `rlm_activate --login` server contract are still
visible in the binary but the supporting files have moved and the
server-side validation now rejects re-login while a valid token
exists.  This section documents what changed, the LAB's adapted
launcher behaviour, and the 2026-06-05 portal retirement.

## File layout migration

| Era | Path (under `%LOCALAPPDATA%\\Coreform\\`) | Contents |
|---|---|---|
| ~ 2025.3 (legacy) | `Cubit\\Coreform\\licenses\\renewals` | JSON cache with `{"Valid": {"today": ..., "licenses": [...]}}`. ~200 bytes. |
| **2025.12+** | `login_tokens.json` (TOP LEVEL) | `{"Cubit":"<UUID>"}` -- 48 bytes, opaque refresh token. |
| 2025.12+ | `cubit_creds` (TOP LEVEL) | Encrypted credentials, ~114 bytes. |
| 2025.12+ | `licenses\\rlm_diagnostics.txt` | Plain-text RLM diagnostic dump (host id, env, ISV csimsoft, etc.) |

The deep `Cubit\\Coreform\\licenses\\` tree is **dead** in 2025.12 and
the old portal that wrote `renewals` JSONs **retires on 2026-06-05**.
LAB has already deleted the legacy tree (`Remove-Item -Recurse -Force
$LOCALAPPDATA\\Coreform\\Cubit`); see 2026-05-26 working session.

## Twin issue: cached-token + --login -> HTTP 500

When a user's `login_tokens.json` is still fresh, running
`rlm_activate.exe --login <email> <password>` reproducibly returns

    HTTP error: http status: 500
    License error: HTTP connection error

This is hypothesised to be one of two server-side changes (LAB
investigation 2026-05-26):

  (iii) **二重発行防止** -- the Coreform RLM server refuses to issue
        a new token while an existing valid token is on record for the
        same account.  A 500 rather than a 401 is used, perhaps to
        confuse scrapers.  Workaround: `rlm_activate --logout` first,
        which releases the server-side seat, then `--login` succeeds.

  (ii)  **Server-side --login deprecation in progress** -- the API
        contract may have changed (added required headers / MFA / OAuth)
        and the older `rlm_activate.exe` client doesn't speak the new
        protocol.  500 is the server's "I don't know how to respond
        to this request" fallback.

The two hypotheses are observationally indistinguishable from a
client.  Either way: **don't try to re-login while a valid cached
token exists** -- the request will fail, possibly using up a rate-limit
quota.  Wait for the cached token to naturally expire (~10-14 days),
OR run `--logout` first.

## Recommended launcher behaviour (CoreformCubit.ps1 2026-05-26)

The lab launcher
implements the following adapted policy:

  1. Probe `$LOCALAPPDATA\\Coreform\\login_tokens.json`.  If present
     and `(now - mtime) < 7 days`, skip `--login` entirely (`$needLogin
     = $false`).  This avoids the 500 -> hypothesis-(iii) trap.
  2. If token is missing OR > 7 days old, run `rlm_activate --login`
     with **retry + exponential backoff** (1s / 3s / 10s, 4 attempts
     total) for transient `HTTP 5xx` failures.  Credentials failures
     (`HTTP 4xx`, "unauthorized", "invalid email/password") do NOT
     retry -- they won't fix themselves.
  3. If all retries fail AND the cached license is < 2 days from
     expiring, emit a `Write-Warning`.  Otherwise (cache fresh) emit
     a calm yellow `Write-Host` saying "using cached seat".
  4. Launch Cubit either way -- the cached token / seat is still
     valid as long as RLM hasn't actively revoked it.

## Force-refresh path (-ForceLogin)

If a user needs a fresh token before the natural expiry (e.g. they
switched machines, or suspect token corruption), invoke the launcher
with `-ForceLogin`.  That runs `rlm_activate --logout` (releases the
server-side seat) and THEN `--login`.  Because the seat is now free,
hypothesis (iii) doesn't apply and the login should succeed.

## Failure-mode cheatsheet (updated for 2025.12)

| Symptom | Likely cause (2025.12 era) | Fix |
|---|---|---|
| Launcher prints "License token cached (X d old)" then Cubit launches | Normal -- token < 7 d, login skipped | None |
| Launcher prints retry sequence then "RLM server unreachable" then Cubit launches | Server 500'd, fail-safe to cached seat | None; will retry next time |
| Launcher cycles retry attempts on every invocation despite fresh token | `login_tokens.json` missing or > 7 d | Run with `-ForceLogin` once; or wait 1 day |
| Cubit refuses to launch ("No license") and cached token > 14 d | Genuinely expired token | `-ForceLogin` to refresh (logout + login) |
| `rlm_activate --login` returns 401 (NOT 500) | Account / credentials problem | Verify email/password in CoreformCubit.ps1 |
| `rlm_activate --login` keeps returning 500 even after `--logout` | Possibly hypothesis (ii) -- server protocol change | Wait for Coreform fix; report to support; cached seat still works |

## 2026-06-05 portal retirement

The legacy portal (the one that wrote the old `Cubit\\Coreform\\licenses\\
renewals` JSON cache) is announced for retirement on 2026-06-05.
After that date the legacy `renewals` mechanism stops being a
fallback; only the 2025.12+ `login_tokens.json` flow remains.  LAB
has pre-emptively deleted the legacy `Cubit\\` subtree to avoid
relying on it.

## References

- LAB session 2026-05-26 -- diagnosis of 500 retry trap +
  `CoreformCubit.ps1` adaptation.
- Coreform Cubit 2025.12 install at
  `C:\\Program Files\\Coreform Cubit 2025.12\\bin\\rlm_activate.exe`
  (`--help` shows `--login` still documented as "Currently only valid
  for Cubit Learn users").
- LAB tasks #74 (uninstall 2025.3), #75 (config cleanup) for the
  2025.3 -> 2025.12 migration arc.
"""


def get_license_documentation(topic: str = "per_user_rule") -> str:
    """Return Cubit license documentation by topic.

    Topics:
        "per_user_rule"      -- (default) headline rule: each user must
                                activate Cubit's license in their own
                                session; admin cannot do it for them.
        "admin_overwrite"    -- alias for the same warning, framed as
                                "do NOT overwrite from admin".
        "token_auth_2025_12" -- 2025.12 cache-layout change + token-
                                based auth + HTTP 500 二重発行防止
                                hypothesis + 2026-06-05 portal
                                retirement.
        "all"                -- concatenate both sections.
    """
    topic = (topic or "").lower().strip()
    if topic == "all":
        return (
            f"# ===== Per-user activation rule =====\n\n"
            f"{LICENSE_PER_USER_RULE}\n\n"
            f"# ===== 2025.12 token-based auth =====\n\n"
            f"{LICENSE_2025_12_TOKEN_AUTH}"
        )
    if topic in (
        "token_auth_2025_12", "token_auth", "token", "2025_12",
        "2025.12", "twin_issue", "retry_backoff", "force_login",
        "portal_retirement", "login_tokens", "login_tokens_json",
    ):
        return LICENSE_2025_12_TOKEN_AUTH
    if topic in (
        "",
        "per_user_rule", "per_user", "user_rule",
        "admin_overwrite", "admin", "renewals", "warning",
    ):
        return LICENSE_PER_USER_RULE
    return (
        f"Unknown license topic '{topic}'.  Available: per_user_rule, "
        f"admin_overwrite (alias), token_auth_2025_12, all."
    )
