"""Cubit license activation must happen per-user, in the user's session.

Coreform Cubit's RLM license stack stores per-user state in
``%LOCALAPPDATA%\\Coreform\\Cubit\\Coreform\\licenses\\renewals``.
The headline rule is:

    Each user activates their own license, in their own Windows
    session.  Admin cannot do it for them.  Admin trying to "help"
    by writing into another user's AppData breaks the cache and
    leaves no obvious symptom -- Cubit silently falls through to
    a slow / failing cold checkout.

This module documents the rule, the failure mode that motivates it,
and the diagnostic checklist for verifying user state from an admin
session WITHOUT writing.
"""

LICENSE_PER_USER_RULE = """
# Cubit license activation must be per-user, in the user's session

The headline rule:

    **Each user activates Cubit's license in their OWN account.**
    Admin cannot bootstrap it for them.

## Why per-user is the only correct path

Coreform Cubit's RLM license stack stores per-user state in:

    %LOCALAPPDATA%\\Coreform\\Cubit\\Coreform\\licenses\\renewals

This file is bound to the **user's own logon token**: it is
generated by ``rlm_activate.exe --login <email> <password>`` running
inside that user's session, and the embedded UUID / hostid /
timestamp combination is only valid for the originating session.
Cubit reads it at startup to confirm the seat is still valid.

A copy from another user (even bit-identical, even on the same
machine) will not validate.

## CORRECT: each user runs the lab launcher themselves

Lab convention (since 2026-04-24):

| Host    | Per-user launcher                                     |
|---------|-------------------------------------------------------|
| LAB     | ``S:/CoreformCubit/CoreformCubit.ps1``                |
| 100号機 | ``W:/00_CAE/CoreformCubit/CoreformCubit.ps1``         |

(LAB ``S:`` and 100号機 ``W:/00_CAE`` are the same SMB share.)

The launcher script:

  1. Looks for ``%LOCALAPPDATA%/Coreform/Cubit/Coreform/licenses/
     renewals`` in the *current user's* AppData.
  2. If absent, or older than 7 days, runs
     ``rlm_activate.exe --login <email> <password>`` -- still in
     the user's own session.
  3. Launches Cubit.

Because step (2) runs under the user's token, the renewals file
ends up owned by the user, ACL-clean, and accepted by Cubit.  The
launcher must be invoked **by the user themselves** -- double-clicking
the ``.cmd`` wrapper, running it from their VSCode terminal,
opening it from a Public Desktop shortcut.  It cannot be invoked
"on behalf of" the user from an admin SSH session.

## ANTI-PATTERN: admin writes / copies the renewals file

If an admin SSH session writes / copies a ``renewals`` file into
another user's AppData (SMB write, scp, ``Copy-Item``, or any other
admin-side file operation), the file appears at the right path but
Windows assigns it the **wrong owner**:

    Owner: BUILTIN\\Administrators (or NT AUTHORITY\\SYSTEM)

The target user's later **read** still works (admin grants
``Users:R`` by default), but **rlm_activate refuses to update a
renewals file it did not create**.  Three things happen:

  1. ``rlm_activate --login`` no-ops on the foreign-owned cache.
  2. Cubit silently falls through to cold license checkout (slow:
     > 60 s before "ready") OR fails outright with "License Error:
     No license found" if the lab license server is unreachable.
  3. The foreign-owned file looks "present and valid" so neither
     the user nor the next admin notices anything is wrong.

## What admin CAN safely do

Admin's role is **infrastructure setup only**:

  - Install ``coreform_cubit.exe`` and ``rlm_activate.exe`` under
    ``C:\\Program Files\\Coreform Cubit ...\\bin\\`` (machine-wide,
    Users:RX).
  - Place the per-user launcher script on the SMB share
    (``W:/00_CAE/CoreformCubit/CoreformCubit.ps1``) so each user
    can read + execute it from their own session.
  - Place a ``.cmd`` wrapper alongside the ``.ps1`` so users do not
    need to type ``pwsh -NoProfile -ExecutionPolicy Bypass``.
  - Optionally create a Public Desktop shortcut
    (``C:\\Users\\Public\\Desktop\\``) pointing at the ``.cmd``.

That is the complete admin task list for Cubit license setup.  The
license activation itself MUST be left to the user.

## Diagnostic checklist (admin SSH, READ-ONLY)

When asked "does Cubit work for user X on host Y", an admin SSH
session can verify infrastructure state without writing:

1. **Plugin deploy state** (machine-wide)::

       cubit-plugin-install --verify-only

   Verifies .ccm / .ccl / .pyd binaries match package source by
   sha256.

2. **Per-user .cubit init script**::

       Get-Content C:/Users/<u>/.cubit

   Should contain a ``play "...startup.py"`` line pointing at the
   deployed ``radia/panels/startup.py``.

3. **Per-user Cubit.ini plugin path**::

       Get-Content C:/Users/<u>/AppData/Roaming/Coreform/Cubit.ini |
         Select-String 'plugin'

   Should show
   ``plugin\\paths=C:/Program Files/Coreform Cubit 2025.3/bin/plugins``.

4. **Per-user license renewals cache**::

       Test-Path C:/Users/<u>/AppData/Local/Coreform/licenses/renewals
       (Get-Acl C:/Users/<u>/AppData/Local/Coreform/licenses/renewals).Owner

   Existence is required for fast Cubit launch.  Owner MUST be the
   user themselves -- if it is ``BUILTIN\\Administrators`` or
   ``NT AUTHORITY\\SYSTEM``, the cache was written by an admin and
   needs to be deleted (see cleanup below) so the user's launcher
   can rebuild it.

What admin CANNOT verify from SSH: that the user's actual Cubit
launch succeeds and the panel toolbar loads.  That requires either
the user to report back, or the SSH-pubkey impersonation bootstrap
(``debug-remote-user`` skill, 2026-04-24).

## If you find a foreign-owned renewals file

```powershell
# As Administrator on the target host:
$f = "C:\\Users\\<u>\\AppData\\Local\\Coreform\\licenses\\renewals"
takeown /F $f /A
icacls $f /grant Administrators:F
Remove-Item $f -Force
# Tell the user to launch via the lab launcher (their own session
# will rebuild the cache with correct ownership).
```

Do NOT replace the file with another admin-written copy -- that
just repeats the original mistake.

## Failure-mode cheatsheet

| Symptom                              | Likely cause                          | Fix                                                  |
|--------------------------------------|---------------------------------------|------------------------------------------------------|
| User's first Cubit launch is > 60 s  | No renewals cache (cold checkout)     | User runs lab launcher once                          |
| "License Error: No license found"    | Cache missing AND license server down | User runs launcher; if still fails, network issue    |
| Cache exists but Cubit still slow    | Cache too old (> 7 d) or corrupted    | User runs launcher (force re-login)                  |
| Cache exists, owned by Admin/SYSTEM  | Admin tried to "help"                 | Delete file, user re-runs launcher                   |
| Per-user launcher hangs              | rlm server unreachable, user offline  | Network / VPN check                                  |

## References

- ``debug-remote-user`` skill, "The 2026-04-21 false-path (do not
  repeat)" -- the original incident.
- ``debug-remote-user`` skill, "Cubit license: each user launches
  explicitly (2026-04-24 retire)" -- when the lab moved off the
  logon-trigger Scheduled Task model.
- ``radia_mcp.cubit.license_warmup`` -- the runtime warmup module
  that runs INSIDE the user's own session.  It is safe to invoke
  because it does not write into other users' AppData; it ONLY
  refreshes the calling user's own renewals cache.
"""


def get_license_documentation(topic: str = "per_user_rule") -> str:
    """Return Cubit license documentation by topic.

    Topics:
        "per_user_rule"     -- (default) headline rule: each user must
                               activate Cubit's license in their own
                               session; admin cannot do it for them.
        "admin_overwrite"   -- alias for the same warning, framed as
                               "do NOT overwrite from admin".
    """
    topic = (topic or "").lower().strip()
    if topic in (
        "",
        "per_user_rule", "per_user", "user_rule",
        "admin_overwrite", "admin", "renewals", "warning",
    ):
        return LICENSE_PER_USER_RULE
    return (
        f"Unknown license topic '{topic}'.  Available: per_user_rule, "
        f"admin_overwrite (alias)."
    )
