function result = fitFiveMomentumExitOptics(relativeMomentumOffsets, ...
    transversePositionsM,transverseAnglesRad,options)
%FITFIVEMOMENTUMEXITOPTICS Fit canonical five-particle exit optics.
%   The position and angle samples are fitted in the basis
%   [1, delta, delta^2]. The reported x0 and psi0 are the tracked values at
%   delta=0; eta and eta_prime are the fitted linear coefficients.
arguments
    relativeMomentumOffsets {mustBeNumeric,mustBeReal}
    transversePositionsM {mustBeNumeric,mustBeReal}
    transverseAnglesRad {mustBeNumeric,mustBeReal}
    options.X0LimitM (1,1) double = 1.0e-3
    options.Psi0LimitRad (1,1) double = 1.0e-3
    options.EtaLimitM (1,1) double = 5.0e-3
    options.EtaPrimeLimitRad (1,1) double = 1.0e-3
end

offsets=double(relativeMomentumOffsets(:));
positions=double(transversePositionsM(:));
angles=double(transverseAnglesRad(:));
if numel(offsets)~=5 || numel(positions)~=5 || numel(angles)~=5
    error("radia:tracking:FiveMomentumSamples", ...
        "five-particle optics requires exactly five samples");
end
if any(~isfinite([offsets;positions;angles]))
    error("radia:tracking:FiveMomentumSamples", ...
        "five-particle offsets and exit states must be finite");
end
if any(diff(offsets)<=0)
    error("radia:tracking:MomentumOffsets", ...
        "relative momentum offsets must be strictly increasing");
end
central=find(offsets==0.0);
if numel(central)~=1
    error("radia:tracking:MomentumOffsets", ...
        "five-particle offsets must contain exactly one zero");
end

limits=[options.X0LimitM;options.Psi0LimitRad; ...
    options.EtaLimitM;options.EtaPrimeLimitRad];
if any(~isfinite(limits)) || any(limits<=0)
    error("radia:tracking:AcceptanceLimits", ...
        "five-particle acceptance limits must be finite and positive");
end

design=[ones(5,1),offsets,offsets.^2];
positionCoefficients=design\positions;
angleCoefficients=design\angles;
positionResidual=positions-design*positionCoefficients;
angleResidual=angles-design*angleCoefficients;
response=[positions(central);angles(central); ...
    positionCoefficients(2);angleCoefficients(2)];
passed=abs(response)<=limits;
regressionInverse=pinv(design);

result=struct( ...
    "schema","radia-five-momentum-exit-optics/v1", ...
    "relative_momentum_offsets",offsets, ...
    "linear_regression_weights",regressionInverse(2,:), ...
    "x0_m",response(1), ...
    "psi0_rad",response(2), ...
    "eta_m",response(3), ...
    "eta_prime_rad",response(4), ...
    "x_fitted_intercept_m",positionCoefficients(1), ...
    "psi_fitted_intercept_rad",angleCoefficients(1), ...
    "x_quadratic_m",positionCoefficients(3), ...
    "psi_quadratic_rad",angleCoefficients(3), ...
    "max_x_residual_m",max(abs(positionResidual)), ...
    "max_psi_residual_rad",max(abs(angleResidual)), ...
    "limits",struct( ...
        "x0_m",limits(1), ...
        "psi0_rad",limits(2), ...
        "eta_m",limits(3), ...
        "eta_prime_rad",limits(4)), ...
    "pass_x0",passed(1), ...
    "pass_psi0",passed(2), ...
    "pass_eta",passed(3), ...
    "pass_eta_prime",passed(4), ...
    "pass_all",all(passed));
end
