function result = ltspiceGate(moduleName, functionName, positional, options)
%LTSPICEGATE Call a Radia LTspice circuit quality or knowledge operation.
arguments
    moduleName (1,1) string
    functionName (1,1) string
    positional (1,:) cell = {}
    options.Keywords (1,1) struct = struct()
end

allowedModules = [ ...
    "allpass_gate", "bandwidth_gate", "bipolar_efficiency_gate", ...
    "bipolar_rail_gate", "bipolar_startup_gate", "boost_gate", ...
    "bridge_rectifier_gate", "complex_zero_gate", ...
    "distributed_line_gate", "filter_gates", "hysteresis_gate", ...
    "ideal_transformer_gate", "knowledge", "learning_quality", ...
    "ltspice_v43_gates", "ltspice_v44_gates", "ltspice_v45_gates", ...
    "ltspice_v46_gates", "ltspice_v47_gates", "ltspice_v48_gates", ...
    "ltspice_v49_gates", "ltspice_v50_gates", "ltspice_v51_gates", ...
    "ltspice_v52_gates", "ltspice_v53_gates", "ltspice_v54_gates", ...
    "ltspice_v55_gates", "measure", "monte_carlo_gate", "noise_gate", ...
    "patentability", "psrr_gate", "rectifier_gate", ...
    "series_rlc_gate", "three_phase_delta_gate", ...
    "voltage_multiplier_gate"];
if ~ismember(moduleName, allowedModules)
    error("radia:python:Module", ...
        "Unsupported Radia LTspice gate module: %s", moduleName);
end

result = radia.internal.callPython("radia.ltspice." + moduleName, ...
    functionName, positional, Keywords=options.Keywords);
end
