"""Golden test for --greedy-turns (the GREEDY CONSTRUCTIVE low-turn strategy).

"Put up a pin, lay the next turn where it helps most."  Instead of contouring
the continuous psi and quantising (which is NON-MONOTONIC in turn count -- N=2
can beat N=20), the coil is built turn-by-turn by matching pursuit with a common
series current: each added loop most reduces the field residual.  MONOTONE by
construction, so the rms-vs-turns trace directly answers "fewest turns for a
spec".  Two candidate dictionaries: (A) dense psi iso-contour loops, (B) small
tangent-plane loops at surface pins.

The .vol meshes are gitignored, regenerated by
``fixtures/make_streamfunction_vol.py``.  Calc runs in a SUBPROCESS; SKIPS on the
LAB MKL/Qt DLL shadow.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_greedy_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed:\n{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


def _run(coil, evalv, extra):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--order", "1", "--target-cf", "x", "--method", "manufacture",
           "--eval-max", "20", "--confine", "off"] + extra
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if ("mkl" in low or "dll" in low or "libiomp" in low
                or (not r.stderr.strip() and abs(r.returncode) > 1000000)):
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(f"calc failed (rc={r.returncode}):\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def _assert_monotone_improving(r, max_turns):
    assert r.get("greedy_turns") is True
    tr = r["greedy_trace"]
    assert 1 <= len(tr) <= max_turns
    assert r["n_turns_used"] == len(tr)
    # MONOTONE by construction: each turn never increases the residual
    for i in range(1, len(tr)):
        assert tr[i]["rms"] <= tr[i - 1]["rms"] + 1e-9, \
            f"greedy not monotone at turn {i}: {tr[i-1]['rms']} -> {tr[i]['rms']}"
    # and the coil genuinely improved from the first turn
    assert tr[-1]["rms"] < tr[0]["rms"], "greedy made no progress"


def test_greedy_contour_dictionary(sample_vols):
    """(A) dense psi iso-contour loops: greedy builds a monotone rms-vs-turns
    trace -- the correct (monotone) replacement for the non-monotonic contour-
    quantise turn-count search."""
    coil, evalv = sample_vols
    r = _run(coil, evalv, ["--greedy-turns", "8", "--greedy-dict", "contour"])
    assert "error" not in r, f"greedy contour error: {r.get('error')}"
    assert r["greedy_dict"] == "contour"
    _assert_monotone_improving(r, 8)


def test_greedy_pin_dictionary(sample_vols):
    """(B) small tangent-plane loops at surface pins ("wind a loop on a pin"):
    same greedy machinery, a different dictionary -- still monotone."""
    coil, evalv = sample_vols
    r = _run(coil, evalv, ["--greedy-turns", "8", "--greedy-dict", "pin"])
    assert "error" not in r, f"greedy pin error: {r.get('error')}"
    assert r["greedy_dict"] == "pin"
    _assert_monotone_improving(r, 8)


def test_greedy_target_stops_early(sample_vols):
    """--greedy-target stops adding turns once the residual meets the spec, so
    the trace directly gives the FEWEST turns for that accuracy."""
    coil, evalv = sample_vols
    r = _run(coil, evalv, ["--greedy-turns", "12", "--greedy-dict", "contour",
                           "--greedy-target", "0.6"])
    assert "error" not in r, f"greedy target error: {r.get('error')}"
    _assert_monotone_improving(r, 12)
    # met the spec early (turn 2 ~ 0.59 < 0.6) -> stopped well before the budget
    assert r["greedy_final_rms"] <= 0.6 + 1e-9
    assert r["n_turns_used"] < 12


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
