"""Golden test for calc_streamfunction.py (SF coil design, Design mode).

Stage-2 validation lock for the .vol-based stream-function designer.  The
canonical sample is a cylinder LATERAL surface coil + a DSV-sphere-volume
evaluation region (generated OCC, Cubit-free, by the fixture script), with a
Gx = "x" target Bz.  Runs the CLI via subprocess, parses the JSON on stdout,
and asserts the key numbers lie inside a hard band.

The sample .vol meshes are gitignored, so they are regenerated by
``fixtures/make_streamfunction_vol.py`` into a temp dir each run.  Both the
mesh-gen and the calc run in SUBPROCESSES so NGSolve stays out of the pytest
process (the LAB MKL/Qt DLL shadow crashes NGSolve-in-pytest); the test SKIPS
if that environment cannot run NGSolve in a subprocess.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


@pytest.fixture(scope="module")
def biplanar_vols(tmp_path_factory):
    """Two-plate biplanar coil + midplane DSV (the multi-surface fixture)."""
    d = str(tmp_path_factory.mktemp("sf_biplanar"))
    fixture = os.path.join(HERE, "fixtures", "make_biplanar_vol.py")
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, fixture, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"biplanar mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "biplanar_coil.vol")
    evalv = os.path.join(d, "biplanar_eval.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("biplanar .vol files not produced")
    return coil, evalv


def _run_calc(coil, evalv, target, extra=None):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--target-cf", target, "--order", "2"] + (extra or [])
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest); run "
                        "calc_streamfunction.py directly to verify")
        raise AssertionError(
            f"calc_streamfunction.py failed (rc={r.returncode}):\n"
            f"STDERR:\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\nSTDERR:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_streamfunction_design_gx_golden(sample_vols):
    """Gx = 'x' Bz target on the cylinder-surface coil: solve + peak in band."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x")
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "design"
    assert r["target_kind"] == "Bz"
    assert r["ndof"] > 100 and r["ndof_free"] > 0
    assert r["n_constraint"] > 0 and r["n_measure"] > 0
    # scalar Bz target -> exactly one constraint row per constraint point
    assert r["n_constraints"] == r["n_constraint"], \
        f"scalar Bz: 1 row/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    # both metrics present: fit residual (at constraints) + true homogeneity
    # (field error at the interior measure points)
    assert "fit_residual_rms" in r and "homogeneity_rms" in r
    # well-conditioned small DSV: homogeneity stays tight
    assert r["rms"] < 5.0e-2, f"homogeneity too large: {r['rms']}"
    assert r["homogeneity_rms"] == r["rms"]
    # peak surface current density (mesh-sensitive -> wide band around ~3.4e5)
    assert 2.0e5 < r["peak_J"] < 5.0e5, f"peak_J out of band: {r['peak_J']}"
    assert r["t_solve_s"] >= 0.0


def test_streamfunction_vector_b_constraints(sample_vols):
    """A 3-vector target gives 3 constraint rows per eval point."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "(0, 0, 1)", extra=["--alpha", "0.01"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["target_kind"] == "vector_B"
    assert r["n_constraints"] == 3 * r["n_constraint"], \
        f"vector B: 3 rows/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    assert r["peak_J"] > 0.0


def test_streamfunction_pareto_front(sample_vols):
    """Pareto mode (alpha-sweep) returns a (homogeneity, peak) front; the
    homogeneity worsens monotonically toward the over-regularised end."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--method", "pareto", "--n-alpha", "5"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "pareto"
    front = r["front"]
    assert len(front) == r["n_alpha"] == 5
    for p in front:
        assert p["homogeneity_rms"] >= 0.0 and p["peak_J"] > 0.0
    # the largest-alpha point is the least homogeneous (most regularised)
    assert front[-1]["homogeneity_rms"] >= front[0]["homogeneity_rms"]


def test_streamfunction_pareto_levers(sample_vols):
    """linf lever drops the peak current over its IRLS trajectory; geometry
    lever's homogeneity worsens as the eval region (DSV) grows."""
    coil, evalv = sample_vols
    rl = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "pareto",
                          "--pareto-lever", "linf", "--linf-iter", "5",
                          "--eval-max", "30"])
    assert "error" not in rl, f"linf error: {rl.get('error')}"
    assert rl["pareto_lever"] == "linf"
    fl = rl["front"]
    assert len(fl) == 5
    # IRLS minimax does not RAISE the peak current end-to-end
    assert fl[-1]["peak_J"] <= fl[0]["peak_J"] * 1.001, \
        f"linf raised the peak: {fl[0]['peak_J']} -> {fl[-1]['peak_J']}"

    rg = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "pareto",
                          "--pareto-lever", "geometry", "--n-alpha", "3",
                          "--eval-max", "30"])
    assert "error" not in rg, f"geometry error: {rg.get('error')}"
    assert rg["pareto_lever"] == "geometry"
    fg = rg["front"]
    assert len(fg) == 3
    # larger eval region -> harder -> worse homogeneity (monotone front)
    assert fg[-1]["homogeneity_rms"] >= fg[0]["homogeneity_rms"]
    assert fg[-1]["eval_scale"] > fg[0]["eval_scale"]


def test_streamfunction_manufacture(sample_vols):
    """Manufacture: psi iso-contours -> single-stroke wire -> PEEC.  The
    orientation-consistent separate turns reproduce the Gx target (validates
    the discretisation); the single-stroke wire + PEEC inductance are
    produced."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--order", "1", "--method", "manufacture",
                         "--nlevels", "8", "--eval-max", "25",
                         "--peec", "--peec-freq", "1e5"])
    assert "error" not in r, f"manufacture error: {r.get('error')}"
    assert r["method"] == "manufacture"
    assert r["n_loops"] > 0 and r["n_wire_points"] > 10
    assert r["wire_length_m"] > 0.0
    # separate orientation-consistent turns reproduce the Gx target well
    assert r["loops_homogeneity_rms"] < 5.0e-2, \
        f"separate-turns coil inaccurate: {r['loops_homogeneity_rms']}"
    assert r["wire_homogeneity_rms"] > 0.0       # single-stroke (connectors)
    assert r["best_fit_current_A"] != 0.0
    # PEEC inductance positive, resistance non-negative
    assert r["peec"]["L_H"] > 0.0 and r["peec"]["R_ohm"] >= 0.0


def test_streamfunction_field_aware_chain(sample_vols):
    """Field-aware chaining (default) chooses the connector cuts to minimise
    the full one-current WIRE error, so it is never worse than nearest-
    neighbour -- and much better once the contours close.  Also exposes the
    open-contour diagnostic (this fixture's short former leaves them open)."""
    coil, evalv = sample_vols
    base = ["--order", "1", "--method", "manufacture", "--nlevels", "10",
            "--eval-max", "40"]
    rn = _run_calc(coil, evalv, "x", extra=base + ["--chain", "nn"])
    rf = _run_calc(coil, evalv, "x", extra=base + ["--chain", "field_aware"])
    assert "error" not in rn and "error" not in rf
    assert rn["chain_method"] == "nn"
    assert rf["chain_method"] == "field_aware"
    # never worse than nearest-neighbour (small tolerance for descent ties)
    assert rf["wire_homogeneity_rms"] <= rn["wire_homogeneity_rms"] * 1.05, \
        f"field_aware {rf['wire_homogeneity_rms']} > nn {rn['wire_homogeneity_rms']}"
    # open-contour count is reported (the former-sizing diagnostic)
    assert "n_open_contours" in rf and rf["n_open_contours"] >= 0


def test_streamfunction_contour_hp_and_flux(sample_vols, tmp_path):
    """Order-p (hp) contour subdivides each triangle and evaluates the curved
    order-2 psi (sub=3); the bubble-system flux plot renders the coil's field
    lines with density ~ |B| on a cut-plane."""
    coil, evalv = sample_vols
    png = str(tmp_path / "flux.png")
    steps = str(tmp_path / "steps.png")
    r = _run_calc(coil, evalv, "x",
                  extra=["--method", "manufacture", "--nlevels", "12",
                         "--eval-max", "40", "--confine", "abe",
                         "--contour-sub", "3", "--distort", "--distort-iter",
                         "2", "--wire-diam", "2e-3", "--flux-plot", png,
                         "--flux-plane", "y", "--steps-plot", steps])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["contour_sub"] == 3
    assert r["n_open_contours"] == 0
    # the high-p contour still yields an accurate separate-turn coil
    assert r["loops_homogeneity_rms"] < 5.0e-2
    # bubble-system flux plot rendered (skip if matplotlib unavailable)
    if "flux_plot_error" not in r:
        assert r["n_flux_lines"] > 0
        assert os.path.exists(png)
    # per-step manufacturing plot (contours -> wire -> bankin -> thickness)
    if "steps_plot_error" not in r:
        assert r.get("steps_plot") == steps
        assert os.path.exists(steps)


def test_streamfunction_confine_closes_contours(sample_vols):
    """Boundary confinement (psi=0 on the former edge) closes the contours on
    ANY former -> a manufacturable single-stroke gradient coil.  On the short
    fixture the unconfined Gx contours all run off the ends (n_open > 0);
    --confine on closes them (n_open == 0) and lowers the delivered
    single-stroke wire error.  This is the method-completing condition."""
    coil, evalv = sample_vols
    base = ["--order", "1", "--method", "manufacture", "--nlevels", "12",
            "--eval-max", "40"]
    roff = _run_calc(coil, evalv, "x", extra=base + ["--confine", "off"])
    ron = _run_calc(coil, evalv, "x", extra=base + ["--confine", "on"])
    rabe = _run_calc(coil, evalv, "x", extra=base + ["--confine", "abe"])
    assert "error" not in roff and "error" not in ron and "error" not in rabe
    assert roff["confine"] == "off" and ron["confine"] == "on"
    assert rabe["confine"] == "abe"
    # unconfined: contours run off the short former; confined: they all close
    assert roff["n_open_contours"] > 0, "short former should leave open contours"
    assert ron["n_open_contours"] == 0, "confine should close every contour"
    assert rabe["n_open_contours"] == 0, "abe should close every contour"
    # closing the contours lowers the delivered single-stroke wire error
    assert ron["wire_homogeneity_rms"] < roff["wire_homogeneity_rms"], \
        f"confine {ron['wire_homogeneity_rms']} !< off {roff['wire_homogeneity_rms']}"
    # Abe edge-equipotential: better/equal DESIGN accuracy than plain psi=0
    # (free boundary constants -> larger function space).  The separate-turn
    # coil is accurate.  (The single-stroke WIRE error is chaining-dependent --
    # abe's boundary-hugging contours can chain worse -- so it is NOT asserted
    # here; abe's value is the canonical BC + generality + design accuracy.)
    assert rabe["homogeneity_rms"] <= ron["homogeneity_rms"] * 1.05, \
        f"abe design {rabe['homogeneity_rms']} !<= on {ron['homogeneity_rms']}"
    assert rabe["loops_homogeneity_rms"] < 5.0e-2, \
        f"abe separate-turn coil inaccurate: {rabe['loops_homogeneity_rms']}"


def test_streamfunction_field_cross_codebase(tmp_path):
    """End-to-end (A): the SF design routine's coil field matches Radia's
    INDEPENDENT C++ Biot-Savart (rad.ObjFlmCur) -- an external-codebase
    confirmation, not self-consistency.  Runs the verify example which designs
    a uniform-Bz cylindrical coil (MRI scale) and cross-checks the two
    engines."""
    import json as _json
    script = os.path.join(REPO, "examples", "stream_function",
                          "verify_coil_field_independent.py")
    if not os.path.exists(script):
        pytest.skip("verify example not present")
    jpath = str(tmp_path / "vc.json")
    cmd = [sys.executable, script, "--order", "1", "--nlevels", "8",
           "--cases", "uniform", "--outdir", str(tmp_path), "--json", jpath]
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/Radia subprocess env issue (LAB pytest)")
        raise AssertionError(f"verify example failed (rc={r.returncode}):\n"
                             f"{r.stderr[-1500:]}")
    with open(jpath) as f:
        d = _json.load(f)
    case = d["cases"][0]
    assert case["case"] == "uniform"
    # INDEPENDENT-codebase field agreement (numpy design routine vs Radia C++)
    assert case["rel_segment_vs_radia"] < 1.0e-6, \
        f"design vs Radia C++ disagree: {case['rel_segment_vs_radia']}"
    # the ~8-turn solenoid-equivalent is uniform over the DSV
    assert case["bz_uniformity"] < 5.0e-2


def test_streamfunction_biplanar(biplanar_vols):
    """Multi-surface generality: a BIPLANAR coil (two disconnected plate
    components in ONE surface mesh) designs + manufactures through the SAME
    FE-direct path as the single-surface cylinder -- no special-casing.  abe
    groups BOTH plates' boundary components (ndof_free < ndof) and the contours
    close on each plate (n_open == 0)."""
    coil, evalv = biplanar_vols
    # design: fits the Gx target on the two-plate former
    rd = _run_calc(coil, evalv, "x", extra=["--order", "1", "--confine", "abe"])
    assert "error" not in rd, f"biplanar design error: {rd.get('error')}"
    assert rd["method"] == "design"
    # abe reduces DOFs (groups each plate's boundary component -> free constant)
    assert rd["ndof_free"] < rd["ndof"], "abe should group the plate edges"
    assert rd["rms"] < 1.0e-2, f"biplanar homogeneity too large: {rd['rms']}"
    # manufacture: contours close on BOTH plates, separate-turn coil accurate
    rm = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "manufacture",
                          "--nlevels", "8", "--confine", "abe"])
    assert "error" not in rm, f"biplanar manufacture error: {rm.get('error')}"
    assert rm["n_loops"] > 0 and rm["n_wire_points"] > 10
    assert rm["n_open_contours"] == 0, \
        "biplanar contours should close on each plate"
    assert rm["loops_homogeneity_rms"] < 1.0e-2, \
        f"biplanar separate-turn coil inaccurate: {rm['loops_homogeneity_rms']}"


def test_streamfunction_figures_no_in_figure_title():
    """Lab figure convention (radia_mcp.figure): NO in-figure title on ANY
    figure -- the caption carries it.  The shipped panel calc cannot import the
    radia_mcp save-time gate, and the examples/ demos that DON'T use
    save_lab_figure have no runtime gate either, so lock the whole SF figure
    suite statically: the shipped calc AND every examples/stream_function
    demo use no ax.set_title / fig.suptitle (panels are identified by (a)-(d)
    corner text via ax.text / ax.text2D).  Fast (source scan; no NGSolve)."""
    import glob
    targets = [CALC] + sorted(glob.glob(os.path.join(
        REPO, "examples", "stream_function", "demo_*.py")))
    bad = []
    for path in targets:
        with open(path, encoding="utf-8") as f:
            src = f.read()
        if ".set_title(" in src or ".suptitle(" in src:
            bad.append(os.path.basename(path))
    assert not bad, (
        "in-figure title (ax.set_title / fig.suptitle) -- move it to the "
        "caption (lab rule, radia_mcp.figure); offenders: " + ", ".join(bad))


def test_streamfunction_min_inductance(sample_vols):
    """Min-inductance regularizer: design min 1/2 psi^T L psi s.t. A psi = B
    where L is the ngsolve.bem single-layer self-inductance (K = n x grad psi).
    This is the canonical MIN-STORED-ENERGY gradient-coil objective.  Locks the
    dense BEM assembly path: it runs, fits the Gx target, and reports a positive
    finite physical stored energy."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--order", "1", "--confine", "abe",
                         "--regularize", "inductance"])
    assert "error" not in r, f"inductance design error: {r.get('error')}"
    assert r["regularize"] == "inductance"
    # still fits the target (the seminorm only picks among A psi = B solutions)
    assert r["rms"] < 5.0e-2, f"inductance homogeneity too large: {r['rms']}"
    # the minimised objective is reported and physical (positive, finite)
    assert "stored_energy_J" in r, "min-inductance must report stored_energy_J"
    assert 0.0 < r["stored_energy_J"] < 1.0e30, \
        f"unphysical stored energy: {r['stored_energy_J']}"
    assert r["peak_J"] > 0.0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
