"""Golden test for --optimize-levels (the few-turn contour-LEVEL optimization).

Pillar 2 of the "SF solver complete for all N" work: the uniform equal-deltaI
contour levels are suboptimal at low turn count.  --optimize-levels does a
coordinate descent on the N ordered levels to minimise the EQUAL-CURRENT (single
series current) discrete-loop field error, keeping clean iso-contours.  Locks
that, for a FEW-turn case, the optimised levels beat the uniform default.

The .vol meshes are gitignored, regenerated by
``fixtures/make_streamfunction_vol.py``.  Mesh-gen + calc run in SUBPROCESSES;
SKIPS on the LAB MKL/Qt DLL shadow.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_levels_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


def _run_calc(coil, evalv, extra):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--order", "1", "--target-cf", "x"] + extra
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if ("mkl" in low or "dll" in low or "libiomp" in low
                or (not r.stderr.strip() and abs(r.returncode) > 1000000)):
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(
            f"calc_streamfunction.py failed (rc={r.returncode}):\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\nSTDERR:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_optimize_levels_beats_uniform_few_turns(sample_vols):
    """FEW-turn (nlevels=5) Gx: optimised levels cut the equal-current (single
    series current) discrete-loop field error well below the uniform levels."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, ["--method", "manufacture", "--nlevels", "5",
                                "--optimize-levels", "--eval-max", "30",
                                "--confine", "off"])
    assert "error" not in r, f"manufacture error: {r.get('error')}"
    assert r.get("levels_optimized") is True
    u = r["equal_current_rms_uniform"]
    o = r["equal_current_rms_optimized"]
    assert u > 0.0 and o > 0.0
    # optimisation never worsens the equal-current fit, and for this few-turn
    # case it cuts it meaningfully.  The MAGNITUDE is mesh-dependent (measured
    # ~0.68->0.48 at maxh 0.04, ~0.77->0.24 at maxh 0.05), so the gain band is
    # generous (>=10%); the hard lock is "never worsens".
    assert o <= u * 1.001, f"optimize-levels worsened the fit: {u} -> {o}"
    assert o < 0.9 * u, \
        f"optimize-levels gave little few-turn gain: {u} -> {o}"


def test_optimize_levels_absent_by_default(sample_vols):
    """Without the flag, levels stay uniform (no metric, no behaviour change)."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, ["--method", "manufacture", "--nlevels", "8",
                                "--eval-max", "30", "--confine", "off"])
    assert "error" not in r
    assert "levels_optimized" not in r
    assert r["method"] == "manufacture"


def test_auto_chain_resolution_improves_delivered_wire_saddle(sample_vols):
    """The field-aware cut-opt resolution AUTO-scales with the loop count; for a
    clustered multi-region (Z2 saddle, --optimize-levels) coil that lowers the
    DELIVERED single-stroke WIRE field error vs the old fixed (ncut=24, passes=4).

    The loop-set field is fixed; only the inter-loop connectors depend on the
    cuts.  More passes monotonically lower the cut-opt objective and a finer
    n_cut grid samples more cuts, so auto resolution is a STRONG NET improvement
    on clustered coils -- though NOT a per-geometry guarantee (the cut grids for
    different n_cut are not strictly nested, so a marginal case can shift a few
    %).  This stubby fixture is firmly in the win regime (the under-resolved
    default leaves Z2 ~0.18, auto ~0.17; a longer former 0.20 -> 0.067).  Target
    Z2 via a trailing --target-cf (argparse last-wins over the helper's 'x')."""
    coil, evalv = sample_vols
    base = ["--method", "manufacture", "--nlevels", "16", "--optimize-levels",
            "--eval-max", "40", "--confine", "abe",
            "--target-cf", "z*z-(x*x+y*y)/2"]
    old = _run_calc(coil, evalv, base + ["--chain-ncut", "24",
                                         "--chain-passes", "4"])
    new = _run_calc(coil, evalv, base)               # auto resolution (default)
    assert "error" not in old and "error" not in new
    wo = old["wire_homogeneity_rms"]
    wn = new["wire_homogeneity_rms"]
    assert wo > 0.0 and wn > 0.0
    # measured ~10% delivered-wire gain on this fixture; lock a conservative >=5%
    # (the gain is geometry-driven, not FP noise, so it is stable on the fixed
    # fixture mesh).
    assert wn < 0.95 * wo, \
        f"auto chain resolution did not improve the delivered wire: {wo} -> {wn}"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
