"""Golden test for the MATERIAL-AWARE (iron) stream-function design kernel.

Locks the ``--iron-vol`` path of calc_streamfunction.py: the free-space Biot-
Savart operator gets the iron reaction field added (reduced scalar potential on
a Kelvin open-boundary FE mesh, ``A = A_free + A_react``), so a coil designed
near an iron yoke/shield/core hits the target IN the iron system.

Verified mechanism: examples/kelvin_transformation/DtN_spectrum demo_oo /
demo_sp1 (material-aware design HITS, free-space design MISSES).  Here the same
operator is exercised end-to-end through the production CLI on a spherical iron
shell enclosing the canonical cylinder coil + DSV.

The .vol meshes are gitignored, regenerated by
``fixtures/make_iron_coil_vol.py`` into a temp dir each run.  Mesh-gen + calc
run in SUBPROCESSES (NGSolve out of pytest); SKIPS on the LAB MKL/Qt DLL shadow.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_iron_coil_vol.py")


@pytest.fixture(scope="module")
def iron_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_iron_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"iron mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    iron = os.path.join(d, "iron_kelvin.vol")
    if not all(os.path.exists(p) for p in (coil, evalv, iron)):
        pytest.skip("iron .vol files not produced")
    return coil, evalv, iron


def _run_calc(coil, evalv, target, extra=None):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--order", "1", "--eval-max", "30"]
    if target is not None:
        cmd += ["--target-cf", target]
    cmd += (extra or [])
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if ("mkl" in low or "dll" in low or "libiomp" in low
                or (not r.stderr.strip() and abs(r.returncode) > 1000000)):
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(
            f"calc_streamfunction.py failed (rc={r.returncode}):\n"
            f"STDERR:\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\nSTDERR:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_streamfunction_iron_aware_design(iron_vols):
    """Material-aware design runs end-to-end, reports the iron metadata, and
    fits the target IN the iron system (the reaction is part of the operator)."""
    coil, evalv, iron = iron_vols
    r = _run_calc(coil, evalv, "x", extra=["--iron-vol", iron, "--mu-r", "200"])
    assert "error" not in r, f"iron design error: {r.get('error')}"
    assert r["method"] == "design"
    # iron metadata recorded (Result Output Policy)
    assert r.get("material_aware") is True
    assert r["iron_vol"] == "iron_kelvin.vol"
    assert r["mu_r"] == 200.0
    assert r["iron_mat"] == "iron"
    # the iron-aware design fits the target in the iron system
    assert r["ndof"] > 50 and r["peak_J"] > 0.0
    assert r["rms"] < 5.0e-2, f"iron-aware homogeneity too large: {r['rms']}"


def test_streamfunction_iron_changes_the_design(iron_vols):
    """The iron reaction is genuinely IN the operator: the material-aware design
    differs from the free-space design (different current pattern -> peak_J),
    i.e. ignoring the iron would give a different (wrong-in-iron) coil."""
    coil, evalv, iron = iron_vols
    r_iron = _run_calc(coil, evalv, "x", extra=["--iron-vol", iron, "--mu-r", "200"])
    r_free = _run_calc(coil, evalv, "x")
    assert "error" not in r_iron and "error" not in r_free
    assert r_free.get("material_aware") is None      # free run = no iron metadata
    # iron changes the solved current pattern measurably
    rel = abs(r_iron["peak_J"] - r_free["peak_J"]) / (r_free["peak_J"] + 1e-30)
    assert rel > 1.0e-3, (
        f"iron did not change the design (peak_J {r_free['peak_J']} -> "
        f"{r_iron['peak_J']}, rel={rel:.2e}); reaction not in the operator?")


def test_streamfunction_iron_exact_source(iron_vols):
    """Opt-in exact source (B_s evaluated at the iron QUADRATURE points, no P1-
    vertex interpolation): runs end-to-end, reports iron_exact_source, fits the
    target, and gives a DIFFERENT (finer-source) reaction than the default P1
    source -- confirming the source plateau is real and removed."""
    coil, evalv, iron = iron_vols
    base = ["--iron-vol", iron, "--mu-r", "200"]
    r_p1 = _run_calc(coil, evalv, "x", extra=base)
    r_ex = _run_calc(coil, evalv, "x",
                     extra=base + ["--iron-exact-source", "--iron-quad-order", "2"])
    assert "error" not in r_ex, f"exact-source error: {r_ex.get('error')}"
    assert r_ex.get("iron_exact_source") is True
    assert r_p1.get("iron_exact_source") is False
    assert r_ex["rms"] < 5.0e-2, f"exact-source homogeneity too large: {r_ex['rms']}"
    # the exact (quadrature) source changes the solved current pattern vs the P1
    # (vertex) source -- the plateau the exact path removes is non-trivial.
    rel = abs(r_ex["peak_J"] - r_p1["peak_J"]) / (r_p1["peak_J"] + 1e-30)
    assert rel > 1.0e-4, (
        f"exact source identical to P1 (peak_J {r_p1['peak_J']} -> "
        f"{r_ex['peak_J']}, rel={rel:.2e}); source path not wired?")


def test_streamfunction_iron_missing_material_raises(iron_vols):
    """No-Fallback: a wrong --iron-mat (absent material) fails loud with the
    available material list, not a silent guess."""
    coil, evalv, iron = iron_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--iron-vol", iron, "--mu-r", "200",
                         "--iron-mat", "steel"])
    assert "error" in r and "steel" in r["error"]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
