"""Golden test for calc_streamfunction.py (SF coil design, Design mode).

Stage-2 validation lock for the .vol-based stream-function designer.  The
canonical sample is a cylinder LATERAL surface coil + a DSV-sphere-volume
evaluation region (generated OCC, Cubit-free, by the fixture script), with a
Gx = "x" target Bz.  Runs the CLI via subprocess, parses the JSON on stdout,
and asserts the key numbers lie inside a hard band.

The sample .vol meshes are gitignored, so they are regenerated by
``fixtures/make_streamfunction_vol.py`` into a temp dir each run.  Both the
mesh-gen and the calc run in SUBPROCESSES so NGSolve stays out of the pytest
process (the LAB MKL/Qt DLL shadow crashes NGSolve-in-pytest); the test SKIPS
if that environment cannot run NGSolve in a subprocess.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


def _run_calc(coil, evalv, target, extra=None):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--target-cf", target, "--order", "2"] + (extra or [])
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest); run "
                        "calc_streamfunction.py directly to verify")
        raise AssertionError(
            f"calc_streamfunction.py failed (rc={r.returncode}):\n"
            f"STDERR:\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\nSTDERR:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_streamfunction_design_gx_golden(sample_vols):
    """Gx = 'x' Bz target on the cylinder-surface coil: solve + peak in band."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x")
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "design"
    assert r["target_kind"] == "Bz"
    assert r["ndof"] > 100 and r["ndof_free"] > 0
    assert r["n_constraint"] > 0 and r["n_measure"] > 0
    # scalar Bz target -> exactly one constraint row per constraint point
    assert r["n_constraints"] == r["n_constraint"], \
        f"scalar Bz: 1 row/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    # both metrics present: fit residual (at constraints) + true homogeneity
    # (field error at the interior measure points)
    assert "fit_residual_rms" in r and "homogeneity_rms" in r
    # well-conditioned small DSV: homogeneity stays tight
    assert r["rms"] < 5.0e-2, f"homogeneity too large: {r['rms']}"
    assert r["homogeneity_rms"] == r["rms"]
    # peak surface current density (mesh-sensitive -> wide band around ~3.4e5)
    assert 2.0e5 < r["peak_J"] < 5.0e5, f"peak_J out of band: {r['peak_J']}"
    assert r["t_solve_s"] >= 0.0


def test_streamfunction_vector_b_constraints(sample_vols):
    """A 3-vector target gives 3 constraint rows per eval point."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "(0, 0, 1)", extra=["--alpha", "0.01"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["target_kind"] == "vector_B"
    assert r["n_constraints"] == 3 * r["n_constraint"], \
        f"vector B: 3 rows/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    assert r["peak_J"] > 0.0


def test_streamfunction_pareto_front(sample_vols):
    """Pareto mode (alpha-sweep) returns a (homogeneity, peak) front; the
    homogeneity worsens monotonically toward the over-regularised end."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--method", "pareto", "--n-alpha", "5"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "pareto"
    front = r["front"]
    assert len(front) == r["n_alpha"] == 5
    for p in front:
        assert p["homogeneity_rms"] >= 0.0 and p["peak_J"] > 0.0
    # the largest-alpha point is the least homogeneous (most regularised)
    assert front[-1]["homogeneity_rms"] >= front[0]["homogeneity_rms"]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
