"""Bibliography INDEX for radia_mcp.topology_optimization.

Auto-generated catalog of 15 PDF references from the Sugahara
Lab literature library.  Catalog paths are relative to the
corpus root (configure the root via RADIA_LIT_ROOT).

Generated by tools/catalog_to_knowledge.py from catalog.json
(pdf_batch_indexer output).  Re-run when new PDFs are added.

Use:
    from radia_mcp.topology_optimization.bibliography_index_knowledge import get_bibliography_index
    print(get_bibliography_index("kelvin"))    # filter
    print(get_bibliography_index(""))          # full
    print(get_bibliography_index("__scanned__"))  # scanned PDFs only
"""

from __future__ import annotations
import json as _json

_CATALOG_JSON = r"""
[
 {
  "filename": "3-D Topology Optimization of Claw-Pole Alternator Using Gaussian-Basis Function With Global and Local Searches.pdf",
  "title": "IEEE TRANSACTIONS ON MAGNETICS, VOL. 56, NO. 1, JANUARY 2020",
  "authors": "Gaussian-Basis Function With Global and Local Searches",
  "abstract_excerpt": "7504604\n3-D Topology Optimization of Claw-Pole Alternator Using\nGaussian-Basis Function With Global and Local Searches\nYoshitsugu Otomo\n1,2, Hajime Igarashi\n1, Yuki Hidaka\n3, Taiga Komatsu3, and Masaki Yamada3\n1Graduate School of Information Science and Technology, Hokkaido University, Sapporo 060-0814, Japan\n2Research Fellow of Japan Society for the Promotion of Science (JSPS), Tokyo 102-0083, Japan\n3Advanced Technology Research and Development Center, Mitsubishi Electric Corporation, Amagasaki 661-8661, Japan\nThis article proposes a two-step topology optimization method based on the normalized Gaussian functions. The proposed method\nis shown to be effective for design of a claw-pole alternator. In this method, the global search using the micro-genetic algorithm\n(μGA) is followed by the",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\逆問題\\3-D Topology Optimization of Claw-Pole Alternator Using Gaussian-Basis Function With Global and Local Searches.pdf"
 },
 {
  "filename": "Application of spectral level set methodology in topology optimization.pdf",
  "title": "Struct Multidisc Optim (2006) 31: 430–443",
  "authors": "DOI 10.1007/s00158-006-0005-2",
  "abstract_excerpt": "DOI 10.1007/s00158-006-0005-2\nRESEARCH\nPAPER\nAlexandra A. Gomes · Afzal Suleman\nApplication of spectral level set methodology in topology\noptimization\nReceived: 28 June 2005 / Revised manuscript received: 28 November 2005 / Published online: 4 April 2006\n© Springer-Verlag 2006\nAbstract In this paper, two benchmark problems in struc-\ntural boundary design are solved using the spectral level set\nmethodology, which is a new approach to topology optimiza-\ntion of interfaces. This methodology is an extension of the\nlevel set methods, in which the interface is represented as the\nzero level set of a function. According to the proposed formu-\nlation, the Fourier coefﬁcients of that function are the design\nvariables describing the interface during the topology opti-\nmization. An advantage of the s",
  "page_count": 14,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\Application of spectral level set methodology in topology optimization.pdf"
 },
 {
  "filename": "Hayaho-Automatic_Design_of_PM_Motor_Using_Monte_Carlo_Tree_Search_in_Conjunction_With_Topology_Optimization.pdf",
  "title": "IEEE TRANSACTIONS ON MAGNETICS, VOL. 58, NO. 9, SEPTEMBER 2022",
  "authors": "Automatic Design of PM Motor Using Monte Carlo Tree Search",
  "abstract_excerpt": "7200504\nAutomatic Design of PM Motor Using Monte Carlo Tree Search\nin Conjunction With Topology Optimization\nHayaho Sato\nand Hajime Igarashi\nGraduate School of Information Science and Technology, Hokkaido University, Sapporo 060-0814, Japan\nA novel automatic design method for permanent magnet (PM) motors using a Monte Carlo tree search is presented. The optimal\nmotor structures are determined through a tree search, in which the motors with different numbers of poles, current phase angles,\nPM conﬁgurations, and numbers of PMs are simultaneously considered. At the leaf nodes, parameter and topology optimizations\nare performed to obtain the optimal material shape and distribution. The proposed method was applied to the optimization of a\n24-slot motor. It was shown to be effective in ﬁnding t",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Monte Carlo Tree Search\\Hayaho-Automatic_Design_of_PM_Motor_Using_Monte_Carlo_Tree_Search_in_Conjunction_With_Topology_Optimization.pdf"
 },
 {
  "filename": "Hayaho-Multi-Objective_Automatic_Design_of_Permanent_Magnet_Motor_Using_Monte_Carlo_Tree_Search.pdf",
  "title": "IEEE TRANSACTIONS ON MAGNETICS, VOL. 59, NO. 5, MAY 2023",
  "authors": "Multi-Objective Automatic Design of Permanent Magnet",
  "abstract_excerpt": "8201304\nMulti-Objective Automatic Design of Permanent Magnet\nMotor Using Monte Carlo Tree Search\nHayaho Sato\nand Hajime Igarashi\nGraduate School of Information Science and Technology, Hokkaido University, Hokkaido 060-0814, Japan\nThis study proposes a novel multi-objective design method based on Monte Carlo tree search (MCTS) for the design of permanent\nmagnet (PM) motors. The global configurations that define the entire structure are represented by nodes in a tree structure. After\nMCTS is performed to select a route extending from the root to leaf node, multi-objective topology optimization (TO) is performed\nat the leaf node to determine the detailed shape, considering a trade-off relationship among objective functions. The novelty of\nthis work lies in the integration of MCTS with multi-",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Monte Carlo Tree Search\\Hayaho-Multi-Objective_Automatic_Design_of_Permanent_Magnet_Motor_Using_Monte_Carlo_Tree_Search.pdf"
 },
 {
  "filename": "Heaviside projection based topology optimization by a PDE-filtered scalar function.pdf",
  "title": "Struct Multidisc Optim (2011) 44:19–24",
  "authors": "DOI 10.1007/s00158-010-0562-2",
  "abstract_excerpt": "DOI 10.1007/s00158-010-0562-2\nBRIEF NOTES\nHeaviside projection based topology optimization\nby a PDE-filtered scalar function\nAtsushi Kawamoto · Tadayoshi Matsumori ·\nShintaro Yamasaki · Tsuyoshi Nomura ·\nTsuguo Kondoh · Shinji Nishiwaki\nReceived: 18 February 2010 / Revised: 24 June 2010 / Accepted: 3 August 2010 / Published online: 29 August 2010\nc⃝Springer-Verlag 2010\nAbstract This paper deals with topology optimization\nbased on the Heaviside projection method using a scalar\nfunction as design variables. The scalar function is then reg-\nularized by a PDE based filter. Several image-processing\nbased filtering techniques have so far been proposed for\nregularization or restricting the minimum length scale.\nThey are conventionally applied to the design sensitivities\nrather than the design va",
  "page_count": 6,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\2020_CAE懇話会_トポロジー最適化\\Heaviside projection based topology optimization by a PDE-filtered scalar function.pdf"
 },
 {
  "filename": "Level set-based topology optimization targeting dielectric resonator-based composite right- and left-handed transmission lines.pdf",
  "title": "INTERNATIONAL JOURNAL FOR NUMERICAL METHODS IN ENGINEERING",
  "authors": "Int. J. Numer. Meth. Engng 2012; 89:1272–1295",
  "abstract_excerpt": "Int. J. Numer. Meth. Engng 2012; 89:1272–1295\nPublished online 6 October 2011 in Wiley Online Library (wileyonlinelibrary.com). DOI: 10.1002/nme.3287\nLevel set-based topology optimization targeting dielectric\nresonator-based composite right- and left-handed\ntransmission lines\nShintaro Yamasaki1,*,†, Tsuyoshi Nomura2, Kazuo Sato2, Naobumi Michishita3,\nYoshihide Yamada3 and Atsushi Kawamoto2\n1Department of Machinery and Control Systems, Shibaura Institute of Technology, 307 Fukasaku, Minuma,\nSaitama 337-8570, Japan\n2Toyota Central R&D Labs., Inc., 41-1 Yokomichi, Nagakute, Aichi 480-1192, Japan\n3Department of Electrical and Electronic Engineering, National Defense Academy, 1-10-20 Hashirimizu,\nYokosuka 239-8686, Japan\nSUMMARY\nIn the last decade, metamaterials have been gaining attention and",
  "page_count": 24,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\Level set-based topology optimization targeting dielectric resonator-based composite right- and left-handed transmission lines.pdf"
 },
 {
  "filename": "Topological shape optimization of microstructural metamaterials using a level set method.pdf",
  "title": "Topological shape optimization of microstructural metamaterials using",
  "authors": "Yiqiang Wang b,a, Zhen Luo a, Nong Zhang a, Zhan Kang b,⇑",
  "abstract_excerpt": "a level set method\nYiqiang Wang b,a, Zhen Luo a, Nong Zhang a, Zhan Kang b,⇑\na School of Electrical, Mechanical and Mechatronic Systems, The University of Technology, Sydney, NSW 2007, Australia\nb State Key Laboratory of Structural Analysis for Industrial Equipment, Dalian University of Technology, Dalian 116024, China\na r t i c l e\ni n f o\nArticle history:\nReceived 1 December 2013\nReceived in revised form 3 February 2014\nAccepted 6 February 2014\nAvailable online 6 March 2014\nKeywords:\nMechanical metamaterials\nArtiﬁcial composite material\nMicrostructure\nLevel set method\nTopological shape optimization\na b s t r a c t\nMetamaterials usually refer to artiﬁcial composite materials consisting of an array of periodically\narranged microstructures, engineered to provide unusual material properties",
  "page_count": 9,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\Topological shape optimization of microstructural metamaterials using a level set method.pdf"
 },
 {
  "filename": "Topology Optimization Using Gabor Filter Application to Synchronous Reluctance Motor.pdf",
  "title": "Transactions on Magnetics",
  "authors": "See http://www.ieee.org/publications_standards/publications/rights/index.html for more information. (Inserted by IEEE.)",
  "abstract_excerpt": "> 326 < \n \n0018-9464 © 2015 IEEE. Personal use is permitted, but republication/redistribution requires IEEE permission. \nSee http://www.ieee.org/publications_standards/publications/rights/index.html for more information. (Inserted by IEEE.) \n1\nTopology Optimization Using Gabor Filter: \nApplication to Synchronous Reluctance Motor \n \nYoshitsugu Otomo1,2, and Hajime Igarashi1, Member, IEEE \n \n1Graduate School of Information Science and Technology, Hokkaido University, Sapporo 060-0814, Japan \n2Research Fellow of Japan Society for the Promotion of Science (JSPS), Tokyo 102-0083, Japan \n \nThis paper proposes a novel topology optimization method using the Gabor filter, which is widely used in the field of image processing. \nThe proposed method is applied to the optimization of a synchronous rel",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\Topology Optimization Using Gabor Filter Application to Synchronous Reluctance Motor.pdf"
 },
 {
  "filename": "Topology Optimization of Magnetic Actuator based on Reluctance Network Modeling and Adjoint Variable Method.pdf",
  "title": "Topology Optimization of Magnetic Actuator based on Reluctance",
  "authors": "Network Modeling and Adjoint Variable Method",
  "abstract_excerpt": "Network Modeling and Adjoint Variable Method\nMing YIN 1, Mohammed NAIDJATE 2, Nicolas BRACIKOWSKI 1, Antoine PIERQUIN 1, Didier TRICHET 1\n1Laboratoire IREENA, Nantes Universit´e, Saint-Nazaire, France, nicolas.bracikowski@univ-nantes.fr\n2 ´Ecole Polytechnique Montr´eal, Montr´eal, Canada, mohammed.naidjate@polymtl.ca\nTopology Optimization (TO) has great significance in primarily the concept design of a product. In the electrical engineering\ncommunity, conventional topology optimization is usually based on a spatial discretization that also is used as the mesh for Finite\nElement Analysis (FEA). In this paper, we proposed to use a local equivalent circuit modeling method - Reluctance Network Analysis\n(RNA). Afterward, a gradient-based optimization algorithm, line search method, was chosen a",
  "page_count": 2,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\RNA法\\Topology Optimization of Magnetic Actuator based on Reluctance Network Modeling and Adjoint Variable Method.pdf"
 },
 {
  "filename": "Topology optimization of conductors in electrical circuit.pdf",
  "title": "Structural and Multidisciplinary Optimization (2019) 59:2205–2225",
  "authors": "RESEARCH PAPER",
  "abstract_excerpt": "This study proposes a topology optimization method for realizing a free-form design of conductors in electrical circuits.",
  "page_count": 21,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\Topology optimization of conductors in electrical circuit.pdf"
 },
 {
  "filename": "コイル銅損と磁気コア鉄損を考慮したワイヤレス電力伝送用コイルのパラメータ・トポロジー最適化.pdf",
  "title": "磁石寸法パラメータと磁気コアトポロジーを同時考慮した",
  "authors": "Considering Magnet Shape Parameter and Magnetic Core Topology",
  "abstract_excerpt": "永久磁石モータの３次元形状最適化法 \n \n正 員 大友 佳嗣＊,  フェロー 阿部 貴志（長崎大学） \n \n3-D Shape Optimization Method for Permanent Magnet Motors \nConsidering Magnet Shape Parameter and Magnetic Core Topology \nYoshitsugu Otomo＊, Takashi Abe (Nagasaki University) \n \nThis paper proposes a 3-D shape optimization method to realize novel 3-D magnet and magnetic core shapes in a \npermanent magnet (PM) motor. In the proposed optimization, the magnet shape is determined with a Boolean geometry \nprojection (BGP) method for its manufacturability. In addition, we propose an extended BGP method to optimize \nmultiple 3-D PMs without introducing any complex geometrical constraints. On the other hand, the magnetic core \nshape is determined with a stacked cylindrical layer-based topology optimization. It is shown that the 3-D optimized",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\コイル銅損と磁気コア鉄損を考慮したワイヤレス電力伝送用コイルのパラメータ・トポロジー最適化.pdf"
 },
 {
  "filename": "磁場整形_3D print of polymer bonded rare-earth magnets, and 3D magnetic field scanning with an end-user 3D printer.pdf",
  "title": "Appl. Phys. Lett. 109, 162401 (2016); https://doi.org/10.1063/1.4964856",
  "authors": "Cite as: Appl. Phys. Lett. 109, 162401 (2016); https://doi.org/10.1063/1.4964856",
  "abstract_excerpt": "109, 162401\n© 2016 Author(s).\n3D print of polymer bonded rare-earth\nmagnets, and 3D magnetic field scanning\nwith an end-user 3D printer\nCite as: Appl. Phys. Lett. 109, 162401 (2016); https://doi.org/10.1063/1.4964856\nSubmitted: 24 May 2016 . Accepted: 03 October 2016 . Published Online: 17 October 2016\nC. Huber, C. Abert, F. Bruckner \n, M. Groenefeld, O. Muthsam, S. Schuschnigg \n, K. Sirak \n, R.\nThanhoffer, I. Teliban, C. Vogler, R. Windl, and D. Suess\nARTICLES YOU MAY BE INTERESTED IN\n Topology optimized and 3D printed polymer-bonded permanent magnets for a predefined\nexternal field\nJournal of Applied Physics 122, 053904 (2017); https://doi.org/10.1063/1.4997441\nRecycled Sm-Co bonded magnet filaments for 3D printing of magnets\nAIP Advances 8, 056722 (2018); https://doi.org/10.1063/1.5007",
  "page_count": 5,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\ハードウェア・磁場設計\\磁場整形_3D print of polymer bonded rare-earth magnets, and 3D magnetic field scanning with an end-user 3D printer.pdf"
 },
 {
  "filename": "磁場整形_Shimming_Additive Manufactured and Topology Optimized Passive Shimming Elements for Permanent Magnetic Systems.pdf",
  "title": "SCientifiC REPOrTS |  (2018) 8:14651  | DOI:10.1038/s41598-018-33059-w",
  "authors": "Additive Manufactured and",
  "abstract_excerpt": "www.nature.com/scientificreports\nAdditive Manufactured and \nTopology Optimized Passive \nShimming Elements for Permanent \nMagnetic Systems\nChristian Huber   1,2, Michael Goertler3, Claas Abert1,2, Florian Bruckner1,2, \nMartin Groenefeld4, Iulian Teliban4 & Dieter Suess1,2\nA method to create a highly homogeneous magnetic field by applying topology optimized, additively \nmanufactured passive shimming elements is investigated. The topology optimization algorithm \ncan calculate a suitable permanent and nonlinear soft magnetic design that fulfills the desired \nfield properties. The permanent magnetic particles are bonded in a polyamide matrix and they \nare manufactured with a low-cost, end-user 3D printer. Stray field measurements and an inverse \nstray field simulation framework can determine p",
  "page_count": 8,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\ハードウェア・磁場設計\\磁場整形_Shimming_Additive Manufactured and Topology Optimized Passive Shimming Elements for Permanent Magnetic Systems.pdf"
 },
 {
  "filename": "磁場整形_Single-Sided_TopologyoptimizationbaseddesignofunilateralNMRforgeneratingaremotehomogeneousfield..pdf",
  "title": "Accepted Manuscript",
  "authors": "Topology optimization based design of unilateral NMR for generating a remote",
  "abstract_excerpt": "This paper presents a topology optimization based design method for the design of",
  "page_count": 25,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\ハードウェア・磁場設計\\磁場整形_Single-Sided_TopologyoptimizationbaseddesignofunilateralNMRforgeneratingaremotehomogeneousfield..pdf"
 },
 {
  "filename": "静磁場問題のトポロジー最適化におけるレベルセット法と進化型on-off法.pdf",
  "title": "計算数理工学論文集 Vol.14(2014 年12 月) ，論文No.06-141206",
  "authors": "JASCOME",
  "abstract_excerpt": "JASCOME \n \n静磁場問題のトポロジー最適化における \nレベルセット法と進化型on/off 法 \nON LEVELSET AND EVOLUTIONARY ON/OFF METHODS  \nFOR TOPOLOGY OPTIMIZATION IN MAGNETOSTATIC PROBLEMS \n \n佐藤 孝洋1),  渡辺 浩太2)， 五十嵐 一3) \n \n Takahiro Sato,  Kota Watanabe,  Hajime IGARASHI \n \n1) 北海道大学 大学院情報科学研究科 （〒060-0814 札幌市北区北14 条西9 丁目，tsato@em-si.eng.hokudai.ac.jp） \n2) 室蘭工業大学  （〒050-8585 室蘭市水元町，k-wata@mmm.muroran-it.ac.jp） \n3) 北海道大学 大学院情報科学研究科 （〒060-0814 札幌市北区北14条西9丁目，igarashi@ssi.ist.hokudai.ac.jp） \n \nThis paper discusses topology optimizations in magnetostatic problems. The levelset \nmethod and the on/off method based on Normalize Gaussian Networks (NGnet) are applied \nto the magnetic shield and IPM motor problems. In the shield and motor problems, the \nlevelset method can find inferior and superior solutions, respectiv",
  "page_count": 6,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\静磁場問題のトポロジー最適化におけるレベルセット法と進化型on-off法.pdf"
 }
]
"""

CATALOG_ENTRIES = _json.loads(_CATALOG_JSON)


def get_bibliography_index(query: str = "") -> str:
    """Return formatted catalog entries.

    Args:
        query: empty string → all entries.  "__scanned__" → only
               scanned PDFs.  Otherwise, case-insensitive substring
               match in title + authors + abstract + filename.
    """
    q = query.strip().lower()
    if q == "__scanned__":
        sel = [e for e in CATALOG_ENTRIES if e.get("is_scanned")]
    elif q == "":
        sel = CATALOG_ENTRIES
    else:
        sel = []
        for e in CATALOG_ENTRIES:
            haystack = " ".join(str(e.get(k, "")) for k in
                ("filename", "title", "authors", "abstract_excerpt")).lower()
            if q in haystack:
                sel.append(e)

    if not sel:
        return f"No catalog entries match query: {query!r}\n"

    lines = [f"## radia_mcp bibliography index — {len(sel)} entries"]
    if query and q != "__scanned__":
        lines.append(f"(filtered by: {query!r})")
    lines.append("")
    for e in sel:
        fn = e.get("filename", "?")
        title = e.get("title", "?")
        a = e.get("authors", "")
        pages = e.get("page_count", 0)
        scanned = e.get("is_scanned", False)
        abs_text = e.get("abstract_excerpt", "")
        lines.append(f"### {fn}")
        lines.append(f"**Title**: {title}")
        if a:
            lines.append(f"**Authors**: {a[:200]}")
        flag = "  [SCANNED — OCR limited]" if scanned else ""
        lines.append(f"**Pages**: {pages}{flag}")
        if abs_text:
            lines.append(f"**Abstract**: {abs_text[:500]}")
        lines.append("")
    return "\n".join(lines)
