"""Golden test for calc_streamfunction.py (SF coil design, Design mode).

Stage-2 validation lock for the .vol-based stream-function designer.  The
canonical sample is a cylinder LATERAL surface coil + a DSV-sphere-volume
evaluation region (generated OCC, Cubit-free, by the fixture script), with a
Gx = "x" target Bz.  Runs the CLI via subprocess, parses the JSON on stdout,
and asserts the key numbers lie inside a hard band.

The sample .vol meshes are gitignored, so they are regenerated by
``fixtures/make_streamfunction_vol.py`` into a temp dir each run.  Both the
mesh-gen and the calc run in SUBPROCESSES so NGSolve stays out of the pytest
process (the LAB MKL/Qt DLL shadow crashes NGSolve-in-pytest); the test SKIPS
if that environment cannot run NGSolve in a subprocess.
"""
from __future__ import annotations

import json
import math
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


@pytest.fixture(scope="module")
def biplanar_vols(tmp_path_factory):
    """Two-plate biplanar coil + midplane DSV (the multi-surface fixture)."""
    d = str(tmp_path_factory.mktemp("sf_biplanar"))
    fixture = os.path.join(HERE, "fixtures", "make_biplanar_vol.py")
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, fixture, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"biplanar mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    coil = os.path.join(d, "biplanar_coil.vol")
    evalv = os.path.join(d, "biplanar_eval.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("biplanar .vol files not produced")
    return coil, evalv


def _run_calc(coil, evalv, target, extra=None, expect_error=False):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--order", "2"]
    if target is not None:
        cmd += ["--target-cf", target]
    cmd += (extra or [])
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if ("mkl" in low or "dll" in low or "libiomp" in low
                # blank-stderr crash = MKL/DLL env fault in pytest subprocess
                or (not r.stderr.strip() and abs(r.returncode) > 1000000)):
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest); run "
                        "calc_streamfunction.py directly to verify")
        # fail-loud calc_main (CLAUDE.md No-Fallback) exits non-zero on an
        # {"error": ...} result but STILL prints the error JSON to stdout; for
        # an EXPECTED user error (bad flags / missing material) parse + return
        # that dict, else re-raise the genuine failure.
        if expect_error:
            elines = [ln for ln in r.stdout.splitlines() if ln.strip()]
            if elines:
                try:
                    d = json.loads(elines[-1])
                    if isinstance(d, dict) and "error" in d:
                        return d
                except json.JSONDecodeError:
                    pass
        raise AssertionError(
            f"calc_streamfunction.py failed (rc={r.returncode}):\n"
            f"STDERR:\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\nSTDERR:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_streamfunction_design_gx_golden(sample_vols):
    """Gx = 'x' Bz target on the cylinder-surface coil: solve + peak in band."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x")
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "design"
    assert r["target_kind"] == "Bz"
    assert r["ndof"] > 100 and r["ndof_free"] > 0
    assert r["n_constraint"] > 0 and r["n_measure"] > 0
    # scalar Bz target -> exactly one constraint row per constraint point
    assert r["n_constraints"] == r["n_constraint"], \
        f"scalar Bz: 1 row/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    # both metrics present: fit residual (at constraints) + true homogeneity
    # (field error at the interior measure points)
    assert "fit_residual_rms" in r and "homogeneity_rms" in r
    # well-conditioned small DSV: homogeneity stays tight
    assert r["rms"] < 5.0e-2, f"homogeneity too large: {r['rms']}"
    assert r["homogeneity_rms"] == r["rms"]
    # peak surface current density (mesh-sensitive -> wide band around ~3.4e5)
    assert 2.0e5 < r["peak_J"] < 5.0e5, f"peak_J out of band: {r['peak_J']}"
    assert r["t_solve_s"] >= 0.0


def test_streamfunction_vector_b_constraints(sample_vols):
    """A 3-vector target gives 3 constraint rows per eval point."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "(0, 0, 1)", extra=["--alpha", "0.01"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["target_kind"] == "vector_B"
    assert r["n_constraints"] == 3 * r["n_constraint"], \
        f"vector B: 3 rows/pt expected: {r['n_constraints']} vs {r['n_constraint']}"
    assert r["peak_J"] > 0.0


def test_streamfunction_pareto_front(sample_vols):
    """Pareto mode (alpha-sweep) returns a (homogeneity, peak) front; the
    homogeneity worsens monotonically toward the over-regularised end."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--method", "pareto", "--n-alpha", "5"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["method"] == "pareto"
    front = r["front"]
    assert len(front) == r["n_alpha"] == 5
    for p in front:
        assert p["homogeneity_rms"] >= 0.0 and p["peak_J"] > 0.0
    # the largest-alpha point is the least homogeneous (most regularised)
    assert front[-1]["homogeneity_rms"] >= front[0]["homogeneity_rms"]


def test_streamfunction_pareto_levers(sample_vols):
    """linf lever drops the peak current over its IRLS trajectory; geometry
    lever's homogeneity worsens as the eval region (DSV) grows."""
    coil, evalv = sample_vols
    rl = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "pareto",
                          "--pareto-lever", "linf", "--linf-iter", "5",
                          "--eval-max", "30"])
    assert "error" not in rl, f"linf error: {rl.get('error')}"
    assert rl["pareto_lever"] == "linf"
    fl = rl["front"]
    assert len(fl) == 5
    # IRLS minimax does not RAISE the peak current end-to-end
    assert fl[-1]["peak_J"] <= fl[0]["peak_J"] * 1.001, \
        f"linf raised the peak: {fl[0]['peak_J']} -> {fl[-1]['peak_J']}"

    rg = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "pareto",
                          "--pareto-lever", "geometry", "--n-alpha", "3",
                          "--eval-max", "30"])
    assert "error" not in rg, f"geometry error: {rg.get('error')}"
    assert rg["pareto_lever"] == "geometry"
    fg = rg["front"]
    assert len(fg) == 3
    # larger eval region -> harder -> worse homogeneity (monotone front)
    assert fg[-1]["homogeneity_rms"] >= fg[0]["homogeneity_rms"]
    assert fg[-1]["eval_scale"] > fg[0]["eval_scale"]


def test_streamfunction_manufacture(sample_vols):
    """Manufacture: psi iso-contours -> single-stroke wire -> PEEC.  The
    orientation-consistent separate turns reproduce the Gx target (validates
    the discretisation); the single-stroke wire + PEEC inductance are
    produced."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--order", "1", "--method", "manufacture",
                         "--nlevels", "8", "--eval-max", "25",
                         "--peec", "--peec-freq", "1e5"])
    assert "error" not in r, f"manufacture error: {r.get('error')}"
    assert r["method"] == "manufacture"
    assert r["n_loops"] > 0 and r["n_wire_points"] > 10
    assert r["wire_length_m"] > 0.0
    # separate orientation-consistent turns reproduce the Gx target well
    assert r["loops_homogeneity_rms"] < 5.0e-2, \
        f"separate-turns coil inaccurate: {r['loops_homogeneity_rms']}"
    assert r["wire_homogeneity_rms"] > 0.0       # single-stroke (connectors)
    assert r["best_fit_current_A"] != 0.0
    # PEEC inductance positive, resistance non-negative
    assert r["peec"]["L_H"] > 0.0 and r["peec"]["R_ohm"] >= 0.0


def test_streamfunction_field_aware_chain(sample_vols):
    """Field-aware chaining (default) chooses the connector cuts to minimise
    the full one-current WIRE error, so it is never worse than nearest-
    neighbour -- and much better once the contours close.  Also exposes the
    open-contour diagnostic (this fixture's short former leaves them open)."""
    coil, evalv = sample_vols
    base = ["--order", "1", "--method", "manufacture", "--nlevels", "10",
            "--eval-max", "40"]
    rn = _run_calc(coil, evalv, "x", extra=base + ["--chain", "nn"])
    rf = _run_calc(coil, evalv, "x", extra=base + ["--chain", "field_aware"])
    assert "error" not in rn and "error" not in rf
    assert rn["chain_method"] == "nn"
    assert rf["chain_method"] == "field_aware"
    # never worse than nearest-neighbour (small tolerance for descent ties)
    assert rf["wire_homogeneity_rms"] <= rn["wire_homogeneity_rms"] * 1.05, \
        f"field_aware {rf['wire_homogeneity_rms']} > nn {rn['wire_homogeneity_rms']}"
    # open-contour count is reported (the former-sizing diagnostic)
    assert "n_open_contours" in rf and rf["n_open_contours"] >= 0


def test_streamfunction_contour_hp_and_flux(sample_vols, tmp_path):
    """Order-p (hp) contour subdivides each triangle and evaluates the curved
    order-2 psi (sub=3); the bubble-system flux plot renders the coil's field
    lines with density ~ |B| on a cut-plane."""
    coil, evalv = sample_vols
    png = str(tmp_path / "flux.png")
    steps = str(tmp_path / "steps.png")
    r = _run_calc(coil, evalv, "x",
                  extra=["--method", "manufacture", "--nlevels", "12",
                         "--eval-max", "40", "--confine", "abe",
                         "--contour-sub", "3", "--distort", "--distort-iter",
                         "2", "--wire-diam", "2e-3", "--flux-plot", png,
                         "--flux-plane", "y", "--steps-plot", steps])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["contour_sub"] == 3
    assert r["n_open_contours"] == 0
    # the high-p contour still yields an accurate separate-turn coil
    assert r["loops_homogeneity_rms"] < 5.0e-2
    # bubble-system flux plot rendered (skip if matplotlib unavailable)
    if "flux_plot_error" not in r:
        assert r["n_flux_lines"] > 0
        assert os.path.exists(png)
    # per-step manufacturing plot (contours -> wire -> bankin -> thickness)
    if "steps_plot_error" not in r:
        assert r.get("steps_plot") == steps
        assert os.path.exists(steps)


def test_streamfunction_confine_closes_contours(sample_vols):
    """Boundary confinement (psi=0 on the former edge) closes the contours on
    ANY former -> a manufacturable single-stroke gradient coil.  On the short
    fixture the unconfined Gx contours all run off the ends (n_open > 0);
    --confine on closes them (n_open == 0) and lowers the delivered
    single-stroke wire error.  This is the method-completing condition."""
    coil, evalv = sample_vols
    base = ["--order", "1", "--method", "manufacture", "--nlevels", "12",
            "--eval-max", "40"]
    roff = _run_calc(coil, evalv, "x", extra=base + ["--confine", "off"])
    ron = _run_calc(coil, evalv, "x", extra=base + ["--confine", "on"])
    rabe = _run_calc(coil, evalv, "x", extra=base + ["--confine", "abe"])
    assert "error" not in roff and "error" not in ron and "error" not in rabe
    assert roff["confine"] == "off" and ron["confine"] == "on"
    assert rabe["confine"] == "abe"
    # unconfined: contours run off the short former; confined: they all close
    assert roff["n_open_contours"] > 0, "short former should leave open contours"
    assert ron["n_open_contours"] == 0, "confine should close every contour"
    assert rabe["n_open_contours"] == 0, "abe should close every contour"
    # closing the contours lowers the delivered single-stroke wire error
    assert ron["wire_homogeneity_rms"] < roff["wire_homogeneity_rms"], \
        f"confine {ron['wire_homogeneity_rms']} !< off {roff['wire_homogeneity_rms']}"
    # Abe edge-equipotential: better/equal DESIGN accuracy than plain psi=0
    # (free boundary constants -> larger function space).  The separate-turn
    # coil is accurate.  (The single-stroke WIRE error is chaining-dependent --
    # abe's boundary-hugging contours can chain worse -- so it is NOT asserted
    # here; abe's value is the canonical BC + generality + design accuracy.)
    assert rabe["homogeneity_rms"] <= ron["homogeneity_rms"] * 1.05, \
        f"abe design {rabe['homogeneity_rms']} !<= on {ron['homogeneity_rms']}"
    assert rabe["loops_homogeneity_rms"] < 5.0e-2, \
        f"abe separate-turn coil inaccurate: {rabe['loops_homogeneity_rms']}"


def test_streamfunction_field_cross_codebase(tmp_path):
    """End-to-end (A): the SF design routine's coil field matches Radia's
    INDEPENDENT C++ Biot-Savart (rad.ObjFlmCur) -- an external-codebase
    confirmation, not self-consistency.  Runs the verify example which designs
    a uniform-Bz cylindrical coil (MRI scale) and cross-checks the two
    engines."""
    import json as _json
    script = os.path.join(REPO, "validation_test", "stream_function",
                          "verify_coil_field_independent.py")
    if not os.path.exists(script):
        pytest.skip("verify example not present")
    jpath = str(tmp_path / "vc.json")
    cmd = [sys.executable, script, "--order", "1", "--nlevels", "8",
           "--cases", "uniform", "--outdir", str(tmp_path), "--json", jpath]
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/Radia subprocess env issue (LAB pytest)")
        raise AssertionError(f"verify example failed (rc={r.returncode}):\n"
                             f"{r.stderr[-1500:]}")
    with open(jpath) as f:
        d = _json.load(f)
    case = d["cases"][0]
    assert case["case"] == "uniform"
    # INDEPENDENT-codebase field agreement (numpy design routine vs Radia C++)
    assert case["rel_segment_vs_radia"] < 1.0e-6, \
        f"design vs Radia C++ disagree: {case['rel_segment_vs_radia']}"
    # the ~8-turn solenoid-equivalent is uniform over the DSV
    assert case["bz_uniformity"] < 5.0e-2


def test_streamfunction_biplanar(biplanar_vols):
    """Multi-surface generality: a BIPLANAR coil (two disconnected plate
    components in ONE surface mesh) designs + manufactures through the SAME
    FE-direct path as the single-surface cylinder -- no special-casing.  abe
    groups BOTH plates' boundary components (ndof_free < ndof) and the contours
    close on each plate (n_open == 0)."""
    coil, evalv = biplanar_vols
    # design: fits the Gx target on the two-plate former
    rd = _run_calc(coil, evalv, "x", extra=["--order", "1", "--confine", "abe"])
    assert "error" not in rd, f"biplanar design error: {rd.get('error')}"
    assert rd["method"] == "design"
    # abe reduces DOFs (groups each plate's boundary component -> free constant)
    assert rd["ndof_free"] < rd["ndof"], "abe should group the plate edges"
    assert rd["rms"] < 1.0e-2, f"biplanar homogeneity too large: {rd['rms']}"
    # manufacture: contours close on BOTH plates, separate-turn coil accurate
    rm = _run_calc(coil, evalv, "x",
                   extra=["--order", "1", "--method", "manufacture",
                          "--nlevels", "8", "--confine", "abe"])
    assert "error" not in rm, f"biplanar manufacture error: {rm.get('error')}"
    assert rm["n_loops"] > 0 and rm["n_wire_points"] > 10
    assert rm["n_open_contours"] == 0, \
        "biplanar contours should close on each plate"
    assert rm["loops_homogeneity_rms"] < 1.0e-2, \
        f"biplanar separate-turn coil inaccurate: {rm['loops_homogeneity_rms']}"


def test_streamfunction_figures_no_in_figure_title():
    """Lab figure convention (radia_mcp.figure): NO in-figure title on ANY
    figure -- the caption carries it.  The shipped panel calc cannot import the
    radia_mcp save-time gate, and the docs-local demo helpers that DON'T use
    save_lab_figure have no runtime gate either, so lock the whole SF figure
    suite statically: the shipped calc AND every docs/stream_function demo
    helper use no ax.set_title / fig.suptitle (panels are identified by (a)-(d)
    corner text via ax.text / ax.text2D).  Fast (source scan; no NGSolve)."""
    import glob
    targets = [CALC] + sorted(glob.glob(os.path.join(
        REPO, "docs", "stream_function", "demo_*.py")))
    bad = []
    for path in targets:
        with open(path, encoding="utf-8") as f:
            src = f.read()
        if ".set_title(" in src or ".suptitle(" in src:
            bad.append(os.path.basename(path))
    assert not bad, (
        "in-figure title (ax.set_title / fig.suptitle) -- move it to the "
        "caption (lab rule, radia_mcp.figure); offenders: " + ", ".join(bad))


def test_streamfunction_ih_resonance(sample_vols):
    """IH-resonance design: pick the turn count (nlevels) so the single-stroke
    coil inductance equals L_target = 1/(omega^2 C) -- the IH work coil + tank
    capacitor resonate at the inverter frequency.  The SAME BEM inductance
    machinery that MINIMISES L for a gradient coil here TARGETS a value for IH
    (L_coil ~ N^2 is set by the turns; the field design is unchanged)."""
    coil, evalv = sample_vols
    # (a) target a specific inductance directly
    r = _run_calc(coil, evalv, "1",
                  extra=["--order", "1", "--method", "manufacture",
                         "--confine", "off", "--target-inductance", "30e-6",
                         "--peec-freq", "2e5"])
    assert "error" not in r, f"resonance design error: {r.get('error')}"
    res = r.get("resonance")
    assert res is not None and res["in_range"], res
    assert 4 <= res["nlevels"] <= 60
    # achieved coil L near the 30 uH target (integer-turn quantised -> ~5-15 %)
    assert res["achieved_rel_error"] < 0.15, res
    assert r["peec"]["L_H"] > 0.0
    # (b) tank-cap path: C + f -> L_target -> the coil resonates near f
    r2 = _run_calc(coil, evalv, "1",
                   extra=["--order", "1", "--method", "manufacture",
                          "--confine", "off", "--resonance-cap", "22e-9",
                          "--peec-freq", "2e5"])
    res2 = r2.get("resonance")
    assert res2 is not None and "resonance_freq_Hz" in res2, res2
    # designed coil resonates within ~12 % of the 200 kHz inverter frequency
    assert abs(res2["resonance_freq_Hz"] - 2.0e5) / 2.0e5 < 0.12, res2


def test_streamfunction_resonance_with_greedy_reports_cap(sample_vols):
    """--greedy-turns (the low-turn coil) + a resonance spec COMPOSE: greedy
    owns the turn count (L_coil ~ N^2 pins it), so the resonance spec does NOT
    search nlevels -- instead the result reports the tank capacitor the
    delivered few-turn coil NEEDS to resonate at the operating frequency
    (required_cap_F), and for --resonance-cap the resonance frequency that coil
    + cap actually reach.  REGRESSION: this combination used to SILENTLY DISCARD
    the resonance target (the greedy branch overwrote the searched nlevels).
    This is exactly the 'few-turn uniform IH coil -> required capacitor' answer."""
    coil, evalv = sample_vols
    # (a) --resonance-cap + --greedy-turns -> required_cap_F + resonance_freq_Hz
    r = _run_calc(coil, evalv, "1",
                  extra=["--order", "1", "--method", "manufacture",
                         "--confine", "off", "--greedy-turns", "8",
                         "--resonance-cap", "47e-9", "--peec-freq", "2e5"])
    assert "error" not in r, f"greedy+resonance error: {r.get('error')}"
    res = r.get("resonance")
    assert res is not None and res.get("mode") == "from_greedy_coil", res
    # turns came from greedy, NOT an nlevels search
    assert res.get("turns_source") == "greedy", res
    assert "nlevels" not in res, "greedy path must not search nlevels"
    L = res["achieved_inductance_H"]
    assert L > 0.0, res
    # required cap resonates THIS coil at the operating freq: C = 1/(w^2 L)
    w = 2.0 * math.pi * 2.0e5
    assert res["required_cap_F"] == pytest.approx(1.0 / (w * w * L), rel=1e-6), res
    # the reported resonance freq for the GIVEN cap is self-consistent
    f_res = 1.0 / (2.0 * math.pi * (L * 47e-9) ** 0.5)
    assert res["resonance_freq_Hz"] == pytest.approx(f_res, rel=1e-6), res
    # (b) --target-inductance + --greedy-turns -> required_cap_F, still no search
    r2 = _run_calc(coil, evalv, "1",
                   extra=["--order", "1", "--method", "manufacture",
                          "--confine", "off", "--greedy-turns", "8",
                          "--target-inductance", "20e-6", "--peec-freq", "2e5"])
    assert "error" not in r2, f"greedy+target-L error: {r2.get('error')}"
    res2 = r2.get("resonance")
    assert res2 is not None and res2.get("mode") == "from_greedy_coil", res2
    assert res2["required_cap_F"] > 0.0 and "nlevels" not in res2, res2


def test_streamfunction_easy_tier_single_stroke_sub500ppm(sample_vols):
    """Method completion (EASY tier): a uniform-Bz (solenoid) target single-
    strokes to SUB-500 ppm with NO --distort -- the nested closed rings have
    no irreducible inter-lobe bridges, so the field-aware chain is a clean
    spiral.  (The HARD Gx fingerprint is intrinsically ~1-2 %; the sheet-metal
    --distort recovers it and min-inductance halves the required bend -- see
    docs/stream_function/single_stroke.md.)  Locks the repository-backed claim
    that the bankin-ho SF pipeline is production-grade on easy targets."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "1",
                  extra=["--order", "1", "--method", "manufacture",
                         "--nlevels", "16", "--confine", "off", "--eval-max", "60"])
    assert "error" not in r, f"uniform manufacture error: {r.get('error')}"
    assert r["n_open_contours"] == 0, "solenoid rings should close on their own"
    assert r["wire_homogeneity_rms"] < 5.0e-4, \
        f"easy-tier single-stroke not sub-500 ppm: {r['wire_homogeneity_rms']}"


def test_streamfunction_min_inductance(sample_vols):
    """Min-inductance regularizer: design min 1/2 psi^T L psi s.t. A psi = B
    where L is the ngsolve.bem single-layer self-inductance (K = n x grad psi).
    This is the canonical MIN-STORED-ENERGY gradient-coil objective.  Locks the
    dense BEM assembly path: it runs, fits the Gx target, and reports a positive
    finite physical stored energy."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x",
                  extra=["--order", "1", "--confine", "abe",
                         "--regularize", "inductance"])
    assert "error" not in r, f"inductance design error: {r.get('error')}"
    assert r["regularize"] == "inductance"
    # still fits the target (the seminorm only picks among A psi = B solutions)
    assert r["rms"] < 5.0e-2, f"inductance homogeneity too large: {r['rms']}"
    # the minimised objective is reported and physical (positive, finite)
    assert "stored_energy_J" in r, "min-inductance must report stored_energy_J"
    assert 0.0 < r["stored_energy_J"] < 1.0e30, \
        f"unphysical stored energy: {r['stored_energy_J']}"
    assert r["peak_J"] > 0.0


DEMO_REGCOIL = os.path.join(REPO, "examples", "stream_function",
                            "demo_regcoil_fusion.py")
DEMO_REGCOIL_ADV = os.path.join(REPO, "examples", "stream_function",
                                "demo_regcoil_fusion_advanced.py")


def test_regcoil_fusion_wout_and_vmec_boundary(tmp_path):
    """Part 4 (C): the VMEC-format boundary helpers, NO NGSolve needed.
    (1) ``_read_wout_boundary`` round-trips the standard VMEC ``wout_*.nc``
    schema (nfp/xm/xn/rmnc/zmns, boundary = last surface) -- this is the
    verification the demo docstring promises for the reader.  (2) the
    rotating-ellipse model boundary is genuinely non-axisymmetric and its
    parametric normals are consistently OUTWARD."""
    netCDF4 = pytest.importorskip("netCDF4")
    import numpy as np
    sys.path.insert(0, os.path.dirname(DEMO_REGCOIL))
    import demo_regcoil_fusion as D

    # --- (1) wout reader round-trip against the VMEC netCDF schema ---
    terms0, nfp0 = D._rotating_ellipse_terms()
    fp = str(tmp_path / "wout_roundtrip.nc")
    ds = netCDF4.Dataset(fp, "w")
    ns, mn = 4, len(terms0)
    ds.createDimension("radius", ns)
    ds.createDimension("mn_mode", mn)
    ds.createVariable("nfp", "i4")[...] = nfp0
    ds.createVariable("ns", "i4")[...] = ns
    ds.createVariable("xm", "f8", ("mn_mode",))[:] = [t[0] for t in terms0]
    ds.createVariable("xn", "f8", ("mn_mode",))[:] = [t[1] * nfp0 for t in terms0]
    rmnc = ds.createVariable("rmnc", "f8", ("radius", "mn_mode"))
    zmns = ds.createVariable("zmns", "f8", ("radius", "mn_mode"))
    rmnc[:] = 0.0
    zmns[:] = 0.0
    rmnc[ns - 1, :] = [t[2] for t in terms0]      # boundary = last flux surface
    zmns[ns - 1, :] = [t[3] for t in terms0]
    ds.close()
    terms_read, nfp_read = D._read_wout_boundary(fp)
    assert nfp_read == nfp0
    assert terms_read == terms0, (terms_read, terms0)

    # a non-VMEC netCDF must RAISE (No-Fallback), not silently mis-read
    bad = str(tmp_path / "not_wout.nc")
    d2 = netCDF4.Dataset(bad, "w")
    d2.createDimension("n", 1)
    d2.createVariable("foo", "f8", ("n",))[:] = 1.0
    d2.close()
    with pytest.raises(ValueError):
        D._read_wout_boundary(bad)

    # a non-stellarator-symmetric (lasym=T) wout carries rmns/zmnc; the symmetric
    # reader must RAISE rather than silently truncate them to the symmetric part
    asym = str(tmp_path / "wout_asym.nc")
    d3 = netCDF4.Dataset(asym, "w")
    d3.createDimension("radius", ns)
    d3.createDimension("mn_mode", mn)
    d3.createVariable("nfp", "i4")[...] = nfp0
    d3.createVariable("xm", "f8", ("mn_mode",))[:] = [t[0] for t in terms0]
    d3.createVariable("xn", "f8", ("mn_mode",))[:] = [t[1] * nfp0 for t in terms0]
    d3.createVariable("rmnc", "f8", ("radius", "mn_mode"))[:] = 0.0
    d3.createVariable("zmns", "f8", ("radius", "mn_mode"))[:] = 0.0
    d3.createVariable("rmns", "f8", ("radius", "mn_mode"))[:] = 0.0   # asymmetric
    d3.close()
    with pytest.raises(ValueError, match="symmetric"):
        D._read_wout_boundary(asym)

    # --- (2) rotating-ellipse boundary: non-axisymmetric + outward normals ---
    pts, nrm = D._vmec_points_normals(terms0, nfp0, 24, 24)
    axis = np.column_stack([
        D.R_MAJOR * pts[:, 0] / np.hypot(pts[:, 0], pts[:, 1]),
        D.R_MAJOR * pts[:, 1] / np.hypot(pts[:, 0], pts[:, 1]),
        np.zeros(len(pts))])
    minor = np.linalg.norm(pts - axis, axis=1)
    assert minor.max() - minor.min() > 1e-3, "boundary should be non-axisym"
    assert (np.sum(nrm * (pts - axis), axis=1) > 0).all(), "normals not outward"


def test_regcoil_fusion_demo_invariants(tmp_path):
    """Parts 1-4 end to end (subprocess): the fusion demo's physics invariants.
    Locks (B) the net-current secular term and (C) the VMEC boundary:
      * forward (PF + stellarator) B.n reproduced to machine precision
      * b1(winding surface) [Euler char, gmsh-free] == number of secular DOFs (== 2)
      * the net-poloidal-current (TF) secular field obeys Ampere 1/R (B_tor*R
        ~ const inside the tube, ~0 outside) and is TANGENT to the plasma
        (its B.n footprint << the net-toroidal one)
      * the VMEC rotating-ellipse boundary is non-axisymmetric and its vertical
        -field B.n target is reproduced to machine precision."""
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    cmd = [sys.executable, DEMO_REGCOIL, "--out-dir", str(tmp_path),
           "--no-plot", "--eval-max", "90", "--n-alpha", "3",
           "--vmec-ntheta", "20", "--vmec-nphi", "20"]
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       cwd=str(tmp_path), timeout=600)
    if r.returncode != 0:
        # tight env-skip (match _run_calc): only genuine MKL/DLL env breakage,
        # NOT a bare ImportError/gmsh substring -- those would mask a real
        # regression in the load-bearing cohomology / physics path as a skip.
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(f"demo failed: {r.stderr[-1500:]}")
    with open(os.path.join(str(tmp_path), "demo_regcoil_fusion.json")) as f:
        d = json.load(f)
    # 1. forward = machine precision
    for nm, dd in d["producible_targets"].items():
        assert dd["bn_residual_rel"] < 1e-6, (nm, dd)
    # 3. net-current secular term
    nc = d["net_current"]
    assert nc["betti1_winding_surface"] == nc["n_secular_dofs"] == 2, nc
    assert nc["tf_field_BR_const_spread_rel"] < 0.02, nc       # Ampere 1/R
    assert nc["tf_field_outside_over_inside"] < 1e-2, nc       # ~0 outside
    fp = nc["secular_bn_footprint_rel"]
    # TF field is tangent to the plasma: its B.n footprint is >100x smaller than
    # the net-toroidal generator's (measured ~2400-2600x) -> prescribed, not fitted
    assert fp["net_poloidal_TF"] < 0.01 * fp["net_toroidal"], fp
    # 4. VMEC boundary
    vm = d["vmec_boundary"]
    assert vm["non_axisymmetric"] is True, vm
    assert vm["bn_residual_rel"] < 1e-6, vm


def test_regcoil_fusion_advanced(tmp_path):
    """Advanced fusion demo: (A) coil force/stress, (B) a real VMEC boundary,
    (C) FOCUS standoff study.  Runs end to end against a SYNTHETIC multi-mode
    (NFP=3) wout so Part B is deterministic + offline (--no-fetch).  Locks:
      A  |f| = |K x B_avg| matches the magnetic pressure B^2/(2 mu0) (ratio ~1)
         and concentrates on the INBOARD leg (inboard/outboard > 2);
      C  coil complexity is MONOTONIC in the winding gap (closer = simpler) and
         the constrained optimum is the minimum standoff;
      B  the Stage-2 design runs on the (synthetic real-format) boundary to
         machine precision."""
    netCDF4 = pytest.importorskip("netCDF4")
    # a synthetic stellarator-symmetric multi-mode wout (NFP=3, R0=1.0)
    terms = [(0, 0, 1.0, 0.0), (1, 0, 0.18, 0.18), (1, 1, 0.05, -0.05),
             (2, 1, 0.012, -0.012)]
    nfp = 3
    wp = str(tmp_path / "wout_synth.nc")
    ds = netCDF4.Dataset(wp, "w")
    ns, mn = 3, len(terms)
    ds.createDimension("radius", ns)
    ds.createDimension("mn_mode", mn)
    ds.createVariable("nfp", "i4")[...] = nfp
    ds.createVariable("xm", "f8", ("mn_mode",))[:] = [t[0] for t in terms]
    ds.createVariable("xn", "f8", ("mn_mode",))[:] = [t[1] * nfp for t in terms]
    ds.createVariable("rmnc", "f8", ("radius", "mn_mode"))[:] = 0.0
    ds.createVariable("zmns", "f8", ("radius", "mn_mode"))[:] = 0.0
    ds["rmnc"][ns - 1, :] = [t[2] for t in terms]
    ds["zmns"][ns - 1, :] = [t[3] for t in terms]
    ds.close()

    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    cmd = [sys.executable, DEMO_REGCOIL_ADV, "--out-dir", str(tmp_path),
           "--no-plot", "--no-fetch", "--wout", wp,
           "--force-ntheta", "11", "--eval-max", "120", "--shape-nblend", "3"]
    r = subprocess.run(cmd, capture_output=True, text=True, env=env,
                       cwd=str(tmp_path), timeout=600)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if "mkl" in low or "dll" in low or "libiomp" in low:
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(f"advanced demo failed: {r.stderr[-1500:]}")
    with open(os.path.join(str(tmp_path),
                           "demo_regcoil_fusion_advanced.json")) as f:
        d = json.load(f)
    # A. force = magnetic pressure, inboard-concentrated
    fr = d["force_stress"]
    assert 0.85 < fr["ratio_mean"] < 1.15, fr
    assert fr["inboard_over_outboard"] > 2.0, fr        # inboard stress peak
    # C. FOCUS: monotonic complexity, constraint-bound optimum
    fo = d["focus_standoff"]
    assert fo["complexity_monotonic_in_gap"] is True, fo
    assert fo["complexity_ratio_far_over_near"] > 5.0, fo
    # B. design runs on the real-format boundary to machine precision
    re_ = d["real_equilibrium"]
    assert re_ is not None and re_["nfp"] == 3, re_
    assert re_["bn_residual_rel"] < 1e-5, re_
    # D. FOCUS winding-SHAPE: the conformal winding is substantially simpler
    # (lower peak |grad psi|) than the circular one at the same min standoff
    sh = d["focus_shape"]
    assert sh["optimum_peak_grad_psi"] < sh["circular_peak_grad_psi"], sh
    assert sh["complexity_reduction_vs_circular"] > 0.15, sh   # measured ~34%


def test_regcoil_fusion_parallel_ops_inside_taskmanager():
    """Confirm (statically, no NGSolve) that EVERY NGSolve parallel op in the
    fusion demos' main() is lexically inside a `with TaskManager():` block --
    i.e. the parallelisation genuinely runs via TaskManager, not serially.

    tools/audit_taskmanager.py is only a per-FILE presence check ('does the file
    contain any TM wrap?'); it does NOT verify the wrap COVERS the parallel ops.
    This locks the coverage so a future edit that moves a Mesh/H1/Integrate/
    BilinearForm/etc. out of the TM block (-> serial) fails here."""
    import ast
    PARALLEL = {"H1", "HCurl", "HDiv", "L2", "VectorH1", "Integrate",
                "BilinearForm", "LinearForm", "GridFunction", "Norm"}
    for demo in (DEMO_REGCOIL, DEMO_REGCOIL_ADV):
        with open(demo, encoding="utf-8") as _f:
            tree = ast.parse(_f.read())
        main = next(n for n in ast.walk(tree)
                    if isinstance(n, ast.FunctionDef) and n.name == "main")
        tm_ranges = []
        for n in ast.walk(main):
            if isinstance(n, ast.With):
                for it in n.items:
                    c = it.context_expr
                    if isinstance(c, ast.Call) and (
                        (isinstance(c.func, ast.Name)
                         and c.func.id == "TaskManager")
                        or (isinstance(c.func, ast.Attribute)
                            and c.func.attr == "TaskManager")):
                        tm_ranges.append((n.lineno, n.end_lineno))
        assert tm_ranges, f"{os.path.basename(demo)}: main() has no TaskManager"

        def _inside(ln, _r=tm_ranges):
            return any(a <= ln <= b for a, b in _r)

        outside = []
        for n in ast.walk(main):
            if isinstance(n, ast.Call):
                fn = n.func
                nm = (fn.id if isinstance(fn, ast.Name)
                      else fn.attr if isinstance(fn, ast.Attribute) else "")
                is_par = nm in PARALLEL or (
                    nm == "Mesh" and n.args and isinstance(n.args[0], ast.Call))
                if is_par and not _inside(n.lineno):
                    outside.append((os.path.basename(demo), n.lineno, nm))
        assert not outside, (
            "NGSolve parallel op(s) OUTSIDE the TaskManager block (would run "
            f"SERIALLY): {outside}")


def _import_calc():
    if PANELS not in sys.path:
        sys.path.insert(0, PANELS)
    import calc_streamfunction as C
    return C


def test_harmonic_basis_is_harmonic():
    """Every solid-harmonic table entry is a HARMONIC polynomial (Laplacian 0)
    -- the precondition for it to be a valid current-free Bz component."""
    import numpy as np
    C = _import_calc()
    rng = np.random.default_rng(1)
    pts = rng.normal(size=(6, 3))
    h = 1e-4
    for (l, m), (nm, expr) in C._SOLID_HARMONICS.items():
        def f(q):
            return float(eval(expr, {"__builtins__": {}},
                              {"x": q[0], "y": q[1], "z": q[2]}))
        worst = 0.0
        for p in pts:
            lap = -6.0 * f(p)
            for k in range(3):
                for s in (+1.0, -1.0):
                    q = p.copy(); q[k] += s * h; lap += f(q)
            scale = abs(f(p)) + 1e-9
            worst = max(worst, abs(lap / h / h) / scale)
        assert worst < 1e-3, f"{nm} {l},{m} not harmonic (lap/scale={worst:.1e})"


def test_harmonic_target_expr_and_decompose_roundtrip():
    """--target-harmonic builds the right polynomial, and the decomposition
    recovers a pure harmonic (purity 1, machine-precision residual)."""
    import numpy as np
    C = _import_calc()
    expr, terms = C._harmonic_target_expr("Z2:1.0,Z:0.1")
    assert terms == [(2, 0, 1.0), (1, 0, 0.1)]
    assert "z*z - 0.5*(x*x + y*y)" in expr and "(z)" in expr
    rng = np.random.default_rng(2)
    pts = rng.normal(size=(400, 3)) * 0.05
    bz = eval(C._SOLID_HARMONICS[(2, 0)][1], {"__builtins__": {}},
              {"x": pts[:, 0], "y": pts[:, 1], "z": pts[:, 2]})
    d = C._harmonic_decompose(pts, bz, 3, target_terms=[(2, 0, 1.0)])
    assert d["dominant"]["name"] == "Z2"
    assert d["purity"] > 0.999
    assert d["residual_fraction"] < 1e-9
    # unknown harmonic name raises (No-Fallback)
    with pytest.raises(ValueError, match="unknown harmonic"):
        C._harmonic_lookup("Q9")


def test_harmonic_l4_forms_and_decompose():
    """l=4 extension: the table carries all 9 order-4 solid harmonics; the
    --target-harmonic parser accepts names, 'l=L,m=M', '(L,M)', ':coeff' and
    mixed sums (the comma INSIDE l=4,m=-4 / (4,-4) is rejoined, not mistaken
    for a term separator); and the decomposition DEPTH matters -- a pure l=4
    zonal is machine-precision pure at lmax=4 but unrepresentable at lmax=3."""
    import numpy as np
    C = _import_calc()
    # all 9 order-4 (l, m) present
    assert sorted(m for (l, m) in C._SOLID_HARMONICS if l == 4) == \
        [-4, -3, -2, -1, 0, 1, 2, 3, 4]
    # parser resolves name / l=,m= / parens / :coeff / mixed correctly
    assert C._harmonic_target_expr("Z4")[1] == [(4, 0, 1.0)]
    assert C._harmonic_target_expr("l=4,m=-4")[1] == [(4, -4, 1.0)]
    assert C._harmonic_target_expr("(4,-4)")[1] == [(4, -4, 1.0)]
    assert C._harmonic_target_expr("l=4,m=-4:0.5")[1] == [(4, -4, 0.5)]
    assert C._harmonic_target_expr("Z4:1.0,l=4,m=4:0.3")[1] == \
        [(4, 0, 1.0), (4, 4, 0.3)]
    # lmax fit space: 1+3+5+7+9 = 25 harmonics at l<=4, 16 at l<=3
    rng = np.random.default_rng(11)
    pts = rng.normal(size=(600, 3)) * 0.05
    assert len(C._solid_harmonic_matrix(pts, 4)[1]) == 25
    assert len(C._solid_harmonic_matrix(pts, 3)[1]) == 16
    bz = eval(C._SOLID_HARMONICS[(4, 0)][1], {"__builtins__": {}},
              {"x": pts[:, 0], "y": pts[:, 1], "z": pts[:, 2]})
    d4 = C._harmonic_decompose(pts, bz, 4, target_terms=[(4, 0, 1.0)])
    assert d4["dominant"]["name"] == "Z4" and d4["purity"] > 0.999
    assert d4["residual_fraction"] < 1e-9
    # l<=3 cannot represent a pure Z4 -> large residual (depth is load-bearing)
    assert C._harmonic_decompose(pts, bz, 3)["residual_fraction"] > 0.5

    # MALFORMED inputs FAIL LOUD but CLEARLY: a missing m ('l=4'), an empty
    # tuple slot ('(4,)') or a non-integer ('l=x,m=y') must raise a clean
    # "unknown harmonic" ValueError -- NOT a raw KeyError / int() ValueError.
    for bad in ("l=4", "(4,)", "(,4)", "l=x,m=y", "m=2,l=4"):
        with pytest.raises(ValueError, match="unknown harmonic"):
            C._harmonic_lookup(bad)
    # a well-FORMED but out-of-table pair gets the range message instead
    with pytest.raises(ValueError, match="not in the table"):
        C._harmonic_lookup("l=9,m=0")


def test_streamfunction_design_target_harmonic(sample_vols):
    """--target-harmonic X (Gx) designs and the achieved-Bz harmonic spectrum
    is dominated by X with high purity + a reported contaminant."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, None,
                  extra=["--target-harmonic", "X"])
    assert "error" not in r, f"calc error: {r.get('error')}"
    assert r["target_cf"] == "(1.0)*(x)"
    h = r["harmonics"]
    assert h["dominant"]["name"] == "X"
    assert h["purity"] > 0.99
    assert h["residual_fraction"] < 1e-2
    assert h["max_contaminant"] is not None
    # the spectrum lists per-(l,m) field fractions, sorted, X first
    assert h["spectrum"][0]["name"] == "X"


def test_streamfunction_target_harmonic_xor(sample_vols):
    """Giving both --target-cf and --target-harmonic is a loud error (fail-loud
    calc_main exits non-zero, the error JSON is still on stdout)."""
    coil, evalv = sample_vols
    r = _run_calc(coil, evalv, "x", extra=["--target-harmonic", "X"],
                  expect_error=True)
    assert "error" in r and "not both" in r["error"]


@pytest.fixture(scope="module")
def shielded_vols(tmp_path_factory):
    """Primary cylinder + shield cylinder + DSV sphere + external annular shell."""
    d = str(tmp_path_factory.mktemp("sf_shield"))
    fixture = os.path.join(HERE, "fixtures", "make_shielded_coil_vol.py")
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, fixture, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"shielded mesh gen failed (NGSolve/OCC unavailable?):\n"
                    f"{r.stderr[-600:]}")
    paths = {
        "primary": os.path.join(d, "primary_cyl.vol"),
        "shield":  os.path.join(d, "shield_cyl.vol"),
        "dsv":     os.path.join(d, "dsv.vol"),
        "ext":     os.path.join(d, "external.vol"),
    }
    if not all(os.path.exists(p) for p in paths.values()):
        pytest.skip("shielded .vol files not produced")
    return paths


def test_streamfunction_active_shielding(shielded_vols):
    """Turner (1986) active shielding: primary (inner) + shield (outer) coil
    designed JOINTLY so that primary+shield together produce the Gz target
    inside the DSV AND null the stray field outside the shield.  The external
    null region is a LARGE full-length annular shell (fixture), so the
    shielding is GENUINE -- asserts the HONEST, generalising behaviour:

      (1) DSV homogeneity preserved (the shield does not spoil the target),
      (2) the HONEST stray (combined field at INDEPENDENT external measure
          points, NOT the constraint vertices) is small (genuine shielding --
          an unshielded primary-only coil sees ~1.6 at these points),
      (3) stray_rms is the independent metric, distinct from the circular
          constraint-point residual stray_fit_rms,
      (4) both primary and shield carry non-trivial current."""
    vols = shielded_vols
    common = [
        "--target-harmonic", "Z",
        "--regularize",      "h1",
        "--confine",         "abe",
        "--eval-max",        "800",
    ]
    # SHIELDED design (primary + shield, joint solve)
    d = _run_calc(vols["primary"], vols["dsv"], None, extra=common + [
        "--shield-vol",      vols["shield"],
        "--shield-eval-vol", vols["ext"],
        "--shield-weight",   "1.0",
    ])
    # (Unshielded primary-only stray at these independent points is ~1.6;
    # the shielded design measures ~0.02-0.05 -> ~30-86x reduction.  The calc
    # does not report the unshielded stray, so the self-contained locks are:
    # stray is small AND it is the independent metric, not the circular one.)
    assert "error" not in d, f"calc error: {d.get('error')}"
    assert d["method"] == "design"
    assert d.get("shielded") is True

    # (1) DSV homogeneity preserved
    assert d["homogeneity_rms"] < 1.0e-2, \
        f"DSV homogeneity too large: {d['homogeneity_rms']}"

    # (2) HONEST stray is small -- genuine shielding (unshielded ~1.6 here;
    # measured shielded ~0.026).  Generous upper band for mesh variation.
    assert d["stray_rms"] < 0.15, \
        f"shielded stray too large (no real shielding?): {d['stray_rms']}"

    # (3) the reported stray is the INDEPENDENT measure (e_mpts), distinct
    # from the circular constraint-point residual.  Both are present.
    assert "stray_fit_rms" in d and d["n_external_measure"] > 0
    assert d["stray_rms"] >= d["stray_fit_rms"], \
        "independent stray should be >= the constraint-point fit residual"

    # (4) Both coils carry current
    assert d["peak_J_primary"] > 1e3 and d["peak_J_shield"] > 1e3
    assert d["ndof_free_primary"] > 0 and d["ndof_free_shield"] > 0
    assert d["shield_weight"] == 1.0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
