"""Golden test for --pin-tiling (the DENSE BUBBLE-TILING pin coil) and the
'bubble' greedy dictionary.

Bubble-tiling drops small equal-current circulating loops over the coil surface
with DENSITY proportional to |K| = |grad psi| (clearance radius r ~ 1/sqrt(|K|))
and sizes each loop to its bubble -- a many-turn, manufacturable alternative to
long iso-contours.

HONEST regime: isolated equal-current bubble loops reproduce the target under
INDEPENDENT currents (loops_homogeneity_rms -- the driven pin / shim ARRAY
regime) but NOT under one series current (wire_homogeneity_rms), because isolated
loops do not tile-cancel into the surface current the way psi iso-contours do.
The test therefore locks the ARRAY metric (loops_homogeneity_rms small) and only
checks that the single-wire metric is present, not that it is small.

The .vol meshes are gitignored, regenerated by ``fixtures/make_streamfunction_vol.py``.
Calc runs in a SUBPROCESS; SKIPS on the LAB MKL/Qt DLL shadow.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
CALC = os.path.join(PANELS, "calc_streamfunction.py")
FIXTURE = os.path.join(HERE, "fixtures", "make_streamfunction_vol.py")


@pytest.fixture(scope="module")
def sample_vols(tmp_path_factory):
    d = str(tmp_path_factory.mktemp("sf_pintile_vols"))
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run([sys.executable, FIXTURE, d],
                       capture_output=True, text=True, env=env, timeout=600)
    if r.returncode != 0:
        pytest.skip(f"sample mesh gen failed:\n{r.stderr[-600:]}")
    coil = os.path.join(d, "coil_cyl_surf.vol")
    evalv = os.path.join(d, "eval_dsv.vol")
    if not (os.path.exists(coil) and os.path.exists(evalv)):
        pytest.skip("sample .vol files not produced")
    return coil, evalv


def _run(coil, evalv, extra):
    cmd = [sys.executable, CALC, "--coil-vol", coil, "--eval-vol", evalv,
           "--order", "1", "--target-cf", "x", "--method", "manufacture",
           "--eval-max", "20", "--confine", "off"] + extra
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=900)
    if r.returncode != 0:
        low = (r.stderr or "").lower()
        if ("mkl" in low or "dll" in low or "libiomp" in low
                or (not r.stderr.strip() and abs(r.returncode) > 1000000)):
            pytest.skip("NGSolve/MKL subprocess env issue (LAB pytest)")
        raise AssertionError(f"calc failed (rc={r.returncode}):\n{r.stderr[-1500:]}")
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    assert lines, f"no stdout:\n{r.stderr[-1500:]}"
    return json.loads(lines[-1])


def test_pin_tiling_array_regime(sample_vols):
    """--pin-tiling lays many equal-current bubble loops; as a DRIVEN ARRAY
    (independent currents) it reproduces the target near-exactly."""
    coil, evalv = sample_vols
    r = _run(coil, evalv, ["--pin-tiling", "--pin-tiling-pins", "60"])
    assert "error" not in r, f"pin-tiling error: {r.get('error')}"
    assert r["pin_tiling"] is True
    assert r["n_pin_loops"] >= 20, f"too few bubble loops: {r['n_pin_loops']}"
    assert r["n_loops"] == r["n_pin_loops"]
    # closed loops -> no spurious open-contour count
    assert r["n_open_contours"] == 0
    # ARRAY regime (independent currents): hits the constraint points tightly
    assert r["loops_homogeneity_rms"] < 0.05, (
        f"array-regime field not reproduced: "
        f"loops_homogeneity_rms={r['loops_homogeneity_rms']}")
    # single-wire metric is reported (honest -- not required to be small)
    assert "wire_homogeneity_rms" in r
    assert "pin_tiling_note" in r


def test_pin_tiling_density_tracks_pins(sample_vols):
    """More requested pins -> more (or equal) bubble loops land (the k-bisection
    targets the requested count)."""
    coil, evalv = sample_vols
    lo = _run(coil, evalv, ["--pin-tiling", "--pin-tiling-pins", "30"])
    hi = _run(coil, evalv, ["--pin-tiling", "--pin-tiling-pins", "80"])
    assert "error" not in lo and "error" not in hi
    assert hi["n_pin_loops"] >= lo["n_pin_loops"], (
        f"pin count did not grow: {lo['n_pin_loops']} -> {hi['n_pin_loops']}")


def test_greedy_bubble_dictionary(sample_vols):
    """The 'bubble' greedy dictionary (density ~ |grad psi| pins) feeds the same
    monotone greedy machinery as contour/pin."""
    coil, evalv = sample_vols
    r = _run(coil, evalv, ["--greedy-turns", "8", "--greedy-dict", "bubble",
                           "--pin-tiling-pins", "60"])
    assert "error" not in r, f"greedy bubble error: {r.get('error')}"
    assert r["greedy_dict"] == "bubble"
    assert r.get("greedy_turns") is True
    tr = r["greedy_trace"]
    assert 1 <= len(tr) <= 8
    for i in range(1, len(tr)):
        assert tr[i]["rms"] <= tr[i - 1]["rms"] + 1e-9, "greedy not monotone"
    assert tr[-1]["rms"] < tr[0]["rms"], "greedy made no progress"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
