function result = validate_ltspice_coil_geometry_resonance
%VALIDATE_LTSPICE_COIL_GEOMETRY_RESONANCE Freeze fixed-C geometry tuning.
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(repoRoot,"matlab"));
resultDirectory = fullfile(repoRoot,"validation_test","optimization");
result = radia.ltspice.runCoilGeometryResonanceOptimizationDemo( ...
    NumTrials=36,Seed=42,ResetStudy=true, ...
    OutputDirectory="C:\temp\radia_coil_geometry_validation", ...
    StoragePath="C:\temp\radia_coil_geometry_validation\study.mat", ...
    ResultPath=fullfile(resultDirectory, ...
        "results_ltspice_coil_geometry_resonance_20260806.json"), ...
    PlotPath=fullfile(resultDirectory, ...
        "ltspice_coil_geometry_resonance_20260806.png"));
gateNames = fieldnames(result.gates);
for index = 1:numel(gateNames)
    if ~result.gates.(gateNames{index})
        error("radia:validation:CoilGeometryGate", ...
            "Coil geometry resonance gate failed: %s",gateNames{index});
    end
end
fprintf("LTSPICE_COIL_GEOMETRY_OK radius=%.6f mm " + ...
    "L_eff=%.9g H f=%.6f Hz inner_evals=%d trials=%d\n", ...
    result.best.radius_m*1e3,result.best.effective_inductance_H, ...
    result.best.frequency_Hz,result.best.frequency_evaluation_count, ...
    result.search.completed_trials);
end
