function result = validate_ltspice_rlc_resonance_ac
%VALIDATE_LTSPICE_RLC_RESONANCE_AC Freeze the frequency-domain demo.
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(repoRoot, "matlab"));
resultDirectory = fullfile(repoRoot, "validation_test", "optimization");
result = radia.ltspice.runRLCResonanceOptimizationDemo( ...
    NumTrials=36, Seed=42, ResetStudy=true, ...
    OutputDirectory="C:\temp\radia_ltspice_rlc_validation", ...
    StoragePath="C:\temp\radia_ltspice_rlc_validation\study.mat", ...
    ResultPath=fullfile(resultDirectory, ...
        "results_ltspice_rlc_ac_resonance_20260806.json"), ...
    PlotPath=fullfile(resultDirectory, ...
        "ltspice_rlc_ac_resonance_20260806.png"), ...
    RequireTimeDomainCrossCheck=true);
gateNames = fieldnames(result.gates);
for index = 1:numel(gateNames)
    if ~result.gates.(gateNames{index})
        error("radia:validation:LTspiceRLCGate", ...
            "LTspice RLC AC gate failed: %s", gateNames{index});
    end
end
fprintf("LTSPICE_RLC_AC_OPTIMIZATION_OK C=%.9g F f=%.6f Hz trials=%d\n", ...
    result.best.capacitance_F, ...
    result.best.measured_ac_resonance_frequency_Hz, ...
    result.search.completed_trials);
end
