function report = validate_matlab_adjoint_quality(options)
%VALIDATE_MATLAB_ADJOINT_QUALITY Cross-check MMA and SQP on an adjoint model.
%   The state equation mimics a material-dependent electromagnetic operator.
%   Both optimizers receive the same analytic state/adjoint derivative and a
%   normalized material-volume inequality.
arguments
    options.OutputFile (1,1) string=""
end
root=fileparts(fileparts(fileparts(mfilename("fullpath"))));
matlabPath=fullfile(root,"matlab");
wasPresent=any(strcmpi(string(strsplit(path,pathsep)),string(matlabPath)));
if ~wasPresent, addpath(matlabPath); end
cleanup=onCleanup(@()localRestorePath(matlabPath,wasPresent));
if strlength(options.OutputFile)==0
    options.OutputFile=fullfile(fileparts(mfilename("fullpath")), ...
        "validation_matlab_adjoint_quality_summary.json");
end

problem=localProblem();
evaluate=@(design)localEvaluate(design,problem);
initial=0.35*ones(problem.design_count,1);
initialEvaluation=evaluate(initial);
gradientCheck=radia.topopt.checkAdjointGradient(initial,evaluate, ...
    RelativeStep=2e-6,RelativeTolerance=2e-5,AbsoluteTolerance=1e-9);

timer=tic;
mma=radia.topopt.optimizeAdjoint(initial,evaluate,Solver="mma", ...
    LowerBounds=problem.lower,UpperBounds=problem.upper,MoveLimit=0.15, ...
    MaxIterations=180,OptimalityTolerance=2e-6, ...
    ConstraintTolerance=1e-8,StepTolerance=5e-6);
mmaElapsed=toc(timer);
timer=tic;
sqp=radia.topopt.optimizeAdjoint(initial,evaluate,Solver="sqp", ...
    LowerBounds=problem.lower,UpperBounds=problem.upper, ...
    MaxIterations=120,MaxFunctionEvaluations=3000, ...
    OptimalityTolerance=1e-9,ConstraintTolerance=1e-9,StepTolerance=1e-11);
sqpElapsed=toc(timer);

objectiveScale=max(1,abs(sqp.objective));
objectiveGap=abs(mma.objective-sqp.objective)/objectiveScale;
mmaDesignError=norm(mma.design-problem.target_design,inf);
sqpDesignError=norm(sqp.design-problem.target_design,inf);
gates=struct( ...
    "adjoint_directional_check",gradientCheck.passed, ...
    "mma_converged",mma.converged, ...
    "sqp_converged",sqp.converged, ...
    "mma_feasible",max([0;mma.constraints])<=1e-7, ...
    "sqp_feasible",max([0;sqp.constraints])<=1e-8, ...
    "mma_sqp_relative_objective_gap_below_1e_5",objectiveGap<=1e-5, ...
    "mma_target_design_error_below_5e_3",mmaDesignError<=5e-3, ...
    "sqp_target_design_error_below_5e_4",sqpDesignError<=5e-4);
gates.all_passed=all(struct2array(gates));

report=struct( ...
    "schema","radia.validation.matlab-adjoint-quality.v1", ...
    "generated_at_utc",string(datetime("now","TimeZone","UTC", ...
        "Format","yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
    "hostname",localHostname(),"matlab_version",string(version), ...
    "matlab_release",string(version("-release")),"platform",string(computer), ...
    "design_count",problem.design_count, ...
    "initial_objective",initialEvaluation.objective, ...
    "gradient_check",struct( ...
        "passed",gradientCheck.passed, ...
        "maximum_objective_error",max(gradientCheck.history.ObjectiveError), ...
        "maximum_constraint_error",max(gradientCheck.history.ConstraintError), ...
        "evaluation_count",gradientCheck.evaluation_count), ...
    "mma",localSummary(mma,mmaElapsed,mmaDesignError), ...
    "sqp",localSummary(sqp,sqpElapsed,sqpDesignError), ...
    "relative_objective_gap",objectiveGap, ...
    "quality_gates",gates, ...
    "timing_scope","LAB smoke observation; not a published performance benchmark");
localWriteJson(options.OutputFile,report);
fprintf("MATLAB adjoint quality report: %s\n",options.OutputFile);
clear cleanup
end

function problem=localProblem()
n=6;
target=linspace(0.25,0.75,n).';
stiffness=diag(4*ones(n,1))+diag(-ones(n-1,1),1)+diag(-ones(n-1,1),-1);
rhs=linspace(1,1.5,n).';
targetState=(stiffness+diag(0.5+2*target.^3))\rhs;
problem=struct("design_count",n,"target_design",target, ...
    "stiffness",stiffness,"rhs",rhs,"target_state",targetState, ...
    "regularization",0.01,"volume_max",0.5*n, ...
    "lower",0.05*ones(n,1),"upper",0.95*ones(n,1));
end

function evaluation=localEvaluate(design,problem)
operator=problem.stiffness+diag(0.5+2*design.^3);
state=operator\problem.rhs;
residual=state-problem.target_state;
adjoint=operator'\residual;
gradient=-6*design.^2.*state.*adjoint+ ...
    2*problem.regularization*(design-problem.target_design);
objective=0.5*(residual'*residual)+ ...
    problem.regularization*sum((design-problem.target_design).^2);
evaluation=struct("objective",objective,"gradient",gradient, ...
    "constraints",sum(design)/problem.volume_max-1, ...
    "constraint_jacobian",ones(problem.design_count,1)/problem.volume_max, ...
    "state",state,"adjoint",adjoint);
end

function summary=localSummary(result,elapsed,designError)
summary=struct("converged",result.converged,"exitflag",result.exitflag, ...
    "objective",result.objective,"max_constraint",max([0;result.constraints]), ...
    "target_design_error_inf",designError, ...
    "iterations",result.output.iterations, ...
    "final_step_inf",result.history.StepInfinity(end), ...
    "final_first_order_optimality",result.history.FirstOrderOptimality(end), ...
    "evaluation_count",result.evaluation_count,"elapsed_s",elapsed);
end

function localWriteJson(outputPath,value)
file=fopen(outputPath,"w","n","UTF-8");
if file<0
    error("radia:validation:AdjointWrite", ...
        "Cannot write MATLAB adjoint validation report: %s",outputPath);
end
cleanup=onCleanup(@()fclose(file));
count=fprintf(file,"%s\n",jsonencode(value,PrettyPrint=true));
if count<=0
    error("radia:validation:AdjointWrite", ...
        "Cannot write MATLAB adjoint validation report: %s",outputPath);
end
clear cleanup
end

function localRestorePath(matlabPath,wasPresent)
if ~wasPresent && any(strcmpi(string(strsplit(path,pathsep)),string(matlabPath)))
    rmpath(matlabPath);
end
end

function name=localHostname()
name=string(getenv("COMPUTERNAME"));
if strlength(name)==0
    [status,output]=system("hostname");
    if status==0, name=strip(string(output)); end
end
end
