function result = validate_rlc_resonance_simulink
%VALIDATE_RLC_RESONANCE_SIMULINK Run and freeze the RLC optimization demo.
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(repoRoot, "matlab"));
resultDirectory = fullfile(repoRoot, "validation_test", "optimization");
result = radia.simulink.runRLCResonanceOptimizationDemo( ...
    NumTrials=36, Seed=42, RebuildModel=true, ResetStudy=true, ...
    ModelFile=fullfile(repoRoot, "matlab", "radia_rlc_resonance_plant.slx"), ...
    OutputDirectory="C:\temp\radia_rlc_resonance_validation", ...
    StoragePath="C:\temp\radia_rlc_resonance_validation\study.mat", ...
    ResultPath=fullfile(resultDirectory, ...
        "results_rlc_resonance_simulink_20260806.json"), ...
    PlotPath=fullfile(resultDirectory, ...
        "rlc_resonance_simulink_20260806.png"));
gateNames = fieldnames(result.gates);
for index = 1:numel(gateNames)
    if ~result.gates.(gateNames{index})
        error("radia:validation:RLCResonanceGate", ...
            "RLC resonance gate failed: %s", gateNames{index});
    end
end
fprintf("RLC_RESONANCE_OPTIMIZATION_OK C=%.9g F f=%.6f Hz trials=%d\n", ...
    result.best.capacitance_F, ...
    result.best.measured_ringdown_frequency_Hz, ...
    result.search.completed_trials);
end
