"""
Convert catalog.json (PDF metadata batch index) into per-subpackage
knowledge modules suitable for radia-mcp MCP servers.

For each radia-mcp subpackage that appears in the catalog, generate:
  packages/radia-mcp/src/radia_mcp/<subpackage>/bibliography_index_knowledge.py

with a structured string containing:
  - Per-PDF catalog entry: filename, title, authors, abstract excerpt,
    page count, scanned-PDF flag
  - Searchable by keyword

The module exposes  get_bibliography_index(query: str = "")  function:
  - query = ""       → return the full catalog
  - query = "keyword" → filter entries by keyword match in title/abstract
  - query = "scanned" → return only scanned PDFs (for OCR audit)
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any


def _relativize(path: str) -> str:
    """Strip the machine-specific corpus-root prefix from a catalog path.

    Catalog ``relative_path`` values arrive as absolute NAS paths
    (e.g. ``W:\\03_文献・論文\\00_電磁界解析\\...``).  For a portable,
    publishable repo we keep only the part relative to the literature
    library root so no local drive layout is embedded in the package.
    """
    if not path:
        return path
    marker = "03_文献・論文\\"
    i = path.find(marker)
    if i != -1:
        return path[i + len(marker):]
    if len(path) > 2 and path[1] == ":":   # bare drive prefix fallback
        return path[3:]
    return path


def format_entry(entry: dict[str, Any]) -> str:
    """Format one PDF metadata entry as readable text."""
    fn = entry.get("filename", "?")
    title = entry.get("title", "?").strip()
    authors = (entry.get("authors") or "").strip()
    abstract = (entry.get("abstract_excerpt") or "").strip()
    pages = entry.get("page_count", 0)
    scanned = entry.get("is_scanned", False)

    parts = [f"### {fn}"]
    parts.append(f"**Title**: {title}")
    if authors:
        parts.append(f"**Authors**: {authors[:200]}")
    parts.append(f"**Pages**: {pages}" + ("  [SCANNED — OCR limited]" if scanned else ""))
    if abstract:
        parts.append(f"**Abstract**: {abstract[:600]}")
    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", required=True, help="catalog.json from pdf_batch_indexer")
    parser.add_argument("--radia-mcp-src", required=True,
                        help="Path to packages/radia-mcp/src/radia_mcp")
    args = parser.parse_args()

    cat_path = Path(args.catalog)
    src_path = Path(args.radia_mcp_src)

    with cat_path.open("r", encoding="utf-8") as f:
        entries = json.load(f)
    print(f"Loaded {len(entries)} entries from {cat_path}")

    # Group by subpackage
    by_sub: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for e in entries:
        sub = e.get("subpackage", "_misc")
        by_sub[sub].append(e)

    # Subpackages that exist in radia_mcp/
    valid_subpackages = set()
    for d in src_path.iterdir():
        if d.is_dir() and (d / "__init__.py").exists():
            valid_subpackages.add(d.name)

    # Write bibliography_index_knowledge.py per subpackage
    for sub, sub_entries in sorted(by_sub.items()):
        if sub.startswith("_") or sub not in valid_subpackages:
            print(f"  SKIP: {sub} ({len(sub_entries)} entries) — no matching subpackage dir")
            continue

        # Sort entries: non-scanned first, then alphabetically
        sub_entries.sort(key=lambda e: (e.get("is_scanned", False), e.get("filename", "")))

        # Build module content
        n = len(sub_entries)
        # Build the catalog as a JSON string parsed at module load.
        # This sidesteps Python-vs-JSON boolean/literal differences.
        slim_entries = []
        for e in sub_entries:
            keys = ["filename", "title", "authors", "abstract_excerpt",
                    "page_count", "is_scanned", "relative_path"]
            slim = {k: e.get(k, "") for k in keys}
            slim["relative_path"] = _relativize(slim.get("relative_path", ""))
            slim_entries.append(slim)
        catalog_json = json.dumps(slim_entries, ensure_ascii=False, indent=1)
        # Triple-quoted strings can't contain triple-double-quotes literally;
        # JSON output doesn't contain triple-quotes so this is safe.
        out_lines = [
            f'"""Bibliography INDEX for radia_mcp.{sub}.',
            '',
            f"Auto-generated catalog of {n} PDF references from the Sugahara",
            "Lab literature library.  Catalog paths are relative to the",
            "corpus root (configure the root via RADIA_LIT_ROOT).",
            "",
            "Generated by tools/catalog_to_knowledge.py from catalog.json",
            "(pdf_batch_indexer output).  Re-run when new PDFs are added.",
            "",
            "Use:",
            f'    from radia_mcp.{sub}.bibliography_index_knowledge import get_bibliography_index',
            '    print(get_bibliography_index("kelvin"))    # filter',
            '    print(get_bibliography_index(""))          # full',
            '    print(get_bibliography_index("__scanned__"))  # scanned PDFs only',
            '"""',
            '',
            'from __future__ import annotations',
            'import json as _json',
            '',
            '_CATALOG_JSON = r"""',
            catalog_json,
            '"""',
            '',
            'CATALOG_ENTRIES = _json.loads(_CATALOG_JSON)',
        ]
        out_lines.append("")
        out_lines.append("")
        out_lines.append("def get_bibliography_index(query: str = \"\") -> str:")
        out_lines.append('    """Return formatted catalog entries.')
        out_lines.append('')
        out_lines.append('    Args:')
        out_lines.append('        query: empty string → all entries.  "__scanned__" → only')
        out_lines.append('               scanned PDFs.  Otherwise, case-insensitive substring')
        out_lines.append('               match in title + authors + abstract + filename.')
        out_lines.append('    """')
        out_lines.append('    q = query.strip().lower()')
        out_lines.append('    if q == "__scanned__":')
        out_lines.append('        sel = [e for e in CATALOG_ENTRIES if e.get("is_scanned")]')
        out_lines.append('    elif q == "":')
        out_lines.append('        sel = CATALOG_ENTRIES')
        out_lines.append('    else:')
        out_lines.append('        sel = []')
        out_lines.append('        for e in CATALOG_ENTRIES:')
        out_lines.append('            haystack = " ".join(str(e.get(k, "")) for k in')
        out_lines.append('                ("filename", "title", "authors", "abstract_excerpt")).lower()')
        out_lines.append('            if q in haystack:')
        out_lines.append('                sel.append(e)')
        out_lines.append('')
        out_lines.append('    if not sel:')
        out_lines.append('        return f"No catalog entries match query: {query!r}\\n"')
        out_lines.append('')
        out_lines.append('    lines = [f"## radia_mcp bibliography index — {len(sel)} entries"]')
        out_lines.append('    if query and q != "__scanned__":')
        out_lines.append('        lines.append(f"(filtered by: {query!r})")')
        out_lines.append('    lines.append("")')
        out_lines.append('    for e in sel:')
        out_lines.append('        fn = e.get("filename", "?")')
        out_lines.append('        title = e.get("title", "?")')
        out_lines.append('        a = e.get("authors", "")')
        out_lines.append('        pages = e.get("page_count", 0)')
        out_lines.append('        scanned = e.get("is_scanned", False)')
        out_lines.append('        abs_text = e.get("abstract_excerpt", "")')
        out_lines.append('        lines.append(f"### {fn}")')
        out_lines.append('        lines.append(f"**Title**: {title}")')
        out_lines.append('        if a:')
        out_lines.append('            lines.append(f"**Authors**: {a[:200]}")')
        out_lines.append('        flag = "  [SCANNED — OCR limited]" if scanned else ""')
        out_lines.append('        lines.append(f"**Pages**: {pages}{flag}")')
        out_lines.append('        if abs_text:')
        out_lines.append('            lines.append(f"**Abstract**: {abs_text[:500]}")')
        out_lines.append('        lines.append("")')
        out_lines.append('    return "\\n".join(lines)')

        out = "\n".join(out_lines) + "\n"

        out_file = src_path / sub / "bibliography_index_knowledge.py"
        out_file.write_text(out, encoding="utf-8")
        print(f"  WROTE {n:5d} entries → {out_file}")

    # Misc / unclassified report
    n_misc = sum(len(es) for sub, es in by_sub.items() if sub.startswith("_"))
    print()
    print(f"Unclassified (_misc, _scanned_etc): {n_misc} entries — review needed")


if __name__ == "__main__":
    main()
