// q2_henrotte_generated.hpp — AUTO-GENERATED by scripts/codegen_q2_henrotte.py
// Source JSON: axifem/quad_q2_henrotte_matrices.json
// DO NOT EDIT MANUALLY. Re-run the codegen if the JSON changes.
//
// Q2 Henrotte axisymmetric element matrices in MONOMIAL coefficient basis:
//   general: {1, s, s^2, z, s*z, s^2*z, z^2, s*z^2, s^2*z^2}    (9 DOFs)
//   axis   : {s, s^2, s*z, s^2*z, s*z^2, s^2*z^2}                (6 DOFs, sa=0)
// where s = r^2.
//
// Stiffness convention (matches axifem/axifem_quad_q2.py):
//   K_phi[i, j] = Integrate( dM_i/ds dM_j/ds / (2 pi muZ)
//                          + dM_i/dz dM_j/dz / (8 pi muR s) ) ds dz
// Mass convention:
//   M_phi[i, j] = sigma / (8 pi^2) * Integrate( M_i M_j / s ) ds dz
//
// Caller transforms to V-DOF (psi = 2 pi r * A_phi at each node):
//   inv_V_phi  = inv(Vandermonde)
//   M_psi      = T * inv_V^T * M_phi * inv_V * T,    T = diag(2 pi r_node)
//
// Index layout for the flat outputs is row-major (entry index = row*N + col),
// where N = 9 (general) or N = 6 (axis-touching).

#ifndef RADIA_AXIFEM_Q2_HENROTTE_GENERATED_HPP
#define RADIA_AXIFEM_Q2_HENROTTE_GENERATED_HPP

#include <cmath>

namespace axifem {
namespace q2_henrotte {

inline constexpr double PI = 3.14159265358979323846;

inline void KPhiGeneral(double sa, double sb, double za, double zb, double muR, double muZ, double K[81])
{
    using std::log;
    K[0] = 0.0;
    K[1] = 0.0;
    K[2] = 0.0;
    K[3] = 0.0;
    K[4] = 0.0;
    K[5] = 0.0;
    K[6] = 0.0;
    K[7] = 0.0;
    K[8] = 0.0;
    K[9] = 0.0;
    K[10] = sa*za/(PI*muZ) - sa*zb/(PI*muZ) - sb*za/(PI*muZ) + sb*zb/(PI*muZ);
    K[11] = (sa*sa)*za/(PI*muZ) - (sa*sa)*zb/(PI*muZ) - (sb*sb)*za/(PI*muZ) + (sb*sb)*zb/(PI*muZ);
    K[12] = 0.0;
    K[13] = (1.0/2.0)*sa*(za*za)/(PI*muZ) - 1.0/2.0*sa*(zb*zb)/(PI*muZ) - 1.0/2.0*sb*(za*za)/(PI*muZ) + (1.0/2.0)*sb*(zb*zb)/(PI*muZ);
    K[14] = (1.0/2.0)*(sa*sa)*(za*za)/(PI*muZ) - 1.0/2.0*(sa*sa)*(zb*zb)/(PI*muZ) - 1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[15] = 0.0;
    K[16] = (1.0/3.0)*sa*(za*za*za)/(PI*muZ) - 1.0/3.0*sa*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ);
    K[17] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[18] = 0.0;
    K[19] = (sa*sa)*za/(PI*muZ) - (sa*sa)*zb/(PI*muZ) - (sb*sb)*za/(PI*muZ) + (sb*sb)*zb/(PI*muZ);
    K[20] = (4.0/3.0)*(sa*sa*sa)*za/(PI*muZ) - 4.0/3.0*(sa*sa*sa)*zb/(PI*muZ) - 4.0/3.0*(sb*sb*sb)*za/(PI*muZ) + (4.0/3.0)*(sb*sb*sb)*zb/(PI*muZ);
    K[21] = 0.0;
    K[22] = (1.0/2.0)*(sa*sa)*(za*za)/(PI*muZ) - 1.0/2.0*(sa*sa)*(zb*zb)/(PI*muZ) - 1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[23] = (2.0/3.0)*(sa*sa*sa)*(za*za)/(PI*muZ) - 2.0/3.0*(sa*sa*sa)*(zb*zb)/(PI*muZ) - 2.0/3.0*(sb*sb*sb)*(za*za)/(PI*muZ) + (2.0/3.0)*(sb*sb*sb)*(zb*zb)/(PI*muZ);
    K[24] = 0.0;
    K[25] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[26] = (4.0/9.0)*(sa*sa*sa)*(za*za*za)/(PI*muZ) - 4.0/9.0*(sa*sa*sa)*(zb*zb*zb)/(PI*muZ) - 4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[27] = 0.0;
    K[28] = 0.0;
    K[29] = 0.0;
    K[30] = -1.0/4.0*za*log(sb/sa)/(PI*muR) + (1.0/4.0)*zb*log(sb/sa)/(PI*muR);
    K[31] = (1.0/4.0)*sa*za/(PI*muR) - 1.0/4.0*sa*zb/(PI*muR) - 1.0/4.0*sb*za/(PI*muR) + (1.0/4.0)*sb*zb/(PI*muR);
    K[32] = (1.0/8.0)*(sa*sa)*za/(PI*muR) - 1.0/8.0*(sa*sa)*zb/(PI*muR) - 1.0/8.0*(sb*sb)*za/(PI*muR) + (1.0/8.0)*(sb*sb)*zb/(PI*muR);
    K[33] = -1.0/4.0*(za*za)*log(sb/sa)/(PI*muR) + (1.0/4.0)*(zb*zb)*log(sb/sa)/(PI*muR);
    K[34] = (1.0/4.0)*sa*(za*za)/(PI*muR) - 1.0/4.0*sa*(zb*zb)/(PI*muR) - 1.0/4.0*sb*(za*za)/(PI*muR) + (1.0/4.0)*sb*(zb*zb)/(PI*muR);
    K[35] = (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[36] = 0.0;
    K[37] = (1.0/2.0)*sa*(za*za)/(PI*muZ) - 1.0/2.0*sa*(zb*zb)/(PI*muZ) - 1.0/2.0*sb*(za*za)/(PI*muZ) + (1.0/2.0)*sb*(zb*zb)/(PI*muZ);
    K[38] = (1.0/2.0)*(sa*sa)*(za*za)/(PI*muZ) - 1.0/2.0*(sa*sa)*(zb*zb)/(PI*muZ) - 1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[39] = (1.0/4.0)*sa*za/(PI*muR) - 1.0/4.0*sa*zb/(PI*muR) - 1.0/4.0*sb*za/(PI*muR) + (1.0/4.0)*sb*zb/(PI*muR);
    K[40] = (1.0/3.0)*sa*(za*za*za)/(PI*muZ) - 1.0/3.0*sa*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ) + (1.0/8.0)*(sa*sa)*za/(PI*muR) - 1.0/8.0*(sa*sa)*zb/(PI*muR) - 1.0/8.0*(sb*sb)*za/(PI*muR) + (1.0/8.0)*(sb*sb)*zb/(PI*muR);
    K[41] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*za/(PI*muR) - 1.0/12.0*(sa*sa*sa)*zb/(PI*muR) - 1.0/12.0*(sb*sb*sb)*za/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*zb/(PI*muR);
    K[42] = (1.0/4.0)*sa*(za*za)/(PI*muR) - 1.0/4.0*sa*(zb*zb)/(PI*muR) - 1.0/4.0*sb*(za*za)/(PI*muR) + (1.0/4.0)*sb*(zb*zb)/(PI*muR);
    K[43] = (1.0/4.0)*sa*(za*za*za*za)/(PI*muZ) - 1.0/4.0*sa*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*sb*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*sb*(zb*zb*zb*zb)/(PI*muZ) + (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[44] = (1.0/4.0)*(sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/4.0*(sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*(za*za)/(PI*muR) - 1.0/12.0*(sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[45] = 0.0;
    K[46] = (1.0/2.0)*(sa*sa)*(za*za)/(PI*muZ) - 1.0/2.0*(sa*sa)*(zb*zb)/(PI*muZ) - 1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[47] = (2.0/3.0)*(sa*sa*sa)*(za*za)/(PI*muZ) - 2.0/3.0*(sa*sa*sa)*(zb*zb)/(PI*muZ) - 2.0/3.0*(sb*sb*sb)*(za*za)/(PI*muZ) + (2.0/3.0)*(sb*sb*sb)*(zb*zb)/(PI*muZ);
    K[48] = (1.0/8.0)*(sa*sa)*za/(PI*muR) - 1.0/8.0*(sa*sa)*zb/(PI*muR) - 1.0/8.0*(sb*sb)*za/(PI*muR) + (1.0/8.0)*(sb*sb)*zb/(PI*muR);
    K[49] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*za/(PI*muR) - 1.0/12.0*(sa*sa*sa)*zb/(PI*muR) - 1.0/12.0*(sb*sb*sb)*za/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*zb/(PI*muR);
    K[50] = (4.0/9.0)*(sa*sa*sa)*(za*za*za)/(PI*muZ) - 4.0/9.0*(sa*sa*sa)*(zb*zb*zb)/(PI*muZ) - 4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ) + (1.0/16.0)*(sa*sa*sa*sa)*za/(PI*muR) - 1.0/16.0*(sa*sa*sa*sa)*zb/(PI*muR) - 1.0/16.0*(sb*sb*sb*sb)*za/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*zb/(PI*muR);
    K[51] = (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[52] = (1.0/4.0)*(sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/4.0*(sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*(za*za)/(PI*muR) - 1.0/12.0*(sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[53] = (1.0/3.0)*(sa*sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/16.0)*(sa*sa*sa*sa)*(za*za)/(PI*muR) - 1.0/16.0*(sa*sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/16.0*(sb*sb*sb*sb)*(za*za)/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*(zb*zb)/(PI*muR);
    K[54] = 0.0;
    K[55] = 0.0;
    K[56] = 0.0;
    K[57] = -1.0/4.0*(za*za)*log(sb/sa)/(PI*muR) + (1.0/4.0)*(zb*zb)*log(sb/sa)/(PI*muR);
    K[58] = (1.0/4.0)*sa*(za*za)/(PI*muR) - 1.0/4.0*sa*(zb*zb)/(PI*muR) - 1.0/4.0*sb*(za*za)/(PI*muR) + (1.0/4.0)*sb*(zb*zb)/(PI*muR);
    K[59] = (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[60] = -1.0/3.0*(za*za*za)*log(sb/sa)/(PI*muR) + (1.0/3.0)*(zb*zb*zb)*log(sb/sa)/(PI*muR);
    K[61] = (1.0/3.0)*sa*(za*za*za)/(PI*muR) - 1.0/3.0*sa*(zb*zb*zb)/(PI*muR) - 1.0/3.0*sb*(za*za*za)/(PI*muR) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muR);
    K[62] = (1.0/6.0)*(sa*sa)*(za*za*za)/(PI*muR) - 1.0/6.0*(sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/6.0*(sb*sb)*(za*za*za)/(PI*muR) + (1.0/6.0)*(sb*sb)*(zb*zb*zb)/(PI*muR);
    K[63] = 0.0;
    K[64] = (1.0/3.0)*sa*(za*za*za)/(PI*muZ) - 1.0/3.0*sa*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ);
    K[65] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[66] = (1.0/4.0)*sa*(za*za)/(PI*muR) - 1.0/4.0*sa*(zb*zb)/(PI*muR) - 1.0/4.0*sb*(za*za)/(PI*muR) + (1.0/4.0)*sb*(zb*zb)/(PI*muR);
    K[67] = (1.0/4.0)*sa*(za*za*za*za)/(PI*muZ) - 1.0/4.0*sa*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*sb*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*sb*(zb*zb*zb*zb)/(PI*muZ) + (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[68] = (1.0/4.0)*(sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/4.0*(sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*(za*za)/(PI*muR) - 1.0/12.0*(sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[69] = (1.0/3.0)*sa*(za*za*za)/(PI*muR) - 1.0/3.0*sa*(zb*zb*zb)/(PI*muR) - 1.0/3.0*sb*(za*za*za)/(PI*muR) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muR);
    K[70] = (1.0/5.0)*sa*(za*za*za*za*za)/(PI*muZ) - 1.0/5.0*sa*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/5.0*sb*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*sb*(zb*zb*zb*zb*zb)/(PI*muZ) + (1.0/6.0)*(sa*sa)*(za*za*za)/(PI*muR) - 1.0/6.0*(sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/6.0*(sb*sb)*(za*za*za)/(PI*muR) + (1.0/6.0)*(sb*sb)*(zb*zb*zb)/(PI*muR);
    K[71] = (1.0/5.0)*(sa*sa)*(za*za*za*za*za)/(PI*muZ) - 1.0/5.0*(sa*sa)*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/5.0*(sb*sb)*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*(sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) + (1.0/9.0)*(sa*sa*sa)*(za*za*za)/(PI*muR) - 1.0/9.0*(sa*sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muR);
    K[72] = 0.0;
    K[73] = (1.0/3.0)*(sa*sa)*(za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa)*(zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[74] = (4.0/9.0)*(sa*sa*sa)*(za*za*za)/(PI*muZ) - 4.0/9.0*(sa*sa*sa)*(zb*zb*zb)/(PI*muZ) - 4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[75] = (1.0/8.0)*(sa*sa)*(za*za)/(PI*muR) - 1.0/8.0*(sa*sa)*(zb*zb)/(PI*muR) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[76] = (1.0/4.0)*(sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/4.0*(sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa)*(za*za)/(PI*muR) - 1.0/12.0*(sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[77] = (1.0/3.0)*(sa*sa*sa)*(za*za*za*za)/(PI*muZ) - 1.0/3.0*(sa*sa*sa)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/3.0*(sb*sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb*sb)*(zb*zb*zb*zb)/(PI*muZ) + (1.0/16.0)*(sa*sa*sa*sa)*(za*za)/(PI*muR) - 1.0/16.0*(sa*sa*sa*sa)*(zb*zb)/(PI*muR) - 1.0/16.0*(sb*sb*sb*sb)*(za*za)/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*(zb*zb)/(PI*muR);
    K[78] = (1.0/6.0)*(sa*sa)*(za*za*za)/(PI*muR) - 1.0/6.0*(sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/6.0*(sb*sb)*(za*za*za)/(PI*muR) + (1.0/6.0)*(sb*sb)*(zb*zb*zb)/(PI*muR);
    K[79] = (1.0/5.0)*(sa*sa)*(za*za*za*za*za)/(PI*muZ) - 1.0/5.0*(sa*sa)*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/5.0*(sb*sb)*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*(sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) + (1.0/9.0)*(sa*sa*sa)*(za*za*za)/(PI*muR) - 1.0/9.0*(sa*sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muR);
    K[80] = (4.0/15.0)*(sa*sa*sa)*(za*za*za*za*za)/(PI*muZ) - 4.0/15.0*(sa*sa*sa)*(zb*zb*zb*zb*zb)/(PI*muZ) - 4.0/15.0*(sb*sb*sb)*(za*za*za*za*za)/(PI*muZ) + (4.0/15.0)*(sb*sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) + (1.0/12.0)*(sa*sa*sa*sa)*(za*za*za)/(PI*muR) - 1.0/12.0*(sa*sa*sa*sa)*(zb*zb*zb)/(PI*muR) - 1.0/12.0*(sb*sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb*sb)*(zb*zb*zb)/(PI*muR);
}

inline void MSigmaPhiGeneral(double sa, double sb, double za, double zb, double sigma, double M[81])
{
    using std::log;
    M[0] = -1.0/4.0*sigma*za*log(sb/sa)/PI + (1.0/4.0)*sigma*zb*log(sb/sa)/PI;
    M[1] = (1.0/4.0)*sa*sigma*za/PI - 1.0/4.0*sa*sigma*zb/PI - 1.0/4.0*sb*sigma*za/PI + (1.0/4.0)*sb*sigma*zb/PI;
    M[2] = (1.0/8.0)*(sa*sa)*sigma*za/PI - 1.0/8.0*(sa*sa)*sigma*zb/PI - 1.0/8.0*(sb*sb)*sigma*za/PI + (1.0/8.0)*(sb*sb)*sigma*zb/PI;
    M[3] = -1.0/8.0*sigma*(za*za)*log(sb/sa)/PI + (1.0/8.0)*sigma*(zb*zb)*log(sb/sa)/PI;
    M[4] = (1.0/8.0)*sa*sigma*(za*za)/PI - 1.0/8.0*sa*sigma*(zb*zb)/PI - 1.0/8.0*sb*sigma*(za*za)/PI + (1.0/8.0)*sb*sigma*(zb*zb)/PI;
    M[5] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[6] = -1.0/12.0*sigma*(za*za*za)*log(sb/sa)/PI + (1.0/12.0)*sigma*(zb*zb*zb)*log(sb/sa)/PI;
    M[7] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[8] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[9] = (1.0/4.0)*sa*sigma*za/PI - 1.0/4.0*sa*sigma*zb/PI - 1.0/4.0*sb*sigma*za/PI + (1.0/4.0)*sb*sigma*zb/PI;
    M[10] = (1.0/8.0)*(sa*sa)*sigma*za/PI - 1.0/8.0*(sa*sa)*sigma*zb/PI - 1.0/8.0*(sb*sb)*sigma*za/PI + (1.0/8.0)*(sb*sb)*sigma*zb/PI;
    M[11] = (1.0/12.0)*(sa*sa*sa)*sigma*za/PI - 1.0/12.0*(sa*sa*sa)*sigma*zb/PI - 1.0/12.0*(sb*sb*sb)*sigma*za/PI + (1.0/12.0)*(sb*sb*sb)*sigma*zb/PI;
    M[12] = (1.0/8.0)*sa*sigma*(za*za)/PI - 1.0/8.0*sa*sigma*(zb*zb)/PI - 1.0/8.0*sb*sigma*(za*za)/PI + (1.0/8.0)*sb*sigma*(zb*zb)/PI;
    M[13] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[14] = (1.0/24.0)*(sa*sa*sa)*sigma*(za*za)/PI - 1.0/24.0*(sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[15] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[16] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[17] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[18] = (1.0/8.0)*(sa*sa)*sigma*za/PI - 1.0/8.0*(sa*sa)*sigma*zb/PI - 1.0/8.0*(sb*sb)*sigma*za/PI + (1.0/8.0)*(sb*sb)*sigma*zb/PI;
    M[19] = (1.0/12.0)*(sa*sa*sa)*sigma*za/PI - 1.0/12.0*(sa*sa*sa)*sigma*zb/PI - 1.0/12.0*(sb*sb*sb)*sigma*za/PI + (1.0/12.0)*(sb*sb*sb)*sigma*zb/PI;
    M[20] = (1.0/16.0)*(sa*sa*sa*sa)*sigma*za/PI - 1.0/16.0*(sa*sa*sa*sa)*sigma*zb/PI - 1.0/16.0*(sb*sb*sb*sb)*sigma*za/PI + (1.0/16.0)*(sb*sb*sb*sb)*sigma*zb/PI;
    M[21] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[22] = (1.0/24.0)*(sa*sa*sa)*sigma*(za*za)/PI - 1.0/24.0*(sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[23] = (1.0/32.0)*(sa*sa*sa*sa)*sigma*(za*za)/PI - 1.0/32.0*(sa*sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/32.0*(sb*sb*sb*sb)*sigma*(za*za)/PI + (1.0/32.0)*(sb*sb*sb*sb)*sigma*(zb*zb)/PI;
    M[24] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[25] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[26] = (1.0/48.0)*(sa*sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/48.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[27] = -1.0/8.0*sigma*(za*za)*log(sb/sa)/PI + (1.0/8.0)*sigma*(zb*zb)*log(sb/sa)/PI;
    M[28] = (1.0/8.0)*sa*sigma*(za*za)/PI - 1.0/8.0*sa*sigma*(zb*zb)/PI - 1.0/8.0*sb*sigma*(za*za)/PI + (1.0/8.0)*sb*sigma*(zb*zb)/PI;
    M[29] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[30] = -1.0/12.0*sigma*(za*za*za)*log(sb/sa)/PI + (1.0/12.0)*sigma*(zb*zb*zb)*log(sb/sa)/PI;
    M[31] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[32] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[33] = -1.0/16.0*sigma*(za*za*za*za)*log(sb/sa)/PI + (1.0/16.0)*sigma*(zb*zb*zb*zb)*log(sb/sa)/PI;
    M[34] = (1.0/16.0)*sa*sigma*(za*za*za*za)/PI - 1.0/16.0*sa*sigma*(zb*zb*zb*zb)/PI - 1.0/16.0*sb*sigma*(za*za*za*za)/PI + (1.0/16.0)*sb*sigma*(zb*zb*zb*zb)/PI;
    M[35] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[36] = (1.0/8.0)*sa*sigma*(za*za)/PI - 1.0/8.0*sa*sigma*(zb*zb)/PI - 1.0/8.0*sb*sigma*(za*za)/PI + (1.0/8.0)*sb*sigma*(zb*zb)/PI;
    M[37] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[38] = (1.0/24.0)*(sa*sa*sa)*sigma*(za*za)/PI - 1.0/24.0*(sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[39] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[40] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[41] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[42] = (1.0/16.0)*sa*sigma*(za*za*za*za)/PI - 1.0/16.0*sa*sigma*(zb*zb*zb*zb)/PI - 1.0/16.0*sb*sigma*(za*za*za*za)/PI + (1.0/16.0)*sb*sigma*(zb*zb*zb*zb)/PI;
    M[43] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[44] = (1.0/48.0)*(sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/48.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[45] = (1.0/16.0)*(sa*sa)*sigma*(za*za)/PI - 1.0/16.0*(sa*sa)*sigma*(zb*zb)/PI - 1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[46] = (1.0/24.0)*(sa*sa*sa)*sigma*(za*za)/PI - 1.0/24.0*(sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[47] = (1.0/32.0)*(sa*sa*sa*sa)*sigma*(za*za)/PI - 1.0/32.0*(sa*sa*sa*sa)*sigma*(zb*zb)/PI - 1.0/32.0*(sb*sb*sb*sb)*sigma*(za*za)/PI + (1.0/32.0)*(sb*sb*sb*sb)*sigma*(zb*zb)/PI;
    M[48] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[49] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[50] = (1.0/48.0)*(sa*sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/48.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[51] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[52] = (1.0/48.0)*(sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/48.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[53] = (1.0/64.0)*(sa*sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/64.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/64.0*(sb*sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/64.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[54] = -1.0/12.0*sigma*(za*za*za)*log(sb/sa)/PI + (1.0/12.0)*sigma*(zb*zb*zb)*log(sb/sa)/PI;
    M[55] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[56] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[57] = -1.0/16.0*sigma*(za*za*za*za)*log(sb/sa)/PI + (1.0/16.0)*sigma*(zb*zb*zb*zb)*log(sb/sa)/PI;
    M[58] = (1.0/16.0)*sa*sigma*(za*za*za*za)/PI - 1.0/16.0*sa*sigma*(zb*zb*zb*zb)/PI - 1.0/16.0*sb*sigma*(za*za*za*za)/PI + (1.0/16.0)*sb*sigma*(zb*zb*zb*zb)/PI;
    M[59] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[60] = -1.0/20.0*sigma*(za*za*za*za*za)*log(sb/sa)/PI + (1.0/20.0)*sigma*(zb*zb*zb*zb*zb)*log(sb/sa)/PI;
    M[61] = (1.0/20.0)*sa*sigma*(za*za*za*za*za)/PI - 1.0/20.0*sa*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/20.0*sb*sigma*(za*za*za*za*za)/PI + (1.0/20.0)*sb*sigma*(zb*zb*zb*zb*zb)/PI;
    M[62] = (1.0/40.0)*(sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/40.0*(sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/40.0*(sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/40.0)*(sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[63] = (1.0/12.0)*sa*sigma*(za*za*za)/PI - 1.0/12.0*sa*sigma*(zb*zb*zb)/PI - 1.0/12.0*sb*sigma*(za*za*za)/PI + (1.0/12.0)*sb*sigma*(zb*zb*zb)/PI;
    M[64] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[65] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[66] = (1.0/16.0)*sa*sigma*(za*za*za*za)/PI - 1.0/16.0*sa*sigma*(zb*zb*zb*zb)/PI - 1.0/16.0*sb*sigma*(za*za*za*za)/PI + (1.0/16.0)*sb*sigma*(zb*zb*zb*zb)/PI;
    M[67] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[68] = (1.0/48.0)*(sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/48.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[69] = (1.0/20.0)*sa*sigma*(za*za*za*za*za)/PI - 1.0/20.0*sa*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/20.0*sb*sigma*(za*za*za*za*za)/PI + (1.0/20.0)*sb*sigma*(zb*zb*zb*zb*zb)/PI;
    M[70] = (1.0/40.0)*(sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/40.0*(sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/40.0*(sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/40.0)*(sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[71] = (1.0/60.0)*(sa*sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/60.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/60.0*(sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/60.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[72] = (1.0/24.0)*(sa*sa)*sigma*(za*za*za)/PI - 1.0/24.0*(sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[73] = (1.0/36.0)*(sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/36.0*(sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[74] = (1.0/48.0)*(sa*sa*sa*sa)*sigma*(za*za*za)/PI - 1.0/48.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[75] = (1.0/32.0)*(sa*sa)*sigma*(za*za*za*za)/PI - 1.0/32.0*(sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[76] = (1.0/48.0)*(sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/48.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[77] = (1.0/64.0)*(sa*sa*sa*sa)*sigma*(za*za*za*za)/PI - 1.0/64.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb*zb)/PI - 1.0/64.0*(sb*sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/64.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[78] = (1.0/40.0)*(sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/40.0*(sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/40.0*(sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/40.0)*(sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[79] = (1.0/60.0)*(sa*sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/60.0*(sa*sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/60.0*(sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/60.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[80] = (1.0/80.0)*(sa*sa*sa*sa)*sigma*(za*za*za*za*za)/PI - 1.0/80.0*(sa*sa*sa*sa)*sigma*(zb*zb*zb*zb*zb)/PI - 1.0/80.0*(sb*sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/80.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
}

inline void KPhiAxis(double sb, double za, double zb, double muR, double muZ, double K[36])
{
    using std::log;
    K[0] = -sb*za/(PI*muZ) + sb*zb/(PI*muZ);
    K[1] = -(sb*sb)*za/(PI*muZ) + (sb*sb)*zb/(PI*muZ);
    K[2] = -1.0/2.0*sb*(za*za)/(PI*muZ) + (1.0/2.0)*sb*(zb*zb)/(PI*muZ);
    K[3] = -1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[4] = -1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ);
    K[5] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[6] = -(sb*sb)*za/(PI*muZ) + (sb*sb)*zb/(PI*muZ);
    K[7] = -4.0/3.0*(sb*sb*sb)*za/(PI*muZ) + (4.0/3.0)*(sb*sb*sb)*zb/(PI*muZ);
    K[8] = -1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[9] = -2.0/3.0*(sb*sb*sb)*(za*za)/(PI*muZ) + (2.0/3.0)*(sb*sb*sb)*(zb*zb)/(PI*muZ);
    K[10] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[11] = -4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[12] = -1.0/2.0*sb*(za*za)/(PI*muZ) + (1.0/2.0)*sb*(zb*zb)/(PI*muZ);
    K[13] = -1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[14] = -1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ) - 1.0/8.0*(sb*sb)*za/(PI*muR) + (1.0/8.0)*(sb*sb)*zb/(PI*muR);
    K[15] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*za/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*zb/(PI*muR);
    K[16] = -1.0/4.0*sb*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*sb*(zb*zb*zb*zb)/(PI*muZ) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[17] = -1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[18] = -1.0/2.0*(sb*sb)*(za*za)/(PI*muZ) + (1.0/2.0)*(sb*sb)*(zb*zb)/(PI*muZ);
    K[19] = -2.0/3.0*(sb*sb*sb)*(za*za)/(PI*muZ) + (2.0/3.0)*(sb*sb*sb)*(zb*zb)/(PI*muZ);
    K[20] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*za/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*zb/(PI*muR);
    K[21] = -4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ) - 1.0/16.0*(sb*sb*sb*sb)*za/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*zb/(PI*muR);
    K[22] = -1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[23] = -1.0/3.0*(sb*sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/16.0*(sb*sb*sb*sb)*(za*za)/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*(zb*zb)/(PI*muR);
    K[24] = -1.0/3.0*sb*(za*za*za)/(PI*muZ) + (1.0/3.0)*sb*(zb*zb*zb)/(PI*muZ);
    K[25] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[26] = -1.0/4.0*sb*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*sb*(zb*zb*zb*zb)/(PI*muZ) - 1.0/8.0*(sb*sb)*(za*za)/(PI*muR) + (1.0/8.0)*(sb*sb)*(zb*zb)/(PI*muR);
    K[27] = -1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[28] = -1.0/5.0*sb*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*sb*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/6.0*(sb*sb)*(za*za*za)/(PI*muR) + (1.0/6.0)*(sb*sb)*(zb*zb*zb)/(PI*muR);
    K[29] = -1.0/5.0*(sb*sb)*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*(sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muR);
    K[30] = -1.0/3.0*(sb*sb)*(za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[31] = -4.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muZ) + (4.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muZ);
    K[32] = -1.0/4.0*(sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/4.0)*(sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb)*(za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb)*(zb*zb)/(PI*muR);
    K[33] = -1.0/3.0*(sb*sb*sb)*(za*za*za*za)/(PI*muZ) + (1.0/3.0)*(sb*sb*sb)*(zb*zb*zb*zb)/(PI*muZ) - 1.0/16.0*(sb*sb*sb*sb)*(za*za)/(PI*muR) + (1.0/16.0)*(sb*sb*sb*sb)*(zb*zb)/(PI*muR);
    K[34] = -1.0/5.0*(sb*sb)*(za*za*za*za*za)/(PI*muZ) + (1.0/5.0)*(sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/9.0*(sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/9.0)*(sb*sb*sb)*(zb*zb*zb)/(PI*muR);
    K[35] = -4.0/15.0*(sb*sb*sb)*(za*za*za*za*za)/(PI*muZ) + (4.0/15.0)*(sb*sb*sb)*(zb*zb*zb*zb*zb)/(PI*muZ) - 1.0/12.0*(sb*sb*sb*sb)*(za*za*za)/(PI*muR) + (1.0/12.0)*(sb*sb*sb*sb)*(zb*zb*zb)/(PI*muR);
}

inline void MSigmaPhiAxis(double sb, double za, double zb, double sigma, double M[36])
{
    using std::log;
    M[0] = -1.0/8.0*(sb*sb)*sigma*za/PI + (1.0/8.0)*(sb*sb)*sigma*zb/PI;
    M[1] = -1.0/12.0*(sb*sb*sb)*sigma*za/PI + (1.0/12.0)*(sb*sb*sb)*sigma*zb/PI;
    M[2] = -1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[3] = -1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[4] = -1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[5] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[6] = -1.0/12.0*(sb*sb*sb)*sigma*za/PI + (1.0/12.0)*(sb*sb*sb)*sigma*zb/PI;
    M[7] = -1.0/16.0*(sb*sb*sb*sb)*sigma*za/PI + (1.0/16.0)*(sb*sb*sb*sb)*sigma*zb/PI;
    M[8] = -1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[9] = -1.0/32.0*(sb*sb*sb*sb)*sigma*(za*za)/PI + (1.0/32.0)*(sb*sb*sb*sb)*sigma*(zb*zb)/PI;
    M[10] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[11] = -1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[12] = -1.0/16.0*(sb*sb)*sigma*(za*za)/PI + (1.0/16.0)*(sb*sb)*sigma*(zb*zb)/PI;
    M[13] = -1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[14] = -1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[15] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[16] = -1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[17] = -1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[18] = -1.0/24.0*(sb*sb*sb)*sigma*(za*za)/PI + (1.0/24.0)*(sb*sb*sb)*sigma*(zb*zb)/PI;
    M[19] = -1.0/32.0*(sb*sb*sb*sb)*sigma*(za*za)/PI + (1.0/32.0)*(sb*sb*sb*sb)*sigma*(zb*zb)/PI;
    M[20] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[21] = -1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[22] = -1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[23] = -1.0/64.0*(sb*sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/64.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[24] = -1.0/24.0*(sb*sb)*sigma*(za*za*za)/PI + (1.0/24.0)*(sb*sb)*sigma*(zb*zb*zb)/PI;
    M[25] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[26] = -1.0/32.0*(sb*sb)*sigma*(za*za*za*za)/PI + (1.0/32.0)*(sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[27] = -1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[28] = -1.0/40.0*(sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/40.0)*(sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[29] = -1.0/60.0*(sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/60.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[30] = -1.0/36.0*(sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/36.0)*(sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[31] = -1.0/48.0*(sb*sb*sb*sb)*sigma*(za*za*za)/PI + (1.0/48.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb)/PI;
    M[32] = -1.0/48.0*(sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/48.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[33] = -1.0/64.0*(sb*sb*sb*sb)*sigma*(za*za*za*za)/PI + (1.0/64.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb)/PI;
    M[34] = -1.0/60.0*(sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/60.0)*(sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
    M[35] = -1.0/80.0*(sb*sb*sb*sb)*sigma*(za*za*za*za*za)/PI + (1.0/80.0)*(sb*sb*sb*sb)*sigma*(zb*zb*zb*zb*zb)/PI;
}

}  // namespace q2_henrotte
}  // namespace axifem

#endif  // RADIA_AXIFEM_Q2_HENROTTE_GENERATED_HPP
