#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2607-0-g9642315f"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2607
#define NETGEN_VERSION_TWEAK 0
#define NETGEN_VERSION_HASH "g9642315f"
#endif // NETGEN_VERSION_HPP_INCLUDED
