# Auto-generated by comsol-converter cc_ir_to_ngsolve (occ_primitives)
# IR: TEAM20_linear_xval  (magnetostatic_A, linear)
import numpy as np
from ngsolve import *
from netgen.occ import Box, Cylinder, Pnt, Dir, Glue, OCCGeometry
from netgen.meshing import MeshingParameters
from radia_mcp.radia_ngsolve.force import MU0
from radia_mcp.radia_ngsolve.solve import solve_magnetostatic_Aform
NU0 = 1.0/MU0; MM = 1e-3

# ---- geometry (netgen.occ primitives) ----
def _yoke():
    s = Box(Pnt(0*MM,0*MM,0*MM), Pnt(127*MM,25*MM,150*MM))
    s = s - Box(Pnt(25*MM,-0.1*MM,25*MM), Pnt(102*MM,25.1*MM,125*MM))
    s = s - Box(Pnt(50*MM,-0.1*MM,125*MM), Pnt(77*MM,25.1*MM,150*MM))
    return s
def _pole():
    s = Box(Pnt(51*MM,7.5*MM,26.5*MM), Pnt(76*MM,17.5*MM,125*MM))
    return s
def _coil():
    co = Cylinder(Pnt(63.5*MM,12.5*MM,26.7*MM), Dir(0,0,1), r=37.5*MM, h=96.6*MM)
    ci = Cylinder(Pnt(63.5*MM,12.5*MM,26.599999999999998*MM), Dir(0,0,1), r=19.5*MM, h=96.8*MM)
    return co - ci
bodies = []
yoke = _yoke(); yoke.mat('yoke')
yoke.faces.maxh = 6*MM
bodies.append(yoke)
pole = _pole(); pole.mat('pole')
for f in pole.faces: f.name = 'pole_surface'
pole.faces.maxh = 4*MM
bodies.append(pole)
coil = _coil(); coil.mat('coil')
coil.faces.maxh = 5*MM
bodies.append(coil)
big = Box(Pnt(-80*MM,-105*MM,-80*MM), Pnt(207*MM,130*MM,230*MM))
for f in big.faces: f.name = 'outer'
air = big - _yoke() - _pole() - _coil()
air.mat('air'); air.maxh = 45*MM
bodies.append(air)
mesh = Mesh(OCCGeometry(Glue(bodies)).GenerateMesh(MeshingParameters(maxh=45*MM, grading=0.3)))
mesh.Curve(2)
print('mesh:', mesh.ne, 'elems', mesh.GetMaterials())

# ---- azimuthal coil current (NI / cross-section) ----
cxc, cyc = 63.5*MM, 12.5*MM
J0 = 1000.0 / ((37.5-19.5)*MM * (123.3-26.7)*MM)
rrel = sqrt((x-cxc)**2 + (y-cyc)**2 + 1e-12)
Jc = CoefficientFunction((-(y-cyc)/rrel*J0, (x-cxc)/rrel*J0, 0.0))
Jsrc = mesh.MaterialCF({'coil': Jc}, default=CoefficientFunction((0.0,0.0,0.0)))

# ---- domain-wise reluctivity (linear) ----
nu = mesh.MaterialCF({'yoke': NU0/1000.0, 'pole': NU0/1000.0}, default=NU0)
gfu = solve_magnetostatic_Aform(mesh, nu, source=Jsrc, order=2, dirichlet='outer', reg=1e-6)
B = curl(gfu)

# ---- outputs ----
# lifting_force: Maxwell stress on 'pole_surface' (air side)
fl = L2(mesh, order=1, definedon=mesh.Materials('air'))
gB = [GridFunction(fl) for _ in range(3)]
for k in range(3): gB[k].Set(B[k])
Ba = CoefficientFunction(tuple(BoundaryFromVolumeCF(gB[k]) for k in range(3)))
nrm = specialcf.normal(3)
Tz = (1.0/MU0)*(Ba[2]*InnerProduct(Ba,nrm) - 0.5*InnerProduct(Ba,Ba)*nrm[2])
Fz = -Integrate(Tz*ds(definedon=mesh.Boundaries('pole_surface')), mesh)
print('lifting_force Fz:', Fz, 'N')
print('B_pole |B|@[63.5, 12.5, 75.0]mm:', sqrt(InnerProduct(B,B))(mesh(63.5*MM,12.5*MM,75.0*MM)))