classdef NativeKernels
    %NATIVEKERNELS Enter the required, Optuna-only native gateway.
    methods (Static)
        function varargout = call(varargin)
            %CALL Enter the required Optuna-only MEX boundary.
            gateway = radia.optuna.internal.NativeKernels.gateway();
            if gateway == "optuna_mex"
                if ~isempty(varargin) && isstring(varargin{1}) && ...
                        isscalar(varargin{1})
                    varargin{1}=char(varargin{1});
                end
                [varargout{1:nargout}]=optuna_mex(varargin{:});
                return
            end
            error("radia:optuna:MissingNativeKernel", ...
                "optuna_mex is required. Run Build.ps1 -OptunaMexOnly " + ...
                "before using radia.optuna.");
        end

        function available = has(command)
            commands = radia.optuna.internal.NativeKernels.commands();
            available = any(commands == string(command));
        end

        function info = status()
            commands = radia.optuna.internal.NativeKernels.commands();
            expected = radia.optuna.internal.NativeKernels.expectedCommands();
            present = ismember(expected, commands);
            gateway=radia.optuna.internal.NativeKernels.gateway();
            info = struct( ...
                schema="radia.optuna.native-kernels.v1", ...
                mex_available=~isempty(commands), ...
                backend="native-mex", ...
                gateway=gateway, ...
                mex_path=string(which(gateway)), ...
                expected_commands=expected, ...
                available_commands=expected(present), ...
                missing_commands=expected(~present));
        end
    end

    methods (Static, Access=private)
        function commands = commands()
            persistent cache initialized
            if isempty(initialized)
                gateway=radia.optuna.internal.NativeKernels.gateway();
                if gateway==""
                    error("radia:optuna:MissingNativeKernel", ...
                        "optuna_mex is required. Run Build.ps1 " + ...
                        "-OptunaMexOnly before using radia.optuna.");
                else
                    cache=string(radia.optuna.internal.NativeKernels.call( ...
                        "api.commands"));
                end
                expected=["api.info","api.commands", ...
                    radia.optuna.internal.NativeKernels.expectedCommands()];
                missing=expected(~ismember(expected,cache));
                unexpected=cache(~ismember(cache,expected));
                if numel(cache)~=numel(expected) || ...
                        ~isempty(missing) || ~isempty(unexpected)
                    error("radia:optuna:IncompatibleNativeKernel", ...
                        "optuna_mex does not match the required %d-command " + ...
                        "contract. Missing: %s. Unexpected: %s. Rebuild " + ...
                        "with Build.ps1 -OptunaMexOnly.", ...
                        numel(expected),strjoin(missing,", "), ...
                        strjoin(unexpected,", "));
                end
                initialized=true;
            end
            commands=cache;
        end

        function expected = expectedCommands()
            expected = [ ...
                "optuna.pareto.rank_crowding", ...
                "optuna.parzen.log_pdf_numerical", ...
                "optuna.parzen.log_pdf_categorical", ...
                "optuna.tpe.best_numerical", ...
                "optuna.tpe.best_joint", ...
                "optuna.tpe.best_joint_observations", ...
                "optuna.tpe.best_numerical_observations", ...
                "optuna.tpe.history.reset", ...
                "optuna.tpe.history.append_complete", ...
                "optuna.tpe.best_grouped_history", ...
                "optuna.random_state.create", ...
                "optuna.random_state.rand", ...
                "optuna.random_state.randn", ...
                "optuna.random_state.randi", ...
                "optuna.random_state.randperm", ...
                "optuna.random_state.snapshot", ...
                "optuna.random_state.restore", ...
                "optuna.random_state.destroy"];
        end

        function name = gateway()
            persistent cache initialized
            if isempty(initialized)
                if exist("optuna_mex","file") == 3
                    cache="optuna_mex";
                else
                    cache="";
                end
                initialized=true;
            end
            name=cache;
        end
    end
end
