function payload = runSimulinkInput(simInput, useFastRestart, modelFolder)
%RUNSIMULINKINPUT Execute one SimulationInput without leaking worker errors.
%   The payload contract lets the client settle every RUNNING trial even
%   when a model simulation throws.  Study and Trial handles intentionally
%   remain on the client; only SimulationInput crosses the worker boundary.

timer = tic;
try
    radia.optuna.internal.setupSimulinkWorker(modelFolder);
    if useFastRestart
        simOut = sim(simInput, "UseFastRestart", "on");
    else
        simOut = sim(simInput);
    end
    payload = struct( ...
        "ok", true, ...
        "output", simOut, ...
        "identifier", "", ...
        "message", "", ...
        "elapsed_s", toc(timer));
catch exception
    payload = struct( ...
        "ok", false, ...
        "output", [], ...
        "identifier", string(exception.identifier), ...
        "message", string(exception.message), ...
        "elapsed_s", toc(timer));
end
end
