// Generated by build/generate_palettes.py; edit shared/palettes.json.
#include "palettes.h"
namespace eqnedit { namespace {
using I = PaletteItem;
I sym(const char* c, const char* f, const char* l, const char* p, const char* t) {
    return I{std::string("symbol.") + c, f, l, p, t};
}
I tpl(const char* c, const char* f, const char* l, const char* p, const char* t) {
    return I{std::string("template.") + c, f, l, p, t};
}
I raw(const char* c, const char* f, const char* l, const char* p, const char* t) {
    return I{std::string("latex.") + c, f, l, p, t};
}
std::vector<Palette> build() {
    std::vector<Palette> p;
    p.push_back({u8"関係演算子", u8"≤≠", 3, {
        sym("\\leq", u8"≤", u8"以下", u8"\\leq", u8"\\leq "),
        sym("\\geq", u8"≥", u8"以上", u8"\\geq", u8"\\geq "),
        sym("\\ll", u8"≪", u8"はるかに小さい", u8"\\ll", u8"\\ll "),
        sym("\\gg", u8"≫", u8"はるかに大きい", u8"\\gg", u8"\\gg "),
        sym("\\prec", u8"≺", u8"順序が先", u8"\\prec", u8"\\prec "),
        sym("\\succ", u8"≻", u8"順序が後", u8"\\succ", u8"\\succ "),
        sym("\\triangleleft", u8"◁", u8"左向き三角", u8"\\triangleleft", u8"\\triangleleft "),
        sym("\\triangleright", u8"▷", u8"右向き三角", u8"\\triangleright", u8"\\triangleright "),
        sym("\\neq", u8"≠", u8"等しくない", u8"\\neq", u8"\\neq "),
        sym("\\equiv", u8"≡", u8"恒等・合同", u8"\\equiv", u8"\\equiv "),
        sym("\\approx", u8"≈", u8"ほぼ等しい", u8"\\approx", u8"\\approx "),
        sym("\\cong", u8"≅", u8"合同", u8"\\cong", u8"\\cong "),
        sym("\\sim", u8"∼", u8"相似", u8"\\sim", u8"\\sim "),
        sym("\\simeq", u8"≃", u8"漸近的に等しい", u8"\\simeq", u8"\\simeq "),
        sym("\\propto", u8"∝", u8"比例", u8"\\propto", u8"\\propto "),
        sym("\\sqsubseteq", u8"⊑", u8"角付き部分集合", u8"\\sqsubseteq", u8"\\sqsubseteq "),
        sym("\\sqsupseteq", u8"⊒", u8"角付き上位集合", u8"\\sqsupseteq", u8"\\sqsupseteq "),
        sym("\\parallel", u8"∥", u8"平行", u8"\\parallel", u8"\\parallel "),
        sym("\\Vert", u8"‖", u8"二重縦線（ノルム）", u8"\\Vert", u8"\\Vert "),
        sym("\\mid", u8"∣", u8"割り切る", u8"\\mid", u8"\\mid "),
        sym("\\vdash", u8"⊢", u8"導出される", u8"\\vdash", u8"\\vdash "),
        sym("\\models", u8"⊨", u8"充足する", u8"\\models", u8"\\models "),
        sym("\\frown", u8"⌢", u8"フラウン（記号）", u8"\\frown", u8"\\frown "),
        sym("\\smile", u8"⌣", u8"スマイル（記号）", u8"\\smile", u8"\\smile "),
    }});
    p.push_back({u8"空白と点", u8"⋯", 3, {
        raw("\\!", u8"−", u8"負の空き", u8"", u8"\\!"),
        raw("\\,", u8"␣", u8"細い空き（1/6 em）", u8"", u8"\\,"),
        raw("\\:", u8"␣␣", u8"中位の空き（2/9 em）", u8"", u8"\\:"),
        raw("\\;", u8"␣␣␣", u8"広い空き（5/18 em）", u8"", u8"\\;"),
        raw("\\quad", u8"1em", u8"1 em の空き", u8"", u8"\\quad"),
        raw("\\qquad", u8"2em", u8"2 em の空き", u8"", u8"\\qquad"),
        sym("\\ldots", u8"…", u8"下寄りの省略記号", u8"\\ldots", u8"\\ldots "),
        sym("\\cdots", u8"⋯", u8"中央の省略記号", u8"\\cdots", u8"\\cdots "),
        sym("\\vdots", u8"⋮", u8"縦の省略記号", u8"\\vdots", u8"\\vdots "),
        sym("\\ddots", u8"⋱", u8"斜めの省略記号", u8"\\ddots", u8"\\ddots "),
        sym("\\therefore", u8"∴", u8"ゆえに", u8"\\therefore", u8"\\therefore "),
        sym("\\because", u8"∵", u8"なぜならば", u8"\\because", u8"\\because "),
    }});
    p.push_back({u8"装飾", u8"x′", 3, {
        tpl("hat", u8"^x", u8"ハット", u8"\\hat{x}", u8"\\hat{}"),
        tpl("tilde", u8"~x", u8"チルダ", u8"\\tilde{x}", u8"\\tilde{}"),
        tpl("bar", u8"¯x", u8"バー（1文字）", u8"\\bar{x}", u8"\\bar{}"),
        tpl("vec", u8"x→", u8"ベクトル矢印", u8"\\vec{x}", u8"\\vec{}"),
        tpl("dot", u8"·x", u8"ドット", u8"\\dot{x}", u8"\\dot{}"),
        tpl("ddot", u8":x", u8"二重ドット", u8"\\ddot{x}", u8"\\ddot{}"),
        tpl("dddot", u8"⋯x", u8"三重ドット", u8"\\dddot{x}", u8"\\dddot{}"),
        tpl("prime", u8"x′", u8"プライム", u8"x'", u8"'"),
        tpl("dprime", u8"x″", u8"二重プライム", u8"x''", u8"''"),
        tpl("tprime", u8"x‴", u8"三重プライム", u8"x'''", u8"'''"),
        tpl("strike", u8"/x", u8"打ち消し線", u8"\\cancel{x}", u8"\\cancel{}"),
        tpl("frown", u8"⌢x", u8"フラウン", u8"\\overset{\\frown}{x}", u8"\\overset{\\frown}{}"),
        tpl("smile", u8"⌣x", u8"スマイル", u8"\\overset{\\smile}{x}", u8"\\overset{\\smile}{}"),
        I{"style.sans", u8"sf", u8"サンセリフ（\\mathsf）", u8"\\mathsf{A}", u8"\\mathsf{}"},
        I{"style.mono", u8"tt", u8"等幅（\\mathtt）", u8"\\mathtt{A}", u8"\\mathtt{}"},
        I{"style.script", u8"cal", u8"カリグラフィー（\\mathcal）", u8"\\mathcal{A}", u8"\\mathcal{}"},
        I{"style.double", u8"bb", u8"黒板太字（\\mathbb）", u8"\\mathbb{A}", u8"\\mathbb{}"},
        I{"style.fraktur", u8"fr", u8"フラクトゥール（\\mathfrak）", u8"\\mathfrak{A}", u8"\\mathfrak{}"},
        I{"style.boldsymbol", u8"Bα", u8"記号太字（\\bm）", u8"\\bm{A}", u8"\\bm{}"},
    }});
    p.push_back({u8"演算子", u8"±×", 3, {
        sym("\\pm", u8"±", u8"プラスマイナス", u8"\\pm", u8"\\pm "),
        sym("\\mp", u8"∓", u8"マイナスプラス", u8"\\mp", u8"\\mp "),
        sym("\\times", u8"×", u8"乗算", u8"\\times", u8"\\times "),
        sym("\\div", u8"÷", u8"除算", u8"\\div", u8"\\div "),
        sym("\\ast", u8"∗", u8"アスタリスク", u8"\\ast", u8"\\ast "),
        sym("\\cdot", u8"⋅", u8"中黒（積）", u8"\\cdot", u8"\\cdot "),
        sym("\\star", u8"⋆", u8"星", u8"\\star", u8"\\star "),
        sym("\\bullet", u8"•", u8"黒丸", u8"\\bullet", u8"\\bullet "),
        sym("\\otimes", u8"⊗", u8"テンソル積", u8"\\otimes", u8"\\otimes "),
        sym("\\oplus", u8"⊕", u8"直和", u8"\\oplus", u8"\\oplus "),
        sym("\\ominus", u8"⊖", u8"丸マイナス", u8"\\ominus", u8"\\ominus "),
        sym("\\odot", u8"⊙", u8"丸ドット", u8"\\odot", u8"\\odot "),
        sym("\\diamond", u8"⋄", u8"ダイヤ演算子", u8"\\diamond", u8"\\diamond "),
        sym("\\bigtriangledown", u8"▽", u8"下向き三角", u8"\\bigtriangledown", u8"\\bigtriangledown "),
        sym("\\dagger", u8"†", u8"ダガー", u8"\\dagger", u8"\\dagger "),
        sym("\\ddagger", u8"‡", u8"二重ダガー", u8"\\ddagger", u8"\\ddagger "),
        sym("\\dag", u8"†", u8"ダガー（別名）", u8"\\dag", u8"\\dag "),
        sym("\\setminus", u8"∖", u8"差集合", u8"\\setminus", u8"\\setminus "),
        sym("\\backslash", u8"\\", u8"バックスラッシュ", u8"\\backslash", u8"\\backslash "),
        sym("\\surd", u8"√", u8"根号記号", u8"\\surd", u8"\\surd "),
    }});
    p.push_back({u8"矢印", u8"→⇒", 3, {
        sym("\\rightarrow", u8"→", u8"右矢印", u8"\\rightarrow", u8"\\rightarrow "),
        sym("\\leftarrow", u8"←", u8"左矢印", u8"\\leftarrow", u8"\\leftarrow "),
        sym("\\leftrightarrow", u8"↔", u8"両向き矢印", u8"\\leftrightarrow", u8"\\leftrightarrow "),
        sym("\\uparrow", u8"↑", u8"上矢印", u8"\\uparrow", u8"\\uparrow "),
        sym("\\downarrow", u8"↓", u8"下矢印", u8"\\downarrow", u8"\\downarrow "),
        sym("\\updownarrow", u8"↕", u8"上下矢印", u8"\\updownarrow", u8"\\updownarrow "),
        sym("\\Rightarrow", u8"⇒", u8"二重右矢印", u8"\\Rightarrow", u8"\\Rightarrow "),
        sym("\\Leftarrow", u8"⇐", u8"二重左矢印", u8"\\Leftarrow", u8"\\Leftarrow "),
        sym("\\Leftrightarrow", u8"⇔", u8"二重両向き矢印", u8"\\Leftrightarrow", u8"\\Leftrightarrow "),
        sym("\\Uparrow", u8"⇑", u8"二重上矢印", u8"\\Uparrow", u8"\\Uparrow "),
        sym("\\to", u8"→", u8"右矢印（\\to）", u8"\\to", u8"\\to "),
        sym("\\mapsto", u8"↦", u8"写像", u8"\\mapsto", u8"\\mapsto "),
        sym("\\Longrightarrow", u8"⟹", u8"長い二重右矢印", u8"\\Longrightarrow", u8"\\Longrightarrow "),
        sym("\\Longleftarrow", u8"⟸", u8"長い二重左矢印", u8"\\Longleftarrow", u8"\\Longleftarrow "),
        sym("\\Longleftrightarrow", u8"⟺", u8"長い二重両向き矢印", u8"\\Longleftrightarrow", u8"\\Longleftrightarrow "),
        sym("\\hookrightarrow", u8"↪", u8"右フック矢印", u8"\\hookrightarrow", u8"\\hookrightarrow "),
        sym("\\hookleftarrow", u8"↩", u8"左フック矢印", u8"\\hookleftarrow", u8"\\hookleftarrow "),
        sym("\\nearrow", u8"↗", u8"右上矢印", u8"\\nearrow", u8"\\nearrow "),
        sym("\\searrow", u8"↘", u8"右下矢印", u8"\\searrow", u8"\\searrow "),
        sym("\\swarrow", u8"↙", u8"左下矢印", u8"\\swarrow", u8"\\swarrow "),
        sym("\\nwarrow", u8"↖", u8"左上矢印", u8"\\nwarrow", u8"\\nwarrow "),
        sym("\\rightharpoonup", u8"⇀", u8"右上ハープーン", u8"\\rightharpoonup", u8"\\rightharpoonup "),
        sym("\\rightharpoondown", u8"⇁", u8"右下ハープーン", u8"\\rightharpoondown", u8"\\rightharpoondown "),
        sym("\\leftharpoonup", u8"↼", u8"左上ハープーン", u8"\\leftharpoonup", u8"\\leftharpoonup "),
        sym("\\leftharpoondown", u8"↽", u8"左下ハープーン", u8"\\leftharpoondown", u8"\\leftharpoondown "),
    }});
    p.push_back({u8"論理記号", u8"∀∧", 2, {
        sym("\\forall", u8"∀", u8"すべての", u8"\\forall", u8"\\forall "),
        sym("\\exists", u8"∃", u8"存在する", u8"\\exists", u8"\\exists "),
        sym("\\nexists", u8"∄", u8"存在しない", u8"\\nexists", u8"\\nexists "),
        sym("\\neg", u8"¬", u8"否定", u8"\\neg", u8"\\neg "),
        sym("\\wedge", u8"∧", u8"論理積", u8"\\wedge", u8"\\wedge "),
        sym("\\vee", u8"∨", u8"論理和", u8"\\vee", u8"\\vee "),
        sym("\\top", u8"⊤", u8"真", u8"\\top", u8"\\top "),
        sym("\\perp", u8"⊥", u8"垂直・偽", u8"\\perp", u8"\\perp "),
        sym("\\not", u8"not", u8"打ち消し", u8"\\not=", u8"\\not "),
    }});
    p.push_back({u8"集合記号", u8"∈∪", 3, {
        sym("\\in", u8"∈", u8"要素である", u8"\\in", u8"\\in "),
        sym("\\notin", u8"∉", u8"要素でない", u8"\\notin", u8"\\notin "),
        sym("\\ni", u8"∋", u8"要素として含む", u8"\\ni", u8"\\ni "),
        sym("\\subset", u8"⊂", u8"部分集合", u8"\\subset", u8"\\subset "),
        sym("\\supset", u8"⊃", u8"上位集合", u8"\\supset", u8"\\supset "),
        sym("\\not\\subset", u8"⊄", u8"部分集合でない", u8"\\not\\subset", u8"\\not\\subset "),
        sym("\\subseteq", u8"⊆", u8"部分集合または等しい", u8"\\subseteq", u8"\\subseteq "),
        sym("\\supseteq", u8"⊇", u8"上位集合または等しい", u8"\\supseteq", u8"\\supseteq "),
        sym("\\emptyset", u8"∅", u8"空集合", u8"\\emptyset", u8"\\emptyset "),
        sym("\\cup", u8"∪", u8"和集合", u8"\\cup", u8"\\cup "),
        sym("\\cap", u8"∩", u8"共通部分", u8"\\cap", u8"\\cap "),
        sym("\\sqcup", u8"⊔", u8"角付き和", u8"\\sqcup", u8"\\sqcup "),
        sym("\\sqcap", u8"⊓", u8"角付き共通部分", u8"\\sqcap", u8"\\sqcap "),
        sym("\\bigcup", u8"⋃", u8"大きい和集合", u8"\\bigcup", u8"\\bigcup "),
        sym("\\bigcap", u8"⋂", u8"大きい共通部分", u8"\\bigcap", u8"\\bigcap "),
    }});
    p.push_back({u8"その他の記号", u8"∂∞", 3, {
        sym("\\partial", u8"∂", u8"偏微分", u8"\\partial", u8"\\partial "),
        sym("\\nabla", u8"∇", u8"ナブラ", u8"\\nabla", u8"\\nabla "),
        sym("\\infty", u8"∞", u8"無限大", u8"\\infty", u8"\\infty "),
        sym("\\Re", u8"ℜ", u8"実部", u8"\\Re", u8"\\Re "),
        sym("\\Im", u8"ℑ", u8"虚部", u8"\\Im", u8"\\Im "),
        sym("\\hbar", u8"ℏ", u8"換算プランク定数", u8"\\hbar", u8"\\hbar "),
        sym("\\angle", u8"∠", u8"角", u8"\\angle", u8"\\angle "),
        sym("\\circ", u8"∘", u8"合成・度（^\\circ）", u8"\\circ", u8"\\circ "),
        sym("\\mho", u8"℧", u8"モー（コンダクタンス）", u8"\\mho", u8"\\mho "),
        sym("\\ell", u8"ℓ", u8"筆記体の l", u8"\\ell", u8"\\ell "),
        sym("\\prime", u8"′", u8"プライム記号", u8"\\prime", u8"\\prime "),
        sym("\\coprod", u8"∐", u8"余積記号", u8"\\coprod", u8"\\coprod "),
        sym("\\langle", u8"⟨", u8"左山括弧（単体）", u8"\\langle", u8"\\langle "),
        sym("\\rangle", u8"⟩", u8"右山括弧（単体）", u8"\\rangle", u8"\\rangle "),
        sym("\\lfloor", u8"⌊", u8"左床記号（単体）", u8"\\lfloor", u8"\\lfloor "),
        sym("\\rfloor", u8"⌋", u8"右床記号（単体）", u8"\\rfloor", u8"\\rfloor "),
        sym("\\lceil", u8"⌈", u8"左天井記号（単体）", u8"\\lceil", u8"\\lceil "),
        sym("\\rceil", u8"⌉", u8"右天井記号（単体）", u8"\\rceil", u8"\\rceil "),
    }});
    p.push_back({u8"微分幾何", u8"∧⋆", 4, {
        raw("\\wedge ", u8"∧", u8"ウェッジ積", u8"\\wedge ", u8"\\wedge "),
        raw("\\star ", u8"⋆", u8"Hodge star作用素", u8"\\star ", u8"\\star "),
        raw("\\mathrm{d} ", u8"dω", u8"外微分（立体のd）", u8"\\mathrm{d}\\omega", u8"\\mathrm{d} "),
        raw("\\iota_{} ", u8"ι", u8"内部積（縮約）ι_X", u8"\\iota_v", u8"\\iota_{} "),
        raw("\\mathcal{L}_{} ", u8"ℒ", u8"Lie微分", u8"\\mathcal{L}_v", u8"\\mathcal{L}_{} "),
        raw("{}^{*} ", u8"f^*", u8"引き戻し（pullback）", u8"f^{*}", u8"{}^{*} "),
        raw("{}_{*} ", u8"f_*", u8"押し出し（pushforward）", u8"f_{*}", u8"{}_{*} "),
        raw("{}^{\\flat} ", u8"♭", u8"フラット（添字を下げる）", u8"v^{\\flat}", u8"{}^{\\flat} "),
        raw("{}^{\\sharp} ", u8"♯", u8"シャープ（添字を上げる）", u8"v^{\\sharp}", u8"{}^{\\sharp} "),
        raw("\\otimes ", u8"⊗", u8"テンソル積", u8"\\otimes ", u8"\\otimes "),
        raw("\\oplus ", u8"⊕", u8"直和", u8"\\oplus ", u8"\\oplus "),
    }});
    p.push_back({u8"ギリシャ小文字", u8"αβ", 4, {
        sym("\\alpha", u8"α", u8"アルファ", u8"\\alpha", u8"\\alpha "),
        sym("\\beta", u8"β", u8"ベータ", u8"\\beta", u8"\\beta "),
        sym("\\gamma", u8"γ", u8"ガンマ", u8"\\gamma", u8"\\gamma "),
        sym("\\delta", u8"δ", u8"デルタ", u8"\\delta", u8"\\delta "),
        sym("\\epsilon", u8"ϵ", u8"イプシロン", u8"\\epsilon", u8"\\epsilon "),
        sym("\\varepsilon", u8"ε", u8"イプシロン（異体）", u8"\\varepsilon", u8"\\varepsilon "),
        sym("\\zeta", u8"ζ", u8"ゼータ", u8"\\zeta", u8"\\zeta "),
        sym("\\eta", u8"η", u8"エータ", u8"\\eta", u8"\\eta "),
        sym("\\theta", u8"θ", u8"シータ", u8"\\theta", u8"\\theta "),
        sym("\\vartheta", u8"ϑ", u8"シータ（異体）", u8"\\vartheta", u8"\\vartheta "),
        sym("\\iota", u8"ι", u8"イオタ", u8"\\iota", u8"\\iota "),
        sym("\\kappa", u8"κ", u8"カッパ", u8"\\kappa", u8"\\kappa "),
        sym("\\varkappa", u8"ϰ", u8"カッパ（異体）", u8"\\varkappa", u8"\\varkappa "),
        sym("\\lambda", u8"λ", u8"ラムダ", u8"\\lambda", u8"\\lambda "),
        sym("\\mu", u8"μ", u8"ミュー", u8"\\mu", u8"\\mu "),
        sym("\\nu", u8"ν", u8"ニュー", u8"\\nu", u8"\\nu "),
        sym("\\xi", u8"ξ", u8"クサイ", u8"\\xi", u8"\\xi "),
        sym("\\pi", u8"π", u8"パイ", u8"\\pi", u8"\\pi "),
        sym("\\varpi", u8"ϖ", u8"パイ（異体）", u8"\\varpi", u8"\\varpi "),
        sym("\\rho", u8"ρ", u8"ロー", u8"\\rho", u8"\\rho "),
        sym("\\varrho", u8"ϱ", u8"ロー（異体）", u8"\\varrho", u8"\\varrho "),
        sym("\\sigma", u8"σ", u8"シグマ", u8"\\sigma", u8"\\sigma "),
        sym("\\varsigma", u8"ς", u8"シグマ（語末形）", u8"\\varsigma", u8"\\varsigma "),
        sym("\\tau", u8"τ", u8"タウ", u8"\\tau", u8"\\tau "),
        sym("\\upsilon", u8"υ", u8"ウプシロン", u8"\\upsilon", u8"\\upsilon "),
        sym("\\phi", u8"ϕ", u8"ファイ", u8"\\phi", u8"\\phi "),
        sym("\\varphi", u8"φ", u8"ファイ（異体）", u8"\\varphi", u8"\\varphi "),
        sym("\\chi", u8"χ", u8"カイ", u8"\\chi", u8"\\chi "),
        sym("\\psi", u8"ψ", u8"プサイ", u8"\\psi", u8"\\psi "),
        sym("\\omega", u8"ω", u8"オメガ", u8"\\omega", u8"\\omega "),
    }});
    p.push_back({u8"ギリシャ大文字", u8"ΓΩ", 4, {
        sym("\\Gamma", u8"Γ", u8"ガンマ", u8"\\Gamma", u8"\\Gamma "),
        sym("\\Delta", u8"Δ", u8"デルタ", u8"\\Delta", u8"\\Delta "),
        sym("\\Theta", u8"Θ", u8"シータ", u8"\\Theta", u8"\\Theta "),
        sym("\\Lambda", u8"Λ", u8"ラムダ", u8"\\Lambda", u8"\\Lambda "),
        sym("\\Xi", u8"Ξ", u8"クサイ", u8"\\Xi", u8"\\Xi "),
        sym("\\Pi", u8"Π", u8"パイ", u8"\\Pi", u8"\\Pi "),
        sym("\\Sigma", u8"Σ", u8"シグマ", u8"\\Sigma", u8"\\Sigma "),
        sym("\\Upsilon", u8"Υ", u8"ウプシロン", u8"\\Upsilon", u8"\\Upsilon "),
        sym("\\Phi", u8"Φ", u8"ファイ", u8"\\Phi", u8"\\Phi "),
        sym("\\Psi", u8"Ψ", u8"プサイ", u8"\\Psi", u8"\\Psi "),
        sym("\\Omega", u8"Ω", u8"オメガ", u8"\\Omega", u8"\\Omega "),
    }});
    p.push_back({u8"括弧", u8"(□)", 3, {
        tpl("paren", u8"(□)", u8"丸括弧", u8"\\left(a\\right)", u8"\\left({}\\right)"),
        tpl("bracket", u8"[□]", u8"角括弧", u8"\\left[a\\right]", u8"\\left[{}\\right]"),
        tpl("brace", u8"{□}", u8"波括弧", u8"\\left\\{a\\right\\}", u8"\\left\\{{}\\right\\}"),
        tpl("angle", u8"⟨□⟩", u8"山括弧", u8"\\left\\langle a\\right\\rangle", u8"\\left\\langle {}\\right\\rangle"),
        tpl("abs", u8"|□|", u8"絶対値", u8"\\left|a\\right|", u8"\\left|{}\\right|"),
        tpl("norm", u8"‖□‖", u8"ノルム", u8"\\left\\|a\\right\\|", u8"\\left\\|{}\\right\\|"),
        tpl("floor", u8"⌊□⌋", u8"床関数", u8"\\left\\lfloor a\\right\\rfloor", u8"\\left\\lfloor {}\\right\\rfloor"),
        tpl("ceil", u8"⌈□⌉", u8"天井関数", u8"\\left\\lceil a\\right\\rceil", u8"\\left\\lceil {}\\right\\rceil"),
        tpl("dirac", u8"⟨□|□⟩", u8"ブラケット", u8"\\left\\langle a\\middle|b\\right\\rangle", u8"\\left\\langle {}\\middle|{}\\right\\rangle"),
    }});
    p.push_back({u8"分数と根号", u8"⁄√", 2, {
        tpl("frac", u8"□/□", u8"分数", u8"\\frac{a}{b}", u8"\\frac{}{}"),
        tpl("slashfrac", u8"□⁄□", u8"スラッシュ分数", u8"{}^{a}/{}_{b}", u8"{}^{}/{}_{}"),
        tpl("sqrt", u8"√□", u8"平方根", u8"\\sqrt{x}", u8"\\sqrt{}"),
        tpl("nthroot", u8"n√□", u8"n 乗根", u8"\\sqrt[n]{x}", u8"\\sqrt[]{}"),
    }});
    p.push_back({u8"上下付き", u8"x↑", 3, {
        tpl("sup", u8"□↑", u8"上付き", u8"a^{b}", u8"{}^{}"),
        tpl("sub", u8"□↓", u8"下付き", u8"a_{b}", u8"{}_{}"),
        tpl("subsup", u8"□↕", u8"上下付き", u8"a_{b}^{c}", u8"{}_{}^{}"),
        tpl("over", u8"↑□", u8"上側の注記", u8"\\overset{b}{a}", u8"\\overset{}{}"),
        tpl("under", u8"↓□", u8"下側の注記", u8"\\underset{b}{a}", u8"\\underset{}{}"),
        tpl("lim", u8"lim", u8"極限（条件は下）", u8"\\lim_{a}", u8"\\lim_{}"),
    }});
    p.push_back({u8"総和", u8"∑", 2, {
        tpl("sum", u8"∑□", u8"総和（上下限つき）", u8"\\sum_{a}^{b} c", u8"\\sum_{}^{} {}"),
        tpl("prod", u8"∏□", u8"総乗（上下限つき）", u8"\\prod_{a}^{b} c", u8"\\prod_{}^{} {}"),
    }});
    p.push_back({u8"積分", u8"∫", 3, {
        tpl("int", u8"∫", u8"積分", u8"\\int_{a}^{b} c", u8"\\int_{}^{} {}"),
        tpl("iint", u8"∬", u8"二重積分", u8"\\iint_{a}^{b} c", u8"\\iint_{}^{} {}"),
        tpl("iiint", u8"∭", u8"三重積分", u8"\\iiint_{a}^{b} c", u8"\\iiint_{}^{} {}"),
        tpl("oint", u8"∮", u8"周回積分", u8"\\oint_{a}^{b} c", u8"\\oint_{}^{} {}"),
    }});
    p.push_back({u8"上線と下線", u8"¯_", 2, {
        tpl("overline", u8"¯□", u8"上線（伸縮）", u8"\\overline{x}", u8"\\overline{}"),
        tpl("underline", u8"_□", u8"下線（伸縮）", u8"\\underline{x}", u8"\\underline{}"),
        tpl("overbrace", u8"⏞□", u8"上の水平波括弧", u8"\\overbrace{xy}", u8"\\overbrace{}^{}"),
        tpl("underbrace", u8"⏟□", u8"下の水平波括弧", u8"\\underbrace{xy}", u8"\\underbrace{}_{}"),
        tpl("overrightarrow", u8"□→", u8"上の右向き伸縮矢印", u8"\\overrightarrow{x}", u8"\\overrightarrow{}"),
        tpl("overleftarrow", u8"←□", u8"上の左向き伸縮矢印", u8"\\overleftarrow{x}", u8"\\overleftarrow{}"),
        tpl("overleftrightarrow", u8"□↔", u8"上の両向き伸縮矢印", u8"\\overleftrightarrow{x}", u8"\\overleftrightarrow{}"),
    }});
    p.push_back({u8"総乗と集合演算", u8"∏∐", 2, {
        tpl("coprod", u8"∐□", u8"余積（上下限つき）", u8"\\coprod_{a}^{b} c", u8"\\coprod_{}^{} {}"),
        tpl("bigcup", u8"⋃□", u8"大きい和集合（上下限つき）", u8"\\bigcup_{a}^{b} c", u8"\\bigcup_{}^{} {}"),
        tpl("bigcap", u8"⋂□", u8"大きい共通部分（上下限つき）", u8"\\bigcap_{a}^{b} c", u8"\\bigcap_{}^{} {}"),
    }});
    p.push_back({u8"行列", u8"⊞", 4, {
        tpl("matrix1x2", u8"1×2", u8"1×2", u8"", u8"\\begin{matrix} {} & {} \\end{matrix}"),
        tpl("matrix1x3", u8"1×3", u8"1×3", u8"", u8"\\begin{matrix} {} & {} & {} \\end{matrix}"),
        tpl("matrix2x1", u8"2×1", u8"2×1", u8"", u8"\\begin{matrix} {} \\\\ {} \\end{matrix}"),
        tpl("matrix2x2", u8"2×2", u8"2×2", u8"", u8"\\begin{matrix} {} & {} \\\\ {} & {} \\end{matrix}"),
        tpl("matrix2x3", u8"2×3", u8"2×3", u8"", u8"\\begin{matrix} {} & {} & {} \\\\ {} & {} & {} \\end{matrix}"),
        tpl("matrix3x1", u8"3×1", u8"3×1", u8"", u8"\\begin{matrix} {} \\\\ {} \\\\ {} \\end{matrix}"),
        tpl("matrix3x2", u8"3×2", u8"3×2", u8"", u8"\\begin{matrix} {} & {} \\\\ {} & {} \\\\ {} & {} \\end{matrix}"),
        tpl("matrix3x3", u8"3×3", u8"3×3", u8"", u8"\\begin{matrix} {} & {} & {} \\\\ {} & {} & {} \\\\ {} & {} & {} \\end{matrix}"),
        tpl("matrix4x4", u8"4×4", u8"4×4", u8"", u8"\\begin{matrix} {} & {} & {} & {} \\\\ {} & {} & {} & {} \\\\ {} & {} & {} & {} \\\\ {} & {} & {} & {} \\end{matrix}"),
        tpl("matrix5x5", u8"5×5", u8"5×5", u8"", u8"\\begin{matrix} {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} \\end{matrix}"),
        tpl("matrix6x6", u8"6×6", u8"6×6", u8"", u8"\\begin{matrix} {} & {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} & {} \\\\ {} & {} & {} & {} & {} & {} \\end{matrix}"),
        I{"matrix.add_row", u8"+R", u8"行を下へ追加", u8"", u8""},
        I{"matrix.remove_row", u8"−R", u8"現在行を削除", u8"", u8""},
        I{"matrix.add_column", u8"+C", u8"列を右へ追加", u8"", u8""},
        I{"matrix.remove_column", u8"−C", u8"現在列を削除", u8"", u8""},
        tpl("cases", u8"{□", u8"場合分け", u8"\\begin{cases}a&b\\\\c&d\\end{cases}", u8"\\begin{cases} {} & {} \\\\ {} & {} \\end{cases}"),
    }});
    return p;
}
} // namespace
const std::vector<Palette>& palettes() { static const auto p = build(); return p; }
int symbol_palette_count() { return 11; }
const std::vector<PaletteCategory>& palette_categories() {
    static const std::vector<PaletteCategory> groups = {
        {u8"基本", {12, 13, 18, 11, 2, 16}},
        {u8"解析", {0, 3, 7, 14, 15}},
        {u8"集合・記号", {4, 6, 5, 17, 1}},
        {u8"幾何", {8}},
        {u8"ギリシャ", {9, 10}},
    };
    return groups;
}
} // namespace eqnedit
