"""
NDT MCP Server (radia_mcp.ndt) -- Non-Destructive Evaluation knowledge.

Two-layer architecture:

  - `ndt(topic=...)` dispatches the curated knowledge.py (this file's
    main tool). The accepted topic enum is published via
    `ndt_topics()` (auto-registered by register_topics_tool).

  - `ndt_bibliography(query=...)` searches the auto-indexed catalog
    of approximately 145 PDFs at
    public-safe curated corpus

The catalog is regenerated by tools/pdf_batch_indexer.py +
tools/catalog_to_knowledge.py.
"""

import sys

from mcp.server.fastmcp import FastMCP
from ..common import register_status_tool, register_topics_tool
from .knowledge import get_knowledge, TOPICS

try:
    from .bibliography_index_knowledge import get_bibliography_index
except ImportError:
    def get_bibliography_index(query: str = "") -> str:
        return ("NDT bibliography index not yet generated. "
                "Run tools/pdf_batch_indexer.py + "
                "tools/catalog_to_knowledge.py to populate.")

mcp = FastMCP("mcp-server-ndt")


@mcp.tool()
def ndt(topic: str = "overview") -> str:
    """
    Electromagnetic non-destructive testing (NDT / NDE) knowledge.

    Covers eddy current testing (ECT), magnetic flux leakage (MFL),
    microwave / EMI metal detection, and the underlying FEM / BEM /
    hysteresis / open-boundary infrastructure.

    Args:
        topic: One of:
            "overview"                  - NDT landscape (DEFAULT)
            "eddy_current_basics"       - Skin depth, impedance plane
            "probe_types"               - Pancake/bobbin/split-D/array
            "defect_models"             - Crack / void / back-side
            "signal_processing"         - Phase, multi-freq, POD
            "fem_formulation"           - A-V / T-Omega / h / edge elements
            "integral_equation"         - BEM, VIE, LIE for cracks
            "multiply_connected"        - Cut surfaces, tree-cotree
            "open_boundary"             - PML, Kelvin, ABC, FEM-BEM
            "hysteresis_in_ndt"         - Vector Play / Stop / Energy
            "mfl_magnetic_flux_leakage" - DC + Hall arrays for pipes / rails
            "microwave_emi_landmine"    - GPR, metal detector, NMR MOUSE
            "ml_for_ndt"                - CNN / U-Net / PINN for NDT
            "all"                       - Everything concatenated
    """
    return get_knowledge(topic)


@mcp.tool()
def ndt_bibliography(query: str = "") -> str:
    """Search the NDT/NDE bibliography catalog.

    Args:
      query: empty string -> all entries; "__scanned__" -> scanned PDFs;
             keyword -> filter by title/authors/abstract substring.
    """
    return get_bibliography_index(query)


register_status_tool(
    mcp,
    server_name='mcp-server-ndt',
    description='Non-destructive testing: eddy current testing, '
                'magnetic flux leakage, MFL signal analysis',
    subpackage='radia_mcp.ndt',
    related_servers=["ih", "magnetic-materials"],
)

register_topics_tool(
    mcp,
    server_name='mcp-server-ndt',
    topics=TOPICS,
)


def main():
    if "--selftest" in sys.argv:
        n_topics = len(TOPICS)
        n_chars = len(get_knowledge("all"))
        n_biblio = len(get_bibliography_index(""))
        print(f"NDT MCP server self-test:")
        print(f"  topics:       {n_topics}")
        print(f"  knowledge:    {n_chars} chars")
        print(f"  bibliography: {n_biblio} chars")
        print("OK")
        return
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
