classdef RawWrite < handle
    %RAWWRITE Write portable ASCII LTspice RAW files, including complex data.
    properties, PlotName (1,1) string="Transient Analysis"; end
    properties (SetAccess=private), Traces (1,:) cell={}; end
    methods
        function addTrace(obj,trace)
            if ~isa(trace,'radia.ltspice.Trace'), error("radia:ltspice:TraceRequired","Expected radia.ltspice.Trace."); end
            if ~isempty(obj.Traces)&&numel(trace.Data)~=numel(obj.Traces{1}.Data), error("radia:ltspice:TraceLength","All traces must have equal length."); end
            obj.Traces{end+1}=trace;
        end
        function trace=getTrace(obj,reference)
            if isnumeric(reference)
                if ~isscalar(reference)||~isfinite(reference)||fix(reference)~=reference
                    error("radia:ltspice:TraceNotFound", ...
                        "Trace index must be a finite integer scalar.");
                end
                % PyLTSpice integer trace references are zero-based.
                j=double(reference)+1;
            else
                j=find(cellfun(@(x)strcmpi(x.Name,string(reference)), ...
                    obj.Traces),1);
            end
            if isempty(j)||j<1||j>numel(obj.Traces),error("radia:ltspice:TraceNotFound","Trace not found.");end
            trace=obj.Traces{j};
        end
        function addTracesFromRaw(obj,raw,filter)
            if ischar(filter)||isstring(filter),filter=cellstr(string(filter));end
            for k=1:numel(filter),obj.addTrace(raw.getTraceObject(filter{k}));end
        end
        function save(obj,filename)
            if isempty(obj.Traces),error("radia:ltspice:NoTraces","At least one trace is required.");end
            n=numel(obj.Traces{1}.Data); complexData=any(cellfun(@(x)~isreal(x.Data),obj.Traces));
            f=fopen(filename,'w');if f<0,error("radia:ltspice:Write","Cannot write %s",filename);end;c=onCleanup(@()fclose(f));
            fprintf(f,'Title: Generated by Radia MATLAB\nDate: %s\nPlotname: %s\nFlags: %s\nNo. Variables: %d\nNo. Points: %d\nVariables:\n',char(datetime('now')),obj.PlotName,localFlag(complexData),numel(obj.Traces),n);
            for j=1:numel(obj.Traces),fprintf(f,'\t%d\t%s\t%s\n',j-1,obj.Traces{j}.Name,localType(obj.Traces{j}.Name));end
            fprintf(f,'Values:\n');
            for i=1:n
                for j=1:numel(obj.Traces)
                    v=obj.Traces{j}.Data(i);
                    if j==1,prefix=sprintf('%d\t',i-1);else,prefix=sprintf('\t');end
                    if complexData,fprintf(f,'%s%.17g,%.17g\n',prefix,real(v),imag(v));else,fprintf(f,'%s%.17g\n',prefix,v);end
                end
            end
            clear c
        end
        function add_trace(obj,t),obj.addTrace(t);end
        function add_traces_from_raw(obj,varargin),obj.addTracesFromRaw(varargin{:});end
        function t=get_trace(obj,r),t=obj.getTrace(r);end
    end
end
function x=localFlag(c),if c,x='complex';else,x='real';end,end
function x=localType(name),if any(strcmpi(name,["time","frequency"])),x=char(lower(name));else,x='voltage';end,end
