function value = rlcResonanceObjective(trial, netlistFile, options)
%RLCRESONANCEOBJECTIVE Evaluate one AC resonance optimization trial.
arguments
    trial (1,1) radia.optuna.Trial
    netlistFile (1,1) string {mustBeFile}
    options.TargetFrequency_Hz (1,1) double {mustBePositive,mustBeFinite} = 1000
    options.Resistance_Ohm (1,1) double {mustBeNonnegative,mustBeFinite} = 2
    options.Inductance_H (1,1) double {mustBePositive,mustBeFinite} = 10e-3
    options.CapacitanceBounds_F (1,2) double {mustBePositive,mustBeFinite} = [1e-6 6e-6]
    options.OutputRoot (1,1) string = "C:\temp\radia_ltspice_rlc_objective"
    options.Executable (1,1) string = ""
end
if options.CapacitanceBounds_F(1) >= options.CapacitanceBounds_F(2)
    error("radia:ltspice:RLCBounds", ...
        "CapacitanceBounds_F must be strictly increasing.");
end
capacitance = trial.suggestFloat("capacitance_F", ...
    options.CapacitanceBounds_F(1), options.CapacitanceBounds_F(2), Log=true);
runDirectory = fullfile(options.OutputRoot, ...
    sprintf("trial_%06d", trial.Number));
result = radia.ltspice.run(netlistFile, ...
    Parameters=struct( ...
        "Rval", options.Resistance_Ohm, ...
        "Lval", options.Inductance_H, ...
        "Cval", capacitance), ...
    Executable=options.Executable, OutputDirectory=runDirectory, ...
    RawFormat="binary");
[frequency_Hz, measurement] = radia.ltspice.measureSeriesResonance(result);
value = log(frequency_Hz/options.TargetFrequency_Hz)^2;
trial.setUserAttr("ltspice_ac_resonance", struct( ...
    "capacitance_F", capacitance, ...
    "frequency_Hz", frequency_Hz, ...
    "measurement", measurement, ...
    "elapsed_s", result.elapsed_s));
end
