function result = runCoilGeometryResonanceOptimizationDemo(options)
%RUNCOILGEOMETRYRESONANCEOPTIMIZATIONDEMO Tune coil geometry at fixed C.
%
% Every geometry trial first builds the HACApK PEEC DC operator, then
% iterates frequency-dependent conductor impedance until
% imag(Z_coil(f) + 1/(j*w*C)) = 0. Simulink receives the converged R/X
% snapshot. LTspice independently checks the corresponding narrow-band
% equivalent circuit.
arguments
    options.TargetFrequency_Hz (1,1) double {mustBePositive,mustBeFinite} = 1000
    options.Capacitance_F (1,1) double {mustBePositive,mustBeFinite} = 3.3e-3
    options.TurnCount (1,1) double {mustBeInteger,mustBePositive} = 12
    options.RadiusBounds_m (1,2) double {mustBePositive,mustBeFinite} = [0.02 0.05]
    options.Pitch_m (1,1) double {mustBePositive,mustBeFinite} = 3e-3
    options.WireWidth_m (1,1) double {mustBePositive,mustBeFinite} = 1.5e-3
    options.WireHeight_m (1,1) double {mustBePositive,mustBeFinite} = 1.5e-3
    options.Conductivity_S_per_m (1,1) double {mustBePositive,mustBeFinite} = 5.8e7
    options.SegmentsPerTurn (1,1) double {mustBeInteger,mustBePositive} = 24
    options.RefinementSegmentsPerTurn (1,1) double {mustBeInteger,mustBePositive} = 48
    options.NumTrials (1,1) double {mustBeInteger,mustBePositive} = 64
    options.RadiusPolishIterations (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 10
    options.Seed (1,1) double {mustBeInteger,mustBeNonnegative} = 42
    options.NetlistFile (1,1) string = fullfile( ...
        fileparts(fileparts(fileparts(mfilename("fullpath")))), ...
        "samples", "ltspice_rlc_resonance_ac.cir")
    options.ModelFile (1,1) string = fullfile( ...
        radia.simulink.exampleDirectory(),"radia_peec_coil_ac_plant.slx")
    options.Executable (1,1) string = ""
    options.OutputDirectory (1,1) string = "C:\temp\radia_coil_geometry_resonance"
    options.StoragePath (1,1) string = ""
    options.ResultPath (1,1) string = ""
    options.PlotPath (1,1) string = ""
    options.RebuildModel (1,1) logical = false
    options.ResetStudy (1,1) logical = true
    options.ShowFigure (1,1) logical = false
end

if options.RadiusBounds_m(1) >= options.RadiusBounds_m(2)
    error("radia:ltspice:CoilRadiusBounds", ...
        "RadiusBounds_m must be strictly increasing.");
end
if options.RefinementSegmentsPerTurn <= options.SegmentsPerTurn
    error("radia:ltspice:CoilRefinement", ...
        "RefinementSegmentsPerTurn must exceed SegmentsPerTurn.");
end
if ~isfile(options.NetlistFile)
    error("radia:ltspice:CoilNetlist", ...
        "The RLC AC netlist does not exist: %s",options.NetlistFile);
end
if ~isfolder(options.OutputDirectory)
    mkdir(options.OutputDirectory);
end
if strlength(options.StoragePath) == 0
    options.StoragePath = fullfile(options.OutputDirectory, ...
        "coil_geometry_resonance_study.mat");
end
if strlength(options.ResultPath) == 0
    options.ResultPath = fullfile(options.OutputDirectory, ...
        "results_coil_geometry_resonance.json");
end
if strlength(options.PlotPath) == 0
    options.PlotPath = fullfile(options.OutputDirectory, ...
        "coil_geometry_resonance.png");
end
ensureParent(options.StoragePath);
ensureParent(options.ResultPath);
ensureParent(options.PlotPath);
if options.ResetStudy && isfile(options.StoragePath)
    delete(options.StoragePath);
end

totalTimer = tic;
setupTimer = tic;
if options.RebuildModel || ~isfile(options.ModelFile)
    [modelDirectory,modelName] = fileparts(options.ModelFile);
    options.ModelFile = radia.simulink.buildPEECCoilACModel( ...
        OutputDirectory=string(modelDirectory),ModelName=string(modelName));
end
target = options.TargetFrequency_Hz;
capacitance = options.Capacitance_F;
radiusBounds = options.RadiusBounds_m;
requiredInductance = 1/((2*pi*target)^2*capacitance);
executable = radia.ltspice.findExecutable(Executable=options.Executable);

lowerCoil = buildCoil(radiusBounds(1),options.SegmentsPerTurn);
upperCoil = buildCoil(radiusBounds(2),options.SegmentsPerTurn);
lowerDC = radia.peec.seriesCoilProperties(lowerCoil);
upperDC = radia.peec.seriesCoilProperties(upperCoil);
lowerRoot = radia.peec.solveSeriesResonance( ...
    lowerCoil,capacitance,DCProperties=lowerDC);
upperRoot = radia.peec.solveSeriesResonance( ...
    upperCoil,capacitance,DCProperties=upperDC);
targetBracketed = (lowerRoot.frequency_Hz-target)* ...
    (upperRoot.frequency_Hz-target) <= 0;
if ~targetBracketed
    error("radia:ltspice:CoilTargetOutsideBounds", ...
        ["The radius bounds do not bracket the target. Boundary " ...
         "self-consistent resonance frequencies are %.6g Hz and %.6g Hz."], ...
        lowerRoot.frequency_Hz,upperRoot.frequency_Hz);
end
setup_s = toc(setupTimer);

trialNumbers = NaN(options.NumTrials,1);
trialRadii = NaN(options.NumTrials,1);
trialDCInductances = NaN(options.NumTrials,1);
trialInductances = NaN(options.NumTrials,1);
trialResistances = NaN(options.NumTrials,1);
trialReactances = NaN(options.NumTrials,1);
trialWheeler = NaN(options.NumTrials,1);
trialFrequencies = NaN(options.NumTrials,1);
trialLTspiceFrequencies = NaN(options.NumTrials,1);
trialIterations = NaN(options.NumTrials,1);
trialModelInductances = NaN(options.NumTrials,1);
trialModelResistances = NaN(options.NumTrials,1);
trialModelReactances = NaN(options.NumTrials,1);
trialModelFrequencies = NaN(options.NumTrials,1);
trialModelNetReactances = NaN(options.NumTrials,1);
trialObjectives = NaN(options.NumTrials,1);
trialRawFiles = strings(options.NumTrials,1);
trialLogFiles = strings(options.NumTrials,1);
recordCount = 0;

study = radia.optuna.createStudy( ...
    study_name="ltspice-peec-frequency-dependent-coil-radius", ...
    direction="minimize", ...
    sampler=radia.optuna.TPESampler( ...
        Seed=options.Seed,NStartupTrials=min(6,options.NumTrials), ...
        Gamma=0.2,NumberOfEIChoices=256), ...
    StoragePath=options.StoragePath,AutoSave=true);
context = struct( ...
    "domain","frequency-dependent-peec-coil-simulink-ltspice-ac", ...
    "target_frequency_Hz",target, ...
    "fixed_capacitance_F",capacitance, ...
    "resonance_definition","imag(Z_coil(f)+1/(j*w*C))=0", ...
    "radius_bounds_m",radiusBounds);
study.setUserAttr("cae_execution_contract",context);
runner = radia.optuna.SimulinkRunner(options.ModelFile, ...
    ConfigureFcn=@configureTrial,ScoreFcn=@scoreTrial, ...
    ResultFcn=@trialArtifacts,StopTime="0",UseFastRestart=true);

optimizationTimer = tic;
runner.optimize(study,options.NumTrials);
optimization_s = toc(optimizationTimer);
best = study.bestSolution();
if ~best.available || ~isfield(best.params,"radius_m")
    error("radia:ltspice:CoilNoBestTrial", ...
        "The coil-geometry optimization did not produce a completed trial.");
end
tpeBestRadius = double(best.params.radius_m);
tpeBestRow = find(trialNumbers == best.trial_number,1);
tpeBestFrequency = trialFrequencies(tpeBestRow);
tpeBestTargetError = abs(tpeBestFrequency-target)/target;

refinementTimer = tic;
[bestRadius,refinedCoil,refinedDC,refinedRoot,polishHistory] = ...
    polishRadius();
coarseCoil = buildCoil(bestRadius,options.SegmentsPerTurn);
coarseDC = radia.peec.seriesCoilProperties(coarseCoil);
coarseRoot = radia.peec.solveSeriesResonance( ...
    coarseCoil,capacitance,DCProperties=coarseDC);
refinementRelative = abs(coarseRoot.inductance_H- ...
    refinedRoot.inductance_H)/refinedRoot.inductance_H;
refinement_s = toc(refinementTimer);

replayTimer = tic;
simulationInput = Simulink.SimulationInput(options.ModelFile);
simulationInput = configureModelSnapshot(simulationInput,refinedRoot);
simulationInput = simulationInput.setModelParameter("StopTime","0");
simulationOutput = sim(simulationInput);
modelInductance = finalTimeseriesValue( ...
    simulationOutput.get("peec_effective_inductance"));
modelResistance = finalTimeseriesValue( ...
    simulationOutput.get("peec_effective_resistance"));
modelReactance = finalTimeseriesValue( ...
    simulationOutput.get("peec_coil_reactance"));
modelFrequency = finalTimeseriesValue( ...
    simulationOutput.get("evaluation_frequency"));
modelNetReactance = finalTimeseriesValue( ...
    simulationOutput.get("input_reactance"));
finalRun = radia.ltspice.run(options.NetlistFile, ...
    Parameters=struct( ...
        "Rval",refinedRoot.resistance_Ohm, ...
        "Lval",refinedRoot.inductance_H, ...
        "Cval",capacitance), ...
    Executable=executable, ...
    OutputDirectory=fullfile(options.OutputDirectory,"best_ac_replay"), ...
    RawFormat="binary");
[measuredFrequency,measurement] = ...
    radia.ltspice.measureSeriesResonance(finalRun);
raw = radia.ltspice.RawRead(finalRun.raw_file);
ltspiceFrequency = real(raw.getTrace("frequency"));
sourceCurrent = raw.getTrace("I(Vdrive)");

sweepFrequency = linspace(0.7*refinedRoot.frequency_Hz, ...
    1.3*refinedRoot.frequency_Hz,181).';
sweepResistance = zeros(size(sweepFrequency));
sweepNetReactance = zeros(size(sweepFrequency));
sweepCurrent = zeros(size(sweepFrequency));
for index = 1:numel(sweepFrequency)
    properties = radia.peec.seriesCoilImpedance( ...
        refinedCoil,sweepFrequency(index),DCProperties=refinedDC);
    sweepResistance(index) = properties.resistance_Ohm;
    sweepNetReactance(index) = properties.reactance_Ohm - ...
        1/(2*pi*sweepFrequency(index)*capacitance);
    sweepCurrent(index) = 1/hypot( ...
        sweepResistance(index),sweepNetReactance(index));
end
replay_s = toc(replayTimer);

targetError = abs(refinedRoot.frequency_Hz-target)/target;
ltspiceError = abs(measuredFrequency-refinedRoot.frequency_Hz)/ ...
    refinedRoot.frequency_Hz;
modelInductanceError = abs(modelInductance-refinedRoot.inductance_H)/ ...
    refinedRoot.inductance_H;
modelResistanceError = abs(modelResistance-refinedRoot.resistance_Ohm)/ ...
    refinedRoot.resistance_Ohm;
modelReactanceError = abs(modelReactance-refinedRoot.coil_reactance_Ohm)/ ...
    refinedRoot.coil_reactance_Ohm;
modelFrequencyError = abs(modelFrequency-refinedRoot.frequency_Hz)/ ...
    refinedRoot.frequency_Hz;
modelNetReactanceRelative = abs(modelNetReactance)/ ...
    max(abs(refinedRoot.coil_reactance_Ohm),eps);
inductanceError = abs(refinedRoot.inductance_H-requiredInductance)/ ...
    requiredInductance;
validRecords = isfinite(trialRadii) & isfinite(trialFrequencies) & ...
    isfinite(trialLTspiceFrequencies) & isfinite(trialObjectives);
if sum(validRecords) ~= options.NumTrials
    error("radia:ltspice:CoilTrialRecords", ...
        "Every completed coil trial must have PEEC and LTspice measurements.");
end

visualizationTimer = tic;
visible = "off";
if options.ShowFigure
    visible = "on";
end
figureHandle = figure("Visible",visible,"Color","white", ...
    "Position",[100 100 1300 820]);
layout = tiledlayout(figureHandle,2,3, ...
    "TileSpacing","compact","Padding","compact");
layoutTitle = title(layout,sprintf( ...
    "Frequency-dependent PEEC tuning: %.3f mF, target %.0f Hz", ...
    capacitance*1e3,target));
layoutTitle.Color = [0.12 0.12 0.12];

geometryAxes = nexttile(layout,1);
hold(geometryAxes,"on");
colors = turbo(options.TurnCount);
for turn = 1:options.TurnCount
    points = refinedCoil.polylines_m(:,:,turn)*1e3;
    plot3(geometryAxes,points(:,1),points(:,2),points(:,3), ...
        "LineWidth",1.6,"Color",colors(turn,:));
end
hold(geometryAxes,"off");
axis(geometryAxes,"equal");
grid(geometryAxes,"on");
view(geometryAxes,36,24);
xlabel(geometryAxes,"x (mm)");
ylabel(geometryAxes,"y (mm)");
zlabel(geometryAxes,"z (mm)");
title(geometryAxes,sprintf( ...
    "Radius %.3f mm, L_eff %.4f uH, R_eff %.3f mOhm", ...
    bestRadius*1e3,refinedRoot.inductance_H*1e6, ...
    refinedRoot.resistance_Ohm*1e3));

responseAxes = nexttile(layout,2);
yyaxis(responseAxes,"left");
peecCurrentLine = plot(responseAxes,sweepFrequency,sweepCurrent, ...
    "LineWidth",1.5,"DisplayName","PEEC |I|");
hold(responseAxes,"on");
ltspiceCurrentLine = plot(responseAxes,ltspiceFrequency,abs(sourceCurrent), ...
    "--","LineWidth",1.1,"DisplayName","LTspice local equivalent");
hold(responseAxes,"off");
ylabel(responseAxes,"|I| for 1 V (A)");
yyaxis(responseAxes,"right");
reactanceLine = plot(responseAxes,sweepFrequency,sweepNetReactance, ...
    "LineWidth",1.2,"DisplayName","PEEC Im(Z_{in})");
yline(responseAxes,0,":");
xline(responseAxes,target,"--","Color",[0.2 0.2 0.2]);
xline(responseAxes,refinedRoot.frequency_Hz,"-.","Color",[0.4 0.4 0.4]);
xlabel(responseAxes,"Frequency (Hz)");
ylabel(responseAxes,"Im(Z_{in}) (Ohm)");
grid(responseAxes,"on");
legend(responseAxes,[peecCurrentLine ltspiceCurrentLine reactanceLine], ...
    "Location","best");
title(responseAxes,sprintf("Self-consistent resonance %.4f Hz", ...
    refinedRoot.frequency_Hz));

iterationAxes = nexttile(layout,3);
semilogy(iterationAxes,1:numel(refinedRoot.history.frequency_Hz), ...
    max(abs(refinedRoot.history.net_reactance_Ohm),realmin), ...
    "o-","LineWidth",1.2);
xlabel(iterationAxes,"Inner PEEC frequency evaluation");
ylabel(iterationAxes,"|Im(Z_{in})| (Ohm)");
grid(iterationAxes,"on");
title(iterationAxes,sprintf("Frequency root: %d evaluations", ...
    refinedRoot.evaluation_count));

inductanceAxes = nexttile(layout,4,[1 2]);
[sortedRadii,order] = sort(trialRadii(validRecords));
sortedDC = trialDCInductances(validRecords);
sortedDC = sortedDC(order);
sortedEffective = trialInductances(validRecords);
sortedEffective = sortedEffective(order);
plot(inductanceAxes,sortedRadii*1e3,sortedDC*1e6, ...
    ":","LineWidth",1.1,"DisplayName","PEEC DC L");
hold(inductanceAxes,"on");
plot(inductanceAxes,sortedRadii*1e3,sortedEffective*1e6, ...
    "o-","LineWidth",1.1,"DisplayName","L_eff at own resonance");
yline(inductanceAxes,requiredInductance*1e6,"--", ...
    "Target-frequency L","DisplayName","Target-frequency L");
plot(inductanceAxes,bestRadius*1e3,refinedRoot.inductance_H*1e6, ...
    "p","MarkerSize",12,"MarkerFaceColor",[0.85 0.2 0.05], ...
    "DisplayName","Refined polished design");
hold(inductanceAxes,"off");
xlabel(inductanceAxes,"Coil radius (mm)");
ylabel(inductanceAxes,"Inductance (uH)");
grid(inductanceAxes,"on");
legend(inductanceAxes,"Location","northwest");
title(inductanceAxes,"Geometry-to-frequency-dependent inductance map");

historyAxes = nexttile(layout,6);
yyaxis(historyAxes,"left");
semilogy(historyAxes,trialNumbers(validRecords), ...
    max(trialObjectives(validRecords),realmin),"o-","LineWidth",1.1);
ylabel(historyAxes,"Objective: log(f_PEEC/f_target)^2");
yyaxis(historyAxes,"right");
plot(historyAxes,trialNumbers(validRecords), ...
    trialRadii(validRecords)*1e3,".-","LineWidth",1.1,"MarkerSize",13);
yline(historyAxes,bestRadius*1e3,"--","Polished radius");
xlabel(historyAxes,"Trial number");
ylabel(historyAxes,"Radius (mm)");
grid(historyAxes,"on");
title(historyAxes,"TPE search and scalar polish");
applyLightAxesStyle(figureHandle);
responseAxes.YAxis(1).Color = [0 0.35 0.72];
responseAxes.YAxis(2).Color = [0.85 0.25 0.05];
historyAxes.YAxis(1).Color = [0 0.35 0.72];
historyAxes.YAxis(2).Color = [0.85 0.25 0.05];
exportgraphics(layout,options.PlotPath,"Resolution",160);
visualization_s = toc(visualizationTimer);
if ~options.ShowFigure
    close(figureHandle);
end

completed = study.TrialTable.State == "COMPLETE";
failed = study.TrialTable.State == "FAIL";
gates = struct( ...
    "all_trials_completed",sum(completed) == options.NumTrials, ...
    "radius_bounds_bracket_target",targetBracketed, ...
    "tpe_best_within_1_percent",tpeBestTargetError <= 1e-2, ...
    "polished_target_within_0_1_percent",targetError <= 1e-3, ...
    "frequency_root_converged",refinedRoot.converged, ...
    "frequency_root_residual_below_1e_8", ...
        refinedRoot.relative_reactance_residual <= 1e-8, ...
    "ltspice_local_equivalent_matches_peec_root",ltspiceError <= 5e-5, ...
    "simulink_receives_peec_inductance",modelInductanceError <= 1e-12, ...
    "simulink_receives_peec_resistance",modelResistanceError <= 1e-12, ...
    "simulink_receives_peec_reactance",modelReactanceError <= 1e-12, ...
    "simulink_receives_evaluation_frequency",modelFrequencyError <= 1e-12, ...
    "simulink_net_reactance_is_zero",modelNetReactanceRelative <= 1e-8, ...
    "ac_resistance_not_below_dc", ...
        refinedRoot.resistance_Ohm >= refinedDC.resistance_Ohm, ...
    "segment_refinement_within_1_percent",refinementRelative <= 0.01, ...
    "wheeler_reference_within_12_percent", ...
        refinedDC.wheeler_relative_difference <= 0.12, ...
    "best_radius_is_interior",bestRadius > radiusBounds(1) && ...
        bestRadius < radiusBounds(2));
pass = all(cell2mat(struct2cell(gates)));
simulinkInfo = ver("simulink");
result = struct( ...
    "radia_version",projectVersion(), ...
    "schema","cae-ai-lab.solver-run.v1", ...
    "created_at_utc",utcTimestamp(), ...
    "case","fixed-capacitor frequency-dependent PEEC coil optimization", ...
    "solver","matlab", ...
    "solver_backend", ...
        "radia-hacapk-peec-bessel-plus-simulink-ac-plus-ltspice", ...
    "source_artifact",portableArtifactPath(options.NetlistFile), ...
    "pass",pass, ...
    "run",struct( ...
        "command","radia.ltspice.runCoilGeometryResonanceOptimizationDemo", ...
        "workdir",portableArtifactPath(options.OutputDirectory), ...
        "exit_code",0, ...
        "duration_s",toc(totalTimer), ...
        "stdout_log",portableArtifactPath(finalRun.log_file)), ...
    "result_files",[portableArtifactPath(options.ResultPath), ...
        portableArtifactPath(options.PlotPath), ...
        portableArtifactPath(options.ModelFile), ...
        portableArtifactPath(options.NetlistFile)], ...
    "checks",struct( ...
        "ran_to_completion",true, ...
        "result_files_exist",isfile(options.PlotPath) && ...
            isfile(options.ModelFile) && isfile(options.NetlistFile), ...
        "validation_passed",pass), ...
    "tolerances",struct( ...
        "target_frequency_relative",1e-3, ...
        "frequency_root_reactance_relative",1e-8, ...
        "ltspice_vs_peec_root_relative",5e-5, ...
        "simulink_handoff_relative",1e-12, ...
        "simulink_net_reactance_relative",1e-8, ...
        "segment_refinement_relative",0.01, ...
        "wheeler_reference_relative",0.12), ...
    "errors",struct( ...
        "target_frequency_relative",targetError, ...
        "frequency_root_reactance_relative", ...
            refinedRoot.relative_reactance_residual, ...
        "ltspice_vs_peec_root_relative",ltspiceError, ...
        "simulink_inductance_handoff_relative",modelInductanceError, ...
        "simulink_resistance_handoff_relative",modelResistanceError, ...
        "simulink_reactance_handoff_relative",modelReactanceError, ...
        "simulink_frequency_handoff_relative",modelFrequencyError, ...
        "simulink_net_reactance_relative",modelNetReactanceRelative, ...
        "segment_refinement_relative",refinementRelative, ...
        "wheeler_reference_relative", ...
            refinedDC.wheeler_relative_difference), ...
    "tool_versions",struct( ...
        "radia",projectVersion(), ...
        "radia_native",string(radia.UtiVer()), ...
        "matlab",string(version), ...
        "simulink",string(simulinkInfo.Version), ...
        "ltspice",executableVersion(executable)), ...
    "target",struct( ...
        "frequency_Hz",target, ...
        "fixed_capacitance_F",capacitance, ...
        "inductance_identity_at_target_H",requiredInductance), ...
    "frequency_dependent_contract",struct( ...
        "root_equation","imag(Z_coil(f)+1/(j*2*pi*f*C))=0", ...
        "internal_impedance_model","equivalent-round-bessel", ...
        "peec_inductance_basis","uniform-current DC partial inductance", ...
        "proximity_effect_included",false, ...
        "ltspice_role","narrow-band R_eff/L_eff cross-check at converged f"), ...
    "simulink_model",struct( ...
        "file",portableArtifactPath(options.ModelFile), ...
        "equation","X_in = Im(Z_PEEC(f_eval)) - 1/(2*pi*f_eval*C)", ...
        "measured_inductance_H",modelInductance, ...
        "measured_resistance_Ohm",modelResistance, ...
        "measured_coil_reactance_Ohm",modelReactance, ...
        "measured_frequency_Hz",modelFrequency, ...
        "measured_net_reactance_Ohm",modelNetReactance), ...
    "fixed_geometry",struct( ...
        "turn_count",options.TurnCount, ...
        "pitch_m",options.Pitch_m, ...
        "wire_width_m",options.WireWidth_m, ...
        "wire_height_m",options.WireHeight_m, ...
        "conductivity_S_per_m",options.Conductivity_S_per_m, ...
        "segments_per_turn",options.SegmentsPerTurn, ...
        "refinement_segments_per_turn",options.RefinementSegmentsPerTurn), ...
    "search",struct( ...
        "parameter","radius_m", ...
        "bounds_m",radiusBounds, ...
        "sampler","TPE", ...
        "seed",options.Seed, ...
        "requested_trials",options.NumTrials, ...
        "completed_trials",sum(completed), ...
        "failed_trials",sum(failed), ...
        "tpe_best_trial_number",best.trial_number, ...
        "tpe_best_radius_m",tpeBestRadius, ...
        "tpe_best_frequency_Hz",tpeBestFrequency, ...
        "tpe_best_target_relative_error",tpeBestTargetError, ...
        "post_tpe_scalar_polish_iterations",options.RadiusPolishIterations), ...
    "feasibility",struct( ...
        "lower_radius_frequency_Hz",lowerRoot.frequency_Hz, ...
        "upper_radius_frequency_Hz",upperRoot.frequency_Hz, ...
        "target_bracketed",targetBracketed), ...
    "best",struct( ...
        "radius_m",bestRadius, ...
        "dc_inductance_H",refinedDC.inductance_H, ...
        "effective_inductance_H",refinedRoot.inductance_H, ...
        "effective_resistance_Ohm",refinedRoot.resistance_Ohm, ...
        "coil_reactance_Ohm",refinedRoot.coil_reactance_Ohm, ...
        "frequency_Hz",refinedRoot.frequency_Hz, ...
        "target_relative_error",targetError, ...
        "frequency_shift_from_dc_relative", ...
            refinedRoot.frequency_shift_from_dc_relative, ...
        "frequency_iteration_count",refinedRoot.iteration_count, ...
        "frequency_evaluation_count",refinedRoot.evaluation_count, ...
        "frequency_root_relative_residual", ...
            refinedRoot.relative_reactance_residual, ...
        "ltspice_local_equivalent_frequency_Hz",measuredFrequency, ...
        "ltspice_measurement",measurement), ...
    "cross_validation",struct( ...
        "peec_segment_refinement_relative",refinementRelative, ...
        "wheeler_reference_H",refinedDC.wheeler_reference_H, ...
        "wheeler_relative_difference",refinedDC.wheeler_relative_difference, ...
        "ltspice_vs_peec_root_relative",ltspiceError, ...
        "simulink_inductance_handoff_relative",modelInductanceError, ...
        "simulink_resistance_handoff_relative",modelResistanceError, ...
        "simulink_reactance_handoff_relative",modelReactanceError, ...
        "simulink_frequency_handoff_relative",modelFrequencyError, ...
        "simulink_net_reactance_relative",modelNetReactanceRelative, ...
        "target_inductance_identity_relative",inductanceError), ...
    "frequency_iteration_history",struct( ...
        "frequency_Hz",refinedRoot.history.frequency_Hz, ...
        "net_reactance_Ohm",refinedRoot.history.net_reactance_Ohm, ...
        "resistance_Ohm",refinedRoot.history.resistance_Ohm, ...
        "inductance_H",refinedRoot.history.inductance_H), ...
    "radius_polish_history",polishHistory, ...
    "trial_history",struct( ...
        "trial_number",trialNumbers(validRecords), ...
        "radius_m",trialRadii(validRecords), ...
        "dc_inductance_H",trialDCInductances(validRecords), ...
        "effective_inductance_H",trialInductances(validRecords), ...
        "effective_resistance_Ohm",trialResistances(validRecords), ...
        "wheeler_reference_H",trialWheeler(validRecords), ...
        "peec_resonance_frequency_Hz",trialFrequencies(validRecords), ...
        "ltspice_frequency_Hz",trialLTspiceFrequencies(validRecords), ...
        "frequency_root_iterations",trialIterations(validRecords), ...
        "objective",trialObjectives(validRecords)), ...
    "gates",gates, ...
    "timing_breakdown_s",struct( ...
        "setup_and_feasibility",setup_s, ...
        "tpe_optimization",optimization_s, ...
        "radius_polish_and_segment_refinement",refinement_s, ...
        "final_replay_and_frequency_sweep",replay_s, ...
        "visualization",visualization_s), ...
    "verification",struct( ...
        "method",["frequency-dependent PEEC root, Simulink R/X/f " ...
            "handoff, LTspice narrow-band equivalent, segment refinement, " ...
            "and Wheeler scale check"], ...
        "objective_domain","frequency", ...
        "command","validate_ltspice_coil_geometry_resonance"));
writeJSON(options.ResultPath,result);
result.result_file = options.ResultPath;

    function coil = buildCoil(radius,segmentsPerTurn)
        coil = radia.peec.circularTurnStack(radius,options.TurnCount, ...
            SegmentsPerTurn=segmentsPerTurn, ...
            Pitch_m=options.Pitch_m, ...
            WireWidth_m=options.WireWidth_m, ...
            WireHeight_m=options.WireHeight_m, ...
            Conductivity_S_per_m=options.Conductivity_S_per_m);
    end

    function simulationInput = configureTrial(simulationInput,trial)
        radius = trial.suggestFloat("radius_m", ...
            radiusBounds(1),radiusBounds(2));
        coil = buildCoil(radius,options.SegmentsPerTurn);
        dc = radia.peec.seriesCoilProperties(coil);
        root = radia.peec.solveSeriesResonance( ...
            coil,capacitance,DCProperties=dc);
        recordCount = recordCount+1;
        row = recordCount;
        trialNumbers(row) = trial.Number;
        trialRadii(row) = radius;
        trialDCInductances(row) = dc.inductance_H;
        trialInductances(row) = root.inductance_H;
        trialResistances(row) = root.resistance_Ohm;
        trialReactances(row) = root.coil_reactance_Ohm;
        trialWheeler(row) = dc.wheeler_reference_H;
        trialFrequencies(row) = root.frequency_Hz;
        trialIterations(row) = root.iteration_count;
        trial.setUserAttr("coil_peec",struct( ...
            "radius_m",radius, ...
            "dc_inductance_H",dc.inductance_H, ...
            "effective_inductance_H",root.inductance_H, ...
            "effective_resistance_Ohm",root.resistance_Ohm, ...
            "frequency_Hz",root.frequency_Hz, ...
            "frequency_root_relative_residual", ...
                root.relative_reactance_residual, ...
            "segment_count",dc.segment_count));
        simulationInput = configureModelSnapshot(simulationInput,root);
    end

    function simulationInput = configureModelSnapshot(simulationInput,root)
        simulationInput = simulationInput.setVariable( ...
            "R_coil_Ohm",root.resistance_Ohm);
        simulationInput = simulationInput.setVariable( ...
            "X_coil_Ohm",root.coil_reactance_Ohm);
        simulationInput = simulationInput.setVariable( ...
            "L_eff_H",root.inductance_H);
        simulationInput = simulationInput.setVariable("C_F",capacitance);
        simulationInput = simulationInput.setVariable( ...
            "f_eval_Hz",root.frequency_Hz);
    end

    function value = scoreTrial(simulationOutput,trial)
        row = trialRow(trial);
        trialModelInductances(row) = finalTimeseriesValue( ...
            simulationOutput.get("peec_effective_inductance"));
        trialModelResistances(row) = finalTimeseriesValue( ...
            simulationOutput.get("peec_effective_resistance"));
        trialModelReactances(row) = finalTimeseriesValue( ...
            simulationOutput.get("peec_coil_reactance"));
        trialModelFrequencies(row) = finalTimeseriesValue( ...
            simulationOutput.get("evaluation_frequency"));
        trialModelNetReactances(row) = finalTimeseriesValue( ...
            simulationOutput.get("input_reactance"));
        runResult = radia.ltspice.run(options.NetlistFile, ...
            Parameters=struct( ...
                "Rval",trialResistances(row), ...
                "Lval",trialInductances(row), ...
                "Cval",capacitance), ...
            Executable=executable, ...
            OutputDirectory=fullfile(options.OutputDirectory,"trials", ...
                sprintf("trial_%06d",trial.Number)), ...
            RawFormat="binary");
        [frequency_Hz,trialMeasurement] = ...
            radia.ltspice.measureSeriesResonance(runResult);
        value = log(trialFrequencies(row)/target)^2;
        trialLTspiceFrequencies(row) = frequency_Hz;
        trialObjectives(row) = value;
        trialRawFiles(row) = string(runResult.raw_file);
        trialLogFiles(row) = string(runResult.log_file);
        trial.setUserAttr("ltspice_ac_resonance",struct( ...
            "role","narrow-band equivalent at converged PEEC frequency", ...
            "frequency_Hz",frequency_Hz, ...
            "measurement",trialMeasurement, ...
            "elapsed_s",runResult.elapsed_s));
    end

    function validation = validateTrial(~,trial)
        row = trialRow(trial);
        ltspiceRelative = abs(trialLTspiceFrequencies(row)- ...
            trialFrequencies(row))/trialFrequencies(row);
        inductanceHandoff = abs(trialModelInductances(row)- ...
            trialInductances(row))/trialInductances(row);
        resistanceHandoff = abs(trialModelResistances(row)- ...
            trialResistances(row))/trialResistances(row);
        reactanceHandoff = abs(trialModelReactances(row)- ...
            trialReactances(row))/trialReactances(row);
        frequencyHandoff = abs(trialModelFrequencies(row)- ...
            trialFrequencies(row))/trialFrequencies(row);
        netReactanceRelative = abs(trialModelNetReactances(row))/ ...
            max(abs(trialReactances(row)),eps);
        validation = struct( ...
            "ltspice_vs_peec_root_relative",ltspiceRelative, ...
            "inductance_handoff_relative",inductanceHandoff, ...
            "resistance_handoff_relative",resistanceHandoff, ...
            "reactance_handoff_relative",reactanceHandoff, ...
            "frequency_handoff_relative",frequencyHandoff, ...
            "net_reactance_relative",netReactanceRelative, ...
            "passed",ltspiceRelative <= 5e-5 && ...
                inductanceHandoff <= 1e-12 && ...
                resistanceHandoff <= 1e-12 && ...
                reactanceHandoff <= 1e-12 && ...
                frequencyHandoff <= 1e-12 && ...
                netReactanceRelative <= 1e-8);
    end

    function artifacts = trialArtifacts(~,trial)
        row = trialRow(trial);
        validation = validateTrial([],trial);
        trial.setUserAttr("cae_validation",validation);
        if ~validation.passed
            error("radia:ltspice:CoilTrialValidation", ...
                "The PEEC/Simulink/LTspice trial validation failed.");
        end
        artifacts = struct( ...
            "ltspice_raw",trialRawFiles(row), ...
            "ltspice_log",trialLogFiles(row), ...
            "radius_m",trialRadii(row), ...
            "peec_dc_inductance_H",trialDCInductances(row), ...
            "peec_effective_inductance_H",trialInductances(row), ...
            "peec_effective_resistance_Ohm",trialResistances(row), ...
            "peec_frequency_Hz",trialFrequencies(row), ...
            "ltspice_frequency_Hz",trialLTspiceFrequencies(row), ...
            "validation",validation);
    end

    function row = trialRow(trial)
        row = find(trialNumbers == trial.Number,1);
        if isempty(row)
            error("radia:ltspice:CoilTrialIdentity", ...
                "No PEEC geometry record exists for trial %d.",trial.Number);
        end
    end

    function [radius,coil,dc,root,history] = polishRadius()
        [lowState,lowResidual] = evaluateRadius( ...
            radiusBounds(1),options.RefinementSegmentsPerTurn);
        [highState,highResidual] = evaluateRadius( ...
            radiusBounds(2),options.RefinementSegmentsPerTurn);
        historyRadius = [radiusBounds(1);radiusBounds(2)];
        historyFrequency = [lowState.root.frequency_Hz; ...
            highState.root.frequency_Hz];
        bestState = lowState;
        if abs(highResidual) < abs(lowResidual)
            bestState = highState;
        end
        lowRadius = radiusBounds(1);
        highRadius = radiusBounds(2);
        polishStep = 0;
        while polishStep < options.RadiusPolishIterations
            polishStep = polishStep+1;
            % A deterministic bisection is cheap relative to rebuilding the
            % refined PEEC operator and cannot stall on one bracket endpoint.
            candidate = 0.5*(lowRadius+highRadius);
            [candidateState,candidateResidual] = evaluateRadius( ...
                candidate,options.RefinementSegmentsPerTurn);
            historyRadius(end+1,1) = candidate; %#ok<AGROW>
            historyFrequency(end+1,1) = ...
                candidateState.root.frequency_Hz; %#ok<AGROW>
            if abs(candidateResidual) < ...
                    abs(bestState.root.frequency_Hz-target)
                bestState = candidateState;
            end
            if candidateResidual == 0
                bestState = candidateState;
                break
            elseif sign(candidateResidual) == sign(lowResidual)
                lowRadius = candidate;
                lowResidual = candidateResidual;
            else
                highRadius = candidate;
            end
        end
        radius = bestState.radius;
        coil = bestState.coil;
        dc = bestState.dc;
        root = bestState.root;
        history = struct( ...
            "radius_m",historyRadius, ...
            "frequency_Hz",historyFrequency, ...
            "target_error_Hz",historyFrequency-target);
    end

    function [state,residual] = evaluateRadius(radius,segmentsPerTurn)
        coil = buildCoil(radius,segmentsPerTurn);
        dc = radia.peec.seriesCoilProperties(coil);
        root = radia.peec.solveSeriesResonance( ...
            coil,capacitance,DCProperties=dc);
        state = struct("radius",radius,"coil",coil,"dc",dc,"root",root);
        residual = root.frequency_Hz-target;
    end
end

function value = finalTimeseriesValue(signal)
if ~isa(signal,"timeseries") || isempty(signal.Data)
    error("radia:ltspice:CoilSimulinkLog", ...
        "The Simulink PEEC parameter log must be a nonempty timeseries.");
end
value = double(signal.Data(end));
end

function ensureParent(path)
folder = string(fileparts(path));
if strlength(folder) > 0 && ~isfolder(folder)
    mkdir(folder);
end
end

function writeJSON(path,value)
file = fopen(path,"w");
if file < 0
    error("radia:ltspice:CoilResultWrite", ...
        "Unable to write the result file: %s",path);
end
cleanup = onCleanup(@() fclose(file));
fprintf(file,"%s\n",jsonencode(value,PrettyPrint=true));
clear cleanup
end

function value = projectVersion()
matlabRoot = radia.simulink.exampleDirectory();
text = fileread(fullfile(fileparts(matlabRoot),"pyproject.toml"));
token = regexp(text,'(?m)^version\s*=\s*"([^"]+)"',"tokens","once");
if isempty(token)
    value = "unknown";
else
    value = string(token{1});
end
end

function value = portableArtifactPath(path)
absolutePath = string(java.io.File(char(path)).getCanonicalPath());
repoRoot = string(java.io.File(char(fileparts( ...
    radia.simulink.exampleDirectory()))).getCanonicalPath());
prefix = repoRoot+string(filesep);
if startsWith(lower(absolutePath),lower(prefix))
    value = extractAfter(absolutePath,strlength(prefix));
    value = replace(value,"\","/");
    return
end
[~,name,extension] = fileparts(absolutePath);
value = "<runtime-output>/"+string(name)+string(extension);
end

function value = executableVersion(executable)
value = "unknown";
if ispc
    try
        info = System.Diagnostics.FileVersionInfo.GetVersionInfo(char(executable));
        value = string(info.FileVersion);
    catch
        value = "unknown";
    end
end
end

function value = utcTimestamp()
value = string(datetime("now","TimeZone","UTC", ...
    "Format","yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end

function applyLightAxesStyle(figureHandle)
axesHandles = findall(figureHandle,"Type","axes");
for index = 1:numel(axesHandles)
    axesHandle = axesHandles(index);
    set(axesHandle,"Color","white","XColor",[0.15 0.15 0.15], ...
        "GridColor",[0.45 0.45 0.45]);
    axesHandle.Title.Color = [0.12 0.12 0.12];
    for axisIndex = 1:numel(axesHandle.YAxis)
        axesHandle.YAxis(axisIndex).Color = [0.15 0.15 0.15];
    end
    if ~isempty(axesHandle.ZAxis)
        axesHandle.ZAxis.Color = [0.15 0.15 0.15];
    end
end
legends = findall(figureHandle,"Type","legend");
for index = 1:numel(legends)
    set(legends(index),"Color","white", ...
        "TextColor",[0.12 0.12 0.12], ...
        "EdgeColor",[0.45 0.45 0.45]);
end
constantLines = findall(figureHandle,"Type","constantline");
for index = 1:numel(constantLines)
    constantLines(index).LabelColor = [0.2 0.2 0.2];
end
end
