function result = runRLCResonanceOptimizationDemo(options)
%RUNRLCRESONANCEOPTIMIZATIONDEMO Tune series-RLC C with LTspice AC solves.
arguments
    options.TargetFrequency_Hz (1,1) double {mustBePositive,mustBeFinite} = 1000
    options.Resistance_Ohm (1,1) double {mustBeNonnegative,mustBeFinite} = 2
    options.Inductance_H (1,1) double {mustBePositive,mustBeFinite} = 10e-3
    options.CapacitanceBounds_F (1,2) double {mustBePositive,mustBeFinite} = [1e-6 6e-6]
    options.NumTrials (1,1) double {mustBeInteger,mustBePositive} = 32
    options.Seed (1,1) double {mustBeInteger,mustBeNonnegative} = 42
    options.NetlistFile (1,1) string = fullfile( ...
        fileparts(fileparts(fileparts(mfilename("fullpath")))), ...
        "samples", "ltspice_rlc_resonance_ac.cir")
    options.Executable (1,1) string = ""
    options.OutputDirectory (1,1) string = "C:\temp\radia_ltspice_rlc_resonance"
    options.StoragePath (1,1) string = ""
    options.ResultPath (1,1) string = ""
    options.PlotPath (1,1) string = ""
    options.ResetStudy (1,1) logical = true
    options.CrossCheckModelFile (1,1) string = fullfile( ...
        radia.simulink.exampleDirectory(), "radia_rlc_resonance_plant.slx")
    options.RequireTimeDomainCrossCheck (1,1) logical = false
    options.ShowFigure (1,1) logical = false
end

if ~isfile(options.NetlistFile)
    error("radia:ltspice:RLCNetlist", ...
        "The RLC AC netlist does not exist: %s", options.NetlistFile);
end
if options.CapacitanceBounds_F(1) >= options.CapacitanceBounds_F(2)
    error("radia:ltspice:RLCBounds", ...
        "CapacitanceBounds_F must be strictly increasing.");
end
if ~isfolder(options.OutputDirectory)
    mkdir(options.OutputDirectory);
end
if strlength(options.StoragePath) == 0
    options.StoragePath = fullfile(options.OutputDirectory, ...
        "rlc_ac_resonance_study.mat");
end
if strlength(options.ResultPath) == 0
    options.ResultPath = fullfile(options.OutputDirectory, ...
        "results_ltspice_rlc_ac_resonance.json");
end
if strlength(options.PlotPath) == 0
    options.PlotPath = fullfile(options.OutputDirectory, ...
        "ltspice_rlc_ac_resonance.png");
end
ensureParent(options.StoragePath);
ensureParent(options.ResultPath);
ensureParent(options.PlotPath);
if options.ResetStudy && isfile(options.StoragePath)
    delete(options.StoragePath);
end

totalTimer = tic;
target = options.TargetFrequency_Hz;
resistance = options.Resistance_Ohm;
inductance = options.Inductance_H;
bounds = options.CapacitanceBounds_F;
analyticCapacitance = 1 / (inductance*(2*pi*target)^2);
if analyticCapacitance < bounds(1) || analyticCapacitance > bounds(2)
    error("radia:ltspice:RLCTargetOutsideBounds", ...
        "The AC target requires C=%.9g F, outside the search bounds.", ...
        analyticCapacitance);
end

executable = radia.ltspice.findExecutable(Executable=options.Executable);
trialRoot = fullfile(options.OutputDirectory, "trials");
startupTrials = min(6, max(1, floor(options.NumTrials/4)));
study = radia.optuna.createStudy( ...
    study_name="ltspice-rlc-ac-resonance", direction="minimize", ...
    sampler=radia.optuna.TPESampler( ...
        Seed=options.Seed, NStartupTrials=startupTrials, ...
        NumberOfEIChoices=48), ...
    StoragePath=options.StoragePath, AutoSave=true);
runner = radia.optuna.LTspiceRunner(options.NetlistFile, ...
    ConfigureFcn=@configureTrial, ScoreFcn=@scoreTrial, ...
    ResultFcn=@recordTrial, Executable=executable, OutputRoot=trialRoot);

optimizationTimer = tic;
runner.optimize(study, options.NumTrials);
optimization_s = toc(optimizationTimer);
best = study.bestSolution();
if ~best.available || ~isfield(best.params, "capacitance_F")
    error("radia:ltspice:RLCNoBestTrial", ...
        "The LTspice AC optimization did not produce a completed trial.");
end

bestCapacitance = double(best.params.capacitance_F);
finalSolveTimer = tic;
finalDirectory = fullfile(options.OutputDirectory, "best_ac_replay");
finalRun = radia.ltspice.run(options.NetlistFile, ...
    Parameters=struct("Rval", resistance, "Lval", inductance, ...
        "Cval", bestCapacitance), ...
    Executable=executable, OutputDirectory=finalDirectory, RawFormat="binary");
[measuredFrequency, measurement] = ...
    radia.ltspice.measureSeriesResonance(finalRun);
raw = radia.ltspice.RawRead(finalRun.raw_file);
frequency = real(raw.getTrace("frequency"));
sourceCurrent = raw.getTrace("I(Vdrive)");
inputVoltage = raw.getTrace("V(in)");
inputImpedance = -inputVoltage ./ sourceCurrent;
if median(real(inputImpedance)) < 0
    inputImpedance = -inputImpedance;
end
final_solve_s = toc(finalSolveTimer);

theory = radia.simulink.analyzeRLCResonance( ...
    resistance, inductance, bestCapacitance);
targetError = abs(measuredFrequency-target)/target;
theoryError = abs(measuredFrequency-theory.series_current_peak_frequency_Hz) / ...
    theory.series_current_peak_frequency_Hz;
capacitanceError = abs(bestCapacitance-analyticCapacitance) / ...
    analyticCapacitance;

crossCheckTimer = tic;
timeCrossCheck = struct("available", false, "passed", false);
if isfile(options.CrossCheckModelFile)
    in = Simulink.SimulationInput(options.CrossCheckModelFile);
    in = in.setVariable("R_ohm", resistance);
    in = in.setVariable("L_H", inductance);
    in = in.setVariable("C_F", bestCapacitance);
    out = sim(in);
    [ringdownFrequency, ringdownMeasurement] = ...
        radia.simulink.measureRingdownFrequency(out.get("ring_voltage"));
    ringdownError = abs(ringdownFrequency-theory.ringdown_frequency_Hz) / ...
        theory.ringdown_frequency_Hz;
    timeCrossCheck = struct( ...
        "available", true, ...
        "passed", ringdownError <= 1e-3, ...
        "model_file", options.CrossCheckModelFile, ...
        "measured_ringdown_frequency_Hz", ringdownFrequency, ...
        "analytic_ringdown_frequency_Hz", theory.ringdown_frequency_Hz, ...
        "measurement_relative_error", ringdownError, ...
        "ac_minus_ringdown_frequency_Hz", ...
            measuredFrequency-ringdownFrequency, ...
        "measurement", ringdownMeasurement);
elseif options.RequireTimeDomainCrossCheck
    error("radia:ltspice:RLCCrossCheckModel", ...
        "The required Simulink cross-check model does not exist: %s", ...
        options.CrossCheckModelFile);
end
crosscheck_s = toc(crossCheckTimer);

completed = study.TrialTable.State == "COMPLETE";
failed = study.TrialTable.State == "FAIL";
completeTrials = study.TrialTable(completed,:);
trialNumbers = completeTrials.TrialNumber;
objectives = completeTrials.Value;
capacitances = cellfun(@(value) double(value.capacitance_F), ...
    completeTrials.Params);

visualizationTimer = tic;
visible = "off";
if options.ShowFigure
    visible = "on";
end
figureHandle = figure("Visible", visible, "Color", "white", ...
    "Position", [100 100 1000 720]);
layout = tiledlayout(figureHandle, 2, 1, ...
    "TileSpacing", "compact", "Padding", "compact");
layoutTitle = title(layout, ...
    sprintf("LTspice AC series-RLC optimization: target %.0f Hz", target));
layoutTitle.Color = [0.12 0.12 0.12];

responseAxes = nexttile(layout, 1);
yyaxis(responseAxes, "left");
plot(responseAxes, frequency, abs(sourceCurrent), "LineWidth", 1.3);
ylabel(responseAxes, "|I_{source}| (A)");
yyaxis(responseAxes, "right");
plot(responseAxes, frequency, imag(inputImpedance), "LineWidth", 1.1);
yline(responseAxes, 0, ":");
xline(responseAxes, target, "--", "Target");
xline(responseAxes, measuredFrequency, "-.", "Measured");
xlabel(responseAxes, "Frequency (Hz)");
ylabel(responseAxes, "Im(Z_{in}) (Ohm)");
grid(responseAxes, "on");
set(responseAxes, "Color", "white", "XColor", [0.15 0.15 0.15], ...
    "GridColor", [0.35 0.35 0.35]);
responseAxes.YAxis(1).Color = [0 0.35 0.72];
responseAxes.YAxis(2).Color = [0.85 0.25 0.05];
responseTitle = title(responseAxes, sprintf( ...
    "Best C = %.6g uF, Im(Z)=0 at %.3f Hz", ...
    bestCapacitance*1e6, measuredFrequency));
responseTitle.Color = [0.12 0.12 0.12];

historyAxes = nexttile(layout, 2);
yyaxis(historyAxes, "left");
semilogy(historyAxes, trialNumbers, max(objectives, realmin), ...
    "o-", "LineWidth", 1.1);
ylabel(historyAxes, "Objective: log(f/f_{target})^2");
yyaxis(historyAxes, "right");
plot(historyAxes, trialNumbers, capacitances*1e6, ".-", ...
    "LineWidth", 1.1, "MarkerSize", 13);
yline(historyAxes, analyticCapacitance*1e6, "--", "Analytic C");
xlabel(historyAxes, "Trial number");
ylabel(historyAxes, "Capacitance (uF)");
grid(historyAxes, "on");
set(historyAxes, "Color", "white", "XColor", [0.15 0.15 0.15], ...
    "GridColor", [0.35 0.35 0.35]);
historyAxes.YAxis(1).Color = [0 0.35 0.72];
historyAxes.YAxis(2).Color = [0.85 0.25 0.05];
exportgraphics(layout, options.PlotPath, "Resolution", 160);
visualization_s = toc(visualizationTimer);
if ~options.ShowFigure
    close(figureHandle);
end

allTrialsCompleted = sum(completed) == options.NumTrials;
crossCheckPassed = ~options.RequireTimeDomainCrossCheck || ...
    (timeCrossCheck.available && timeCrossCheck.passed);
gates = struct( ...
    "all_trials_completed", allTrialsCompleted, ...
    "target_within_2_percent", targetError <= 0.02, ...
    "ac_measurement_within_0_05_percent", theoryError <= 5e-4, ...
    "impedance_zero_matches_current_peak", ...
        measurement.zero_vs_peak_relative_difference <= 5e-4, ...
    "capacitance_within_3_percent", capacitanceError <= 0.03, ...
    "time_domain_crosscheck", crossCheckPassed);
pass = ~any(~struct2array(gates));
simulinkInfo = ver("simulink");
result = struct( ...
    "radia_version", projectVersion(), ...
    "schema", "cae-ai-lab.solver-run.v1", ...
    "created_at_utc", utcTimestamp(), ...
    "case", "series RLC capacitance optimization at 1 kHz", ...
    "solver", "matlab", ...
    "solver_backend", "ltspice-ac", ...
    "source_artifact", options.NetlistFile, ...
    "pass", pass, ...
    "run", struct( ...
        "command", "radia.ltspice.run(..., RawFormat='binary')", ...
        "workdir", options.OutputDirectory, ...
        "exit_code", 0, ...
        "duration_s", toc(totalTimer), ...
        "stdout_log", finalRun.log_file), ...
    "result_files", [options.ResultPath, options.PlotPath, options.NetlistFile], ...
    "checks", struct( ...
        "ran_to_completion", true, ...
        "result_files_exist", isfile(options.PlotPath) && isfile(options.NetlistFile), ...
        "validation_passed", pass), ...
    "tolerances", struct( ...
        "target_relative", 0.02, ...
        "ac_theory_relative", 5e-4, ...
        "time_crosscheck_relative", 1e-3), ...
    "errors", struct( ...
        "target_relative", targetError, ...
        "ac_theory_relative", theoryError, ...
        "capacitance_relative", capacitanceError), ...
    "tool_versions", struct( ...
        "radia", projectVersion(), ...
        "matlab", string(version), ...
        "simulink", string(simulinkInfo.Version), ...
        "ltspice", executableVersion(executable)), ...
    "target_frequency_Hz", target, ...
    "fixed_components", struct( ...
        "resistance_Ohm", resistance, "inductance_H", inductance), ...
    "search", struct( ...
        "parameter", "capacitance_F", ...
        "bounds_F", bounds, ...
        "sampler", "TPE", ...
        "seed", options.Seed, ...
        "requested_trials", options.NumTrials, ...
        "completed_trials", sum(completed), ...
        "failed_trials", sum(failed)), ...
    "best", struct( ...
        "trial_number", best.trial_number, ...
        "objective", best.value, ...
        "capacitance_F", bestCapacitance, ...
        "measured_ac_resonance_frequency_Hz", measuredFrequency, ...
        "analytic_ac_resonance_frequency_Hz", ...
            theory.series_current_peak_frequency_Hz, ...
        "target_relative_error", targetError, ...
        "measurement_vs_theory_relative_error", theoryError, ...
        "measurement", measurement), ...
    "analytic_optimum", struct( ...
        "capacitance_F", analyticCapacitance, ...
        "best_capacitance_relative_error", capacitanceError), ...
    "simulink_time_domain_crosscheck", timeCrossCheck, ...
    "gates", gates, ...
    "timing_breakdown_s", struct( ...
        "optimization", optimization_s, ...
        "best_ac_solve", final_solve_s, ...
        "time_domain_crosscheck", crosscheck_s, ...
        "visualization", visualization_s), ...
    "verification", struct( ...
        "method", "LTspice Im(Zin)=0 and |I| peak versus analytic series-RLC identity", ...
        "command", "validate_ltspice_rlc_resonance_ac"));
writeJSON(options.ResultPath, result);
result.result_file = options.ResultPath;

    function parameters = configureTrial(trial)
        capacitance = trial.suggestFloat( ...
            "capacitance_F", bounds(1), bounds(2), Log=true);
        parameters = struct( ...
            "Rval", resistance, "Lval", inductance, "Cval", capacitance);
    end

    function value = scoreTrial(runResult, ~)
        frequency_Hz = radia.ltspice.measureSeriesResonance(runResult);
        value = log(frequency_Hz/target)^2;
    end

    function recordTrial(runResult, trial)
        [frequency_Hz, trialMeasurement] = ...
            radia.ltspice.measureSeriesResonance(runResult);
        trial.setUserAttr("ltspice_ac_resonance", struct( ...
            "frequency_Hz", frequency_Hz, ...
            "capacitance_F", trial.Params.capacitance_F, ...
            "measurement", trialMeasurement, ...
            "elapsed_s", runResult.elapsed_s));
    end
end

function ensureParent(path)
folder = string(fileparts(path));
if strlength(folder) > 0 && ~isfolder(folder)
    mkdir(folder);
end
end

function writeJSON(path, value)
file = fopen(path, "w");
if file < 0
    error("radia:ltspice:RLCResultWrite", ...
        "Unable to write the result file: %s", path);
end
cleanup = onCleanup(@() fclose(file));
fprintf(file, "%s\n", jsonencode(value, PrettyPrint=true));
clear cleanup
end

function value = projectVersion()
matlabRoot = radia.simulink.exampleDirectory();
text = fileread(fullfile(fileparts(matlabRoot), "pyproject.toml"));
token = regexp(text, '(?m)^version\s*=\s*"([^"]+)"', "tokens", "once");
if isempty(token)
    value = "unknown";
else
    value = string(token{1});
end
end

function value = executableVersion(executable)
value = "unknown";
if ispc
    try
        info = System.Diagnostics.FileVersionInfo.GetVersionInfo(char(executable));
        value = string(info.FileVersion);
    catch
        value = "unknown";
    end
end
end

function value = utcTimestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end
