function report = verify_radia_simulink_release()
%VERIFY_RADIA_SIMULINK_RELEASE Verify an extracted full Radia library package.
matlabRoot = fileparts(mfilename("fullpath"));
pathWasPresent = isPathEntry(matlabRoot);
if ~pathWasPresent
    addpath(matlabRoot, "-begin");
end
cleanupPath = onCleanup(@() removePathIfAdded(matlabRoot, pathWasPresent));

required = ["radia_simulink_library.slx", "radia_ih.slx", ...
    "radia_electromagnet.slx", "radia_maglev.slx", ...
    "radia_streamfunction_optimization.slx", "install_radia_simulink.m", ...
    "radia_mex." + mexext, "radia_ih_eddy_sfun.m", ...
    "radia_ih_thermal_sfun.m"];
missing = required(~isfile(fullfile(matlabRoot, required)));
if ~isempty(missing)
    error("radia:simulink:ReleaseMissing", ...
        "Radia Simulink release is missing: %s", strjoin(missing, ", "));
end

setupInfo = radia.setup(RequireMex=true,Force=true);
if ~setupInfo.mex_available
    error("radia:simulink:ReleaseMex", ...
        "The full library package did not load radia_mex.");
end
api = radia.apiInfo();

libraryPath = fullfile(matlabRoot, "radia_simulink_library.slx");
load_system(libraryPath);
cleanupLibrary = onCleanup(@() closeIfLoaded("radia_simulink_library"));
if string(get_param("radia_simulink_library", "BlockDiagramType")) ~= "library"
    error("radia:simulink:ReleaseLibrary", ...
        "radia_simulink_library.slx is not a Simulink library.");
end
motorPath = ...
    "radia_simulink_library/Reduced Models/Motor Angle Family";
if getSimulinkBlockHandle(motorPath) <= 0 || ...
        string(get_param(motorPath, "FunctionName")) ~= ...
        "radia_motor_angle_family_mex_sfunction"
    error("radia:simulink:ReleaseMotorBlock", ...
        "The native Motor Angle Family block is absent or miswired.");
end
motorContract = get_param(motorPath, "UserData");
if string(motorContract.backend) ~= ...
        "native-mex-periodic-interpolation" || motorContract.python_per_step
    error("radia:simulink:ReleaseMotorBackend", ...
        "The Motor Angle Family block backend contract is invalid.");
end

maglevBlockPath = ...
    "radia_simulink_library/Applications/Magnetic Levitation";
if getSimulinkBlockHandle(maglevBlockPath) <= 0 || ...
        string(get_param(maglevBlockPath, "BlockType")) ~= "SubSystem" || ...
        string(get_param(maglevBlockPath + "/Moving HCurl CLN", ...
        "FunctionName")) ~= "radia_hcurl_eddy_cln_family_sfunction"
    error("radia:simulink:ReleaseMagLevBlock", ...
        "The common-basis MagLev block is absent or miswired.");
end
maglevContract = get_param(maglevBlockPath, "UserData");
if string(maglevContract.backend) ~= ...
        "matlab-level2-common-basis-cln" || ...
        maglevContract.python_per_step || maglevContract.surrogate
    error("radia:simulink:ReleaseMagLevBackend", ...
        "The MagLev block backend contract is invalid.");
end

electromagnetBlockPath = ...
    "radia_simulink_library/Applications/Electromagnet Topology Optimization";
if getSimulinkBlockHandle(electromagnetBlockPath) <= 0 || ...
        string(get_param(electromagnetBlockPath,"BlockType")) ~= ...
        "SubSystem" || string(get_param(electromagnetBlockPath + ...
        "/Density Topology Optimization","FunctionName")) ~= ...
        "radia_electromagnet_topology_sfun"
    error("radia:simulink:ReleaseElectromagnetTopologyBlock", ...
        "The electromagnet topology block is absent or miswired.");
end
electromagnetContract = get_param(electromagnetBlockPath,"UserData");
if string(electromagnetContract.adjoint_backend) ~= ...
        "matlab-native-vim-density-adjoint" || ...
        electromagnetContract.state_solves_per_gradient ~= 1 || ...
        electromagnetContract.adjoint_solves_per_gradient ~= 1 || ...
        electromagnetContract.finite_difference_fallback || ...
        electromagnetContract.python_per_optimization_step
    error("radia:simulink:ReleaseElectromagnetTopologyBackend", ...
        "The electromagnet topology backend contract is invalid.");
end

grid = [0; pi];
period = 2*pi;
A = reshape([1.0, 0.5], 1, 1, 2);
B = reshape([1.0, 3.0], 1, 1, 2);
C = reshape([1.0, 3.0], 1, 1, 2);
D = zeros(1, 1, 2);
Q = reshape([2.0, 4.0], 1, 1, 2);
R = reshape([1.0, 2.0], 1, 1, 2);
S = reshape([0.0, 2.0], 1, 1, 2);
nativeHandle = radia.internal.callMex( ...
    "simulink.state_space.create", grid, period, A, B, C, D, ...
    Q, R, S, 2.0);
cleanupHandle = onCleanup(@() destroyNativeStateSpace(nativeHandle));
first = radia.internal.callMex( ...
    "simulink.state_space.output", nativeHandle, pi/2, 3.0);
radia.internal.callMex( ...
    "simulink.state_space.update", nativeHandle, pi/2, 3.0);
second = radia.internal.callMex( ...
    "simulink.state_space.output", nativeHandle, pi/2, 3.0);
snapshot = radia.internal.callMex( ...
    "simulink.state_space.snapshot", nativeHandle);
if norm(first - [4.0; 19.5], inf) > 1e-12 || ...
        norm(second - [15.0; 122.625], inf) > 1e-12 || ...
        snapshot.step_count ~= 1
    error("radia:simulink:ReleaseMotorNumerics", ...
        "The extracted native motor lifecycle smoke failed.");
end
clear cleanupHandle

maglevModelPath = fullfile(matlabRoot, "radia_maglev.slx");
load_system(maglevModelPath);
cleanupMagLev = onCleanup(@() closeIfLoaded("radia_maglev"));
set_param("radia_maglev", "SimulationCommand", "update");
maglevOutput = sim("radia_maglev", "StopTime", "0.001", ...
    "ReturnWorkspaceOutputs", "on");
maglevDataset = maglevOutput.get("yout");
maglevForce = maglevDataset.getElement(2).Values.Data;
if size(maglevForce, 2) ~= 3 || any(~isfinite(maglevForce), "all") || ...
        max(abs(maglevForce(:,3))) <= 0
    error("radia:simulink:ReleaseMagLevNumerics", ...
        "The standalone MagLev force smoke failed.");
end
clear cleanupMagLev

electromagnetModelPath = fullfile(matlabRoot,"radia_electromagnet.slx");
load_system(electromagnetModelPath);
cleanupElectromagnet = onCleanup(@() closeIfLoaded("radia_electromagnet"));
set_param("radia_electromagnet","SimulationCommand","update");
electromagnetOutput = sim("radia_electromagnet", ...
    "ReturnWorkspaceOutputs","on");
electromagnetDataset = electromagnetOutput.get("yout");
electromagnetObjective = ...
    electromagnetDataset.getElement(4).Values.Data;
electromagnetStatus = electromagnetDataset.getElement(5).Values.Data;
electromagnetDensity = electromagnetDataset.getElement(7).Values.Data;
electromagnetVolumeFraction = ...
    electromagnetDataset.getElement(8).Values.Data;
if electromagnetStatus(end) ~= 2 || ...
        ~isfinite(electromagnetObjective(end)) || ...
        size(electromagnetDensity,2) ~= 4 || ...
        any(~isfinite(electromagnetDensity),"all") || ...
        electromagnetVolumeFraction(end) > 0.5 + 1e-7
    error("radia:simulink:ReleaseElectromagnetTopologyNumerics", ...
        "The standalone electromagnet topology smoke failed.");
end
clear cleanupElectromagnet

ih = verify_radia_ih_release();
report = struct( ...
    "passed", true, ...
    "matlab_release", string(version("-release")), ...
    "mex_api_version", api.api_version, ...
    "library", "radia_simulink_library", ...
    "motor_backend", string(motorContract.backend), ...
    "motor_first_output", first, ...
    "motor_second_output", second, ...
    "maglev_backend", string(maglevContract.backend), ...
    "maglev_max_vertical_force_N", max(abs(maglevForce(:,3))), ...
    "electromagnet_topology_backend", ...
        string(electromagnetContract.adjoint_backend), ...
    "electromagnet_topology_objective",electromagnetObjective(end), ...
    "electromagnet_topology_volume_fraction", ...
        electromagnetVolumeFraction(end), ...
    "ih_backend", string(ih.backend), ...
    "python_per_step", false);
fprintf("RADIA_SIMULINK_RELEASE_OK matlab=%s motor=%s maglev=%s em_topology=%s ih=%s\n", ...
    report.matlab_release, report.motor_backend, ...
    report.maglev_backend,report.electromagnet_topology_backend, ...
    report.ih_backend);
clear cleanupLibrary cleanupPath
end

function destroyNativeStateSpace(handle)
try
    radia.internal.callMex("simulink.state_space.destroy", handle);
catch
end
end

function closeIfLoaded(name)
if bdIsLoaded(name)
    close_system(name, 0);
end
end

function present = isPathEntry(folder)
present = any(strcmpi(split(string(path), pathsep), string(folder)));
end

function removePathIfAdded(folder, pathWasPresent)
if ~pathWasPresent && isPathEntry(folder)
    rmpath(folder);
end
end
