function report = verify_radia_simulink_release()
%VERIFY_RADIA_SIMULINK_RELEASE Verify an extracted full Radia library package.
matlabRoot = fileparts(mfilename("fullpath"));
pathWasPresent = isPathEntry(matlabRoot);
if ~pathWasPresent
    addpath(matlabRoot, "-begin");
end
cleanupPath = onCleanup(@() removePathIfAdded(matlabRoot, pathWasPresent));

required = ["radia_simulink_library.slx", "radia_ih.slx", ...
    "radia_electromagnet.slx", "radia_maglev.slx", ...
    "radia_nonlinear_reactor.slx", ...
    "radia_streamfunction_optimization.slx", "install_radia_simulink.m", ...
    "radia_mex." + mexext, "optuna_mex." + mexext, ...
    "radia_ih_eddy_sfun.m", ...
    "radia_ih_thermal_sfun.m", "radia_nonlinear_reactor_sfun.m"];
required(end+1) = "radia_streamfunction_optuna_sfun.m";
missing = required(~isfile(fullfile(matlabRoot, required)));
if ~isempty(missing)
    error("radia:simulink:ReleaseMissing", ...
        "Radia Simulink release is missing: %s", strjoin(missing, ", "));
end

setupInfo = radia.setup(RequireMex=true,Force=true);
if ~setupInfo.mex_available
    error("radia:simulink:ReleaseMex", ...
        "The full library package did not load radia_mex.");
end
api = radia.apiInfo();
optunaInfo = radia.optuna.internal.NativeKernels.call("api.info");
optunaCommands = string(radia.optuna.internal.NativeKernels.call( ...
    "api.commands"));
if string(optunaInfo.backend) ~= "optuna_mex" || ...
        optunaInfo.command_count ~= numel(optunaCommands)
    error("radia:simulink:ReleaseOptunaMex", ...
        "The full library package did not load a self-consistent optuna_mex.");
end

libraryPath = fullfile(matlabRoot, "radia_simulink_library.slx");
load_system(libraryPath);
cleanupLibrary = onCleanup(@() closeIfLoaded("radia_simulink_library"));
if string(get_param("radia_simulink_library", "BlockDiagramType")) ~= "library"
    error("radia:simulink:ReleaseLibrary", ...
        "radia_simulink_library.slx is not a Simulink library.");
end
motorPath = ...
    "radia_simulink_library/Reduced Models/Motor Angle Family";
if getSimulinkBlockHandle(motorPath) <= 0 || ...
        string(get_param(motorPath, "FunctionName")) ~= ...
        "radia_motor_angle_family_mex_sfunction"
    error("radia:simulink:ReleaseMotorBlock", ...
        "The native Motor Angle Family block is absent or miswired.");
end
motorContract = get_param(motorPath, "UserData");
if string(motorContract.backend) ~= ...
        "native-mex-periodic-interpolation" || motorContract.python_per_step
    error("radia:simulink:ReleaseMotorBackend", ...
        "The Motor Angle Family block backend contract is invalid.");
end

reactorBlockPath = ...
    "radia_simulink_library/Reduced Models/Nonlinear HDiv-MMM Reactor";
if getSimulinkBlockHandle(reactorBlockPath) <= 0 || ...
        string(get_param(reactorBlockPath,"FunctionName")) ~= ...
        "radia_nonlinear_reactor_sfun"
    error("radia:simulink:ReleaseReactorBlock", ...
        "The nonlinear HDiv-MMM reactor block is absent or miswired.");
end
reactorContract = get_param(reactorBlockPath,"UserData");
if string(reactorContract.backend) ~= ...
        "matlab-level2+radia-mex-handle" || ...
        reactorContract.python_per_step || reactorContract.surrogate
    error("radia:simulink:ReleaseReactorBackend", ...
        "The nonlinear reactor backend contract is invalid.");
end

maglevBlockPath = ...
    "radia_simulink_library/Applications/Magnetic Levitation";
if getSimulinkBlockHandle(maglevBlockPath) <= 0 || ...
        string(get_param(maglevBlockPath, "BlockType")) ~= "SubSystem" || ...
        string(get_param(maglevBlockPath + "/Moving HCurl CLN", ...
        "FunctionName")) ~= "radia_hcurl_eddy_cln_family_sfunction"
    error("radia:simulink:ReleaseMagLevBlock", ...
        "The common-basis MagLev block is absent or miswired.");
end
maglevContract = get_param(maglevBlockPath, "UserData");
if string(maglevContract.backend) ~= ...
        "matlab-level2-common-basis-cln" || ...
        maglevContract.python_per_step || maglevContract.surrogate
    error("radia:simulink:ReleaseMagLevBackend", ...
        "The MagLev block backend contract is invalid.");
end

electromagnetBlockPath = ...
    "radia_simulink_library/Applications/Electromagnet Topology Optimization";
if getSimulinkBlockHandle(electromagnetBlockPath) <= 0 || ...
        string(get_param(electromagnetBlockPath,"BlockType")) ~= ...
        "SubSystem" || string(get_param(electromagnetBlockPath + ...
        "/Density Topology Optimization","FunctionName")) ~= ...
        "radia_electromagnet_topology_sfun"
    error("radia:simulink:ReleaseElectromagnetTopologyBlock", ...
        "The electromagnet topology block is absent or miswired.");
end
electromagnetContract = get_param(electromagnetBlockPath,"UserData");
if string(electromagnetContract.adjoint_backend) ~= ...
        "matlab-native-vim-density-adjoint" || ...
        electromagnetContract.state_solves_per_gradient ~= 1 || ...
        electromagnetContract.adjoint_solves_per_gradient ~= 1 || ...
        electromagnetContract.finite_difference_fallback || ...
        electromagnetContract.python_per_optimization_step
    error("radia:simulink:ReleaseElectromagnetTopologyBackend", ...
        "The electromagnet topology backend contract is invalid.");
end

streamOptunaPath = ...
    "radia_simulink_library/Applications/Stream Function Optuna";
if getSimulinkBlockHandle(streamOptunaPath) <= 0 || ...
        string(get_param(streamOptunaPath,"FunctionName")) ~= ...
        "radia_streamfunction_optuna_sfun"
    error("radia:simulink:ReleaseStreamFunctionOptunaBlock", ...
        "The Stream Function Optuna block is absent or miswired.");
end
streamOptunaContract = get_param(streamOptunaPath,"UserData");
if string(streamOptunaContract.optimizer_backend) ~= ...
        "matlab-native-optuna" || ...
        string(streamOptunaContract.inner_factorization) ~= ...
        "aca_plus_qr_tsvd" || streamOptunaContract.python_per_step
    error("radia:simulink:ReleaseStreamFunctionOptunaBackend", ...
        "The Stream Function Optuna backend contract is invalid.");
end

grid = [0; pi];
period = 2*pi;
A = reshape([1.0, 0.5], 1, 1, 2);
B = reshape([1.0, 3.0], 1, 1, 2);
C = reshape([1.0, 3.0], 1, 1, 2);
D = zeros(1, 1, 2);
Q = reshape([2.0, 4.0], 1, 1, 2);
R = reshape([1.0, 2.0], 1, 1, 2);
S = reshape([0.0, 2.0], 1, 1, 2);
nativeHandle = radia.internal.callMex( ...
    "simulink.state_space.create", grid, period, A, B, C, D, ...
    Q, R, S, 2.0);
cleanupHandle = onCleanup(@() destroyNativeStateSpace(nativeHandle));
first = radia.internal.callMex( ...
    "simulink.state_space.output", nativeHandle, pi/2, 3.0);
radia.internal.callMex( ...
    "simulink.state_space.update", nativeHandle, pi/2, 3.0);
second = radia.internal.callMex( ...
    "simulink.state_space.output", nativeHandle, pi/2, 3.0);
snapshot = radia.internal.callMex( ...
    "simulink.state_space.snapshot", nativeHandle);
if norm(first - [4.0; 19.5], inf) > 1e-12 || ...
        norm(second - [15.0; 122.625], inf) > 1e-12 || ...
        snapshot.step_count ~= 1
    error("radia:simulink:ReleaseMotorNumerics", ...
        "The extracted native motor lifecycle smoke failed.");
end
clear cleanupHandle

reactorConfig = radia.simulink.makeNonlinearReactorDemoConfig();
reactorHandle = radia.internal.callMex("reactor.create",reactorConfig);
cleanupReactorHandle = onCleanup( ...
    @() destroyNonlinearReactor(reactorHandle));
reactorZero = radia.internal.callMex("reactor.output",reactorHandle,0.0);
reactorSaturated = radia.internal.callMex( ...
    "reactor.output",reactorHandle,20.0);
reactorBefore = radia.internal.callMex("reactor.snapshot",reactorHandle);
radia.internal.callMex("reactor.update",reactorHandle,20.0);
reactorAfter = radia.internal.callMex("reactor.snapshot",reactorHandle);
if reactorZero.peak_flux_density_T ~= 0 || ...
        reactorSaturated.peak_flux_density_T <= 2 || ...
        reactorSaturated.differential_inductance_H >= 1e-4 || ...
        reactorSaturated.residual_relative_norm >= 1e-10 || ...
        reactorAfter.accepted_steps ~= reactorBefore.accepted_steps+1
    error("radia:simulink:ReleaseReactorNumerics", ...
        "The nonlinear HDiv-MMM reactor MEX smoke failed.");
end
clear cleanupReactorHandle

maglevModelPath = fullfile(matlabRoot, "radia_maglev.slx");
load_system(maglevModelPath);
cleanupMagLev = onCleanup(@() closeIfLoaded("radia_maglev"));
set_param("radia_maglev", "SimulationCommand", "update");
maglevOutput = sim("radia_maglev", "StopTime", "0.001", ...
    "ReturnWorkspaceOutputs", "on");
maglevDataset = maglevOutput.get("yout");
maglevForce = maglevDataset.getElement(2).Values.Data;
if size(maglevForce, 2) ~= 3 || any(~isfinite(maglevForce), "all") || ...
        max(abs(maglevForce(:,3,:)), [], "all") <= 0
    error("radia:simulink:ReleaseMagLevNumerics", ...
        "The standalone MagLev force smoke failed.");
end
clear cleanupMagLev

reactorModelPath = fullfile(matlabRoot,"radia_nonlinear_reactor.slx");
load_system(reactorModelPath);
cleanupReactor = onCleanup(@() closeIfLoaded("radia_nonlinear_reactor"));
reactorInput = Simulink.SimulationInput("radia_nonlinear_reactor");
reactorInput = reactorInput.setModelParameter( ...
    "StopTime","0.02","SimulationMode","normal");
reactorOutput = sim(reactorInput);
reactorBpeak = reactorOutput.logsout.get("Bpeak_T").Values;
reactorLdiff = reactorOutput.logsout.get("Ldiff_H").Values;
reactorResidual = reactorOutput.logsout.get("residual").Values;
if max(reactorBpeak.Data) <= 2 || min(reactorLdiff.Data) >= 1e-4 || ...
        max(reactorResidual.Data) >= 1e-10
    error("radia:simulink:ReleaseReactorModel", ...
        "The standalone nonlinear reactor simulation failed.");
end
clear cleanupReactor

electromagnetModelPath = fullfile(matlabRoot,"radia_electromagnet.slx");
load_system(electromagnetModelPath);
cleanupElectromagnet = onCleanup(@() closeIfLoaded("radia_electromagnet"));
set_param("radia_electromagnet","SimulationCommand","update");
electromagnetOutput = sim("radia_electromagnet", ...
    "ReturnWorkspaceOutputs","on");
electromagnetDataset = electromagnetOutput.get("yout");
electromagnetObjective = ...
    electromagnetDataset.getElement(4).Values.Data;
electromagnetStatus = electromagnetDataset.getElement(5).Values.Data;
electromagnetDensity = electromagnetDataset.getElement(7).Values.Data;
electromagnetVolumeFraction = ...
    electromagnetDataset.getElement(8).Values.Data;
electromagnetTopologyExecuted = hasOptimizationToolbox();
if electromagnetTopologyExecuted
    if electromagnetStatus(end) ~= 2 || ...
            ~isfinite(electromagnetObjective(end)) || ...
            size(electromagnetDensity,2) ~= 4 || ...
            any(~isfinite(electromagnetDensity),"all") || ...
            electromagnetVolumeFraction(end) > 0.5 + 1e-7
        error("radia:simulink:ReleaseElectromagnetTopologyNumerics", ...
            "The standalone electromagnet topology smoke failed.");
    end
elseif electromagnetStatus(end) ~= -1 || ...
        size(electromagnetDensity,2) ~= 4 || ...
        any(~isfinite(electromagnetDensity),"all") || ...
        abs(electromagnetVolumeFraction(end)-0.5) > 1e-12
    error("radia:simulink:ReleaseElectromagnetTopologyDependency", ...
        "The electromagnet block did not fail loudly without Optimization Toolbox.");
end
clear cleanupElectromagnet

ih = verify_radia_ih_release();
report = struct( ...
    "passed", true, ...
    "matlab_release", string(version("-release")), ...
    "mex_api_version", api.api_version, ...
    "optuna_mex_backend", string(optunaInfo.backend), ...
    "optuna_mex_command_count", optunaInfo.command_count, ...
    "library", "radia_simulink_library", ...
    "motor_backend", string(motorContract.backend), ...
    "motor_first_output", first, ...
    "motor_second_output", second, ...
    "reactor_backend", string(reactorContract.backend), ...
    "reactor_peak_flux_density_T",max(reactorBpeak.Data), ...
    "reactor_min_differential_inductance_H",min(reactorLdiff.Data), ...
    "maglev_backend", string(maglevContract.backend), ...
    "maglev_max_vertical_force_N", ...
        max(abs(maglevForce(:,3,:)), [], "all"), ...
    "electromagnet_topology_backend", ...
        string(electromagnetContract.adjoint_backend), ...
    "electromagnet_topology_executed",electromagnetTopologyExecuted, ...
    "electromagnet_topology_dependency","Optimization Toolbox", ...
    "electromagnet_topology_objective",electromagnetObjective(end), ...
    "electromagnet_topology_volume_fraction", ...
        electromagnetVolumeFraction(end), ...
    "streamfunction_optuna_backend", ...
        string(streamOptunaContract.optimizer_backend), ...
    "streamfunction_optuna_inner", ...
        string(streamOptunaContract.inner_factorization), ...
    "ih_backend", string(ih.backend), ...
    "python_per_step", false);
electromagnetCheck = "dependency-gated";
if electromagnetTopologyExecuted
    electromagnetCheck = "executed";
end
fprintf("RADIA_SIMULINK_RELEASE_OK matlab=%s motor=%s reactor=%s maglev=%s em_topology=%s em_check=%s sf_optuna=%s sf_inner=%s ih=%s\n", ...
    report.matlab_release, report.motor_backend, ...
    report.reactor_backend,report.maglev_backend, ...
    report.electromagnet_topology_backend, ...
    electromagnetCheck,report.streamfunction_optuna_backend, ...
    report.streamfunction_optuna_inner,report.ih_backend);
clear cleanupLibrary cleanupPath
end

function destroyNativeStateSpace(handle)
try
    radia.internal.callMex("simulink.state_space.destroy", handle);
catch
end
end

function destroyNonlinearReactor(handle)
try
    radia.internal.callMex("reactor.destroy",handle);
catch
end
end

function closeIfLoaded(name)
if bdIsLoaded(name)
    close_system(name, 0);
end
end

function present = isPathEntry(folder)
present = any(strcmpi(split(string(path), pathsep), string(folder)));
end

function removePathIfAdded(folder, pathWasPresent)
if ~pathWasPresent && isPathEntry(folder)
    rmpath(folder);
end
end

function available = hasOptimizationToolbox()
available = ~isempty(ver("optim")) && ...
    license("test","Optimization_Toolbox") && ...
    exist("fmincon","file") == 2;
end
