function report = verify_radia_ih_release()
%VERIFY_RADIA_IH_RELEASE Verify an extracted native IH preview package.
matlabRoot = fileparts(mfilename("fullpath"));
addpath(matlabRoot, "-begin");
cleanupPath = onCleanup(@() rmpath(matlabRoot));

required = ["radia_ih.slx","IH_VERSION","install_radia_ih.m", ...
    "radia_ih_eddy_sfun." + mexext, ...
    "radia_ih_thermal_sfun." + mexext];
missing = required(~isfile(fullfile(matlabRoot, required)));
if ~isempty(missing)
    error("radia:simulink:IHReleaseMissing", ...
        "IH release is missing: %s", strjoin(missing, ", "));
end
radia.simulink.requireIHNativeRuntime();

modelPath = fullfile(matlabRoot, "radia_ih.slx");
load_system(modelPath);
cleanupModel = onCleanup(@() closeIfLoaded("radia_ih"));
if string(get_param("radia_ih/Eddy", "FunctionName")) ~= ...
        "radia_ih_eddy_sfun" || ...
        string(get_param("radia_ih/Thermal", "FunctionName")) ~= ...
        "radia_ih_thermal_sfun"
    error("radia:simulink:IHReleaseBackend", ...
        "radia_ih.slx is not wired to both native MEX S-Functions.");
end

workspace = get_param("radia_ih", "ModelWorkspace");
config = workspace.getVariable("radia_ih_config");
if ~isfield(config, "diagnostic_only") || ~config.diagnostic_only || ...
        string(config.backend) ~= "native-mex-sfunction"
    error("radia:simulink:IHReleaseConfig", ...
        "The tracked model must contain the native diagnostic configuration.");
end
set_param("radia_ih", "SimulationCommand", "update");
simulation = sim("radia_ih", "StopTime", ...
    compose("%.17g", 2 * config.sample_time_s), ...
    "ReturnWorkspaceOutputs", "on");
output = simulation.get("yout");
if ~isa(output,"Simulink.SimulationData.Dataset") || ...
        output.numElements ~= 2
    error("radia:simulink:IHReleaseOutput", ...
        "The native IH smoke simulation produced an invalid output contract.");
end
heat = output{1}.Values.Data;
temperature = output{2}.Values.Data;
if any(~isfinite(heat),"all") || any(~isfinite(temperature),"all") || ...
        ~(heat(end) > 0) || ...
        ~(temperature(end) > temperature(1))
    error("radia:simulink:IHReleaseNumerics", ...
        "The native IH smoke outputs are non-finite or physically inactive.");
end

report = struct( ...
    "passed", true, ...
    "ih_version", strtrim(string(fileread(fullfile(matlabRoot,"IH_VERSION")))), ...
    "matlab_release", string(version("-release")), ...
    "backend", "native-mex-sfunction", ...
    "python_fallback", false, ...
    "sample_time_s", config.sample_time_s, ...
    "final_heat_density_W_per_m3", heat(end), ...
    "initial_temperature_K", temperature(1), ...
    "final_temperature_K", temperature(end), ...
    "dt_order", string(config.dt_order));
fprintf("RADIA_IH_RELEASE_OK version=%s matlab=%s backend=%s\n", ...
    report.ih_version, report.matlab_release, report.backend);
end

function closeIfLoaded(name)
if bdIsLoaded(name)
    close_system(name, 0);
end
end
