"""Bibliography INDEX for radia_mcp.pinn.

Auto-generated catalog of 52 PDF references from the Sugahara
Lab literature library.  Catalog paths are relative to the
corpus root (configure the root via RADIA_LIT_ROOT).

Generated by tools/catalog_to_knowledge.py from catalog.json
(pdf_batch_indexer output).  Re-run when new PDFs are added.

Use:
    from radia_mcp.pinn.bibliography_index_knowledge import get_bibliography_index
    print(get_bibliography_index("kelvin"))    # filter
    print(get_bibliography_index(""))          # full
    print(get_bibliography_index("__scanned__"))  # scanned PDFs only
"""

from __future__ import annotations
import json as _json

_CATALOG_JSON = r"""
[
 {
  "filename": "04_MRI_Pole plate effected gradient coils design in permanent magnet MRI system.pdf",
  "title": "Received: 17 April2UlG",
  "authors": "Rewised: lU Urtnler 2ざI",
  "abstract_excerpt": "Rewised: lU Urtnler 2ざI\nAccepted: 1g Octnber 20I6\nARTIじL『\nVILEY\nPole plate effected gradient coiks designin pernanentm\nMIRI system\nYajie Xul,z\nHector Sanchez Lopezl\n1\nQiaoyan Chenl,2Xiaodong\n1\nIDepartnnent of NIedical Inaging Suzhou\nIngtitute of Bianledica] Engineering and\nAbgtract\nTechnlngy, Chineze Acadeny pfSciences Pole platein pernnanentinagnet MIRI systen leads to serioug impa\nSuzhau,Jianggu China\nlinearity,and inductance of gradient coils due to theinduced cu\nこUniversity ofChinese Acadeny afSciences\nChina\nnaterial.In this article,a nodified mirror current(MIC)modelotplate basedon\n7 gradient coil i8 established; aining at inproving gradient coil per\n1.\nDeparunent ofIledical\nLevenberg‑Mlarquardt (LM) algorithm ig\nfor the gradient coil optiniz\nSuzhau Ingtituie nt Binnedical Engineerin",
  "page_count": 9,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\アプリケーション\\04_MRI_Pole plate effected gradient coils design in permanent magnet MRI system.pdf"
 },
 {
  "filename": "3-3_chapter3.pdf",
  "title": "本章では電気機器の新しい最適設計法とそれらを用いた",
  "authors": "",
  "abstract_excerpt": "最適化結果について報告する。近年，穴の生成・消滅を含め\nた自由変形により最適な機器構造を探索するトポロジー最\n適化が注目されている。3.2 節はトポロジー最適化に関する\n最新の研究成果についてまとめている。本節ではまず目的\n関数の勾配(微分)を基にトポロジー最適化を行う密度法お\nよびレベルセット法を議論する。つぎに設計領域を多数の\n小領域(有限要素)に分割し，それぞれの小領域の材料を決定\nするON/OFF 法を取り上げる。まず空間的な高周波数成分\nを消去して，滑らかな境界を持つ物体形状を得るために，ガ\nウスフィルターをトポロジー最適化に適用する方法につい\nて述べる。つぎに3 つ以上の材料種について最適分布を求\nめる多材料トポロジー最適化，トポロジー最適化の非接触\n給電最適設計への応用について報告する。ON/OFF 法のため\nに従来，遺伝的アルゴリズム(GA: Genetic Algorithm)が用い\nられてきたが， CMA-ES により，少ない個体数で高い探索\n性能を実現できることが近年注目されている。本節の最後\nで，CMA-ES とGA の比較結果について報告する。 \n3.3 節では人工知能(AI: Artificial Intelligence)技術の最適設\n計への応用について述べる。まず深層ニューラルネットワ\nーク(NN: Neural Network)を有限要素法の代替モデルとし\nて，トポロジー最適化を高速化する方法について述べる。こ\nの中では，追学習，Grad-CAM を用いた深層学習結果の可視\n化，磁束密度を深層NN に入力する方法，深層NN による電\n流依存のトルク特性の推定と磁気回路の特徴抽出および教\n師なし学習による最適設計について議論する。つぎに，木構\n造を用いた自動設計・総合設計について述べる。本手法で\nは，設計手順を木構造で表し，モータの体格や極",
  "page_count": 32,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\00_技術報告\\2023_05_電気学会報告書\\3-3_chapter3.pdf"
 },
 {
  "filename": "3D and multiple load case bi-directional evolutionary optimization.pdf",
  "title": "Structural Optimization 18,183‑192 Springer‑'",
  "authors": "V. Young O.M.Querin, G:P・ Steven",
  "abstract_excerpt": "1999\n3D andnultiple load case bi‑directionalevolutionary structural\noptinization (BZSo)\nV. Young O.M.Querin, G:P・ Steven\nDepartnent of Aeronautical Engineering, BuildingJ07,University ofSydney NSV 2006,Australia\nY.II Xie\nDepartnent of CivilandBuilding Engineering, VUT; Box 14428,MMC, VIC 3000,Australia\nAbstract\nEvolutionary Structural\nOptimnization (ESO)isture Although theanalyticalnnethods provide exact optina\nnurnerical\nmethod of structural optimization that is integrated\nare not realistic solutions and are linnited to\nmore sim‑\nwith finite elenent analysis (FEA) Bi‑directional ESO (BESO)is ple problerns\nIn contrast, the nurerical rethods\ncan\nPro‑\nan extension to this nethod and can begin with minimal amount\nduce nnorerealistic optinalstructures andmorerecently have\nof material (only th",
  "page_count": 10,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\トポロジー最適化\\3D and multiple load case bi-directional evolutionary optimization.pdf"
 },
 {
  "filename": "83[1].pdf",
  "title": "IEEE TRANSACTIONS",
  "authors": "ON MAGNETICS,",
  "abstract_excerpt": "ON MAGNETICS,\nVOL\n31\nNO̲ 4,JULY\n1995\nThin Fim Transforner and ItS Analysis by Integr\nEquationMlethod\nL. Marinova, Y. Midorikawa, S. Hayano, and Y.\nSaito\nAbstract‑Recently\nwe proposed a new high frequency trang\nbased\non the skin\neffect sinilar to that of our coreless\nformer that could alloy the manufacture Of smah poyer sup‑\ntransforner [5]. This fact was confirnned by comparing\nplies  In this paper we propogea thinfilmtransformer for Small\nelectronic devices; and apply the integral equation method to\ntheirfrequency characteristicsTo designandimpr\nanalyzethis transformer。 Both the primary and secondary coils\nfiln transforner characteristics, it is essential to analy\nofthefilmtransformer arearranged coaxially on onelayer and\nits electronagnetic phenomena and paraneters\nBoth the\nmultiply lam",
  "page_count": 6,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\90_各大学の研究内容\\斎藤研究室\\高周波トランス\\83[1].pdf"
 },
 {
  "filename": "A hybrid twin based on machine learning enhanced reduced order model for real-time simulation of magnetic bearings.pdf",
  "title": "Ghnatios et al. Advanced Modeling and Simulation",
  "authors": "Advanced Modeling and Simulation",
  "abstract_excerpt": "The simulation of magnetic bearings involves highly non-linear physics, with high",
  "page_count": 15,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\MOR_モデル縮約\\A hybrid twin based on machine learning enhanced reduced order model for real-time simulation of magnetic bearings.pdf"
 },
 {
  "filename": "A novel graph convolutional neural network for predicting interaction sites on protein kinase inhibitorsin phosphorylation.pdf",
  "title": "Vol.:(0123456789)",
  "authors": "Scientific Reports |          (2022) 12:229",
  "abstract_excerpt": "Scientific Reports |          (2022) 12:229  \n| https://doi.org/10.1038/s41598-021-04230-7\nwww.nature.com/scientificreports\nA novel graph convolutional neural \nnetwork for predicting interaction \nsites on protein kinase inhibitors \nin phosphorylation\nFeiqi Wang1*, Yun‑Ti Chen2, Jinn‑Moon Yang3 & Tatsuya Akutsu4\nProtein kinase-inhibitor interactions are key to the phosphorylation of proteins involved in cell \nproliferation, differentiation, and apoptosis, which shows the importance of binding mechanism \nresearch and kinase inhibitor design. In this study, a novel machine learning module (i.e., the WL \nBox) was designed and assembled to the Prediction of Interaction Sites of Protein Kinase Inhibitors \n(PISPKI) model, which is a graph convolutional neural network (GCN) to predict the interac",
  "page_count": 11,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Graph_Neural_Network\\A novel graph convolutional neural network for predicting interaction sites on protein kinase inhibitorsin phosphorylation.pdf"
 },
 {
  "filename": "A target field approach to optimal coil design.pdf",
  "title": "JPhysD:AppL",
  "authors": "LETTERTOTHE EDITOR",
  "abstract_excerpt": "19(1986)L147‑L151.Printedin GreatBritain\nLETTERTOTHE EDITOR\ntargetfeldapproach to optimalcoil design\nRTurner\nDepartmentofPhysics,Nottingham University,Nottingham NG7ZRD,UK\nReceived2\n1986\nAbsiract. Usinga Fourier‑Bessel expansion Of the magnetic feld generated by curren\nfowingonacylindertherelationshipbeteencurrentandfeldmaybeinvertedHencet\ncurrent densityrequiredtogenerateaspecifedrargetfeldBonthesurfaceofacylinder\nsmallerradius may beevaluated Gradient solenoidaland shim coil designs basedon this\napproach provide exceptionally large usable volumes while remaining compa\nnecessary,oflowinductance,\nFormanyapplicationsinphysicsandengineering,particularlyin NMRsp\nimagingitis necessary tO employ magnetic felds ofspecifedspatial variation\ntheseare generated by coils wound on cylindricalfornners",
  "page_count": 5,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\コイル最適化\\流れ関数法\\ターゲットフィールド法\\A target field approach to optimal coil design.pdf"
 },
 {
  "filename": "ARD カーネルによる非線形地震応答解析のガウス過程回帰代替モデル構築-LAPTOP-T2OH2TJ4.pdf",
  "title": "ARD カーネルによる非線形地震応答解析の",
  "authors": "E-mail: saida.taisei.tj@alumni.tsukuba.ac.jp",
  "abstract_excerpt": "ガウス過程回帰代替モデル構築 \n \n \n \n才田 大聖1・西尾 真由子2 \n \n1 学生会員 筑波大学大学院 構造エネルギー工学学位プログラム 博士前期課程（〒305-8573 茨城県つくば\n市天王台1-1-1） \nE-mail: saida.taisei.tj@alumni.tsukuba.ac.jp \n2 正会員 筑波大学 システム情報系 准教授（〒305-8573 茨城県つくば市天王台1-1-1） \nE-mail: nishio@kz.tsukuba.ac.jp (Corresponding Author) \n \n不確定性を考慮する構造物の地震リスク解析ではモンテカルロ計算を行うが，地震動を入力とする非線\n形時刻歴応答解析で不確定パラメータが高次元となると計算負荷が増加する．そこで本研究では，計算負\n荷軽減のため，免震RC 橋脚の地震応答解析を対象に，その入出力関係に対する関連度自動決定（ARD）\nカーネルを用いたガウス過程回帰での代替モデル構築を行った．地震動特性に依存する橋脚と免震支承で\nの非線形挙動発現に対してガウス過程回帰で適切な代替モデルが構築できることを検証した結果，非線形\n挙動の有無に関わらず200 程度の訓練データで，最大応答分布を適切に導出する代替モデルを構築できた．\nその上で，ARDによって最大変位応答に対する不確定パラメータの寄与度を，異なる非線形性の発現度に\n対して適切に自動抽出できることを確かめた． \n \n     Key Words: surrogate model,  gaussian process regression,  automated relative determination,   \nnonlinear time-history analysis, seismic islated bridge pier \n \n \n1．",
  "page_count": 12,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\ARD カーネルによる非線形地震応答解析のガウス過程回帰代替モデル構築-LAPTOP-T2OH2TJ4.pdf"
 },
 {
  "filename": "ARD カーネルによる非線形地震応答解析のガウス過程回帰代替モデル構築.pdf",
  "title": "ARD カーネルによる非線形地震応答解析の",
  "authors": "E-mail: saida.taisei.tj@alumni.tsukuba.ac.jp",
  "abstract_excerpt": "ガウス過程回帰代替モデル構築 \n \n \n \n才田 大聖1・西尾 真由子2 \n \n1 学生会員 筑波大学大学院 構造エネルギー工学学位プログラム 博士前期課程（〒305-8573 茨城県つくば\n市天王台1-1-1） \nE-mail: saida.taisei.tj@alumni.tsukuba.ac.jp \n2 正会員 筑波大学 システム情報系 准教授（〒305-8573 茨城県つくば市天王台1-1-1） \nE-mail: nishio@kz.tsukuba.ac.jp (Corresponding Author) \n \n不確定性を考慮する構造物の地震リスク解析ではモンテカルロ計算を行うが，地震動を入力とする非線\n形時刻歴応答解析で不確定パラメータが高次元となると計算負荷が増加する．そこで本研究では，計算負\n荷軽減のため，免震RC 橋脚の地震応答解析を対象に，その入出力関係に対する関連度自動決定（ARD）\nカーネルを用いたガウス過程回帰での代替モデル構築を行った．地震動特性に依存する橋脚と免震支承で\nの非線形挙動発現に対してガウス過程回帰で適切な代替モデルが構築できることを検証した結果，非線形\n挙動の有無に関わらず200 程度の訓練データで，最大応答分布を適切に導出する代替モデルを構築できた．\nその上で，ARDによって最大変位応答に対する不確定パラメータの寄与度を，異なる非線形性の発現度に\n対して適切に自動抽出できることを確かめた． \n \n     Key Words: surrogate model,  gaussian process regression,  automated relative determination,   \nnonlinear time-history analysis, seismic islated bridge pier \n \n \n1．",
  "page_count": 12,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\ARD カーネルによる非線形地震応答解析のガウス過程回帰代替モデル構築.pdf"
 },
 {
  "filename": "Computer Techniques For Electromagnetics OCR.pdf",
  "title": "INTERNATIONAL SERIES OF MONOGRAPHS IN",
  "authors": "GENERAL EDITOR:DJ SILVERLEAF",
  "abstract_excerpt": "GENERAL EDITOR:DJ SILVERLEAF\nEXECUTIVE EDITOR: V.T,NORRIS\nVOLUME 7\nCOMPUTER TECHNIQUES\nFOR ELECTROMAGNETICS\n\n∼※\nVol\n1.\nBEAN & SmMONS一\n一Lighting Eittings: Peyfornnance and Design\nVol.2.\nVILsoN一Modern Practice in Servo Design\nVol.\n3, KNGHT一Power Systens Engineering and Mathenatics\nVol.4.\nJoNES一New Approaches to the Design and Economics 9fEHVTransn\nVol. 5.\nBoypLER一Measurenents in High‑Voltage Test Circuits\nVol. 6.\nMUR『HY一Thyristor ControlofA.C:Motors\n曇\n\nCOMPUTER TECHNIQUES\nFOR\nELECTROMAGNETICS\nEDITED BY\nR.MITTRA\nUnipevsity of IIlinois, Urbana, Illinois\nPERGAMONPRESS\nOXFORD\nNEV YORK\nTORONTO\nSYDNEY\nBRAUNSCHVEIG",
  "page_count": 410,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\01_教科書\\00_有限要素法・数値解析\\Computer Techniques For Electromagnetics OCR.pdf"
 },
 {
  "filename": "Computer Techniques For Electromagnetics.pdf",
  "title": "INTERNATIONAL SERIES OF MONOGRAPHS IN",
  "authors": "GENERAL EDITOR:DJ SILVERLEAF",
  "abstract_excerpt": "GENERAL EDITOR:DJ SILVERLEAF\nEXECUTIVE EDITOR: V.T,NORRIS\nVOLUME 7\nCOMPUTER TECHNIQUES\nFOR ELECTROMAGNETICS\n\n∼※\nVol\n1.\nBEAN & SmMONS一\n一Lighting Eittings: Peyfornnance and Design\nVol.2.\nVILsoN一Modern Practice in Servo Design\nVol.\n3, KNGHT一Power Systens Engineering and Mathenatics\nVol.4.\nJoNES一New Approaches to the Design and Economics 9fEHVTransn\nVol. 5.\nBoypLER一Measurenents in High‑Voltage Test Circuits\nVol. 6.\nMUR『HY一Thyristor ControlofA.C:Motors\n曇\n\nCOMPUTER TECHNIQUES\nFOR\nELECTROMAGNETICS\nEDITED BY\nR.MITTRA\nUnipevsity of IIlinois, Urbana, Illinois\nPERGAMONPRESS\nOXFORD\nNEV YORK\nTORONTO\nSYDNEY\nBRAUNSCHVEIG",
  "page_count": 410,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\01_教科書\\00_有限要素法・数値解析\\Computer Techniques For Electromagnetics.pdf"
 },
 {
  "filename": "Dipole Moments in Rayleigh Scattering.pdf",
  "title": "J,Inst Marhs Applics (1972} 9,14‑22",
  "authors": "Dipole IVomet辺 Rayleigh Scattering*",
  "abstract_excerpt": "Dipole IVomet辺 Rayleigh Scattering*\nDeparinert gf Vathemaatics Uniuersity Heights\nAND\nCourant Institute のj Nathennatical Sciences; New Zork UniDersily;\nNew Yari 10012\nR.E KLEn「MAN\nDepariment af Marhematics Unipersity of Delaware, Newarh; Delaware 1\nAND\nTBA.SeNIOR\nRadiation Laboratory, The Uniperyityof Michigan An Arbor; Nichiga\n[Received [6 March 1971 andin revised form 13 July 1971]\nThe Reld scattered Dy a Rnite ckosea, pcrfectly conducting bgdy irradiated by\n'frequency plane electromagnetic wave 1 expressed in ternns OF the polarization and\nvintugl ;a58tensors oTthe body: These tensors are 「unctions on]y of the geometry of\nthe body, aind expressions Eor their elernents aro derivea Fora body with a口 ax5s 0\nsyuumnetry,just three elemnents are̲independent,and these serve to specif\ninits en",
  "page_count": 9,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\モーメント法・境界要素法\\Dipole Moments in Rayleigh Scattering.pdf"
 },
 {
  "filename": "Evolution and Beyond A Systematic Literature Review and Bibliometric Analysis.pdf",
  "title": "Citation: Lawal, Z.K.; Yassin, H.; Lai,",
  "authors": "D.T.C.; Che Idris, A. Physics-Informed",
  "abstract_excerpt": ": This research aims to study and assess state-of-the-art physics-informed neural networks",
  "page_count": 23,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Physics-Informed Neural Network\\Evolution and Beyond A Systematic Literature Review and Bibliometric Analysis.pdf"
 },
 {
  "filename": "Exterior Calculs.pdf",
  "title": "Exterior Calculus:",
  "authors": "VNedge Products,",
  "abstract_excerpt": "VNedge Products,\nNanifoldsand\nDifferentialForms\nDavidJ.Cartano\n小\nRl)\nひ\nWx\n\nExTERIOR CALCULUS PRODUCTS,MANIFOLDS AND DIFFERENTIALFO\nByDavidJ.Cartano\nSeniorPartner\nBanton, Klugman & OettingLLP\nLos Angeles California\nCopyright 2023 by InternetPublications,Ltd\nNew York New York\nAll Rights Reserved\nISBN: 9798398260243\n\nISBN:9798398260243\nCopyright2023 by InternetPublications,Ltd\nNew York New York\nAll Rights Reserved\nNo clainis madeto original governnnent works; however Vithin this Productor\nPublication, thefollowingaresubjectto the copyrightofInternetPublicatio\nthe gathering connpilation and arrangennentofsuch governnnentnnaterials; \nmagnetic translationand digital conversion ofdata, ifapplicable (3)the hist\nstatutory and other notes andreferences; and (4)theconnentary and othermateria",
  "page_count": 474,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\01_教科書\\00_有限要素法・数値解析\\コホモロジー\\Exterior Calculs.pdf"
 },
 {
  "filename": "Generalized Perfectly Matched Layer for the Absorption of ]Propagating and Evanescent Waves in Lossless and Lossy Media.pdf",
  "title": "IEEE TRANSACTIONS ON MICROVAVE THEORY AND TECHNIQUES, VOL 44, NO",
  "authors": "Generalized Perfectly Matched Layer for t",
  "abstract_excerpt": "12,DECEMBER 1996\nGeneralized Perfectly Matched Layer for t\nAbsorption of Propagating and Evanescent\nVaves in Lossless and Lossy Media\nJiayuan Fang; Member; IEEE and Zhonghua\nStudent Mlenber; IEEE\nAbstact一The perfectly matched layer (PNIL〕 proposed by̲\nappear at the interface OfPMIL and an interiormedium̲\nBerenger; has Deen proved\nvery effective in absorbing prop‑\nTherefore; the original fornn ofthe PML is not\na\nchoice\nagating waves in lossless media: However; it has been found for applications involving modeling wave propagat\nthat the original construction of PMIL cannot effectively absorb\nevanescent wayeS: AISO;\nsignificantreHection can appear as PIIL\nmedia\nis applied 1o terninate Iossy一\nmedia。This paper describesa\nAmodification ofthe originalPML has been pioposedin [\ngeneralized perfect",
  "page_count": 7,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\非破壊検査\\Generalized Perfectly Matched Layer for the Absorption of ]Propagating and Evanescent Waves in Lossless and Lossy Media.pdf"
 },
 {
  "filename": "Henderson et al - 2023 - Covariance models and Gaussian process regression for the wave equation.pdf",
  "title": "arXiv:2311.05205v1  [math.AP]  9 Nov 2023",
  "authors": "Covariance models and Gaussian process regression for the",
  "abstract_excerpt": "In this article, we consider the general task of performing Gaussian process regres-",
  "page_count": 41,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\Physics_informed\\Henderson et al - 2023 - Covariance models and Gaussian process regression for the wave equation.pdf"
 },
 {
  "filename": "Hysteresis Modeling in Iron-Dominated Magnets Based on a Multi-Layered Narx Neural Network Approach.pdf",
  "title": "See discussions, stats, and author profiles for this publication at: https://www.researchgate.net/publication/353410770",
  "authors": "Hysteresis Modeling in Iron-Dominated Magnets Based on a Multi-Layered",
  "abstract_excerpt": "Hysteresis Modeling in Iron-Dominated Magnets Based on a Multi-Layered\nNARX Neural Network Approach\nArticle  in  International Journal of Neural Systems · July 2021\nDOI: 10.1142/S0129065721500337\nCITATIONS\n0\nREADS\n33\n5 authors, including:\nSome of the authors of this publication are also working on these related projects:\nCNAO Centro Nazionale di adroterapia oncologica View project\nCryogenics Monitoring View project\nMaria Amodeo\nUniversity of Naples Federico II\n6 PUBLICATIONS   6 CITATIONS   \nSEE PROFILE\nPasquale Arpaia\nUniversity of Naples Federico II\n338 PUBLICATIONS   2,241 CITATIONS   \nSEE PROFILE\nMarco Buzio\nCERN\n134 PUBLICATIONS   775 CITATIONS   \nSEE PROFILE\nVincenzo Di Capua\nUniversity of Naples Federico II\n3 PUBLICATIONS   2 CITATIONS   \nSEE PROFILE\nAll content following this page",
  "page_count": 19,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\磁気特性\\ヒステリシス\\CERN論文\\Hysteresis Modeling in Iron-Dominated Magnets Based on a Multi-Layered Narx Neural Network Approach.pdf"
 },
 {
  "filename": "Integral Equation Solutions of Three-dimensional Scattering Problems.pdf",
  "title": "IntegraL Equqtion Solutions",
  "authors": "A JPOGGIO",
  "abstract_excerpt": "of Thyee‑dinensional Scattering Problenns\nA JPOGGIO\nCovnell Aeronqutical Laboratory, Buffalo, New York\nAND\nEK.MIILLER\nLawyence Liternore Laboratory; Lipermore Calif\n4.1.IITRODひCTION\nThe general topic to be considered in this chapter is the solution of a bounda\nproblenina three‑dimensional domain The general procedure will be to reduce a three‑\ndimnensionalproblemn to tyo dimensions by castingthesolutioninterns ofunknownsu\nfunctions rather than unknown\nvolume functions Hence rather than solve the simple\nappcaring wave eguation with extremely\ncomplicated boundary conditions we choo\nformulate the solution in ternns ofunknown functions over two‑dinnensionalsurfaces: This\nofvieiv yillallow considerableincreases in generality over the direct solution of the\nwave eguation although this fornzulat",
  "page_count": 106,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\モーメント法・境界要素法\\高周波\\Integral Equation Solutions of Three-dimensional Scattering Problems.pdf"
 },
 {
  "filename": "LLM_day6_v2.pdf",
  "title": "第6回：RLHF(Advanced Topic for Tuning Pre-trained Models)",
  "authors": "Sony ML R&D intern",
  "abstract_excerpt": "2023/09/22\nサマースクール2023・⼤規模⾔語モデル\n1\n\n講師⾃⼰紹介\n2\n髙城頌太（東京⼤学⼤学院⼯学系研究科松尾研究室修⼠2年）\n•\n経歴\n•\n2019年3⽉\n奈良⼯業⾼等専⾨学校情報⼯学科修了\n•\n2022年3⽉\n⼤阪⼤学基礎⼯学部システム化学科修了\n•\n2022年4⽉〜東京⼤学⼯学系研究科技術経営戦略学専攻\n•\nインターン等\n•\nSony ML R&D intern\n•\nDeNA backend intern\n•\nRecruit Data Specialist Intern\n•\nSanSan Intern\n•\n専⾨分野︓\n•\n⼤規模⾔語モデル，強化学習，ロボティックス\n•\nその他の活動︓\n•\n「Deep Learning基礎講座」「深層強化学習スプリングセミナー」などのTA担当\n\narXiv interpreter\n3\n•\nSlack上で論文の要約，図表の切り出し，質問応答ができるBot\n•\n意見や改善案募集中です！(コミッターも募集)\n← 論文要約\n↓ 図表の切り出し",
  "page_count": 100,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Large Language Model\\LLM_day6_v2.pdf"
 },
 {
  "filename": "Large Language Models to Enhance Bayesian Optimization.pdf",
  "title": "Published as a conference paper at ICLR 2024",
  "authors": "LARGE LANGUAGE MODELS TO ENHANCE BAYESIAN",
  "abstract_excerpt": "Bayesian optimization (BO) is a powerful approach for optimizing complex and",
  "page_count": 33,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Large Language Model\\Large Language Models to Enhance Bayesian Optimization.pdf"
 },
 {
  "filename": "MATLABで始める機械学習／Deep Learning ア・ラ・カルト.pdf",
  "title": "機械学習/Deep Learning",
  "authors": "G-DEPソリューションパートナー  （株）システム計画研究所",
  "abstract_excerpt": "ア・ラ・カルト  \n \nG-DEPソリューションパートナー  （株）システム計画研究所 \n \n村瀬知彦・山本真司 \n２０１５／０６／０８ ＠計算工学講演会 \n  \n\n何ができる？ \nハンドサイン認識中 \n \n\n本日のお品書 \n• MATLABとは？ \n• 機械学習とは？ \n• ア・ラ・カルト（デモ） \n1. Hinton先生の再現 \n2. Neural Neｔwork Toolbox \n3. RCNNの再現 \n• 弊社について",
  "page_count": 36,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\00_教科書\\機械学習\\MATLABで始める機械学習／Deep Learning ア・ラ・カルト.pdf"
 },
 {
  "filename": "Mathematical Models of Hysteresis and Their Applications.pdf",
  "title": "ISAAK MAYERGOYz",
  "authors": "MATIIEMATICAL MODELS OR",
  "abstract_excerpt": "MATIIEMATICAL MODELS OR\nIIVSTERESIS AND TIIEIR\nAPPLICATIONS\nHy\n・川\nりこ川\nA Volumein the Elsevier Series in Electromagnetism\n\nIIathematical MIodels ofHysteresis\nandTheir Applications\nA Volumein the Elsevier Seriesin Electronagnetism\n\nElseひier Science Intevnet Honepqge\nhttp:lltxひ.elseひiercon\nConsulttheElsevierhomepageforfullcatalogueinfornnationonallbooks,journals\nelectronicproducts andservices\nElsevier Seriesin Electromagnetism\n(Series fornnerly knownas AcadenicPress Series in Electronagnetisn)\nEditedby\nISAAKMAYERGOYZUniversity ofMarylandCollegeParkUSA\nElectromagnetismis a classical area Ofphysics and engineering that stillplaysa very\ninportantroleinthedevelopmentofnew\ntechnology Electonagnetisnoftenserves\nalink between electrical\nengineers,naterial scientists,andphysicists This se\nriespresen",
  "page_count": 492,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\磁気特性\\ヒステリシス\\00_教科書\\Mathematical Models of Hysteresis and Their Applications.pdf"
 },
 {
  "filename": "Matrix continued fraction expansion and inversion by the generalized matrix Routh algorithm.pdf",
  "title": "IT,J, COATROL, 1974, VOL. 20,NO.5,727‑737",
  "authors": "Matrix continued fraction expansion and inversion by the",
  "abstract_excerpt": "Matrix continued fraction expansion and inversion by the\ngeneralized matrix Routh algorithm\nL\nS.SHIEHt and\n『. GAUDIANOt\nA generalizedmatrix\nRouth algorithin\niら estahlighct\ntC eypunt\nl\nmatrix\ntransfer\nfunction into the matrix continuetl fraction of threu Inatri Cauer forns:\nIy the use\nOf the generalizedl matrix Iouth algorithm\nanl ytate‑space techniulues; a\nmnethod is\nestablishedl for\npertornning the inatrix continuedl fraction inversion\nThe proceclurい\nis anenable to (ligital computation\n1.\nIntroduction\nA transfer function natrix is often used to express therelationship between\nthe inputs and outputs ofa nulti‑terminal circuit\noI\na\nnulti‑variable contiol\nThe expansionof the\ntransfer function\nmatrix\ninto\na\nnatrix\nCOIl‑\ntinued fraction and the inversion of\na matrix continued fraction to\na tr",
  "page_count": 11,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\MOR_モデル縮約\\CLN\\Matrix continued fraction expansion and inversion by the generalized matrix Routh algorithm.pdf"
 },
 {
  "filename": "Model Order Reduction Based on Runge-Kutta Neural Network.pdf",
  "title": "MODEL ORDER REDUCTION BASED ON RUNGE-KUTTA",
  "authors": "NEURAL NETWORK",
  "abstract_excerpt": "Model Order Reduction (MOR) methods enable the generation of real-time-capable digital twins,",
  "page_count": 21,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\MOR_モデル縮約\\Model Order Reduction Based on Runge-Kutta Neural Network.pdf"
 },
 {
  "filename": "Numerical Meth Engineering - February 1987 - Zienkiewicz - A simple error estimator and adaptive procedure for practical.pdf",
  "title": "INTERNATIONAL JOURNAL rOR NUMERICAL METHODS IN ENGINELRINC, VOL24,337‑357(198",
  "authors": "A SIMPLE ERROR ESTIMATOR AND ADAPTIVE",
  "abstract_excerpt": "A SIMPLE ERROR ESTIMATOR AND ADAPTIVE\nPROCEDURE FOR PRACTICAL ENGINEERING ANALYSIS\n0.CZIENKIEWICZANDJ.zZHU\nDepartent of CiziL Engineering, University of Swunsea, Swunseq,SAZ 8PP UK\nSUMMARY\nA\nnew\nerror estimator is prescnted which\nis not only rcasonably\naccurate\nbut whose evaluation\nis\ncomputationally so simple thatjt can be readily innplernented in existing 「inite element codes\nTheestinnatorallowstheglobalenergynormerrorto be wellestimatedandalsogivesa\nevaluationof\nlocal errors It can thus be conbined with a full adaptive process ofrefincnncnt ornore simply, provide\nguidance for mesh redesign which allows the user to obtain a desired accuracy with one or two trials\nWhencombined withanautonaticneshgeneratoraveryefficientguidanceprocesstoanalysisisavailab\nEstimates other than theenergy norm",
  "page_count": 21,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\FEMの定式化\\誤差の理論\\Zienkiewicz-Zhu_error_estimator\\Numerical Meth Engineering - February 1987 - Zienkiewicz - A simple error estimator and adaptive procedure for practical.pdf"
 },
 {
  "filename": "Optunaによるブラックボックス最適化.pdf",
  "title": "横械学習のハイパーパラメータ調整",
  "authors": "JPTUNA",
  "abstract_excerpt": "ミドルウェアのパフォーマンス向上\n料理のレシピ改善\nそのほか手間のかかるあらゆる最適化を自動化する方法を\n\n言が合まれている場台があります‑また 内谷を車新する場台があります。\nJPTUNA\nOptunaは株式会杜 Preferred Ietuロrls の日本国およびその地の国における商標ま\n本書に揖Xきれている会杜名\n製品名は;\n本書左発行するにあたって;\n内奇に誤りのないょうてきる限りの注意を払いましたが;\n本善の内容を通用した結果生じたこ,\nまた; 適用てきなかった結果について; 若者\n出版社とも一切の責任を負いませんのこご丁乗くだきい.\n本善は, 「若作権法」 によっ一; 若作権等の権利が保譲きれている者作物です. 本\n有しています. 本善の全部または一部につき, 無断て転戦;\n根写機製,)子的装置への\n入力等をされると着作権等の権利長善となる場合があります. また; 代行楽者等の第\n三者によるスキャンヤデジゥル化は; たとえ個人や家庭内での利用であっても善作権法\n上認められておりませんのここ注意くだきい.\n本書の無断榎写は;善作権法上の制̲事項を隊き,\n禁じられています本書の複写複\n製を希望きれる場合は』\nこのつ̲事町に下記‑連幣して許語を得てくだきい̲\n電誘 03‑5244‑5088,FAI 03‑5244‑5089, e‑mail:infolejcopyorjp\nIロpi\n出版者善作権管理楼構 委託出版物>\n\nまえがき\n深層学習に代表きれる機械学習技術によって, 多くの仕事が自動化きれつつあ\nります. 機械学習は処理のルールをデータから \"自動\" で習得する技術ではあり\nすが, 依然として, 人間が \"手動\" て決めなければならない設定項目 (ハイパーパ\nラメータ) が多く存在しますハイパーパラメータは;\nときおり機械学習モデル\nの性能を大きく左右するためそ",
  "page_count": 223,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\00_教科書\\Optunaによるブラックボックス最適化\\Optunaによるブラックボックス最適化.pdf"
 },
 {
  "filename": "PSO (Particle Swarm Optimization）の制御設計への応用.pdf",
  "title": "PSO(Particle Swarm Optimization)の",
  "authors": "PSOの基本的な考え方",
  "abstract_excerpt": "制御設計への応用\n1\nPSOの基本的な考え方\n2.\nPSOの探索能力の評価\n3.\nPゆ制御の自動パラメータ調整\n4\n燃料電池におけるPMモータのPSOを使った\nパラメータ設計\n山\nNeorium Technology\n非線形最適化のアルゴリズム\n最急降下法\n句配\nニュートン法\n準二ユートン法\nニューラルネット\nNelder‑Nlead法\n(ホップフィールド型)\n(シンプレックス法)\n非句配\nPSO\n遺伝的アルゴリズム(GA) 大\n連続変数(実数)\n離散変数(整数)\nParticle Swarm Optimization(生物群最適化)\nNeorium Technology\n\n1 Particle Swarm Optimizationの基本的な考え\nJ Kennedy & 尺 Eberhan, 1995\n生物の社会的振る舞い (飼の療得行動)一最適解の探索\nx(k+リ)=x(ん)+v(ん)\nG\nP (ん)‑x(ト\nPersomal\n探索個体の位置\nBest\n(Pは個体番号)\nGlobal\nBest\n探索個体の速度\nk\n更新回数\n一様乱数(w‑0.7,C‑2)\n(3)\nParticle Swarm Optimization\n(ANovelParadigm forAtenna Designs)より\n山\nNeorium Technology\n2 PS0の探索能力の評価(Rastrigin関数を例に)\n2\nf(ちz)‑20+*\n一IO[cos(2m\n十Cos(2n)]\n1\n1E』\n川\n1り]\n町\n上\n=1\n大域的最小値f(O,0)=0\nNeorium Technology\n十X\n\nPSOの探索能力の評価(Rastrigin関数を例に)\n探索個体数=10, 探索回数=1000ロ\nV‑0.7\n9 C=2.0,\n初期値=‑5∼5の乱数\n19\"\n1ロ'\n1\nW\n*\nxP =\n10  \n探索",
  "page_count": 8,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Particle Swarm Optimization\\PSO (Particle Swarm Optimization）の制御設計への応用.pdf"
 },
 {
  "filename": "Pförtner et al - 2023 - Physics-Informed Gaussian Process Regression Generalizes Linear PDE Solvers.pdf",
  "title": "Physics-Informed Gaussian Process Regression",
  "authors": "Generalizes Linear PDE Solvers",
  "abstract_excerpt": "Linear partial differential equations (PDEs) are an important, widely applied class of mech-",
  "page_count": 50,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\Physics_informed\\Pförtner et al - 2023 - Physics-Informed Gaussian Process Regression Generalizes Linear PDE Solvers.pdf"
 },
 {
  "filename": "Physics-Embedded Neural Networks Graph Neural PDE Solvers with Mixed Boundary Conditions.pdf",
  "title": "Physics-Embedded Neural Networks: Graph Neural",
  "authors": "PDE Solvers with Mixed Boundary Conditions",
  "abstract_excerpt": "Graph neural network (GNN) is a promising approach to learning and predicting",
  "page_count": 12,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Graph_Neural_Network\\Physics-Embedded Neural Networks Graph Neural PDE Solvers with Mixed Boundary Conditions.pdf"
 },
 {
  "filename": "Physics-Informed Neural Network (PINN) Evolution and Beyond A Systematic Literature Review and Bibliometric Analysis.pdf",
  "title": "Citation: Lawal, Z.K.; Yassin, H.; Lai,",
  "authors": "D.T.C.; Che Idris, A. Physics-Informed",
  "abstract_excerpt": ": This research aims to study and assess state-of-the-art physics-informed neural networks",
  "page_count": 23,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\00_教科書\\PINN\\Physics-Informed Neural Network (PINN) Evolution and Beyond A Systematic Literature Review and Bibliometric Analysis.pdf"
 },
 {
  "filename": "Physics-Informed Neural Network Method for Space Charge Effect in Particle Accelerators.pdf",
  "title": "This work is licensed under a Creative Commons Attribution 4.0 License. For more information, see https://creativecommons.org/licenses/by/4.0/",
  "authors": "This article has been accepted for publication in a future issue of this journal, but has not been fully edited. Content may change prior to final publication. Citation information: DOI",
  "abstract_excerpt": "The electromagnetic coupling of a charged particle beam with vacuum chambers is of great",
  "page_count": 10,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\加速器\\ビームトラッキング\\Physics-Informed Neural Network Method for Space Charge Effect in Particle Accelerators.pdf"
 },
 {
  "filename": "Pythonで機械学習入門.pdf",
  "title": "敵対的生成ネットワークまで予測して",
  "authors": "Ohmsha",
  "abstract_excerpt": "みましょう 』\n大関真之善\n鏡よ 鏡\nこのリンゴは\nもしかして?\n̲7\nbn\nメ学習\n@予測\nOhmsha\nいナ\n生成ニュ‑ラルネットワ‑ク\n識別ネットワ‑ク\n元デー\nBottlneck‑\ncnnl\ncnn2\nb\ncnn3\n1I\n\nPythonで\n機械学習入門さ\n深層学習から敵対的生成ネットワークまで\n大関 真之 善\nOhmsha\n\nPythonで\n機械学習入門\n深層学習から敵対的生成ネットワークまで\n大関真之善\nOhmsha",
  "page_count": 410,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\00_教科書\\機械学習\\Pythonで機械学習入門.pdf"
 },
 {
  "filename": "Raissi et al - 2017 - Machine learning of linear differential equations using Gaussian processes.pdf",
  "title": "Machine Learning of Linear Diﬀerential Equations using",
  "authors": "Gaussian Processes",
  "abstract_excerpt": "This work leverages recent advances in probabilistic machine learning to",
  "page_count": 18,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\Physics_informed\\Raissi et al - 2017 - Machine learning of linear differential equations using Gaussian processes.pdf"
 },
 {
  "filename": "Solving_Dense_Nonsymmetric_Linear_Systems_Arising_from_Integral_Formulations.pdf",
  "title": "IEEE TRANSACTIONS ON MAGNETICS,",
  "authors": "VOL 32, NO.3, MAY",
  "abstract_excerpt": "VOL 32, NO.3, MAY\n1996\n1377\nSolving Pense TVonsynnnnetric LinearSystens\nArising from Integral Eormulations\nJukka Salonen;\nKoski;Prank Cameron; KimmoForsman and Lauri IKettunen\nTampere University of Technology; Laboratory of Electricity and Magnetism P.O.Box 692,FIN‑3\nAbgtract一\nSeveral inethods for solving dense non‑\nTABLEI\nsynnznnetric linear systenns arising fronn volunneintegral\nSozUrioN TIMEs OBTAINED BY LUFACTORIZATION\nfornnulations lave been tested\nOur results slow tlat\nNunnber o「equations\n250\n500\n1000\n2500\niterative solvers based\no1 IKrylov nlethods are signif‑\ncanitly faster tlan direct Inethods,ifa cgood\" precon‑\nNunerical Recipes LU\n1.02\n9.32\n89.4\n1536\nditioneris used\nInaddition tleresults reveal thattle\nLAPACK LU\n0.14\n0.79\n6.0\n108\ninplennentation of a Inethodis of vital innporta",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\モーメント法・境界要素法\\Solving_Dense_Nonsymmetric_Linear_Systems_Arising_from_Integral_Formulations.pdf"
 },
 {
  "filename": "The Electromagnetic Theory of Coaxial Transmission Lines and Cylindrical Shields.pdf",
  "title": "The Electromagnetic Theony ot Coaxial Transmission Lines",
  "authors": "Gurh LuhES",
  "abstract_excerpt": "and Cylindrical Shields\n』 cylimdrical conducr\ntubr uithin whi:n\nGurh LuhES\nhave 『aumdapplication in radi g[aLion島 [ connect\nAブ』 Part ulthe developmient\nGpanenits\nadarhe\naBuinst inductive eHertg\nyhich i aHarded by\nrhe ouler\nheynnd the r』四巳a PTEgnt applization houh\nteg\n{requency\nHE mathematical theory of wave propagation along a conductor\nwith an external cuaxial return ig very old, going back t the\nworl of Rayleigh Heavigide and ]|\nThungnn\nNIuch innportant\nwork has been done in develaping and cxtending this theory\nAmong\nthe problems dealt with in rhis developnent uay be listed the follow‑\nthe extension o[ the theory to gygtennis consisting ロ\nplurality\no cylindrical conductorg; the invegtigation of shielding and cro\nin coaxial systenis and the efects o【 eccentriciry; the extension of the\npa",
  "page_count": 25,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\98_部品・材料\\リッツ線\\The Electromagnetic Theory of Coaxial Transmission Lines and Cylindrical Shields.pdf"
 },
 {
  "filename": "The Rayleigh Region.pdf",
  "title": "PROCEEDINGS OF",
  "authors": "Awgzst",
  "abstract_excerpt": "THB\nAwgzst\njity oMichigan Ann Arbor Rept 3648‑2‑T,Jan 1963.\n[17] Iouyounjian, R\" The backscattering\nfronn a circular\n[13] Blore, WE\n'The radar cross section of ogives, clonble‑bacled\nAbpi Sci: Res  vol\n1956,p 165.\ncones 〔louble‑roundecl cones; and\n[18] Veston, V̲II Scattcring fronl a circular\nDept of Elec\non Antenny〔s and Probuygiignl\nvol AP‑12,\n1964,PP 582‑590,̲\nUniversity of Toronto; CanadaResearch Rept12,\nl14] Iennaugh 巳一MI and D L Moffatt Ontheaxial echoarca of\n1957.\nthe cone‑sphereshape Proc IRE (Covvcspondcncc),vol 50,Eeb\n[19] Peters, Lっ End‑Gre echo area of\nthin bodies, IRヱ Tr4nzs\n1962,P 199.\non Antcnnas\nPvobagation vol AP‑6,Jan 1958,PP 133‑139\n[15] Senior\nB\nThe backscattering cross section\nof &\ncolle‑\n[20] Siegel, K:̲\nML Bistatic radars and forwar〔l scatter\npresented\non Antcnnas a",
  "page_count": 9,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\モーメント法・境界要素法\\The Rayleigh Region.pdf"
 },
 {
  "filename": "The question of forces in Electromagnetics.pdf",
  "title": "lgep.supelec.frlm",
  "authors": "Labovatoive de Geie",
  "abstract_excerpt": "Labovatoive de Geie\nbossavit@lgep\nThe ques\ninSlectron\nToKV\nFriday 11 June2004\nOCd cont\nThanks to organizersand\nProf Takagiforsuppor\nnoderngeo\n\nselpersolablbossavit.htnl\nOsSqVit\nctrique deParis (CNNRS)\nsupelecfir\nn gfforces\nnagnetics\nOverlays,notpartof\npresented slides, contain\noversies\nsummary oforalcomments\netricaCtools\n\nqagnetof\nCountless problems require force comp\nandlormagnets Mostoften,the",
  "page_count": 103,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\01_教科書\\00_有限要素法・数値解析\\Bossavit\\The question of forces in Electromagnetics.pdf"
 },
 {
  "filename": "Three-dimensional eddy current analysis by the boundary element method using vector potential.pdf",
  "title": "Electricity Magnetisn felds",
  "authors": "Okayanna University",
  "abstract_excerpt": "Okayanna University\nYear 1990\nThree‑dinensional eddy current analysis\nby the boundary elenent nethod using\nvector potential\nHTsuboi\nIVI. Tanaka\nOkayana University\nOkayanna University\nThis paper is posted at eScholarship@OUDIR\nOkayana University Digital Infornnation\nRepository\nIlescholarshiplib.okayana‑u.acjplelectricity̲and̲nagnetisn/121\nhttp;\n\n454\nIEEE TRANSACTIONS ON MAGNETICS, VOL. 26, NO̲ 2,MARCH\n1990\nTIRBR‑DIMENSIONAL\nEDDy\nCURRENT ANALYSIS\nBY THじ BOUNDARY\nELEMENT METHOD USING VECTOR POTENTIAL\nH\nTsuboi\nand\nM.Tanaka\nDcpartmentof\nElectrica】and\nElectronic\nEngineering,\nOkayama University;\nTsushima;\nama\n700, Japan\nAbsiract:\nA\nboundayyclement\nmethod\nusing\na\nmagnetic\nappcars\non\nthe\nboundany surfaces\nbetween\nconductor\nand\nvector\npotential for\neddy\ncurrent\nanalysisis\ndescribed\nair\nthrcc‑dimens",
  "page_count": 5,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\非破壊検査\\Three-dimensional eddy current analysis by the boundary element method using vector potential.pdf"
 },
 {
  "filename": "h051056_IEEJ-20210910X01601.pdf",
  "title": "SA-21-066〜081",
  "authors": "RM-21-087〜102",
  "abstract_excerpt": "RM-21-087〜102\n電気学会研究会資料 \n  \nThe Papers of Joint Technical Meeting on\n\"Static Apparatus\" and \"Rotating Machinery\",\nIEE Japan\n静⽌器/回転機合同研究会\nSA-21-066〜081\nRM-21-087〜102\n2021年9⽉10⽇\n⼀般社団法⼈電気学会\nThe Institute of Electrical Engineers of Japan\n 東京都千代⽥区五番町６-２\n購読番号：h051056 複製禁止\n\n購読番号：h051056 複製禁止\n\n電気学会研究会資料⽬次\n  \n静⽌器/回転機合同研究会\n  \nテーマ「電磁界数値計算技術とその応⽤」\n  \nSA-21-066\nRM-21-087 \nCNNを⽤いた複数電流条件におけるトルクリップル推定⾼精度化に関する検討\n◎佐々⽊秀徳（法政⼤学）\n...... 1\n  \nSA-21-067\nRM-21-088 \n敵対的⽣成ネットワークと畳み込みニューラルネットワークを活⽤したIPMSMの\n回転⼦形状最適化\n◎清⽔悠⽣,森本茂雄,真⽥雅之,井上征則（⼤阪府⽴⼤学）\n...... 7\n  \nSA-21-068\nRM-21-089 \nDeep Image Priorを⽤いた磁気シールドの位相最適化に関する基礎的検討\n◎⼀⾊梨⾐,川俣良太,若尾真治,村⽥ 昇（早稲⽥⼤学）\n...... 13\n  \nSA-21-069\nRM-21-090 \n適応代替モデルによるIPMモータのトポロジー最適化\n◎佐藤駿輔,五⼗嵐⼀（北海道⼤学）\n...... 19\n  \nSA-21-070\nRM-21-091 \n永久磁⽯モータの制御を考慮したトポロジー最適化の基礎検討\n◎林 翔吾（北海道⼤学）\n久保⽥芳永,相⾺慎吾（本⽥技術研究所）",
  "page_count": 99,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\リニアドライブ\\リニアドライブ2021\\h051056_IEEJ-20210910X01601.pdf"
 },
 {
  "filename": "nec2prt1.pdf",
  "title": "NUMERICAL ELECTROMAGNETICS CODE (NEC)",
  "authors": "METHOD OF MOMENTS",
  "abstract_excerpt": "METHOD OF MOMENTS\nPARTI:PROGRAM DESCRIPTION\nTHEORY\n6\nJ\nBurke\nA\nJ. Poggio\nJanuary 1981\n'Ihisiv aninformwlimtendedprimarily 「orinierna】\nlimited exiernnldigiriburion The\nwpiniwns gnd\ncunclusiony sraiud\n【h・ aurhur nud m』y\nmい} m【\nthose o「rhic\nahnruimry\nawrence\nLivernore\naboratgry\n「enori\n\nDISCLAIMER (Fronthe originalNECdocunent)\nThis docunent\nwas prepared asan account Of wOrk sponsored by an agency Of the United States Governnent\nNeither the United States Government nor the University Of California nor any Of their enployees \nwarranty; express or implied\nOr assunes any legaliability\nor responsibility for the accuracy, conpleteness\nor\nusefulness ofany infornatiom, apparatus, product Or process disclosed Orrepresents that its use would\nprivately ovned rightsReference herein tO any specific conner",
  "page_count": 87,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\モーメント法・境界要素法\\NEC\\nec2prt1.pdf"
 },
 {
  "filename": "pulse_Genetic algorithms and solid state NMR pulse sequences.pdf",
  "title": "Genetic algorithms and solid state NMR pulse sequences",
  "authors": "Matthias Bechmann a,⇑, John Clark b, Angelika Sebald a",
  "abstract_excerpt": "Matthias Bechmann a,⇑, John Clark b, Angelika Sebald a\na Department of Chemistry, University of York, YO10 5DD York, UK\nb Department of Computer Science, University of York, YO10 5DD York, UK\na r t i c l e\ni n f o\nArticle history:\nReceived 1 November 2012\nRevised 17 December 2012\nAvailable online 5 January 2013\nKeywords:\nSolid-state NMR\nRecoupling\nOptimisation\nGenetic algorithms\na b s t r a c t\nThe use of genetic algorithms for the optimisation of magic angle spinning NMR pulse sequences is dis-\ncussed. The discussion uses as an example the optimisation of the C71\n2 dipolar recoupling pulse sequence,\naiming to achieve improved efﬁciency for spin systems characterised by large chemical shielding aniso-\ntropies and/or small dipolar coupling interactions. The optimised pulse sequence is foun",
  "page_count": 10,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\計測・信号処理\\pulse_Genetic algorithms and solid state NMR pulse sequences.pdf"
 },
 {
  "filename": "pulse_Improving excitation and inversion accuracy by optimized RF pulse using genetic algorithm.pdf",
  "title": "Improving excitation and inversion accuracy by optimized",
  "authors": "RF pulse using genetic algorithm",
  "abstract_excerpt": "In this study, a Genetic Algorithm (GA) is introduced to optimize the multidimensional spatial selective RF pulse to reduce the pass-",
  "page_count": 8,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\計測・信号処理\\pulse_Improving excitation and inversion accuracy by optimized RF pulse using genetic algorithm.pdf"
 },
 {
  "filename": "カーネル密度推定とガウス過程を用いた非線形非ガウスシステムの確率的モデリング.pdf",
  "title": "システム制御情報学会論文誌，Vol. 33, No. 12, pp. 303–313, 2020",
  "authors": "Probabilistic Modeling for Nonlinear and Non-Gaussian",
  "abstract_excerpt": "303\n論\n文\nカーネル密度推定とガウス過程を用いた\n非線形・非ガウスシステムの確率的モデリング*\n金田　泰昌†・鈴木　　聡†・入月　康晴†\nProbabilistic Modeling for Nonlinear and Non-Gaussian\nSystems Using Kernel Density Estimation\nand Gaussian Process*\nYasuaki Kaneda†, Satoshi Suzuki† and Yasuharu Irizuki†\nRecently, in order to model systems with uncertainty, probabilistic modeling with conditional\nprobability distribution are widely noticed. Modeling the systems as probability density function\nenables us to apply strategies considering unsertainty to control systems. One of the most famous\nmodeling methods is Gaussian process regression (GPR). GPR is often used in the ﬁeld of control\nsystems and its eﬀectiveness is demonstrated in many papers. However, since GPR can represent\nonly Gaussian distribution, GPR cannot always achieve good performances for s",
  "page_count": 11,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\カーネル密度推定とガウス過程を用いた非線形非ガウスシステムの確率的モデリング.pdf"
 },
 {
  "filename": "サンプルで学ぶMATLABによるディープラーニング実践ガイド.pdf",
  "title": "サンプルで学ぶ MATLAB による",
  "authors": "NlathVorks",
  "abstract_excerpt": "ディープラーニング実銭ガイド \nNlathVorks\n\nはじめに\nこの ebook は 「ディープラーニングとは何か?」をM説した MATLAB\n始めるディープラーニングの続編です今回は デイープラーニングの実\n銭的な手法を解説しますネットワークの学習を行うための 次の 3 つの\nアプローチをご紹介します。\nゼロからネットワークを学習させる\n転移学習を使用してx存ネットワークを再学習させる\n眠存ネットワークを学習させて セマンティックセグメンテーションに\n適用する\nこれらの例では画像の分類にディープラーニングを使用していますが\n画像以外のアプリケーションヘの使用も増えてきていますoebook の第\n2 部では 画像に使われるデイープラーニングの手法の多くが信号データ\nにも適用できることを示す 2 つの例をご紹介します。\nすべてのサンプルおよびコードはダウンロート可能ですっまた デイープ\nラーニング向け MATLAB 30 日間無料評価版も件せてダウンロードする\nことで今すぐお試しいただけます。\n基磯を復習\nディープラーニングとは?3.33\nディープラーニングvs 機械学習3:48\nNlathWorks\n2 | サンプルで学ぶ MATLAB によるディープラーニング実\n\n実路例 1: ゼロからモデルを学習させる\nこの例では 畳み込みニユーラルネットワーク (CNN) を学習させて\nシンプルなデータセットを使用することで 計算処理能力の問題\n手書き数字の識別を行います0 から 9 の手書き数字が 60,0O0 個舎ま\nタセットが大きすぎてメモリに収まらないといった問題に直面する\nれる MNIST データセットのデータを使用します以下は MNIST データ\nなく ディープラーニングのワークフローにおける主要な手順をすべ\nセットに合まれる 25 個の手書き数字のランダムなサンプル",
  "page_count": 33,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\00_教科書\\深層学習\\サンプルで学ぶMATLABによるディープラーニング実践ガイド.pdf"
 },
 {
  "filename": "プラズマとメタマテリアルとの出会いによる新マテリアル.pdf",
  "title": "The Japan Society",
  "authors": "Science",
  "abstract_excerpt": "of\nplasma\nScience\nand\nNuclear\nEusion\nResearch\nJ.PlasmaFusion Res Vol88,No5(2012)251‑260\n解説\nプラズマとメタマテリアルとの出会いによる新マテリアル\n酒井  道\n京都大学大学院工学研究科\n(原穂受付 : 2012年2月3日)\n近年注目されているメタマテリアル構造とプラズマ状態を組み合わせることで;\n従来のメタマテリアルやプ\nラズマを超えた新たな電磁波嫌質としての \"材料'\n状態\nシステムが生まれると期待できる. 特に広範囲のパラ\nメータ領域を包合する複素誘電率の効果;\nおよび誘電率が伝報電磁波の電界に依存する非線形効果は;\n特異な現\n象を生み出し, 新たなプラズマ応用分野への開拓にもつながると期待される̲\nKeywords:\nmetanaterial,refractiveindex,pernnittivity,perneability\n1. はじめに\nいる, ということだけが目的ではない.\nもちろん, 後で述\nある \"モノ\" (後で述べるように;\nこれは; 「物質」 とい\nべるような;屈折率を負にする,といったことはバルク材\nう意味だけではなく; もっとあいまいに一般化されたシス\n料を使っては実現できないので;\nそのような側面もあるに\nテムなども合みたい)が; AとBとCという構成要素からはあるが; それに止まらない.\nできていると考えよう. そのとき,そのモノが全体として\nむしろ, 材料学的な側面を合みながら,\nそれ以外の分野\nどのような機能をもつか考えてみると, まず最初に浮かぶ\nに対して6; 従来の考え方を漆ぐコンセプトを提供するも\n推論は以下のようになるだろう: Aがどのくらい合まれの; と考えたい:ここで; 仮定として, 波に対して作用す\nて, Bがどのくらい合まれて; そして",
  "page_count": 10,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\98_部品・材料\\メタマテリアル\\プラズマとメタマテリアルとの出会いによる新マテリアル.pdf"
 },
 {
  "filename": "多巻線変圧器の定常時および励磁突入時の特性とその等価回路.pdf",
  "title": "多巻線変圧器の定常時および耐磁突入時の特性とその等価回",
  "authors": "Inductance Characteristics of a MMulti‑VVinding Transfornner and its Eq",
  "abstract_excerpt": "正 鼻 稲垣\n恵造*\nInductance Characteristics of a MMulti‑VVinding Transfornner and its Eq\nunder Steady State and Magnetizing Inrush Conditions\nKeizo Inagaki Member\nI thi paper; the niethod of dezivinng the practical‑use equivalent circuit of 3 winding tr\ncauculating rnagnetizing inrush current Of a transformner ig ghown\nOn the basis of this equivalent circuit;\nthesinnulation circuit for general‑puzpoge progranns; guch as EMITP; can be derived: Refer\nabout the infuence to a rnagnetizing inzugh current calculation result by equivalent circuit constitutio\nキーワード:変圧器; 等価回路;\n蒲れインダクタンス, 闘磁インダクタンス,\nIaywords: transforyer; equivalent circuit, leakage inductance; exciting inductance, rnagnetizing inrush\n形等価回路の考え方を誤って適用したり;\n変圧器の刷磁現\n1.\nまえがき\n象を十分に理解しないまま誤った回路で解析している例\n電力系統における変圧群のふるまいを BMITP(1} などの\n多い。 EMITP の",
  "page_count": 7,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\電位振動解析\\多巻線変圧器の定常時および励磁突入時の特性とその等価回路.pdf"
 },
 {
  "filename": "大規模歩容データベースを用いたガウス過程回帰による年齢推定の評価.pdf",
  "title": "IPSJ SIG Technical Report",
  "authors": "",
  "abstract_excerpt": "大規模歩容データベースを用いた\nガウス過程回帰による年齢推定の評価\n奥\n村\n麻\n由†1\n槇\n原\n靖†1\n八\n木\n康\n史†1\nこれまで人の歩き方の個性である歩容に基づく個人認証の研究が数多く行われてき\nたが，歩容に基づく年齢推定の研究は数少なく，また用いられているデータベースの\n被験者数や年齢層の広がりが十分ではなかった．そこで本研究では，2 歳～94 歳まで\nの幅広い年代層を含む1,730 人の被験者からなる大規模歩容データベースを用いて，\nガウス過程回帰による年齢推定の評価を行う．まず歩容特徴を入力ベクトル，年齢を\n出力とするガウス過程回帰を考え，入出力の組からなる学習データを用いてガウス過\n程回帰のパラメータを学習する．次に，学習されたパラメータを用いて，新たな歩容\n特徴の入力ベクトルに対する，年齢の期待値と分散を推定する．実験では，平均シル\nエット，周波数領域特徴，歩行周期を歩容特徴として，大規模歩容データベース中の\n879 人を学習に用い，851 人に対して年齢推定を行った．結果として，周波数領域特\n徴を用いた年齢推定が最も推定精度が高く，また30 代女性，40 代男性の推定精度が\n高いことが示された．\nEvaluation of Age Estimation by Gaussian Process Regression\nusing a Very Large-scale Gait Database\nMAYU OKUMURA ,†1 YASUSHI MAKIHARA †1\nand YASUSHI YAGI†1\nWhile many gait recognition methods have been recently proposed, the studies about\ngait-based age estimation is unexplored and the",
  "page_count": 8,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\ガウス過程回帰\\大規模歩容データベースを用いたガウス過程回帰による年齢推定の評価.pdf"
 },
 {
  "filename": "巣別れを導入したParticle Swarm Optimizationアルゴリズムの提案.pdf",
  "title": "巣別れを導入したParticle Swarm Optimization",
  "authors": "The Proposal of the Particle Swarm Optimization",
  "abstract_excerpt": "アルゴリズムの提案\nThe Proposal of the Particle Swarm Optimization\nAlgorithm with Colony Fission\n松山隼人\nHayato Matsuyama\n広島市立大学大学院情報科学研究科\nEmail: hmatsuyama ＠ints.info.hiroshima-cu.ac.jp\n串田淳一\nJun-ichi Kushida\n広島市立大学大学院情報科学研究科\nEmail: kushida ＠hiroshima-cu.ac.jp\n原章\nAkira Hara\n広島市立大学大学院情報科学研究科\nEmail: ahara ＠hiroshima-cu.ac.jp\n高濱　徹行\nTetsuyuki Takahama\n広島市立大学大学院情報科学研究科\nEmail: takahama ＠hiroshima-cu.ac.jp\nAbstract—Particle swarm optimization (PSO) is a popu-\nlation based stochastic optimization algorithm. PSO works\nwith a swarm of simple agents and has been successfully\napplied in many areas. However, to avoid premature\nconvergence in multi-modal function is difﬁcult for PSO.\nIn this paper, we introduce the concept of colony ﬁssion\nto PSO and aim to improve search performance in multi-\nmodal function. The",
  "page_count": 4,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\Particle Swarm Optimization\\巣別れを導入したParticle Swarm Optimizationアルゴリズムの提案.pdf"
 },
 {
  "filename": "改良型免疫アルゴリズムによる多峰性関数の大域的最大値の探索.pdf",
  "title": "改良型免疫アルゴリズムによる",
  "authors": "Key Words : genetic algorithm(GA), immune alg",
  "abstract_excerpt": "多峰性関数の大域的最大値の探索\n中村秀明1・松本 剛2・宮本文穂3\n1知能情報システム工学科\n2日本電信電話株式会社(ＮＴＴ)\n3知能情報システム工学科\n　近年，遺伝的アルゴリズム（ＧＡ：Genetic Algorithm）の組合せ最適化問題や多峰性関数の最適化問題\nなどへの適用が盛んに行われている．ＧＡは多点探索と交叉オペレ－タにより最適解を得るため，状態空\n間を広く探索することが可能である．しかしながら，ＧＡでは，解の探索が不十分な時点で集団の多様性\nが急速に失われることがある．この問題を解決するため，集団の多様性維持を目的とした手法がいくつか\n提案されている．\n　免疫アルゴリズム（ＩＡ：Immune Algorithm）は，生体のもつ免疫システムを真似た最適化手法であり，\n解の多様性を維持するとともに，複数の準最適解を得ることが可能である．本研究では，最適設計問題に，\nこのＩＡを適用することを念頭に，ＩＡの改良を行い，収束を早くするとともに，より多様性を持った解\nの探索を可能とした．\n  Key Words : genetic algorithm(GA), immune algorithm(IA), optimization, global maximum, diversity\n１．はじめに\n　組合せ最適化問題では，考慮すべき組合せ数が，\n問題の規模に応じて指数関数的に増大するため，実\n用的な最適解が現実的な時間内に得られない場合が\n多い．特に，工学分野における最適設計問題などで\nは，制約条件が多かったり，設計パラメ－タ－が多\n数あるため，その組合せ数は，膨大な数となること\nが予想される．近年，このような組合せ最適化問題\nや多峰性関数の最適化問題などの解法として遺伝的\nアルゴリズム1),2)(ＧＡ：genetic algorithm)が盛んに\n用いられている．ＧＡは",
  "page_count": 8,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\進化計算\\改良型免疫アルゴリズムによる多峰性関数の大域的最大値の探索.pdf"
 },
 {
  "filename": "穴埋め式電磁気学.pdf",
  "title": "遠藤雅守⾎田淳子北林照幸",
  "authors": "Nasqnori Endo",
  "abstract_excerpt": "藤城武彦\nNasqnori Endo\nJunko Kuhida\nTeruyuki Kitabayashi\nTakehiko Fujishiro\nN\n];\n雷いて覚える。\n1\n(こ\n覚えて } く。\nしっかりと身につける。\n講談社\n\n表01\n電磁気学の物理量\n物理量\n記号\n単位\n英語\n素電荷\nelenentary electric charge\n1\nクーロン定数\nん三一\nNn?iC?\nCoulonbs constant\n真空の誘電率\nEo\nFlm\n二CZlN・n?pernittivity ofvacuun\nmagnetic perneability of\n真空の透磁率Ho\nHlm\n二Vb/Am\nvacuun\n誘電率\nElm =\nCZlNm\n2 pernnittivity;\ndielectric constant\n透磁率\nM\nHlm\n二Wb/Am magnetic̲pezneability̲\n北誘電率\nrelative pernittivity\nEo\n比透磁率\nK=\n上\nrelative nagnetic\nHo\npermeability\n1\nC=\n光速度\nnls\nspeed oflight\nVeoHo\n特性インピーダ\nHo\n二\ncharacteristic inpedance\nンス\nI\nVe\n電磁波のパワーI= SBc\nWln?\npower Of electronagnetic\n2\nwave\n電荷\nQ 9\nC\nelectiic chazge\n磁荷\nQm 9m\nWb\nmagnetic charge̲\n3\n電荷密度\nClm:\ncharge density\n面電荷密度?\nClmz\nsurface charge density\n線電荷密度\nClm\nlinechargedensity̲\n電場\n二豆一\nVlm\n二NIC\nelectric field\n9\n磁場の強さ\nAlm\nmagneti",
  "page_count": 215,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\01_教科書\\10_電磁気学・物理基礎\\和書\\穴埋め式電磁気学.pdf"
 },
 {
  "filename": "量子アニーリングを用いたメタマテリアル設計.pdf",
  "title": "*kitai_koki_18@stu-cbms.k.u-tokyo.ac.jp",
  "authors": "",
  "abstract_excerpt": "量子アニーリングを用いたメタマテリアル設計 \n(1 東大, 2NIMS, 3 早稲田大, 4JST, 5 理研)  \n◯北井孝紀1＊, Jiang Guo1, Shenghong Ju1,2, 田中周 3,4, \n津田宏治1,2,5, 塩見淳一郎1,2,5, 田村亮1,2,5 \n \n1. \nはじめに \n近年は機能性材料の合成技術が進歩し、内部の\n人工的な構造により自然には見られない特異な\n性質を持ったメタマテリアルの研究が活発に進\nめられている。一方で、材料設計において調整可\n能なパラメーターの数が増えると、可能な組合せ\nの数が指数関数的に増大し最適な構造を見つけ\nるのが困難になるという問題が生じる。より高度\nな材料設計を考えるうえで、この問題の解決は重\n要な課題である。そのためには、計算機上でのシ\nミュレーションや機械学習の手法を用いた設計\n過程の効率化や自動化が必要となる。[1] \n材料設計の問題として、与えた組成や構造に対\nして最適化対象の指標の値だけが評価可能で、そ\nの解析的な表記や勾配などに関する情報は得ら\nれないものと仮定する。そのような系における最\n適化はブラックボックス最適化と呼ばれており、\n一般的に難しい問題である。解法には遺伝的アル\nゴリズムやベイズ最適化のようなヒューリステ\nィックな手法が用いられることが多い。ベイズ最\n適化は、すでに得られているデータ点から目的関\n数の回帰モデルを学習し、そのモデルをもとに最\n適解を推定するSurrogate-based method と総称さ\nれる手法のひとつである。また、その推定された\n最適解における指標を実際に評価し学習データ\nに加えることで、さらなる最適解の推定を繰り返\nす。ベイズ最適化では回帰モデルにガウス過程と\n呼ばれるノンパラメトリックモデルを利用する\nが、問題設定や計算機環境に応じて別のモデルを\n選",
  "page_count": 2,
  "is_scanned": false,
  "relative_path": "04_機械学習と最適化\\FMQA\\量子アニーリングを用いたメタマテリアル設計.pdf"
 },
 {
  "filename": "量子計算_Experimental Realization of a Quantum Support Vector Machine.pdf",
  "title": "Experimental Realization of a Quantum Support Vector Machine",
  "authors": "Zhaokai Li,1,2 Xiaomei Liu,1 Nanyang Xu,1,2,* and Jiangfeng Du1,2,†",
  "abstract_excerpt": "Zhaokai Li,1,2 Xiaomei Liu,1 Nanyang Xu,1,2,* and Jiangfeng Du1,2,†\n1Hefei National Laboratory for Physical Sciences at the Microscale and Department of Modern Physics,\nUniversity of Science and Technology of China, Hefei 230026, China\n2Synergetic Innovation Center of Quantum Information and Quantum Physics,\nUniversity of Science and Technology of China, Hefei 230026, China\n(Received 1 December 2014; revised manuscript received 17 February 2015; published 8 April 2015)\nThe fundamental principle of artificial intelligence is the ability of machines to learn from previous\nexperience and do future work accordingly. In the age of big data, classical learning machines often require\nhuge computational resources in many practical cases. Quantum machine learning algorithms, on the other\nhand, cou",
  "page_count": 5,
  "is_scanned": false,
  "relative_path": "00_電磁界解析\\99_アプリケーション\\NMR・MRI\\量子計算\\量子計算_Experimental Realization of a Quantum Support Vector Machine.pdf"
 }
]
"""

CATALOG_ENTRIES = _json.loads(_CATALOG_JSON)


def get_bibliography_index(query: str = "") -> str:
    """Return formatted catalog entries.

    Args:
        query: empty string → all entries.  "__scanned__" → only
               scanned PDFs.  Otherwise, case-insensitive substring
               match in title + authors + abstract + filename.
    """
    q = query.strip().lower()
    if q == "__scanned__":
        sel = [e for e in CATALOG_ENTRIES if e.get("is_scanned")]
    elif q == "":
        sel = CATALOG_ENTRIES
    else:
        sel = []
        for e in CATALOG_ENTRIES:
            haystack = " ".join(str(e.get(k, "")) for k in
                ("filename", "title", "authors", "abstract_excerpt")).lower()
            if q in haystack:
                sel.append(e)

    if not sel:
        return f"No catalog entries match query: {query!r}\n"

    lines = [f"## radia_mcp bibliography index — {len(sel)} entries"]
    if query and q != "__scanned__":
        lines.append(f"(filtered by: {query!r})")
    lines.append("")
    for e in sel:
        fn = e.get("filename", "?")
        title = e.get("title", "?")
        a = e.get("authors", "")
        pages = e.get("page_count", 0)
        scanned = e.get("is_scanned", False)
        abs_text = e.get("abstract_excerpt", "")
        lines.append(f"### {fn}")
        lines.append(f"**Title**: {title}")
        if a:
            lines.append(f"**Authors**: {a[:200]}")
        flag = "  [SCANNED — OCR limited]" if scanned else ""
        lines.append(f"**Pages**: {pages}{flag}")
        if abs_text:
            lines.append(f"**Abstract**: {abs_text[:500]}")
        lines.append("")
    return "\n".join(lines)
