"""Regenerate binput_play_fixture.npz with the FIXED build_shape_functions.

Background (2026-05-02):
    Three bugs were found in radia/src/radia/hysteresis_io.py via MATLAB
    forensic cross-validation for the IGTE'26 submission:
        1. load_mat: item['B'].flat[0] read only one scalar per branch
        2. build_shape_functions: sort direction inverted (asc -> desc fix)
        3. build_shape_functions: r=0 anchor lost to floating-point noise
    The pre-existing binput_play_fixture.npz was generated by the buggy code
    and therefore stored INCORRECT shape functions. This script rebuilds the
    fixture from the Potter-Schmulian B_input.mat (the originally documented
    source) using the corrected build_shape_functions.

Source data:
    W:\999_菅原賢悟\19_磁気ヒステリシス\2024_IGTE_共同研究\2024_03_08_H-input_B-input
    \Potter_Schmulian\B_input.mat
    (analytical Potter-Schmulian model, 20 BMax levels, dB = 0.095 T,
    Bmax_max = 1.9 T, generated by CASE_02.m)

Output:
    binput_play_fixture.npz with keys:
        K, eta, chi              - full set
        K_sub, eta_sub, chi_sub  - subset (typically K_full/4) for fast tests
        dB, Bplay
        r_0, f_0, r_1, f_1, ...  - per-operator (r, f) shape function tables
        r_sub_0, f_sub_0, ...    - per-operator subset tables
"""

import os
import numpy as np

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))
from radia.hysteresis_io import load_mat, build_shape_functions

DATA_FILE = (r"W:\999_菅原賢悟\19_磁気ヒステリシス\2024_IGTE_共同研究"
             r"\2024_03_08_H-input_B-input\Potter_Schmulian\B_input.mat")
OUT_FILE  = os.path.join(os.path.dirname(__file__), "binput_play_fixture.npz")


def main():
    print(f"Loading source data: {DATA_FILE}")
    loops, dB, BMax = load_mat(DATA_FILE)
    print(f"  {len(loops)} BH loops, dB = {dB:.4f} T, Bmax range "
          f"[{min(l['Bmax'] for l in loops):.3f}, "
          f"{max(l['Bmax'] for l in loops):.3f}] T")

    eta, f_tables, Bplay = build_shape_functions(loops, dB)
    K = len(eta)
    chi = eta.copy()
    print(f"  Identified K = {K} Play operators")

    # Build a "subset" version for fast tests (every 2nd operator -> K/2)
    sub_step = 2
    sub_idx = list(range(0, K, sub_step))
    eta_sub = eta[sub_idx]
    chi_sub = chi[sub_idx]
    K_sub = len(eta_sub)
    f_tables_sub = [f_tables[i] for i in sub_idx]

    out = {
        'K':       int(K),
        'K_sub':   int(K_sub),
        'eta':     eta,
        'chi':     chi,
        'eta_sub': eta_sub,
        'chi_sub': chi_sub,
        'dB':      dB,
        'Bplay':   Bplay,
    }
    for k in range(K):
        r, f = f_tables[k]
        out[f'r_{k}'] = np.asarray(r)
        out[f'f_{k}'] = np.asarray(f)
    for ki, k in enumerate(sub_idx):
        r, f = f_tables[k]
        out[f'r_sub_{ki}'] = np.asarray(r)
        out[f'f_sub_{ki}'] = np.asarray(f)

    np.savez(OUT_FILE, **out)
    print(f"\nSaved fixture: {OUT_FILE}")
    print(f"  Full set:   K = {K}")
    print(f"  Subset:     K_sub = {K_sub} (every {sub_step}-th operator)")


if __name__ == "__main__":
    main()
