"""Manufactured two-edge GetTrafo inverse with analytic orbit reclosure.

The target is generated by two smooth, topology-preserving pole-face modes.
Every LP candidate rebuilds the HDiv-MMM operator, solves the BDM1 state,
recovers both periodic design orbits with the native tracker, and rebuilds the
transfer matrices about those realized orbits.  The design Jacobian contains
the matrix-free ``dM+dB+dG+drhs`` state tangent, the exact flat-TET field
source tangent, the Lorentz variational equation, the implicit two-variable
orbit-closure derivative, moving field observations, and segment-length AD.

No optimizer finite difference is used.  The one numerical two-column
Jacobian used to seed each Broyden orbit root belongs only to orbit recovery.
"""
from __future__ import annotations

import argparse
import json
import platform
import time
from pathlib import Path

import numpy as np


RESPONSE_ENTRIES = (
    (0, 0), (0, 1), (1, 0), (1, 1),
    (2, 2), (2, 3), (3, 2), (3, 3),
    (4, 4), (4, 5), (5, 4), (5, 5),
)


def _peak_working_set_bytes():
    try:
        import psutil
        info = psutil.Process().memory_info()
        return int(getattr(info, "peak_wset", info.rss))
    except Exception:
        return None


def run(args):
    import ngsolve as ng
    from ngsolve.meshes import MakeStructured3DMesh

    from radia.ffag_topopt import (
        build_ffag_cell_target_family,
        differentiate_recovered_planar_orbit_shape_native,
        recover_ffag_closed_orbit_family_native,
    )
    from radia.isochronous_topopt import MU0
    from radia.topology_optimization import (
        ShapeLinearization,
        assemble_ngsolve_hdiv_linear_form_shape_tangents,
        production_vim_state_shape_jacobian_streaming,
        sample_production_gettrafo_displacements,
        solve_shape_lp,
    )
    from radia.vim._field_batch import _create_field_evaluator
    from radia.vim._vim import _charge_basis, build_charge_gram

    ng.SetNumThreads(args.threads)
    started = time.perf_counter()
    mesh = MakeStructured3DMesh(
        hexes=False, nx=args.nx, ny=args.ny, nz=args.nz,
        mapping=lambda x, y, z: (
            -0.15+1.40*x, -4.55+0.90*y, 0.10+0.30*z))
    fes = ng.HDiv(mesh, order=1)
    mode_space = ng.VectorH1(mesh, order=1)
    xi = (ng.x+0.15)/1.40
    yi = (ng.y+4.55)/0.90
    zi = (ng.z-0.10)/0.30
    transverse = (4.0*yi*(1.0-yi))*(1.0-zi)
    modes = []
    for profile in (
            (256.0/27.0)*xi*(1.0-xi)**3,
            (256.0/27.0)*xi**3*(1.0-xi)):
        mode = ng.GridFunction(mode_space)
        mode.Set(ng.CF((0.0, 0.0, -transverse*profile)))
        modes.append(mode)
    deformation = ng.GridFunction(mode_space)
    applied = ng.CF((0.0, 0.0, args.source_h_a_per_m))
    inv_chi = 1.0/(args.mu_r-1.0)
    target_family = build_ffag_cell_target_family(
        args.energies, n_segments=args.segments,
        transfer_matrix_band=1.0, bend_field_band=1.0,
        response_entries=RESPONSE_ENTRIES)

    class TotalField:
        def __init__(self, evaluator):
            self.evaluator = evaluator

        def b_field(self, points):
            raw = np.asarray(points, dtype=float)
            single = raw.shape == (3,)
            packed = np.ascontiguousarray(raw.reshape(-1, 3))
            demag = np.asarray(
                self.evaluator.field(packed, "direct"), dtype=float
            )/(4.0*np.pi)
            result = MU0*(
                demag + np.array([0.0, 0.0, args.source_h_a_per_m]))
            return result[0] if single else result

    def set_deformation(parameters):
        deformation.vec.data = 0.0*deformation.vec
        for value, mode in zip(parameters, modes):
            deformation.vec.data += float(value)*mode.vec
        mesh.SetDeformation(deformation)

    solve_records = []

    def solve_state(parameters):
        call_started = time.perf_counter()
        set_deformation(parameters)
        try:
            with ng.TaskManager():
                charge_map, gram, _ = build_charge_gram(
                    fes, eps=args.hmatrix_eps,
                    leafsize=args.leaf_size, eta=args.hmatrix_eta,
                    image_masks=[4], image_signs=[-1.0])
                rhs, _ = assemble_ngsolve_hdiv_linear_form_shape_tangents(
                    fes, applied, (), bonus_intorder=args.integration_order)
                solved = gram.solve_configured_linear_material_auto_prec_many(
                    inv_chi, np.ascontiguousarray(rhs[None, :]),
                    tol=args.solve_tolerance,
                    maxit=args.solve_max_iterations, mass_riesz=True)
                state = np.asarray(solved["m"], dtype=float)[0]
                evaluator, evaluator_stats = _create_field_evaluator(
                    gram, state, 1)
            record = {
                "parameters_m": np.asarray(parameters, dtype=float).tolist(),
                "wall_s": time.perf_counter()-call_started,
                "iterations": int(solved["iters"][0]),
            }
            solve_records.append(record)
            return {
                "q": np.asarray(parameters, dtype=float).copy(),
                "charge_map": charge_map,
                "gram": gram,
                "rhs": np.asarray(rhs, dtype=float),
                "state": state,
                "iterations": int(solved["iters"][0]),
                "field": TotalField(evaluator),
                "evaluator": evaluator,
                "evaluator_stats": evaluator_stats,
            }
        finally:
            mesh.UnsetDeformation()

    recovery_records = []

    def recover(package, seeds=None):
        call_started = time.perf_counter()
        recovered = recover_ffag_closed_orbit_family_native(
            package["field"], target_family,
            iron_evaluator=package["evaluator"],
            iron_scale=MU0/(4.0*np.pi), iron_algorithm="direct",
            constant_field_t=(0.0, 0.0, MU0*args.source_h_a_per_m),
            initial_references=seeds, n_segments=args.segments,
            gradient_offset=args.gradient_offset,
            tracking_step_m=args.tracking_step,
            position_tolerance=args.position_tolerance,
            tangent_tolerance=args.tangent_tolerance,
            root_max_evaluations=args.root_max_evaluations,
            response_entries=RESPONSE_ENTRIES)
        recovery_records.append({
            "parameters_m": package["q"].tolist(),
            "wall_s": time.perf_counter()-call_started,
            "root_track_counts": [
                int(item.root_evaluations) for item in recovered],
            "position_closure_m": [
                float(item.periodic_position_residual_m)
                for item in recovered],
            "tangent_closure": [
                float(item.periodic_tangent_residual)
                for item in recovered],
        })
        return recovered

    def map_vector(recovered):
        return np.concatenate([
            item.transfer.response for item in recovered])

    linearization_records = []

    def linearize(package, recovered, target_vector, response_band):
        call_started = time.perf_counter()
        set_deformation(package["q"])
        try:
            with ng.TaskManager():
                basis = _charge_basis(fes, 3, materialize_mass=False)
                _, rhs_jacobian = (
                    assemble_ngsolve_hdiv_linear_form_shape_tangents(
                        fes, applied, modes,
                        bonus_intorder=args.integration_order))
                state_shape = production_vim_state_shape_jacobian_streaming(
                    fes=fes, deformation_modes=modes, charge_basis=basis,
                    charge_gram=package["gram"],
                    charge_map=package["charge_map"], inv_chi=inv_chi,
                    rhs=package["rhs"], rhs_jacobian=rhs_jacobian,
                    family="tet", solve_tolerance=args.solve_tolerance,
                    solve_max_iterations=args.solve_max_iterations,
                    mass_riesz=True, derivative_eps=args.hmatrix_eps,
                    derivative_leaf=args.leaf_size,
                    derivative_eta=args.hmatrix_eta,
                    state=package["state"],
                    state_iterations=package["iterations"])
                geometry = sample_production_gettrafo_displacements(
                    fes, modes, basis, family="tet")
                cells = np.ascontiguousarray(
                    np.stack(geometry.cell, axis=1))
                faces = np.ascontiguousarray(
                    np.stack(geometry.face, axis=1))
        finally:
            mesh.UnsetDeformation()
        differentiated = tuple(
            differentiate_recovered_planar_orbit_shape_native(
                item, charge_gram=package["gram"],
                state=package["state"],
                state_jacobian=state_shape.state_jacobian,
                cell_vertex_velocity=cells,
                face_vertex_velocity=faces,
                iron_evaluator=package["evaluator"],
                iron_scale=MU0/(4.0*np.pi),
                constant_field_t=(
                    0.0, 0.0, MU0*args.source_h_a_per_m),
                cell_angle_rad=target_family.spec.cell_bend_angle_rad,
                gradient_offset=args.gradient_offset,
                tracking_step_m=args.tracking_step,
                integration_stations=args.variational_stations,
                curvature_sign=1.0,
                response_entries=RESPONSE_ENTRIES)
            for item in recovered)
        response = map_vector(recovered)
        jacobian = np.vstack([
            item.transfer.response_jacobian for item in differentiated])
        parity = float(max(
            np.max(np.abs(item.field_response-reference.field_response))
            for item, reference in zip(differentiated, recovered)))
        normalized = (response-target_vector)/response_band
        objective_gradient = (
            jacobian.T@((response-target_vector)/response_band**2))
        result = ShapeLinearization(
            0.5*float(normalized@normalized), objective_gradient,
            response, jacobian, target_vector, response_band)
        linearization_records.append({
            "parameters_m": package["q"].tolist(),
            "wall_s": time.perf_counter()-call_started,
            "state_tangent_iterations": list(
                state_shape.tangent_iterations),
            "state_tangent_timings_s": state_shape.timings_s,
            "field_response_parity_max_abs": parity,
            "entrance_parameter_jacobians": [
                item.entrance_parameter_jacobian.tolist()
                for item in differentiated],
            "path_length_jacobians": [
                item.path_length_jacobian.tolist()
                for item in differentiated],
        })
        return result, differentiated, parity

    target_parameters = 1.0e-3*np.asarray(
        args.target_amplitude_mm, dtype=float)
    target_package = solve_state(target_parameters)
    target_recovered = recover(target_package)
    target_vector = map_vector(target_recovered)
    target_maps = np.asarray([
        item.transfer.matrix for item in target_recovered])
    target_done = time.perf_counter()

    parameters = np.zeros(2)
    current_package = solve_state(parameters)
    current_recovered = recover(current_package)
    base_vector = map_vector(current_recovered)
    manufactured_change = target_vector-base_vector
    response_band = np.maximum(
        args.response_relative_band*np.abs(manufactured_change),
        args.response_band_floor)
    current_ratio = float(np.max(np.abs(
        (base_vector-target_vector)/response_band)))
    initial_ratio = current_ratio
    base_done = time.perf_counter()

    history = []
    parity_errors = []
    converged = current_ratio <= 1.0
    for iteration in range(args.max_iterations):
        if converged:
            break
        analytic, differentiated, parity = linearize(
            current_package, current_recovered,
            target_vector, response_band)
        parity_errors.append(parity)
        update = solve_shape_lp(
            parameters, analytic,
            move_limit=np.full(2, args.move_limit_mm*1.0e-3),
            parameter_bounds=(
                np.full(2, args.parameter_min_mm*1.0e-3),
                np.full(2, args.parameter_max_mm*1.0e-3)))
        entry = {
            "iteration": iteration,
            "parameters_before_m": parameters.tolist(),
            "exact_max_band_ratio_before": current_ratio,
            "lp_delta_m": update.delta.tolist(),
            "lp_predicted_max_band_ratio": (
                update.predicted_max_band_ratio),
            "lp_status": update.status,
            "accepted": False,
        }
        for trial in range(args.backtracking_trials):
            factor = 0.5**trial
            candidate_parameters = parameters+factor*update.delta
            candidate_package = solve_state(candidate_parameters)
            try:
                candidate_recovered = recover(
                    candidate_package, current_recovered)
            except RuntimeError as exc:
                entry.setdefault("trials", []).append({
                    "factor": factor, "accepted": False,
                    "reason": "orbit recovery failed: " + str(exc)})
                continue
            candidate_vector = map_vector(candidate_recovered)
            candidate_ratio = float(np.max(np.abs(
                (candidate_vector-target_vector)/response_band)))
            accepted = bool(
                candidate_ratio < current_ratio-args.ratio_tolerance
                or candidate_ratio <= 1.0)
            entry.setdefault("trials", []).append({
                "factor": factor,
                "parameters_m": candidate_parameters.tolist(),
                "exact_max_band_ratio": candidate_ratio,
                "accepted": accepted,
            })
            if accepted:
                parameters = candidate_parameters
                current_package = candidate_package
                current_recovered = candidate_recovered
                current_ratio = candidate_ratio
                entry.update({
                    "accepted": True,
                    "accepted_factor": factor,
                    "parameters_after_m": parameters.tolist(),
                    "exact_max_band_ratio_after": current_ratio,
                })
                break
        history.append(entry)
        if not entry["accepted"]:
            break
        converged = current_ratio <= 1.0
    inverse_done = time.perf_counter()

    final_package = solve_state(parameters)
    final_recovered = recover(final_package, current_recovered)
    final_vector = map_vector(final_recovered)
    final_ratio = float(np.max(np.abs(
        (final_vector-target_vector)/response_band)))
    final_maps = np.asarray([
        item.transfer.matrix for item in final_recovered])
    parameter_relative_error = float(
        np.linalg.norm(parameters-target_parameters)
        / np.linalg.norm(target_parameters))
    maximum_position_closure = float(max(
        item.periodic_position_residual_m for item in final_recovered))
    maximum_tangent_closure = float(max(
        item.periodic_tangent_residual for item in final_recovered))
    finished = time.perf_counter()

    ratios = [initial_ratio] + [
        item["exact_max_band_ratio_after"]
        for item in history if item["accepted"]]
    gates = {
        "bdm1_tet_shape_lane": bool(
            fes.globalorder == 1
            and all(len(element.vertices) == 4
                    for element in mesh.Elements(ng.VOL))),
        "fixed_topology_and_no_air_volume_mesh": bool(
            mesh.ne == 6*args.nx*args.ny*args.nz),
        "manufactured_map_change_is_nontrivial": bool(
            np.max(np.abs(manufactured_change))
            >= args.minimum_manufactured_change),
        "analytic_field_rows_match_recovered_samples": bool(
            parity_errors
            and max(parity_errors) <= args.field_parity_tolerance),
        "every_accepted_exact_ratio_is_monotone": bool(
            all(right < left-args.ratio_tolerance or right <= 1.0
                for left, right in zip(ratios, ratios[1:]))),
        "reclosed_shape_lp_enters_all_transfer_bands": bool(
            converged and final_ratio <= 1.0),
        "manufactured_two_mode_amplitude_is_recovered": bool(
            parameter_relative_error <= args.parameter_relative_tolerance),
        "final_orbits_reclose": bool(
            maximum_position_closure <= args.position_tolerance
            and maximum_tangent_closure <= args.tangent_tolerance),
        "optimizer_finite_difference_not_used": True,
    }
    report = {
        "schema": "radia.ffag-hdiv-mmm-reclosed-gettrafo-map/v1",
        "status": "pass" if all(gates.values()) else "fail",
        "scope": (
            "Manufactured two-mode BDM1-TET entrance/exit pole-face shape "
            "inverse with native full-field periodic-orbit recovery and "
            "analytic implicit orbit/map derivative; not an engineering "
            "magnet design or a HEX shape-derivative claim."),
        "validation_class": args.validation_class,
        "machine": platform.node(),
        "python": platform.python_version(),
        "mesh": {
            "element_family": "TET",
            "hdiv_family": "BDM1",
            "air_volume_elements": 0,
            "elements": int(mesh.ne),
            "dofs": int(fes.ndof),
            "topology_changed": False,
        },
        "manufactured_target": {
            "target_parameters_m": target_parameters.tolist(),
            "recovered_parameters_m": parameters.tolist(),
            "parameter_relative_error": parameter_relative_error,
            "maximum_design_response_change": float(
                np.max(np.abs(manufactured_change))),
            "target_transfer_matrices": target_maps.tolist(),
            "final_transfer_matrices": final_maps.tolist(),
            "initial_exact_max_band_ratio": initial_ratio,
            "final_exact_max_band_ratio": final_ratio,
        },
        "physics": {
            "energies_mev": [float(value) for value in args.energies],
            "segments_per_orbit": args.segments,
            "source_h_a_per_m": args.source_h_a_per_m,
            "mu_r": args.mu_r,
            "gradient_offset_m": args.gradient_offset,
        },
        "inverse": {
            "method": "relinearized Chebyshev shape LP with exact candidate gate",
            "derivative": (
                "matrix-free analytic dM+dB+dG+drhs state tangent, exact "
                "flat-TET dC, analytic field spatial Jacobian, Lorentz "
                "variational equation, implicit orbit closure, moving "
                "observations, and segment-length Frechet AD"),
            "optimizer_finite_difference_used": False,
            "orbit_root_numerical_difference_only": True,
            "shape_jacobian_orbit_treatment": (
                "analytic implicit derivative of the reclosed orbit"),
            "history": history,
            "response_relative_band": args.response_relative_band,
            "response_band_floor": args.response_band_floor,
            "maximum_field_response_parity_error": (
                None if not parity_errors else max(parity_errors)),
        },
        "closure": {
            "maximum_position_residual_m": maximum_position_closure,
            "maximum_tangent_residual": maximum_tangent_closure,
        },
        "timings_s": {
            "manufactured_target": target_done-started,
            "base": base_done-target_done,
            "analytic_shape_lp_and_candidate_gates": inverse_done-base_done,
            "fresh_final_verification": finished-inverse_done,
            "total": finished-started,
            "state_solves": solve_records,
            "orbit_recoveries": recovery_records,
            "analytic_linearizations": linearization_records,
        },
        "peak_working_set_bytes": _peak_working_set_bytes(),
        "gates": gates,
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2)+"\n", encoding="utf-8")
    return report


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--energies", type=float, nargs="+",
                        default=[139.0, 140.0])
    parser.add_argument("--nx", type=int, default=4)
    parser.add_argument("--ny", type=int, default=3)
    parser.add_argument("--nz", type=int, default=1)
    parser.add_argument("--segments", type=int, default=16)
    parser.add_argument("--threads", type=int, default=8)
    parser.add_argument("--source-h-a-per-m", type=float,
                        default=188775.01919094552)
    parser.add_argument("--mu-r", type=float, default=1000.0)
    parser.add_argument("--gradient-offset", type=float, default=0.015)
    parser.add_argument("--target-amplitude-mm", type=float, nargs=2,
                        default=[3.0, -2.0])
    parser.add_argument("--move-limit-mm", type=float, default=4.0)
    parser.add_argument("--parameter-min-mm", type=float, default=-10.0)
    parser.add_argument("--parameter-max-mm", type=float, default=10.0)
    parser.add_argument("--parameter-relative-tolerance", type=float,
                        default=0.08)
    parser.add_argument("--response-relative-band", type=float, default=0.05)
    parser.add_argument("--response-band-floor", type=float, default=1.0e-7)
    parser.add_argument("--minimum-manufactured-change", type=float,
                        default=1.0e-4)
    parser.add_argument("--field-parity-tolerance", type=float,
                        default=2.0e-10)
    parser.add_argument("--max-iterations", type=int, default=8)
    parser.add_argument("--backtracking-trials", type=int, default=6)
    parser.add_argument("--ratio-tolerance", type=float, default=1.0e-8)
    parser.add_argument("--tracking-step", type=float, default=0.01)
    parser.add_argument("--variational-stations", type=int, default=257)
    parser.add_argument("--position-tolerance", type=float, default=1.0e-7)
    parser.add_argument("--tangent-tolerance", type=float, default=1.0e-7)
    parser.add_argument("--root-max-evaluations", type=int, default=10)
    parser.add_argument("--hmatrix-eps", type=float, default=1.0e-7)
    parser.add_argument("--leaf-size", type=int, default=64)
    parser.add_argument("--hmatrix-eta", type=float, default=2.0)
    parser.add_argument("--integration-order", type=int, default=4)
    parser.add_argument("--solve-tolerance", type=float, default=1.0e-10)
    parser.add_argument("--solve-max-iterations", type=int, default=5000)
    parser.add_argument("--validation-class", default="compute-host validation")
    args = parser.parse_args(argv)
    if (len(args.energies) != 2 or args.segments < 8
            or (args.variational_stations-1) % args.segments != 0
            or args.max_iterations < 1 or args.backtracking_trials < 1):
        parser.error("invalid two-mode reclosed-orbit validation settings")
    return args


if __name__ == "__main__":
    parsed = parse_args()
    result = run(parsed)
    print(json.dumps({
        "status": result["status"],
        "final_exact_max_band_ratio": result[
            "manufactured_target"]["final_exact_max_band_ratio"],
        "recovered_parameters_m": result[
            "manufactured_target"]["recovered_parameters_m"],
        "total_s": result["timings_s"]["total"],
    }, indent=2))
    raise SystemExit(0 if result["status"] == "pass" else 1)
