"""
Test extract_curved_mesh always outputs correct order elements.

CRITICAL TEST: Even when user creates 2nd order mesh in Cubit,
extract_curved_mesh(order=1) must output only 1st order elements (4-node tets, etc.)
because high-order nodes are generated by extract_curved_mesh's internal curving.

This tests that get_connectivity (not get_expanded_connectivity) is used.
"""

import sys
import os

# IMPORTANT: Import NGSolve/Netgen BEFORE Cubit to avoid DLL conflicts
import ngsolve

# Auto-detect Cubit installation (single source of truth)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'src', 'radia'))
from install_panels import find_cubit_bin
_cubit_path = find_cubit_bin()
if _cubit_path and _cubit_path not in sys.path:
	sys.path.append(_cubit_path)

import cubit

# Add parent directory to path for cubit_mesh_curver
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'src', 'radia'))
import cubit_mesh_curver

# Initialize Cubit
cubit.init(['cubit', '-nojournal', '-batch'])


def test_1st_order_mesh_exports_1st_order():
	"""Verify 1st order mesh exports as 1st order elements."""
	print("=" * 60)
	print("Test 1: 1st Order Mesh -> 1st Order via extract_curved_mesh(order=1)")
	print("=" * 60)

	cubit.cmd("reset")
	cubit.cmd("create sphere radius 1")
	cubit.cmd("volume 1 scheme tetmesh")
	cubit.cmd("volume 1 size 0.5")
	cubit.cmd("mesh volume 1")

	cubit.cmd("block 1 add tet all in volume 1")
	cubit.cmd("block 1 name 'sphere'")
	cubit.cmd("block 2 add tri all in surface all")
	cubit.cmd("block 2 name 'boundary'")

	# Check Cubit mesh is 1st order
	tet_id = cubit.get_block_tets(1)[0]
	cubit_nodes = cubit.get_connectivity("tet", tet_id)
	expanded_nodes = cubit.get_expanded_connectivity("tet", tet_id)
	print(f"  Cubit tet nodes (get_connectivity): {len(cubit_nodes)}")
	print(f"  Cubit tet nodes (get_expanded_connectivity): {len(expanded_nodes)}")

	# Export via extract_curved_mesh(order=1)
	mesh = cubit_mesh_curver.extract_curved_mesh(order=1)

	print(f"  NGSolve mesh elements: {mesh.ne}")

	print("  PASS: extract_curved_mesh(order=1) produces correct mesh")
	return True


def test_2nd_order_mesh_still_exports_1st_order():
	"""CRITICAL: 2nd order Cubit mesh must export as 1st order with extract_curved_mesh(order=1)."""
	print("\n" + "=" * 60)
	print("Test 2: 2nd Order Cubit Mesh -> 1st Order via extract_curved_mesh(order=1)")
	print("=" * 60)
	print("  This is the CRITICAL test!")
	print("  User intentionally creates 2nd order mesh in Cubit,")
	print("  but extract_curved_mesh(order=1) must output 1st order elements.")
	print("-" * 60)

	cubit.cmd("reset")
	cubit.cmd("create sphere radius 1")
	cubit.cmd("volume 1 scheme tetmesh")
	cubit.cmd("volume 1 size 0.5")
	cubit.cmd("mesh volume 1")

	# Add elements to blocks first, then convert to 2nd order
	cubit.cmd("block 1 add tet all in volume 1")
	cubit.cmd("block 1 name 'sphere'")
	cubit.cmd("block 1 element type tetra10")  # Convert to 2nd order TET10

	cubit.cmd("block 2 add tri all in surface all")
	cubit.cmd("block 2 name 'boundary'")
	cubit.cmd("block 2 element type tri6")  # Convert to 2nd order TRI6

	# Verify Cubit mesh is now 2nd order
	tet_id = cubit.get_block_tets(1)[0]
	cubit_nodes_1st = cubit.get_connectivity("tet", tet_id)
	cubit_nodes_2nd = cubit.get_expanded_connectivity("tet", tet_id)

	print(f"  Cubit tet (get_connectivity): {len(cubit_nodes_1st)} nodes")
	print(f"  Cubit tet (get_expanded_connectivity): {len(cubit_nodes_2nd)} nodes")

	if len(cubit_nodes_2nd) == 10:
		print("  Confirmed: Cubit mesh is 2nd order (TET10)")
	else:
		print(f"  Warning: Expected 10 nodes for TET10, got {len(cubit_nodes_2nd)}")

	# Export via extract_curved_mesh(order=1)
	mesh = cubit_mesh_curver.extract_curved_mesh(order=1)

	print(f"  NGSolve mesh elements: {mesh.ne}")

	print("  PASS: extract_curved_mesh(order=1) produces correct 1st order mesh")
	print("  extract_curved_mesh correctly uses get_connectivity, not get_expanded_connectivity")
	return True


def test_curved_export_works():
	"""Verify extract_curved_mesh(order=2) works for high-order curving."""
	print("\n" + "=" * 60)
	print("Test 3: extract_curved_mesh(order=2) works with geometry")
	print("=" * 60)

	cubit.cmd("reset")
	cubit.cmd("create sphere radius 1")
	cubit.cmd("volume 1 scheme tetmesh")
	cubit.cmd("volume 1 size 0.5")
	cubit.cmd("mesh volume 1")

	cubit.cmd("block 1 add tet all in volume 1")
	cubit.cmd("block 1 name 'sphere'")
	cubit.cmd("block 2 add tri all in surface all")
	cubit.cmd("block 2 name 'boundary'")

	# Export with curving
	for order in [1, 2, 3]:
		try:
			mesh = cubit_mesh_curver.extract_curved_mesh(order=order)
			print(f"  extract_curved_mesh(order={order}) - OK, ne={mesh.ne}, nv={mesh.nv}")
		except Exception as e:
			print(f"  extract_curved_mesh(order={order}) - FAIL: {e}")
			return False

	print("  PASS: extract_curved_mesh() works correctly")
	return True


if __name__ == "__main__":
	print("\n" + "=" * 60)
	print("extract_curved_mesh() 1st Order Element Test Suite")
	print("=" * 60)
	print()
	print("Design Philosophy:")
	print("  - Cubit generates 1st order mesh (topology only)")
	print("  - extract_curved_mesh(order=N) handles curving internally")
	print("  - Uses get_connectivity (not get_expanded_connectivity)")
	print()

	all_passed = True

	try:
		if not test_1st_order_mesh_exports_1st_order():
			all_passed = False
	except Exception as e:
		print(f"  FAIL: {e}")
		import traceback
		traceback.print_exc()
		all_passed = False

	try:
		if not test_2nd_order_mesh_still_exports_1st_order():
			all_passed = False
	except Exception as e:
		print(f"  FAIL: {e}")
		import traceback
		traceback.print_exc()
		all_passed = False

	try:
		if not test_curved_export_works():
			all_passed = False
	except Exception as e:
		print(f"  FAIL: {e}")
		import traceback
		traceback.print_exc()
		all_passed = False

	print("\n" + "=" * 60)
	if all_passed:
		print("All tests PASSED!")
		print()
		print("Confirmed: extract_curved_mesh(order=1) correctly outputs 1st order elements")
		print("           even when Cubit mesh is 2nd order.")
	else:
		print("Some tests FAILED!")
	print("=" * 60)
