function torque_Nm = integrateLorentzTorque( ...
    currentDensity_A_per_m2, magneticFluxDensity_T, volumeWeights_m3, ...
    samplePoints_m, pivot_m)
%INTEGRATELORENTZTORQUE Integrate static Lorentz torque about a pivot.

if nargin < 5
    pivot_m = [];
end
[~, torque_Nm] = radia.force.integrateLorentzForceTorque( ...
    currentDensity_A_per_m2, magneticFluxDensity_T, volumeWeights_m3, ...
    samplePoints_m, pivot_m);
end
