function tests = test_native_ih_sfun_integration
%TEST_NATIVE_IH_SFUN_INTEGRATION Exercise the native Eddy -> Thermal path.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
if bdIsLoaded("radia_simulink_library")
    close_system("radia_simulink_library",0);
end
clear radia_ih_eddy_sfun radia_ih_thermal_sfun
testCase.TestData.FileGenConfig = Simulink.fileGenControl("getConfig");
testCase.TestData.FileGenRoot = string(tempname("C:\temp"));
Simulink.fileGenControl("set", ...
    CacheFolder=fullfile(testCase.TestData.FileGenRoot,"cache"), ...
    CodeGenFolder=fullfile(testCase.TestData.FileGenRoot,"codegen"), ...
    createDir=true);
end

function teardownOnce(testCase)
Simulink.fileGenControl("setConfig", ...
    config=testCase.TestData.FileGenConfig);
if isfolder(testCase.TestData.FileGenRoot)
    rmdir(testCase.TestData.FileGenRoot,"s");
end
end

function testHeatRaisesTemperature(testCase)
out1 = runNativeIH(1.0);
out2 = runNativeIH(2.0);
verifyGreaterThan(testCase,out1.temperature_K(end),293.15);
verifyEqual(testCase,out2.heat_density_W_per_m3(end), ...
    4*out1.heat_density_W_per_m3(end),"RelTol",1e-10);
verifyGreaterThan(testCase,out2.temperature_K(end),out1.temperature_K(end));
end

function out = runNativeIH(current)
model = "radia_native_ih_" + erase(string(java.util.UUID.randomUUID),"-");
cfg = struct("n_eddy_unknown",1,"n_heat",1,"n_temperature",1, ...
    "bh_mode",'linear', ...
    "eddy_matrix_real",1,"eddy_matrix_imag",0, ...
    "eddy_rhs_real",1,"eddy_rhs_imag",0,"heat_projection",1, ...
    "heat_cell_weights",1, ...
    "heat_to_temperature_projection",1, ...
    "mass_row_ptr",[0;1],"mass_col",0,"mass_value",1, ...
    "stiffness_row_ptr",[0;1],"stiffness_col",0,"stiffness_value",0, ...
    "temperature_cell_weights",1,"initial_temperature_K",293.15, ...
    "rotation_mode",'periodic-uniform',"angle_origin_rad",0, ...
    "sample_time_s",0.1,"thermal_tolerance",1e-12, ...
    "thermal_max_iterations",100);
assignin("base","radia_native_ih_config",cfg);
new_system(model); cleanup=onCleanup(@() closeIfLoaded(model));
add_block("simulink/Sources/Constant",model+"/I","Value",num2str(current),"Position",[20 35 70 65]);
add_block("simulink/Sources/Constant",model+"/angle","Value","0","Position",[20 95 70 125]);
add_block("simulink/Sources/Constant",model+"/Tamb","Value","293.15","Position",[20 155 70 185]);
add_block("simulink/User-Defined Functions/S-Function",model+"/Eddy", ...
    "FunctionName","radia_ih_eddy_sfun","Parameters","radia_native_ih_config", ...
    "Position",[120 45 240 105]);
add_block("simulink/User-Defined Functions/S-Function",model+"/Thermal", ...
    "FunctionName","radia_ih_thermal_sfun","Parameters","radia_native_ih_config", ...
    "Position",[300 55 430 115]);
add_block("simulink/Sinks/To Workspace",model+"/HeatOut","VariableName","native_heat", ...
    "SaveFormat","Array","Position",[480 35 570 65]);
add_block("simulink/Sinks/To Workspace",model+"/TempOut","VariableName","native_temp", ...
    "SaveFormat","Array","Position",[480 100 570 130]);
add_line(model,"I/1","Eddy/1"); add_line(model,"angle/1","Eddy/2");
add_line(model,"Eddy/1","Thermal/1"); add_line(model,"Tamb/1","Thermal/2"); add_line(model,"angle/1","Thermal/3");
add_line(model,"Thermal/1","Eddy/3");
add_line(model,"Eddy/1","HeatOut/1"); add_line(model,"Thermal/1","TempOut/1");
set_param(model,"StopTime","0.3");
simOut=sim(model,"ReturnWorkspaceOutputs","on");
out.heat_density_W_per_m3=simOut.get("native_heat");
out.temperature_K=simOut.get("native_temp");
end

function testEddyAngleRotatesHeatInWorkpieceCoordinates(testCase)
heatAtOrigin = runEddyAtAngle(0);
heatAtQuarterTurn = runEddyAtAngle(pi/2);
verifyEqual(testCase,heatAtOrigin,[1,2,3,4],"AbsTol",1e-12);
verifyEqual(testCase,heatAtQuarterTurn,[2,3,4,1],"AbsTol",1e-12);
verifyEqual(testCase,sum(heatAtQuarterTurn),sum(heatAtOrigin), ...
    "AbsTol",1e-12);
end

function heat = runEddyAtAngle(angle)
model = "radia_native_ih_eddy_angle_" + ...
    erase(string(java.util.UUID.randomUUID),"-");
n = 4;
cfg = struct("n_eddy_unknown",1,"n_heat",n,"n_temperature",n, ...
    "bh_mode",'linear',"eddy_matrix_real",1,"eddy_matrix_imag",0, ...
    "eddy_rhs_real",1,"eddy_rhs_imag",0, ...
    "heat_projection",(1:n).',"heat_cell_weights",ones(n,1), ...
    "temperature_cell_weights",ones(n,1), ...
    "rotation_mode",'periodic-uniform',"angle_origin_rad",0, ...
    "sample_time_s",0.1);
assignin("base","radia_native_ih_eddy_angle_config",cfg);
new_system(model); cleanup=onCleanup(@() closeIfLoaded(model));
add_block("simulink/Sources/Constant",model+"/I","Value","1");
add_block("simulink/Sources/Constant",model+"/angle", ...
    "Value",compose("%.17g",angle));
add_block("simulink/Sources/Constant",model+"/T", ...
    "Value","293.15*ones(4,1)");
add_block("simulink/User-Defined Functions/S-Function",model+"/Eddy", ...
    "FunctionName","radia_ih_eddy_sfun", ...
    "Parameters","radia_native_ih_eddy_angle_config");
add_block("simulink/Sinks/To Workspace",model+"/HeatOut", ...
    "VariableName","rotated_heat","SaveFormat","Array");
add_line(model,"I/1","Eddy/1"); add_line(model,"angle/1","Eddy/2");
add_line(model,"T/1","Eddy/3"); add_line(model,"Eddy/1","HeatOut/1");
set_param(model,"StopTime","0","SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete","FixedStep","0.1");
simOut=sim(model,"ReturnWorkspaceOutputs","on");
values=simOut.get("rotated_heat");
heat=values(end,:);
end

function testRotationTransportConservesWeightedEnergy(testCase)
model = "radia_native_ih_rotation_" + erase(string(java.util.UUID.randomUUID),"-");
n = 4;
weights = [1;2;1;2];
initial = [300;340;380;420];
cfg = struct("n_eddy_unknown",1,"n_heat",n,"n_temperature",n, ...
    "bh_mode",'linear',"eddy_matrix_real",1,"eddy_matrix_imag",0, ...
    "eddy_rhs_real",1,"eddy_rhs_imag",0,"heat_projection",ones(n,1), ...
    "heat_cell_weights",weights, ...
    "heat_to_temperature_projection",reshape(eye(n).',[],1), ...
    "mass_row_ptr",(0:n).',"mass_col",(0:n-1).',"mass_value",ones(n,1), ...
    "stiffness_row_ptr",(0:n).',"stiffness_col",(0:n-1).', ...
    "stiffness_value",zeros(n,1),"temperature_cell_weights",weights, ...
    "initial_temperature_K",initial,"sample_time_s",0.1, ...
    "rotation_mode",'periodic-uniform',"angle_origin_rad",0, ...
    "thermal_tolerance",1e-12,"thermal_max_iterations",100);
assignin("base","radia_native_ih_rotation_config",cfg);
new_system(model); cleanup=onCleanup(@() closeIfLoaded(model));
add_block("simulink/Sources/Constant",model+"/I","Value","0");
add_block("simulink/Sources/Constant",model+"/angle","Value","pi/2");
add_block("simulink/Sources/Constant",model+"/Tamb","Value","293.15");
add_block("simulink/User-Defined Functions/S-Function",model+"/Eddy", ...
    "FunctionName","radia_ih_eddy_sfun","Parameters", ...
    "radia_native_ih_rotation_config");
add_block("simulink/User-Defined Functions/S-Function",model+"/Thermal", ...
    "FunctionName","radia_ih_thermal_sfun","Parameters", ...
    "radia_native_ih_rotation_config");
add_block("simulink/Sinks/To Workspace",model+"/TempOut", ...
    "VariableName","rotation_temp","SaveFormat","Array");
add_line(model,"I/1","Eddy/1"); add_line(model,"angle/1","Eddy/2");
add_line(model,"Eddy/1","Thermal/1"); add_line(model,"Tamb/1","Thermal/2");
add_line(model,"angle/1","Thermal/3"); add_line(model,"Thermal/1","Eddy/3");
add_line(model,"Thermal/1","TempOut/1");
set_param(model,"StopTime","0.1","SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete","FixedStep","0.1");
simOut=sim(model,"ReturnWorkspaceOutputs","on");
temperature=simOut.get("rotation_temp");
verifyEqual(testCase,weights.'*temperature(end,:).',weights.'*initial, ...
    "AbsTol",1e-10);
verifyNotEqual(testCase,temperature(end,:),initial.');
end

function closeIfLoaded(name)
if bdIsLoaded(name), close_system(name,0); end
end
