function artifact = run_team28_coilbuilder_dynamic_simulink(options)
%RUN_TEAM28COILBUILDERDYNAMICSIMULINK Validate the moving TEAM 28 model.
%   The 50 Hz CoilBuilder/HCurl eddy-bubble height family supplies a
%   cycle-averaged lift law. Simulink integrates the slower vertical disk
%   motion with gravity and an explicit configurable viscous damping term.

arguments
    options.ModelFile (1,1) string = ""
    options.ResultFile (1,1) string = ""
    options.PlotFile (1,1) string = ""
    options.DampingRatio (1,1) double {mustBeNonnegative} = 0.35
    options.InitialHeightOffset_m (1,1) double {mustBeFinite} = -7.0e-3
    options.SampleTime_s (1,1) double {mustBePositive} = 1.0e-3
    options.StopTime_s (1,1) double {mustBePositive} = 2.0
    options.ShowFigure (1,1) logical = false
end

totalTimer = tic;
here = string(fileparts(mfilename("fullpath")));
repoRoot = string(fileparts(fileparts(here)));
matlabRoot = fullfile(repoRoot, "matlab");
if ~contains(path, matlabRoot)
    addpath(matlabRoot);
end
if strlength(options.ModelFile) == 0
    options.ModelFile = fullfile(matlabRoot, ...
        "radia_team28_coilbuilder_dynamic.slx");
end
if strlength(options.ResultFile) == 0
    options.ResultFile = fullfile(here, ...
        "team28_coilbuilder_dynamic_simulink_results.json");
end
if strlength(options.PlotFile) == 0
    options.PlotFile = fullfile(here, ...
        "team28_coilbuilder_dynamic_simulink.png");
end
if ~isfile(options.ModelFile)
    error("radia:validation:TEAM28Model", ...
        "Simulink model does not exist: %s", options.ModelFile);
end

loadTimer = tic;
lut = radia.simulink.makeTeam28CoilBuilderLUT( ...
    SampleTime_s=options.SampleTime_s);
plant = radia.simulink.makeTeam28CoilBuilderPlant(lut, ...
    DampingRatio=options.DampingRatio, ...
    InitialHeightOffset_m=options.InitialHeightOffset_m, ...
    SampleTime_s=options.SampleTime_s, StopTime_s=options.StopTime_s);
[~, modelName] = fileparts(options.ModelFile);
load_system(options.ModelFile);
cleanupModel = onCleanup(@() closeLoadedModel(modelName));
workspace = get_param(modelName, "ModelWorkspace");
assignin(workspace, "radia_team28_coilbuilder_lut", plant.lut);
assignin(workspace, "team28_coil_current_A", ...
    plant.lut.reference_coil_current_A);
assignin(workspace, "team28_disk_weight_N", plant.disk_weight_N);
assignin(workspace, "team28_inverse_mass_per_kg", 1.0 / plant.disk_mass_kg);
assignin(workspace, "team28_damping_Ns_per_m", ...
    plant.viscous_damping_Ns_per_m);
assignin(workspace, "team28_initial_height_offset_m", ...
    plant.initial_height_offset_m);
assignin(workspace, "team28_reference_disk_bottom_m", ...
    plant.reference_disk_bottom_m);
assignin(workspace, "team28_sample_time_s", plant.sample_time_s);
load_s = toc(loadTimer);

simulationTimer = tic;
simulation = Simulink.SimulationInput(modelName);
simulation = simulation.setModelParameter( ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", num2str(plant.sample_time_s, 17), ...
    "StopTime", num2str(plant.stop_time_s, 17), ...
    "SaveOutput", "on", "OutputSaveName", "yout", ...
    "ReturnWorkspaceOutputs", "on");
simulationOutput = sim(simulation);
dataset = simulationOutput.get("yout");
[time_s, heightOffset] = datasetSignal(dataset, 1);
[~, absoluteBottom] = datasetSignal(dataset, 2);
[~, velocity] = datasetSignal(dataset, 3);
[~, lift] = datasetSignal(dataset, 4);
[~, acceleration] = datasetSignal(dataset, 5);
simulation_s = toc(simulationTimer);

verificationTimer = tic;
terminalHeightError = abs(heightOffset(end) - ...
    plant.equilibrium_height_offset_m);
terminalForceResidual = abs(lift(end) - plant.disk_weight_N - ...
    plant.viscous_damping_Ns_per_m * velocity(end));
heightTolerance = 0.1e-3;
forceTolerance = 0.02;
finiteValues = [time_s; heightOffset; absoluteBottom; velocity; lift; acceleration];
gates = struct( ...
    "all_outputs_are_finite", all(isfinite(finiteValues)), ...
    "initial_height_is_preserved", ...
        abs(heightOffset(1) - plant.initial_height_offset_m) < 1e-12, ...
    "trajectory_stays_inside_validated_height_family", ...
        min(heightOffset) >= plant.height_limits_m(1) - 1e-12 && ...
        max(heightOffset) <= plant.height_limits_m(2) + 1e-12, ...
    "terminal_height_within_0p1_mm_of_equilibrium", ...
        terminalHeightError < heightTolerance, ...
    "terminal_force_balance_below_0p02_N", ...
        terminalForceResidual < forceTolerance, ...
    "terminal_speed_below_1_mm_per_s", abs(velocity(end)) < 1e-3, ...
    "coilbuilder_source_validation_is_retained", ...
        plant.lut.source_validation_passed, ...
    "common_rank_three_eddy_basis_is_retained", ...
        plant.lut.family_state_order == 3 && ...
        plant.lut.family_snapshot_count == 25);
pass = all(cell2mat(struct2cell(gates)));
verification_s = toc(verificationTimer);

visualizationTimer = tic;
figureHandle = figure("Visible", onOff(options.ShowFigure), ...
    "Color", "w", "Position", [100, 100, 900, 650]);
layout = tiledlayout(figureHandle, 2, 1, ...
    "TileSpacing", "compact", "Padding", "compact");
heightAxes = nexttile(layout, 1);
plot(heightAxes, time_s, 1e3 * absoluteBottom, ...
    "LineWidth", 1.5, "DisplayName", "Disk bottom");
hold(heightAxes, "on");
yline(heightAxes, 1e3 * plant.equilibrium_absolute_bottom_m, "--", ...
    "Force = weight", "LineWidth", 1.1);
hold(heightAxes, "off");
xlabel(heightAxes, "Time (s)");
ylabel(heightAxes, "Absolute height (mm)");
title(heightAxes, "TEAM 28 moving disk: CoilBuilder + HCurl eddy-bubble");
grid(heightAxes, "on");
legend(heightAxes, "Location", "best");
forceAxes = nexttile(layout, 2);
plot(forceAxes, time_s, lift, "LineWidth", 1.4, ...
    "DisplayName", "Cycle-averaged lift");
hold(forceAxes, "on");
yline(forceAxes, plant.disk_weight_N, "--", "Disk weight", ...
    "LineWidth", 1.1);
hold(forceAxes, "off");
xlabel(forceAxes, "Time (s)");
ylabel(forceAxes, "Force (N)");
grid(forceAxes, "on");
legend(forceAxes, "Location", "best");
exportgraphics(layout, options.PlotFile, "Resolution", 160);
visualization_s = toc(visualizationTimer);
if ~options.ShowFigure
    close(figureHandle);
end

simulinkInfo = ver("simulink");
artifact = struct( ...
    "radia_version", projectVersion(repoRoot), ...
    "schema", "cae-ai-lab.solver-run.v1", ...
    "created_at_utc", utcTimestamp(), ...
    "case", "TEAM 28 dynamic CoilBuilder HCurl eddy-bubble levitation", ...
    "solver", "simulink", ...
    "solver_backend", "fixed-50Hz-cycle-average-lut-plus-mechanical-plant", ...
    "source_artifact", portablePath(options.ModelFile, repoRoot), ...
    "pass", pass, ...
    "run", struct( ...
        "command", "run_team28_coilbuilder_dynamic_simulink", ...
        "workdir", ".", "exit_code", 0, ...
        "duration_s", toc(totalTimer)), ...
    "result_files", [portablePath(options.ResultFile, repoRoot), ...
        portablePath(options.PlotFile, repoRoot), ...
        portablePath(options.ModelFile, repoRoot), ...
        portablePath(plant.lut.source_file, repoRoot)], ...
    "checks", struct( ...
        "ran_to_completion", true, ...
        "result_files_exist", isfile(options.ModelFile) && ...
            isfile(options.PlotFile), ...
        "validation_passed", pass, ...
        "details", gates), ...
    "tolerances", struct( ...
        "terminal_height_abs_m", heightTolerance, ...
        "terminal_force_balance_abs_N", forceTolerance, ...
        "terminal_speed_abs_m_per_s", 1e-3), ...
    "errors", struct( ...
        "terminal_height_abs_m", terminalHeightError, ...
        "terminal_force_balance_abs_N", terminalForceResidual, ...
        "terminal_speed_abs_m_per_s", abs(velocity(end))), ...
    "tool_versions", struct( ...
        "radia", projectVersion(repoRoot), ...
        "matlab", string(version), ...
        "matlab_release", string(version("-release")), ...
        "simulink", string(simulinkInfo.Version)), ...
    "timing_breakdown_s", struct( ...
        "load_and_configure", load_s, ...
        "simulink_execution", simulation_s, ...
        "verification", verification_s, ...
        "visualization_and_write", visualization_s), ...
    "verification", struct( ...
        "method", "validated force-height replay, force-weight equilibrium, " + ...
            "bounded damped trajectory, and terminal balance", ...
        "command", "run_team28_coilbuilder_dynamic_simulink"), ...
    "model_contract", rmfield(plant, "lut"), ...
    "observables", struct( ...
        "sample_count", numel(time_s), ...
        "initial_absolute_bottom_mm", 1e3 * absoluteBottom(1), ...
        "terminal_absolute_bottom_mm", 1e3 * absoluteBottom(end), ...
        "predicted_equilibrium_absolute_bottom_mm", ...
            1e3 * plant.equilibrium_absolute_bottom_m, ...
        "peak_upward_lift_N", max(lift), ...
        "terminal_upward_lift_N", lift(end), ...
        "peak_speed_m_per_s", max(abs(velocity))));

writeTimer = tic;
writeJson(options.ResultFile, artifact);
artifact.timing_breakdown_s.visualization_and_write = ...
    artifact.timing_breakdown_s.visualization_and_write + toc(writeTimer);
artifact.run.duration_s = toc(totalTimer);
writeJson(options.ResultFile, artifact);
if ~artifact.pass
    error("radia:validation:TEAM28Dynamic", ...
        "TEAM 28 dynamic Simulink model failed one or more gates.");
end
clear cleanupModel
closeLoadedModel(modelName);
end

function [time, data] = datasetSignal(dataset, index)
signal = dataset.getElement(index);
time = double(signal.Values.Time(:));
data = double(signal.Values.Data(:));
end

function closeLoadedModel(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end

function value = onOff(enabled)
if enabled
    value = "on";
else
    value = "off";
end
end

function writeJson(fileName, value)
[folder, ~, ~] = fileparts(fileName);
if strlength(folder) > 0 && ~isfolder(folder)
    mkdir(folder);
end
file = fopen(fileName, "w");
if file < 0
    error("radia:validation:TEAM28Write", ...
        "could not open result file: %s", fileName);
end
cleanup = onCleanup(@() fclose(file));
fprintf(file, "%s\n", jsonencode(value, PrettyPrint=true));
clear cleanup
end

function value = projectVersion(repoRoot)
text = fileread(fullfile(repoRoot, "pyproject.toml"));
token = regexp(text, '(?m)^version\s*=\s*"([^"]+)"', "tokens", "once");
if isempty(token)
    value = "unknown";
else
    value = string(token{1});
end
end

function value = utcTimestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end

function pathValue = portablePath(fileName, repoRoot)
pathValue = replace(string(fileName), "\", "/");
root = replace(string(repoRoot), "\", "/") + "/";
if startsWith(lower(pathValue), lower(root))
    pathValue = extractAfter(pathValue, strlength(root));
end
end
