function [sweep, artifact] = validate_team28_coilbuilder_eddy_bubble(options)
%VALIDATE_TEAM28COILBUILDEREDDYBUBBLE Replay the TEAM 28 CLN model in MATLAB.
%   The spatial HCurl eddy-bubble reduction and CoilBuilder source are
%   established by the adjacent Python validation. MATLAB reads that fixed
%   exchange model, solves three coil currents through the native MEX kernel,
%   and returns a table suitable for scripts, optimization, or Simulink.

arguments
    options.ModelFile (1,1) string = ""
    options.PythonResultFile (1,1) string = ""
    options.OutputFile (1,1) string = ""
    options.Currents_A (1,:) double = [10, 20, 30]
end

totalTimer = tic;
here = string(fileparts(mfilename("fullpath")));
repoRoot = string(fileparts(fileparts(here)));
matlabRoot = fullfile(repoRoot, "matlab");
if ~contains(path, matlabRoot)
    addpath(matlabRoot);
end
if strlength(options.ModelFile) == 0
    options.ModelFile = fullfile(here, ...
        "team28_coilbuilder_hcurl_eddy_cln.json");
end
if strlength(options.PythonResultFile) == 0
    options.PythonResultFile = fullfile(here, ...
        "team28_coilbuilder_eddy_bubble_results.json");
end
if strlength(options.OutputFile) == 0
    options.OutputFile = fullfile(here, ...
        "team28_coilbuilder_matlab_results.json");
end
validateattributes(options.Currents_A, {'double'}, ...
    {'row', 'finite', 'positive', 'nonempty'});

loadTimer = tic;
model = radia.simulink.loadHCurlEddyCLNModel(options.ModelFile);
pythonResult = jsondecode(fileread(options.PythonResultFile));
load_s = toc(loadTimer);

solveTimer = tic;
currents = options.Currents_A(:);
nCase = numel(currents);
force = zeros(nCase, 3);
jouleLoss = zeros(nCase, 1);
magneticEnergy = zeros(nCase, 1);
for k = 1:nCase
    coefficients = radia.simulink.solveHCurlEddyCLNHarmonic( ...
        model, double(model.metadata.frequency_hz), currents(k));
    force(k, :) = radia.simulink.evaluateHCurlEddyCLNForce( ...
        model, coefficients, currents(k)).';
    jouleLoss(k) = 0.5 * real(coefficients' * ...
        model.resistance * coefficients);
    magneticEnergy(k) = 0.25 * real(coefficients' * ...
        model.inductance * coefficients);
end
forcePerCurrentSquared = force(:, 3) ./ currents.^2;
sweep = table(currents, force(:, 1), force(:, 2), force(:, 3), ...
    jouleLoss, magneticEnergy, forcePerCurrentSquared, ...
    'VariableNames', {'coil_current_A', 'force_x_N', 'force_y_N', ...
    'upward_force_N', 'joule_loss_W', 'magnetic_energy_J', ...
    'force_per_current_squared_N_per_A2'});
solve_s = toc(solveTimer);

verifyTimer = tic;
referenceCurrent = double(model.metadata.coil_current_reference_A);
referenceIndex = find(abs(currents - referenceCurrent) < 1e-12, 1);
if isempty(referenceIndex)
    error("radia:validation:TEAM28Current", ...
        "Currents_A must include the exchange reference current.");
end
pythonForce = double(pythonResult.details.observables. ...
    reference_current_force_N(:));
matlabForce = force(referenceIndex, :).';
mexVsPythonRelative = norm(matlabForce - pythonForce) / ...
    max(norm(pythonForce), realmin);
targetForce = double(pythonResult.details.observables. ...
    target_upward_force_N);
targetRelative = abs(matlabForce(3) - targetForce) / targetForce;
quadraticSpread = (max(forcePerCurrentSquared) - ...
    min(forcePerCurrentSquared)) / ...
    max(abs(mean(forcePerCurrentSquared)), realmin);
gates = struct( ...
    "three_or_more_current_points", nCase >= 3, ...
    "reference_current_included", ~isempty(referenceIndex), ...
    "mex_matches_python_below_1e_10", mexVsPythonRelative < 1e-10, ...
    "upward_force_matches_reference_below_one_percent", ...
        matlabForce(3) > 0 && targetRelative < 0.01, ...
    "force_scales_with_current_squared", quadraticSpread < 1e-12, ...
    "loss_is_nonnegative", all(jouleLoss >= 0), ...
    "magnetic_energy_is_nonnegative", all(magneticEnergy >= 0));
pass = all(struct2array(gates));
verify_s = toc(verifyTimer);

artifact = struct( ...
    "radia_version", projectVersion(repoRoot), ...
    "schema", "cae-ai-lab.solver-run.v1", ...
    "created_at_utc", utcTimestamp(), ...
    "case", "TEAM 28 CoilBuilder HCurl eddy-bubble MATLAB replay", ...
    "solver", "matlab", ...
    "source_artifact", ...
        "validation_test/maglev/validate_team28_coilbuilder_eddy_bubble.m", ...
    "pass", pass, ...
    "run", struct( ...
        "command", "validate_team28_coilbuilder_eddy_bubble", ...
        "workdir", ".", ...
        "exit_code", 0, ...
        "duration_s", toc(totalTimer)), ...
    "result_files", [ ...
        "validation_test/maglev/team28_coilbuilder_matlab_results.json", ...
        "validation_test/maglev/team28_coilbuilder_hcurl_eddy_cln.json", ...
        "validation_test/maglev/team28_coilbuilder_eddy_bubble_results.json"], ...
    "checks", struct( ...
        "ran_to_completion", true, ...
        "result_files_exist", isfile(options.ModelFile) && ...
            isfile(options.PythonResultFile), ...
        "validation_passed", pass, ...
        "details", gates), ...
    "tolerances", struct( ...
        "mex_vs_python_max_rel", 1e-10, ...
        "force_reference_max_rel", 0.01, ...
        "quadratic_scaling_max_rel", 1e-12), ...
    "errors", struct( ...
        "max_rel", max([mexVsPythonRelative, targetRelative, ...
            quadraticSpread]), ...
        "max_abs", max(abs(matlabForce - pythonForce))), ...
    "tool_versions", struct( ...
        "radia", projectVersion(repoRoot), ...
        "matlab", string(version), ...
        "matlab_release", string(version("-release"))), ...
    "timing_breakdown_s", struct( ...
        "load_exchange_and_python_evidence", load_s, ...
        "mex_harmonic_current_sweep", solve_s, ...
        "cross_language_verification", verify_s, ...
        "write_results", 0.0), ...
    "verification", struct( ...
        "method", "Python/MATLAB CLN parity, stored TEAM force, " + ...
            "passivity observables, and current-squared scaling", ...
        "command", "validate_team28_coilbuilder_eddy_bubble"), ...
    "comparisons", struct( ...
        "mex_vs_python_relative_error", mexVsPythonRelative, ...
        "upward_force_reference_relative_error", targetRelative, ...
        "force_over_current_squared_relative_spread", quadraticSpread), ...
    "current_sweep", table2struct(sweep));

writeTimer = tic;
writeJson(options.OutputFile, artifact);
artifact.timing_breakdown_s.write_results = toc(writeTimer);
artifact.run.duration_s = toc(totalTimer);
writeJson(options.OutputFile, artifact);
if ~artifact.pass
    error("radia:validation:TEAM28CoilBuilder", ...
        "TEAM 28 CoilBuilder MATLAB replay failed one or more gates.");
end
end

function writeJson(fileName, value)
[folder, ~, ~] = fileparts(fileName);
if strlength(folder) > 0 && ~isfolder(folder)
    mkdir(folder);
end
file = fopen(fileName, "w");
if file < 0
    error("radia:validation:TEAM28Write", ...
        "could not open result file: %s", fileName);
end
cleanup = onCleanup(@() fclose(file));
fprintf(file, "%s\n", jsonencode(value, PrettyPrint=true));
clear cleanup
end

function value = projectVersion(repoRoot)
text = fileread(fullfile(repoRoot, "pyproject.toml"));
token = regexp(text, '(?m)^version\s*=\s*"([^"]+)"', "tokens", "once");
if isempty(token)
    value = "unknown";
else
    value = string(token{1});
end
end

function value = utcTimestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end
