"""Phase C.5: BEM-A intree cross-validation against PEEC golden on the
rect-cross-section, multi-loft, united-solid coil
(``tests/panels/golden/rect_torus_lofted_united.step``).

PEEC golden L = 138.16 nH (band [120, 160]).  This is the geometry
that triggered Kubota's 2026-04-28 work-in-progress and led to the
v4.24.0 PEEC Phase C-heavy filament dispatcher (Path 2c
``_filaments_from_section_planes``).  Cross-validating BEM-A here
demonstrates that BEM-A handles the same lofted geometry that PEEC
covers, giving an independent check on the thin-skin inductance.

The BEM-A surface mesh is generated by NGSolve OCC ``Glue(faces)``
+ Netgen meshing with the smallest two faces (8 mm x 6 mm = 4.8e-5 m^2)
labelled as ``source`` / ``sink`` based on their y-centroid (the
gap is at theta = 0..-5 deg, with the source cap at y=0).
"""
from __future__ import annotations

import math
import os
import sys

import numpy as np
import pytest


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
STEP_PATH = os.path.join(ROOT, "tests", "panels", "golden",
                         "rect_torus_lofted_united.step")


def _have_netgen_occ():
    try:
        from netgen.occ import OCCGeometry, Glue  # noqa: F401
        return True
    except Exception:
        return False


def _build_mesh_with_labels(maxh):
    """Load STEP, label cap faces (smallest mass) as source/sink, mesh."""
    from netgen.occ import OCCGeometry, Glue
    from netgen.meshing import MeshingParameters
    from ngsolve import Mesh

    geo = OCCGeometry(STEP_PATH)
    shape = geo.shape
    # The 2 smallest-mass faces are the gap caps (8mm x 6mm = 4.8e-5 m^2);
    # the lofted lateral faces are larger.  Source/sink distinguished by
    # y-centroid: source at theta=0 (y~0), sink at theta=-5 deg (y<0).
    fs_sorted = sorted(enumerate(shape.faces), key=lambda x: x[1].mass)
    ca, fa = fs_sorted[0]
    cb, fb = fs_sorted[1]
    if abs(fa.center[1]) < abs(fb.center[1]):
        fa.name, fb.name = "source", "sink"
    else:
        fa.name, fb.name = "sink", "source"
    for i, f in enumerate(shape.faces):
        if i not in (ca, cb):
            f.name = "body"
    faces = list(shape.faces)

    ngmesh = OCCGeometry(Glue(faces)).GenerateMesh(
        mp=MeshingParameters(maxh=maxh, curvaturesafety=1.0,
                              segmentsperedge=1))
    return Mesh(ngmesh)


def _arrays_from_mesh(mesh):
    from ngsolve import BND
    n_v = mesh.nv
    verts = np.empty((n_v, 3), dtype=np.float64)
    for i in range(n_v):
        verts[i] = [mesh.vertices[i].point[k] for k in range(3)]
    bnd_names = list(mesh.GetBoundaries())
    src_idx = {i for i, n in enumerate(bnd_names) if n == "source"}
    snk_idx = {i for i, n in enumerate(bnd_names) if n == "sink"}
    tris, src_mask, snk_mask = [], [], []
    for el in mesh.Elements(BND):
        tris.append([int(v.nr) for v in el.vertices])
        src_mask.append(el.index in src_idx)
        snk_mask.append(el.index in snk_idx)
    return (verts, np.array(tris, dtype=np.int64),
            np.array(src_mask, dtype=bool),
            np.array(snk_mask, dtype=bool))


@pytest.fixture(scope="module")
def bem_a_result():
    """Run BEM-A intree saddle solve on the rect_torus_lofted STEP at
    a moderate mesh density."""
    if not _have_netgen_occ():
        pytest.skip("netgen.occ not available")
    if not os.path.isfile(STEP_PATH):
        pytest.skip(f"STEP fixture not found: {STEP_PATH}")
    from radia.bem.efie_rwg import solve_inductance_source_sink_intree

    mesh = _build_mesh_with_labels(maxh=0.012)
    verts, tris, src, snk = _arrays_from_mesh(mesh)
    res = solve_inductance_source_sink_intree(
        verts, tris, src, snk,
        regular_quad_degree=5, singular_n_q=6)
    res["mesh_nv"] = mesh.nv
    res["mesh_n_tris"] = len(tris)
    res["mesh_n_src_tris"] = int(src.sum())
    res["mesh_n_snk_tris"] = int(snk.sum())
    return res


@pytest.mark.slow
def test_rect_torus_loft_in_PEEC_band(bem_a_result):
    """BEM-A intree L is in PEEC golden hard band [120, 160] nH.

    PEEC golden: 138.16 nH (Phase C-heavy `_filaments_from_section_planes`).
    BEM-A at maxh=12mm: ~153 nH (caps are coarse: 4 tris each).
    Both methods are approximations of thin-skin geometry; ~10% spread
    reflects mesh + filament-vs-surface modelling differences.
    """
    L_nH = bem_a_result["L"] * 1e9
    assert 120.0 <= L_nH <= 160.0, (
        f"BEM-A L = {L_nH:.2f} nH outside PEEC golden hard band "
        f"[120, 160]")


@pytest.mark.slow
def test_rect_torus_loft_residual_machine_precision(bem_a_result):
    assert bem_a_result["residual"] < 1e-12


@pytest.mark.slow
def test_rect_torus_loft_caps_resolved(bem_a_result):
    """Sanity: source and sink caps each have at least 2 triangles
    (otherwise the saddle-point system might be over-determined or the
    OCC face classifier picked the wrong faces)."""
    assert bem_a_result["mesh_n_src_tris"] >= 2
    assert bem_a_result["mesh_n_snk_tris"] >= 2
    assert bem_a_result["mesh_n_src_tris"] == bem_a_result["mesh_n_snk_tris"], (
        f"asymmetric port mesh: src={bem_a_result['mesh_n_src_tris']}, "
        f"snk={bem_a_result['mesh_n_snk_tris']}")
