function [Ere, Eim, Hre, Him] = equivalenceSourceHarmonic( ...
    centroids, normals, areas, EreSurf, EimSurf, HreSurf, HimSurf, obs, omega, nThreads)
%EQUIVALENCESOURCEHARMONIC Reconstruct harmonic E/H from an equivalent surface.
if nargin < 10, nThreads = 0; end
[Ere, Eim, Hre, Him] = radia.internal.callMex('equivalence.harmonic', ...
    double(centroids), double(normals), double(areas), double(EreSurf), ...
    double(EimSurf), double(HreSurf), double(HimSurf), double(obs), ...
    double(omega), double(nThreads));
end
