function result = evrsTMethod(curlMap, divMap, gradMap, evrsMap, ...
        resistanceCurrent, inductanceCurrent, portCurrent)
%EVRSTMETHOD Build T-method and EVRS reduced matrices in native C++.

result = radia.internal.callMex( ...
    'evrs.tmethod', double(curlMap), double(divMap), double(gradMap), ...
    double(evrsMap), double(resistanceCurrent), double(inductanceCurrent), ...
    double(portCurrent));
end
