function report = quickCheck(options)
%QUICKCHECK Verify that the MATLAB MEX runtime is usable.
%   REPORT = radia.quickCheck() checks setup, the native API, and TaskManager.

arguments
    options.PythonExecutable (1,1) string = "python"
    options.ProbeSize (1,1) double {mustBeInteger, mustBePositive} = 10000
    options.Verbose (1,1) logical = false
end

setupInfo = radia.setup( ...
    PythonExecutable=options.PythonExecutable, Verbose=options.Verbose);
apiInfo = radia.apiInfo();
probe = radia.taskmanagerProbe(options.ProbeSize);
commands = string(radia.commands());
required = ["api.info", "taskmanager.probe", "ngsolve.space_info", ...
    "ngsolve.matrix_dump", ...
    "cln.lanczos", "hacapk.bem.create", "hacapk.peec.create", ...
    "radia.PlanarChargeField", "hlu.get_trunc_tol"];
missing = setdiff(required, commands);

report = struct( ...
    "ready", setupInfo.mex_available && isempty(missing) && ...
        probe.used_threads >= 1 && isfinite(probe.checksum), ...
    "setup", setupInfo, ...
    "api", apiInfo, ...
    "probe", probe, ...
    "command_count", numel(commands), ...
    "missing_commands", missing);
end
