function gram = tetHCurlReducedGram(cellVerts, exponents, coefficients, ...
        nModes, refPoints, refWeights)
%TETHCURLREDUCEDGRAM Assemble the native reduced HCurl Gram on tetrahedra.

gram = radia.internal.callMex( ...
    'hcurl.tet_reduced_gram', double(cellVerts), int32(exponents), ...
    double(coefficients), double(nModes), double(refPoints), ...
    double(refWeights));
end
