function blockPath = addElectromagnetOptimizationSubsystem(parent,name,position)
%ADDELECTROMAGNETOPTIMIZATIONSUBSYSTEM Add analysis and VIM topology lanes.
arguments
    parent (1,1) string
    name (1,1) string = "Electromagnet Topology Optimization"
    position (1,4) double = [45 100 375 220]
end
blockPath = parent + "/" + name;
add_block("simulink/Ports & Subsystems/Subsystem",blockPath, ...
    Position=position);
delete_line(blockPath,"In1/1","Out1/1");
delete_block(blockPath + "/In1");
delete_block(blockPath + "/Out1");

add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/run_analysis",Port="1",OutDataTypeStr="boolean", ...
    Position=[25 55 55 75]);
add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/run_topology",Port="2",OutDataTypeStr="boolean", ...
    Position=[25 205 55 225]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath + "/Electromagnet Analysis", ...
    FunctionName="radia_application_sfun", ...
    Parameters="'em','','C:\temp\radia_simulink',3600,'python'", ...
    Position=[125 35 355 105]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath + "/Density Topology Optimization", ...
    FunctionName="radia_electromagnet_topology_sfun", ...
    Parameters="radia_electromagnet_adjoint_runner,1,96", ...
    Position=[125 165 385 285]);

outputNames = [ ...
    "analysis_status","primary","elapsed_s", ...
    "objective","optimization_status","iterations","density", ...
    "volume_fraction","history_count","history_iteration", ...
    "history_objective","history_constraint"];
for index = 1:numel(outputNames)
    y = 25 + (index-1)*35;
    add_block("simulink/Ports & Subsystems/Out1", ...
        blockPath + "/" + outputNames(index),Port=string(index), ...
        Position=[810 y 840 y+20]);
end

add_block("simulink/Sinks/Scope",blockPath + "/Analysis Monitor", ...
    NumInputPorts="3",Position=[455 30 590 105]);
add_block("simulink/Sinks/Scope",blockPath + "/Optimization Monitor", ...
    NumInputPorts="4",Position=[455 130 590 215]);
add_block("simulink/Sinks/Scope",blockPath + "/Material Density", ...
    Position=[455 235 590 285]);
add_block("simulink/Sinks/XY Graph",blockPath + "/Objective History", ...
    Position=[455 315 590 375]);
add_block("simulink/Sinks/XY Graph",blockPath + "/Constraint History", ...
    Position=[625 315 760 375]);

connect(blockPath,"run_analysis/1","Electromagnet Analysis/1");
connect(blockPath,"run_topology/1","Density Topology Optimization/1");
for index = 1:3
    connect(blockPath,"Electromagnet Analysis/" + index, ...
        outputNames(index) + "/1");
    connect(blockPath,"Electromagnet Analysis/" + index, ...
        "Analysis Monitor/" + index);
end
for index = 1:9
    connect(blockPath,"Density Topology Optimization/" + index, ...
        outputNames(index+3) + "/1");
end
for index = 1:3
    connect(blockPath,"Density Topology Optimization/" + index, ...
        "Optimization Monitor/" + index);
end
connect(blockPath,"Density Topology Optimization/5", ...
    "Optimization Monitor/4");
connect(blockPath,"Density Topology Optimization/4", ...
    "Material Density/1");
connect(blockPath,"Density Topology Optimization/7", ...
    "Objective History/1");
connect(blockPath,"Density Topology Optimization/8", ...
    "Objective History/2");
connect(blockPath,"Density Topology Optimization/7", ...
    "Constraint History/1");
connect(blockPath,"Density Topology Optimization/9", ...
    "Constraint History/2");

mask = Simulink.Mask.create(blockPath);
mask.Description = "Electromagnet batch analysis plus density topology " + ...
    "optimization with one VIM state solve, one adjoint solve, and MMA/SQP.";
mask.addParameter(Type="edit",Name="config_file", ...
    Prompt="Analysis configuration JSON",Value="''",Evaluate="on");
mask.addParameter(Type="edit",Name="run_root",Prompt="Run artifact root", ...
    Value="'C:\temp\radia_simulink'",Evaluate="on");
mask.addParameter(Type="edit",Name="timeout_s",Prompt="Timeout (s)", ...
    Value="3600",Evaluate="on");
mask.addParameter(Type="edit",Name="python_executable", ...
    Prompt="Python executable",Value="'python'",Evaluate="on");
mask.addParameter(Type="edit",Name="radia_electromagnet_adjoint_runner", ...
    Prompt="Electromagnet adjoint runner", ...
    Value="radia_electromagnet_adjoint_runner",Evaluate="on");
mask.addParameter(Type="popup",Name="solver",Prompt="Optimizer", ...
    TypeOptions={"mma","sqp"},Value="mma");
mask.addParameter(Type="edit",Name="sample_time_s", ...
    Prompt="Sample time (s)",Value="1",Evaluate="on");
mask.addParameter(Type="edit",Name="history_capacity", ...
    Prompt="History capacity",Value="96",Evaluate="on");
mask.Initialization = ...
    "radia.simulink.configureElectromagnetOptimizationSubsystem(gcb);";
mask.Display = "disp('Electromagnet Topology Optimization');" + ...
    "port_label('input',1,'run analysis');" + ...
    "port_label('input',2,'run topology');";
for index = 1:numel(outputNames)
    mask.Display = mask.Display + "port_label('output'," + index + ...
        ",'" + outputNames(index) + "');";
end
set_param(blockPath,"Tag","RadiaElectromagnetTopology", ...
    "UserData",struct( ...
        "domain","electromagnet-topology-optimization", ...
        "analysis_backend","python-headless-cli-explicit-trigger", ...
        "adjoint_backend","matlab-native-vim-density-adjoint", ...
        "parameterization","per-cell-material-density", ...
        "solvers","mma,sqp", ...
        "state_solves_per_gradient",1, ...
        "adjoint_solves_per_gradient",1, ...
        "finite_difference_fallback",false, ...
        "python_per_optimization_step",false, ...
        "visualization","simulink-scope-xy", ...
        "history","complete-study-vectors"), ...
    "UserDataPersistent","on");
end

function connect(parent,source,destination)
add_line(parent,source,destination,"autorouting","smart");
end
