function monitorOutport = addIHMonitorBus(parentPath, options)
%ADDIHMONITORBUS Add a compact fixed-schema IH telemetry subsystem.
arguments
    parentPath (1,1) string
    options.HeatSource (1,1) string
    options.TemperatureSource (1,1) string
    options.CurrentSource (1,1) string
    options.AngleSource (1,1) string
    options.AmbientSource (1,1) string
    options.ConfigExpression (1,1) string = "radia_ih_config"
    options.RevisionExpression (1,1) string = "radia_ih_geometry_revision"
    options.BlockName (1,1) string = "IH Monitor"
    options.Position (1,4) double = [700 250 850 390]
    options.OutportNumber (1,1) double {mustBeInteger,mustBePositive} = 3
    options.OutportPosition (1,4) double = [930 305 960 325]
end

radia.simulink.makeIHMonitorBusObject();
monitorPath = parentPath + "/" + options.BlockName;
add_block("simulink/Ports & Subsystems/Subsystem", monitorPath, ...
    Position=options.Position);
delete_line(monitorPath, "In1/1", "Out1/1");
delete_block(monitorPath + "/In1");
delete_block(monitorPath + "/Out1");

inputNames = ["heat_density", "temperature", "current_A", ...
    "angle_rad", "ambient_temperature_K"];
for index = 1:numel(inputNames)
    add_block("simulink/Ports & Subsystems/In1", ...
        monitorPath + "/" + inputNames(index), Port=string(index), ...
        Position=[25, 45 + 50*(index-1), 55, 65 + 50*(index-1)]);
end
add_block("simulink/Sources/Constant", ...
    monitorPath + "/Geometry Revision", ...
    Value=options.RevisionExpression, Position=[25 300 105 330]);
add_block("simulink/Sources/Constant", ...
    monitorPath + "/Schema Version", ...
    Value="uint16(1)", OutDataTypeStr="uint16", ...
    Position=[340 25 405 55]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    monitorPath + "/Runtime", FunctionName="radia_ih_monitor_sfun", ...
    Parameters=options.ConfigExpression, Position=[145 85 300 255]);
add_block("simulink/Signal Routing/Bus Creator", ...
    monitorPath + "/Header", Inputs="5", ...
    OutDataTypeStr="Bus: RadiaMonitorHeaderV1", ...
    NonVirtualBus="on", Position=[430 55 440 165]);
add_block("simulink/Signal Routing/Bus Creator", ...
    monitorPath + "/Bus", Inputs="12", ...
    OutDataTypeStr="Bus: IHMonitorBusV1", ...
    NonVirtualBus="on", Position=[570 45 580 315]);
add_block("simulink/Ports & Subsystems/Out1", ...
    monitorPath + "/Monitor", Port="1", Position=[660 170 690 190]);

runtimeInputs = [inputNames + "/1", "Geometry Revision/1"];
for index = 1:numel(runtimeInputs)
    add_line(monitorPath, runtimeInputs(index), "Runtime/" + index, ...
        "autorouting", "smart");
end
headerSources = ["Schema Version/1", "Runtime/1", "Runtime/2", ...
    "Runtime/3", "Runtime/4"];
headerNames = ["schema_version", "status_code", "time_s", ...
    "revision", "error_code"];
for index = 1:numel(headerSources)
    line = add_line(monitorPath, headerSources(index), ...
        "Header/" + index, "autorouting", "smart");
    set_param(line, "Name", headerNames(index));
end
payloadNames = ["sample_index", "current_A", "angle_rad", ...
    "ambient_temperature_K", "heat_min_W_per_m3", ...
    "heat_mean_W_per_m3", "heat_max_W_per_m3", "total_heat_W", ...
    "temperature_min_K", "temperature_mean_K", "temperature_max_K"];
line = add_line(monitorPath, "Header/1", "Bus/1", ...
    "autorouting", "smart");
set_param(line, "Name", "header");
for index = 1:numel(payloadNames)
    line = add_line(monitorPath, "Runtime/" + (index + 4), ...
        "Bus/" + (index + 1), "autorouting", "smart");
    set_param(line, "Name", payloadNames(index));
end
add_line(monitorPath, "Bus/1", "Monitor/1");

parentSources = [options.HeatSource, options.TemperatureSource, ...
    options.CurrentSource, options.AngleSource, options.AmbientSource];
for index = 1:numel(parentSources)
    add_line(parentPath, parentSources(index), ...
        options.BlockName + "/" + index, "autorouting", "smart");
end
monitorOutport = parentPath + "/monitor";
add_block("simulink/Ports & Subsystems/Out1", monitorOutport, ...
    Port=string(options.OutportNumber), Position=options.OutportPosition);
add_line(parentPath, options.BlockName + "/1", "monitor/1", ...
    "autorouting", "smart");

mask = Simulink.Mask.create(monitorPath);
mask.Description = "Native IH scalar telemetry. Internal signal reduction " + ...
    "and Bus construction stay encapsulated; raw q and T remain separate.";
mask.Display = "disp('IH Monitor');" + ...
    "port_label('input',1,'q');port_label('input',2,'T');" + ...
    "port_label('input',3,'I');port_label('input',4,'theta');" + ...
    "port_label('input',5,'T_{amb}');port_label('output',1,'monitor');";
set_param(monitorPath, UserData=struct( ...
    "monitor_bus", "IHMonitorBusV1", ...
    "backend", "matlab-level2-monitor", ...
    "mean_kind", "cell-weighted", ...
    "raw_fields", "heat_density_W_per_m3,temperature_K"), ...
    UserDataPersistent="on");
end
