function dashboardPath = addIHMonitorDashboard(parentPath, options)
%ADDIHMONITORDASHBOARD Add standard IH scopes driven by one monitor bus.
arguments
    parentPath (1,1) string
    options.BlockName (1,1) string = "IH Dashboard"
    options.Position (1,4) double = [805 250 955 330]
end

dashboardPath = parentPath + "/" + options.BlockName;
add_block("simulink/Ports & Subsystems/Subsystem", dashboardPath, ...
    Position=options.Position);
delete_line(dashboardPath, "In1/1", "Out1/1");
delete_block(dashboardPath + "/Out1");
set_param(dashboardPath + "/In1", Name="Monitor", Port="1");
add_block("simulink/Signal Routing/Bus Selector", ...
    dashboardPath + "/Select Telemetry", ...
    OutputSignals=strjoin([ ...
        "heat_min_W_per_m3", "heat_mean_W_per_m3", ...
        "heat_max_W_per_m3", "temperature_min_K", ...
        "temperature_mean_K", "temperature_max_K", ...
        "total_heat_W"], ","), ...
    Position=[110 45 125 315]);
add_block("simulink/Signal Routing/Mux", ...
    dashboardPath + "/Heat Statistics", Inputs="3", ...
    Position=[205 45 215 135]);
add_block("simulink/Signal Routing/Mux", ...
    dashboardPath + "/Temperature Statistics", Inputs="3", ...
    Position=[205 165 215 255]);
add_block("simulink/Sinks/Scope", ...
    dashboardPath + "/Heat Scope", Position=[285 65 385 115]);
add_block("simulink/Sinks/Scope", ...
    dashboardPath + "/Temperature Scope", Position=[285 185 385 235]);
add_block("simulink/Sinks/Display", ...
    dashboardPath + "/Total Heat W", Position=[285 275 385 305]);
add_block("simulink/Signal Routing/Mux", ...
    dashboardPath + "/Monitor Telemetry", Inputs="7", ...
    Position=[430 75 440 305]);
add_block("simulink/Sinks/To Workspace", ...
    dashboardPath + "/Log Monitor Telemetry", ...
    VariableName="radia_ih_monitor", SaveFormat="Array", ...
    Position=[500 175 650 205]);
add_line(dashboardPath, "Monitor/1", "Select Telemetry/1");
for index = 1:3
    add_line(dashboardPath, "Select Telemetry/" + index, ...
        "Heat Statistics/" + index);
    add_line(dashboardPath, "Select Telemetry/" + (index + 3), ...
        "Temperature Statistics/" + index);
end
for index = 1:7
    add_line(dashboardPath, "Select Telemetry/" + index, ...
        "Monitor Telemetry/" + index);
end
add_line(dashboardPath, "Heat Statistics/1", "Heat Scope/1");
add_line(dashboardPath, ...
    "Temperature Statistics/1", "Temperature Scope/1");
add_line(dashboardPath, "Select Telemetry/7", "Total Heat W/1");
add_line(dashboardPath, ...
    "Monitor Telemetry/1", "Log Monitor Telemetry/1");
for scopeName = ["Heat Scope", "Temperature Scope"]
    scopeConfiguration = get_param( ...
        dashboardPath + "/" + scopeName, "ScopeConfiguration");
    scopeConfiguration.AxesScaling = "Auto";
end
mask = Simulink.Mask.create(dashboardPath);
mask.Description = "IH scalar telemetry dashboard. Distributed q and T " + ...
    "remain separate physical outputs.";
mask.Display = "disp('IH Dashboard');port_label('input',1,'monitor');";
set_param(dashboardPath, UserData=struct( ...
    "monitor_bus", "IHMonitorBusV1", ...
    "raw_fields", "heat_density_W_per_m3,temperature_K", ...
    "mean_kind", "cell-weighted"), UserDataPersistent="on");
end
