function blockPath = addMagLevCLNBlock(parent, options)
%ADDMAGLEVCLNBLOCK Add the moving common-basis MagLev CLN plant block.

arguments
    parent (1,1) string
    options.BlockName (1,1) string = "Magnetic Levitation"
    options.Position (1,4) double = [200 100 460 245]
    options.FamilyExpression (1,1) string = ...
        "radia.simulink.makeMagLevSmokeFamily()"
end

blockPath = parent + "/" + options.BlockName;
add_block("simulink/Ports & Subsystems/Subsystem", blockPath, ...
    Position=options.Position);
delete_line(blockPath, "In1/1", "Out1/1");
delete_block(blockPath + "/In1");
delete_block(blockPath + "/Out1");

add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/minus_dI_dt", Port="1", ...
    Position=[25 45 55 65]);
add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/height_m", Port="2", ...
    Position=[25 105 55 125]);
add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/coil_current_A", Port="3", ...
    Position=[25 165 55 185]);
add_block("simulink/Signal Routing/Mux", blockPath + "/Input Mux", ...
    Inputs="3", Position=[95 55 120 180]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath + "/Moving HCurl CLN", ...
    FunctionName="radia_hcurl_eddy_cln_family_sfunction", ...
    Parameters=char(options.FamilyExpression), Position=[175 75 365 160]);
add_block("simulink/Signal Routing/Demux", blockPath + "/Output Demux", ...
    Outputs="[-1 3]", Position=[415 75 440 160]);
add_block("simulink/Ports & Subsystems/Out1", ...
    blockPath + "/induced_response", Port="1", ...
    Position=[505 90 535 110]);
add_block("simulink/Ports & Subsystems/Out1", ...
    blockPath + "/force_N", Port="2", ...
    Position=[505 135 535 155]);

add_line(blockPath, "minus_dI_dt/1", "Input Mux/1");
add_line(blockPath, "height_m/1", "Input Mux/2");
add_line(blockPath, "coil_current_A/1", "Input Mux/3");
add_line(blockPath, "Input Mux/1", "Moving HCurl CLN/1");
add_line(blockPath, "Moving HCurl CLN/1", "Output Demux/1");
add_line(blockPath, "Output Demux/1", "induced_response/1");
add_line(blockPath, "Output Demux/2", "force_N/1");

mask = Simulink.Mask.create(blockPath);
mask.Description = ...
    "Moving conductive-body HCurl/CLN plant with common reduced coordinates. " + ...
    "The block evaluates the induced response and reduced Lorentz force without per-step Python.";
mask.addParameter(Type="edit", Name="family", ...
    Prompt="Common-basis CLN family", ...
    Value=char(options.FamilyExpression), Evaluate="off", ...
    Callback="radia.simulink.onMagLevBlockFamilyChanged(gcb);");
mask.Display = "disp('Magnetic Levitation');" + ...
    "port_label('input',1,'-dI/dt');" + ...
    "port_label('input',2,'height');" + ...
    "port_label('input',3,'I');" + ...
    "port_label('output',1,'response');" + ...
    "port_label('output',2,'F');";
set_param(blockPath, "Tag", "RadiaMagLevCLN", ...
    "UserData", struct( ...
        "backend", "matlab-level2-common-basis-cln", ...
        "state_lifecycle", "outputs-read;update-advance", ...
        "interpolation", "shared-state-coordinate-family", ...
        "force", "reduced-lorentz-operator", ...
        "python_per_step", false, ...
        "surrogate", false), ...
    "UserDataPersistent", "on");
end
