function blockPath = addNonlinearReactorBlock(parent,options)
%ADDNONLINEARREACTORBLOCK Add the masked production reactor library block.
arguments
    parent (1,1) string
    options.BlockName (1,1) string = "Nonlinear HDiv-MMM Reactor"
    options.Position (1,4) double = [45 35 300 125]
    options.ConfigExpression (1,1) string = "radia_nonlinear_reactor_config"
end
blockPath = parent+"/"+options.BlockName;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath,"Position",options.Position);
mask = Simulink.Mask.create(blockPath);
mask.Type = "Radia Nonlinear HDiv-MMM Reactor";
mask.Description = ...
    "Native nonlinear HDiv-MMM reactor. Input is winding current; outputs " + ...
    "are terminal voltage, flux linkage, differential inductance, peak B, " + ...
    "magnetic energy, Newton iterations, residual, and distributed B samples.";
mask.addParameter(Type="edit",Name="reactor_config", ...
    Prompt="Reactor configuration",Value=options.ConfigExpression, ...
    Evaluate="on");
set_param(blockPath,"Parameters","reactor_config");
set_param(blockPath,"FunctionName","radia_nonlinear_reactor_sfun");
mask.Display = "disp('Nonlinear HDiv-MMM Reactor');" + ...
    "port_label('input',1,'current_A');" + ...
    "port_label('output',1,'voltage_V');" + ...
    "port_label('output',2,'flux_Wb_turn');" + ...
    "port_label('output',3,'Ldiff_H');" + ...
    "port_label('output',4,'Bpeak_T');" + ...
    "port_label('output',5,'energy_J');" + ...
    "port_label('output',6,'iterations');" + ...
    "port_label('output',7,'residual');" + ...
    "port_label('output',8,'B_samples_T');";
set_param(blockPath,"UserData",struct( ...
    "domain","nonlinear-reactor", ...
    "formulation","reduced-hdiv-mmm", ...
    "backend","matlab-level2+radia-mex-handle", ...
    "state_lifecycle","outputs-evaluate;update-commit", ...
    "python_per_step",false,"surrogate",false, ...
    "constitutive_law","single-valued nonlinear BH table"), ...
    "UserDataPersistent","on");
end
