function blockPath = addStreamFunctionOptunaBlock(parent, options)
%ADDSTREAMFUNCTIONOPTUNABLOCK Add explicit-batch Stream Function Optuna.
arguments
    parent (1,1) string
    options.BlockName (1,1) string = "Stream Function Optuna"
    options.Position (1,4) double = [45 620 345 680]
end
blockPath = parent + "/" + options.BlockName;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath, FunctionName="radia_streamfunction_optuna_sfun", ...
    Parameters="'radia_streamfunction_optuna_runner'," + ...
        "'radia_streamfunction_optuna_study',20,1", ...
    Position=options.Position, ShowName="off");
mask = Simulink.Mask.create(blockPath);
mask.Description = "MATLAB Optuna outer-loop search over explicit Stream " + ...
    "Function ACA+/QR/TSVD batch analyses. One rising trigger runs the " + ...
    "requested trials; Python is never called per simulation timestep.";
mask.addParameter(Type="edit", Name="runner_variable", ...
    Prompt="Optuna runner variable", ...
    Value="'radia_streamfunction_optuna_runner'", Evaluate="on");
mask.addParameter(Type="edit", Name="study_variable", ...
    Prompt="Optuna study variable", ...
    Value="'radia_streamfunction_optuna_study'", Evaluate="on");
mask.addParameter(Type="edit", Name="num_trials", ...
    Prompt="Number of trials", Value="20", Evaluate="on");
mask.addParameter(Type="edit", Name="sample_time_s", ...
    Prompt="Sample time (s)", Value="1", Evaluate="on");
set_param(blockPath, "Parameters", ...
    "runner_variable,study_variable,num_trials,sample_time_s");
mask.Display = "disp('Stream Function Optuna');" + ...
    "port_label('input',1,'run');" + ...
    "port_label('output',1,'status');" + ...
    "port_label('output',2,'best');" + ...
    "port_label('output',3,'best trial');" + ...
    "port_label('output',4,'completed');" + ...
    "port_label('output',5,'failed');" + ...
    "port_label('output',6,'pareto N');" + ...
    "port_label('output',7,'elapsed_s');";
set_param(blockPath, "UserData", struct( ...
    "domain", "stream-function-optuna", ...
    "optimizer_backend", "matlab-native-optuna", ...
    "inner_factorization", "aca_plus_qr_tsvd", ...
    "execution", "one-explicit-batch-study-per-rising-trigger", ...
    "python_per_trial", true, ...
    "python_per_step", false, ...
    "artifact_contract", "radia.stream.optuna-trial.v1"), ...
    "UserDataPersistent", "on");
end
