function blockPath = addStreamFunctionOptimizationSubsystem( ...
        parent, name, position)
%ADDSTREAMFUNCTIONOPTIMIZATIONSUBSYSTEM Add the production SF optimizer.
arguments
    parent (1,1) string
    name (1,1) string = "Stream Function Optimization"
    position (1,4) double = [45 380 345 470]
end
blockPath = parent + "/" + name;
add_block("simulink/Ports & Subsystems/Subsystem",blockPath, ...
    Position=position);
delete_line(blockPath,"In1/1","Out1/1");
delete_block(blockPath + "/In1");
delete_block(blockPath + "/Out1");

add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/run_design",Port="1",OutDataTypeStr="boolean", ...
    Position=[25 55 55 75]);
add_block("simulink/Ports & Subsystems/In1", ...
    blockPath + "/run_adjoint",Port="2",OutDataTypeStr="boolean", ...
    Position=[25 205 55 225]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath + "/Stream Function Design", ...
    FunctionName="radia_application_sfun", ...
    Parameters="'streamfunction','','C:\temp\radia_simulink'," + ...
        "3600,'python'",Position=[125 35 355 105]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath + "/Analytic Topology Optimization", ...
    FunctionName="radia_streamfunction_topology_sfun", ...
    Parameters="radia_streamfunction_adjoint_runner,1,64", ...
    Position=[125 170 385 275]);

outputNames = [ ...
    "design_status","primary","elapsed_s", ...
    "objective","optimization_status","iterations","design", ...
    "history_count","history_iteration","history_objective", ...
    "history_constraint"];
for index = 1:numel(outputNames)
    y = 25 + (index-1)*35;
    add_block("simulink/Ports & Subsystems/Out1", ...
        blockPath + "/" + outputNames(index),Port=string(index), ...
        Position=[790 y 820 y+20]);
end

add_block("simulink/Sinks/Scope",blockPath + "/Batch Monitor", ...
    NumInputPorts="3",Position=[455 30 590 105]);
add_block("simulink/Sinks/Scope",blockPath + "/Optimization Monitor", ...
    NumInputPorts="3",Position=[455 135 590 210]);
add_block("simulink/Sinks/Scope",blockPath + "/Design Coefficients", ...
    Position=[455 225 590 275]);
add_block("simulink/Sinks/XY Graph",blockPath + "/Objective History", ...
    Position=[455 305 590 365]);
add_block("simulink/Sinks/XY Graph",blockPath + "/Constraint History", ...
    Position=[625 305 760 365]);

connect(blockPath,"run_design/1","Stream Function Design/1");
connect(blockPath,"run_adjoint/1","Analytic Topology Optimization/1");
for index = 1:3
    connect(blockPath,"Stream Function Design/" + index, ...
        outputNames(index) + "/1");
    connect(blockPath,"Stream Function Design/" + index, ...
        "Batch Monitor/" + index);
end
for index = 1:8
    connect(blockPath,"Analytic Topology Optimization/" + index, ...
        outputNames(index+3) + "/1");
end
for index = 1:3
    connect(blockPath,"Analytic Topology Optimization/" + index, ...
        "Optimization Monitor/" + index);
end
connect(blockPath,"Analytic Topology Optimization/4", ...
    "Design Coefficients/1");
connect(blockPath,"Analytic Topology Optimization/6", ...
    "Objective History/1");
connect(blockPath,"Analytic Topology Optimization/7", ...
    "Objective History/2");
connect(blockPath,"Analytic Topology Optimization/6", ...
    "Constraint History/1");
connect(blockPath,"Analytic Topology Optimization/8", ...
    "Constraint History/2");

mask = Simulink.Mask.create(blockPath);
mask.Description = "Stream-function design/Pareto batch plus analytic " + ...
    "MMA/SQP coefficient optimization and Simulink-native history plots.";
mask.addParameter(Type="edit",Name="config_file", ...
    Prompt="Design configuration JSON",Value="''",Evaluate="on");
mask.addParameter(Type="edit",Name="run_root",Prompt="Run artifact root", ...
    Value="'C:\temp\radia_simulink'",Evaluate="on");
mask.addParameter(Type="edit",Name="timeout_s",Prompt="Timeout (s)", ...
    Value="3600",Evaluate="on");
mask.addParameter(Type="edit",Name="python_executable", ...
    Prompt="Python executable",Value="'python'",Evaluate="on");
mask.addParameter(Type="edit",Name="radia_streamfunction_adjoint_runner", ...
    Prompt="Stream-function adjoint runner", ...
    Value="radia_streamfunction_adjoint_runner",Evaluate="on");
mask.addParameter(Type="popup",Name="solver", ...
    Prompt="Optimizer",TypeOptions={"mma","sqp"},Value="mma");
mask.addParameter(Type="edit",Name="sample_time_s", ...
    Prompt="Sample time (s)",Value="1",Evaluate="on");
mask.addParameter(Type="edit",Name="history_capacity", ...
    Prompt="History capacity",Value="64",Evaluate="on");
mask.Initialization = ...
    "radia.simulink.configureStreamFunctionOptimizationSubsystem(gcb);";
mask.Display = "disp('Stream Function Optimization');" + ...
    "port_label('input',1,'run design');" + ...
    "port_label('input',2,'run adjoint');";
for index = 1:numel(outputNames)
    mask.Display = mask.Display + "port_label('output'," + index + ...
        ",'" + outputNames(index) + "');";
end
set_param(blockPath,"UserData",struct( ...
    "domain","stream-function-topology-optimization", ...
    "batch_backend","python-headless-cli-explicit-trigger", ...
    "adjoint_backend","matlab-native-analytic-gradient", ...
    "parameterization","stream-function-coefficients", ...
    "python_per_step",false, ...
    "visualization","simulink-scope-xy", ...
    "history","complete-study-vectors", ...
    "browser_required",false),"UserDataPersistent","on");
end

function connect(parent,source,destination)
add_line(parent,source,destination,"autorouting","smart");
end
