function config = assembleIHOperatorsFromGeometry(wpVol, coilFile, configFile, options)
%ASSEMBLEIHOPERATORSFROMGEOMETRY Build native IH operators from geometry.
%   This is the explicit Simulink update boundary. It invokes Radia's
%   built-in radia-ih-assemble Python CLI once, then returns the checked
%   JSON configuration. Python is never invoked by either time-step
%   S-Function.

arguments
    wpVol (1,1) string
    coilFile (1,1) string
    configFile (1,1) string
    options (1,1) struct = struct()
end
if ~isfile(wpVol)
    error("radia:simulink:IHAssemblyWorkpiece", ...
        "Workpiece geometry does not exist: %s", wpVol);
end
if ~isfile(coilFile)
    error("radia:simulink:IHAssemblyCoil", ...
        "Coil geometry does not exist: %s", coilFile);
end

% Legacy callers with only a panel file retain the specified-panel behavior.
if ~isfield(options,"zs_mode") && isfield(options,"panel_zs_file") && strlength(string(options.panel_zs_file)) > 0
    options.zs_mode = "element-file";
end
defaults = struct( ...
    "python_executable", "", ...
    "axisymmetric_thermal_vol", "", ...
    "panel_zs_file", "", ...
    "zs_mode", "uniform", ...
    "esim_bh_file", "", ...
    "esim_panel_evaluator", "table", ...
    "esim_tolerance", 1e-3, ...
    "esim_max_iter", 15, ...
    "esim_half_thickness_m", 0.01, ...
    "esim_reference_current_A", 1, ...
    "esim_drive_relative_band", 0.1, ...
    "esim_reference_phase_rad", 0, ...
    "n_phi_samples", 128, ...
    "frequency_hz", 7000, ...
    "coil_sigma", 5.8e7, ...
    "workpiece_sigma", 5.0e6, ...
    "workpiece_mu_r", 100, ...
    "density", 7800, ...
    "heat_capacity", 467, ...
    "thermal_conductivity", 46.6, ...
    "thermal_order", 1, ...
    "convection", 10, ...
    "initial_temperature_K", 293.15, ...
    "sample_time_s", 0.5, ...
    "workpiece_label", "sibc", ...
    "coil_body_label", "body", ...
    "coil_source_label", "source", ...
    "coil_sink_label", "sink", ...
    "peec_n_peri", 16, ...
    "coil_step_solver", "peec", ...
    "fin_n_lanes", [], ...
    "fin_n_stations", [], ...
    "fin_lane_grading", "", ...
    "fin_tip_lanes", [], ...
    "peec_proximity", true, ...
    "coupling_mode", "weak", ...
    "workpiece_bem_backend", "intree-dense");
names = string(fieldnames(defaults));
for index = 1:numel(names)
    name = names(index);
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end

options.python_executable = radia.internal.resolveAssemblyPython( ...
    options.python_executable);

parts = [ ...
    quote(options.python_executable), "-m", ...
    "radia.simulink.ih_operator_assembly", ...
    quote(wpVol), quote(coilFile), ...
    "--output", quote(configFile), ...
    "--frequency", numeric(options.frequency_hz, "frequency_hz"), ...
    "--coil-sigma", numeric(options.coil_sigma, "coil_sigma"), ...
    "--workpiece-sigma", numeric(options.workpiece_sigma, "workpiece_sigma"), ...
    "--workpiece-mu-r", numeric(options.workpiece_mu_r, "workpiece_mu_r"), ...
    "--density", numeric(options.density, "density"), ...
    "--heat-capacity", numeric(options.heat_capacity, "heat_capacity"), ...
    "--thermal-conductivity", numeric(options.thermal_conductivity, "thermal_conductivity"), ...
    "--thermal-order", integer(options.thermal_order, "thermal_order"), ...
    "--convection", numeric(options.convection, "convection"), ...
    "--initial-temperature-K", numeric(options.initial_temperature_K, "initial_temperature_K"), ...
    "--sample-time", numeric(options.sample_time_s, "sample_time_s"), ...
    "--workpiece-label", quote(options.workpiece_label), ...
    "--coil-body-label", quote(options.coil_body_label), ...
    "--coil-source-label", quote(options.coil_source_label), ...
    "--coil-sink-label", quote(options.coil_sink_label), ...
    "--peec-n-peri", integer(options.peec_n_peri, "peec_n_peri"), ...
    "--coil-step-solver", choice(options.coil_step_solver, ...
        "coil_step_solver", ["peec", "fin-surface"]), ...
    "--coupling-mode", quote(options.coupling_mode), ...
    "--workpiece-bem-backend", quote(options.workpiece_bem_backend)];
optionalIntegers = ["fin_n_lanes", "fin_n_stations", "fin_tip_lanes"];
optionalFlags = ["--fin-n-lanes", "--fin-n-stations", "--fin-tip-lanes"];
for index = 1:numel(optionalIntegers)
    name = optionalIntegers(index);
    if ~isempty(options.(name)) && strlength(string(options.(name))) > 0
        parts(end + 1:end + 2) = [optionalFlags(index), integer(options.(name), name)];
    end
end
if strlength(strtrim(string(options.fin_lane_grading))) > 0
    parts(end + 1:end + 2) = ["--fin-lane-grading", ...
        choice(options.fin_lane_grading, "fin_lane_grading", ["auto", "uniform"])];
end
if logicalValue(options.peec_proximity, "peec_proximity")
    parts(end + 1) = "--peec-proximity";
else
    parts(end + 1) = "--no-peec-proximity";
end
parts(end+1:end+2) = ["--zs-mode", choice(options.zs_mode, "zs_mode", ...
    ["uniform", "element-file", "per-panel-esim"])];
if string(options.zs_mode) == "per-panel-esim"
    parts = [parts, "--esim-bh-file", quote(options.esim_bh_file), ...
        "--esim-panel-evaluator", choice(options.esim_panel_evaluator, ...
        "esim_panel_evaluator", ["table", "direct"]), ...
        "--esim-tolerance", numeric(options.esim_tolerance, "esim_tolerance"), ...
        "--esim-max-iter", integer(options.esim_max_iter, "esim_max_iter"), ...
        "--esim-half-thickness-m", numeric(options.esim_half_thickness_m, "esim_half_thickness_m"), ...
        "--esim-reference-current-A", numeric(options.esim_reference_current_A, "esim_reference_current_A"), ...
        "--esim-drive-relative-band", numeric(options.esim_drive_relative_band, "esim_drive_relative_band"), ...
        "--esim-reference-phase-rad", numeric(options.esim_reference_phase_rad, "esim_reference_phase_rad")];
end
command = join(parts, " ");
if strlength(string(options.panel_zs_file)) > 0
    command = command + " --panel-zs-file " + quote(options.panel_zs_file);
end
if strlength(string(options.axisymmetric_thermal_vol)) > 0
    command = command + " --axisymmetric-thermal-vol " + quote(options.axisymmetric_thermal_vol) + ...
        " --n-phi-samples " + integer(options.n_phi_samples,"n_phi_samples");
end
[status, output] = system(command);
if status ~= 0 || ~isfile(configFile)
    error("radia:simulink:IHAssemblyFailed", ...
        "Built-in IH operator assembly failed (exit %d).\n%s", ...
        status, tailOf(output, 4000));
end
try
    config = jsondecode(fileread(configFile));
catch decodeError
    error("radia:simulink:IHAssemblyArtifact", ...
        "Built-in IH assembler wrote invalid JSON (%s): %s", ...
        decodeError.message, configFile);
end
end

function value = quote(value)
value = '"' + replace(string(value), '"', '\"') + '"';
end

function value = numeric(raw, name)
if ischar(raw) || isstring(raw)
    number = str2double(string(raw));
else
    number = double(raw);
end
if ~(isscalar(number) && isfinite(number))
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be one finite number.", name);
end
value = compose("%.17g", number);
end

function value = integer(raw, name)
number = str2double(numeric(raw, name));
if number <= 0 || fix(number) ~= number
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be a positive integer.", name);
end
value = compose("%d", number);
end

function value = logicalValue(raw, name)
if islogical(raw) && isscalar(raw)
    value = raw;
    return
end

text = lower(strtrim(string(raw)));
if isscalar(text) && ismember(text, ["on", "true", "1"])
    value = true;
elseif isscalar(text) && ismember(text, ["off", "false", "0"])
    value = false;
else
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be on/off or true/false.", name);
end
end

function value = choice(raw, name, allowed)
value = string(raw);
if ~isscalar(value) || ~ismember(value, allowed)
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be one of: %s.", name, strjoin(allowed, ", "));
end
value = quote(value);
end

function text = tailOf(text, limit)
text = char(text);
if numel(text) > limit
    text = text(end - limit + 1:end);
end
end
