function config = assembleIHOperatorsFromGeometry(wpVol, coilFile, configFile, options)
%ASSEMBLEIHOPERATORSFROMGEOMETRY Build native IH operators from geometry.
%   This is the explicit Simulink update boundary. It invokes Radia's
%   built-in radia-ih-assemble Python CLI once, then returns the checked
%   JSON configuration. Python is never invoked by either time-step
%   S-Function.

arguments
    wpVol (1,1) string
    coilFile (1,1) string
    configFile (1,1) string
    options (1,1) struct = struct()
end
if ~isfile(wpVol)
    error("radia:simulink:IHAssemblyWorkpiece", ...
        "Workpiece geometry does not exist: %s", wpVol);
end
if ~isfile(coilFile)
    error("radia:simulink:IHAssemblyCoil", ...
        "Coil geometry does not exist: %s", coilFile);
end

defaults = struct( ...
    "python_executable", "python", ...
    "frequency_hz", 7000, ...
    "coil_sigma", 5.8e7, ...
    "workpiece_sigma", 5.0e6, ...
    "workpiece_mu_r", 100, ...
    "density", 7800, ...
    "heat_capacity", 467, ...
    "thermal_conductivity", 46.6, ...
    "convection", 10, ...
    "initial_temperature_K", 293.15, ...
    "sample_time_s", 0.5, ...
    "workpiece_label", "sibc", ...
    "coil_body_label", "body", ...
    "coil_source_label", "source", ...
    "coil_sink_label", "sink", ...
    "peec_n_peri", 16, ...
    "peec_proximity", true, ...
    "coupling_mode", "weak", ...
    "workpiece_bem_backend", "intree-dense");
names = string(fieldnames(defaults));
for index = 1:numel(names)
    name = names(index);
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end

parts = [ ...
    quote(options.python_executable), "-m", ...
    "radia.simulink.ih_operator_assembly", ...
    quote(wpVol), quote(coilFile), ...
    "--output", quote(configFile), ...
    "--frequency", numeric(options.frequency_hz, "frequency_hz"), ...
    "--coil-sigma", numeric(options.coil_sigma, "coil_sigma"), ...
    "--workpiece-sigma", numeric(options.workpiece_sigma, "workpiece_sigma"), ...
    "--workpiece-mu-r", numeric(options.workpiece_mu_r, "workpiece_mu_r"), ...
    "--density", numeric(options.density, "density"), ...
    "--heat-capacity", numeric(options.heat_capacity, "heat_capacity"), ...
    "--thermal-conductivity", numeric(options.thermal_conductivity, "thermal_conductivity"), ...
    "--convection", numeric(options.convection, "convection"), ...
    "--initial-temperature-K", numeric(options.initial_temperature_K, "initial_temperature_K"), ...
    "--sample-time", numeric(options.sample_time_s, "sample_time_s"), ...
    "--workpiece-label", quote(options.workpiece_label), ...
    "--coil-body-label", quote(options.coil_body_label), ...
    "--coil-source-label", quote(options.coil_source_label), ...
    "--coil-sink-label", quote(options.coil_sink_label), ...
    "--peec-n-peri", integer(options.peec_n_peri, "peec_n_peri"), ...
    "--coupling-mode", quote(options.coupling_mode), ...
    "--workpiece-bem-backend", quote(options.workpiece_bem_backend)];
if logicalValue(options.peec_proximity, "peec_proximity")
    parts(end + 1) = "--peec-proximity";
else
    parts(end + 1) = "--no-peec-proximity";
end
command = join(parts, " ");
[status, output] = system(command);
if status ~= 0 || ~isfile(configFile)
    error("radia:simulink:IHAssemblyFailed", ...
        "Built-in IH operator assembly failed (exit %d).\n%s", ...
        status, tailOf(output, 4000));
end
try
    config = jsondecode(fileread(configFile));
catch decodeError
    error("radia:simulink:IHAssemblyArtifact", ...
        "Built-in IH assembler wrote invalid JSON (%s): %s", ...
        decodeError.message, configFile);
end
end

function value = quote(value)
value = '"' + replace(string(value), '"', '\"') + '"';
end

function value = numeric(raw, name)
if ischar(raw) || isstring(raw)
    number = str2double(string(raw));
else
    number = double(raw);
end
if ~(isscalar(number) && isfinite(number))
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be one finite number.", name);
end
value = compose("%.17g", number);
end

function value = integer(raw, name)
number = str2double(numeric(raw, name));
if number <= 0 || fix(number) ~= number
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be a positive integer.", name);
end
value = compose("%d", number);
end

function value = logicalValue(raw, name)
if islogical(raw) && isscalar(raw)
    value = raw;
    return
end
text = lower(strtrim(string(raw)));
if isscalar(text) && ismember(text, ["on", "true", "1"])
    value = true;
elseif isscalar(text) && ismember(text, ["off", "false", "0"])
    value = false;
else
    error("radia:simulink:IHAssemblyOption", ...
        "%s must be on/off or true/false.", name);
end
end

function text = tailOf(text, limit)
text = char(text);
if numel(text) > limit
    text = text(end - limit + 1:end);
end
end
