function blockPath=buildOptunaBlock(modelName,options)
%BUILDOPTUNABLOCK Add a triggerable MATLAB Optuna block to a Simulink model.
arguments
 modelName (1,1) string; options.ObjectiveFcn (1,1) string; options.NumTrials (1,1) double {mustBeInteger,mustBePositive}=20
 options.Direction (1,1) string {mustBeMember(options.Direction,["minimize","maximize"])}="minimize"
 options.Directions string=string.empty
 options.StoragePath (1,1) string=""; options.SampleTime_s (1,1) double {mustBePositive}=1
 options.Sampler (1,1) string {mustBeMember(options.Sampler, ...
  ["auto","random","tpe","cmaes","motpe","nsgaii","gp", ...
  "nsgaiii","bruteforce","qmc"])}="auto"
 options.Seed double=[]
 options.Pruner (1,1) string {mustBeMember(options.Pruner, ...
  ["none","median","hyperband","percentile","patient", ...
  "successivehalving","threshold"])}="none"
 options.ParameterSpec (1,1) string="[]"
 options.ModelName (1,1) string=modelName
 options.LiveVisualization (1,1) logical=false; options.Save (1,1) logical=true
end
if ~bdIsLoaded(modelName), new_system(modelName); end
blockPath=modelName+"/Optuna Optimization";
directions=options.Directions;
if isempty(directions), directions=options.Direction; end
if any(~ismember(directions,["minimize","maximize"]))
 error("radia:simulink:OptunaDirection","Directions must contain only minimize or maximize.");
end
directionExpression=formatDirections(directions);
objectiveExpression=formatObjective(options.ObjectiveFcn);
seedExpression=formatSeed(options.Seed);
samplerExpression=formatSamplerConfig(options.Sampler,seedExpression, ...
 options.Pruner,options.ParameterSpec,options.ModelName);
initialParameters=sprintf('%s,%d,%s,''%s'',%.17g,%d,%s', ...
 objectiveExpression,options.NumTrials,directionExpression, ...
 options.StoragePath,options.SampleTime_s,options.LiveVisualization, ...
 samplerExpression);
add_block('simulink/User-Defined Functions/Level-2 MATLAB S-Function', ...
 char(blockPath),'FunctionName','radia_optuna_sfun', ...
 'Parameters',initialParameters);
set_param(char(blockPath),'Position',[180 90 480 430]);
mask=Simulink.Mask.create(blockPath);
mask.Description="MATLAB-native Optuna session. One trial executes per " + ...
 "sample; completed history is checkpointed and objective failures are " + ...
 "recorded. Status: -1 failure, 0 idle, 1 complete, 2 running, " + ...
 "3 cancelled, 4 paused.";
mask.addParameter(Type="edit",Name="objective_fcn",Prompt="Objective function", ...
 Value=objectiveExpression,Evaluate="on");
mask.addParameter(Type="edit",Name="num_trials",Prompt="Number of trials", ...
 Value=string(options.NumTrials),Evaluate="on");
mask.addParameter(Type="edit",Name="directions",Prompt="Objective directions", ...
 Value=directionExpression,Evaluate="on");
mask.addParameter(Type="edit",Name="storage_path",Prompt="Study MAT file", ...
 Value=quoteString(options.StoragePath),Evaluate="on");
mask.addParameter(Type="edit",Name="sample_time_s",Prompt="Trial sample time (s)", ...
 Value=compose("%.17g",options.SampleTime_s),Evaluate="on");
liveValue="off"; if options.LiveVisualization,liveValue="on";end
mask.addParameter(Type="checkbox",Name="live_visualization", ...
 Prompt="External MATLAB monitor",Value=liveValue);
mask.addParameter(Type="popup",Name="sampler_name",Prompt="Sampler", ...
 TypeOptions={"auto","random","tpe","cmaes","motpe","nsgaii", ...
 "gp","nsgaiii","bruteforce","qmc"}, ...
 Value=options.Sampler);
mask.addParameter(Type="edit",Name="seed",Prompt="Sampler seed ([] = fresh)", ...
 Value=seedExpression,Evaluate="on");
mask.addParameter(Type="popup",Name="pruner_name",Prompt="Pruner", ...
 TypeOptions={"none","median","hyperband","percentile","patient", ...
 "successivehalving","threshold"},Value=options.Pruner);
mask.addParameter(Type="edit",Name="parameter_spec", ...
 Prompt="OptimizationParameter array ([] = Trial objective)", ...
 Value=options.ParameterSpec,Evaluate="on");
mask.addParameter(Type="edit",Name="model_name",Prompt="Model to update", ...
 Value=quoteString(options.ModelName),Evaluate="on");
set_param(blockPath,"Parameters", ...
 "objective_fcn,num_trials,directions,storage_path,sample_time_s," + ...
 "strcmp(live_visualization,'on')," + ...
 "struct('Name',sampler_name,'Seed',seed,'Pruner',pruner_name," + ...
 "'Parameters',parameter_spec,'ModelName',model_name)");
mask.Display="disp('Optuna Optimization');" + ...
    "port_label('input',1,'start');" + ...
    "port_label('input',2,'cancel');" + ...
    "port_label('input',3,'pause');" + ...
    "port_label('input',4,'resume');" + ...
    "port_label('input',5,'selected trial');" + ...
    "port_label('input',6,'apply');" + ...
 "port_label('output',1,'best');port_label('output',2,'best trial');" + ...
 "port_label('output',3,'status');port_label('output',4,'trials');" + ...
 "port_label('output',5,'last');port_label('output',6,'elapsed');" + ...
 "port_label('output',7,'best update');port_label('output',8,'pareto N');" + ...
 "port_label('output',9,'pareto X');port_label('output',10,'pareto Y');" + ...
    "port_label('output',11,'pareto rev');" + ...
    "port_label('output',12,'failed');port_label('output',13,'attempted');" + ...
    "port_label('output',14,'failure code');" + ...
    "port_label('output',15,'selected');port_label('output',16,'pruned');" + ...
    "port_label('output',17,'current');port_label('output',18,'checkpoint');";
set_param(blockPath,"UserData",struct("execution","one-trial-per-sample", ...
 "visualization","simulink-monitor","browser_required",false, ...
 "optimizer_backend","matlab-native", ...
 "session_contract","radia.optuna.session-snapshot.v1", ...
 "controls","start,cancel,pause,resume,select,apply", ...
 "pareto_kernel","required-optuna-mex", ...
 "cae_failure_policy","record-and-continue", ...
 "python_per_trial",false),"UserDataPersistent","on");
if options.Save, save_system(modelName); end
end

function expression=formatDirections(directions)
quoted='"'+reshape(string(directions),1,[])+'"';
if isscalar(quoted)
 expression=char(quoted);
else
 expression=char("["+strjoin(quoted,",")+"]");
end
end

function expression=formatObjective(value)
value=strtrim(string(value));
if startsWith(value,"@")
 expression=char(value);
else
 expression=char(quoteString(value));
end
end

function expression=quoteString(value)
expression="'"+replace(string(value),"'","''")+"'";
end

function expression=formatSeed(value)
if isempty(value)
 expression="[]";
elseif isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value>=0 && value==floor(value)
 expression=compose("%.0f",value);
else
 error("radia:simulink:OptunaSeed", ...
  "Seed must be empty or one nonnegative integer.");
end
end

function expression=formatSamplerConfig(name,seed,pruner,parameters,modelName)
parameters=strtrim(string(parameters));
if strlength(parameters)==0,parameters="[]";end
expression="struct('Name',"+quoteString(name)+",'Seed',"+seed+ ...
 ",'Pruner',"+quoteString(pruner)+",'Parameters',"+parameters+ ...
 ",'ModelName',"+quoteString(modelName)+")";
end
