function [blockPath, monitorPath] = buildSheetMetalOptimizationBlock(modelName, options)
%BUILDSHEETMETALOPTIMIZATIONBLOCK Add native sheet optimization and monitor.
arguments
    modelName (1,1) string
    options.RunnerVariable (1,1) string = "radia_sheet_metal_runner"
    options.Runner = []
    options.NumTrials (1,1) double {mustBeInteger,mustBePositive} = 20
    options.Direction (1,1) string ...
        {mustBeMember(options.Direction,["minimize","maximize"])} = "minimize"
    options.Directions string = string.empty
    options.StoragePath (1,1) string = ""
    options.SampleTime_s (1,1) double {mustBePositive} = 1
    options.Sampler (1,1) string {mustBeMember(options.Sampler, ...
        ["auto","random","tpe","cmaes","motpe","nsgaii"])} = "auto"
    options.LiveVisualization (1,1) logical = false
    options.AddMonitor (1,1) logical = true
    options.Save (1,1) logical = true
end
if ~isvarname(options.RunnerVariable)
    error("radia:simulink:SheetMetalRunnerVariable", ...
        "RunnerVariable must be a valid MATLAB variable name.");
end
if ~isempty(options.Runner)
    if ~isa(options.Runner, "radia.optuna.SheetMetalRunner")
        error("radia:simulink:SheetMetalRunner", ...
            "Runner must be a radia.optuna.SheetMetalRunner.");
    end
    assignin("base", options.RunnerVariable, options.Runner);
end
if ~bdIsLoaded(modelName)
    new_system(modelName);
end

directions = options.Directions;
if isempty(directions)
    directions = options.Direction;
end
if any(~ismember(directions, ["minimize","maximize"]))
    error("radia:simulink:OptunaDirection", ...
        "Directions must contain only minimize or maximize.");
end

blockPath = modelName + "/Sheet Metal Optimization";
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath, FunctionName="radia_optuna_sfun", ...
    Parameters="'',20,'minimize','',1,false,'auto'", ...
    Position=[180 90 390 180]);
mask = Simulink.Mask.create(blockPath);
mask.Description = "Native NGSolve/Cubit sheet-metal optimization with cancel, failure telemetry, and automatic MEX acceleration.";
mask.addParameter(Type="edit", Name="runner", ...
    Prompt="SheetMetalRunner", Value=options.RunnerVariable, Evaluate="on");
mask.addParameter(Type="edit", Name="num_trials", ...
    Prompt="Number of trials", Value=string(options.NumTrials), Evaluate="on");
mask.addParameter(Type="edit", Name="directions", ...
    Prompt="Objective directions", Value=formatDirections(directions), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="storage_path", ...
    Prompt="Study MAT file", Value=quoteString(options.StoragePath), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="sample_time_s", ...
    Prompt="Trial sample time (s)", Value=compose("%.17g", ...
    options.SampleTime_s), Evaluate="on");
liveValue = "off";
if options.LiveVisualization
    liveValue = "on";
end
mask.addParameter(Type="checkbox", Name="live_visualization", ...
    Prompt="External MATLAB monitor", Value=liveValue);
mask.addParameter(Type="popup", Name="sampler_name", Prompt="Sampler", ...
    TypeOptions={"auto","random","tpe","cmaes","motpe","nsgaii"}, ...
    Value=options.Sampler);
set_param(blockPath, Parameters= ...
    "@(trial)runner.evaluate(trial),num_trials,directions,storage_path," + ...
    "sample_time_s,strcmp(live_visualization,'on'),sampler_name");
mask.Display = "disp('Sheet Metal Optimization');" + ...
    "port_label('input',1,'start');" + ...
    "port_label('input',2,'cancel');" + ...
    "port_label('output',1,'best');port_label('output',2,'best trial');" + ...
    "port_label('output',3,'status');port_label('output',4,'trials');" + ...
    "port_label('output',5,'last');port_label('output',6,'elapsed');" + ...
    "port_label('output',7,'best update');port_label('output',8,'pareto N');" + ...
    "port_label('output',9,'pareto X');port_label('output',10,'pareto Y');" + ...
    "port_label('output',11,'pareto rev');" + ...
    "port_label('output',12,'failed');port_label('output',13,'attempted');" + ...
    "port_label('output',14,'failure code');";
set_param(blockPath, UserData=struct( ...
    "domain", "sheet-metal", ...
    "backend", "matlab-native-ngsolve-cubit", ...
    "runner", "radia.optuna.SheetMetalRunner", ...
    "execution", "one-trial-per-sample", ...
    "pareto_kernel", "required-optuna-mex", ...
    "cae_failure_policy", "record-and-continue", ...
    "python_per_trial", false, ...
    "browser_required", false), UserDataPersistent="on");

monitorPath = "";
if options.AddMonitor
    monitorPath = radia.simulink.addOptunaMonitor(modelName, ...
        "Sheet Metal Monitor", [470 65 720 220]);
    sourcePorts = [1,5,4,3,9,10,8,7,11];
    for index = 1:numel(sourcePorts)
        add_line(modelName, ...
            "Sheet Metal Optimization/" + sourcePorts(index), ...
            "Sheet Metal Monitor/" + index);
    end
end
if options.Save
    save_system(modelName);
end
end

function expression = formatDirections(directions)
quoted = '"' + reshape(string(directions), 1, []) + '"';
if isscalar(quoted)
    expression = char(quoted);
else
    expression = char("[" + strjoin(quoted, ",") + "]");
end
end

function expression = quoteString(value)
expression = "'" + replace(string(value), "'", "''") + "'";
end
