function modelPath = buildMagLevModel(options)
%BUILDMAGLEVMODEL Build the standalone Radia MagLev Simulink model.

arguments
    options.ModelName (1,1) string = "radia_maglev"
    options.OutputDirectory (1,1) string = ""
    options.Family (1,1) struct = struct()
    options.FamilyFile (1,1) string = ""
    options.Open (1,1) logical = false
end

if exist("new_system", "file") ~= 2 && exist("new_system", "builtin") ~= 5
    error("radia:simulink:MissingSimulink", ...
        "Simulink is required to build the MagLev model.");
end
if ~isempty(fieldnames(options.Family)) && strlength(options.FamilyFile) > 0
    error("radia:simulink:MagLevFamily", ...
        "Specify Family or FamilyFile, not both.");
end

matlabRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
if strlength(options.OutputDirectory) == 0
    options.OutputDirectory = matlabRoot;
end
if ~isfolder(options.OutputDirectory)
    mkdir(options.OutputDirectory);
end
if bdIsLoaded(options.ModelName)
    close_system(options.ModelName, 0);
end

if strlength(options.FamilyFile) > 0
    family = radia.simulink.loadHCurlEddyCLNFamily(options.FamilyFile);
elseif isempty(fieldnames(options.Family))
    family = radia.simulink.makeMagLevSmokeFamily();
else
    family = options.Family;
end
validateFamily(family);

new_system(options.ModelName);
workspace = get_param(options.ModelName, "ModelWorkspace");
workspace.assignin("radia_maglev_family", family);
workspace.assignin("radia_maglev_current_amplitude_A", 20.0);
workspace.assignin("radia_maglev_frequency_Hz", 50.0);

add_block("simulink/Sources/Sine Wave", ...
    options.ModelName + "/Coil Current", ...
    Amplitude="radia_maglev_current_amplitude_A", ...
    Frequency="2*pi*radia_maglev_frequency_Hz", ...
    Phase="0", SampleTime="radia_maglev_family.sample_time_s", ...
    Position=[35 55 105 85]);
add_block("simulink/Sources/Sine Wave", ...
    options.ModelName + "/Minus Current Derivative", ...
    Amplitude="2*pi*radia_maglev_frequency_Hz*radia_maglev_current_amplitude_A", ...
    Frequency="2*pi*radia_maglev_frequency_Hz", ...
    Phase="-pi/2", SampleTime="radia_maglev_family.sample_time_s", ...
    Position=[35 125 105 155]);
add_block("simulink/Sources/Constant", ...
    options.ModelName + "/Mechanical Height", ...
    Value="mean(radia_maglev_family.positions_m)", ...
    Position=[35 195 105 225]);

radia.simulink.addMagLevCLNBlock(options.ModelName, ...
    BlockName="MagLev Plant", Position=[205 65 485 235], ...
    FamilyExpression="radia_maglev_family");
add_block("simulink/Ports & Subsystems/Out1", ...
    options.ModelName + "/induced_response", Port="1", ...
    Position=[590 95 620 115]);
add_block("simulink/Ports & Subsystems/Out1", ...
    options.ModelName + "/force_N", Port="2", ...
    Position=[590 175 620 195]);
add_block("simulink/Sinks/Scope", ...
    options.ModelName + "/Induced Response", ...
    Position=[690 80 790 130]);
add_block("simulink/Sinks/Scope", ...
    options.ModelName + "/Lorentz Force", ...
    Position=[690 160 790 210]);
for scopeName = ["Induced Response", "Lorentz Force"]
    scopeConfiguration = get_param( ...
        options.ModelName + "/" + scopeName, "ScopeConfiguration");
    scopeConfiguration.AxesScaling = "Auto";
end

parameterPath = options.ModelName + "/MagLev Parameters";
add_block("simulink/Ports & Subsystems/Subsystem", parameterPath, ...
    Position=[205 285 485 365]);
delete_line(parameterPath, "In1/1", "Out1/1");
delete_block(parameterPath + "/In1");
delete_block(parameterPath + "/Out1");
mask = Simulink.Mask.create(parameterPath);
mask.Description = ...
    "Load a common-basis HCurl/CLN family exported by Radia. " + ...
    "The empty path keeps the family embedded in this model.";
familyFile = options.FamilyFile;
if strlength(familyFile) == 0 && isfield(family, "source_file")
    familyFile = string(family.source_file);
end
familyFileParameter = mask.addParameter(Type="edit", Name="family_file", ...
    Prompt="CLN family JSON", Value=char(familyFile), Evaluate="off");
interpolationParameter = mask.addParameter(Type="popup", ...
    Name="interpolation", Prompt="Position interpolation", ...
    TypeOptions={"nearest", "linear", "pchip"}, ...
    Value=char(string(family.interpolation)));
extrapolationParameter = mask.addParameter(Type="popup", ...
    Name="extrapolation", Prompt="Outside sampled range", ...
    TypeOptions={"error", "clamp"}, ...
    Value=char(string(family.extrapolation)));
sampleTimeParameter = mask.addParameter(Type="edit", ...
    Name="sample_time_s", Prompt="Sample time (s)", ...
    Value=char(compose("%.17g", family.sample_time_s)), Evaluate="off");
callback = "radia.simulink.onMagLevFamilyChanged(gcb);";
familyFileParameter.Callback = callback;
interpolationParameter.Callback = callback;
extrapolationParameter.Callback = callback;
sampleTimeParameter.Callback = callback;
mask.Display = "disp('MagLev Parameters');";
set_param(parameterPath, "UserData", struct( ...
    "schema", family.schema, ...
    "backend", "matlab-level2-common-basis-cln", ...
    "configuration", "model-workspace-or-family-json", ...
    "python_per_step", false), "UserDataPersistent", "on");

connect(options.ModelName, "Minus Current Derivative/1", "MagLev Plant/1");
connect(options.ModelName, "Mechanical Height/1", "MagLev Plant/2");
connect(options.ModelName, "Coil Current/1", "MagLev Plant/3");
connect(options.ModelName, "MagLev Plant/1", "induced_response/1");
connect(options.ModelName, "MagLev Plant/1", "Induced Response/1");
connect(options.ModelName, "MagLev Plant/2", "force_N/1");
connect(options.ModelName, "MagLev Plant/2", "Lorentz Force/1");

set_param(options.ModelName, ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", char(compose("%.17g", family.sample_time_s)), ...
    "StopTime", "0.1", ...
    "SaveOutput", "on", "OutputSaveName", "yout", ...
    "ModelBrowserVisibility", "off");
modelPath = fullfile(options.OutputDirectory, options.ModelName + ".slx");
save_system(options.ModelName, modelPath);
if options.Open
    open_system(options.ModelName);
else
    close_system(options.ModelName, 0);
end
end

function connect(modelName, source, destination)
add_line(modelName, source, destination, "autorouting", "smart");
end

function validateFamily(family)
required = ["schema", "shared_state_basis", "positions_m", "models", ...
    "snapshot_count", "state_order", "port_count", "sample_time_s", ...
    "interpolation", "extrapolation"];
if ~isstruct(family) || ~all(isfield(family, cellstr(required))) || ...
        string(family.schema) ~= "radia.hcurl.eddy_cln.family.v1" || ...
        ~family.shared_state_basis || family.snapshot_count < 1 || ...
        family.state_order < 1 || family.port_count < 1 || ...
        numel(family.models) ~= family.snapshot_count
    error("radia:simulink:MagLevFamily", ...
        "Family must be a valid common-basis HCurl CLN family.");
end
end
