function blockPath = buildOptunaStudyBlock(parent, options)
%BUILDOPTUNASTUDYBLOCK Add the compact student-facing Optuna facade.
%   The six-input/eighteen-output runtime remains inside the masked
%   subsystem.  A model using this facade therefore needs no rewiring when
%   the sampler, seed, pruner, search bounds, or trial budget changes.
arguments
    parent (1,1) string
    options.BlockName (1,1) string = "Optuna Study"
    options.ObjectiveFcn (1,1) string = ""
    options.NumTrials (1,1) double {mustBeInteger,mustBePositive} = 20
    options.Direction (1,1) string ...
        {mustBeMember(options.Direction,["minimize","maximize"])} = ...
        "minimize"
    options.Directions string = string.empty
    options.StoragePath (1,1) string = ""
    options.SampleTime_s (1,1) double {mustBePositive} = 1
    options.Sampler (1,1) string {mustBeMember(options.Sampler, ...
        ["auto","random","tpe","cmaes","motpe","nsgaii","gp", ...
        "nsgaiii","bruteforce","qmc"])} = "auto"
    options.Seed double = []
    options.Pruner (1,1) string {mustBeMember(options.Pruner, ...
        ["none","median","hyperband","percentile","patient", ...
        "successivehalving","threshold"])} = "none"
    options.ParameterSpec (1,1) string = "[]"
    options.ModelName (1,1) string = ""
    options.LiveVisualization (1,1) logical = false
    options.Position (1,4) double = [180 90 430 260]
    options.Save (1,1) logical = true
end

[rootName, parentPath] = normalizeParent(parent);
radia.simulink.makeOptunaMonitorBusObject();
if ~bdIsLoaded(rootName)
    new_system(rootName);
end
if strlength(parentPath) > 0 && getSimulinkBlockHandle(parentPath) < 0
    error("radia:simulink:OptunaParent", ...
        "Parent subsystem '%s' does not exist.", parentPath);
end

directions = options.Directions;
if isempty(directions)
    directions = options.Direction;
end
if any(~ismember(directions, ["minimize","maximize"]))
    error("radia:simulink:OptunaDirection", ...
        "Directions must contain only minimize or maximize.");
end
if strlength(options.ModelName) == 0 && strlength(parentPath) == 0
    options.ModelName = rootName;
end

blockPath = joinPath(parent, options.BlockName);
add_block("simulink/Ports & Subsystems/Subsystem", blockPath, ...
    Position=options.Position);
delete_line(blockPath, "In1/1", "Out1/1");
delete_block(blockPath + "/In1");
delete_block(blockPath + "/Out1");

add_block("simulink/Ports & Subsystems/In1", blockPath + "/Start", ...
    Port="1", Position=[30 78 60 92]);
add_block("simulink/Ports & Subsystems/In1", blockPath + "/Cancel", ...
    Port="2", Position=[30 128 60 142]);
controlNames = ["Pause","Resume","Selected Trial","Apply"];
for index = 1:numel(controlNames)
    add_block("simulink/Sources/Constant", ...
        blockPath + "/" + controlNames(index), Value="0", ...
        Position=[35, 170 + 42*index, 80, 190 + 42*index]);
end

runtime = blockPath + "/Advanced Runtime";
objectiveExpression = formatObjective(options.ObjectiveFcn);
directionExpression = formatDirections(directions);
seedExpression = formatSeed(options.Seed);
initialSampler = formatSamplerConfig(options.Sampler, seedExpression, ...
    options.Pruner, options.ParameterSpec, options.ModelName);
initialParameters = sprintf('%s,%d,%s,''%s'',%.17g,%d,%s', ...
    objectiveExpression, options.NumTrials, directionExpression, ...
    options.StoragePath, options.SampleTime_s, ...
    options.LiveVisualization, initialSampler);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    runtime, FunctionName="radia_optuna_sfun", ...
    Parameters=initialParameters, ...
    Position=[140 35 350 355]);

add_line(blockPath, "Start/1", "Advanced Runtime/1");
add_line(blockPath, "Cancel/1", "Advanced Runtime/2");
for index = 1:numel(controlNames)
    add_line(blockPath, controlNames(index) + "/1", ...
        "Advanced Runtime/" + (index + 2));
end

outputNames = ["Best","Status","Progress","Best Trial"];
runtimePorts = [1, 3, 13, 2];
for index = 1:numel(outputNames)
    add_block("simulink/Ports & Subsystems/Out1", ...
        blockPath + "/" + outputNames(index), Port=string(index), ...
        Position=[515, 65 + 62*index, 545, 79 + 62*index]);
    add_line(blockPath, "Advanced Runtime/" + runtimePorts(index), ...
        outputNames(index) + "/1");
end

addOptunaMonitorBus(blockPath);

monitorPorts = [1:8, 11:18];
unusedPorts = setdiff(1:18, [runtimePorts, monitorPorts], "stable");
for index = 1:numel(unusedPorts)
    port = unusedPorts(index);
    terminator = "Unused Runtime " + port;
    add_block("simulink/Sinks/Terminator", ...
        blockPath + "/" + terminator, ...
        Position=[430, 20 + 23*index, 450, 40 + 23*index]);
    add_line(blockPath, "Advanced Runtime/" + port, terminator + "/1");
end

mask = Simulink.Mask.create(blockPath);
mask.Description = "Compact MATLAB-native Optuna study. Change the " + ...
    "sampler, seed, pruner, search space, or total trial budget in this " + ...
    "dialog and run again; the MAT study resumes without changing wiring. " + ...
    "OptunaMonitorBusV1 exposes fixed scalar telemetry.";
mask.addParameter(Type="edit", Name="objective_fcn", ...
    Prompt="Objective function", Value=objectiveExpression, Evaluate="on");
mask.addParameter(Type="edit", Name="num_trials", ...
    Prompt="Total trial budget", Value=string(options.NumTrials), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="directions", ...
    Prompt="Objective directions", Value=directionExpression, ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="storage_path", ...
    Prompt="Study MAT file", Value=quoteString(options.StoragePath), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="sample_time_s", ...
    Prompt="Trial sample time (s)", ...
    Value=compose("%.17g", options.SampleTime_s), Evaluate="on");
liveValue = "off";
if options.LiveVisualization
    liveValue = "on";
end
mask.addParameter(Type="checkbox", Name="live_visualization", ...
    Prompt="External MATLAB monitor", Value=liveValue);
mask.addParameter(Type="popup", Name="sampler_name", Prompt="Sampler", ...
    TypeOptions={"auto","random","tpe","cmaes","motpe","nsgaii", ...
    "gp","nsgaiii","bruteforce","qmc"}, Value=options.Sampler);
mask.addParameter(Type="edit", Name="seed", ...
    Prompt="Sampler seed ([] = fresh)", Value=seedExpression, ...
    Evaluate="on");
mask.addParameter(Type="popup", Name="pruner_name", Prompt="Pruner", ...
    TypeOptions={"none","median","hyperband","percentile","patient", ...
    "successivehalving","threshold"}, Value=options.Pruner);
mask.addParameter(Type="edit", Name="parameter_spec", ...
    Prompt="OptimizationParameter array", Value=options.ParameterSpec, ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="model_name", ...
    Prompt="Model to update", Value=quoteString(options.ModelName), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="selected_trial", ...
    Prompt="Trial to apply (-1 = best)", Value="-1", Evaluate="on");
reviewButton = mask.addDialogControl("pushbutton", "review_study");
reviewButton.Prompt = "Review saved study";
reviewButton.Callback = "radia.simulink.reviewOptunaStudy(gcb);";
applyButton = mask.addDialogControl("pushbutton", "apply_trial");
applyButton.Prompt = "Apply selected trial";
applyButton.Callback = ...
    "radia.simulink.applyOptunaTrial(gcb,selected_trial);";
runtimeParameters = ...
    "objective_fcn,num_trials,directions,storage_path," + ...
    "sample_time_s,strcmp(live_visualization,'on')," + ...
    "struct('Name',sampler_name,'Seed',seed,'Pruner',pruner_name," + ...
    "'Parameters',parameter_spec,'ModelName',model_name)";
mask.Initialization = "radia.simulink.makeOptunaMonitorBusObject();" + ...
    "set_param([gcb '/Advanced Runtime']," + ...
    "'Parameters','" + replace(runtimeParameters, "'", "''") + "');";
mask.Display = "disp('Optuna Study');" + ...
    "port_label('input',1,'start');port_label('input',2,'cancel');" + ...
    "port_label('output',1,'best');port_label('output',2,'status');" + ...
    "port_label('output',3,'progress');" + ...
    "port_label('output',4,'best trial');" + ...
    "port_label('output',5,'monitor');";
set_param(blockPath, UserData=struct( ...
    "interface", "compact-student", ...
    "public_inputs", "start,cancel", ...
    "public_outputs", "best,status,progress,best-trial,monitor", ...
    "monitor_bus", "OptunaMonitorBusV1", ...
    "advanced_runtime", "internal-6-input-18-output", ...
    "iteration", "mask-edit;resume-study;review-table;apply-trial", ...
    "session_contract", "radia.optuna.session-snapshot.v1", ...
    "optimizer_backend", "matlab-native", ...
    "pareto_kernel", "required-optuna-mex", ...
    "python_per_trial", false, ...
    "browser_required", false), UserDataPersistent="on");

if options.Save
    save_system(rootName);
end
end

function addOptunaMonitorBus(blockPath)
add_block("simulink/Sources/Constant", ...
    blockPath + "/Monitor Schema Version", ...
    Value="uint16(1)", OutDataTypeStr="uint16", ...
    Position=[365 375 420 405]);
add_block("simulink/Signal Routing/Bus Creator", ...
    blockPath + "/Monitor Header", Inputs="5", ...
    OutDataTypeStr="Bus: RadiaMonitorHeaderV1", ...
    NonVirtualBus="on", Position=[455 355 465 465]);
add_block("simulink/Signal Routing/Bus Creator", ...
    blockPath + "/Monitor Bus", Inputs="13", ...
    OutDataTypeStr="Bus: OptunaMonitorBusV1", ...
    NonVirtualBus="on", Position=[610 330 620 570]);
add_block("simulink/Ports & Subsystems/Out1", ...
    blockPath + "/Monitor", Port="5", ...
    Position=[690 440 720 454]);

headerSources = ["Monitor Schema Version/1", "Advanced Runtime/3", ...
    "Advanced Runtime/6", "Advanced Runtime/18", "Advanced Runtime/14"];
headerNames = ["schema_version", "status_code", "time_s", ...
    "revision", "error_code"];
for index = 1:numel(headerSources)
    line = add_line(blockPath, headerSources(index), ...
        "Monitor Header/" + index);
    set_param(line, "Name", headerNames(index));
end

payloadPorts = [1, 2, 4, 5, 7, 8, 11, 12, 13, 15, 16, 17];
payloadNames = ["best_value", "best_trial", "completed_trials", ...
    "last_value", "best_updated", "pareto_count", ...
    "pareto_revision", "failed_trials", "attempted_trials", ...
    "selected_trial", "pruned_trials", "current_trial"];
line = add_line(blockPath, "Monitor Header/1", "Monitor Bus/1");
set_param(line, "Name", "header");
for index = 1:numel(payloadPorts)
    line = add_line(blockPath, ...
        "Advanced Runtime/" + payloadPorts(index), ...
        "Monitor Bus/" + (index + 1));
    set_param(line, "Name", payloadNames(index));
end
add_line(blockPath, "Monitor Bus/1", "Monitor/1");
end

function [rootName, parentPath] = normalizeParent(parent)
parts = split(parent, "/");
rootName = parts(1);
if numel(parts) > 1
    parentPath = parent;
else
    parentPath = "";
end
end

function path = joinPath(parent, name)
path = parent + "/" + name;
end

function expression = formatDirections(directions)
quoted = '"' + reshape(string(directions), 1, []) + '"';
if isscalar(quoted)
    expression = char(quoted);
else
    expression = char("[" + strjoin(quoted, ",") + "]");
end
end

function expression = formatObjective(value)
value = strtrim(string(value));
if startsWith(value, "@")
    expression = char(value);
else
    expression = char(quoteString(value));
end
end

function expression = quoteString(value)
expression = "'" + replace(string(value), "'", "''") + "'";
end

function expression = formatSeed(value)
if isempty(value)
    expression = "[]";
elseif isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 0 && value == floor(value)
    expression = compose("%.0f", value);
else
    error("radia:simulink:OptunaSeed", ...
        "Seed must be empty or one nonnegative integer.");
end
end

function expression = formatSamplerConfig(name, seed, pruner, ...
        parameters, modelName)
parameters = strtrim(string(parameters));
if strlength(parameters) == 0
    parameters = "[]";
end
expression = "struct('Name'," + quoteString(name) + ",'Seed'," + ...
    seed + ",'Pruner'," + quoteString(pruner) + ...
    ",'Parameters'," + parameters + ",'ModelName'," + ...
    quoteString(modelName) + ")";
end
