function blockPath = buildAdjointOptimizationBlock(modelName, options)
%BUILDADJOINTOPTIMIZATIONBLOCK Add a masked Simulink MMA/SQP block.
arguments
    modelName (1,1) string
    options.RunnerVariable (1,1) string = "radia_adjoint_runner"
    options.Runner = []
    options.Solver (1,1) string ...
        {mustBeMember(options.Solver,["mma","sqp"])} = "mma"
    options.SampleTime_s (1,1) double {mustBePositive}=1
    options.Save (1,1) logical=true
end
if ~isvarname(options.RunnerVariable)
    error("radia:simulink:AdjointRunnerVariable", ...
        "RunnerVariable must be a valid MATLAB variable name.");
end
if ~isempty(options.Runner)
    if ~isa(options.Runner,"radia.topopt.AdjointRunner")
        error("radia:simulink:AdjointRunner", ...
            "Runner must be a radia.topopt.AdjointRunner.");
    end
    options.Runner.setSolver(options.Solver);
    assignin("base",options.RunnerVariable,options.Runner);
end
if ~bdIsLoaded(modelName)
    new_system(modelName);
end
blockPath = modelName + "/Adjoint Topology Optimization";
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    blockPath,FunctionName="radia_adjoint_optimization_sfun", ...
    Parameters=options.RunnerVariable+","+compose("%.17g",options.SampleTime_s), ...
    Position=[180 90 420 190]);
mask = Simulink.Mask.create(blockPath);
mask.Description = "Checked adjoint topology optimization with MMA or analytic-gradient SQP.";
mask.addParameter(Type="edit",Name="runner",Prompt="AdjointRunner", ...
    Value=options.RunnerVariable,Evaluate="on");
solverParameter = mask.addParameter(Type="popup",Name="solver",Prompt="Optimizer", ...
    TypeOptions={"mma","sqp"},Value=options.Solver);
solverParameter.Callback = "runner.setSolver(string(solver));";
mask.addParameter(Type="edit",Name="sample_time_s",Prompt="Sample time (s)", ...
    Value=compose("%.17g",options.SampleTime_s),Evaluate="on");
set_param(blockPath,"Parameters", ...
    "runner,"+compose("%.17g",options.SampleTime_s));
mask.Display = "disp('Adjoint Topology Optimization');" + ...
    "port_label('input',1,'start');" + ...
    "port_label('output',1,'objective');" + ...
    "port_label('output',2,'status');" + ...
    "port_label('output',3,'iterations');" + ...
    "port_label('output',4,'design');";
set_param(blockPath,"UserData",struct( ...
    "domain","topology-optimization", ...
    "backend","matlab-native-adjoint", ...
    "solvers","mma,sqp", ...
    "execution","one-study-per-rising-trigger", ...
    "finite_difference_fallback",false), ...
    "UserDataPersistent","on");
if options.Save
    save_system(modelName);
end
end
