function modelFile = buildRLCResonanceOptimizationDemo(options)
%BUILDRLCRESONANCEOPTIMIZATIONDEMO Build the series-RLC ring-down plant.
arguments
    options.OutputDirectory (1,1) string = radia.simulink.exampleDirectory()
    options.ModelName (1,1) string = "radia_rlc_resonance_plant"
    options.OpenModel (1,1) logical = false
end

if ~isfolder(options.OutputDirectory)
    mkdir(options.OutputDirectory);
end
model = options.ModelName;
modelFile = fullfile(options.OutputDirectory, model + ".slx");
if bdIsLoaded(model)
    close_system(model, 0);
end
if isfile(modelFile)
    delete(modelFile);
end

new_system(model);
cleanup = onCleanup(@() closeIfLoaded(model));
set_param(model, ...
    "Solver", "ode45", ...
    "StopTime", "0.02", ...
    "MaxStep", "2e-5", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "SaveTime", "on", ...
    "TimeSaveName", "tout", ...
    "SaveOutput", "on", ...
    "OutputSaveName", "yout", ...
    "ReturnWorkspaceOutputs", "on", ...
    "PreLoadFcn", "R_ohm=2; L_H=10e-3; C_F=2.5e-6;", ...
    "ModelBrowserVisibility", "off");

add_block("simulink/Sources/Constant", model + "/Zero voltage", ...
    "Value", "0", "Position", [45 135 105 165]);
add_block("simulink/Continuous/State-Space", model + "/Series RLC", ...
    "A", "[-R_ohm/L_H -1/L_H; 1/C_F 0]", ...
    "B", "[1/L_H; 0]", ...
    "C", "[0 1]", ...
    "D", "0", ...
    "X0", "[0; 1]", ...
    "Position", [180 105 350 195]);
add_block("simulink/Ports & Subsystems/Out1", ...
    model + "/capacitor_voltage_V", ...
    "Port", "1", "Position", [555 115 675 135]);
add_block("simulink/Sinks/To Workspace", model + "/Ring voltage", ...
    "VariableName", "ring_voltage", ...
    "SaveFormat", "Timeseries", ...
    "Position", [470 180 585 220]);
add_block("simulink/Sinks/Scope", model + "/Ring-down scope", ...
    "Position", [500 270 535 305]);

add_line(model, "Zero voltage/1", "Series RLC/1");
add_line(model, "Series RLC/1", "capacitor_voltage_V/1");
add_line(model, "Series RLC/1", "Ring voltage/1");
add_line(model, "Series RLC/1", "Ring-down scope/1");

annotationText = "Series RLC ring-down: x = [i; v_C], x(0) = [0; 1]." + ...
    newline + ...
    "C is tuned outside the time-step loop by radia.optuna.SimulinkRunner.";
annotation = Simulink.Annotation(model, char(annotationText));
annotation.Position = [35 25 675 75];
save_system(model, modelFile);
if options.OpenModel
    clear cleanup
    open_system(model);
else
    close_system(model, 0);
    clear cleanup
end
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
