function modelPath = buildIHControlModel(modelName, plant, eddyLut, options)
%BUILDIHCONTROLMODEL Create a sampled IH eddy/thermal Simulink model.
%   radia.simulink.buildIHControlModel(NAME,PLANT,EDDYLUT) creates separate
%   Eddy Current and Thermal subsystems. Eddy Current evaluates the periodic
%   q(theta,current) map at every sample. Its inputs are the RMS carrier-
%   current envelope and mechanical rotation angle; its output is one heat-
%   density value per EDDYLUT region. Thermal integrates those densities
%   over their region volumes before updating its temperature state. The
%   masked IH Parameters block supplies fixed LUT/region parameters; current,
%   rotation angle, and ambient temperature remain external Simulink signals.
%
%   Set IncludePID=true to generate the current envelope from a temperature
%   setpoint. Set PlantBlock="radia-sfunction" to use the Radia-owned
%   Level-2 MATLAB S-function thermal boundary or "radia-mex" to use the
%   persistent native state-space boundary.

arguments
    modelName (1,1) string
    plant (1,1) struct
    eddyLut (1,1) struct
    options.IncludePID (1,1) logical = false
    options.Kp (1,1) double {mustBeFinite} = 1.0
    options.Ki (1,1) double {mustBeFinite} = 0.0
    options.Kd (1,1) double {mustBeFinite} = 0.0
    options.CurrentLowerBound_A (1,1) double {mustBeNonnegative} = 0.0
    options.CurrentUpperBound_A (1,1) double {mustBePositive} = 1.0e4
    options.StopTime_s (1,1) double {mustBePositive} = 10.0
    options.PlantBlock (1,1) string = "standard"
    options.OutputDirectory (1,1) string = ""
    options.Save (1,1) logical = true
    options.Open (1,1) logical = false
end

if exist("new_system", "file") ~= 2 && exist("new_system", "builtin") ~= 5
    error("radia:simulink:MissingSimulink", ...
        "Simulink is required to build the IH control model.");
end
if ~isfield(plant, "schema") || plant.schema ~= "radia.ih.simulink.plant.v1"
    error("radia:simulink:InvalidPlant", "plant is not a Radia IH plant.");
end
if ~isfield(eddyLut, "schema") || ...
        eddyLut.schema ~= "radia.ih.simulink.eddy_heat_density_lut.v1"
    error("radia:simulink:InvalidEddyLUT", ...
        "eddyLut must come from radia.simulink.makeIHEddyHeatDensityLUT.");
end
if options.CurrentUpperBound_A <= options.CurrentLowerBound_A
    error("radia:simulink:CurrentBounds", ...
        "CurrentUpperBound_A must exceed CurrentLowerBound_A.");
end
if ~ismember(options.PlantBlock, ["standard", "radia-sfunction", "radia-mex"])
    error("radia:simulink:PlantBlock", ...
        "PlantBlock must be 'standard', 'radia-sfunction', or 'radia-mex'.");
end
if bdIsLoaded(char(modelName))
    error("radia:simulink:ModelLoaded", ...
        "close the existing model before rebuilding it.");
end

new_system(char(modelName));
set_param(char(modelName), "Solver", "FixedStepDiscrete", ...
    "FixedStep", num2str(plant.sample_time_s, 17), ...
    "StopTime", num2str(options.StopTime_s, 17));

root = string(modelName);
if options.PlantBlock ~= "standard"
    modelWorkspace = get_param(root, "ModelWorkspace");
    assignin(modelWorkspace, "radia_ih_plant", plant);
end
addIHParameterSubsystem(root, plant, eddyLut, options.PlantBlock, ...
    [260 250 445 365]);
addEddyCurrentSubsystem(root, eddyLut, plant.sample_time_s, [500 65 690 170]);
addThermalSubsystem(root, plant, eddyLut, options.PlantBlock, [750 65 940 190]);
add_block("simulink/Signal Routing/Demux", root + "/OutputDemux", ...
    "Outputs", num2str(size(plant.C, 1)), "Position", [985 45 1010 210]);

if options.IncludePID
    add_block("simulink/Math Operations/Sum", root + "/TemperatureError", ...
        "Inputs", "+-", "Position", [130 70 160 110]);
    add_block("simulink/Discrete/Discrete PID Controller", root + "/TemperaturePID", ...
        "P", num2str(options.Kp, 17), "I", num2str(options.Ki, 17), ...
        "D", num2str(options.Kd, 17), ...
        "SampleTime", num2str(plant.sample_time_s, 17), ...
        "Position", [210 60 340 120]);
    add_block("simulink/Discontinuities/Saturation", root + "/CurrentSaturation", ...
        "UpperLimit", num2str(options.CurrentUpperBound_A, 17), ...
        "LowerLimit", num2str(options.CurrentLowerBound_A, 17), ...
        "Position", [370 70 465 110]);
    add_block("simulink/Discrete/Unit Delay", root + "/TemperatureFeedbackDelay", ...
        "InitialCondition", num2str(plant.x0(1), 17), ...
        "SampleTime", num2str(plant.sample_time_s, 17), ...
        "Position", [930 330 1000 370]);
    add_block("simulink/Ports & Subsystems/In1", root + "/temperature_setpoint_K", ...
        "Port", "1", "Position", [25 80 55 100]);
    add_block("simulink/Ports & Subsystems/In1", root + "/rotation_angle_rad", ...
        "Port", "2", "Position", [415 145 445 165]);
    add_block("simulink/Ports & Subsystems/In1", root + "/ambient_temperature_K", ...
        "Port", "3", "Position", [610 220 640 240]);
    add_line(root, "temperature_setpoint_K/1", "TemperatureError/1");
    add_line(root, "TemperatureError/1", "TemperaturePID/1");
    add_line(root, "TemperaturePID/1", "CurrentSaturation/1");
    add_line(root, "CurrentSaturation/1", "Eddy Current/1");
else
    add_block("simulink/Ports & Subsystems/In1", root + "/coil_current_rms_A", ...
        "Port", "1", "Position", [415 85 445 105]);
    add_block("simulink/Ports & Subsystems/In1", root + "/rotation_angle_rad", ...
        "Port", "2", "Position", [415 145 445 165]);
    add_block("simulink/Ports & Subsystems/In1", root + "/ambient_temperature_K", ...
        "Port", "3", "Position", [610 220 640 240]);
    add_line(root, "coil_current_rms_A/1", "Eddy Current/1");
end

add_line(root, "rotation_angle_rad/1", "Eddy Current/2");
add_line(root, "IH Parameters/1", "Eddy Current/3", "autorouting", "smart");
add_line(root, "IH Parameters/2", "Eddy Current/4", "autorouting", "smart");
add_line(root, "Eddy Current/1", "Thermal/1");
add_line(root, "ambient_temperature_K/1", "Thermal/2");
add_line(root, "IH Parameters/3", "Thermal/3", "autorouting", "smart");
add_line(root, "Thermal/1", "OutputDemux/1");
for k = 1:size(plant.C, 1)
    name = char(plant.output_names(k));
    blockName = matlab.lang.makeValidName(name);
    add_block("simulink/Ports & Subsystems/Out1", root + "/" + blockName, ...
        "Port", num2str(k), "Position", [1100 35 + 50 * k 1180 55 + 50 * k]);
    add_line(root, "OutputDemux/" + k, blockName + "/1");
    set_param(root + "/" + blockName, "Name", name);
end
heatDensityPort = size(plant.C, 1) + 1;
add_block("simulink/Ports & Subsystems/Out1", ...
    root + "/heat_density_W_per_m3", "Port", num2str(heatDensityPort), ...
    "Position", [750 265 860 285]);
add_line(root, "Eddy Current/1", "heat_density_W_per_m3/1", ...
    "autorouting", "smart");

if options.IncludePID
    add_line(root, "OutputDemux/1", "TemperatureFeedbackDelay/1", ...
        "autorouting", "smart");
    add_line(root, "TemperatureFeedbackDelay/1", "TemperatureError/2", ...
        "autorouting", "smart");
end

set_param(root, "ModelBrowserVisibility", "off");
if options.Open
    open_system(root);
end
if options.Save
    outputDirectory = options.OutputDirectory;
    if strlength(outputDirectory) == 0
        if ispc
            outputDirectory = fullfile("C:\temp", "radia_ih_models");
        else
            outputDirectory = fullfile(tempdir, "radia_ih_models");
        end
    end
    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end
    modelPath = string(fullfile(outputDirectory, modelName + ".slx"));
    save_system(root, modelPath);
else
    modelPath = "";
end
end

function path = addIHParameterSubsystem(root, plant, lut, plantBlock, position)
path = root + "/IH Parameters";
add_block("simulink/Ports & Subsystems/Subsystem", path, "Position", position);
delete_line(path, "In1/1", "Out1/1");
delete_block(path + "/In1");
delete_block(path + "/Out1");

add_block("simulink/Sources/Constant", path + "/AngleOrigin", ...
    "Value", "angle_origin_rad", "Position", [35 35 125 65]);
add_block("simulink/Sources/Constant", path + "/AnglePeriod", ...
    "Value", "angle_period_rad", "Position", [35 90 125 120]);
add_block("simulink/Sources/Constant", path + "/RegionVolumes", ...
    "Value", "region_volumes_m3", "Position", [35 145 125 175]);
add_block("simulink/Ports & Subsystems/Out1", path + "/angle_origin_rad", ...
    "Port", "1", "Position", [185 40 215 60]);
add_block("simulink/Ports & Subsystems/Out1", path + "/angle_period_rad", ...
    "Port", "2", "Position", [185 95 215 115]);
add_block("simulink/Ports & Subsystems/Out1", path + "/region_volumes_m3", ...
    "Port", "3", "Position", [185 150 215 170]);
add_line(path, "AngleOrigin/1", "angle_origin_rad/1");
add_line(path, "AnglePeriod/1", "angle_period_rad/1");
add_line(path, "RegionVolumes/1", "region_volumes_m3/1");

mask = Simulink.Mask.create(path);
mask.Description = ...
    "Fixed IH model parameters. Current, rotation angle, and ambient " + ...
    "temperature remain external Simulink signals.";
mask.addParameter(Type="edit", Name="angle_origin_rad", ...
    Prompt="Angle origin (rad)", Value=num2str(lut.angle_origin_rad, 17), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="angle_period_rad", ...
    Prompt="Angle period (rad)", Value=num2str(lut.angle_period_rad, 17), ...
    Evaluate="on");
mask.addParameter(Type="edit", Name="region_volumes_m3", ...
    Prompt="Region volumes (m^3)", Value=mat2str(lut.region_volumes_m3(:), 17), ...
    Evaluate="on");
sampleTimeParameter = mask.addParameter(Type="edit", Name="sample_time_s", ...
    Prompt="Sample time (s)", Value=num2str(plant.sample_time_s, 17), ...
    Evaluate="off");
sampleTimeParameter.Enabled = "off";
carrierParameter = mask.addParameter(Type="edit", Name="carrier_frequency_Hz", ...
    Prompt="Carrier frequency (Hz)", Value=num2str(lut.carrier_frequency_Hz, 17), ...
    Evaluate="off");
carrierParameter.Enabled = "off";
backendParameter = mask.addParameter(Type="edit", Name="thermal_backend", ...
    Prompt="Thermal backend", Value=char(plantBlock), Evaluate="off");
backendParameter.Enabled = "off";
regionsParameter = mask.addParameter(Type="edit", Name="region_names", ...
    Prompt="Heated regions", Value=strjoin(cellstr(lut.region_names(:)), ", "), ...
    Evaluate="off");
regionsParameter.Enabled = "off";
mask.Display = "disp('IH Parameters');" + ...
    "port_label('output',1,'theta_0');" + ...
    "port_label('output',2,'period');" + ...
    "port_label('output',3,'V');";
end

function path = addEddyCurrentSubsystem(root, lut, sampleTime_s, position)
path = root + "/Eddy Current";
add_block("simulink/Ports & Subsystems/Subsystem", path, "Position", position);
delete_line(path, "In1/1", "Out1/1");
delete_block(path + "/In1");
delete_block(path + "/Out1");

add_block("simulink/Ports & Subsystems/In1", path + "/coil_current_rms_A", ...
    "Port", "1", "Position", [25 45 55 65]);
add_block("simulink/Ports & Subsystems/In1", path + "/rotation_angle_rad", ...
    "Port", "2", "Position", [25 115 55 135]);
add_block("simulink/Ports & Subsystems/In1", path + "/angle_origin_rad", ...
    "Port", "3", "Position", [25 175 55 195]);
add_block("simulink/Ports & Subsystems/In1", path + "/angle_period_rad", ...
    "Port", "4", "Position", [25 225 55 245]);
add_block("simulink/Math Operations/Abs", path + "/CurrentMagnitude", ...
    "Position", [90 40 125 70]);
add_block("simulink/Math Operations/Sum", path + "/SubtractAngleOrigin", ...
    "Inputs", "+-", "Position", [90 105 120 145]);
add_block("simulink/Discrete/Unit Delay", path + "/PreviousRotationAngle", ...
    "InitialCondition", "0", ...
    "SampleTime", num2str(sampleTime_s, 17), ...
    "Position", [160 105 225 145]);
add_block("simulink/Math Operations/Math Function", path + "/WrapAngle", ...
    "Operator", "mod", "Position", [270 105 315 145]);
add_block("simulink/Math Operations/Sum", path + "/RestoreAngleOrigin", ...
    "Inputs", "++", "Position", [360 105 390 145]);
add_line(path, "coil_current_rms_A/1", "CurrentMagnitude/1");
add_line(path, "rotation_angle_rad/1", "SubtractAngleOrigin/1");
add_line(path, "angle_origin_rad/1", "SubtractAngleOrigin/2");
add_line(path, "SubtractAngleOrigin/1", "PreviousRotationAngle/1");
add_line(path, "PreviousRotationAngle/1", "WrapAngle/1");
add_line(path, "angle_period_rad/1", "WrapAngle/2");
add_line(path, "WrapAngle/1", "RestoreAngleOrigin/1");
add_line(path, "angle_origin_rad/1", "RestoreAngleOrigin/2");

lookupOutputs = strings(lut.region_count, 1);
for region = 1:lut.region_count
    lookupName = "HeatDensity_" + string(region);
    lookupPath = path + "/" + lookupName;
    y0 = 25 + 95 * (region - 1);
    add_block("simulink/Lookup Tables/2-D Lookup Table", lookupPath, ...
        "BreakpointsForDimension1", ...
        mat2str(lut.rotation_angle_breakpoints_rad(:).', 17), ...
        "BreakpointsForDimension2", ...
        mat2str(lut.coil_current_rms_breakpoints_A(:).', 17), ...
        "Table", mat2str(lut.table_heat_density_W_per_m3(:, :, region), 17), ...
        "InterpMethod", "Linear point-slope", "ExtrapMethod", "Clip", ...
        "Position", [455 y0 605 y0 + 60]);
    add_line(path, "RestoreAngleOrigin/1", lookupName + "/1");
    add_line(path, "CurrentMagnitude/1", lookupName + "/2");
    lookupOutputs(region) = lookupName + "/1";
end

if lut.region_count == 1
    outputSource = lookupOutputs(1);
else
    add_block("simulink/Signal Routing/Mux", path + "/RegionMux", ...
        "Inputs", num2str(lut.region_count), ...
        "Position", [655 30 680 55 + 95 * (lut.region_count - 1)]);
    for region = 1:lut.region_count
        add_line(path, lookupOutputs(region), "RegionMux/" + region);
    end
    outputSource = "RegionMux/1";
end
add_block("simulink/Ports & Subsystems/Out1", ...
    path + "/heat_density_W_per_m3", "Port", "1", ...
    "Position", [740 70 770 90]);
add_line(path, outputSource, "heat_density_W_per_m3/1");

mask = Simulink.Mask.create(path);
mask.Description = ...
    "Periodic Radia heat-density map. At sample k it combines the current " + ...
    "RMS carrier-current envelope with rotation angle k-1 and outputs one " + ...
    "W/m^3 value per heated region.";
mask.Display = "disp('Eddy Current');" + ...
    "port_label('input',1,'I_{rms}');" + ...
    "port_label('input',2,'theta');" + ...
    "port_label('input',3,'theta_0');" + ...
    "port_label('input',4,'period');" + ...
    "port_label('output',1,'q');";
end

function path = addThermalSubsystem(root, plant, ~, plantBlock, position)
path = root + "/Thermal";
add_block("simulink/Ports & Subsystems/Subsystem", path, "Position", position);
delete_line(path, "In1/1", "Out1/1");
delete_block(path + "/In1");
delete_block(path + "/Out1");

add_block("simulink/Ports & Subsystems/In1", path + "/heat_density_W_per_m3", ...
    "Port", "1", "Position", [25 45 55 65]);
add_block("simulink/Ports & Subsystems/In1", path + "/ambient_temperature_K", ...
    "Port", "2", "Position", [25 105 55 125]);
add_block("simulink/Ports & Subsystems/In1", path + "/region_volumes_m3", ...
    "Port", "3", "Position", [25 165 55 185]);
add_block("simulink/Math Operations/Dot Product", path + "/IntegrateDensity", ...
    "Position", [100 35 145 75]);
add_block("simulink/Signal Routing/Mux", path + "/ThermalInputMux", ...
    "Inputs", "2", "Position", [180 40 205 130]);

plantPath = path + "/ThermalPlant";
if plantBlock == "standard"
    add_block("simulink/Discrete/Discrete State-Space", plantPath, ...
        "A", mat2str(plant.A, 17), "B", mat2str(plant.B, 17), ...
        "C", mat2str(plant.C, 17), "D", mat2str(plant.D, 17), ...
        "X0", mat2str(plant.x0, 17), ...
        "SampleTime", num2str(plant.sample_time_s, 17), ...
        "Position", [255 35 435 135]);
elseif plantBlock == "radia-sfunction"
    add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
        plantPath, "FunctionName", "radia_ih_plant_sfunction", ...
        "Parameters", "radia_ih_plant", "Position", [255 35 435 135]);
else
    add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
        plantPath, "FunctionName", "radia_state_space_mex_sfunction", ...
        "Parameters", "radia_ih_plant", "Position", [255 35 435 135]);
end
add_block("simulink/Ports & Subsystems/Out1", path + "/thermal_outputs", ...
    "Port", "1", "Position", [490 75 520 95]);
add_line(path, "heat_density_W_per_m3/1", "IntegrateDensity/1");
add_line(path, "region_volumes_m3/1", "IntegrateDensity/2");
add_line(path, "IntegrateDensity/1", "ThermalInputMux/1");
add_line(path, "ambient_temperature_K/1", "ThermalInputMux/2");
add_line(path, "ThermalInputMux/1", "ThermalPlant/1");
add_line(path, "ThermalPlant/1", "thermal_outputs/1");

mask = Simulink.Mask.create(path);
mask.Description = ...
    "Lumped thermal state model. Region heat densities are integrated over " + ...
    "their volumes here; this subsystem alone owns temperature and energy state.";
mask.Display = "disp('Thermal');" + ...
    "port_label('input',1,'q');" + ...
    "port_label('input',2,'T_{amb}');" + ...
    "port_label('input',3,'V');" + ...
    "port_label('output',1,'thermal');";
end
