function libraryPath=buildLibrary(options)
%BUILDLIBRARY Build the single distributable Radia Simulink block library.
arguments, options.OutputDirectory (1,1) string=""; end
radia.simulink.requireIHNativeRuntime();
matlabRoot=fileparts(fileparts(fileparts(mfilename("fullpath"))));
if strlength(options.OutputDirectory)==0,options.OutputDirectory=matlabRoot;end
if ~isfolder(options.OutputDirectory),mkdir(options.OutputDirectory);end
name="radia_simulink_library"; libraryPath=fullfile(options.OutputDirectory,name+".slx");
if bdIsLoaded(name),close_system(name,0);end
assignin("base","radia_ih_config",radia.simulink.makeIHNativeSmokeConfig());
assignin("base","radia_nonlinear_reactor_config", ...
    radia.simulink.makeNonlinearReactorDemoConfig());
assignin("base","radia_bh_config",struct("mode","formula", ...
    "reference_temperature_K",293.15,"mu_r_ref",1,"mu_r_temperature_slope",0));
defaultMaterials=struct("air",radia.simulink.makeMaterialSpec());
defaultRegions=struct("air","air");
defaultMaterialContract=radia.simulink.compileMaterialDictionary( ...
    defaultMaterials,RegionMaterials=defaultRegions);
assignin("base","radia_materials",defaultMaterials);
assignin("base","radia_region_materials",defaultRegions);
assignin("base","radia_material_contract",defaultMaterialContract);
assignin("base","radia_material_bus",defaultMaterialContract.runtime);
radia.simulink.makeMaterialBusObject(defaultMaterialContract.runtime, ...
    Name="RadiaMaterialBus");
defaultWindings=struct("winding",radia.simulink.makeWindingSpec( ...
    Regions="air",Turns=1));
defaultWindingContract=radia.simulink.compileWindingDictionary( ...
    defaultWindings,defaultMaterialContract);
assignin("base","radia_windings",defaultWindings);
assignin("base","radia_winding_contract",defaultWindingContract);
assignin("base","radia_winding_bus",defaultWindingContract.runtime);
radia.simulink.makeWindingBusObject(defaultWindingContract.runtime, ...
    Name="RadiaWindingBus");
radia.simulink.makeElectromechanicalBusObjects();
defaultStudyRuntime=struct("schema_version",uint16(1), ...
    "physics_code",uint16(0),"formulation_code",uint16(0), ...
    "element_order",uint16(1),"frequency_Hz",0,"model_depth_m",1, ...
    "boundary_count",uint16(0),"boundary_id",zeros(64,1,"uint32"), ...
    "boundary_kind",zeros(64,1,"uint16"), ...
    "boundary_value_real",zeros(64,1),"boundary_value_imag",zeros(64,1), ...
    "robin_transfer_W_per_m2K",zeros(64,1),"robin_ambient_K",zeros(64,1));
defaultStudyRuntime.time_sample_count=uint16(0);
defaultStudyRuntime.theta=1;
defaultStudyRuntime.initial_temperature_K=293.15;
defaultStudyRuntime.conductor_count=uint16(0);
defaultStudyRuntime.force_boundary_count=uint16(0);
assignin("base","radia_field_study_bus",defaultStudyRuntime);
radia.simulink.makeFieldStudyBusObject(defaultStudyRuntime,Name="RadiaStudyBus");
assignin("base","radia_adjoint_runner", ...
    radia.topopt.makeAdjointDemoRunner());
assignin("base","radia_electromagnet_adjoint_runner", ...
    radia.topopt.makeElectromagnetReferenceRunner());
assignin("base","radia_streamfunction_adjoint_runner", ...
    radia.topopt.makeStreamFunctionAdjointDemoRunner());
motorGrid=[0;pi];
motorA=reshape([1.0,0.5],1,1,2);
motorB=reshape([1.0,3.0],1,1,2);
motorC=reshape([1.0,3.0],1,1,2);
motorD=zeros(1,1,2);
motorQ=reshape([2.0,4.0],1,1,2);
motorR=reshape([1.0,2.0],1,1,2);
motorS=reshape([0.0,2.0],1,1,2);
assignin("base","radia_motor_angle_family", ...
    radia.simulink.makeMotorAngleFamily( ...
    motorGrid,motorA,motorB,motorC,motorD,motorQ,motorR,motorS,2.0));
new_system(name,"Library");
applications=addEmptySubsystem(name,"Applications",[70 40 410 285]);
addApplicationBlock(applications,"Electromagnet","em",[45 30 345 80]);
radia.simulink.addElectromagnetOptimizationSubsystem(applications, ...
    "Electromagnet Topology Optimization",[45 100 375 190]);
addApplicationBlock(applications,"PCB PEEC","pcb",[45 220 345 270]);
addApplicationBlock(applications,"Motor","motor",[45 290 345 340]);
addApplicationBlock(applications,"Stream Function","streamfunction", ...
    [45 360 345 410]);
addIHNativeBlock(applications,"Induction Heating",[45 430 345 480]);
radia.simulink.addStreamFunctionOptimizationSubsystem(applications, ...
    "Stream Function Optimization",[45 500 345 590]);
radia.simulink.addMagLevCLNBlock(applications, ...
    BlockName="Magnetic Levitation",Position=[45 620 345 690], ...
    FamilyExpression="radia.simulink.makeMagLevSmokeFamily()");
addApplicationBlock(applications,"Field Study","field",[45 720 345 770]);

materials=addEmptySubsystem(name,"Material Models",[70 570 330 660]);
addBHBlock(materials,"Temperature-Dependent BH",[45 35 285 105]);
addMaterialDatabaseBlock(materials,"Material Database",[45 125 285 195]);
addMaterialDictionaryBlock(materials,"Material Dictionary",[45 215 285 285]);

utilities=addEmptySubsystem(name,"Utilities",[470 570 730 660]);
% Reduce a distributed field port (temperature / heat density) to
% [min mean max] before wiring it to a scope; a raw N-wide vector with
% thousands of DOFs is unreadable on a scope.
radia.simulink.addFieldStatsBlock(utilities,BlockName="Field Stats", ...
    Position=[45 35 285 105]);

addEmptySubsystem(name,"LTspice",[70 305 310 405]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",name+"/LTspice/LTspice Circuit", ...
 "FunctionName","radia_ltspice_sfun","Parameters","'', {'control'}, {'V(out)'}, 1e-3, 'C:\temp\radia_ltspice_block', inf, 300, ''",Position=[45 35 200 85]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",name+"/LTspice/Hysteretic LTspice Plant", ...
 "FunctionName","radia_hysteretic_ltspice_sfun","Parameters","'', 1e-3, 'C:\temp\radia_hysteretic_ltspice_block'",Position=[45 105 200 155]);
coupling=addEmptySubsystem(name,"Coupling",[470 305 730 405]);
addWindingDictionaryBlock(coupling,"Winding Dictionary",[45 35 285 105]);
addFieldStudyBlock(coupling,"Field Study Configuration",[45 125 285 195]);
reducedModels=addEmptySubsystem(name,"Reduced Models",[470 435 760 535]);
addMotorAngleFamilyLibraryBlock(reducedModels,"Motor Angle Family", ...
    [45 35 285 105]);
radia.simulink.addNonlinearReactorBlock(reducedModels, ...
    BlockName="Nonlinear HDiv-MMM Reactor",Position=[45 135 315 235]);
optimization=addEmptySubsystem(name,"Optimization",[70 435 430 560]);
addOptunaLibraryBlock(optimization,"Optuna Optimization",[45 35 240 105]);
addSheetMetalLibraryBlock(optimization,"Sheet Metal Optimization", ...
    [45 135 240 205]);
addAdjointLibraryBlock(optimization,"Adjoint Topology Optimization", ...
    [45 235 240 305]);
radia.simulink.addOptunaMonitor(optimization,"Optuna Monitor", ...
    [300 25 530 205]);
set_param(name,"Lock","on"); save_system(name,libraryPath); close_system(name,0);
end

function path=addEmptySubsystem(parent,name,position)
path=parent+"/"+name;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1");
delete_block(path+"/Out1");
end

function addApplicationBlock(parent,label,application,position)
path=parent+"/"+label;
parameters="'"+application+"', config_file, run_root, timeout_s, python_executable";
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",path, ...
    FunctionName="radia_application_sfun", ...
    Parameters="'"+application+"', '', 'C:\temp\radia_simulink', 3600, 'python'", ...
    Position=position,ShowName="off");
mask=Simulink.Mask.create(path);
mask.Description=label+" batch analysis. Create settings with radia.simulink.writeApplicationConfig; a rising trigger executes the validated Radia headless CLI once.";
mask.addParameter(Type="edit",Name="config_file", ...
    Prompt="Configuration JSON",Value="''",Evaluate="on");
mask.addParameter(Type="edit",Name="run_root", ...
    Prompt="Run artifact root", ...
    Value="'C:\temp\radia_simulink'",Evaluate="on");
mask.addParameter(Type="edit",Name="timeout_s", ...
    Prompt="Timeout (s)",Value="3600",Evaluate="on");
mask.addParameter(Type="edit",Name="python_executable", ...
    Prompt="Python executable",Value="'python'",Evaluate="on");
mask.Display="disp('"+label+"');" + ...
    "port_label('input',1,'run');" + ...
    "port_label('output',1,'status');" + ...
    "port_label('output',2,'primary');" + ...
    "port_label('output',3,'elapsed_s');";
set_param(path,"Parameters",parameters);
end

function addMotorAngleFamilyLibraryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    path,FunctionName="radia_motor_angle_family_mex_sfunction", ...
    Parameters="radia_motor_angle_family",Position=position,ShowName="off");
mask=Simulink.Mask.create(path);
mask.Description="Periodic motor ROM with native MEX interpolation, state update, and torque evaluation.";
mask.addParameter(Type="edit",Name="family", ...
    Prompt="Motor angle family",Value="radia_motor_angle_family", ...
    Evaluate="on");
set_param(path,"Parameters","family");
mask.Display="disp('Motor Angle Family');" + ...
    "port_label('input',1,'theta,u');" + ...
    "port_label('output',1,'y,torque');";
set_param(path,"UserData",struct( ...
    "backend","native-mex-periodic-interpolation", ...
    "state_lifecycle","outputs-read;update-advance", ...
    "sim_state","custom-snapshot-restore", ...
    "python_per_step",false),"UserDataPersistent","on");
end

function addOptunaLibraryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",path, ...
    FunctionName="radia_optuna_sfun", ...
    Parameters="'',20,'minimize','',1,false,'auto'",Position=position);
mask=Simulink.Mask.create(path);
mask.Description="Native MATLAB CAE study with cancel, failure telemetry, and automatic MEX acceleration.";
mask.addParameter(Type="edit",Name="objective_fcn", ...
    Prompt="Objective function",Value="''",Evaluate="on");
addOptunaMaskParameters(mask);
set_param(path,Parameters= ...
    "objective_fcn,num_trials,directions,storage_path,sample_time_s," + ...
    "strcmp(live_visualization,'on'),sampler_name");
mask.Display=optunaMaskDisplay(label);
set_param(path,UserData=struct("execution","one-trial-per-sample", ...
    "visualization","simulink-monitor","browser_required",false, ...
    "optimizer_backend","matlab-native", ...
    "pareto_kernel","auto-mex-with-matlab-fallback", ...
    "cae_failure_policy","record-and-continue", ...
    "python_per_trial",false), ...
    UserDataPersistent="on");
end

function addSheetMetalLibraryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",path, ...
    FunctionName="radia_optuna_sfun", ...
    Parameters="'',20,'minimize','',1,false,'auto'",Position=position);
mask=Simulink.Mask.create(path);
mask.Description="Native NGSolve/Cubit sheet-metal optimization through radia.optuna.SheetMetalRunner.";
mask.addParameter(Type="edit",Name="runner",Prompt="SheetMetalRunner", ...
    Value="radia_sheet_metal_runner",Evaluate="on");
addOptunaMaskParameters(mask);
set_param(path,Parameters= ...
    "@(trial)runner.evaluate(trial),num_trials,directions,storage_path," + ...
    "sample_time_s,strcmp(live_visualization,'on'),sampler_name");
mask.Display=optunaMaskDisplay(label);
set_param(path,UserData=struct("domain","sheet-metal", ...
    "backend","matlab-native-ngsolve-cubit", ...
    "runner","radia.optuna.SheetMetalRunner", ...
    "execution","one-trial-per-sample", ...
    "visualization","simulink-monitor", ...
    "pareto_kernel","auto-mex-with-matlab-fallback", ...
    "cae_failure_policy","record-and-continue", ...
    "python_per_trial",false, ...
    "browser_required",false),UserDataPersistent="on");
end

function addAdjointLibraryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",path, ...
    FunctionName="radia_adjoint_optimization_sfun", ...
    Parameters="radia_adjoint_runner,1",Position=position);
mask=Simulink.Mask.create(path);
mask.Description="Checked adjoint topology optimization through the MMA/SQP runner.";
mask.addParameter(Type="edit",Name="runner",Prompt="AdjointRunner", ...
    Value="radia_adjoint_runner",Evaluate="on");
solverParameter=mask.addParameter(Type="popup",Name="solver",Prompt="Optimizer", ...
    TypeOptions={"mma","sqp"},Value="mma");
solverParameter.Callback="runner.setSolver(string(solver));";
mask.addParameter(Type="edit",Name="sample_time_s",Prompt="Sample time (s)", ...
    Value="1",Evaluate="on");
set_param(path,"Parameters","runner,sample_time_s");
mask.Display="disp('Adjoint Topology Optimization');" + ...
    "port_label('input',1,'start');" + ...
    "port_label('output',1,'objective');" + ...
    "port_label('output',2,'status');" + ...
    "port_label('output',3,'iterations');" + ...
    "port_label('output',4,'design');";
set_param(path,"UserData",struct("domain","topology-optimization", ...
    "backend","matlab-native-adjoint","solvers","mma,sqp", ...
    "execution","one-study-per-rising-trigger", ...
    "finite_difference_fallback",false),"UserDataPersistent","on");
end

function addOptunaMaskParameters(mask)
mask.addParameter(Type="edit",Name="num_trials", ...
    Prompt="Number of trials",Value="20",Evaluate="on");
mask.addParameter(Type="edit",Name="directions", ...
    Prompt="Objective directions",Value="'minimize'",Evaluate="on");
mask.addParameter(Type="edit",Name="storage_path", ...
    Prompt="Study MAT file",Value="''",Evaluate="on");
mask.addParameter(Type="edit",Name="sample_time_s", ...
    Prompt="Trial sample time (s)",Value="1",Evaluate="on");
mask.addParameter(Type="checkbox",Name="live_visualization", ...
    Prompt="External MATLAB monitor",Value="off");
mask.addParameter(Type="popup",Name="sampler_name",Prompt="Sampler", ...
    TypeOptions={"auto","random","tpe","cmaes","motpe","nsgaii"}, ...
    Value="auto");
end

function display=optunaMaskDisplay(label)
display="disp('"+label+"');" + ...
    "port_label('input',1,'start');" + ...
    "port_label('input',2,'cancel');" + ...
    "port_label('output',1,'best');port_label('output',2,'best trial');" + ...
    "port_label('output',3,'status');port_label('output',4,'trials');" + ...
    "port_label('output',5,'last');port_label('output',6,'elapsed');" + ...
    "port_label('output',7,'best update');port_label('output',8,'pareto N');" + ...
    "port_label('output',9,'pareto X');port_label('output',10,'pareto Y');" + ...
    "port_label('output',11,'pareto rev');" + ...
    "port_label('output',12,'failed');port_label('output',13,'attempted');" + ...
    "port_label('output',14,'failure code');";
end

function addBHBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function",path, ...
    "FunctionName","radia_bh_sfun","Parameters","radia_bh_config", ...
    Position=position,ShowName="off");
mask=Simulink.Mask.create(path);
mask.Description="Temperature-dependent BH law. Select formula or LUT in radia_bh_config.";
mask.addParameter(Type="edit",Name="mode",Prompt="BH mode",Value="'formula'",Evaluate="on");
mask.addParameter(Type="edit",Name="config_file",Prompt="BH configuration",Value="''",Evaluate="on");
mask.Initialization = ...
    "cfg=evalin('base','radia_bh_config');" + ...
    "if ~isempty(config_file),s=load(config_file);" + ...
    "if isfield(s,'config'),cfg=s.config;elseif isfield(s,'radia_bh_config'),cfg=s.radia_bh_config;else,error('BH config file must contain config or radia_bh_config.');end;end;" + ...
    "cfg.mode=mode;assignin('base','radia_bh_config',cfg);";
mask.Display="disp('Temperature-Dependent BH');" + ...
    "port_label('input',1,'T');" + "port_label('input',2,'H');" + ...
    "port_label('output',1,'B');" + "port_label('output',2,'dB/dH');";
set_param(path,"UserData",struct("backend","matlab-sfunction", ...
    "config_source","radia_bh_config","supports","formula,lut"), ...
    "UserDataPersistent","on");
end

function addMaterialDatabaseBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1"); delete_block(path+"/Out1");
mask=Simulink.Mask.create(path);
mask.Description="Construct and register the immutable workpiece-coordinate MaterialDatabase.";
mask.addParameter(Type="edit",Name="database_file",Prompt="MaterialDatabase MAT/JSON",Value="''",Evaluate="on");
mask.addParameter(Type="edit",Name="material_id",Prompt="Material ID",Value="'default'",Evaluate="on");
mask.Initialization = ...
    "if isempty(database_file),error('Material Database requires database_file.');end;" + ...
    "[~,~,ext]=fileparts(database_file);" + ...
    "if strcmpi(ext,'.mat'),s=load(database_file);" + ...
    "if isfield(s,'database'),db=s.database;elseif isfield(s,'radia_material_database'),db=s.radia_material_database;else,error('MAT file must contain database.');end;" + ...
    "else,db=jsondecode(fileread(database_file));end;" + ...
    "db.material_id=material_id;db=radia.material.validateDatabase(db);" + ...
    "assignin('base','radia_material_database',db);";
mask.Display="disp('Material Database');";
set_param(path,"UserData",struct("schema","radia.material.database.v1", ...
    "coordinate_system","workpiece","shared_variable","radia_material_database", ...
    "wired_ports",false),"UserDataPersistent","on");
end

function addMaterialDictionaryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1"); delete_block(path+"/Out1");
add_block("simulink/Sources/Constant",path+"/Compiled Material Bus", ...
    "Value","radia_material_bus","OutDataTypeStr","Bus: RadiaMaterialBus", ...
    "SampleTime","inf","Position",[45 45 190 85]);
add_block("simulink/Ports & Subsystems/Out1",path+"/materials", ...
    "Port","1","Position",[250 55 280 75]);
add_line(path,"Compiled Material Bus/1","materials/1");
radia.simulink.configureMaterialDictionaryBlock(path);
end

function addWindingDictionaryBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1"); delete_block(path+"/Out1");
add_block("simulink/Sources/Constant",path+"/Compiled Winding Bus", ...
    "Value","radia_winding_bus","OutDataTypeStr","Bus: RadiaWindingBus", ...
    "SampleTime","inf","Position",[45 45 190 85]);
add_block("simulink/Ports & Subsystems/Out1",path+"/windings", ...
    "Port","1","Position",[250 55 280 75]);
add_line(path,"Compiled Winding Bus/1","windings/1");
radia.simulink.configureWindingDictionaryBlock(path);
end

function addFieldStudyBlock(parent,label,position)
path=parent+"/"+label;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1"); delete_block(path+"/Out1");
add_block("simulink/Sources/Constant",path+"/Compiled Study Bus", ...
    "Value","radia_field_study_bus","OutDataTypeStr","Bus: RadiaStudyBus", ...
    "SampleTime","inf","Position",[45 45 190 85]);
add_block("simulink/Ports & Subsystems/Out1",path+"/study", ...
    "Port","1","Position",[250 55 280 75]);
add_line(path,"Compiled Study Bus/1","study/1");
radia.simulink.configureFieldStudyBlock(path);
end

function addIHNativeBlock(parent,label,position)
% Add the native IH preview boundary. IH does not use the generic Python
% application runner: its Eddy and Thermal states live in native MEX
% S-Functions and share one checked configuration contract.
path=parent+"/"+label;
add_block("simulink/Ports & Subsystems/Subsystem",path,Position=position);
delete_line(path,"In1/1","Out1/1");
delete_block(path+"/In1");
delete_block(path+"/Out1");

add_block("simulink/Ports & Subsystems/In1",path+"/coil_current_A", ...
    "Port","1","Position",[25 45 55 65]);
add_block("simulink/Ports & Subsystems/In1",path+"/workpiece_angle_rad", ...
    "Port","2","Position",[25 105 55 125]);
add_block("simulink/Ports & Subsystems/In1",path+"/ambient_temperature_K", ...
    "Port","3","Position",[25 165 55 185]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    path+"/Eddy Level-2 S-Function", ...
    "FunctionName","radia_ih_eddy_sfun", ...
    "Parameters","radia_ih_config", ...
    "Position",[105 35 285 90]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    path+"/Thermal Level-2 S-Function", ...
    "FunctionName","radia_ih_thermal_sfun", ...
    "Parameters","radia_ih_config", ...
    "Position",[355 75 535 130]);
add_block("simulink/Ports & Subsystems/Out1",path+"/heat_density_W_per_m3", ...
    "Port","1","Position",[590 40 620 60]);
add_block("simulink/Ports & Subsystems/Out1",path+"/temperature_K", ...
    "Port","2","Position",[590 105 620 125]);

add_line(path,"coil_current_A/1","Eddy Level-2 S-Function/1");
add_line(path,"workpiece_angle_rad/1","Eddy Level-2 S-Function/2");
add_line(path,"ambient_temperature_K/1","Thermal Level-2 S-Function/2");
add_line(path,"workpiece_angle_rad/1","Thermal Level-2 S-Function/3");
add_line(path,"Eddy Level-2 S-Function/1","heat_density_W_per_m3/1");
add_line(path,"Eddy Level-2 S-Function/1","Thermal Level-2 S-Function/1");
add_line(path,"Thermal Level-2 S-Function/1","temperature_K/1");
add_line(path,"Thermal Level-2 S-Function/1","Eddy Level-2 S-Function/3");

mask=Simulink.Mask.create(path);
mask.Description="Native IH preview block. Readable Level-2 MATLAB Eddy and Thermal S-Functions use checked radia_mex handles and require preassembled operators.";
configParameter=mask.addParameter(Type="edit",Name="config_file", ...
    Prompt="IHDesignSpec configuration",Value="",Evaluate="off");
% Thin callback: the .slx stores only a named .m entry point (mask
% callbacks run in the base workspace where bare mask variables do not
% exist; inline callback code is invisible to diffs).
configParameter.Callback = "radia.simulink.onIHConfigFileChanged(gcb);";
mask.Display="disp('Induction Heating');" + ...
    "port_label('input',1,'I');" + ...
    "port_label('input',2,'theta_{work}');" + ...
    "port_label('input',3,'T_{amb}');" + ...
    "port_label('output',1,'q');" + ...
    "port_label('output',2,'T');";
set_param(path,"UserData",struct("backend","matlab-level2+radia-mex-handles", ...
    "release_channel","preview", ...
    "operator_assembly","preassembled", ...
    "config_source","IHDesignSpec","python_fallback",false, ...
    "distributed_field",true,"surrogate",false, ...
    "temperature_feedback","previous-accepted-thermal-state", ...
    "dt_order","eddy;transport(theta_prev,theta_now);thermal"), ...
    "UserDataPersistent","on");
end
