function config = configureIHNativeModel(modelName, configFile)
%CONFIGUREIHNATIVEMODEL Load and validate one native IH model configuration.
arguments
    modelName (1,1) string
    configFile (1,1) string = ""
end
if ~bdIsLoaded(modelName)
    error("radia:simulink:IHModelNotLoaded", ...
        "The IH model must be loaded before it is configured.");
end
workspace = get_param(modelName, "ModelWorkspace");
if strlength(configFile) > 0
    if ~isfile(configFile)
        error("radia:simulink:IHConfigFile", ...
            "IH configuration file does not exist: %s", configFile);
    end
    [~,~,extension] = fileparts(configFile);
    if strcmpi(extension, ".mat")
        loaded = load(configFile);
        if isfield(loaded, "config")
            config = loaded.config;
        elseif isfield(loaded, "radia_ih_config")
            config = loaded.radia_ih_config;
        else
            error("radia:simulink:IHConfigFile", ...
                "MAT file must contain config or radia_ih_config.");
        end
    elseif strcmpi(extension, ".json")
        config = jsondecode(fileread(configFile));
    else
        error("radia:simulink:IHConfigFile", ...
            "IH configuration must be a MAT or JSON file.");
    end
else
    try
        config = workspace.getVariable("radia_ih_config");
    catch
        try
            config = evalin("base", "radia_ih_config");
        catch
            error("radia:simulink:IHConfigMissing", ...
                "Neither the model workspace nor base workspace contains radia_ih_config.");
        end
    end
end

required = ["n_eddy_unknown","n_heat","n_temperature","bh_mode", ...
    "eddy_matrix_real","eddy_matrix_imag","eddy_rhs_real", ...
    "eddy_rhs_imag","heat_projection","heat_cell_weights", ...
    "heat_to_temperature_projection","mass_row_ptr","mass_col", ...
    "mass_value","stiffness_row_ptr","stiffness_col", ...
    "stiffness_value","temperature_cell_weights", ...
    "initial_temperature_K","sample_time_s","rotation_mode", ...
    "angle_origin_rad"];
missing = required(~isfield(config, required));
if ~isempty(missing)
    error("radia:simulink:IHConfigMissing", ...
        "Native IH configuration is missing: %s", strjoin(missing, ", "));
end
if ~isfield(config, "backend") || ...
        string(config.backend) ~= "matlab-level2+radia-mex-handles"
    error("radia:simulink:IHConfigBackend", ...
        "IH configuration backend must be matlab-level2+radia-mex-handles.");
end
diagnosticOnly = isfield(config, "diagnostic_only") && ...
    logical(config.diagnostic_only);
if ~diagnosticOnly
    if ~isfield(config, "operator_assembly") || ...
            string(config.operator_assembly) ~= "preassembled"
        error("radia:simulink:IHConfigAssembly", ...
            "IH runtime configurations must contain preassembled native operators.");
    end
    if ~isfield(config, "vol_check_required") || ...
            ~logical(config.vol_check_required) || ...
            ~isfield(config, "vol_check_reports") || ...
            isempty(config.vol_check_reports) || ...
            any(~isfile(string(config.vol_check_reports)))
        error("radia:simulink:IHConfigVolCheck", ...
            "Checked .vol reports are required before native IH initialization.");
    end
end
if ~(isscalar(config.sample_time_s) && isfinite(config.sample_time_s) && ...
        config.sample_time_s > 0)
    error("radia:simulink:IHConfigSampleTime", ...
        "sample_time_s must be finite and positive.");
end
if numel(config.temperature_cell_weights) ~= config.n_temperature || ...
        numel(config.initial_temperature_K) ~= config.n_temperature || ...
        any(~isfinite(config.temperature_cell_weights)) || ...
        any(config.temperature_cell_weights <= 0) || ...
        any(~isfinite(config.initial_temperature_K)) || ...
        any(config.initial_temperature_K <= 0)
    error("radia:simulink:IHConfigTemperatureShape", ...
        "Temperature vectors must match n_temperature.");
end
if numel(config.heat_cell_weights) ~= config.n_heat || ...
        any(~isfinite(config.heat_cell_weights)) || ...
        any(config.heat_cell_weights <= 0)
    error("radia:simulink:IHConfigHeatShape", ...
        "heat_cell_weights must contain one finite positive value per heat region.");
end
if ~any(string(config.rotation_mode) == ["none","periodic-uniform"])
    error("radia:simulink:IHConfigRotation", ...
        "rotation_mode must be none or periodic-uniform.");
end
if numel(config.heat_to_temperature_projection) ~= ...
        config.n_temperature * config.n_heat || ...
        any(~isfinite(config.heat_to_temperature_projection))
    error("radia:simulink:IHConfigHeatProjection", ...
        "heat_to_temperature_projection must contain n_temperature*n_heat values.");
end
config = radia.simulink.validateIHNativeConfig(config);
workspace.assignin("radia_ih_config", config);
set_param(modelName, "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", compose("%.17g", config.sample_time_s));
end
