function lut = makeTeam28CoilBuilderLUT(source, options)
%MAKETEAM28COILBUILDERLUT Load the validated CoilBuilder height family.
%   The source is the 25-position HCurl eddy-bubble/CLN validation result.
%   Its force is already the physical 50 Hz cycle average, so no additional
%   factor-of-two correction is applied. The returned schema is compatible
%   with evaluateTeam28CLNForce and the packaged TEAM 28 LUT S-function.

arguments
    source = ""
    options.SampleTime_s (1,1) double {mustBePositive} = 1.0e-3
    options.Extrapolation (1,1) string = "clip"
end

if ~ismember(options.Extrapolation, ["clip", "error"])
    error("radia:simulink:Team28Extrapolation", ...
        "Extrapolation must be 'clip' or 'error'.");
end

if isstruct(source)
    data = source;
    sourceFile = "";
else
    source = string(source);
    if strlength(source) == 0
        repoRoot = fileparts(fileparts(fileparts(fileparts( ...
            mfilename("fullpath")))));
        source = fullfile(repoRoot, "validation_test", "maglev", ...
            "team28_coilbuilder_height_family_results.json");
    end
    if ~isfile(source)
        error("radia:simulink:Team28CoilBuilderSource", ...
            "TEAM 28 CoilBuilder family result does not exist: %s", source);
    end
    data = jsondecode(fileread(source));
    sourceFile = source;
end

validateSource(data);
samples = data.details.height_family;
heightOffset = reshape(double([samples.height_offset_m]), [], 1);
upwardLift = reshape(double([samples.upward_force_N]), [], 1);
[heightOffset, order] = sort(heightOffset);
upwardLift = upwardLift(order);
if numel(heightOffset) < 2 || any(~isfinite(heightOffset)) || ...
        any(~isfinite(upwardLift)) || any(diff(heightOffset) <= 0)
    error("radia:simulink:Team28CoilBuilderSource", ...
        "height and lift samples must be finite and strictly increasing.");
end

signedForce = -upwardLift;
forceSlope = gradient(signedForce, heightOffset);
problem = data.details.problem;
lut = struct( ...
    "schema", "radia.team28.cln_lut.v1", ...
    "height_offset_m", heightOffset, ...
    "force_N", signedForce, ...
    "upward_lift_N", upwardLift, ...
    "force_slope_N_per_m", forceSlope, ...
    "frequency_Hz", double(problem.frequency_hz), ...
    "disk_weight_N", double(problem.disk_weight_N), ...
    "reference_coil_current_A", ...
        double(problem.coil_current_reference_A), ...
    "reference_disk_bottom_m", ...
        double(problem.reference_disk_bottom_mm) * 1.0e-3, ...
    "physical_force_factor", 1.0, ...
    "sample_time_s", options.SampleTime_s, ...
    "extrapolation", options.Extrapolation, ...
    "source_file", string(sourceFile), ...
    "source_radia_version", string(data.radia_version), ...
    "source_validation_passed", logical(data.pass), ...
    "family_state_order", double(problem.evrs_rank), ...
    "family_snapshot_count", numel(heightOffset), ...
    "model", ...
        "TEAM 28 CoilBuilder + common-basis HCurl eddy-bubble height family", ...
    "force_semantics", ...
        "fixed-frequency cycle-averaged Lorentz lift; current scales quadratically");
end

function validateSource(data)
required = ["radia_version", "schema", "pass", "details"];
if ~all(isfield(data, cellstr(required))) || ...
        string(data.schema) ~= "cae-ai-lab.solver-run.v1" || ~data.pass
    error("radia:simulink:Team28CoilBuilderSource", ...
        "source must be a passing solver-run artifact.");
end
if ~isfield(data.details, "height_family") || ...
        ~isfield(data.details, "problem")
    error("radia:simulink:Team28CoilBuilderSource", ...
        "source is missing the height family or problem metadata.");
end
problem = data.details.problem;
needed = ["frequency_hz", "coil_current_reference_A", ...
    "disk_weight_N", "reference_disk_bottom_mm", "evrs_rank"];
if ~all(isfield(problem, cellstr(needed)))
    error("radia:simulink:Team28CoilBuilderSource", ...
        "source problem metadata is incomplete.");
end
end
