function family = makeHCurlEddyFosterFamily(positions_m, decayRates, modalPortRHS, forceOperator, options)
%MAKEHCURLEDDYFOSTERFAMILY Create a moving Foster family with shared modes.
%   positions_m is strictly increasing (count values).  decayRates holds the
%   shared Foster decay rates (n_state), modalPortRHS is
%   [n_state, port_count, count] and forceOperator is
%   [3, n_state, port_count, count] in modal coordinates.  The discrete
%   state matrix is shared; the input and force operators interpolate in
%   height, which keeps every interpolated model passive.

arguments
    positions_m double
    decayRates double
    modalPortRHS double
    forceOperator double
    options.SampleTime_s (1,1) double {mustBeFinite, mustBePositive} = 1.0e-5
    options.Interpolation (1,1) string {mustBeMember(options.Interpolation, ...
        ["nearest", "linear", "pchip"])} = "linear"
    options.Extrapolation (1,1) string {mustBeMember(options.Extrapolation, ...
        ["error", "clamp"])} = "error"
    options.InitialState double = []
end

positions = double(positions_m(:));
count = numel(positions);
if count < 1 || any(~isfinite(positions)) || any(diff(positions) <= 0)
    error("radia:simulink:HCurlFosterFamily", ...
        "positions_m must be finite and strictly increasing.");
end
nState = numel(decayRates);
nPort = size(modalPortRHS, 2);
if size(modalPortRHS, 1) ~= nState || size(modalPortRHS, 3) ~= count || nPort < 1
    error("radia:simulink:HCurlFosterFamily", ...
        "modalPortRHS must be [n_state, port_count, count].");
end
if ~isequal([size(forceOperator, 1), size(forceOperator, 2), ...
        size(forceOperator, 3), size(forceOperator, 4)], [3, nState, nPort, count])
    error("radia:simulink:HCurlFosterFamily", ...
        "forceOperator must be [3, n_state, port_count, count].");
end
% The reference model validates passivity, finiteness and the hold.
reference = radia.simulink.makeHCurlEddyFosterModel(decayRates, ...
    modalPortRHS(:, :, 1), SampleTime_s=options.SampleTime_s, ...
    ForceOperator=forceOperator(:, :, :, 1), InitialState=options.InitialState);
if any(~isfinite(modalPortRHS), "all") || any(~isfinite(forceOperator), "all")
    error("radia:simulink:HCurlFosterFamily", ...
        "family operators must be finite.");
end
[~, bdGain] = radia.internal.hcurlEddyFosterZOH(reference.decay_rates, ...
    options.SampleTime_s);
family = struct( ...
    "schema", "radia.hcurl.eddy_foster.family.v1", ...
    "source_file", "", ...
    "shared_modes", true, ...
    "positions_m", positions, ...
    "decay_rates", reference.decay_rates, ...
    "modal_port_rhs", double(modalPortRHS), ...
    "force_operator", double(forceOperator), ...
    "Ad", reference.Ad, ...
    "bd_gain", bdGain, ...
    "x0", reference.x0, ...
    "snapshot_count", count, ...
    "state_order", nState, ...
    "port_count", nPort, ...
    "sample_time_s", options.SampleTime_s, ...
    "interpolation", options.Interpolation, ...
    "extrapolation", options.Extrapolation, ...
    "metadata", struct());
end
