function study = makeFieldStudySpec(options)
%MAKEFIELDSTUDYSPEC Construct the setup-time multiphysics study description.

arguments
    options.Physics (1,1) string {mustBeMember(options.Physics, ...
        ["electrostatic","current_flow","steady_heat","harmonic_eddy"])}
    options.Formulation (1,1) string {mustBeMember(options.Formulation, ...
        ["planar","axisymmetric"])} = "planar"
    options.ElementFamily (1,1) string {mustBeMember(options.ElementFamily, ...
        ["P1","P2","P2_curved","Q1","Q2","Q2_curved"])} = "P1"
    options.Frequency_Hz (1,1) double {mustBeFinite,mustBeNonnegative} = 0
    options.ModelDepth_m (1,1) double {mustBeFinite,mustBePositive} = 1
    options.DirichletValues (1,1) struct = struct()
    options.RobinBoundaries (1,1) struct = struct()
    options.VolumetricSources (1,1) struct = struct()
    options.TerminalPair (1,1) struct = struct()
    options.BranchCurrent_A = zeros(0,1)
    options.Description (1,1) string = ""
end
if options.Physics=="harmonic_eddy" && options.Frequency_Hz<=0
    error("radia:simulink:FieldStudyFrequency", ...
        "harmonic_eddy requires Frequency_Hz > 0.");
end
if options.Physics~="harmonic_eddy" && options.Physics~="current_flow" && ...
        options.Frequency_Hz~=0
    error("radia:simulink:FieldStudyFrequency", ...
        "Frequency_Hz is available only for harmonic_eddy or AC current_flow.");
end
currents=options.BranchCurrent_A(:);
if any(~isfinite(real(currents))) || any(~isfinite(imag(currents)))
    error("radia:simulink:FieldStudyCurrent","Branch currents must be finite.");
end
study=struct("schema","radia.simulink.field-study-spec.v1", ...
    "physics",options.Physics,"formulation",options.Formulation, ...
    "element_family",options.ElementFamily,"frequency_Hz",options.Frequency_Hz, ...
    "model_depth_m",options.ModelDepth_m, ...
    "dirichlet_values",options.DirichletValues, ...
    "robin_boundaries",options.RobinBoundaries, ...
    "volumetric_sources",options.VolumetricSources, ...
    "terminal_pair",options.TerminalPair, ...
    "branch_current_A",currents,"description",options.Description);
end
