function plant = makeTeam28CoilBuilderPlant(lut, options)
%MAKETEAM28COILBUILDERPLANT Build the slow mechanical TEAM 28 contract.
%   The electromagnetic force is a validated, fixed-50-Hz cycle average.
%   Mechanical motion is therefore quasi-steady relative to the carrier.
%   DampingRatio is an explicit demonstration parameter, not an identified
%   TEAM 28 material or aerodynamic damping coefficient.

arguments
    lut (1,1) struct
    options.Gravity_m_per_s2 (1,1) double {mustBePositive} = 9.81
    options.DampingRatio (1,1) double {mustBeNonnegative} = 0.35
    options.InitialHeightOffset_m (1,1) double {mustBeFinite} = -7.0e-3
    options.SampleTime_s (1,1) double {mustBePositive} = 1.0e-3
    options.StopTime_s (1,1) double {mustBePositive} = 2.0
end

validateLUT(lut);
grid = double(lut.height_offset_m(:));
lift = double(lut.upward_lift_N(:));
residual = lift - double(lut.disk_weight_N);
crossing = find(residual(1:end-1) .* residual(2:end) <= 0, 1);
if isempty(crossing)
    error("radia:simulink:Team28Equilibrium", ...
        "the validated height family does not bracket force equals weight.");
end
equilibrium = fzero(@(height) interp1(grid, lift, height, "pchip") - ...
    double(lut.disk_weight_N), grid(crossing:crossing + 1));
signedSlope = interp1(grid, double(lut.force_slope_N_per_m(:)), ...
    equilibrium, "linear");
restoringStiffness = max(signedSlope, 0.0);
if restoringStiffness <= 0
    error("radia:simulink:Team28Equilibrium", ...
        "the force-height crossing is not a stable restoring equilibrium.");
end

mass = double(lut.disk_weight_N) / options.Gravity_m_per_s2;
damping = 2.0 * options.DampingRatio * ...
    sqrt(mass * restoringStiffness);
naturalFrequency = sqrt(restoringStiffness / mass) / (2.0 * pi);
if options.InitialHeightOffset_m < grid(1) || ...
        options.InitialHeightOffset_m > grid(end)
    error("radia:simulink:Team28InitialHeight", ...
        "InitialHeightOffset_m must lie inside the validated height family.");
end

lut.sample_time_s = options.SampleTime_s;
plant = struct( ...
    "schema", "radia.team28.coilbuilder_mechanical.v1", ...
    "lut", lut, ...
    "disk_mass_kg", mass, ...
    "disk_weight_N", double(lut.disk_weight_N), ...
    "gravity_m_per_s2", options.Gravity_m_per_s2, ...
    "reference_disk_bottom_m", double(lut.reference_disk_bottom_m), ...
    "equilibrium_height_offset_m", equilibrium, ...
    "equilibrium_absolute_bottom_m", ...
        double(lut.reference_disk_bottom_m) + equilibrium, ...
    "linearized_restoring_stiffness_N_per_m", restoringStiffness, ...
    "undamped_natural_frequency_Hz", naturalFrequency, ...
    "damping_ratio", options.DampingRatio, ...
    "viscous_damping_Ns_per_m", damping, ...
    "initial_height_offset_m", options.InitialHeightOffset_m, ...
    "sample_time_s", options.SampleTime_s, ...
    "stop_time_s", options.StopTime_s, ...
    "height_limits_m", [grid(1), grid(end)], ...
    "electromagnetic_assumption", ...
        "50 Hz cycle-averaged force with quasi-steady height interpolation", ...
    "damping_provenance", ...
        "explicit control-oriented demonstration parameter; not identified data");
end

function validateLUT(lut)
required = ["schema", "height_offset_m", "upward_lift_N", ...
    "force_slope_N_per_m", "disk_weight_N", ...
    "reference_disk_bottom_m", "reference_coil_current_A"];
if ~all(isfield(lut, cellstr(required))) || ...
        string(lut.schema) ~= "radia.team28.cln_lut.v1"
    error("radia:simulink:Team28LUT", ...
        "lut must be a validated TEAM 28 CLN LUT contract.");
end
end
