function lut = makeTeam28LiftLUT(source, options)
%MAKETEAM28LIFTLUT Load the full-FEM TEAM 28 force-height curve as a LUT.
%   LUT = radia.simulink.makeTeam28LiftLUT() loads
%   validation_test/maglev/team28_axisym_fem_height_sweep.json, the
%   axisymmetric full-FEM sweep that involves no reduced model.  The stored
%   upward_physical_N is the physical 50 Hz time-averaged lift, so no
%   factor-of-two correction is applied.  HeightOffset_m is dZ relative to
%   the 10.8 mm reference disk position.

arguments
    source = ""
    options.SampleTime_s (1,1) double {mustBePositive} = 1.0e-3
    options.Extrapolation (1,1) string = "clip"
end

if ~ismember(options.Extrapolation, ["clip", "error"])
    error("radia:simulink:Team28Extrapolation", ...
        "Extrapolation must be 'clip' or 'error'.");
end
if isstruct(source)
    data = source;
    sourceFile = "";
else
    source = string(source);
    if strlength(source) == 0
        repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename("fullpath")))));
        source = fullfile(repoRoot, "validation_test", "maglev", ...
            "team28_axisym_fem_height_sweep.json");
        sourceFile = fullfile("validation_test", "maglev", ...
            "team28_axisym_fem_height_sweep.json");
    else
        sourceFile = source;
    end
    if ~isfile(source)
        error("radia:simulink:Team28Source", ...
            "TEAM 28 full-FEM sweep does not exist: %s", source);
    end
    data = jsondecode(fileread(source));
end

required = ["schema", "pass", "dZ_mm", "upward_physical_N", ...
    "frequency_Hz", "coil_current_peak_A", "disk_weight_N"];
if ~all(isfield(data, cellstr(required))) || ...
        string(data.schema) ~= "radia.team28-axisym-fem-height-sweep.v1" || ~data.pass
    error("radia:simulink:Team28Source", ...
        "source must be a passing TEAM 28 full-FEM height sweep.");
end
heightOffset = double(data.dZ_mm(:)) * 1.0e-3;
upwardLift = double(data.upward_physical_N(:));
if numel(heightOffset) < 2 || numel(upwardLift) ~= numel(heightOffset) || ...
        any(~isfinite(heightOffset)) || any(~isfinite(upwardLift))
    error("radia:simulink:Team28Source", ...
        "TEAM 28 height and force vectors must be finite and have matching sizes.");
end
[heightOffset, order] = sort(heightOffset);
upwardLift = upwardLift(order);
if any(diff(heightOffset) <= 0)
    error("radia:simulink:Team28Source", ...
        "TEAM 28 heights must be strictly increasing.");
end

force = -upwardLift;
lut = struct( ...
    "schema", "radia.team28.lift_lut.v1", ...
    "height_offset_m", heightOffset, ...
    "force_N", force, ...
    "upward_lift_N", upwardLift, ...
    "force_slope_N_per_m", gradient(force, heightOffset), ...
    "frequency_Hz", double(data.frequency_Hz), ...
    "disk_weight_N", double(data.disk_weight_N), ...
    "reference_coil_current_A", double(data.coil_current_peak_A), ...
    "reference_disk_bottom_m", 10.8e-3, ...
    "physical_force_factor", 1.0, ...
    "sample_time_s", options.SampleTime_s, ...
    "extrapolation", options.Extrapolation, ...
    "source_file", string(sourceFile), ...
    "source_validation_passed", logical(data.pass), ...
    "model", "axisymmetric TEAM 28 full-FEM force-height curve", ...
    "force_semantics", ...
        "fixed-frequency cycle-averaged Lorentz lift; current scales quadratically");
end
