function [busObject, value] = makeIHMonitorBusObject(options)
%MAKEIHMONITORBUSOBJECT Define fixed-schema induction-heating telemetry.
arguments
    options.AssignToBase (1,1) logical = true
end

[~, header] = radia.simulink.makeMonitorHeaderBusObject( ...
    AssignToBase=options.AssignToBase);
value = struct( ...
    "header", header, ...
    "sample_index", 0, ...
    "current_A", 0, ...
    "angle_rad", 0, ...
    "ambient_temperature_K", 0, ...
    "heat_min_W_per_m3", 0, ...
    "heat_mean_W_per_m3", 0, ...
    "heat_max_W_per_m3", 0, ...
    "total_heat_W", 0, ...
    "temperature_min_K", 0, ...
    "temperature_mean_K", 0, ...
    "temperature_max_K", 0);
payloadNames = string(fieldnames(value));
elements = repmat(Simulink.BusElement, numel(payloadNames), 1);
for index = 1:numel(payloadNames)
    element = Simulink.BusElement;
    element.Name = char(payloadNames(index));
    element.Dimensions = 1;
    element.DimensionsMode = "Fixed";
    element.Complexity = "real";
    if payloadNames(index) == "header"
        element.DataType = "Bus: RadiaMonitorHeaderV1";
    else
        element.DataType = "double";
    end
    elements(index) = element;
end
busObject = Simulink.Bus;
busObject.Description = ...
    "Scalar native IH telemetry; distributed q and T remain physical ports";
busObject.Elements = elements;
if options.AssignToBase
    assignin("base", "IHMonitorBusV1", busObject);
end
end
