function config = makeIHNativeSmokeConfig(options)
%MAKEIHNATIVESMOKECONFIG Minimal executable native IH configuration.
%   This one-DOF configuration exists for model load/update and installation
%   diagnostics. It is not a physical design result.
arguments
    options.SampleTime_s (1,1) double {mustBePositive,mustBeFinite} = 0.1
end
config = struct( ...
    "schema", "radia.ih.simulink.native_sfunction.v1", ...
    "backend", "matlab-level2+radia-mex-handles", ...
    "python_fallback", false, ...
    "release_channel", "preview", ...
    "operator_assembly", "diagnostic", ...
    "diagnostic_only", true, ...
    "eddy_solver", "fem", ...
    "thermal_solver", "fem", ...
    "n_eddy_unknown", 1, ...
    "n_heat", 1, ...
    "n_temperature", 1, ...
    "bh_mode", 'linear', ...
    "eddy_matrix_real", 1, ...
    "eddy_matrix_imag", 0, ...
    "eddy_rhs_real", 1, ...
    "eddy_rhs_imag", 0, ...
    "heat_projection", 1, ...
    "heat_cell_weights", 1, ...
    "heat_to_temperature_projection", 1, ...
    "mass_row_ptr", [0;1], ...
    "mass_col", 0, ...
    "mass_value", 1, ...
    "stiffness_row_ptr", [0;1], ...
    "stiffness_col", 0, ...
    "stiffness_value", 0, ...
    "temperature_cell_weights", 1, ...
    "initial_temperature_K", 293.15, ...
    "sample_time_s", options.SampleTime_s, ...
    "thermal_tolerance", 1e-12, ...
    "thermal_max_iterations", 100, ...
    "rotation_mode", 'periodic-uniform', ...
    "angle_origin_rad", 0, ...
    "temperature_coordinate_system", "workpiece", ...
    "rotation_transport", "conservative-periodic", ...
    "dt_order", "eddy;transport(theta_prev,theta_now);thermal");
config = radia.simulink.validateIHNativeConfig(config);
end
