function [busObject, value] = makeOptunaMonitorBusObject(options)
%MAKEOPTUNAMONITORBUSOBJECT Define fixed-schema Optuna telemetry.
arguments
    options.AssignToBase (1,1) logical = true
end

[~, header] = radia.simulink.makeMonitorHeaderBusObject( ...
    AssignToBase=options.AssignToBase);
value = struct( ...
    "header", header, ...
    "best_value", NaN, ...
    "best_trial", NaN, ...
    "completed_trials", 0, ...
    "last_value", NaN, ...
    "best_updated", 0, ...
    "pareto_count", 0, ...
    "pareto_revision", 0, ...
    "failed_trials", 0, ...
    "attempted_trials", 0, ...
    "selected_trial", NaN, ...
    "pruned_trials", 0, ...
    "current_trial", NaN);
payloadNames = string(fieldnames(value));
elements = repmat(Simulink.BusElement, numel(payloadNames), 1);
for index = 1:numel(payloadNames)
    element = Simulink.BusElement;
    element.Name = char(payloadNames(index));
    element.Dimensions = 1;
    element.DimensionsMode = "Fixed";
    element.Complexity = "real";
    if payloadNames(index) == "header"
        element.DataType = "Bus: RadiaMonitorHeaderV1";
    else
        element.DataType = "double";
    end
    elements(index) = element;
end
busObject = Simulink.Bus;
busObject.Description = ...
    "Scalar Optuna study telemetry; variable-length history stays in MAT tables";
busObject.Elements = elements;
if options.AssignToBase
    assignin("base", "OptunaMonitorBusV1", busObject);
end
end
