function study = makeFieldStudySpec(options)
%MAKEFIELDSTUDYSPEC Construct the setup-time multiphysics study description.

arguments
    options.Physics (1,1) string {mustBeMember(options.Physics, ...
        ["electrostatic","electrostatic_system","current_flow", ...
        "steady_heat","transient_heat","harmonic_eddy"])}
    options.Formulation (1,1) string {mustBeMember(options.Formulation, ...
        ["planar","axisymmetric"])} = "planar"
    options.ElementFamily (1,1) string {mustBeMember(options.ElementFamily, ...
        ["P1","P2","P2_curved","Q1","Q2","Q2_curved"])} = "P1"
    options.Frequency_Hz (1,1) double {mustBeFinite,mustBeNonnegative} = 0
    options.ModelDepth_m (1,1) double {mustBeFinite,mustBePositive} = 1
    options.DirichletValues (1,1) struct = struct()
    options.RobinBoundaries (1,1) struct = struct()
    options.VolumetricSources (1,1) struct = struct()
    options.TerminalPair (1,1) struct = struct()
    options.BranchCurrent_A = zeros(0,1)
    options.Time_s (:,1) double {mustBeFinite,mustBeNonnegative} = zeros(0,1)
    options.Theta (1,1) double {mustBeFinite} = 1
    options.InitialTemperature_K = 293.15
    options.DirichletHistory_K (1,1) struct = struct()
    options.VolumetricSourceHistory_W_per_m3 (1,1) struct = struct()
    options.Conductors (:,1) string = strings(0,1)
    options.AppliedVoltages_V (:,1) double {mustBeFinite} = zeros(0,1)
    options.ForceBoundaries (:,1) string = strings(0,1)
    options.Description (1,1) string = ""
end
if options.Physics=="harmonic_eddy" && options.Frequency_Hz<=0
    error("radia:simulink:FieldStudyFrequency", ...
        "harmonic_eddy requires Frequency_Hz > 0.");
end
if options.Physics~="harmonic_eddy" && options.Physics~="current_flow" && ...
        options.Frequency_Hz~=0
    error("radia:simulink:FieldStudyFrequency", ...
        "Frequency_Hz is available only for harmonic_eddy or AC current_flow.");
end
if options.Physics=="transient_heat"
    if numel(options.Time_s)<2 || any(diff(options.Time_s)<=0)
        error("radia:simulink:FieldStudyTime", ...
            "transient_heat requires a strictly increasing Time_s with at least two samples.");
    end
    if options.Theta<0.5 || options.Theta>1
        error("radia:simulink:FieldStudyTheta","Theta must be in [0.5,1].");
    end
elseif ~isempty(options.Time_s) || ~isempty(fieldnames(options.DirichletHistory_K)) || ...
        ~isempty(fieldnames(options.VolumetricSourceHistory_W_per_m3))
    error("radia:simulink:FieldStudyTime", ...
        "Transient time/history options require Physics='transient_heat'.");
end
if options.Physics=="electrostatic_system"
    if numel(options.Conductors)<2 || ...
            numel(unique(options.Conductors))~=numel(options.Conductors) || ...
            any(strlength(options.Conductors)==0)
        error("radia:simulink:FieldStudyConductors", ...
            "electrostatic_system requires at least two unique conductor boundaries.");
    end
    if numel(options.AppliedVoltages_V)~=numel(options.Conductors) || ...
            max(options.AppliedVoltages_V)-min(options.AppliedVoltages_V)<=0
        error("radia:simulink:FieldStudyVoltages", ...
            "AppliedVoltages_V needs one value per conductor and a nonzero difference.");
    end
elseif ~isempty(options.Conductors) || ~isempty(options.AppliedVoltages_V) || ...
        ~isempty(options.ForceBoundaries)
    error("radia:simulink:FieldStudyConductors", ...
        "Conductor options require Physics='electrostatic_system'.");
end
currents=options.BranchCurrent_A(:);
if any(~isfinite(real(currents))) || any(~isfinite(imag(currents)))
    error("radia:simulink:FieldStudyCurrent","Branch currents must be finite.");
end
study=struct("schema","radia.simulink.field-study-spec.v1", ...
    "physics",options.Physics,"formulation",options.Formulation, ...
    "element_family",options.ElementFamily,"frequency_Hz",options.Frequency_Hz, ...
    "model_depth_m",options.ModelDepth_m, ...
    "dirichlet_values",options.DirichletValues, ...
    "robin_boundaries",options.RobinBoundaries, ...
    "volumetric_sources",options.VolumetricSources, ...
    "terminal_pair",options.TerminalPair, ...
    "branch_current_A",currents,"time_s",options.Time_s(:), ...
    "theta",options.Theta,"initial_temperature_K",options.InitialTemperature_K, ...
    "dirichlet_history_K",options.DirichletHistory_K, ...
    "volumetric_source_history_W_per_m3",options.VolumetricSourceHistory_W_per_m3, ...
    "conductors",options.Conductors(:), ...
    "applied_voltages_V",options.AppliedVoltages_V(:), ...
    "force_boundaries",options.ForceBoundaries(:), ...
    "description",options.Description);
end
