function family = makeMagLevSmokeFamily(options)
%MAKEMAGLEVSMOKEFAMILY Create a small passive MagLev CLN test family.
%   This family exists so the packaged block can compile and simulate
%   without external artifacts. It is diagnostic data, not a validated
%   levitation design. Replace it with a common-basis family exported by
%   radia.vim.ExportHCurlEddyCLNFamilyJSON for engineering work.

arguments
    options.SampleTime_s (1,1) double {mustBeFinite, mustBePositive} = 1.0e-4
end

positions = [0.0; 0.01];
resistance = cat(3, ...
    [4.0, 0.2; 0.2, 8.0], ...
    [5.0, 0.3; 0.3, 9.5]);
inductance = cat(3, ...
    [0.025, 0.001; 0.001, 0.050], ...
    [0.030, 0.0015; 0.0015, 0.060]);
portRHS = cat(3, [0.30; 0.12], [0.24; 0.10]);

models = cell(1, numel(positions));
for index = 1:numel(positions)
    model = radia.simulink.makeHCurlEddyCLNModel( ...
        resistance(:,:,index), inductance(:,:,index), ...
        portRHS(:,:,index), SampleTime_s=options.SampleTime_s);
    model.height_m = positions(index);
    model.exchange_schema = "radia.hcurl.eddy_cln.exchange.v1";
    model.force_operator = zeros(3, model.state_order, model.port_count);
    model.force_operator(3,:,1) = ...
        (1.0 - 0.25 * (index - 1)) * [-0.18, -0.08];
    model.metadata = struct("purpose", "diagnostic-smoke-only");
    models{index} = model;
end

family = struct( ...
    "schema", "radia.hcurl.eddy_cln.family.v1", ...
    "source_file", "", ...
    "shared_state_basis", true, ...
    "positions_m", positions, ...
    "models", {models}, ...
    "snapshot_count", numel(positions), ...
    "state_order", models{1}.state_order, ...
    "port_count", models{1}.port_count, ...
    "sample_time_s", options.SampleTime_s, ...
    "interpolation", "linear", ...
    "extrapolation", "error", ...
    "metadata", struct( ...
        "purpose", "diagnostic-smoke-only", ...
        "production_replacement", ...
        "radia.vim.ExportHCurlEddyCLNFamilyJSON"));
end
