function family = makeMotorAngleFamily(angleGrid_rad, A, B, C, D, Q, R, S, x0, options)
%MAKEMOTORANGLEFAMILY Validate a periodic native motor ROM family.
%   A/B/C/D define the discrete state-space model at each angle snapshot.
%   Q/R/S define torque as
%     0.5*x'*Q*x + x'*R*u + 0.5*u'*S*u.
%   Snapshot pages cross the MATLAB/MEX boundary once when the S-Function
%   starts. Periodic interpolation and every simulation step run in C++.

arguments
    angleGrid_rad (:,1) double
    A double
    B double
    C double
    D double
    Q double
    R double
    S double
    x0 (:,1) double
    options.Period_rad (1,1) double {mustBePositive} = 2*pi
    options.SampleTime_s (1,1) double {mustBePositive} = 1.0e-4
end

snapshotCount = numel(angleGrid_rad);
if snapshotCount < 2 || any(~isfinite(angleGrid_rad)) || ...
        any(diff(angleGrid_rad) <= 0) || ...
        angleGrid_rad(end) - angleGrid_rad(1) >= options.Period_rad
    error("radia:simulink:MotorAngleGrid", ...
        "The angle grid must contain at least two finite, strictly increasing, non-repeated periodic samples.");
end
arrays = {A, B, C, D, Q, R, S};
names = ["A", "B", "C", "D", "Q", "R", "S"];
for index = 1:numel(arrays)
    value = arrays{index};
    if ndims(value) > 3 || size(value, 3) ~= snapshotCount || ...
            any(~isfinite(value), "all")
        error("radia:simulink:MotorAngleFamily", ...
            "%s must be a finite matrix family with one page per angle.", names(index));
    end
end

nState = size(A, 1);
nInput = size(B, 2);
nLinearOutput = size(C, 1);
if nState < 1 || nInput < 1 || nLinearOutput < 1 || ...
        size(A, 2) ~= nState || size(B, 1) ~= nState || ...
        size(C, 2) ~= nState || ~isequal(size(D, 1:2), [nLinearOutput, nInput]) || ...
        ~isequal(size(Q, 1:2), [nState, nState]) || ...
        ~isequal(size(R, 1:2), [nState, nInput]) || ...
        ~isequal(size(S, 1:2), [nInput, nInput]) || numel(x0) ~= nState
    error("radia:simulink:MotorAngleFamily", ...
        "The A/B/C/D/Q/R/S and x0 dimensions are inconsistent.");
end
for snapshot = 1:snapshotCount
    if norm(Q(:,:,snapshot) - Q(:,:,snapshot).', "fro") > ...
            1.0e-12 * max(1.0, norm(Q(:,:,snapshot), "fro")) || ...
            norm(S(:,:,snapshot) - S(:,:,snapshot).', "fro") > ...
            1.0e-12 * max(1.0, norm(S(:,:,snapshot), "fro"))
        error("radia:simulink:MotorTorqueForm", ...
            "Every Q and S snapshot must be symmetric.");
    end
end

family = struct( ...
    "schema", "radia.motor.periodic-angle-family.v1", ...
    "angle_grid_rad", angleGrid_rad(:), ...
    "period_rad", options.Period_rad, ...
    "sample_time_s", options.SampleTime_s, ...
    "snapshot_count", snapshotCount, ...
    "state_order", nState, ...
    "input_count", nInput, ...
    "linear_output_count", nLinearOutput, ...
    "output_count", nLinearOutput + 1, ...
    "A", A, "B", B, "C", C, "D", D, ...
    "Q", Q, "R", R, "S", S, "x0", x0(:), ...
    "backend", "native-mex-periodic-interpolation", ...
    "torque_definition", "0.5*x'*Q*x + x'*R*u + 0.5*u'*S*u");
end
