function config = makeNonlinearReactorConfig( ...
        demagOperator, magnetizationModes, sampleWeights, ...
        excitationPerAmp, bhCurve, options)
%MAKENONLINEARREACTORCONFIG Build a native reduced HDiv-MMM reactor contract.
%   The preassembled HDiv-MMM model is solved in the native MEX runtime at
%   each accepted Simulink sample. The Level-2 MATLAB S-Function owns the
%   Simulink lifecycle; Python is not used per simulation step.

arguments
    demagOperator double
    magnetizationModes double
    sampleWeights (:,1) double
    excitationPerAmp (:,1) double
    bhCurve (:,2) double
    options.SamplePoints_m double = zeros(0,3)
    options.AirInductance_H (1,1) double {mustBeFinite,mustBeNonnegative} = 0
    options.WindingResistance_Ohm (1,1) double {mustBeFinite,mustBeNonnegative} = 0
    options.SampleTime_s (1,1) double {mustBeFinite,mustBePositive} = 1.0e-4
    options.InitialCurrent_A (1,1) double {mustBeFinite} = 0
    options.ResidualTolerance (1,1) double {mustBeFinite,mustBePositive} = 1.0e-9
    options.MaxIterations (1,1) double {mustBeInteger,mustBePositive} = 40
    options.LineSearchMinimum (1,1) double {mustBeFinite,mustBePositive} = 2^-20
    options.Source (1,1) string = "preassembled-hdiv-mmm"
end

nModes = size(magnetizationModes,1);
nSamples = size(magnetizationModes,2);
if nModes < 1 || nSamples < 1 || size(magnetizationModes,3) ~= 3 || ...
        ~isequal(size(demagOperator),[nModes,nModes]) || ...
        numel(sampleWeights) ~= nSamples || numel(excitationPerAmp) ~= nModes
    error("radia:simulink:NonlinearReactorDimensions", ...
        "Demag, modes, weights, and excitation dimensions are inconsistent.");
end
if any(~isfinite(demagOperator),"all") || ...
        any(~isfinite(magnetizationModes),"all") || ...
        any(~isfinite(sampleWeights)) || any(sampleWeights <= 0) || ...
        any(~isfinite(excitationPerAmp)) || norm(excitationPerAmp) == 0
    error("radia:simulink:NonlinearReactorValues", ...
        "HDiv-MMM operators, modes, weights, and excitation must be finite; weights and excitation must be nonzero.");
end
symmetryError = norm(demagOperator-demagOperator.',"fro") / ...
    max(norm(demagOperator,"fro"),realmin);
if symmetryError > 1.0e-10
    error("radia:simulink:NonlinearReactorDemag", ...
        "The HDiv-MMM demagnetizing operator must be symmetric.");
end
demagOperator = 0.5*(demagOperator+demagOperator.');

if size(bhCurve,1) < 2 || any(~isfinite(bhCurve),"all") || ...
        any(diff(bhCurve(:,1)) <= 0) || any(diff(bhCurve(:,2)) <= 0) || ...
        any(abs(bhCurve(1,:)) > 1.0e-14)
    error("radia:simulink:NonlinearReactorBH", ...
        "BHCurve must start at [0,0] and contain strictly increasing finite H [A/m] and B [T].");
end
mu0 = 4*pi*1.0e-7;
magnetizationTable = bhCurve(:,2)/mu0-bhCurve(:,1);
scale = max(1,max(abs(magnetizationTable)));
if magnetizationTable(1) ~= 0 || ...
        any(diff(magnetizationTable) <= 1.0e-12*scale)
    error("radia:simulink:NonlinearReactorBHInverse", ...
        "BHCurve must define a strictly increasing magnetization B/mu0-H. " + ...
        "Extend the final high-field point with at least the vacuum slope instead of using a flat B tail.");
end
if options.LineSearchMinimum > 1
    error("radia:simulink:NonlinearReactorLineSearch", ...
        "LineSearchMinimum must be in (0,1].");
end

samplePoints = double(options.SamplePoints_m);
if ~isempty(samplePoints) && ...
        (~isequal(size(samplePoints),[nSamples,3]) || ...
         any(~isfinite(samplePoints),"all"))
    error("radia:simulink:NonlinearReactorPoints", ...
        "SamplePoints_m must be empty or an nSamples-by-3 finite array.");
end

config = struct( ...
    "schema",char("radia.simulink.nonlinear-hdiv-mmm-reactor.v1"), ...
    "backend",char("matlab-level2+radia-mex-handle"), ...
    "source",char(options.Source), ...
    "python_per_step",false, ...
    "n_modes",nModes,"n_samples",nSamples, ...
    "demag_row_major",reshape(demagOperator.',1,[]), ...
    "magnetization_modes_row_major", ...
        reshape(permute(magnetizationModes,[3,2,1]),1,[]), ...
    "sample_weights",sampleWeights(:), ...
    "sample_points_m",samplePoints, ...
    "excitation_per_amp",excitationPerAmp(:), ...
    "bh_curve_H_A_per_m_B_T",bhCurve, ...
    "magnetization_table_A_per_m",magnetizationTable(:), ...
    "field_table_A_per_m",bhCurve(:,1), ...
    "air_inductance_H",options.AirInductance_H, ...
    "winding_resistance_Ohm",options.WindingResistance_Ohm, ...
    "sample_time_s",options.SampleTime_s, ...
    "initial_current_A",options.InitialCurrent_A, ...
    "residual_tolerance",options.ResidualTolerance, ...
    "max_iterations",options.MaxIterations, ...
    "line_search_minimum",options.LineSearchMinimum, ...
    "flux_linkage_definition", ...
        "lambda=L_air*i+mu0*excitation_per_amp'*magnetization", ...
    "voltage_definition","v=R*i+(lambda-lambda_previous)/dt", ...
    "field_output","sampled B magnitude in tesla");
config = radia.simulink.validateNonlinearReactorConfig(config);
end
