function review = reviewOptunaStudy(blockPath)
%REVIEWOPTUNASTUDY Load trial history without adding Simulink signal lines.
arguments
    blockPath (1,1) string
end
storagePath = evaluatedMaskValue(blockPath, "storage_path");
if strlength(storagePath) == 0
    error("radia:simulink:OptunaStudyStorage", ...
        "Set Study MAT file before reviewing a study.");
end
if ~isfile(storagePath) && ~isfile(storagePath + ".bak")
    error("radia:simulink:OptunaStudyStorage", ...
        "Study MAT file '%s' does not exist.", storagePath);
end
study = radia.optuna.loadStudy(storage=storagePath);
review = struct( ...
    "schema", "radia.optuna.simulink-study-review.v1", ...
    "storage_path", storagePath, ...
    "trials", study.TrialTable, ...
    "objectives", study.ObjectiveTable, ...
    "parameters", study.ParamTable, ...
    "intermediate", study.IntermediateTable, ...
    "constraints", study.ConstraintTable, ...
    "pareto", study.paretoFront());
if nargout == 0
    assignin("base", "radia_optuna_review", review);
    assignin("base", "radia_optuna_trials", review.trials);
    fprintf("Optuna study: %d trials (%d complete, %d pruned, %d failed)\n", ...
        height(review.trials), sum(review.trials.State == "COMPLETE"), ...
        sum(review.trials.State == "PRUNED"), ...
        sum(review.trials.State == "FAIL"));
end
end

function value = evaluatedMaskValue(blockPath, name)
variables = get_param(blockPath, "MaskWSVariables");
match = find(strcmp({variables.Name}, name), 1);
if isempty(match)
    error("radia:simulink:OptunaStudyMask", ...
        "Block '%s' has no '%s' mask parameter.", blockPath, name);
end
value = string(variables(match).Value);
end
