function result = runApplication(application, configFile, options)
%RUNAPPLICATION Execute one DesignSpec-backed Radia application explicitly.
%   This is the batch-analysis boundary used by Radia application blocks.
%   It launches Python once per explicit request and reads the stable
%   run.log/result.json artifact pair; it is not a per-time-step solver.

arguments
    application (1,1) string {mustBeMember(application, ...
        ["em", "pcb", "motor", "streamfunction", "ih"])}
    configFile (1,1) string
    options.RunRoot (1,1) string = "C:\temp\radia_simulink"
    options.Timeout_s (1,1) double {mustBeNonnegative} = 3600
    options.PythonExecutable (1,1) string = "python"
    options.ThrowOnFailure (1,1) logical = true
end

if ~isfolder(options.RunRoot)
    mkdir(options.RunRoot);
end

stamp = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyyMMdd'T'HHmmss'Z'"));
runDirectory = fullfile(options.RunRoot, application, stamp);
suffix = 1;
while isfolder(runDirectory)
    suffix = suffix + 1;
    runDirectory = fullfile(options.RunRoot, application, ...
        stamp + "_" + compose("%02d", suffix));
end
mkdir(runDirectory);

command = quoteArgument(options.PythonExecutable) + ...
    " -m radia.simulink.application" + ...
    " --application " + quoteArgument(application) + ...
    " --config " + quoteArgument(configFile) + ...
    " --run-dir " + quoteArgument(runDirectory) + ...
    " --timeout " + compose("%.17g", options.Timeout_s);
launcherCommandPath = fullfile(runDirectory, "launcher_command.txt");
writeTextFile(launcherCommandPath, command + newline);
startedAt = utcTimestamp();
timer = tic;
[processStatus, processOutput] = system(command);
elapsed_s = toc(timer);

resultPath = fullfile(runDirectory, "result.json");
if ~isfile(resultPath)
    logPath = fullfile(runDirectory, "run.log");
    writeTextFile(logPath, processOutput);
    message = "Radia application runner did not create result.json. " + ...
        "See run.log for launcher output.";
    result = launcherFailureResult(application, configFile, runDirectory, ...
        logPath, launcherCommandPath, command, processStatus, message, ...
        startedAt, elapsed_s, options.Timeout_s);
    encoded = string(jsonencode(struct("radia_result", result), ...
        PrettyPrint=true));
    writeTextFile(resultPath, encoded + newline);
else
    decoded = jsondecode(fileread(resultPath));
    if ~isfield(decoded, "radia_result")
        error("radia:simulink:InvalidResult", ...
            "Radia application result has no radia_result object: %s", resultPath);
    end
    result = decoded.radia_result;
end
result.result_json = string(resultPath);
result.process_status = processStatus;
result.process_output = string(processOutput);

if options.ThrowOnFailure && ...
        (processStatus ~= 0 || string(result.status) ~= "passed")
    message = "Radia " + application + " application failed.";
    if isfield(result, "error") && ~isempty(result.error)
        message = message + " " + string(result.error);
    end
    error("radia:simulink:ApplicationFailed", "%s", message);
end
end

function quoted = quoteArgument(value)
value = string(value);
if contains(value, '"')
    error("radia:simulink:InvalidCommandArgument", ...
        "Command arguments must not contain a double quote.");
end
quoted = '"' + value + '"';
end

function result = launcherFailureResult(application, configFile, runDirectory, ...
        logPath, commandPath, command, processStatus, message, startedAt, ...
        elapsed_s, timeout_s)
result = struct( ...
    "schema", "radia.simulink.application_run.v1", ...
    "application", application, ...
    "backend", "python-headless-cli", ...
    "status", "failed", ...
    "returncode", processStatus, ...
    "error", message, ...
    "executed_at_utc", startedAt, ...
    "completed_at_utc", utcTimestamp(), ...
    "elapsed_s", elapsed_s, ...
    "timeout_s", timeout_s, ...
    "runtime_radia_version", "unknown", ...
    "runtime_python", "unavailable", ...
    "runtime_platform", string(computer), ...
    "config", configFile, ...
    "config_sha256", "", ...
    "run_dir", runDirectory, ...
    "log", logPath, ...
    "command_file", commandPath, ...
    "solver_result", "", ...
    "command", {{}}, ...
    "command_line", command, ...
    "primary", struct("key", "", "value", []));
end

function timestamp = utcTimestamp()
timestamp = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end

function writeTextFile(path, text)
fileID = fopen(path, "w", "n", "UTF-8");
if fileID < 0
    error("radia:simulink:ArtifactWriteFailed", ...
        "Could not write Simulink application artifact: %s", path);
end
cleanup = onCleanup(@() fclose(fileID));
count = fprintf(fileID, "%s", text);
if count < 0
    error("radia:simulink:ArtifactWriteFailed", ...
        "Could not write Simulink application artifact: %s", path);
end
clear cleanup
end
