function result = runRLCResonanceOptimizationDemo(options)
%RUNRLCRESONANCEOPTIMIZATIONDEMO Tune series-RLC C from Simulink ring-downs.
arguments
    options.TargetFrequency_Hz (1,1) double {mustBePositive,mustBeFinite} = 1000
    options.Resistance_Ohm (1,1) double {mustBeNonnegative,mustBeFinite} = 2
    options.Inductance_H (1,1) double {mustBePositive,mustBeFinite} = 10e-3
    options.CapacitanceBounds_F (1,2) double {mustBePositive,mustBeFinite} = [1e-6 6e-6]
    options.NumTrials (1,1) double {mustBeInteger,mustBePositive} = 32
    options.Seed (1,1) double {mustBeInteger,mustBeNonnegative} = 42
    options.StopTime_s (1,1) double {mustBePositive,mustBeFinite} = 0.02
    options.ModelFile (1,1) string = fullfile( ...
        radia.simulink.exampleDirectory(), "radia_rlc_resonance_plant.slx")
    options.OutputDirectory (1,1) string = "C:\temp\radia_rlc_resonance_demo"
    options.StoragePath (1,1) string = ""
    options.ResultPath (1,1) string = ""
    options.PlotPath (1,1) string = ""
    options.RebuildModel (1,1) logical = false
    options.ResetStudy (1,1) logical = true
    options.ShowFigure (1,1) logical = false
end

if options.CapacitanceBounds_F(1) >= options.CapacitanceBounds_F(2)
    error("radia:simulink:RLCBounds", ...
        "CapacitanceBounds_F must be strictly increasing.");
end
if ~isfolder(options.OutputDirectory)
    mkdir(options.OutputDirectory);
end
if strlength(options.StoragePath) == 0
    options.StoragePath = fullfile(options.OutputDirectory, ...
        "rlc_resonance_study.mat");
end
if strlength(options.ResultPath) == 0
    options.ResultPath = fullfile(options.OutputDirectory, ...
        "results_rlc_resonance_optimization.json");
end
if strlength(options.PlotPath) == 0
    options.PlotPath = fullfile(options.OutputDirectory, ...
        "rlc_resonance_optimization.png");
end
ensureParent(options.StoragePath);
ensureParent(options.ResultPath);
ensureParent(options.PlotPath);

totalTimer = tic;
build_s = 0;
if options.RebuildModel || ~isfile(options.ModelFile)
    buildTimer = tic;
    [modelDirectory, modelName] = fileparts(options.ModelFile);
    modelDirectory = string(modelDirectory);
    modelName = string(modelName);
    options.ModelFile = radia.simulink.buildRLCResonanceOptimizationDemo( ...
        OutputDirectory=modelDirectory, ModelName=modelName);
    build_s = toc(buildTimer);
end
if options.ResetStudy && isfile(options.StoragePath)
    delete(options.StoragePath);
end

target = options.TargetFrequency_Hz;
resistance = options.Resistance_Ohm;
inductance = options.Inductance_H;
bounds = options.CapacitanceBounds_F;
analyticCapacitance = 1 / (inductance * ((2*pi*target)^2 + ...
    (resistance/(2*inductance))^2));
if analyticCapacitance < bounds(1) || analyticCapacitance > bounds(2)
    error("radia:simulink:RLCTargetOutsideBounds", ...
        "The target frequency requires C=%.9g F, outside the search bounds.", ...
        analyticCapacitance);
end

startupTrials = min(6, max(1, floor(options.NumTrials/4)));
sampler = radia.optuna.TPESampler( ...
    Seed=options.Seed, NStartupTrials=startupTrials, ...
    NumberOfEIChoices=48);
study = radia.optuna.createStudy( ...
    study_name="rlc-resonance", direction="minimize", ...
    sampler=sampler, StoragePath=options.StoragePath, AutoSave=true);
context = struct( ...
    "domain", "series-rlc-ringdown", ...
    "target_frequency_Hz", target, ...
    "resistance_Ohm", resistance, ...
    "inductance_H", inductance, ...
    "capacitance_bounds_F", bounds);
runner = radia.optuna.SimulinkRunner(options.ModelFile, ...
    ConfigureFcn=@configureTrial, ...
    ScoreFcn=@scoreTrial, ...
    ValidationFcn=@validateTrial, ...
    ResultFcn=@trialArtifacts, ...
    StopTime=compose("%.17g", options.StopTime_s), ...
    UseFastRestart=true, Context=context);

optimizationTimer = tic;
runner.optimize(study, options.NumTrials, ContinueOnError=false);
optimization_s = toc(optimizationTimer);
best = study.bestSolution();
if ~best.available || ~isfield(best.params, "capacitance_F")
    error("radia:simulink:RLCNoBestTrial", ...
        "The RLC optimization did not produce a completed trial.");
end

bestCapacitance = double(best.params.capacitance_F);
replayTimer = tic;
in = Simulink.SimulationInput(options.ModelFile);
in = in.setVariable("R_ohm", resistance);
in = in.setVariable("L_H", inductance);
in = in.setVariable("C_F", bestCapacitance);
in = in.setModelParameter("StopTime", compose("%.17g", options.StopTime_s));
out = sim(in);
ringVoltage = out.get("ring_voltage");
[measuredFrequency, measurement] = ...
    radia.simulink.measureRingdownFrequency(ringVoltage);
theory = radia.simulink.analyzeRLCResonance( ...
    resistance, inductance, bestCapacitance);
replay_s = toc(replayTimer);

completed = study.TrialTable.State == "COMPLETE";
failed = study.TrialTable.State == "FAIL";
completeTrials = study.TrialTable(completed,:);
trialNumbers = completeTrials.TrialNumber;
objectives = completeTrials.Value;
capacitances = cellfun(@(value) double(value.capacitance_F), ...
    completeTrials.Params);
targetError = abs(measuredFrequency-target) / target;
theoryError = abs(measuredFrequency-theory.ringdown_frequency_Hz) / ...
    theory.ringdown_frequency_Hz;
capacitanceError = abs(bestCapacitance-analyticCapacitance) / ...
    analyticCapacitance;

visualizationTimer = tic;
visible = "off";
if options.ShowFigure
    visible = "on";
end
figureHandle = figure("Visible", visible, "Color", "white", ...
    "Position", [100 100 1000 720]);
layout = tiledlayout(figureHandle, 2, 1, ...
    "TileSpacing", "compact", "Padding", "compact");
layoutTitle = title(layout, ...
    sprintf("Series RLC capacitance optimization: target %.0f Hz", target));
layoutTitle.Color = [0.12 0.12 0.12];

ringAxes = nexttile(layout, 1);
plot(ringAxes, ringVoltage.Time*1e3, ringVoltage.Data, "LineWidth", 1.4);
set(ringAxes, "Color", "white", "XColor", [0.15 0.15 0.15], ...
    "YColor", [0.15 0.15 0.15], "GridColor", [0.35 0.35 0.35]);
xlabel(ringAxes, "Time (ms)");
ylabel(ringAxes, "Capacitor voltage (V)");
grid(ringAxes, "on");
ringTitle = title(ringAxes, sprintf( ...
    "Best ring-down: C = %.6g uF, measured = %.3f Hz", ...
    bestCapacitance*1e6, measuredFrequency));
ringTitle.Color = [0.12 0.12 0.12];

historyAxes = nexttile(layout, 2);
yyaxis(historyAxes, "left");
semilogy(historyAxes, trialNumbers, max(objectives, realmin), ...
    "o-", "LineWidth", 1.1);
ylabel(historyAxes, "Objective: log(f/f_{target})^2");
yyaxis(historyAxes, "right");
plot(historyAxes, trialNumbers, capacitances*1e6, ".-", "LineWidth", 1.1, ...
    "MarkerSize", 13);
yline(historyAxes, analyticCapacitance*1e6, "--", "Analytic C");
set(historyAxes, "Color", "white", "XColor", [0.15 0.15 0.15], ...
    "GridColor", [0.35 0.35 0.35]);
ylabel(historyAxes, "Capacitance (uF)");
xlabel(historyAxes, "Trial number");
grid(historyAxes, "on");
historyAxes.YAxis(1).Color = [0 0.35 0.72];
historyAxes.YAxis(2).Color = [0.85 0.25 0.05];
exportgraphics(layout, options.PlotPath, "Resolution", 160);
visualization_s = toc(visualizationTimer);
if ~options.ShowFigure
    close(figureHandle);
end

simulinkInfo = ver("simulink");
result = struct( ...
    "radia_version", projectVersion(), ...
    "executed_at_utc", utcTimestamp(), ...
    "matlab_release", string(version("-release")), ...
    "simulink_version", string(simulinkInfo.Version), ...
    "schema", "radia.validation.rlc-resonance-optimization.v1", ...
    "model_file", string(options.ModelFile), ...
    "study_file", string(options.StoragePath), ...
    "plot_file", string(options.PlotPath), ...
    "definition", "underdamped free ring-down frequency from zero crossings", ...
    "target_frequency_Hz", target, ...
    "fixed_components", struct( ...
        "resistance_Ohm", resistance, "inductance_H", inductance), ...
    "search", struct( ...
        "parameter", "capacitance_F", ...
        "bounds_F", bounds, ...
        "sampler", "TPE", ...
        "seed", options.Seed, ...
        "requested_trials", options.NumTrials, ...
        "completed_trials", sum(completed), ...
        "failed_trials", sum(failed)), ...
    "best", struct( ...
        "trial_number", best.trial_number, ...
        "objective", best.value, ...
        "capacitance_F", bestCapacitance, ...
        "measured_ringdown_frequency_Hz", measuredFrequency, ...
        "analytic_ringdown_frequency_Hz", theory.ringdown_frequency_Hz, ...
        "natural_frequency_Hz", theory.natural_frequency_Hz, ...
        "quality_factor", theory.quality_factor, ...
        "target_relative_error", targetError, ...
        "measurement_vs_theory_relative_error", theoryError, ...
        "zero_crossing_measurement", measurement), ...
    "analytic_optimum", struct( ...
        "capacitance_F", analyticCapacitance, ...
        "best_capacitance_relative_error", capacitanceError), ...
    "gates", struct( ...
        "all_trials_completed", sum(completed) == options.NumTrials, ...
        "target_within_2_percent", targetError <= 0.02, ...
        "ringdown_measurement_within_0_1_percent", theoryError <= 1e-3, ...
        "capacitance_within_3_percent", capacitanceError <= 0.03), ...
    "timing_s", struct( ...
        "model_build", build_s, ...
        "optimization", optimization_s, ...
        "best_replay", replay_s, ...
        "visualization", visualization_s, ...
        "total_before_json_write", toc(totalTimer)));
writeJSON(options.ResultPath, result);
result.result_file = string(options.ResultPath);

    function simulationInput = configureTrial(simulationInput, trial)
        capacitance = trial.suggestFloat( ...
            "capacitance_F", bounds(1), bounds(2), Log=true);
        simulationInput = simulationInput.setVariable("R_ohm", resistance);
        simulationInput = simulationInput.setVariable("L_H", inductance);
        simulationInput = simulationInput.setVariable("C_F", capacitance);
    end

    function value = scoreTrial(simulationOutput, ~)
        frequency = radia.simulink.measureRingdownFrequency( ...
            simulationOutput.get("ring_voltage"));
        value = log(frequency/target)^2;
    end

    function validation = validateTrial(simulationOutput, trial)
        frequency = radia.simulink.measureRingdownFrequency( ...
            simulationOutput.get("ring_voltage"));
        expected = radia.simulink.analyzeRLCResonance( ...
            resistance, inductance, trial.Params.capacitance_F);
        validation = struct( ...
            "measured_frequency_Hz", frequency, ...
            "analytic_frequency_Hz", expected.ringdown_frequency_Hz, ...
            "relative_error", abs(frequency-expected.ringdown_frequency_Hz) / ...
                expected.ringdown_frequency_Hz, ...
            "passed", abs(frequency-expected.ringdown_frequency_Hz) / ...
                expected.ringdown_frequency_Hz <= 1e-3);
    end

    function artifacts = trialArtifacts(simulationOutput, trial)
        frequency = radia.simulink.measureRingdownFrequency( ...
            simulationOutput.get("ring_voltage"));
        artifacts = struct( ...
            "capacitance_F", trial.Params.capacitance_F, ...
            "ringdown_frequency_Hz", frequency);
    end
end

function ensureParent(path)
folder = string(fileparts(path));
if strlength(folder) > 0 && ~isfolder(folder)
    mkdir(folder);
end
end

function writeJSON(path, value)
file = fopen(path, "w");
if file < 0
    error("radia:simulink:RLCResultWrite", ...
        "Unable to open result file for writing: %s", path);
end
cleanup = onCleanup(@() fclose(file));
fprintf(file, "%s\n", jsonencode(value, PrettyPrint=true));
clear cleanup
end

function value = projectVersion()
matlabRoot = radia.simulink.exampleDirectory();
projectFile = fullfile(fileparts(matlabRoot), "pyproject.toml");
text = fileread(projectFile);
token = regexp(text, '(?m)^version\s*=\s*"([^"]+)"', "tokens", "once");
if isempty(token)
    value = "unknown";
else
    value = string(token{1});
end
end

function value = utcTimestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end
