function config = validateNonlinearReactorConfig(config)
%VALIDATENONLINEARREACTORCONFIG Validate the native reactor ABI contract.

if ~isstruct(config) || ~isscalar(config)
    error("radia:simulink:NonlinearReactorConfig", ...
        "The nonlinear reactor configuration must be a scalar struct.");
end
required = ["schema","backend","python_per_step","n_modes","n_samples", ...
    "demag_row_major","magnetization_modes_row_major","sample_weights", ...
    "excitation_per_amp","magnetization_table_A_per_m", ...
    "field_table_A_per_m","air_inductance_H", ...
    "winding_resistance_Ohm","sample_time_s","initial_current_A", ...
    "residual_tolerance","max_iterations","line_search_minimum"];
missing = required(~isfield(config,required));
if ~isempty(missing)
    error("radia:simulink:NonlinearReactorConfig", ...
        "The nonlinear reactor configuration is missing: %s", ...
        strjoin(missing,", "));
end
if ~ischar(config.schema) || ~isrow(config.schema) || ...
        ~ischar(config.backend) || ~isrow(config.backend) || ...
        string(config.schema) ~= "radia.simulink.nonlinear-hdiv-mmm-reactor.v1" || ...
        string(config.backend) ~= "matlab-level2+radia-mex-handle" || ...
        ~isscalar(config.python_per_step) || logical(config.python_per_step)
    error("radia:simulink:NonlinearReactorBackend", ...
        "The configuration must use the native MEX handle backend with no Python per step.");
end
nModes = double(config.n_modes);
nSamples = double(config.n_samples);
if ~isscalar(nModes) || ~isscalar(nSamples) || ...
        nModes < 1 || nSamples < 1 || fix(nModes) ~= nModes || ...
        fix(nSamples) ~= nSamples || ...
        numel(config.demag_row_major) ~= nModes^2 || ...
        numel(config.magnetization_modes_row_major) ~= 3*nModes*nSamples || ...
        numel(config.sample_weights) ~= nSamples || ...
        numel(config.excitation_per_amp) ~= nModes
    error("radia:simulink:NonlinearReactorDimensions", ...
        "The nonlinear reactor configuration has inconsistent dimensions.");
end
numericFields = ["demag_row_major","magnetization_modes_row_major", ...
    "sample_weights","excitation_per_amp", ...
    "magnetization_table_A_per_m","field_table_A_per_m"];
for fieldName = numericFields
    if ~isnumeric(config.(fieldName)) || ...
            any(~isfinite(double(config.(fieldName))),"all")
        error("radia:simulink:NonlinearReactorValues", ...
            "%s must contain finite numeric values.",fieldName);
    end
end
if any(double(config.sample_weights) <= 0) || ...
        norm(double(config.excitation_per_amp)) == 0
    error("radia:simulink:NonlinearReactorValues", ...
        "Sample weights must be positive and excitation must be nonzero.");
end
magnetization = double(config.magnetization_table_A_per_m(:));
fieldStrength = double(config.field_table_A_per_m(:));
if numel(magnetization) < 2 || numel(magnetization) ~= numel(fieldStrength) || ...
        magnetization(1) ~= 0 || fieldStrength(1) ~= 0 || ...
        any(diff(magnetization) <= 0) || any(diff(fieldStrength) <= 0)
    error("radia:simulink:NonlinearReactorBHInverse", ...
        "The inverse BH table must start at zero and increase strictly.");
end
scalars = double([config.air_inductance_H,config.winding_resistance_Ohm, ...
    config.sample_time_s,config.initial_current_A,config.residual_tolerance, ...
    config.max_iterations,config.line_search_minimum]);
if any(~isfinite(scalars)) || config.air_inductance_H < 0 || ...
        config.winding_resistance_Ohm < 0 || config.sample_time_s <= 0 || ...
        config.residual_tolerance <= 0 || config.max_iterations < 1 || ...
        fix(config.max_iterations) ~= config.max_iterations || ...
        config.line_search_minimum <= 0 || config.line_search_minimum > 1
    error("radia:simulink:NonlinearReactorValues", ...
        "The nonlinear reactor scalar configuration is invalid.");
end
end
