function verifyIHPanelImpedanceProvenance(configFile, sourceFile, expectedHash, options)
%VERIFYIHPANELIMPEDANCEPROVENANCE Require assembly to use the watched Zs bytes.
arguments
    configFile (1,1) string
    sourceFile (1,1) string
    expectedHash (1,1) string
    options (1,1) struct = struct()
end
config = jsondecode(fileread(configFile));
if ~isfield(config, "surface_impedance")
    error("radia:simulink:IHPanelZsProvenance", "Assembler omitted surface impedance provenance.");
end
actual = config.surface_impedance;
if isfield(options,"zs_mode") && string(options.zs_mode) == "per-panel-esim"
    try
    required = ["mode","artifact_file","artifact_sha256","surface_sha256","bh_sha256","bh_source_file", ...
        "reference_current_A","reference_phase_rad","frequency_hz","drive_relative_band", ...
        "iterations","final_residual","tolerance","final_certification","evaluator","zs_semantics"];
    valid = all(isfield(actual,required));
    if valid
        artifact = string(actual.artifact_file);
        bh = radia.simulink.fileFingerprint(string(options.esim_bh_file));
        valid = isfile(artifact) && string(actual.mode) == "per-panel-esim" && ...
            string(actual.zs_semantics) == "frozen_at_reference_current" && ...
            string(actual.bh_sha256) == string(bh.sha256) && ...
            string(actual.bh_source_file) == string(options.esim_bh_file) && ...
            actual.reference_current_A == str2double(string(options.esim_reference_current_A)) && ...
            actual.frequency_hz == str2double(string(options.frequency_hz)) && ...
            actual.drive_relative_band == str2double(string(options.esim_drive_relative_band)) && ...
            actual.reference_phase_rad == 0 && isfinite(actual.iterations) && actual.iterations > 0 && ...
            actual.iterations == fix(actual.iterations) && ...
            actual.iterations <= str2double(string(options.esim_max_iter)) && ...
            string(actual.evaluator) == string(options.esim_panel_evaluator) && ...
            isfinite(actual.final_residual) && actual.final_residual >= 0 && actual.final_residual <= actual.tolerance && ...
            actual.tolerance == str2double(string(options.esim_tolerance)) && ...
            string(actual.final_certification) == "direct-all-panels";
        if valid
            identity = radia.simulink.fileFingerprint(artifact);
            valid = string(identity.sha256) == string(actual.artifact_sha256);
            if valid
                data = jsondecode(fileread(artifact));
                valid = ...
                string(data.schema) == "radia.panel_surface_impedance.v1" && ...
                string(data.layout) == "BND-element-order" && string(data.unit) == "ohm" && ...
                data.frequency_hz == actual.frequency_hz && string(data.surface_sha256) == string(actual.surface_sha256) && isfield(data,"provenance") && ...
                all(isfield(data.provenance,["mode","iterations","tolerance","reference_current_A", ...
                    "reference_phase_rad","frequency_hz","drive_relative_band","bh_sha256", ...
                    "evaluator","final_residual","final_certification","zs_semantics"])) && ...
                string(data.provenance.mode) == string(actual.mode) && ...
                string(data.provenance.zs_semantics) == string(actual.zs_semantics) && ...
                data.provenance.iterations == actual.iterations && ...
                data.provenance.tolerance == actual.tolerance && ...
                data.provenance.reference_current_A == actual.reference_current_A && ...
                data.provenance.reference_phase_rad == actual.reference_phase_rad && ...
                data.provenance.frequency_hz == actual.frequency_hz && ...
                data.provenance.drive_relative_band == actual.drive_relative_band && ...
                string(data.provenance.bh_sha256) == string(actual.bh_sha256) && ...
                string(data.provenance.evaluator) == string(actual.evaluator) && ...
                data.provenance.final_residual == actual.final_residual && ...
                string(data.provenance.final_certification) == "direct-all-panels";
            end
        end
    end
    catch
        valid = false; % Malformed certificates fail with the stable boundary error.
    end
elseif strlength(sourceFile) == 0
    valid = string(actual.mode) == "uniform-linear";
else
    valid = string(actual.mode) == "specified-panel" && ...
        isfield(actual, "file_sha256") && string(actual.file_sha256) == expectedHash && ...
        isfield(actual, "source_file") && string(actual.source_file) == sourceFile;
end
if ~valid
    error("radia:simulink:IHPanelZsProvenance", ...
        "Assembled impedance does not match the watched input; rebuild from unchanged inputs.");
end
end
