function evaluation = evaluateAdjoint(evaluateFcn, design, expected)
%EVALUATEADJOINT Validate the objective/constraint adjoint contract.
arguments
    evaluateFcn (1,1) function_handle
    design (:,1) double {mustBeReal,mustBeFinite}
    expected.ConstraintCount (1,1) double ...
        {mustBeInteger,mustBeGreaterThanOrEqual(expected.ConstraintCount,-1)}=-1
    expected.EqualityCount (1,1) double ...
        {mustBeInteger,mustBeGreaterThanOrEqual(expected.EqualityCount,-1)}=-1
end

payload = evaluateFcn(design);
if ~isstruct(payload) || ~isscalar(payload) || ...
        ~all(isfield(payload, ["objective","gradient"]))
    error("radia:topopt:AdjointContract", ...
        "The evaluator must return a scalar struct with objective and gradient.");
end

objective = payload.objective;
gradient = payload.gradient;
if ~isnumeric(objective) || ~isscalar(objective) || ~isreal(objective) || ...
        ~isfinite(objective)
    error("radia:topopt:AdjointObjective", ...
        "objective must be one finite real scalar.");
end
gradient = double(gradient(:));
if numel(gradient) ~= numel(design) || ~isreal(gradient) || ...
        any(~isfinite(gradient))
    error("radia:topopt:AdjointGradient", ...
        "gradient must contain one finite real value per design variable.");
end

[constraints, constraintJacobian] = localConstraintPair( ...
    payload, "constraints", "constraint_jacobian", numel(design));
[equalities, equalityJacobian] = localConstraintPair( ...
    payload, "equalities", "equality_jacobian", numel(design));
if expected.ConstraintCount >= 0 && ...
        numel(constraints) ~= expected.ConstraintCount
    error("radia:topopt:AdjointConstraintCount", ...
        "The inequality-constraint count changed during optimization.");
end
if expected.EqualityCount >= 0 && numel(equalities) ~= expected.EqualityCount
    error("radia:topopt:AdjointEqualityCount", ...
        "The equality-constraint count changed during optimization.");
end

evaluation = struct( ...
    "schema", "radia.topopt.adjoint-evaluation/v1", ...
    "objective", double(objective), ...
    "gradient", gradient, ...
    "constraints", constraints, ...
    "constraint_jacobian", constraintJacobian, ...
    "equalities", equalities, ...
    "equality_jacobian", equalityJacobian, ...
    "payload", payload);
end

function [values, jacobian] = localConstraintPair(payload, valueName, ...
        jacobianName, designCount)
if ~isfield(payload, valueName)
    values = zeros(0,1);
    jacobian = zeros(designCount,0);
    return
end
values = double(payload.(valueName)(:));
if ~isreal(values) || any(~isfinite(values))
    error("radia:topopt:AdjointConstraint", ...
        "%s must contain finite real values.", valueName);
end
if isempty(values)
    jacobian = zeros(designCount,0);
    return
end
if ~isfield(payload, jacobianName)
    error("radia:topopt:AdjointJacobian", ...
        "%s is required when %s is nonempty.", jacobianName, valueName);
end
jacobian = double(payload.(jacobianName));
if ~isequal(size(jacobian), [designCount,numel(values)]) || ...
        ~isreal(jacobian) || any(~isfinite(jacobian), "all")
    error("radia:topopt:AdjointJacobian", ...
        "%s must be design_count-by-constraint_count and finite.", ...
        jacobianName);
end
end
