classdef (Abstract) BaseStorage < handle
    %BASESTORAGE Optuna 4.9 storage backend interface.

    methods (Abstract)
        check_trial_is_updatable(obj,trial_id,trial_state)
        study_id=create_new_study(obj,directions,study_name)
        trial_id=create_new_trial(obj,study_id,template_trial)
        delete_study(obj,study_id)
        studies=get_all_studies(obj)
        trials=get_all_trials(obj,study_id,deepcopy,states)
        trial=get_best_trial(obj,study_id)
        count=get_n_trials(obj,study_id,state)
        directions=get_study_directions(obj,study_id)
        study_id=get_study_id_from_name(obj,study_name)
        study_name=get_study_name_from_id(obj,study_id)
        attributes=get_study_system_attrs(obj,study_id)
        attributes=get_study_user_attrs(obj,study_id)
        trial=get_trial(obj,trial_id)
        trial_id=get_trial_id_from_study_id_trial_number(obj,study_id,trial_number)
        trial_number=get_trial_number_from_id(obj,trial_id)
        value=get_trial_param(obj,trial_id,param_name)
        params=get_trial_params(obj,trial_id)
        attributes=get_trial_system_attrs(obj,trial_id)
        attributes=get_trial_user_attrs(obj,trial_id)
        remove_session(obj)
        set_study_system_attr(obj,study_id,key,value)
        set_study_user_attr(obj,study_id,key,value)
        set_trial_intermediate_value(obj,trial_id,step,value)
        set_trial_param(obj,trial_id,param_name,param_value_internal,distribution)
        updated=set_trial_state_values(obj,trial_id,state,values)
        set_trial_system_attr(obj,trial_id,key,value)
        set_trial_user_attr(obj,trial_id,key,value)
    end
end
