function trial=createTrial(options)
%CREATETRIAL Construct a FrozenTrial for Study.addTrial().
arguments
    options.State (1,1) string = "COMPLETE"
    options.Value double = NaN
    options.Values double = NaN
    options.Params (1,1) struct = struct()
    options.Distributions (1,1) struct = struct()
    options.IntermediateValues table = table()
    options.UserAttrs (1,1) struct = struct()
    options.SystemAttrs (1,1) struct = struct()
    options.Constraints double = zeros(1,0)
    options.ConstraintPresent (1,1) logical = false
    options.DatetimeStart datetime = NaT
    options.DatetimeComplete datetime = NaT
    options.ErrorMessage (1,1) string = ""
end
trial=radia.optuna.FrozenTrial(State=options.State,Value=options.Value, ...
    Values=options.Values,Params=options.Params, ...
    Distributions=options.Distributions, ...
    IntermediateValues=options.IntermediateValues, ...
    UserAttrs=options.UserAttrs,SystemAttrs=options.SystemAttrs, ...
    Constraints=options.Constraints, ...
    ConstraintPresent=options.ConstraintPresent, ...
    DatetimeStart=options.DatetimeStart, ...
    DatetimeComplete=options.DatetimeComplete, ...
    ErrorMessage=options.ErrorMessage);
end
