function names=DISTRIBUTION_CLASSES()
%DISTRIBUTION_CLASSES Names in Optuna 4.9's public distribution registry.
names=["IntDistribution","IntLogUniformDistribution", ...
    "IntUniformDistribution","FloatDistribution", ...
    "UniformDistribution","LogUniformDistribution", ...
    "DiscreteUniformDistribution","CategoricalDistribution"];
end
