"""
Check Netgen .vol mesh quality, labels, and optional CAD reference values.

Standalone checker -- does NOT require Cubit.
The .vol file is always checked.  A sibling .vol.json CAD reference is used
when present, but is not required for the structural/label gate.

Usage:
    check-vol model.vol
    check-vol model.vol --strict-labels --contract labels.json
    check-vol model.vol --report-json run/vol_check.json

Exit code: 0 = all checks pass, 1 = validation finding, 2 = input error.
"""

import argparse
from collections.abc import Mapping
from datetime import datetime, timezone
import gzip
import importlib.metadata
import json
import os
from pathlib import Path
import platform
import re
import sys

import numpy as np


REPORT_SCHEMA = "cubit-mesh-export.vol-check.v1"
LABEL_CONTRACT_SCHEMA = "radia.vol-label-contract.v1"

_MATERIAL_LABEL_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_BOUNDARY_LABEL_RE = re.compile(
    r"^(?:[a-z][a-z0-9_]*|sym_(?:bn|ht)=0_[xyz])$"
)
_AUTOGENERATED_MATERIAL_RE = re.compile(
    r"^(?:block|domain|material|volume)[_-]?\d+$", re.IGNORECASE
)
_AUTOGENERATED_BOUNDARY_RE = re.compile(
    r"^(?:boundary|face|surface)[_-]?\d+$", re.IGNORECASE
)


def _distribution_version(name):
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


def _runtime_metadata():
    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "versions": {
            "cubit_mesh_export": _distribution_version("cubit-mesh-export"),
            "ngsolve": _distribution_version("ngsolve"),
            "python": platform.python_version(),
        },
    }


def _labels(value):
    if value is None:
        return set()
    if isinstance(value, str):
        return {part.strip() for part in value.split(",") if part.strip()}
    return {str(part).strip() for part in value if str(part).strip()}


def _mesh_label(value):
    """Normalize transport whitespace without changing label semantics."""
    return str(value).strip()


def _read_vol_text(path):
    path = Path(path)
    if path.suffix.lower() == ".gz":
        with gzip.open(path, "rt", encoding="utf-8-sig") as stream:
            return stream.read()
    return path.read_text(encoding="utf-8-sig")


def _vol_counted_rows(lines, names, *, required):
    if isinstance(names, str):
        names = (names,)
    lookup = {str(name).lower() for name in names}
    for section_index, line in enumerate(lines):
        if line.strip().lower() not in lookup:
            continue
        count_index = section_index + 1
        while count_index < len(lines):
            count_line = lines[count_index].strip()
            if count_line and not count_line.startswith("#"):
                break
            count_index += 1
        if count_index >= len(lines):
            raise ValueError(f".vol section {line.strip()!r} has no row count")
        try:
            count = int(lines[count_index].split()[0])
        except (IndexError, ValueError) as exc:
            raise ValueError(
                f".vol section {line.strip()!r} has an invalid row count"
            ) from exc
        if count < 0:
            raise ValueError(f".vol section {line.strip()!r} has a negative row count")
        rows = []
        row_index = count_index + 1
        while row_index < len(lines) and len(rows) < count:
            row = lines[row_index].strip()
            if row and not row.startswith("#"):
                rows.append(row)
            row_index += 1
        if len(rows) != count:
            raise ValueError(
                f".vol section {line.strip()!r} ended after {len(rows)} of {count} rows"
            )
        return rows
    if required:
        joined = " or ".join(repr(name) for name in names)
        raise ValueError(f".vol section {joined} not found")
    return []


def _boundary_domain_ownership_from_text(text):
    lines = str(text).splitlines()
    volume_rows = _vol_counted_rows(lines, "volumeelements", required=True)
    surface_rows = _vol_counted_rows(
        lines, ("surfaceelements", "surfaceelementsuv"), required=True
    )
    material_rows = _vol_counted_rows(lines, "materials", required=False)

    volume_domain_counts = {}
    invalid_volume_rows = []
    for row_number, row in enumerate(volume_rows, start=1):
        fields = row.split()
        try:
            domain = int(fields[0])
        except (IndexError, ValueError):
            invalid_volume_rows.append(row_number)
            continue
        if domain <= 0:
            invalid_volume_rows.append(row_number)
            continue
        volume_domain_counts[domain] = volume_domain_counts.get(domain, 0) + 1

    material_ids = []
    for row in material_rows:
        fields = row.split()
        try:
            material_ids.append(int(fields[0]))
        except (IndexError, ValueError):
            continue

    pair_counts = {}
    domain_surface_counts = {}
    exterior_domain_counts = {}
    internal_pair_counts = {}
    invalid_surface_rows = []
    invalid_surface_connectivity_rows = []
    duplicate_surface_connectivity_rows = []
    seen_surface_connectivity = {}
    zero_zero_rows = []
    equal_domain_rows = []
    referenced_domains = set()
    for row_number, row in enumerate(surface_rows, start=1):
        fields = row.split()
        try:
            domain_in = int(fields[2])
            domain_out = int(fields[3])
        except (IndexError, ValueError):
            invalid_surface_rows.append(row_number)
            continue
        pair = f"{domain_in}->{domain_out}"
        pair_counts[pair] = pair_counts.get(pair, 0) + 1
        try:
            node_count = int(fields[4])
            if node_count not in (3, 4) or len(fields) < 5 + node_count:
                raise ValueError
            connectivity = (
                node_count,
                *sorted(int(value) for value in fields[5:5 + node_count]),
            )
        except (IndexError, ValueError):
            invalid_surface_connectivity_rows.append(row_number)
        else:
            if connectivity in seen_surface_connectivity:
                duplicate_surface_connectivity_rows.append(row_number)
            else:
                seen_surface_connectivity[connectivity] = row_number
        if domain_in == 0 and domain_out == 0:
            zero_zero_rows.append(row_number)
        if domain_in != 0 and domain_in == domain_out:
            equal_domain_rows.append(row_number)
        if (domain_in == 0) != (domain_out == 0):
            domain = domain_in or domain_out
            exterior_domain_counts[domain] = exterior_domain_counts.get(domain, 0) + 1
        elif domain_in != 0 and domain_out != 0 and domain_in != domain_out:
            lo, hi = sorted((domain_in, domain_out))
            interface = f"{lo}<->{hi}"
            internal_pair_counts[interface] = internal_pair_counts.get(interface, 0) + 1
        for domain in (domain_in, domain_out):
            if domain != 0:
                referenced_domains.add(domain)
                domain_surface_counts[domain] = domain_surface_counts.get(domain, 0) + 1

    volume_domains = set(volume_domain_counts)
    unknown_surface_domains = sorted(referenced_domains - volume_domains)
    unreferenced_volume_domains = sorted(volume_domains - referenced_domains)
    missing_material_ids = sorted(volume_domains - set(material_ids)) if material_rows else []

    issues = []
    if invalid_volume_rows:
        issues.append(
            "invalid or non-positive volume domain rows: "
            + ", ".join(map(str, invalid_volume_rows))
        )
    if invalid_surface_rows:
        issues.append(
            "surface rows without integer DomainIn/DomainOut: "
            + ", ".join(map(str, invalid_surface_rows))
        )
    if invalid_surface_connectivity_rows:
        issues.append(
            "surface rows with invalid triangle/quad connectivity: "
            + ", ".join(map(str, invalid_surface_connectivity_rows))
        )
    if duplicate_surface_connectivity_rows:
        issues.append(
            "surface connectivity exported more than once: "
            + ", ".join(map(str, duplicate_surface_connectivity_rows))
        )
    if zero_zero_rows:
        issues.append(
            "surface rows with no owning domain (0->0): "
            + ", ".join(map(str, zero_zero_rows))
        )
    if equal_domain_rows:
        issues.append(
            "surface rows use the same nonzero domain on both sides: "
            + ", ".join(map(str, equal_domain_rows))
        )
    if unknown_surface_domains:
        issues.append(
            "surface rows reference unknown volume domains: "
            + ", ".join(map(str, unknown_surface_domains))
        )
    if unreferenced_volume_domains:
        issues.append(
            "volume domains absent from all boundary/interface descriptors: "
            + ", ".join(map(str, unreferenced_volume_domains))
        )

    return {
        "passed": not issues,
        "volume_element_count": len(volume_rows),
        "surface_element_count": len(surface_rows),
        "volume_domain_counts": dict(sorted(volume_domain_counts.items())),
        "surface_domain_pair_counts": dict(sorted(pair_counts.items())),
        "domain_surface_incidence_counts": dict(sorted(domain_surface_counts.items())),
        "exterior_surface_element_count": sum(exterior_domain_counts.values()),
        "exterior_surface_domain_counts": dict(sorted(exterior_domain_counts.items())),
        "internal_interface_element_count": sum(internal_pair_counts.values()),
        "internal_interface_domain_pair_counts": dict(sorted(internal_pair_counts.items())),
        "material_ids": sorted(set(material_ids)),
        "missing_material_ids": missing_material_ids,
        "unknown_surface_domains": unknown_surface_domains,
        "unreferenced_volume_domains": unreferenced_volume_domains,
        "invalid_volume_rows": invalid_volume_rows,
        "invalid_surface_rows": invalid_surface_rows,
        "invalid_surface_connectivity_rows": invalid_surface_connectivity_rows,
        "duplicate_surface_connectivity_rows": duplicate_surface_connectivity_rows,
        "zero_zero_rows": zero_zero_rows,
        "equal_domain_rows": equal_domain_rows,
        "issues": issues,
    }


def check_vol_boundary_domain_ownership(vol_path):
    """Audit raw ``.vol`` DomainIn/DomainOut coverage before solver use."""
    return _boundary_domain_ownership_from_text(_read_vol_text(vol_path))


def _load_label_contract(contract):
    if contract is None or contract == "":
        return {}
    if isinstance(contract, Mapping):
        payload = dict(contract)
    else:
        path = Path(contract)
        try:
            payload = json.loads(path.read_text(encoding="utf-8-sig"))
        except OSError as exc:
            raise ValueError(f"could not read label contract {path}: {exc}") from exc
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid label contract JSON {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError("label contract must be a JSON object")
    if "schema" not in payload:
        raise ValueError(
            f"label contract must declare schema {LABEL_CONTRACT_SCHEMA!r}"
        )
    schema = payload["schema"]
    if schema != LABEL_CONTRACT_SCHEMA:
        raise ValueError(
            f"unsupported label contract schema {schema!r}; "
            f"expected {LABEL_CONTRACT_SCHEMA!r}"
        )
    return payload


def _casefold_collisions(labels):
    grouped = {}
    for label in labels:
        grouped.setdefault(label.casefold(), set()).add(label)
    return [sorted(values) for values in grouped.values() if len(values) > 1]


def _mesh_label_inventory(mesh):
    def names(method):
        getter = getattr(mesh, method, None)
        if getter is None:
            return []
        return sorted({_mesh_label(value) for value in getter()
                       if _mesh_label(value)})

    return {
        "materials": names("GetMaterials"),
        "boundaries": names("GetBoundaries"),
        "bboundaries": names("GetBBoundaries"),
        "bbboundaries": names("GetBBBoundaries"),
    }


def _contract_label_set(payload, category, mode):
    section = payload.get(mode, {})
    if section is None:
        section = {}
    if not isinstance(section, Mapping):
        raise ValueError(f"label contract {mode!r} entry must be an object")
    nested = _labels(section.get(category))
    flat = _labels(payload.get(f"{mode}_{category}"))
    return nested | flat


def _contract_has_label_set(payload, category, mode):
    section = payload.get(mode, {})
    nested = isinstance(section, Mapping) and category in section
    return nested or f"{mode}_{category}" in payload


def check_label_contract(
    mesh_or_path,
    *,
    contract=None,
    strict=False,
    required_materials=(),
    required_boundaries=(),
    required_bboundaries=(),
    required_bbboundaries=(),
):
    """Validate solver-facing .vol labels without guessing their meaning.

    Strict mode requires lower snake-case material and boundary labels and
    rejects Cubit/Netgen fallback names such as ``volume_1`` or ``Surface_7``.
    ``GND`` is the one reserved upper-case point label.  Application-specific
    required labels belong in a versioned label-contract JSON.
    """

    import ngsolve as ng

    mesh = (
        ng.Mesh(str(mesh_or_path))
        if isinstance(mesh_or_path, (str, os.PathLike))
        else mesh_or_path
    )
    payload = _load_label_contract(contract)
    contract_strict = payload.get("strict_labels", False)
    if not isinstance(contract_strict, bool):
        raise ValueError("label contract strict_labels must be boolean")
    application = payload.get("application")
    if application is not None and not isinstance(application, str):
        raise ValueError("label contract application must be a string")
    strict = bool(strict or contract_strict)
    inventory = _mesh_label_inventory(mesh)

    explicit_required = {
        "materials": _labels(required_materials),
        "boundaries": _labels(required_boundaries),
        "bboundaries": _labels(required_bboundaries),
        "bbboundaries": _labels(required_bbboundaries),
    }
    required = {
        kind: sorted(values | _contract_label_set(payload, kind, "required"))
        for kind, values in explicit_required.items()
    }
    allowed = {
        kind: sorted(_contract_label_set(payload, kind, "allowed"))
        for kind in inventory
    }
    allowed_specified = {
        kind: _contract_has_label_set(payload, kind, "allowed")
        for kind in inventory
    }
    for kind in inventory:
        if (
            allowed_specified[kind]
            and not set(required[kind]).issubset(allowed[kind])
        ):
            omitted = sorted(set(required[kind]) - set(allowed[kind]))
            raise ValueError(
                f"label contract required {kind} are absent from allowed {kind}: "
                + ", ".join(omitted)
            )
    missing = {
        kind: sorted(set(values) - set(inventory[kind]))
        for kind, values in required.items()
    }
    unexpected = {
        kind: (
            sorted(set(inventory[kind]) - set(values))
            if allowed_specified[kind] else []
        )
        for kind, values in allowed.items()
    }

    invalid = {kind: [] for kind in inventory}
    autogenerated = {kind: [] for kind in inventory}
    if strict:
        invalid["materials"] = sorted(
            label for label in inventory["materials"]
            if not _MATERIAL_LABEL_RE.fullmatch(label)
        )
        invalid["boundaries"] = sorted(
            label for label in inventory["boundaries"]
            if not _BOUNDARY_LABEL_RE.fullmatch(label)
        )
        invalid["bboundaries"] = sorted(
            label for label in inventory["bboundaries"]
            if label != "default" and not _BOUNDARY_LABEL_RE.fullmatch(label)
        )
        invalid["bbboundaries"] = sorted(
            label for label in inventory["bbboundaries"]
            if label != "GND" and not _BOUNDARY_LABEL_RE.fullmatch(label)
        )
        autogenerated["materials"] = sorted(
            label for label in inventory["materials"]
            if _AUTOGENERATED_MATERIAL_RE.fullmatch(label)
            or label.casefold() == "default"
        )
        autogenerated["boundaries"] = sorted(
            label for label in inventory["boundaries"]
            if _AUTOGENERATED_BOUNDARY_RE.fullmatch(label)
            or label.casefold() in {"boundary", "default"}
        )

    collisions = {
        kind: _casefold_collisions(values)
        for kind, values in inventory.items()
    }
    boundaries = set(inventory["boundaries"])
    materials = set(inventory["materials"])
    bbboundaries = set(inventory["bbboundaries"])
    relational_issues = []
    if ("kelvin_int" in boundaries) != ("kelvin_ext" in boundaries):
        relational_issues.append("kelvin_int and kelvin_ext must appear as a pair")
    if "kelvin" in materials:
        if not {"kelvin_int", "kelvin_ext"}.issubset(boundaries):
            relational_issues.append(
                "kelvin material requires kelvin_int and kelvin_ext boundaries"
            )
        if "GND" not in bbboundaries:
            relational_issues.append("kelvin material requires the GND point label")
    if ("source" in boundaries) != ("sink" in boundaries):
        relational_issues.append("source and sink boundaries must appear as a pair")
    for axis in "xyz":
        if {
            f"sym_bn=0_{axis}",
            f"sym_ht=0_{axis}",
        }.issubset(boundaries):
            relational_issues.append(
                f"symmetry axis {axis} cannot carry both bn and ht labels"
            )

    warnings = []
    if int(getattr(mesh, "ne", 0)) > 0 and not inventory["materials"]:
        warnings.append("mesh has no material labels")
    if not inventory["boundaries"]:
        warnings.append("mesh has no boundary labels")
    for kind, values in missing.items():
        if values:
            warnings.append(f"missing {kind}: " + ", ".join(values))
    for kind, values in unexpected.items():
        if values:
            warnings.append(f"unexpected {kind}: " + ", ".join(values))
    for kind, values in invalid.items():
        if values:
            warnings.append(f"non-canonical {kind}: " + ", ".join(values))
    for kind, values in autogenerated.items():
        if values:
            warnings.append(f"autogenerated {kind}: " + ", ".join(values))
    for kind, values in collisions.items():
        if values:
            rendered = "; ".join("/".join(group) for group in values)
            warnings.append(f"case-insensitive {kind} collisions: {rendered}")
    warnings.extend(relational_issues)

    return {
        "schema": LABEL_CONTRACT_SCHEMA,
        "passed": not warnings,
        "application": application,
        "strict_labels": strict,
        **inventory,
        "required": required,
        "allowed": allowed,
        "allowed_specified": allowed_specified,
        "missing": missing,
        "unexpected": unexpected,
        "invalid": invalid,
        "autogenerated": autogenerated,
        "casefold_collisions": collisions,
        "relational_issues": relational_issues,
        "warnings": warnings,
    }


def _node_number(node):
    number = getattr(node, "nr", None)
    return int(node) if number is None else int(number)


def _element_number(element):
    number = getattr(element, "nr", None)
    return int(getattr(element, "index")) if number is None else int(number)


def _classify_conductor_face(volume_records, conductive, air):
    conductive_records = [row for row in volume_records if row[1] in conductive]
    if not conductive_records:
        return "nonconductive"
    if len(conductive_records) >= 2:
        materials = {row[1] for row in conductive_records}
        return "conductor-conductor" if len(materials) == 1 else "conductive-interface"

    neighbors = [row[1] for row in volume_records if row[1] not in conductive]
    if any(material in air for material in neighbors):
        return "conductor-air"
    if neighbors:
        return "conductor-insulator"
    return "conductor-exterior"


def _face_adjacency_quality(mesh, conductive_materials, air_materials,
                            sibc_boundaries, require_all_sibc_labeled):
    import ngsolve as ng

    conductive = _labels(conductive_materials)
    air = _labels(air_materials)
    sibc = _labels(sibc_boundaries)
    if not conductive:
        return {
            "enabled": False,
            "conductive_materials": [],
            "air_materials": sorted(air),
        }, []

    face_to_volume = {}
    for element in mesh.Elements(ng.VOL):
        record = (_element_number(element), _mesh_label(element.mat))
        for face in element.faces:
            face_to_volume.setdefault(_node_number(face), []).append(record)

    face_to_boundary = {}
    for element in mesh.Elements(ng.BND):
        record = (_element_number(element), _mesh_label(element.mat))
        for face in element.faces:
            face_to_boundary.setdefault(_node_number(face), []).append(record)

    role_counts = {}
    marked_non_sibc = []
    unlabeled_sibc = []
    for face_nr in sorted(set(face_to_volume) | set(face_to_boundary)):
        volume_records = tuple(face_to_volume.get(face_nr, ()))
        boundary_records = tuple(face_to_boundary.get(face_nr, ()))
        role = _classify_conductor_face(volume_records, conductive, air)
        role_counts[role] = role_counts.get(role, 0) + 1
        boundary_labels = {row[1] for row in boundary_records}
        is_sibc_role = role in {"conductor-air", "conductor-exterior"}
        marked = bool(boundary_labels & sibc)
        if marked and not is_sibc_role:
            marked_non_sibc.append({
                "face_nr": face_nr,
                "role": role,
                "boundary_labels": sorted(boundary_labels),
            })
        if require_all_sibc_labeled and is_sibc_role and not marked:
            unlabeled_sibc.append({
                "face_nr": face_nr,
                "role": role,
                "boundary_labels": sorted(boundary_labels),
            })

    warnings = []
    if marked_non_sibc:
        warnings.append(
            f"{len(marked_non_sibc)} SIBC-labelled faces are not conductor-air/exterior faces")
    if unlabeled_sibc:
        warnings.append(
            f"{len(unlabeled_sibc)} conductor-air/exterior faces lack an SIBC label")

    return {
        "enabled": True,
        "conductive_materials": sorted(conductive),
        "air_materials": sorted(air),
        "sibc_boundaries": sorted(sibc),
        "face_count": sum(role_counts.values()),
        "face_role_counts": dict(sorted(role_counts.items())),
        "sibc_candidate_face_count": (
            role_counts.get("conductor-air", 0)
            + role_counts.get("conductor-exterior", 0)
        ),
        "loop_bridge_face_count": (
            role_counts.get("conductor-conductor", 0)
            + role_counts.get("conductive-interface", 0)
        ),
        "marked_non_sibc_faces": marked_non_sibc[:50],
        "unlabeled_sibc_faces": unlabeled_sibc[:50],
    }, warnings


def check_mesh_quality(mesh_or_path, *, min_scaled_jacobian=1.0e-6,
                       jacobian_tolerance=0.0, integration_order=None,
                       min_curve_order=1, require_tetrahedra=False,
                       required_materials=(), required_boundaries=(),
                       conductive_materials=(), air_materials=("air", "vacuum"),
                       sibc_boundaries=(), require_all_sibc_labeled=False,
                       conductors=None, tet_only=None):
    """Check curved-element mappings, labels, and conductor-face adjacency.

    Unlike a corner-only tetrahedron metric, this gate samples the actual
    NGSolve element transformation at a high-order integration rule.  A
    consistently positive or negative element orientation is valid; a sign
    change within one element is not.  Scaled quality therefore uses
    ``abs(det(J))`` and still detects folded or nearly collapsed curved maps
    even when the linear corner element is valid.
    """
    import ngsolve as ng

    if conductors is not None:
        alias_labels = _labels(conductors)
        canonical_labels = _labels(conductive_materials)
        if canonical_labels and alias_labels != canonical_labels:
            raise ValueError(
                "conductors and conductive_materials specify different labels"
            )
        conductive_materials = alias_labels
    if tet_only is not None:
        if not isinstance(tet_only, bool):
            raise ValueError("tet_only must be boolean when provided")
        alias_value = tet_only
        if require_tetrahedra and not alias_value:
            raise ValueError(
                "tet_only=False conflicts with require_tetrahedra=True"
            )
        require_tetrahedra = alias_value

    mesh = (
        ng.Mesh(str(mesh_or_path))
        if isinstance(mesh_or_path, (str, os.PathLike))
        else mesh_or_path
    )
    curve_order = int(mesh.GetCurveOrder())
    min_scaled_jacobian = float(min_scaled_jacobian)
    jacobian_tolerance = float(jacobian_tolerance)
    min_curve_number = float(min_curve_order)
    if not np.isfinite(min_curve_number) or not min_curve_number.is_integer():
        raise ValueError("min_curve_order must be a positive integer")
    min_curve_order = int(min_curve_number)
    if integration_order is None:
        sample_order = 1 if curve_order <= 1 else 2 * curve_order + 2
    else:
        integration_number = float(integration_order)
        if not np.isfinite(integration_number) or not integration_number.is_integer():
            raise ValueError("integration_order must be a positive integer")
        sample_order = int(integration_number)
    if sample_order < 1:
        raise ValueError("integration_order must be positive")
    if (
        not np.isfinite(min_scaled_jacobian)
        or min_scaled_jacobian < 0.0
        or min_scaled_jacobian > 1.0
    ):
        raise ValueError("min_scaled_jacobian must lie in [0, 1]")
    if not np.isfinite(jacobian_tolerance) or jacobian_tolerance < 0.0:
        raise ValueError("jacobian_tolerance must be finite and non-negative")
    if min_curve_order < 1:
        raise ValueError("min_curve_order must be positive")

    min_det = float("inf")
    max_det = float("-inf")
    min_abs_det = float("inf")
    min_scaled = float("inf")
    sample_count = 0
    finite_jacobian_sample_count = 0
    finite_scaled_jacobian_sample_count = 0
    invalid_count = 0
    orientation_flip_count = 0
    negative_jacobian_sample_count = 0
    low_scaled_count = 0
    invalid_elements = set()
    low_scaled_elements = set()
    volume_element_count = 0
    tetrahedron_count = 0
    positive_orientation_element_count = 0
    negative_orientation_element_count = 0

    for element in mesh.Elements(ng.VOL):
        volume_element_count += 1
        if element.type == ng.ET.TET:
            tetrahedron_count += 1
        trafo = mesh.GetTrafo(element)
        rule = ng.IntegrationRule(element.type, sample_order)
        orientation_sign = None
        for point in rule:
            jacobian = np.asarray(trafo(point).jacobi, dtype=float)
            determinant = float(np.linalg.det(jacobian))
            column_norm_product = float(np.prod(np.linalg.norm(jacobian, axis=0)))
            scaled = (
                abs(determinant) / column_norm_product
                if column_norm_product > 0.0 else float("-inf")
            )
            sample_count += 1
            if np.isfinite(determinant):
                finite_jacobian_sample_count += 1
                min_det = min(min_det, determinant)
                max_det = max(max_det, determinant)
                min_abs_det = min(min_abs_det, abs(determinant))
                if determinant < 0.0:
                    negative_jacobian_sample_count += 1
            if np.isfinite(scaled):
                finite_scaled_jacobian_sample_count += 1
                min_scaled = min(min_scaled, scaled)

            invalid = (
                not np.isfinite(determinant)
                or abs(determinant) <= jacobian_tolerance
            )
            if not invalid:
                sign = 1 if determinant > 0.0 else -1
                if orientation_sign is None:
                    orientation_sign = sign
                elif sign != orientation_sign:
                    invalid = True
                    orientation_flip_count += 1
            if invalid:
                invalid_count += 1
                invalid_elements.add(_element_number(element))
            if not np.isfinite(scaled) or scaled < min_scaled_jacobian:
                low_scaled_count += 1
                low_scaled_elements.add(_element_number(element))
        if orientation_sign == 1:
            positive_orientation_element_count += 1
        elif orientation_sign == -1:
            negative_orientation_element_count += 1

    materials = sorted({_mesh_label(value) for value in mesh.GetMaterials()})
    boundaries = sorted({_mesh_label(value) for value in mesh.GetBoundaries()})
    missing_materials = sorted(_labels(required_materials) - set(materials))
    missing_boundaries = sorted(_labels(required_boundaries) - set(boundaries))
    adjacency, adjacency_warnings = _face_adjacency_quality(
        mesh,
        conductive_materials,
        air_materials,
        sibc_boundaries,
        require_all_sibc_labeled,
    )

    warnings = list(adjacency_warnings)
    if curve_order < min_curve_order:
        warnings.append(f"curve order {curve_order} is below required order {min_curve_order}")
    if invalid_count:
        warnings.append(
            f"{invalid_count} mapping samples are singular, non-finite, or "
            "change orientation within an element"
        )
    if low_scaled_count:
        warnings.append(
            f"{low_scaled_count} mapping samples are below scaled Jacobian "
            f"{min_scaled_jacobian:g}"
        )
    if require_tetrahedra and tetrahedron_count != volume_element_count:
        warnings.append(
            f"{volume_element_count - tetrahedron_count} volume elements are not tetrahedra")
    if missing_materials:
        warnings.append("missing materials: " + ", ".join(missing_materials))
    if missing_boundaries:
        warnings.append("missing boundaries: " + ", ".join(missing_boundaries))

    return {
        "passed": not warnings,
        "curve_order": curve_order,
        "integration_order": sample_order,
        "volume_element_count": volume_element_count,
        "tetrahedron_count": tetrahedron_count,
        "mapping_sample_count": sample_count,
        "finite_jacobian_sample_count": finite_jacobian_sample_count,
        "finite_scaled_jacobian_sample_count": finite_scaled_jacobian_sample_count,
        "minimum_jacobian": (
            None if finite_jacobian_sample_count == 0 else min_det
        ),
        "maximum_jacobian": (
            None if finite_jacobian_sample_count == 0 else max_det
        ),
        "minimum_absolute_jacobian": (
            None if finite_jacobian_sample_count == 0 else min_abs_det
        ),
        "minimum_scaled_jacobian": (
            None if finite_scaled_jacobian_sample_count == 0 else min_scaled
        ),
        "invalid_jacobian_sample_count": invalid_count,
        "orientation_flip_sample_count": orientation_flip_count,
        "negative_jacobian_sample_count": negative_jacobian_sample_count,
        "positive_orientation_element_count": positive_orientation_element_count,
        "negative_orientation_element_count": negative_orientation_element_count,
        "low_scaled_jacobian_sample_count": low_scaled_count,
        "invalid_jacobian_elements": sorted(invalid_elements)[:50],
        "low_scaled_jacobian_elements": sorted(low_scaled_elements)[:50],
        "materials": materials,
        "boundaries": boundaries,
        "missing_materials": missing_materials,
        "missing_boundaries": missing_boundaries,
        "adjacency": adjacency,
        "warnings": warnings,
    }


def _load_json_object(path, description):
    try:
        payload = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    except OSError as exc:
        raise ValueError(f"could not read {description} {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid {description} JSON {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{description} must be a JSON object")
    return payload


def _reference_values(cad_reference, name):
    values = cad_reference.get(name, {})
    if values is None:
        return {}
    if not isinstance(values, Mapping):
        raise ValueError(f"CAD reference {name!r} entry must be an object")
    checked = {}
    for label, value in values.items():
        number = float(value)
        if not np.isfinite(number) or number < 0.0:
            raise ValueError(
                f"CAD reference {name}.{label} must be finite and non-negative"
            )
        checked[str(label)] = number
    return checked


def _reference_labels(cad_reference, name):
    values = cad_reference.get(name, [])
    if values is None:
        return []
    if not isinstance(values, list):
        raise ValueError(f"CAD reference {name!r} entry must be an array")
    checked = []
    for index, value in enumerate(values):
        label = str(value).strip()
        if not label:
            raise ValueError(f"CAD reference {name}[{index}] must be a non-empty label")
        if label not in checked:
            checked.append(label)
    return checked


def _unique_messages(messages):
    return list(dict.fromkeys(str(message) for message in messages if str(message)))


def _finite_measurement(value, description):
    number = float(value)
    if not np.isfinite(number):
        raise ValueError(f"NGSolve {description} is not finite")
    return number


def check_consistency(
    vol_path,
    json_path=None,
    threshold=1.0,
    *,
    quality=True,
    contract=None,
    strict_labels=False,
    required_materials=(),
    required_boundaries=(),
    required_bboundaries=(),
    required_bbboundaries=(),
    **quality_options,
):
    """Run the complete standalone gate for a Netgen ``.vol`` mesh.

    The mesh, label inventory, and (by default) curved-map quality are always
    checked.  ``vol_path + '.json'`` is used as a CAD reference when it exists;
    an explicitly supplied ``json_path`` is required to exist.  Material
    constants are intentionally outside this checker and remain owned by the
    application's DesignSpec/configuration contract.
    """
    from ngsolve import BND, BBND, CF, Integrate, Mesh, TaskManager

    threshold = float(threshold)
    if not np.isfinite(threshold) or threshold < 0.0:
        raise ValueError("threshold must be finite and non-negative")

    vol_file = Path(vol_path)
    if not vol_file.is_file():
        raise FileNotFoundError(f".vol mesh not found: {vol_file}")

    explicit_json = json_path is not None
    cad_file = Path(json_path) if explicit_json else Path(str(vol_file) + ".json")
    if explicit_json and not cad_file.is_file():
        raise FileNotFoundError(f"CAD reference not found: {cad_file}")
    cad_available = cad_file.is_file()
    cad_reference = (
        _load_json_object(cad_file, "CAD reference") if cad_available else {}
    )
    boundary_domain_ownership = check_vol_boundary_domain_ownership(vol_file)

    label_contract = _load_label_contract(contract)
    contract_quality = label_contract.get("quality", {})
    if contract_quality is None:
        contract_quality = {}
    if not isinstance(contract_quality, Mapping):
        raise ValueError("label contract 'quality' entry must be an object")
    for key, value in contract_quality.items():
        quality_options.setdefault(str(key), value)

    mesh = Mesh(str(vol_file))
    labels = check_label_contract(
        mesh,
        contract=label_contract or None,
        strict=strict_labels,
        required_materials=required_materials,
        required_boundaries=required_boundaries,
        required_bboundaries=required_bboundaries,
        required_bbboundaries=required_bbboundaries,
    )
    quality_result = (
        check_mesh_quality(mesh, **quality_options) if quality else None
    )

    warnings = list(labels["warnings"])
    warnings.extend(boundary_domain_ownership["issues"])
    if quality_result is not None:
        warnings.extend(quality_result["warnings"])

    cad_volumes = _reference_values(cad_reference, "materials")
    cad_areas = _reference_values(cad_reference, "boundaries")
    cad_lengths = _reference_values(cad_reference, "edges")
    mesh_only_materials = _reference_labels(cad_reference, "mesh_only_materials")
    overlap = sorted(set(cad_volumes) & set(mesh_only_materials))
    if overlap:
        raise ValueError(
            "CAD reference materials and mesh_only_materials overlap: "
            + ", ".join(overlap)
        )

    materials = []
    boundaries = []
    edges = []
    with TaskManager():
        for material in labels["materials"]:
            ng_volume = _finite_measurement(
                Integrate(CF(1), mesh, definedon=mesh.Materials(material)),
                f'volume for material "{material}"',
            )
            entry = {"name": material, "ng_volume": ng_volume}
            if material in cad_volumes:
                cad_volume = cad_volumes[material]
                entry["cad_volume"] = cad_volume
                if cad_volume > 0.0:
                    error = (ng_volume - cad_volume) / cad_volume * 100.0
                    entry["error_pct"] = error
                    if abs(error) > threshold:
                        warnings.append(
                            f'Volume "{material}": {error:+.2e}% '
                            f"(ng={ng_volume:.6e}, cad={cad_volume:.6e})"
                        )
            elif material in mesh_only_materials:
                entry["cad_reference_status"] = "mesh_only_no_cad_volume"
            materials.append(entry)

        for boundary in labels["boundaries"]:
            ng_area = _finite_measurement(
                Integrate(
                    CF(1), mesh, BND,
                    definedon=mesh.Boundaries(boundary),
                    order=16,
                ),
                f'area for boundary "{boundary}"',
            )
            entry = {"name": boundary, "ng_area": ng_area}
            if boundary in cad_areas:
                cad_area = cad_areas[boundary]
                entry["cad_area"] = cad_area
                if cad_area > 0.0:
                    error = (ng_area - cad_area) / cad_area * 100.0
                    entry["error_pct"] = error
                    if abs(error) > threshold:
                        warnings.append(
                            f'Area "{boundary}": {error:+.2e}% '
                            f"(ng={ng_area:.6e}, cad={cad_area:.6e})"
                        )
            boundaries.append(entry)

        edge_error = None
        total_ng_length = None
        try:
            total_ng_length = _finite_measurement(
                Integrate(CF(1), mesh, BBND), "total BBND length"
            )
            for edge in labels["bboundaries"]:
                ng_length = _finite_measurement(
                    Integrate(
                        CF(1), mesh, BBND,
                        definedon=mesh.BBoundaries(edge),
                    ),
                    f'length for BBND "{edge}"',
                )
                entry = {"name": edge, "ng_length": ng_length}
                if edge in cad_lengths:
                    entry["cad_length"] = cad_lengths[edge]
                edges.append(entry)
        except Exception as exc:
            edge_error = str(exc)

    measured_edge_names = {entry["name"] for entry in edges}
    for edge, cad_length in sorted(cad_lengths.items()):
        if edge not in measured_edge_names:
            edges.append({"name": edge, "cad_length": cad_length})

    if cad_available:
        mesh_materials = set(labels["materials"])
        mesh_boundaries = set(labels["boundaries"])
        for label in sorted(set(cad_volumes) - mesh_materials):
            warnings.append(f'CAD material "{label}" is absent from the mesh')
        for label in sorted(set(mesh_only_materials) - mesh_materials):
            warnings.append(f'Mesh-only material "{label}" is absent from the mesh')
        referenced_materials = set(cad_volumes) | set(mesh_only_materials)
        for label in sorted(mesh_materials - referenced_materials):
            warnings.append(f'Material "{label}" has no CAD volume reference')
        for label in sorted(set(cad_areas) - mesh_boundaries):
            warnings.append(f'CAD boundary "{label}" is absent from the mesh')
        for label in sorted(mesh_boundaries - set(cad_areas)):
            warnings.append(f'Boundary "{label}" has no CAD area reference')

    total_edge_length = None
    if edge_error is not None and labels["bboundaries"] and not cad_lengths:
        warnings.append("Could not integrate BBND edge lengths: " + edge_error)
    if cad_lengths:
        total_cad_length = float(sum(cad_lengths.values()))
        if edge_error is not None or total_ng_length is None:
            warnings.append(
                "Could not integrate BBND edge length required by the CAD reference: "
                + (edge_error or "unknown error")
            )
        elif total_cad_length > 0.0:
            error = (
                (total_ng_length - total_cad_length)
                / total_cad_length * 100.0
            )
            total_edge_length = {
                "cad": total_cad_length,
                "ng": total_ng_length,
                "error_pct": error,
            }
            if abs(error) > threshold:
                warnings.append(
                    f"Total edge length: {error:+.2e}% "
                    f"(ng={total_ng_length:.6e}, cad={total_cad_length:.6e})"
                )

    mesh_summary = {
        "dimension": int(mesh.dim),
        "curve_order": int(mesh.GetCurveOrder()),
        "n_elements": int(mesh.ne),
        "n_points": int(mesh.nv),
    }
    metadata_checks = {}
    if cad_available:
        for key in ("n_elements", "n_points", "order"):
            if key not in cad_reference:
                continue
            raw_expected = cad_reference[key]
            if isinstance(raw_expected, bool):
                raise ValueError(f"CAD metadata {key} must be a non-negative integer")
            try:
                expected_number = float(raw_expected)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"CAD metadata {key} must be a non-negative integer"
                ) from exc
            if (
                not np.isfinite(expected_number)
                or expected_number < 0.0
                or not expected_number.is_integer()
            ):
                raise ValueError(f"CAD metadata {key} must be a non-negative integer")
            expected = int(expected_number)
            actual_key = "curve_order" if key == "order" else key
            actual = mesh_summary[actual_key]
            metadata_checks[key] = {
                "expected": expected,
                "actual": actual,
                "passed": expected == actual,
            }
            if expected != actual:
                warnings.append(
                    f"CAD metadata {key}: expected {expected}, mesh has {actual}"
                )

    warnings = _unique_messages(warnings)
    result = {
        "schema": REPORT_SCHEMA,
        **_runtime_metadata(),
        "passed": not warnings,
        "vol_file": str(vol_file),
        "json_file": str(cad_file) if cad_available else None,
        "threshold_pct": threshold,
        "cad_reference": {
            "available": cad_available,
            "file": str(cad_file) if cad_available else None,
            "auto_discovered": cad_available and not explicit_json,
            "mesh_only_materials": mesh_only_materials,
            "metadata_checks": metadata_checks,
        },
        "mesh": mesh_summary,
        "order": mesh_summary["curve_order"],
        "n_elements": mesh_summary["n_elements"],
        "n_points": mesh_summary["n_points"],
        "labels": labels,
        "quality": quality_result,
        "boundary_domain_ownership": boundary_domain_ownership,
        "materials": materials,
        "boundaries": boundaries,
        "edges": edges,
        "edge_check": {
            "available": edge_error is None,
            "error": edge_error,
            "per_edge_mapping": "best-effort",
            "total_length_comparison": "used for the CAD gate when edges exist",
        },
        "warnings": warnings,
    }
    if total_edge_length is not None:
        result["total_edge_length"] = total_edge_length
    return result


def print_table(results):
    """Print a human-readable summary of a ``check_consistency`` report."""
    print(f"Mesh: {results['vol_file']}")
    print(f"Threshold: {results['threshold_pct']}%")
    cad = results.get("cad_reference", {})
    print(
        "CAD reference: "
        + (str(cad.get("file")) if cad.get("available") else "not present (optional)")
    )
    print()

    labels = results.get("labels")
    if labels:
        print("  Label contract")
        print("  " + "-" * 64)
        print(
            f"  strict={labels['strict_labels']}, "
            f"materials={len(labels['materials'])}, "
            f"boundaries={len(labels['boundaries'])}, "
            f"BBND={len(labels['bboundaries'])}, "
            f"BBBND={len(labels['bbboundaries'])}"
        )
        print()

    quality = results.get("quality")
    if quality:
        print("  Curved mapping quality")
        print("  " + "-" * 64)
        print(
            f"  curve order={quality['curve_order']}, "
            f"elements={quality['volume_element_count']}, "
            f"samples={quality['mapping_sample_count']}")
        minimum_jacobian = quality["minimum_absolute_jacobian"]
        minimum_scaled = quality["minimum_scaled_jacobian"]
        if minimum_jacobian is None or minimum_scaled is None:
            print("  min |det(J)|=N/A, min scaled J=N/A")
        else:
            print(
                f"  min |det(J)|={minimum_jacobian:.6e}, "
                f"min scaled J={minimum_scaled:.6e}")
        print(
            "  element orientations: "
            f"+={quality['positive_orientation_element_count']}, "
            f"-={quality['negative_orientation_element_count']}"
        )
        adjacency = quality.get("adjacency", {})
        if adjacency.get("enabled"):
            print(f"  face roles={adjacency['face_role_counts']}")
        print()

    # Volume table
    if results["materials"]:
        print("  Material            CAD Volume      NG Volume       Error")
        print("  " + "-" * 64)
        for m in results["materials"]:
            cad_value = m.get("cad_volume")
            ng = m.get("ng_volume", 0)
            err = m.get("error_pct")
            err_s = f"{err:+.2e}%" if err is not None else "N/A"
            flag = (
                " ***"
                if err is not None and abs(err) > results["threshold_pct"]
                else ""
            )
            cad_s = f"{cad_value:.6e}" if cad_value is not None else "N/A"
            print(
                f"  {m['name']:<20s}{cad_s:>14s}  {ng:>14.6e}  "
                f"{err_s:>10s}{flag}"
            )
        print()

    # Area table
    if results["boundaries"]:
        print("  Boundary            CAD Area        NG Area         Error")
        print("  " + "-" * 64)
        for b in results["boundaries"]:
            cad_value = b.get("cad_area")
            ng = b.get("ng_area", 0)
            err = b.get("error_pct")
            err_s = f"{err:+.2e}%" if err is not None else "N/A"
            flag = (
                " ***"
                if err is not None and abs(err) > results["threshold_pct"]
                else ""
            )
            cad_s = f"{cad_value:.6e}" if cad_value is not None else "N/A"
            print(
                f"  {b['name']:<20s}{cad_s:>14s}  {ng:>14.6e}  "
                f"{err_s:>10s}{flag}"
            )
        print()

    # Length table
    if results["edges"]:
        print("  Edge                CAD Length      NG Length")
        print("  " + "-" * 52)
        for e in results["edges"]:
            cad_value = e.get("cad_length")
            ng = e.get("ng_length", 0)
            cad_s = f"{cad_value:.6e}" if cad_value is not None else "N/A"
            print(f"  {e['name']:<20s}{cad_s:>14s}  {ng:>14.6e}")
        # Total length check
        tot = results.get("total_edge_length")
        if tot:
            print("  " + "-" * 52)
            err_s = f"{tot['error_pct']:+.2e}%"
            flag = " ***" if abs(tot["error_pct"]) > results["threshold_pct"] else ""
            print(f"  {'TOTAL':<20s}{tot['cad']:>14.6e}  {tot['ng']:>14.6e}  {err_s}{flag}")
        print()

    # Warnings summary
    if results.get("warnings"):
        print(f"  WARNINGS ({len(results['warnings'])}):")
        for w in results["warnings"]:
            print(f"    - {w}")
    else:
        print("  All checks PASSED.")


def _write_report_json(path, payload):
    report_path = Path(path)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
        encoding="utf-8",
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Check a Netgen .vol mesh, its labels and curved mapping, and "
            "an optional CAD-reference sidecar"
        ))
    parser.add_argument("vol", help="Path to .vol mesh file")
    parser.add_argument("--json", default=None,
                        help=(
                            "Required CAD-reference JSON path (without this flag, "
                            "vol + .json is used only when it exists)"
                        ))
    parser.add_argument("--threshold", type=float, default=1.0,
                        help="Warning threshold in percent (default: 1.0)")
    quality_group = parser.add_mutually_exclusive_group()
    quality_group.add_argument(
        "--quality", dest="quality", action="store_true",
        help="Run curved-map quality checks (default)")
    quality_group.add_argument(
        "--no-quality", dest="quality", action="store_false",
        help="Skip curved-map sampling; label and CAD checks still run")
    parser.set_defaults(quality=True)
    parser.add_argument("--min-scaled-jacobian", type=float, default=1.0e-6,
                        help="Minimum sampled scaled Jacobian (default: 1e-6)")
    parser.add_argument(
        "--jacobian-tolerance", type=float, default=0.0,
        help="Minimum absolute det(J) before a sample is singular (default: 0)")
    parser.add_argument("--integration-order", type=int, default=None,
                        help=(
                            "Mapping sampling order (default: 1 for affine "
                            "meshes, otherwise 2*curve_order+2)"
                        ))
    parser.add_argument("--min-curve-order", type=int, default=1)
    parser.add_argument(
        "--tet-only", "--require-tet", dest="require_tet",
        action="store_true", help="Require every volume element to be a tetrahedron")
    parser.add_argument(
        "--contract", default=None,
        help=f"Path to a {LABEL_CONTRACT_SCHEMA} JSON label contract")
    parser.add_argument(
        "--strict-labels", action="store_true",
        help="Require canonical labels and reject generated fallback names")
    parser.add_argument("--required-materials", default="")
    parser.add_argument("--required-boundaries", default="")
    parser.add_argument("--required-bboundaries", default="")
    parser.add_argument("--required-bbboundaries", default="")
    parser.add_argument("--conductors", default="",
                        help="Comma-separated conductive material labels")
    parser.add_argument("--air-materials", default="air,vacuum")
    parser.add_argument("--sibc-boundaries", default="",
                        help="Comma-separated SIBC boundary labels")
    parser.add_argument("--require-all-sibc-labeled", action="store_true")
    parser.add_argument(
        "--format", choices=("text", "json"), default="text",
        help="Console report format (default: text)")
    parser.add_argument(
        "--report-json", default=None,
        help="Also write the versioned JSON report to this path")

    args = parser.parse_args(argv)
    try:
        results = check_consistency(
            args.vol,
            args.json,
            args.threshold,
            quality=args.quality,
            contract=args.contract,
            strict_labels=args.strict_labels,
            required_materials=args.required_materials,
            required_boundaries=args.required_boundaries,
            required_bboundaries=args.required_bboundaries,
            required_bbboundaries=args.required_bbboundaries,
            min_scaled_jacobian=args.min_scaled_jacobian,
            jacobian_tolerance=args.jacobian_tolerance,
            integration_order=args.integration_order,
            min_curve_order=args.min_curve_order,
            require_tetrahedra=args.require_tet,
            conductive_materials=args.conductors,
            air_materials=args.air_materials,
            sibc_boundaries=args.sibc_boundaries,
            require_all_sibc_labeled=args.require_all_sibc_labeled,
        )
    except Exception as exc:
        error = {
            "schema": REPORT_SCHEMA,
            **_runtime_metadata(),
            "passed": False,
            "error": str(exc),
        }
        if args.report_json:
            try:
                _write_report_json(args.report_json, error)
            except OSError as report_exc:
                error["report_error"] = str(report_exc)
        if args.format == "json":
            print(json.dumps(error, indent=2, ensure_ascii=False))
        else:
            print(f"ERROR: {exc}", file=sys.stderr)
            if error.get("report_error"):
                print(
                    f"ERROR: could not write report: {error['report_error']}",
                    file=sys.stderr,
                )
        return 2

    if args.report_json:
        try:
            _write_report_json(args.report_json, results)
        except OSError as exc:
            print(f"ERROR: could not write report: {exc}", file=sys.stderr)
            return 2
    if args.format == "json":
        print(json.dumps(results, indent=2, ensure_ascii=False))
    else:
        print_table(results)
    return 0 if results["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
