/*-------------------------------------------------------------------------
*
* File name:      rad_biot_savart_surface.h
*
* Project:        RADIA
*
* Description:    Biot-Savart B and A from a triangulated surface carrying a
*                 piecewise-constant complex surface current density J_s [A/m].
*                 Used to evaluate the field generated by the SIBC-induced
*                 surface current on the workpiece (J_s = -n x grad_s phi).
*
*                 Also used by the Telegen-reciprocity inductance helper to
*                 evaluate A_inc from PEEC filaments at workpiece centroids
*                 (that path uses _AFromSegmentsComplex; this file is for the
*                 inverse direction: workpiece -> arbitrary obs points).
*
* First release:  2026-04-30
*
-------------------------------------------------------------------------*/

#ifndef __RAD_BIOT_SAVART_SURFACE_H
#define __RAD_BIOT_SAVART_SURFACE_H

namespace radia { namespace bs {

/**
 * Magnetic vector potential A at observation points from a piecewise-constant
 * complex surface current density J_s [A/m] on a triangulated surface.
 *
 * Per triangle T with vertices v1, v2, v3 and (constant) J_s_T:
 *     A(P) += (mu_0/(4 pi)) * J_s_T * integral_T 1/|P - r'| dS'
 *
 * The integral is evaluated with 3-point Gauss quadrature (mid-edge points,
 * equal weights 1/3).  This is exact for linear integrands and gives ~1%
 * accuracy on the 1/r kernel for obs distances >= 1 triangle edge length.
 * For visualization / Telegen reciprocity at non-singular obs points, this
 * is sufficient.  Singular evaluation (obs on or very close to T) is NOT
 * supported -- use ngsolve.bem or analytical Wilton formulas for those.
 *
 * @param verts      (n_t, 3, 3) row-major: [tri][vertex][xyz]; double [m]
 * @param n_t        number of triangles
 * @param J_re,J_im  (n_t, 3) row-major: real/imag of J_s_T [A/m]
 * @param obs        (n_obs, 3) row-major; double [m]
 * @param n_obs      number of obs points
 * @param A_re_out   (n_obs, 3) row-major: real part of A output [T*m] (overwritten)
 * @param A_im_out   (n_obs, 3) row-major: imag part of A output [T*m] (overwritten)
 * @param n_threads  0 = TaskManager default; > 0 = request that many
 */
void AFromTrianglesComplex(
    const double* verts, int n_t,
    const double* J_re,
    const double* J_im,
    const double* obs, int n_obs,
    double* A_re_out,
    double* A_im_out,
    int n_threads);

/**
 * Magnetic flux density B at observation points from a piecewise-constant
 * complex surface current density J_s [A/m] on a triangulated surface.
 *
 * Per triangle T with vertices v1, v2, v3 and (constant) J_s_T:
 *     B(P) += (mu_0/(4 pi)) * integral_T (J_s_T x (P - r')) / |P - r'|^3 dS'
 *
 * Same 3-point Gauss quadrature as AFromTrianglesComplex.  Same caveats
 * about singular evaluation.
 *
 * @param verts      (n_t, 3, 3) row-major: [tri][vertex][xyz]; double [m]
 * @param n_t        number of triangles
 * @param J_re,J_im  (n_t, 3) row-major: real/imag of J_s_T [A/m]
 * @param obs        (n_obs, 3) row-major; double [m]
 * @param n_obs      number of obs points
 * @param B_re_out   (n_obs, 3) row-major: real part of B output [T] (overwritten)
 * @param B_im_out   (n_obs, 3) row-major: imag part of B output [T] (overwritten)
 * @param n_threads  0 = TaskManager default; > 0 = request that many
 */
void BFromTrianglesComplex(
    const double* verts, int n_t,
    const double* J_re,
    const double* J_im,
    const double* obs, int n_obs,
    double* B_re_out,
    double* B_im_out,
    int n_threads);

}}  // namespace radia::bs

#endif  // __RAD_BIOT_SAVART_SURFACE_H
