function optunaPrecision(action,varargin)
% Optional audit of real-double verifyEqual assertions, not a new oracle.
persistent output records provenance
switch action
    case 'begin'
        output=string(getenv('RADIA_OPTUNA_PRECISION_OUTPUT'));
        records={}; provenance=varargin{1};
    case 'record'
        if isempty(output)||strlength(output)==0, return; end
        actual=varargin{1}; expected=varargin{2};
        if ~isa(actual,'double')||~isa(expected,'double')|| ...
                ~isreal(actual)||~isreal(expected)||~isequal(size(actual),size(expected))
            return
        end
        entry=optunaFloatError(actual,expected);
        stack=dbstack;
        entry.test=stack(3).name;
        entry.line=stack(3).line;
        records{end+1}=entry;
    case 'finish'
        if isempty(output)||strlength(output)==0, return; end
        [status,host]=system('hostname'); assert(status==0);
        source=fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
            'test_optuna_upstream_oracle.m');
        digest=java.security.MessageDigest.getInstance('SHA-256');
        digest.update(unicode2native(fileread(source),'UTF-8'));
        sourceHash=lower(reshape(dec2hex(typecast(digest.digest(),'uint8'),2).',1,[]));
        result=struct('schema','radia.validation.optuna-float-precision.v1', ...
            'host',strtrim(host),'matlab',version, ...
            'test_source_file','tests/matlab/test_optuna_upstream_oracle.m', ...
            'test_source_sha256',sourceHash, ...
            'optuna_version',provenance.optuna_version, ...
            'oracle_python_version',provenance.python_version, ...
            'numpy_version',provenance.numpy_version, ...
            'scipy_version',provenance.scipy_version, ...
            'torch_version',provenance.torch_version, ...
            'cmaes_version',provenance.cmaes_version, ...
            'scope','Real-double equality assertions, including numeric metadata and internal consistency checks; nested structures are not traversed.', ...
            'relative_definition','abs(actual-expected)/abs(expected); zero references excluded and mismatches counted separately.', ...
            'ulp_definition','Binary64 representable-value distance; signed zeros equivalent; exact uint64 distance serialized as decimal text.', ...
            'pairs','[actual MATLAB, expected]; each maximum has its own pair.', ...
            'comparisons',{records});
        fid=fopen(output,'w'); assert(fid>=0);
        cleanup=onCleanup(@()fclose(fid));
        fprintf(fid,'%s',jsonencode(result,PrettyPrint=true));
        output=""; records={};
end
end
