"""Tier 7 — poster_from_pptx.

Many Japanese researchers draft posters in PowerPoint first. This tool
converts a .pptx into a Kelvin-style A1 portrait .tex skeleton — the
user then fine-tunes the structure rather than building from scratch.

Lazy-imports python-pptx; install with ``mcp-server-document[pptx]``.
"""
from __future__ import annotations

import pathlib
import re


def _slug(s: str, maxlen: int = 30) -> str:
    s = re.sub(r"[^\w\-]+", "_", s, flags=re.UNICODE)
    return s.strip("_")[:maxlen] or "section"


def _escape(s: str) -> str:
    return (s.replace("\\", "\\textbackslash{}")
             .replace("&", "\\&").replace("%", "\\%")
             .replace("$", "\\$").replace("#", "\\#")
             .replace("_", "\\_").replace("{", "\\{")
             .replace("}", "\\}").replace("~", "\\textasciitilde{}")
             .replace("^", "\\textasciicircum{}"))


def poster_from_pptx(pptx_path: str,
                     out_tex_path: str | None = None) -> str:
    """Convert a PowerPoint poster draft to a Kelvin-style A1 .tex.

    Each slide becomes one ``contentbox``. The first slide's title is
    promoted to the poster title; subsequent slide titles become
    ``subsectionbox`` headings inside their respective ``contentbox``.

    Args:
        pptx_path: Path to the input ``.pptx``.
        out_tex_path: Optional path to write the generated ``.tex``. If
                      None, the source is returned as a string.

    Returns:
        Status string when ``out_tex_path`` is given; .tex source otherwise.
    """
    try:
        from pptx import Presentation  # type: ignore
    except ImportError:
        return ("Error: python-pptx not installed. Install with "
                "`pip install -e .[pptx]`.")
    p = pathlib.Path(pptx_path)
    if not p.is_absolute():
        p = pathlib.Path.cwd() / p
    if not p.exists():
        return f"Error: file not found: {p}"

    prs = Presentation(p)
    slides = list(prs.slides)
    if not slides:
        return f"Error: {p} has no slides"

    title_text = ""
    body_blocks: list[tuple[str, list[str]]] = []
    for i, slide in enumerate(slides):
        heading = ""
        paragraphs: list[str] = []
        for shape in slide.shapes:
            if not shape.has_text_frame:
                continue
            for para in shape.text_frame.paragraphs:
                txt = "".join(run.text for run in para.runs).strip()
                if not txt:
                    continue
                # First non-empty text on slide 0 = title; on later slides = heading.
                if not heading and not (i == 0 and not title_text):
                    heading = txt
                elif i == 0 and not title_text:
                    title_text = txt
                else:
                    paragraphs.append(txt)
        body_blocks.append((heading or f"スライド {i+1}", paragraphs))

    parts = [
        "\\documentclass[a1paper,portrait]{bxjsarticle}",
        "\\usepackage[dvipdfmx]{graphicx,color}",
        "\\usepackage{amsmath,multicol,enumitem,bm,geometry}",
        "\\geometry{margin=2cm,top=1cm,bottom=1cm}",
        "\\usepackage{tikz,tcolorbox,caption,anyfontsize,xcolor}",
        "\\tcbuselibrary{breakable,skins}",
        "\\usepackage{newtxtext,newtxmath}",
        "\\renewcommand{\\familydefault}{\\sfdefault}",
        "\\definecolor{headercolor}{RGB}{0,51,153}",
        "\\definecolor{sectionblue}{RGB}{51,102,204}",
        "\\tcbset{",
        "  sectionbox/.style={colback=sectionblue,coltext=white,boxrule=0pt,arc=5mm,"
        "left=15pt,right=15pt,top=10pt,bottom=10pt,fontupper=\\Large\\bfseries},",
        "  contentbox/.style={colback=white,colframe=sectionblue,boxrule=2pt,arc=3mm,"
        "boxsep=10pt,left=10pt,right=10pt,top=10pt,bottom=10pt},",
        "  subsectionbox/.style={colback=sectionblue!15,coltext=sectionblue!80!black,"
        "boxrule=0pt,arc=3mm,left=12pt,right=12pt,top=6pt,bottom=6pt,fontupper=\\large\\bfseries},",
        "}",
        "\\begin{document}",
        "% --- Header (auto-generated by poster_from_pptx) ---",
        "\\begin{flushleft}",
        f"  {{\\fontsize{{60}}{{72}}\\selectfont\\bfseries\\color{{headercolor}} {_escape(title_text or 'Poster Title')}}}",
        "\\end{flushleft}",
        "\\hrule",
        "\\vspace{10pt}",
        "\\begin{multicols}{2}",
    ]

    for heading, paragraphs in body_blocks:
        parts.append("\\begin{tcolorbox}[contentbox,breakable]")
        parts.append("  \\begin{tcolorbox}[subsectionbox]")
        parts.append(f"    {{\\fontsize{{30pt}}{{36pt}}\\selectfont {_escape(heading)}}}")
        parts.append("  \\end{tcolorbox}")
        parts.append("  {\\fontsize{24pt}{33pt}\\selectfont")
        for para in paragraphs:
            parts.append(f"  {_escape(para)}\\par")
        parts.append("  }")
        parts.append("\\end{tcolorbox}")

    parts.append("\\end{multicols}")
    parts.append("\\end{document}")

    src = "\n".join(parts)
    if out_tex_path is None:
        return src
    out = pathlib.Path(out_tex_path)
    if not out.is_absolute():
        out = pathlib.Path.cwd() / out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(src, encoding="utf-8")
    return f"poster_from_pptx: wrote {out}\n  slides ingested: {len(body_blocks)}"
