"""One-shot generator: introspect build123d, write `build123d_api.py`.

Not run at MCP server import (too slow); run manually when we want a
refreshed snapshot of the build123d API. The generated `.py` ships in
the wheel and is loaded as one of the bundled KB topics.

Usage:
    python -m radia_mcp.build123d._gen_api_reference

Output:
    radia_mcp/build123d/build123d_api.py  (overwritten)
"""

from __future__ import annotations

import inspect
from pathlib import Path


def _is_b3d_native(obj) -> bool:
	mod = getattr(obj, "__module__", "") or ""
	return mod.startswith("build123d")


def _first_line(doc: str | None) -> str:
	if not doc:
		return ""
	lines = [ln.strip() for ln in doc.splitlines() if ln.strip()]
	if not lines:
		return ""
	return lines[0][:200]


def _sig(obj) -> str:
	try:
		return str(inspect.signature(obj))
	except (TypeError, ValueError):
		return ""


def _classify(cls) -> str:
	"""Category for ordering inside the output."""
	name = cls.__name__
	bases = {b.__name__ for b in cls.__mro__}
	if name.startswith("Build") or "Builder" in bases:
		return "1_builder"
	if name in {"Box", "Cylinder", "Sphere", "Cone", "Torus", "Wedge"}:
		return "2_primitive_3d"
	if name in {"Rectangle", "Circle", "Polygon", "Ellipse", "RegularPolygon",
	            "SlotArc", "SlotCenterPoint", "SlotCenterToCenter",
	            "SlotOverall", "Text", "Trapezoid", "Triangle", "Arrow",
	            "DoubleArrow", "TriangularNumber", "Airfoil"}:
		return "3_primitive_2d"
	if name in {"Plane", "Axis", "Location", "Locations", "Color",
	            "Vector", "Matrix", "Pos", "Rot"}:
		return "4_geometry"
	if name in {"Shape", "Part", "Sketch", "Edge", "Wire", "Face",
	            "Solid", "Shell", "Compound", "Vertex", "Curve"}:
		return "5_topology"
	if name.endswith("Joint") or name == "Joint":
		return "6_joint"
	if name.endswith("Mode") or name in {"Align", "Keep", "Kind",
	                                       "GeomType", "Select", "SortBy"}:
		return "7_enum"
	return "8_other"


def generate() -> str:
	import build123d  # late import — not required unless generating
	out: list[str] = []
	out.append('"""Auto-generated API reference for build123d.\n\n'
	           'Generated by `_gen_api_reference.py` — do not edit by hand.\n'
	           'Regenerate when bumping build123d in the environment.\n'
	           '"""')
	out.append("")
	out.append("API_REFERENCE = '''# build123d API reference (auto-generated)")
	out.append("")
	out.append(f"build123d version: {getattr(build123d, '__version__', '?')}")
	out.append("")

	names = sorted(
		n for n in dir(build123d)
		if not n.startswith("_")
	)
	classes: list[tuple[str, str, type]] = []  # (category, name, cls)
	funcs: list[tuple[str, callable]] = []

	for n in names:
		obj = getattr(build123d, n)
		if not _is_b3d_native(obj):
			continue
		if inspect.isclass(obj):
			classes.append((_classify(obj), n, obj))
		elif inspect.isfunction(obj):
			funcs.append((n, obj))

	# ---- Functions ----
	out.append("## Functions (module-level, Algebra API)")
	out.append("")
	for name, fn in sorted(funcs):
		sig = _sig(fn)
		doc = _first_line(inspect.getdoc(fn))
		out.append(f"### {name}{sig}")
		if doc:
			out.append(f"- {doc}")
		out.append("")

	# ---- Classes, grouped by category ----
	cat_headings = {
		"1_builder": "## Builder classes (context-manager API)",
		"2_primitive_3d": "## 3D primitives",
		"3_primitive_2d": "## 2D primitives",
		"4_geometry": "## Geometry primitives (Plane / Axis / Location / Vector / Color)",
		"5_topology": "## Topology (Shape / Part / Sketch / Edge / Face / Wire / Vertex / Compound / Solid)",
		"6_joint": "## Joints (assembly kinematics)",
		"7_enum": "## Enums (Align / Mode / Keep / Kind / GeomType / SortBy / …)",
		"8_other": "## Other (helpers, section-makers, …)",
	}
	# Stable sort by category key then name
	classes.sort(key=lambda t: (t[0], t[1]))
	last_cat = None
	for cat, name, cls in classes:
		if cat != last_cat:
			out.append("")
			out.append(cat_headings.get(cat, f"## {cat}"))
			out.append("")
			last_cat = cat
		bases = [b.__name__ for b in cls.__mro__[1:] if _is_b3d_native(b)]
		bases_str = f" : {', '.join(bases[:3])}" if bases else ""
		out.append(f"### class {name}{bases_str}")
		cdoc = _first_line(inspect.getdoc(cls))
		if cdoc:
			out.append(f"- {cdoc}")
		# __init__ signature
		try:
			init = cls.__init__
			if init is not object.__init__:
				out.append(f"- ctor: `{name}{_sig(init)}`")
		except (TypeError, ValueError):
			pass
		# Public methods defined in build123d (skip inherited stdlib / typing)
		methods = []
		for mname, m in inspect.getmembers(cls):
			if mname.startswith("_"):
				continue
			if not _is_b3d_native(m):
				continue
			if inspect.isfunction(m) or inspect.ismethod(m):
				methods.append((mname, m))
		if methods:
			# Cap per-class to keep the file sane (take the first 10 by name)
			methods.sort(key=lambda t: t[0])
			for mname, m in methods[:10]:
				sig = _sig(m)
				mdoc = _first_line(inspect.getdoc(m))
				line = f"  - `{mname}{sig}`"
				if mdoc:
					line += f" — {mdoc[:140]}"
				out.append(line)
			if len(methods) > 10:
				out.append(f"  - … +{len(methods) - 10} more methods")
		out.append("")

	out.append("'''")
	out.append("")
	out.append("def get_api_reference() -> str:")
	out.append('    """Return the full bundled build123d API reference."""')
	out.append("    return API_REFERENCE")

	return "\n".join(out)


def main() -> None:
	body = generate()
	target = Path(__file__).with_name("build123d_api.py")
	target.write_text(body, encoding="utf-8")
	line_count = body.count("\n")
	print(f"wrote {target} ({len(body)} bytes, {line_count} lines)")


if __name__ == "__main__":
	main()
