"""Codegen for Q3 Henrotte: JSON Mathematica strings -> C++ inline functions.

Output:
    src/q3_henrotte_generated.hpp   (auto-generated)
    scripts/q3_henrotte_test_values.json

Generated functions (analogous to Q2 but for the 16-monomial tensor product):
    KPhiGeneral(sa, sb, za, zb, muR, muZ, K[256])
    MSigmaPhiGeneral(sa, sb, za, zb, sigma, M[256])
    KPhiAxis(sb, za, zb, muR, muZ, K[144])
    MSigmaPhiAxis(sb, za, zb, sigma, M[144])
"""
from __future__ import annotations

import json
from pathlib import Path

import sympy
from sympy.parsing.mathematica import parse_mathematica
from sympy.printing.c import C99CodePrinter

JSON_PATH = Path(
    "W:/30_CauerLadderNetwork/2026_04_01_長方形CLN/axifemm/"
    "quad_q3_henrotte_matrices.json"
)
HEADER_PATH = Path(__file__).resolve().parent.parent / "src" / "q3_henrotte_generated.hpp"
TEST_VALUES_PATH = Path(__file__).resolve().parent / "q3_henrotte_test_values.json"


class _Printer(C99CodePrinter):
    def _print_Pi(self, expr):
        return "PI"

    def _print_Pow(self, expr):
        if expr.exp.is_Integer and 1 < int(expr.exp) <= 8:
            n = int(expr.exp)
            base = self._print(expr.base)
            return "(" + "*".join([base] * n) + ")"
        if expr.exp.is_Integer and int(expr.exp) == -1:
            base = self._print(expr.base)
            return f"(1.0/({base}))"
        return super()._print_Pow(expr)


def to_ccode(expr) -> str:
    return _Printer().doprint(expr)


def parse_entries(entries):
    return [parse_mathematica(s) for s in entries]


def emit_function(name, args_decl, exprs, out_var, n):
    lines = [f"inline void {name}({args_decl}, double {out_var}[{n}])"]
    lines.append("{")
    lines.append("    using std::log;")
    for i, e in enumerate(exprs):
        if e == 0:
            lines.append(f"    {out_var}[{i}] = 0.0;")
        else:
            code = to_ccode(e)
            lines.append(f"    {out_var}[{i}] = {code};")
    lines.append("}")
    return "\n".join(lines)


def main():
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    print("Parsing K_phi general (256)...")
    k_g = parse_entries(data["K_phi_general_strings"])
    print("Parsing M_sigma_phi general (256)...")
    m_g = parse_entries(data["M_sigma_phi_general_strings"])
    print("Parsing K_phi axis (144)...")
    k_a = parse_entries(data["K_phi_axis_strings"])
    print("Parsing M_sigma_phi axis (144)...")
    m_a = parse_entries(data["M_sigma_phi_axis_strings"])

    print("Emitting C++ functions...")

    args_kg = ("double sa, double sb, double za, double zb, "
               "double muR, double muZ")
    args_mg = "double sa, double sb, double za, double zb, double sigma"
    args_ka = "double sb, double za, double zb, double muR, double muZ"
    args_ma = "double sb, double za, double zb, double sigma"

    body_kg = emit_function("KPhiGeneral", args_kg, k_g, "K", 256)
    body_mg = emit_function("MSigmaPhiGeneral", args_mg, m_g, "M", 256)
    body_ka = emit_function("KPhiAxis", args_ka, k_a, "K", 144)
    body_ma = emit_function("MSigmaPhiAxis", args_ma, m_a, "M", 144)

    header = f"""\
// q3_henrotte_generated.hpp — AUTO-GENERATED by scripts/codegen_q3_henrotte.py
// Source JSON: axifemm/quad_q3_henrotte_matrices.json
// DO NOT EDIT MANUALLY.
//
// Q3 Henrotte axisymmetric element matrices in MONOMIAL coefficient basis:
//   general (16 mons): {{s^a z^b : 0 <= a,b <= 3}}, ordered (a major, b minor):
//                      {{1, z, z^2, z^3, s, sz, sz^2, sz^3, s^2, s^2z, s^2z^2,
//                       s^2z^3, s^3, s^3z, s^3z^2, s^3z^3}}
//   axis    (12 mons): drop the 4 a=0 monomials -> {{s^a z^b : 1 <= a <= 3, 0 <= b <= 3}}
// (Conditioning of the 16x16 Vandermonde for double precision is ~1e6-1e8;
//  borderline but workable. Use orthogonal basis for Q4+.)
//
// Convention: Hessian-of-W (matches Phase A2 / axifemm_quad.py).
//
// Index layout: row-major (entry index = row*N + col), N = 16 (general) or 12 (axis).

#ifndef RADIA_AXIFEMM_Q3_HENROTTE_GENERATED_HPP
#define RADIA_AXIFEMM_Q3_HENROTTE_GENERATED_HPP

#include <cmath>

namespace radia_axifemm {{
namespace q3_henrotte {{

inline constexpr double PI = 3.14159265358979323846;

{body_kg}

{body_mg}

{body_ka}

{body_ma}

}}  // namespace q3_henrotte
}}  // namespace radia_axifemm

#endif  // RADIA_AXIFEMM_Q3_HENROTTE_GENERATED_HPP
"""
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(header, encoding="utf-8")
    print(f"  -> {HEADER_PATH}  ({len(header):,} bytes)")

    print("Computing reference values for tests...")
    sigma_Cu = sympy.Rational("5.8e7")
    mu0 = 4 * sympy.pi * sympy.Rational("1e-7")

    subs_general_named = {"sa": sympy.Rational("1e-6"), "sb": sympy.Rational("4e-6"),
                          "za": 0, "zb": sympy.Rational("1e-3"),
                          "muR": mu0, "muZ": mu0, "sigma": sigma_Cu}
    subs_axis_named = {"sb": sympy.Rational("4e-6"), "za": 0, "zb": sympy.Rational("1e-3"),
                       "muR": mu0, "muZ": mu0, "sigma": sigma_Cu}

    def numeval(exprs, subs_named):
        out = []
        for e in exprs:
            subs = {sym: subs_named[sym.name] for sym in e.free_symbols
                    if sym.name in subs_named}
            out.append(float(sympy.N(e.subs(subs), 30)))
        return out

    test_values = {
        "test_params_general": {"sa": 1e-6, "sb": 4e-6, "za": 0.0, "zb": 1e-3,
                                "muR": 4*3.141592653589793e-7, "muZ": 4*3.141592653589793e-7,
                                "sigma": 5.8e7},
        "test_params_axis": {"sb": 4e-6, "za": 0.0, "zb": 1e-3,
                             "muR": 4*3.141592653589793e-7, "muZ": 4*3.141592653589793e-7,
                             "sigma": 5.8e7},
        "K_phi_general": numeval(k_g, subs_general_named),
        "M_sigma_phi_general": numeval(m_g, subs_general_named),
        "K_phi_axis": numeval(k_a, subs_axis_named),
        "M_sigma_phi_axis": numeval(m_a, subs_axis_named),
    }
    TEST_VALUES_PATH.write_text(json.dumps(test_values, indent=2), encoding="utf-8")
    print(f"  -> {TEST_VALUES_PATH}")
    print("Done.")


if __name__ == "__main__":
    main()
