"""Canonical high-order Lie maps for accelerator-magnet topology design.

The map coordinates are ``(x, px/p0, y, py/p0, ell, delta)``.  The
longitudinal pair has the opposite sign used by the existing Radia static-
magnet convention.  A fourth-degree curvilinear body-field Hamiltonian is
expanded into symmetric ``H2/H3/H4`` tensors, propagated with forward-mode
algorithmic differentiation, and converted to the Dragt--Finn form

``M = R o exp(:f3:) o exp(:f4:) o exp(:f5:) + O(z**5)``.

Here ``exp(:f:)`` denotes the canonical Hamiltonian flow on coordinates.  The
The fourth-order path reconstructs ``R/T/U/V`` and is formally symplectic
through fourth map order.  It includes the fourth-order coordinate terms
generated by the exact ``H2/H3/H4`` body Hamiltonian and all of their lower-
order cascades; it does not pretend that a direct ``H5``/decapole field term
is present.
The native C++ variational kernel remains an independent value oracle for the
unprojected Hamiltonian jet.  Mathematica is used only for the tracked
symbolic derivation/golden; it is not a runtime dependency.

The physical scope is explicit: source-free, piecewise-constant body
multipoles through octupole, one horizontal reference curvature per segment,
and optional finite-reference-speed slip.  Longitudinal fringe/edge vector
potentials and closed-orbit recovery require additional field derivatives and
are not fabricated by this module.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import permutations
from math import factorial

import numpy as np
from scipy.linalg import expm, expm_frechet

from .accelerator_magnet_topopt import (
    PlanarDesignOrbit,
    differentiate_transfer_matrix_field_response,
)
from .accelerator_taylor_topopt import (
    THIRD_ORDER_MULTIPOLE_COMPONENTS,
    PlanarThirdOrderTaylorMapObjective,
    _compose_third_order,
    _cross_second_order,
    _cross_second_order_tangent,
    _finite_array,
    _identity_third_order,
    _third_order_rhs,
    _third_order_rk4_step,
    _unpack_third_order_multipoles,
    optimize_hdiv_mmm_magnet_from_third_order_taylor_map,
    run_third_order_taylor_material_inverse_pipeline,
)


_ALL_SYMMETRIC_V_ENTRIES = tuple(
    (output, first, second, third, fourth)
    for output in range(6)
    for first in range(6)
    for second in range(first, 6)
    for third in range(second, 6)
    for fourth in range(third, 6)
)


def canonical_poisson_matrix() -> np.ndarray:
    """Return the Radia six-dimensional static-magnet Poisson matrix."""
    result = np.zeros((6, 6), dtype=float)
    for position, momentum, sign in ((0, 1, 1.0), (2, 3, 1.0), (4, 5, -1.0)):
        result[position, momentum] = sign
        result[momentum, position] = -sign
    return result


_POISSON = canonical_poisson_matrix()


def _add_hamiltonian_monomial(
    tensor, tangent, powers, coefficient, coefficient_tangent
):
    degree = int(sum(powers))
    if degree != tensor.ndim:
        raise ValueError("Hamiltonian tensor rank does not match monomial degree")
    derivative = float(coefficient)
    derivative_tangent = np.asarray(coefficient_tangent, dtype=float).copy()
    inputs: list[int] = []
    for coordinate, power in enumerate(powers):
        derivative *= factorial(int(power))
        derivative_tangent *= factorial(int(power))
        inputs.extend([coordinate] * int(power))
    for ordered in set(permutations(inputs)):
        tensor[ordered] += derivative
        tangent[(slice(None),) + ordered] += derivative_tangent


@dataclass(frozen=True)
class CanonicalHamiltonianJet:
    """Symmetric Hamiltonian tensors and their Hamiltonian vector-field jet."""

    H2: np.ndarray
    H3: np.ndarray
    H4: np.ndarray
    A: np.ndarray
    F2: np.ndarray
    F3: np.ndarray
    H2_jacobian: np.ndarray
    H3_jacobian: np.ndarray
    H4_jacobian: np.ndarray
    A_jacobian: np.ndarray
    F2_jacobian: np.ndarray
    F3_jacobian: np.ndarray
    reference_beta: float


def canonical_body_hamiltonian_jet(
    coefficients,
    magnetic_rigidity,
    *,
    curvature_sign=1.0,
    gradient_sign=1.0,
    reference_beta=1.0,
) -> CanonicalHamiltonianJet:
    """Build the fourth-degree canonical body-multipole Hamiltonian.

    The exact parent Hamiltonian is the scaled curvilinear expression

    ``-(1+h*x)*sqrt((1+delta)^2-px^2-py^2) - a_s + H_ref(delta)``.

    ``a_s`` is the covariant longitudinal vector potential.  Its dipole term
    cancels the reference-orbit linear force and supplies sector focusing;
    normal/skew harmonic terms continue through octupole.  ``H_ref`` supplies
    finite-speed slip and becomes ``1+delta`` when ``reference_beta=1``.
    """
    values = _finite_array(coefficients, shape=(7,), name="segment multipoles")
    rigidity = float(magnetic_rigidity)
    curvature_sign = float(curvature_sign)
    gradient_sign = float(gradient_sign)
    beta = float(reference_beta)
    if (
        not np.isfinite(rigidity)
        or rigidity == 0.0
        or not np.all(np.isfinite([curvature_sign, gradient_sign, beta]))
        or beta <= 0.0
        or beta > 1.0
    ):
        raise ValueError("rigidity/signs must be finite and 0 < reference_beta <= 1")

    parameter_count = 7
    H2 = np.zeros((6, 6), dtype=float)
    H3 = np.zeros((6, 6, 6), dtype=float)
    H4 = np.zeros((6, 6, 6, 6), dtype=float)
    dH2 = np.zeros((parameter_count, 6, 6), dtype=float)
    dH3 = np.zeros((parameter_count, 6, 6, 6), dtype=float)
    dH4 = np.zeros((parameter_count, 6, 6, 6, 6), dtype=float)
    zero = np.zeros(parameter_count)

    curvature = curvature_sign * values[0] / rigidity
    dcurvature = zero.copy()
    dcurvature[0] = curvature_sign / rigidity

    # Quadratic kinetic, sector, and finite-speed reference terms.
    _add_hamiltonian_monomial(H2, dH2, (0, 2, 0, 0, 0, 0), 0.5, zero)
    _add_hamiltonian_monomial(H2, dH2, (0, 0, 0, 2, 0, 0), 0.5, zero)
    _add_hamiltonian_monomial(
        H2,
        dH2,
        (2, 0, 0, 0, 0, 0),
        0.5 * curvature * curvature,
        curvature * dcurvature,
    )
    _add_hamiltonian_monomial(
        H2,
        dH2,
        (1, 0, 0, 0, 0, 1),
        -curvature,
        -dcurvature,
    )
    _add_hamiltonian_monomial(
        H2,
        dH2,
        (0, 0, 0, 0, 0, 2),
        0.5 * (1.0 - beta * beta),
        zero,
    )

    # Cubic kinematic terms from the exact square root.
    for momentum in (1, 3):
        powers = [0] * 6
        powers[momentum] = 2
        powers[5] = 1
        _add_hamiltonian_monomial(H3, dH3, tuple(powers), -0.5, zero)
        powers[5] = 0
        powers[0] = 1
        _add_hamiltonian_monomial(
            H3,
            dH3,
            tuple(powers),
            0.5 * curvature,
            0.5 * dcurvature,
        )
    _add_hamiltonian_monomial(
        H3,
        dH3,
        (0, 0, 0, 0, 0, 3),
        -0.5 * beta * beta * (1.0 - beta * beta),
        zero,
    )

    # Quartic kinematic and reference-speed terms.
    for momentum in (1, 3):
        powers = [0] * 6
        powers[momentum] = 2
        powers[5] = 2
        _add_hamiltonian_monomial(H4, dH4, tuple(powers), 0.5, zero)
        powers[5] = 1
        powers[0] = 1
        _add_hamiltonian_monomial(
            H4,
            dH4,
            tuple(powers),
            -0.5 * curvature,
            -0.5 * dcurvature,
        )
    _add_hamiltonian_monomial(H4, dH4, (0, 4, 0, 0, 0, 0), 0.125, zero)
    _add_hamiltonian_monomial(H4, dH4, (0, 0, 0, 4, 0, 0), 0.125, zero)
    _add_hamiltonian_monomial(H4, dH4, (0, 2, 0, 2, 0, 0), 0.25, zero)
    _add_hamiltonian_monomial(
        H4,
        dH4,
        (0, 0, 0, 0, 0, 4),
        beta * beta * (1.0 - beta * beta) * (5.0 * beta * beta - 1.0) / 8.0,
        zero,
    )

    # Re[(normal+i*skew)*(x+i*y)^(order+1)]/(order+1).
    for order in range(1, 4):
        degree = order + 1
        normal_parameter = 2 * order - 1
        skew_parameter = 2 * order
        normalized = (
            gradient_sign
            * complex(values[normal_parameter], values[skew_parameter])
            / rigidity
        )
        normalized_tangent = np.zeros(parameter_count, dtype=complex)
        normalized_tangent[normal_parameter] = gradient_sign / rigidity
        normalized_tangent[skew_parameter] = 1.0j * gradient_sign / rigidity
        target, target_tangent = (
            (H2, dH2) if degree == 2 else (H3, dH3) if degree == 3 else (H4, dH4)
        )
        for y_power in range(degree + 1):
            polynomial_scale = (
                factorial(degree)
                / (factorial(y_power) * factorial(degree - y_power))
                * (1.0j**y_power)
                / degree
            )
            polynomial = normalized * polynomial_scale
            polynomial_tangent = normalized_tangent * polynomial_scale
            powers = [0] * 6
            powers[0] = degree - y_power
            powers[2] = y_power
            _add_hamiltonian_monomial(
                target,
                target_tangent,
                tuple(powers),
                polynomial.real,
                polynomial_tangent.real,
            )

    A = np.einsum("ia,aj->ij", _POISSON, H2, optimize=True)
    F2 = np.einsum("ia,ajk->ijk", _POISSON, H3, optimize=True)
    F3 = np.einsum("ia,ajkl->ijkl", _POISSON, H4, optimize=True)
    dA = np.einsum("ia,paj->pij", _POISSON, dH2, optimize=True)
    dF2 = np.einsum("ia,pajk->pijk", _POISSON, dH3, optimize=True)
    dF3 = np.einsum("ia,pajkl->pijkl", _POISSON, dH4, optimize=True)

    # C++ is the runtime numerical source of truth; the Python construction
    # above owns the analytic parameter tangents and is checked against it.
    from .beam import canonical_body_hamiltonian_jet as native_hamiltonian_jet

    native = native_hamiltonian_jet(
        values,
        rigidity,
        curvature_sign=curvature_sign,
        gradient_sign=gradient_sign,
        reference_beta=beta,
    )
    python_values = (H2, H3, H4, A, F2, F3)
    native_values = tuple(
        np.asarray(native[name], dtype=float)
        for name in (
            "H2_per_m",
            "H3_per_m",
            "H4_per_m",
            "A_per_m",
            "F2_per_m",
            "F3_per_m",
        )
    )
    if any(
        not np.allclose(python, compiled, rtol=2.0e-14, atol=2.0e-14)
        for python, compiled in zip(python_values, native_values, strict=True)
    ):
        raise RuntimeError(
            "analytic Hamiltonian construction disagrees with the native C++ jet"
        )
    H2, H3, H4, A, F2, F3 = native_values
    return CanonicalHamiltonianJet(
        H2=H2,
        H3=H3,
        H4=H4,
        A=A,
        F2=F2,
        F3=F3,
        H2_jacobian=dH2,
        H3_jacobian=dH3,
        H4_jacobian=dH4,
        A_jacobian=dA,
        F2_jacobian=dF2,
        F3_jacobian=dF3,
        reference_beta=beta,
    )


def canonical_body_hamiltonian_rhs(
    state,
    coefficients,
    magnetic_rigidity,
    *,
    curvature_sign=1.0,
    gradient_sign=1.0,
    reference_beta=1.0,
) -> np.ndarray:
    """Evaluate the unexpanded canonical body-field Hamilton equations.

    This pointwise path is an independent trajectory oracle for the truncated
    Lie map.  It uses the exact relativistic square roots and the polynomial
    covariant longitudinal vector potential through octupole.
    """
    z = _finite_array(state, shape=(6,), name="state")
    values = _finite_array(coefficients, shape=(7,), name="segment multipoles")
    rigidity = float(magnetic_rigidity)
    beta = float(reference_beta)
    if (
        not np.isfinite(rigidity)
        or rigidity == 0.0
        or not np.isfinite(beta)
        or beta <= 0.0
        or beta > 1.0
    ):
        raise ValueError("Hamiltonian RHS rigidity/beta are invalid")
    x, px, y, py, _, delta = z
    transverse_square = px * px + py * py
    longitudinal_square = (1.0 + delta) ** 2 - transverse_square
    if longitudinal_square <= 0.0:
        raise ValueError("canonical state has non-positive longitudinal momentum")
    root = np.sqrt(longitudinal_square)
    curvature = float(curvature_sign) * values[0] / rigidity
    coordinate = complex(x, y)
    potential_x = curvature + curvature * curvature * x
    potential_y = 0.0
    for order in range(1, 4):
        coefficient = (
            float(gradient_sign)
            * complex(values[2 * order - 1], values[2 * order])
            / rigidity
        )
        field = coefficient * coordinate**order
        potential_x += field.real
        potential_y -= field.imag
    reference_mass_square = 1.0 / (beta * beta) - 1.0
    reference_root = np.sqrt((1.0 + delta) ** 2 + reference_mass_square)
    reference_derivative = (1.0 + delta) / (beta * reference_root)
    metric = 1.0 + curvature * x
    return np.asarray(
        [
            metric * px / root,
            curvature * root - potential_x,
            metric * py / root,
            -potential_y,
            metric * (1.0 + delta) / root - reference_derivative,
            0.0,
        ],
        dtype=float,
    )


@dataclass(frozen=True)
class FormalSymplecticResidual:
    """Coefficient-wise residual of ``D M(z)^T J D M(z) = J``."""

    constant: float
    linear: float
    quadratic: float
    maximum: float


def formal_symplectic_residual(R, T, U) -> FormalSymplecticResidual:
    """Measure formal symplecticity through quadratic Jacobian degree."""
    R = _finite_array(R, shape=(6, 6), name="R")
    T = _finite_array(T, shape=(6, 6, 6), name="T")
    U = _finite_array(U, shape=(6, 6, 6, 6), name="U")
    constant_tensor = R.T @ _POISSON @ R - _POISSON
    linear_tensor = np.empty((6, 6, 6), dtype=float)
    quadratic_tensor = np.empty((6, 6, 6, 6), dtype=float)
    for first in range(6):
        T_first = T[:, :, first]
        linear_tensor[:, :, first] = R.T @ _POISSON @ T_first + T_first.T @ _POISSON @ R
        for second in range(6):
            T_second = T[:, :, second]
            U_pair = U[:, :, first, second]
            quadratic_tensor[:, :, first, second] = 0.5 * (
                R.T @ _POISSON @ U_pair + U_pair.T @ _POISSON @ R
            ) + 0.5 * (
                T_first.T @ _POISSON @ T_second + T_second.T @ _POISSON @ T_first
            )
    constant = float(np.max(np.abs(constant_tensor), initial=0.0))
    linear = float(np.max(np.abs(linear_tensor), initial=0.0))
    quadratic = float(np.max(np.abs(quadratic_tensor), initial=0.0))
    return FormalSymplecticResidual(
        constant=constant,
        linear=linear,
        quadratic=quadratic,
        maximum=max(constant, linear, quadratic),
    )


@dataclass(frozen=True)
class FormalFourthOrderSymplecticResidual:
    """Coefficient residual of ``D M.T J D M = J`` through cubic degree."""

    constant: float
    linear: float
    quadratic: float
    cubic: float
    maximum: float


def formal_fourth_order_symplectic_residual(
    R, T, U, V
) -> FormalFourthOrderSymplecticResidual:
    """Measure formal symplecticity of a factorial ``R/T/U/V`` map."""
    lower = formal_symplectic_residual(R, T, U)
    R = _finite_array(R, shape=(6, 6), name="R")
    T = _finite_array(T, shape=(6, 6, 6), name="T")
    U = _finite_array(U, shape=(6, 6, 6, 6), name="U")
    V = _finite_array(V, shape=(6, 6, 6, 6, 6), name="V")
    cubic_tensor = np.empty((6, 6, 6, 6, 6), dtype=float)
    for first in range(6):
        T_first = T[:, :, first]
        for second in range(6):
            T_second = T[:, :, second]
            U_first_second = U[:, :, first, second]
            for third in range(6):
                T_third = T[:, :, third]
                U_first_third = U[:, :, first, third]
                U_second_third = U[:, :, second, third]
                V_triple = V[:, :, first, second, third]
                cubic_tensor[:, :, first, second, third] = (
                    R.T @ _POISSON @ V_triple
                    + V_triple.T @ _POISSON @ R
                    + T_first.T @ _POISSON @ U_second_third
                    + T_second.T @ _POISSON @ U_first_third
                    + T_third.T @ _POISSON @ U_first_second
                    + U_first_second.T @ _POISSON @ T_third
                    + U_first_third.T @ _POISSON @ T_second
                    + U_second_third.T @ _POISSON @ T_first
                ) / 6.0
    cubic = float(np.max(np.abs(cubic_tensor), initial=0.0))
    return FormalFourthOrderSymplecticResidual(
        constant=lower.constant,
        linear=lower.linear,
        quadratic=lower.quadratic,
        cubic=cubic,
        maximum=max(lower.maximum, cubic),
    )


def _symmetrize_tensor(value, degree, *, parameter_axis=False):
    offset = 1 if parameter_axis else 0
    prefix = (0,) if parameter_axis else ()
    axes = tuple(range(offset, offset + degree))
    result = np.zeros_like(value, dtype=float)
    unique = tuple(permutations(axes))
    for ordered in unique:
        result += np.transpose(value, prefix + ordered)
    return result / len(unique)


@dataclass(frozen=True)
class DragtFinnFactorization:
    """Third-order Dragt--Finn factors and the reconstructed formal map."""

    R: np.ndarray
    f3: np.ndarray
    f4: np.ndarray
    T: np.ndarray
    U: np.ndarray
    R_jacobian: np.ndarray
    f3_jacobian: np.ndarray
    f4_jacobian: np.ndarray
    T_jacobian: np.ndarray
    U_jacobian: np.ndarray
    f3_symmetry_defect: float
    f4_symmetry_defect: float
    relative_reconstruction_error: float
    raw_symplectic_residual: FormalSymplecticResidual
    reconstructed_symplectic_residual: FormalSymplecticResidual

    @property
    def maximum_generator_symmetry_defect(self) -> float:
        return max(self.f3_symmetry_defect, self.f4_symmetry_defect)


@dataclass(frozen=True)
class DragtFinnFourthOrderFactorization:
    """Fourth-order Dragt--Finn factors and reconstructed formal map."""

    R: np.ndarray
    f3: np.ndarray
    f4: np.ndarray
    f5: np.ndarray
    T: np.ndarray
    U: np.ndarray
    V: np.ndarray
    R_jacobian: np.ndarray
    f3_jacobian: np.ndarray
    f4_jacobian: np.ndarray
    f5_jacobian: np.ndarray
    T_jacobian: np.ndarray
    U_jacobian: np.ndarray
    V_jacobian: np.ndarray
    f3_symmetry_defect: float
    f4_symmetry_defect: float
    f5_symmetry_defect: float
    relative_reconstruction_error: float
    raw_symplectic_residual: FormalFourthOrderSymplecticResidual
    reconstructed_symplectic_residual: FormalFourthOrderSymplecticResidual

    @property
    def maximum_generator_symmetry_defect(self) -> float:
        return max(
            self.f3_symmetry_defect,
            self.f4_symmetry_defect,
            self.f5_symmetry_defect,
        )


def _homogeneous_generator_gradient_hessian(tensor, state):
    degree = tensor.ndim
    if degree == 3:
        gradient = 0.5 * np.einsum("ijk,j,k->i", tensor, state, state)
        hessian = np.einsum("ijk,k->ij", tensor, state)
    elif degree == 4:
        gradient = np.einsum("ijkl,j,k,l->i", tensor, state, state, state) / 6.0
        hessian = 0.5 * np.einsum("ijkl,k,l->ij", tensor, state, state)
    elif degree == 5:
        gradient = (
            np.einsum("ijklm,j,k,l,m->i", tensor, state, state, state, state)
            / 24.0
        )
        hessian = (
            np.einsum("ijklm,k,l,m->ij", tensor, state, state, state) / 6.0
        )
    else:
        raise ValueError("Lie generator tensor must have degree three, four, or five")
    return gradient, hessian


def apply_homogeneous_lie_generator(
    generator,
    state,
    *,
    substeps=1,
    newton_tolerance=1.0e-13,
    maximum_newton_iterations=20,
    return_jacobian=False,
):
    """Apply a homogeneous Lie generator with implicit-midpoint flow.

    Implicit midpoint is symplectic at finite amplitude.  For a cubic
    generator it reproduces the Taylor map through cubic coordinate degree;
    for a quartic generator it reproduces it through cubic degree as well.
    """
    tensor = _finite_array(generator, name="generator")
    if tensor.shape not in ((6, 6, 6), (6, 6, 6, 6), (6, 6, 6, 6, 6)):
        raise ValueError("generator must be a symmetric rank-three/four/five tensor")
    value = _finite_array(state, shape=(6,), name="state").copy()
    count = int(substeps)
    tolerance = float(newton_tolerance)
    iteration_cap = int(maximum_newton_iterations)
    if count < 1 or not np.isfinite(tolerance) or tolerance <= 0.0 or iteration_cap < 1:
        raise ValueError("Lie-flow integration controls are invalid")
    step = 1.0 / count
    total_jacobian = np.eye(6)
    identity = np.eye(6)
    for _ in range(count):
        initial = value.copy()
        trial = initial + step * (
            _POISSON @ _homogeneous_generator_gradient_hessian(tensor, initial)[0]
        )
        converged = False
        for _ in range(iteration_cap):
            midpoint = 0.5 * (initial + trial)
            gradient, hessian = _homogeneous_generator_gradient_hessian(
                tensor, midpoint
            )
            residual = trial - initial - step * (_POISSON @ gradient)
            system = identity - 0.5 * step * (_POISSON @ hessian)
            update = np.linalg.solve(system, residual)
            trial -= update
            if np.linalg.norm(update, ord=np.inf) <= tolerance * max(
                1.0, np.linalg.norm(trial, ord=np.inf)
            ):
                converged = True
                break
        if not converged:
            raise RuntimeError("implicit-midpoint Lie flow did not converge")
        midpoint = 0.5 * (initial + trial)
        _, hessian = _homogeneous_generator_gradient_hessian(tensor, midpoint)
        left = identity - 0.5 * step * (_POISSON @ hessian)
        right = identity + 0.5 * step * (_POISSON @ hessian)
        local_jacobian = np.linalg.solve(left, right)
        total_jacobian = local_jacobian @ total_jacobian
        value = trial
    if return_jacobian:
        return value, total_jacobian
    return value


def apply_dragt_finn_map(
    factorization: DragtFinnFactorization | DragtFinnFourthOrderFactorization,
    state,
    *,
    generator_substeps=1,
    return_jacobian=False,
):
    """Apply the available Dragt--Finn factors as an exact symplectic flow."""
    if not isinstance(
        factorization, (DragtFinnFactorization, DragtFinnFourthOrderFactorization)
    ):
        raise TypeError("factorization must be a Dragt-Finn factorization")
    if isinstance(factorization, DragtFinnFourthOrderFactorization):
        value, f5_jacobian = apply_homogeneous_lie_generator(
            factorization.f5,
            state,
            substeps=generator_substeps,
            return_jacobian=True,
        )
    else:
        value = _finite_array(state, shape=(6,), name="state")
        f5_jacobian = np.eye(6)
    value, f4_jacobian = apply_homogeneous_lie_generator(
        factorization.f4,
        value,
        substeps=generator_substeps,
        return_jacobian=True,
    )
    value, f3_jacobian = apply_homogeneous_lie_generator(
        factorization.f3,
        value,
        substeps=generator_substeps,
        return_jacobian=True,
    )
    value = factorization.R @ value
    jacobian = factorization.R @ f3_jacobian @ f4_jacobian @ f5_jacobian
    if return_jacobian:
        return value, jacobian
    return value


def dragt_finn_factorize_third_order(
    R,
    T,
    U,
    *,
    R_jacobian=None,
    T_jacobian=None,
    U_jacobian=None,
) -> DragtFinnFactorization:
    """Factor and symplectically reconstruct an origin-preserving ``R/T/U`` map."""
    R = _finite_array(R, shape=(6, 6), name="R")
    T = _finite_array(T, shape=(6, 6, 6), name="T")
    U = _finite_array(U, shape=(6, 6, 6, 6), name="U")
    supplied = any(item is not None for item in (R_jacobian, T_jacobian, U_jacobian))
    if supplied and any(item is None for item in (R_jacobian, T_jacobian, U_jacobian)):
        raise ValueError("all map Jacobians must be supplied together")
    if supplied:
        dR = _finite_array(R_jacobian, name="R_jacobian")
        dT = _finite_array(T_jacobian, name="T_jacobian")
        dU = _finite_array(U_jacobian, name="U_jacobian")
        parameter_count = dR.shape[0]
        if (
            dR.shape != (parameter_count, 6, 6)
            or dT.shape != (parameter_count, 6, 6, 6)
            or dU.shape != (parameter_count, 6, 6, 6, 6)
        ):
            raise ValueError("map Jacobians have incompatible shapes")
    else:
        parameter_count = 0
        dR = np.zeros((0, 6, 6))
        dT = np.zeros((0, 6, 6, 6))
        dU = np.zeros((0, 6, 6, 6, 6))

    inverse = np.linalg.inv(R)
    dinverse = -np.einsum("ia,pab,bj->pij", inverse, dR, inverse, optimize=True)
    normalized_T = np.einsum("ia,ajk->ijk", inverse, T, optimize=True)
    normalized_U = np.einsum("ia,ajkl->ijkl", inverse, U, optimize=True)
    dnormalized_T = np.einsum("pia,ajk->pijk", dinverse, T, optimize=True) + np.einsum(
        "ia,pajk->pijk", inverse, dT, optimize=True
    )
    dnormalized_U = np.einsum(
        "pia,ajkl->pijkl", dinverse, U, optimize=True
    ) + np.einsum("ia,pajkl->pijkl", inverse, dU, optimize=True)

    raw_f3 = -np.einsum("ai,ijk->ajk", _POISSON, normalized_T, optimize=True)
    draw_f3 = -np.einsum("ai,pijk->pajk", _POISSON, dnormalized_T, optimize=True)
    f3 = _symmetrize_tensor(raw_f3, 3)
    df3 = _symmetrize_tensor(draw_f3, 3, parameter_axis=True)
    f3_scale = max(1.0, float(np.max(np.abs(raw_f3), initial=0.0)))
    f3_defect = float(np.max(np.abs(raw_f3 - f3), initial=0.0) / f3_scale)
    quadratic_flow = np.einsum("ia,ajk->ijk", _POISSON, f3, optimize=True)
    dquadratic_flow = np.einsum("ia,pajk->pijk", _POISSON, df3, optimize=True)
    identity = np.eye(6)
    zero_dR = np.zeros((parameter_count, 6, 6))
    self_cubic = 0.5 * _cross_second_order(quadratic_flow, identity, quadratic_flow)
    dself_cubic = 0.5 * _cross_second_order_tangent(
        quadratic_flow,
        identity,
        quadratic_flow,
        dquadratic_flow,
        zero_dR,
        dquadratic_flow,
    )
    cubic_residual = (
        normalized_U
        - _cross_second_order(quadratic_flow, identity, normalized_T)
        + self_cubic
    )
    dcubic_residual = (
        dnormalized_U
        - _cross_second_order_tangent(
            quadratic_flow,
            identity,
            normalized_T,
            dquadratic_flow,
            zero_dR,
            dnormalized_T,
        )
        + dself_cubic
    )
    raw_f4 = -np.einsum("ai,ijkl->ajkl", _POISSON, cubic_residual, optimize=True)
    draw_f4 = -np.einsum("ai,pijkl->pajkl", _POISSON, dcubic_residual, optimize=True)
    f4 = _symmetrize_tensor(raw_f4, 4)
    df4 = _symmetrize_tensor(draw_f4, 4, parameter_axis=True)
    f4_scale = max(1.0, float(np.max(np.abs(raw_f4), initial=0.0)))
    f4_defect = float(np.max(np.abs(raw_f4 - f4), initial=0.0) / f4_scale)
    cubic_flow = np.einsum("ia,ajkl->ijkl", _POISSON, f4, optimize=True)
    dcubic_flow = np.einsum("ia,pajkl->pijkl", _POISSON, df4, optimize=True)

    normalized_reconstructed_U = cubic_flow + self_cubic
    reconstructed_T = np.einsum("ia,ajk->ijk", R, quadratic_flow, optimize=True)
    reconstructed_U = np.einsum(
        "ia,ajkl->ijkl", R, normalized_reconstructed_U, optimize=True
    )
    dreconstructed_T = np.einsum(
        "pia,ajk->pijk", dR, quadratic_flow, optimize=True
    ) + np.einsum("ia,pajk->pijk", R, dquadratic_flow, optimize=True)
    dreconstructed_U = np.einsum(
        "pia,ajkl->pijkl", dR, normalized_reconstructed_U, optimize=True
    ) + np.einsum(
        "ia,pajkl->pijkl",
        R,
        dcubic_flow + dself_cubic,
        optimize=True,
    )
    reconstruction_scale = max(
        1.0,
        float(np.max(np.abs(T), initial=0.0)),
        float(np.max(np.abs(U), initial=0.0)),
    )
    reconstruction_error = (
        max(
            float(np.max(np.abs(reconstructed_T - T), initial=0.0)),
            float(np.max(np.abs(reconstructed_U - U), initial=0.0)),
        )
        / reconstruction_scale
    )
    return DragtFinnFactorization(
        R=np.ascontiguousarray(R),
        f3=np.ascontiguousarray(f3),
        f4=np.ascontiguousarray(f4),
        T=np.ascontiguousarray(reconstructed_T),
        U=np.ascontiguousarray(reconstructed_U),
        R_jacobian=np.ascontiguousarray(dR),
        f3_jacobian=np.ascontiguousarray(df3),
        f4_jacobian=np.ascontiguousarray(df4),
        T_jacobian=np.ascontiguousarray(dreconstructed_T),
        U_jacobian=np.ascontiguousarray(dreconstructed_U),
        f3_symmetry_defect=f3_defect,
        f4_symmetry_defect=f4_defect,
        relative_reconstruction_error=reconstruction_error,
        raw_symplectic_residual=formal_symplectic_residual(R, T, U),
        reconstructed_symplectic_residual=formal_symplectic_residual(
            R, reconstructed_T, reconstructed_U
        ),
    )


@dataclass(frozen=True)
class ThirdOrderLieMap:
    """Canonical Dragt--Finn map, forward AD, and projection diagnostics."""

    R: np.ndarray
    T: np.ndarray
    U: np.ndarray
    R_jacobian: np.ndarray
    T_jacobian: np.ndarray
    U_jacobian: np.ndarray
    f3: np.ndarray
    f4: np.ndarray
    f3_jacobian: np.ndarray
    f4_jacobian: np.ndarray
    raw_R: np.ndarray
    raw_T: np.ndarray
    raw_U: np.ndarray
    factorization: DragtFinnFactorization
    multipole_components: tuple[str, ...]
    derivative_backend: str = "forward-mode-hamiltonian-lie-ad"
    value_backend: str = "native-cpp-hamiltonian-jet-plus-dragt-finn"


@dataclass(frozen=True)
class FourthOrderLieMap:
    """Canonical ``R/T/U/V`` map, ``f3/f4/f5`` factors, and forward AD."""

    R: np.ndarray
    T: np.ndarray
    U: np.ndarray
    V: np.ndarray
    R_jacobian: np.ndarray
    T_jacobian: np.ndarray
    U_jacobian: np.ndarray
    V_jacobian: np.ndarray
    f3: np.ndarray
    f4: np.ndarray
    f5: np.ndarray
    f3_jacobian: np.ndarray
    f4_jacobian: np.ndarray
    f5_jacobian: np.ndarray
    raw_R: np.ndarray
    raw_T: np.ndarray
    raw_U: np.ndarray
    raw_V: np.ndarray
    factorization: DragtFinnFourthOrderFactorization
    multipole_components: tuple[str, ...]
    derivative_backend: str = "forward-mode-fourth-order-hamiltonian-lie-ad"
    value_backend: str = "native-cpp-H2-H4-jet-plus-python-f5-dragt-finn"


def _exact_linear_map_with_tangent(A_values, dA_values, lengths):
    segment_count = len(lengths)
    parameter_count = 7 * segment_count
    accumulated = np.eye(6)
    daccumulated = np.zeros((parameter_count, 6, 6))
    for segment, length in enumerate(lengths):
        scaled = A_values[segment] * length
        local = expm(scaled)
        dlocal = np.asarray(
            [
                expm_frechet(
                    scaled,
                    dA_values[segment, parameter] * length,
                    compute_expm=False,
                )
                for parameter in range(7)
            ]
        )
        embedded = np.zeros((parameter_count, 6, 6))
        indexes = [block * segment_count + segment for block in range(7)]
        embedded[indexes] = dlocal
        daccumulated = np.einsum(
            "pia,aj->pij", embedded, accumulated, optimize=True
        ) + np.einsum("ia,paj->pij", local, daccumulated, optimize=True)
        accumulated = local @ accumulated
    return accumulated, daccumulated


def _cross_fourth_second(F2, R, U):
    """Fourth derivative from one linear and one cubic inner-map block."""
    return (
        np.einsum("iab,aj,bklm->ijklm", F2, R, U, optimize=True)
        + np.einsum("iab,ak,bjlm->ijklm", F2, R, U, optimize=True)
        + np.einsum("iab,al,bjkm->ijklm", F2, R, U, optimize=True)
        + np.einsum("iab,am,bjkl->ijklm", F2, R, U, optimize=True)
    )


def _cross_fourth_second_tangent(F2, R, U, dF2, dR, dU):
    parameter_count = dF2.shape[0]
    result = np.zeros((parameter_count, 6, 6, 6, 6, 6), dtype=float)
    for parameter in range(parameter_count):
        result[parameter] = (
            _cross_fourth_second(dF2[parameter], R, U)
            + _cross_fourth_second(F2, dR[parameter], U)
            + _cross_fourth_second(F2, R, dU[parameter])
        )
    return result


def _pair_fourth_second(F2, T):
    """Fourth derivative from the three pairings of two quadratic blocks."""
    return (
        np.einsum("iab,ajk,blm->ijklm", F2, T, T, optimize=True)
        + np.einsum("iab,ajl,bkm->ijklm", F2, T, T, optimize=True)
        + np.einsum("iab,ajm,bkl->ijklm", F2, T, T, optimize=True)
    )


def _pair_fourth_second_tangent(F2, T, dF2, dT):
    parameter_count = dF2.shape[0]
    result = np.zeros((parameter_count, 6, 6, 6, 6, 6), dtype=float)
    for parameter in range(parameter_count):
        result[parameter] = (
            _pair_fourth_second(dF2[parameter], T)
            + np.einsum(
                "iab,ajk,blm->ijklm",
                F2,
                dT[parameter],
                T,
                optimize=True,
            )
            + np.einsum(
                "iab,ajk,blm->ijklm",
                F2,
                T,
                dT[parameter],
                optimize=True,
            )
            + np.einsum(
                "iab,ajl,bkm->ijklm",
                F2,
                dT[parameter],
                T,
                optimize=True,
            )
            + np.einsum(
                "iab,ajl,bkm->ijklm",
                F2,
                T,
                dT[parameter],
                optimize=True,
            )
            + np.einsum(
                "iab,ajm,bkl->ijklm",
                F2,
                dT[parameter],
                T,
                optimize=True,
            )
            + np.einsum(
                "iab,ajm,bkl->ijklm",
                F2,
                T,
                dT[parameter],
                optimize=True,
            )
        )
    return result


def _cross_fourth_third(F3, R, T):
    """Fourth derivative from the six ``T,R,R`` set partitions."""
    return (
        np.einsum("iabc,ajk,bl,cm->ijklm", F3, T, R, R, optimize=True)
        + np.einsum("iabc,ajl,bk,cm->ijklm", F3, T, R, R, optimize=True)
        + np.einsum("iabc,ajm,bk,cl->ijklm", F3, T, R, R, optimize=True)
        + np.einsum("iabc,akl,bj,cm->ijklm", F3, T, R, R, optimize=True)
        + np.einsum("iabc,akm,bj,cl->ijklm", F3, T, R, R, optimize=True)
        + np.einsum("iabc,alm,bj,ck->ijklm", F3, T, R, R, optimize=True)
    )


def _cross_fourth_third_tangent(F3, R, T, dF3, dR, dT):
    parameter_count = dF3.shape[0]
    result = np.zeros((parameter_count, 6, 6, 6, 6, 6), dtype=float)
    for parameter in range(parameter_count):
        # F3 is symmetric in its three inputs.  Differentiating the two R
        # slots independently is essential even though their values coincide.
        value = _cross_fourth_third(dF3[parameter], R, T)
        value += _cross_fourth_third(F3, R, dT[parameter])
        value += (
            np.einsum(
                "iabc,ajk,pbl,cm->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,ajk,bl,pcm->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,ajl,pbk,cm->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,ajl,bk,pcm->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,ajm,pbk,cl->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,ajm,bk,pcl->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,akl,pbj,cm->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,akl,bj,pcm->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,akm,pbj,cl->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,akm,bj,pcl->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,alm,pbj,ck->pijklm",
                F3,
                T,
                dR[parameter : parameter + 1],
                R,
                optimize=True,
            )[0]
            + np.einsum(
                "iabc,alm,bj,pck->pijklm",
                F3,
                T,
                R,
                dR[parameter : parameter + 1],
                optimize=True,
            )[0]
        )
        result[parameter] = value
    return result


def _transform_quartic(F4, R):
    return np.einsum(
        "iabcd,aj,bk,cl,dm->ijklm", F4, R, R, R, R, optimize=True
    )


def _transform_quartic_tangent(F4, R, dF4, dR):
    parameter_count = dF4.shape[0]
    result = np.zeros((parameter_count, 6, 6, 6, 6, 6), dtype=float)
    for parameter in range(parameter_count):
        value = _transform_quartic(dF4[parameter], R)
        for slot in range(4):
            inputs = [R, R, R, R]
            inputs[slot] = dR[parameter]
            value += np.einsum(
                "iabcd,aj,bk,cl,dm->ijklm", F4, *inputs, optimize=True
            )
        result[parameter] = value
    return result


def _identity_fourth_order(parameter_count):
    count = int(parameter_count)
    return (
        np.eye(6),
        np.zeros((6, 6, 6)),
        np.zeros((6, 6, 6, 6)),
        np.zeros((6, 6, 6, 6, 6)),
        np.zeros((count, 6, 6)),
        np.zeros((count, 6, 6, 6)),
        np.zeros((count, 6, 6, 6, 6)),
        np.zeros((count, 6, 6, 6, 6, 6)),
    )


def _fourth_order_rhs(A, F2, F3, dA, dF2, dF3, R, T, U, V, dR, dT, dU, dV):
    lower = _third_order_rhs(A, F2, F3, dA, dF2, dF3, R, T, U, dR, dT, dU)
    R_dot, T_dot, U_dot, dR_dot, dT_dot, dU_dot = lower
    V_dot = (
        np.einsum("ia,ajklm->ijklm", A, V, optimize=True)
        + _cross_fourth_second(F2, R, U)
        + _pair_fourth_second(F2, T)
        + _cross_fourth_third(F3, R, T)
    )
    dV_dot = (
        np.einsum("ia,pajklm->pijklm", A, dV, optimize=True)
        + np.einsum("pia,ajklm->pijklm", dA, V, optimize=True)
        + _cross_fourth_second_tangent(F2, R, U, dF2, dR, dU)
        + _pair_fourth_second_tangent(F2, T, dF2, dT)
        + _cross_fourth_third_tangent(F3, R, T, dF3, dR, dT)
    )
    return R_dot, T_dot, U_dot, V_dot, dR_dot, dT_dot, dU_dot, dV_dot


def _fourth_order_rk4_step(A, F2, F3, dA, dF2, dF3, length):
    state = _identity_fourth_order(dA.shape[0])

    def rhs(value):
        return _fourth_order_rhs(A, F2, F3, dA, dF2, dF3, *value)

    def shifted(value, derivative, scale):
        return tuple(item + scale * rate for item, rate in zip(value, derivative))

    k1 = rhs(state)
    k2 = rhs(shifted(state, k1, 0.5 * length))
    k3 = rhs(shifted(state, k2, 0.5 * length))
    k4 = rhs(shifted(state, k3, length))
    return tuple(
        item + length * (first + 2.0 * second + 2.0 * third + fourth) / 6.0
        for item, first, second, third, fourth in zip(state, k1, k2, k3, k4)
    )


def _compose_fourth_order(outer, inner):
    Ro, To, Uo, Vo, dRo, dTo, dUo, dVo = outer
    Ri, Ti, Ui, Vi, dRi, dTi, dUi, dVi = inner
    R, T, U, dR, dT, dU = _compose_third_order(
        (Ro, To, Uo, dRo, dTo, dUo),
        (Ri, Ti, Ui, dRi, dTi, dUi),
    )
    V = (
        np.einsum("ia,ajklm->ijklm", Ro, Vi, optimize=True)
        + _cross_fourth_second(To, Ri, Ui)
        + _pair_fourth_second(To, Ti)
        + _cross_fourth_third(Uo, Ri, Ti)
        + _transform_quartic(Vo, Ri)
    )
    dV = (
        np.einsum("pia,ajklm->pijklm", dRo, Vi, optimize=True)
        + np.einsum("ia,pajklm->pijklm", Ro, dVi, optimize=True)
        + _cross_fourth_second_tangent(To, Ri, Ui, dTo, dRi, dUi)
        + _pair_fourth_second_tangent(To, Ti, dTo, dTi)
        + _cross_fourth_third_tangent(Uo, Ri, Ti, dUo, dRi, dTi)
        + _transform_quartic_tangent(Vo, Ri, dVo, dRi)
    )
    return R, T, U, V, dR, dT, dU, dV


def dragt_finn_factorize_fourth_order(
    R,
    T,
    U,
    V,
    *,
    R_jacobian=None,
    T_jacobian=None,
    U_jacobian=None,
    V_jacobian=None,
) -> DragtFinnFourthOrderFactorization:
    """Factor and symplectically reconstruct a factorial ``R/T/U/V`` map."""
    R = _finite_array(R, shape=(6, 6), name="R")
    T = _finite_array(T, shape=(6, 6, 6), name="T")
    U = _finite_array(U, shape=(6, 6, 6, 6), name="U")
    V = _finite_array(V, shape=(6, 6, 6, 6, 6), name="V")
    supplied = any(
        item is not None
        for item in (R_jacobian, T_jacobian, U_jacobian, V_jacobian)
    )
    if supplied and any(
        item is None
        for item in (R_jacobian, T_jacobian, U_jacobian, V_jacobian)
    ):
        raise ValueError("all fourth-order map Jacobians must be supplied together")
    if supplied:
        dR = _finite_array(R_jacobian, name="R_jacobian")
        dT = _finite_array(T_jacobian, name="T_jacobian")
        dU = _finite_array(U_jacobian, name="U_jacobian")
        dV = _finite_array(V_jacobian, name="V_jacobian")
        parameter_count = dR.shape[0]
        if (
            dR.shape != (parameter_count, 6, 6)
            or dT.shape != (parameter_count, 6, 6, 6)
            or dU.shape != (parameter_count, 6, 6, 6, 6)
            or dV.shape != (parameter_count, 6, 6, 6, 6, 6)
        ):
            raise ValueError("fourth-order map Jacobians have incompatible shapes")
    else:
        parameter_count = 0
        dR = np.zeros((0, 6, 6))
        dT = np.zeros((0, 6, 6, 6))
        dU = np.zeros((0, 6, 6, 6, 6))
        dV = np.zeros((0, 6, 6, 6, 6, 6))

    lower = dragt_finn_factorize_third_order(
        R,
        T,
        U,
        R_jacobian=dR,
        T_jacobian=dT,
        U_jacobian=dU,
    )
    inverse = np.linalg.inv(R)
    dinverse = -np.einsum("ia,pab,bj->pij", inverse, dR, inverse, optimize=True)
    normalized_V = np.einsum("ia,ajklm->ijklm", inverse, V, optimize=True)
    dnormalized_V = np.einsum(
        "pia,ajklm->pijklm", dinverse, V, optimize=True
    ) + np.einsum("ia,pajklm->pijklm", inverse, dV, optimize=True)

    quadratic_flow = np.einsum("ia,ajk->ijk", _POISSON, lower.f3, optimize=True)
    dquadratic_flow = np.einsum(
        "ia,pajk->pijk", _POISSON, lower.f3_jacobian, optimize=True
    )
    cubic_flow = np.einsum("ia,ajkl->ijkl", _POISSON, lower.f4, optimize=True)
    dcubic_flow = np.einsum(
        "ia,pajkl->pijkl", _POISSON, lower.f4_jacobian, optimize=True
    )
    identity = np.eye(6)
    zero_dR = np.zeros((parameter_count, 6, 6))

    # exp(:f3:) contributes at fourth order through the third repeated Lie
    # action.  Composing exp(:f3:) after exp(:f4:) adds the q/r cross term.
    cubic_cascade = _cross_second_order(
        quadratic_flow, identity, quadratic_flow
    )
    dcubic_cascade = _cross_second_order_tangent(
        quadratic_flow,
        identity,
        quadratic_flow,
        dquadratic_flow,
        zero_dR,
        dquadratic_flow,
    )
    f3_self_fourth = (
        _cross_fourth_second(
            quadratic_flow, identity, cubic_cascade
        )
        / 6.0
        + _pair_fourth_second(quadratic_flow, quadratic_flow) / 3.0
    )
    df3_self_fourth = (
        _cross_fourth_second_tangent(
            quadratic_flow,
            identity,
            cubic_cascade,
            dquadratic_flow,
            zero_dR,
            dcubic_cascade,
        )
        / 6.0
        + _pair_fourth_second_tangent(
            quadratic_flow,
            quadratic_flow,
            dquadratic_flow,
            dquadratic_flow,
        )
        / 3.0
    )
    f3_f4_cross = _cross_fourth_second(
        quadratic_flow, identity, cubic_flow
    )
    df3_f4_cross = _cross_fourth_second_tangent(
        quadratic_flow,
        identity,
        cubic_flow,
        dquadratic_flow,
        zero_dR,
        dcubic_flow,
    )
    known_fourth = f3_self_fourth + f3_f4_cross
    dknown_fourth = df3_self_fourth + df3_f4_cross
    fourth_residual = normalized_V - known_fourth
    dfourth_residual = dnormalized_V - dknown_fourth

    raw_f5 = -np.einsum("ai,ijklm->ajklm", _POISSON, fourth_residual, optimize=True)
    draw_f5 = -np.einsum(
        "ai,pijklm->pajklm", _POISSON, dfourth_residual, optimize=True
    )
    f5 = _symmetrize_tensor(raw_f5, 5)
    df5 = _symmetrize_tensor(draw_f5, 5, parameter_axis=True)
    f5_scale = max(1.0, float(np.max(np.abs(raw_f5), initial=0.0)))
    f5_defect = float(np.max(np.abs(raw_f5 - f5), initial=0.0) / f5_scale)
    quartic_flow = np.einsum("ia,ajklm->ijklm", _POISSON, f5, optimize=True)
    dquartic_flow = np.einsum(
        "ia,pajklm->pijklm", _POISSON, df5, optimize=True
    )
    normalized_reconstructed_V = known_fourth + quartic_flow
    dnormalized_reconstructed_V = dknown_fourth + dquartic_flow
    reconstructed_V = np.einsum(
        "ia,ajklm->ijklm", R, normalized_reconstructed_V, optimize=True
    )
    dreconstructed_V = np.einsum(
        "pia,ajklm->pijklm", dR, normalized_reconstructed_V, optimize=True
    ) + np.einsum(
        "ia,pajklm->pijklm", R, dnormalized_reconstructed_V, optimize=True
    )
    reconstruction_scale = max(
        1.0,
        float(np.max(np.abs(T), initial=0.0)),
        float(np.max(np.abs(U), initial=0.0)),
        float(np.max(np.abs(V), initial=0.0)),
    )
    reconstruction_error = max(
        float(np.max(np.abs(lower.T - T), initial=0.0)),
        float(np.max(np.abs(lower.U - U), initial=0.0)),
        float(np.max(np.abs(reconstructed_V - V), initial=0.0)),
    ) / reconstruction_scale
    return DragtFinnFourthOrderFactorization(
        R=np.ascontiguousarray(R),
        f3=lower.f3,
        f4=lower.f4,
        f5=np.ascontiguousarray(f5),
        T=lower.T,
        U=lower.U,
        V=np.ascontiguousarray(reconstructed_V),
        R_jacobian=np.ascontiguousarray(dR),
        f3_jacobian=lower.f3_jacobian,
        f4_jacobian=lower.f4_jacobian,
        f5_jacobian=np.ascontiguousarray(df5),
        T_jacobian=lower.T_jacobian,
        U_jacobian=lower.U_jacobian,
        V_jacobian=np.ascontiguousarray(dreconstructed_V),
        f3_symmetry_defect=lower.f3_symmetry_defect,
        f4_symmetry_defect=lower.f4_symmetry_defect,
        f5_symmetry_defect=f5_defect,
        relative_reconstruction_error=reconstruction_error,
        raw_symplectic_residual=formal_fourth_order_symplectic_residual(R, T, U, V),
        reconstructed_symplectic_residual=formal_fourth_order_symplectic_residual(
            R, lower.T, lower.U, reconstructed_V
        ),
    )


def third_order_lie_map_from_multipoles(
    multipole_response,
    segment_lengths,
    magnetic_rigidity,
    *,
    curvature_sign=1.0,
    gradient_sign=1.0,
    reference_beta=1.0,
    maximum_step_m=1.0e-3,
    maximum_steps=1_000_000,
    factorization_tolerance=1.0e-8,
) -> ThirdOrderLieMap:
    """Build a formally symplectic third-order map from canonical Hamiltonians."""
    lengths = _finite_array(segment_lengths, name="segment_lengths").reshape(-1)
    if lengths.size == 0 or np.any(lengths <= 0.0):
        raise ValueError("segment_lengths must be non-empty and positive")
    coefficients = _unpack_third_order_multipoles(multipole_response, lengths.size)
    step_limit = float(maximum_step_m)
    step_cap = int(maximum_steps)
    tolerance = float(factorization_tolerance)
    if (
        not np.isfinite(step_limit)
        or step_limit <= 0.0
        or step_cap < 1
        or not np.isfinite(tolerance)
        or tolerance < 0.0
    ):
        raise ValueError("Lie integration/factorization limits are invalid")

    parameter_count = coefficients.size
    accumulated = _identity_third_order(parameter_count)
    A_values = np.empty((lengths.size, 6, 6))
    F2_values = np.empty((lengths.size, 6, 6, 6))
    F3_values = np.empty((lengths.size, 6, 6, 6, 6))
    dA_values = np.empty((lengths.size, 7, 6, 6))
    total_steps = 0
    for segment, length in enumerate(lengths):
        jet = canonical_body_hamiltonian_jet(
            coefficients[:, segment],
            magnetic_rigidity,
            curvature_sign=curvature_sign,
            gradient_sign=gradient_sign,
            reference_beta=reference_beta,
        )
        A_values[segment] = jet.A
        F2_values[segment] = jet.F2
        F3_values[segment] = jet.F3
        dA_values[segment] = jet.A_jacobian
        step_count = int(np.ceil(length / step_limit))
        total_steps += step_count
        if total_steps > step_cap:
            raise ValueError("Lie-map integration exceeds maximum_steps")
        step = _third_order_rk4_step(
            jet.A,
            jet.F2,
            jet.F3,
            jet.A_jacobian,
            jet.F2_jacobian,
            jet.F3_jacobian,
            length / step_count,
        )
        local = _identity_third_order(7)
        for _ in range(step_count):
            local = _compose_third_order(step, local)
        embedded = _identity_third_order(parameter_count)
        embedded = (
            local[0],
            local[1],
            local[2],
            np.zeros_like(embedded[3]),
            np.zeros_like(embedded[4]),
            np.zeros_like(embedded[5]),
        )
        indexes = np.asarray(
            [block * lengths.size + segment for block in range(7)], dtype=np.int64
        )
        embedded[3][indexes] = local[3]
        embedded[4][indexes] = local[4]
        embedded[5][indexes] = local[5]
        accumulated = _compose_third_order(embedded, accumulated)

    from .beam import propagate_variational_map

    native = propagate_variational_map(
        lengths,
        A_values,
        F2_values,
        F3_values,
        maximum_order=3,
        maximum_step_m=step_limit,
        maximum_steps=step_cap,
    )
    native_R = np.asarray(native["R"], dtype=float)
    native_T = np.asarray(native["T"], dtype=float)
    native_U = np.asarray(native["U"], dtype=float)
    if (
        not np.allclose(accumulated[0], native_R, rtol=2.0e-12, atol=2.0e-13)
        or not np.allclose(accumulated[1], native_T, rtol=3.0e-11, atol=3.0e-12)
        or not np.allclose(accumulated[2], native_U, rtol=8.0e-10, atol=8.0e-11)
    ):
        raise RuntimeError(
            "forward-AD Hamiltonian propagation disagrees with the native value"
        )

    exact_R, exact_dR = _exact_linear_map_with_tangent(A_values, dA_values, lengths)
    factorization = dragt_finn_factorize_third_order(
        exact_R,
        native_T,
        native_U,
        R_jacobian=exact_dR,
        T_jacobian=accumulated[4],
        U_jacobian=accumulated[5],
    )
    if (
        factorization.maximum_generator_symmetry_defect > tolerance
        or factorization.relative_reconstruction_error > tolerance
        or factorization.reconstructed_symplectic_residual.maximum
        > 20.0 * max(tolerance, np.finfo(float).eps)
    ):
        raise RuntimeError(
            "Hamiltonian map failed the Dragt-Finn integrability/projection gate"
        )
    return ThirdOrderLieMap(
        R=factorization.R,
        T=factorization.T,
        U=factorization.U,
        R_jacobian=factorization.R_jacobian,
        T_jacobian=factorization.T_jacobian,
        U_jacobian=factorization.U_jacobian,
        f3=factorization.f3,
        f4=factorization.f4,
        f3_jacobian=factorization.f3_jacobian,
        f4_jacobian=factorization.f4_jacobian,
        raw_R=native_R,
        raw_T=native_T,
        raw_U=native_U,
        factorization=factorization,
        multipole_components=THIRD_ORDER_MULTIPOLE_COMPONENTS,
    )


def fourth_order_lie_map_from_multipoles(
    multipole_response,
    segment_lengths,
    magnetic_rigidity,
    *,
    curvature_sign=1.0,
    gradient_sign=1.0,
    reference_beta=1.0,
    maximum_step_m=1.0e-3,
    maximum_steps=1_000_000,
    factorization_tolerance=1.0e-8,
) -> FourthOrderLieMap:
    """Build the fourth-order map generated by body ``H2/H3/H4``.

    ``V`` contains direct fourth-order coordinate terms generated by the
    nonlinear flow and all lower-order cascades.  A direct fifth-degree
    Hamiltonian (for example a decapole ``H5`` term) is intentionally outside
    this contract and can be added later without changing the ``f5`` API.
    """
    lengths = _finite_array(segment_lengths, name="segment_lengths").reshape(-1)
    if lengths.size == 0 or np.any(lengths <= 0.0):
        raise ValueError("segment_lengths must be non-empty and positive")
    coefficients = _unpack_third_order_multipoles(
        multipole_response, lengths.size
    )
    step_limit = float(maximum_step_m)
    step_cap = int(maximum_steps)
    tolerance = float(factorization_tolerance)
    if (
        not np.isfinite(step_limit)
        or step_limit <= 0.0
        or step_cap < 1
        or not np.isfinite(tolerance)
        or tolerance < 0.0
    ):
        raise ValueError("fourth-order Lie integration/factorization limits are invalid")

    # The established native-valued third-order lane remains the independent
    # lower-order oracle.  The new rank-five variational equation is checked
    # against it before f5 projection.
    lower = third_order_lie_map_from_multipoles(
        coefficients.reshape(-1),
        lengths,
        magnetic_rigidity,
        curvature_sign=curvature_sign,
        gradient_sign=gradient_sign,
        reference_beta=reference_beta,
        maximum_step_m=step_limit,
        maximum_steps=step_cap,
        factorization_tolerance=tolerance,
    )
    parameter_count = coefficients.size
    accumulated = _identity_fourth_order(parameter_count)
    total_steps = 0
    for segment, length in enumerate(lengths):
        jet = canonical_body_hamiltonian_jet(
            coefficients[:, segment],
            magnetic_rigidity,
            curvature_sign=curvature_sign,
            gradient_sign=gradient_sign,
            reference_beta=reference_beta,
        )
        step_count = int(np.ceil(length / step_limit))
        total_steps += step_count
        if total_steps > step_cap:
            raise ValueError("fourth-order Lie-map integration exceeds maximum_steps")
        step = _fourth_order_rk4_step(
            jet.A,
            jet.F2,
            jet.F3,
            jet.A_jacobian,
            jet.F2_jacobian,
            jet.F3_jacobian,
            length / step_count,
        )
        local = _identity_fourth_order(7)
        for _ in range(step_count):
            local = _compose_fourth_order(step, local)
        embedded = list(_identity_fourth_order(parameter_count))
        embedded[:4] = local[:4]
        indexes = np.asarray(
            [block * lengths.size + segment for block in range(7)], dtype=np.int64
        )
        for derivative_index in range(4):
            embedded[4 + derivative_index][indexes] = local[4 + derivative_index]
        accumulated = _compose_fourth_order(tuple(embedded), accumulated)

    if (
        not np.allclose(accumulated[0], lower.raw_R, rtol=2.0e-12, atol=2.0e-13)
        or not np.allclose(
            accumulated[1], lower.raw_T, rtol=3.0e-11, atol=3.0e-12
        )
        or not np.allclose(
            accumulated[2], lower.raw_U, rtol=8.0e-10, atol=8.0e-11
        )
    ):
        raise RuntimeError(
            "fourth-order forward AD disagrees with the native lower-order map"
        )
    factorization = dragt_finn_factorize_fourth_order(
        lower.R,
        lower.raw_T,
        lower.raw_U,
        accumulated[3],
        R_jacobian=lower.R_jacobian,
        T_jacobian=accumulated[5],
        U_jacobian=accumulated[6],
        V_jacobian=accumulated[7],
    )
    if (
        factorization.maximum_generator_symmetry_defect > tolerance
        or factorization.relative_reconstruction_error > tolerance
        or factorization.reconstructed_symplectic_residual.maximum
        > 30.0 * max(tolerance, np.finfo(float).eps)
    ):
        raise RuntimeError(
            "Hamiltonian map failed the fourth-order Dragt-Finn gate"
        )
    return FourthOrderLieMap(
        R=factorization.R,
        T=factorization.T,
        U=factorization.U,
        V=factorization.V,
        R_jacobian=factorization.R_jacobian,
        T_jacobian=factorization.T_jacobian,
        U_jacobian=factorization.U_jacobian,
        V_jacobian=factorization.V_jacobian,
        f3=factorization.f3,
        f4=factorization.f4,
        f5=factorization.f5,
        f3_jacobian=factorization.f3_jacobian,
        f4_jacobian=factorization.f4_jacobian,
        f5_jacobian=factorization.f5_jacobian,
        raw_R=accumulated[0].copy(),
        raw_T=accumulated[1].copy(),
        raw_U=accumulated[2].copy(),
        raw_V=accumulated[3].copy(),
        factorization=factorization,
        multipole_components=THIRD_ORDER_MULTIPOLE_COMPONENTS,
    )


@dataclass(frozen=True)
class PlanarThirdOrderLieMapObjective(PlanarThirdOrderTaylorMapObjective):
    """Selected ``R/T/U`` objective evaluated through canonical Lie factors."""

    reference_beta: float = 1.0
    factorization_tolerance: float = 1.0e-8
    target_symplectic_tolerance: float = 1.0e-9

    def __post_init__(self):
        super().__post_init__()
        beta = float(self.reference_beta)
        tolerance = float(self.factorization_tolerance)
        target_tolerance = float(self.target_symplectic_tolerance)
        if (
            not np.isfinite(beta)
            or beta <= 0.0
            or beta > 1.0
            or not np.isfinite(tolerance)
            or tolerance < 0.0
            or not np.isfinite(target_tolerance)
            or target_tolerance < 0.0
        ):
            raise ValueError("Lie objective beta/tolerance are invalid")
        target_residual = formal_symplectic_residual(
            self.target_R, self.target_T, self.target_U
        )
        if target_residual.maximum > target_tolerance:
            raise ValueError(
                "target R/T/U is not formally symplectic through third order"
            )
        object.__setattr__(self, "reference_beta", beta)
        object.__setattr__(self, "factorization_tolerance", tolerance)
        object.__setattr__(self, "target_symplectic_tolerance", target_tolerance)
        object.__setattr__(self, "_target_symplectic_residual", target_residual)

    @property
    def target_symplectic_residual(self) -> FormalSymplecticResidual:
        return self._target_symplectic_residual

    @property
    def derivative_backend(self) -> str:
        return "forward-mode-hamiltonian-lie-ad"

    def evaluate_taylor_map(self, field_response) -> ThirdOrderLieMap:
        return third_order_lie_map_from_multipoles(
            field_response,
            self.orbit.segment_lengths,
            self.orbit.magnetic_rigidity,
            curvature_sign=self.curvature_sign,
            gradient_sign=self.gradient_sign,
            reference_beta=self.reference_beta,
            maximum_step_m=self.maximum_step_m,
            factorization_tolerance=self.factorization_tolerance,
        )


def _checked_v_entries(entries):
    result = tuple(tuple(int(value) for value in item) for item in entries)
    if (
        not result
        or len(set(result)) != len(result)
        or any(len(item) != 5 for item in result)
        or any(index < 0 or index >= 6 for item in result for index in item)
    ):
        raise ValueError("V_entries must contain unique zero-based rank-5 indices")
    if any(
        first > second or second > third or third > fourth
        for _, first, second, third, fourth in result
    ):
        raise ValueError(
            "V entries must use canonical order first<=second<=third<=fourth"
        )
    return result


@dataclass(frozen=True)
class PlanarFourthOrderLieMapObjective(PlanarThirdOrderLieMapObjective):
    """Selected canonical ``R/T/U/V`` objective with an ``f5`` gate."""

    target_V: np.ndarray | None = None
    V_band: np.ndarray | float = 1.0
    V_entries: tuple[tuple[int, int, int, int, int], ...] = (
        _ALL_SYMMETRIC_V_ENTRIES
    )

    def __post_init__(self):
        super().__post_init__()
        if self.target_V is None:
            raise ValueError("target_V is required for a fourth-order Lie objective")
        target_V = _finite_array(
            self.target_V, shape=(6, 6, 6, 6, 6), name="target_V"
        )
        symmetry_defect = max(
            float(
                np.max(
                    np.abs(target_V - np.transpose(target_V, (0,) + ordered)),
                    initial=0.0,
                )
            )
            for ordered in set(permutations((1, 2, 3, 4)))
        )
        symmetry_scale = max(1.0, float(np.max(np.abs(target_V), initial=0.0)))
        if symmetry_defect > 1.0e-12 * symmetry_scale:
            raise ValueError("target_V input indices must be symmetric")
        V_band = np.broadcast_to(
            np.asarray(self.V_band, dtype=float), (6, 6, 6, 6, 6)
        ).copy()
        V_entries = _checked_v_entries(self.V_entries)
        if not np.all(np.isfinite(V_band)) or np.any(V_band <= 0.0):
            raise ValueError("V_band must be finite and positive")
        target_residual = formal_fourth_order_symplectic_residual(
            self.target_R, self.target_T, self.target_U, target_V
        )
        if target_residual.maximum > self.target_symplectic_tolerance:
            raise ValueError(
                "target R/T/U/V is not formally symplectic through fourth order"
            )
        object.__setattr__(self, "target_V", target_V.copy())
        object.__setattr__(self, "V_band", V_band)
        object.__setattr__(self, "V_entries", V_entries)
        object.__setattr__(self, "_target_symplectic_residual", target_residual)

    @property
    def target_symplectic_residual(self) -> FormalFourthOrderSymplecticResidual:
        return self._target_symplectic_residual

    @property
    def derivative_backend(self) -> str:
        return "forward-mode-fourth-order-hamiltonian-lie-ad"

    @property
    def response_target(self) -> np.ndarray:
        return np.r_[
            super().response_target,
            [self.target_V[index] for index in self.V_entries],
        ]

    @property
    def response_band(self) -> np.ndarray:
        return np.r_[
            super().response_band,
            [self.V_band[index] for index in self.V_entries],
        ]

    @property
    def response_slices(self) -> tuple[tuple[str, slice], ...]:
        lower = super().response_slices
        start = lower[-1][1].stop
        return lower + (("V", slice(start, start + len(self.V_entries))),)

    def evaluate_taylor_map(self, field_response) -> FourthOrderLieMap:
        return fourth_order_lie_map_from_multipoles(
            field_response,
            self.orbit.segment_lengths,
            self.orbit.magnetic_rigidity,
            curvature_sign=self.curvature_sign,
            gradient_sign=self.gradient_sign,
            reference_beta=self.reference_beta,
            maximum_step_m=self.maximum_step_m,
            factorization_tolerance=self.factorization_tolerance,
        )

    def transform(self, field_response) -> np.ndarray:
        values = _unpack_third_order_multipoles(
            field_response, len(self.orbit.segment_lengths)
        )
        transfer = self.evaluate_taylor_map(values.reshape(-1))
        return np.r_[
            values[0],
            [transfer.R[index] for index in self.R_entries],
            [transfer.T[index] for index in self.T_entries],
            [transfer.U[index] for index in self.U_entries],
            [transfer.V[index] for index in self.V_entries],
        ]

    def transform_jacobian(self, field_response) -> np.ndarray:
        transfer = self.evaluate_taylor_map(field_response)
        count = len(self.orbit.segment_lengths)
        dipole = np.zeros((count, self.raw_field_response_size))
        dipole[np.arange(count), np.arange(count)] = 1.0

        def rows(tensor, entries):
            return np.asarray(
                [tensor[(slice(None),) + index] for index in entries]
            )

        return np.vstack(
            (
                dipole,
                rows(transfer.R_jacobian, self.R_entries),
                rows(transfer.T_jacobian, self.T_entries),
                rows(transfer.U_jacobian, self.U_entries),
                rows(transfer.V_jacobian, self.V_entries),
            )
        )


@dataclass(frozen=True)
class FourthOrderLieMaterialInversePipelineResult:
    """Auditable field -> ``R/T/U/V`` -> TSVD/ACA material chain."""

    objective: PlanarFourthOrderLieMapObjective
    multipole_distribution: np.ndarray
    realized_R: np.ndarray
    realized_T: np.ndarray
    realized_U: np.ndarray
    realized_V: np.ndarray
    R_difference: np.ndarray
    T_difference: np.ndarray
    U_difference: np.ndarray
    V_difference: np.ndarray
    normalized_R_difference: np.ndarray
    normalized_T_difference: np.ndarray
    normalized_U_difference: np.ndarray
    normalized_V_difference: np.ndarray
    reachability: object
    automatic_differentiation: object
    multipole_correction: object
    material_selection: object
    proposed_R: np.ndarray
    proposed_T: np.ndarray
    proposed_U: np.ndarray
    proposed_V: np.ndarray
    proposed_exact_max_band_ratio: float
    stage_order: tuple[str, ...] = (
        "rk-tracked-reference-orbit-and-moving-frame",
        "normal-skew-body-multipoles-through-octupole",
        "forward-ad-fourth-order-lie-map-f3-f4-f5",
        "target-R-T-U-V-difference",
        "tsvd-reachability-certificate",
        "tsvd-minimax-multipole-correction",
        "aca-thin-qr-tsvd-material-inverse",
        "exact-R-T-U-V-dragt-finn-gate",
    )


@dataclass(frozen=True)
class FourthOrderLieTopologyResult:
    """Whole-element topology result scored against ``R/T/U/V``."""

    objective: PlanarFourthOrderLieMapObjective
    generation: object
    realized_multipole_response: np.ndarray
    realized_R: np.ndarray
    realized_T: np.ndarray
    realized_U: np.ndarray
    realized_V: np.ndarray
    normal_dipole_max_band_ratio: float
    lie_map_max_band_ratio: float
    topology: object

    @property
    def active_elements(self) -> np.ndarray:
        return self.generation.active_elements

    @property
    def converged(self) -> bool:
        return bool(
            self.normal_dipole_max_band_ratio <= 1.0
            and self.lie_map_max_band_ratio <= 1.0
        )


def run_third_order_lie_material_inverse_pipeline(
    objective: PlanarThirdOrderLieMapObjective, current_multipole_response, **options
):
    """Run TSVD plus ACA/QR/TSVD material inversion against a Lie objective."""
    if not isinstance(objective, PlanarThirdOrderLieMapObjective):
        raise TypeError("objective must be PlanarThirdOrderLieMapObjective")
    return run_third_order_taylor_material_inverse_pipeline(
        objective, current_multipole_response, **options
    )


def optimize_hdiv_mmm_magnet_from_third_order_lie_map(
    objective: PlanarThirdOrderLieMapObjective, **options
):
    """Optimize binary HDiv-MMM material against canonical Lie ``R/T/U``."""
    if not isinstance(objective, PlanarThirdOrderLieMapObjective):
        raise TypeError("objective must be PlanarThirdOrderLieMapObjective")
    return optimize_hdiv_mmm_magnet_from_third_order_taylor_map(objective, **options)


@dataclass(frozen=True)
class TrackedOrbitFourthOrderLieMap:
    """Moving-frame field fit and fourth-order map on an RK-tracked orbit."""

    orbit: PlanarDesignOrbit
    multipole_response: np.ndarray
    transfer: FourthOrderLieMap
    field_fit: dict


def fourth_order_lie_map_from_tracked_orbit(
    field,
    orbit: PlanarDesignOrbit,
    *,
    sample_radius_m=1.0e-3,
    initial_horizontal=(1.0, 0.0, 0.0),
    curvature_sign=1.0,
    gradient_sign=1.0,
    reference_beta=1.0,
    maximum_step_m=1.0e-3,
    maximum_steps=1_000_000,
    factorization_tolerance=1.0e-8,
) -> TrackedOrbitFourthOrderLieMap:
    """Fit moving-frame multipoles after reference-orbit RK tracking.

    Use :func:`radia.ffag_topopt.recover_periodic_planar_closed_orbit` (or an
    equivalent Lorentz RK tracker) first.  This function consumes its
    :class:`PlanarDesignOrbit`, constructs the local transverse moving frame,
    samples the live field through octupole, and then builds ``R/T/U/V`` and
    ``f3/f4/f5``.  The caller owns ``ngsolve.TaskManager`` for field work.
    """
    if not isinstance(orbit, PlanarDesignOrbit):
        raise TypeError("orbit must be an RK-tracked PlanarDesignOrbit")
    from .beam import propagate_grid_function_multipole_map

    tangents = orbit.tangents[:-1] + orbit.tangents[1:]
    tangents /= np.linalg.norm(tangents, axis=1)[:, None]
    fitted = propagate_grid_function_multipole_map(
        field,
        orbit.segment_lengths,
        orbit.sample_positions,
        tangents,
        orbit.magnetic_rigidity,
        sample_radius_m=sample_radius_m,
        initial_horizontal=initial_horizontal,
        curvature_sign=curvature_sign,
        gradient_sign=gradient_sign,
        multipole_order=3,
        maximum_map_order=1,
        maximum_step_m=maximum_step_m,
        maximum_steps=maximum_steps,
    )
    normal = _finite_array(
        fitted["multipole_normal_t_per_m_power"], name="normal multipoles"
    )
    skew = _finite_array(
        fitted["multipole_skew_t_per_m_power"], name="skew multipoles"
    )
    expected = (len(orbit.segment_lengths), 4)
    if normal.shape != expected or skew.shape != expected:
        raise RuntimeError("moving-frame field fit returned an invalid multipole shape")
    response = np.vstack(
        (
            normal[:, 0],
            normal[:, 1],
            skew[:, 1],
            normal[:, 2],
            skew[:, 2],
            normal[:, 3],
            skew[:, 3],
        )
    ).reshape(-1)
    transfer = fourth_order_lie_map_from_multipoles(
        response,
        orbit.segment_lengths,
        orbit.magnetic_rigidity,
        curvature_sign=curvature_sign,
        gradient_sign=gradient_sign,
        reference_beta=reference_beta,
        maximum_step_m=maximum_step_m,
        maximum_steps=maximum_steps,
        factorization_tolerance=factorization_tolerance,
    )
    return TrackedOrbitFourthOrderLieMap(
        orbit=orbit,
        multipole_response=np.ascontiguousarray(response),
        transfer=transfer,
        field_fit=fitted,
    )


def differentiate_fourth_order_lie_field_response(
    objective: PlanarFourthOrderLieMapObjective,
    current_multipole_response,
    *,
    field_basis=None,
):
    """Return full/directional forward AD for selected ``R/T/U/V`` rows."""
    if not isinstance(objective, PlanarFourthOrderLieMapObjective):
        raise TypeError("objective must be PlanarFourthOrderLieMapObjective")
    return differentiate_transfer_matrix_field_response(
        objective, current_multipole_response, field_basis=field_basis
    )


def run_fourth_order_lie_material_inverse_pipeline(
    objective: PlanarFourthOrderLieMapObjective,
    current_multipole_response,
    **options,
) -> FourthOrderLieMaterialInversePipelineResult:
    """Run reachability, TSVD correction, and ACA/QR/TSVD material inversion."""
    if not isinstance(objective, PlanarFourthOrderLieMapObjective):
        raise TypeError("objective must be PlanarFourthOrderLieMapObjective")
    current = _finite_array(
        current_multipole_response, name="current_multipole_response"
    ).reshape(-1)
    base = run_third_order_taylor_material_inverse_pipeline(
        objective, current, **options
    )
    realized = objective.evaluate_taylor_map(current)
    proposed = objective.evaluate_taylor_map(
        base.material_selection.predicted_response
    )
    return FourthOrderLieMaterialInversePipelineResult(
        objective=objective,
        multipole_distribution=current.copy(),
        realized_R=realized.R.copy(),
        realized_T=realized.T.copy(),
        realized_U=realized.U.copy(),
        realized_V=realized.V.copy(),
        R_difference=objective.target_R - realized.R,
        T_difference=objective.target_T - realized.T,
        U_difference=objective.target_U - realized.U,
        V_difference=objective.target_V - realized.V,
        normalized_R_difference=(objective.target_R - realized.R) / objective.R_band,
        normalized_T_difference=(objective.target_T - realized.T) / objective.T_band,
        normalized_U_difference=(objective.target_U - realized.U) / objective.U_band,
        normalized_V_difference=(objective.target_V - realized.V) / objective.V_band,
        reachability=base.reachability,
        automatic_differentiation=base.automatic_differentiation,
        multipole_correction=base.multipole_correction,
        material_selection=base.material_selection,
        proposed_R=proposed.R.copy(),
        proposed_T=proposed.T.copy(),
        proposed_U=proposed.U.copy(),
        proposed_V=proposed.V.copy(),
        proposed_exact_max_band_ratio=base.proposed_exact_max_band_ratio,
    )


def optimize_hdiv_mmm_magnet_from_fourth_order_lie_map(
    objective: PlanarFourthOrderLieMapObjective, **options
) -> FourthOrderLieTopologyResult:
    """Optimize binary HDiv-MMM material against selected ``R/T/U/V`` rows."""
    if not isinstance(objective, PlanarFourthOrderLieMapObjective):
        raise TypeError("objective must be PlanarFourthOrderLieMapObjective")
    base = optimize_hdiv_mmm_magnet_from_third_order_taylor_map(
        objective, **options
    )
    transfer = objective.evaluate_taylor_map(base.realized_multipole_response)
    V_ratio = max(
        abs((transfer.V[index] - objective.target_V[index]) / objective.V_band[index])
        for index in objective.V_entries
    )
    return FourthOrderLieTopologyResult(
        objective=objective,
        generation=base.generation,
        realized_multipole_response=base.realized_multipole_response.copy(),
        realized_R=transfer.R.copy(),
        realized_T=transfer.T.copy(),
        realized_U=transfer.U.copy(),
        realized_V=transfer.V.copy(),
        normal_dipole_max_band_ratio=base.normal_dipole_max_band_ratio,
        lie_map_max_band_ratio=float(max(base.taylor_map_max_band_ratio, V_ratio)),
        topology=base.topology,
    )


__all__ = [
    "CanonicalHamiltonianJet",
    "DragtFinnFactorization",
    "DragtFinnFourthOrderFactorization",
    "FormalFourthOrderSymplecticResidual",
    "FormalSymplecticResidual",
    "FourthOrderLieMap",
    "FourthOrderLieMaterialInversePipelineResult",
    "FourthOrderLieTopologyResult",
    "PlanarFourthOrderLieMapObjective",
    "PlanarThirdOrderLieMapObjective",
    "ThirdOrderLieMap",
    "TrackedOrbitFourthOrderLieMap",
    "apply_dragt_finn_map",
    "apply_homogeneous_lie_generator",
    "canonical_body_hamiltonian_jet",
    "canonical_body_hamiltonian_rhs",
    "canonical_poisson_matrix",
    "differentiate_fourth_order_lie_field_response",
    "dragt_finn_factorize_fourth_order",
    "dragt_finn_factorize_third_order",
    "formal_fourth_order_symplectic_residual",
    "formal_symplectic_residual",
    "fourth_order_lie_map_from_multipoles",
    "fourth_order_lie_map_from_tracked_orbit",
    "optimize_hdiv_mmm_magnet_from_fourth_order_lie_map",
    "optimize_hdiv_mmm_magnet_from_third_order_lie_map",
    "run_fourth_order_lie_material_inverse_pipeline",
    "run_third_order_lie_material_inverse_pipeline",
    "third_order_lie_map_from_multipoles",
]
