"""
Shared base for Radia standalone analysis windows (PySide6).

Provides:
  - ModePanel: form layout with add_line/add_combo/add_spin/add_browse helpers
  - AnalysisWindow: QMainWindow with Run/Stop/Save/GMSH buttons + QProcess
"""

import json
import os
import sys

from PySide6.QtCore import Qt, QProcess
from PySide6.QtGui import QFont, QIcon
from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget,
    QVBoxLayout, QHBoxLayout, QFormLayout,
    QLabel, QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QCheckBox,
    QPushButton, QPlainTextEdit, QFileDialog,
    QMessageBox, QSplitter, QGroupBox, QStyle,
    QScrollArea, QFrame,
)

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PANELS_DIR = os.path.join(_THIS_DIR, "panels")
_RESOURCES_DIR = os.path.join(_THIS_DIR, "resources")
_PYTHON = sys.executable
_SETTINGS_DIR = os.path.join(os.path.expanduser("~"), ".radia")


def radia_version():
    """Installed ``radia`` version string for the Output banner.

    Lightweight: reads the package *dist metadata* via
    ``importlib.metadata`` -- it does NOT ``import radia`` (which would
    load the heavy MKL + C++ extension into the GUI process, violating
    the Layer-3 "no radia import" boundary).  Returns ``"unknown"`` if
    the metadata cannot be read.
    """
    try:
        from importlib.metadata import version, PackageNotFoundError
        try:
            return version("radia")
        except PackageNotFoundError:
            return "unknown"
    except Exception:
        return "unknown"

# ----------------------------------------------------------------------
# Shared CoilBuilder starter template (written by the EM and IH panels'
# "New..." buttons).  Self-contained: includes the sys.path bootstrap,
# the build_coil() entry point the EM panel imports, and a __main__
# block that ALSO writes a sibling .step (for IH PEEC + visualisation).
# Numbers are a generic racetrack -- the user edits the EDIT BLOCK at
# the top of build_coil() to retarget for their magnet / coil.
# ----------------------------------------------------------------------
COIL_TEMPLATE = '''"""Starter coil for Radia panels (CoilBuilder).

Generated by the Radia EM / IH panel "New..." button.  Edit the
numbers in the EDIT BLOCK below to match your coil, then point the
panel field (Coil script for EM, STEP for IH) at:
    EM        this .py
    IH/PEEC   the sibling .step that __main__ writes when this .py
              is run (see bottom of this file)

CoilBuilder API summary (see src/radia/coil_builder.py for full):
  .set_start([x, y, z])              -- start position (meters)
  .set_cross_section(width, height)  -- cross-section (meters)
  .add_straight(length)              -- run straight along current direction
  .add_arc(radius, arc_angle, tilt=0)  -- circular arc (degrees)
  .mirror(plane)                     -- 'xy' / 'xz' / 'yz' (current flips)
  .rotate_copies(n, axis)            -- N rotated copies (multipoles)

The panels consume the CoilBuilder via:
  - .to_radia()           (FEM / MSC: list of Radia objects, Biot-Savart)
  - .to_wire_segments()   (PEEC: filament centerline + current)
  - .write_step(path)     (PEEC STEP path: swept solid for the coil)
"""
import os
import sys

# Resolve src/radia for the CoilBuilder import; this file is expected
# to live somewhere under the repo or alongside an installed copy.
_HERE = os.path.dirname(os.path.abspath(__file__))
for _up in range(5):
    _candidate = os.path.normpath(
        os.path.join(_HERE, *[".."] * _up, "src", "radia"))
    if os.path.isfile(os.path.join(_candidate, "coil_builder.py")):
        sys.path.insert(0, _candidate)
        break

from coil_builder import CoilBuilder


def build_coil():
    """Return a CoilBuilder instance describing the coil."""
    mm = 1e-3

    # ===== EDIT BLOCK: set these to match your magnet ================
    NI       = 2000                    # ampere-turns (A)
    START    = [25 * mm, 100 * mm, 0]  # corner where the coil begins
    WIDTH    = 35 * mm                 # cross-section -- radial dim
    HEIGHT   = 105 * mm                # cross-section -- axial dim
    STRAIGHT = 60 * mm                 # straight-section length
    ARC_R    = 22.5 * mm               # bending arc radius (centerline)
    # ================================================================

    coil = (CoilBuilder(current=NI)
        .set_start(START)
        .set_cross_section(width=WIDTH, height=HEIGHT)
        .add_straight(STRAIGHT)
        .add_arc(radius=ARC_R, arc_angle=90)
        .add_straight(STRAIGHT)
        .add_arc(radius=ARC_R, arc_angle=90)
        .add_straight(STRAIGHT)
        .add_arc(radius=ARC_R, arc_angle=90)
        .add_straight(STRAIGHT)
        .add_arc(radius=ARC_R, arc_angle=90))
    return coil


if __name__ == "__main__":
    coil = build_coil()
    segs, current = coil.to_wire_segments()
    print(f"Wire segments: {len(segs)}, current: {current} A")
    print(f"Gap: {coil.gap:.6e} m, closed: {coil.is_closed}")
    # STEP export -- needed for the IH panel PEEC modes.  Skipped
    # silently if netgen.occ is unavailable (allows EM-only setups
    # without NGSolve/Netgen installed to still print wire-seg info).
    step_out = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    try:
        coil.write_step(step_out)
        print(f"Wrote {step_out}")
    except Exception as exc:
        print(f"STEP export skipped: {exc}")
'''


# Lab-standard panel font baseline.  Target display is 2K+ (per
# feedback_panel_vertical_space.md).  Bracketing from user feedback
# 2026-04-26:
#   -  9pt (Qt OS default) -- "小さすぎる", unreadable on 2K
#   - 11pt (first bump)    -- "637x740みたいにケチらなくてよい",
#                              still felt stingy at desk distance
#   - 13pt (over-correct)  -- too big
#   - 12pt                 -- "12pt あれば十分です" (chosen)
#
# Family is intentionally NOT hardcoded -- apply_panel_base_font
# inherits the OS default family (Segoe UI on Windows, system
# sans-serif on Linux/macOS) and bumps only the point size.
PANEL_BASE_FONT_POINT_SIZE = 10  # 2026-05-29: 11 -> 10 per kubota readability request
PANEL_OUTPUT_FONT_POINT_SIZE = 10  # smaller for the log/output text box

# Shared panel debug log (C:/radia_panel_log.txt on Windows). Append-only
# from this process; the Cubit-side register_toolbar.py truncates it on
# session start so the file holds one continuous Cubit session log.
if _PANELS_DIR not in sys.path:
    sys.path.insert(0, _PANELS_DIR)
try:
    from panel_log import (init_panel_log, panel_log,
                           panel_log_exception, PANEL_LOG_PATH)
    init_panel_log("ih-window", truncate=False, banner=True)
    panel_log(f"radia_gui_base.py file={__file__}")
except Exception:
    # Panel log is best-effort. Define no-op shims so the analysis
    # windows still run if panel_log.py is missing for any reason.
    PANEL_LOG_PATH = ""
    def panel_log(_msg):
        pass
    def panel_log_exception(_prefix=""):
        pass


def _icon_path():
    """Resolve the Radia panel window icon.

    Prefers (in order):
      1. `radia_icon.ico` or `radia_icon.png` (canonical fixed name)
      2. The most recently-modified `.ico` or `.png` in
         `src/radia/resources/` (dated logos like `2026_04_26.png`).

    The dated-filename fallback lets the user drop a new logo into
    `resources/` without renaming -- the resolver picks it up by
    mtime.  Returns "" if no image is found.
    """
    if not os.path.isdir(_RESOURCES_DIR):
        return ""
    # 1. Canonical fixed name
    for ext in (".ico", ".png"):
        p = os.path.join(_RESOURCES_DIR, "radia_icon" + ext)
        if os.path.isfile(p):
            return p
    # 2. Most recent .ico / .png in the resources directory
    candidates = []
    for fname in os.listdir(_RESOURCES_DIR):
        ext = os.path.splitext(fname)[1].lower()
        if ext in (".ico", ".png"):
            full = os.path.join(_RESOURCES_DIR, fname)
            try:
                candidates.append((os.path.getmtime(full), ext, full))
            except OSError:
                pass
    if not candidates:
        return ""
    # Prefer .ico over .png at equal mtime; among same ext, newest mtime.
    candidates.sort(key=lambda t: (t[0], 0 if t[1] == ".ico" else 1),
                    reverse=True)
    return candidates[0][2]


def calc_script(name):
    return os.path.join(_PANELS_DIR, name)


def msh_output(vol_path, suffix):
    base = vol_path if vol_path else "output"
    return os.path.splitext(base)[0] + suffix + ".msh"


def json_output(base_path, suffix):
    """Companion to msh_output: <base>_<suffix>.json next to the input.

    base_path: any input path the analysis is keyed on (.vol or .step).
    The .json is written by calc_main when --output is passed and lives
    next to the .msh so users can find both side-by-side.
    """
    base = base_path if base_path else "output"
    return os.path.splitext(base)[0] + suffix + ".json"


# ============================================================
# ModePanel: form layout base
# ============================================================

# ----------------------------------------------------------------------
# Wheel-guarded input widgets.
#
# A bare QComboBox / QSpinBox grabs mouse-wheel events and changes its
# value -- even when the user only meant to SCROLL THE FORM.  In a tall
# parameter panel this silently mutates a selection the user already
# set and believes is fixed (kubota 2026-05-29: after clicking a combo
# to inspect it, scrolling the form kept changing the selection
# unnoticed -> wrong run input, hard to confirm).  These subclasses
# ignore the wheel event so it propagates to the parent scroll area
# (the form scrolls); the value changes ONLY via click+dropdown /
# arrows / keyboard.  Enforced by tests/panels/test_combo_wheel_guard.py
# (panel-wheel-guard skill).
# ----------------------------------------------------------------------
class _NoWheelComboBox(QComboBox):
    def wheelEvent(self, event):  # noqa: N802 (Qt override)
        event.ignore()


class _NoWheelSpinBox(QSpinBox):
    def wheelEvent(self, event):  # noqa: N802
        event.ignore()


class _NoWheelDoubleSpinBox(QDoubleSpinBox):
    def wheelEvent(self, event):  # noqa: N802
        event.ignore()


class ModePanel(QWidget):
    """Base class for analysis parameter panels."""

    _RED = "QLineEdit { background-color: #FFD0D0; }"
    _NORMAL = ""

    def __init__(self, parent=None):
        super().__init__(parent)
        self._form = QFormLayout()
        self._form.setLabelAlignment(Qt.AlignRight)
        # Row spacing = 17 px (= 13 pt) for the user-set 11 pt body
        # text baseline (2026-04-29 update: panel font 12 -> 11 pt,
        # text-box font 10 pt, line spacing 13 pt).  Windows default
        # QFormLayout verticalSpacing (~6 px) was too tight at any
        # of those sizes; explicit setVerticalSpacing keeps the form
        # readable without window resize.
        self._form.setVerticalSpacing(17)
        self._form.setHorizontalSpacing(10)
        self.setLayout(self._form)
        self._widgets = {}
        self._row_indices = {}
        # Optional per-panel status line (created lazily by
        # add_status_label).  Lives in self._status_label so panel_qa
        # and subclasses can find it consistently.
        self._status_label = None

    # ------------------------------------------------------------------
    # Section header (hoisted from radia_em / radia_ih -- 2026-04-26).
    # Both panels had identical 9-line copies; kept the IH docstring
    # which captures the offscreen-vs-real-desktop rendering lesson.
    # ------------------------------------------------------------------
    def _add_section(self, title, key=None):
        """Insert a visual section header into the form.

        Section header is a QLabel with bold HTML text.  Must use an
        explicit fixed height computed from fontMetrics: stylesheet
        ``padding`` / ``margin`` are painted INSIDE the widget rect but
        NOT added to sizeHint, so QFormLayout gives the row a
        too-small height and the bold text gets vertically clipped
        (visible as dotted lines on the real desktop, even though
        offscreen measurements read as "OK").

        Section header font is +1pt above the panel baseline so
        sections are clearly distinguished from their fields.

        ``key`` registers the row in ``self._row_indices`` so it can be
        collapsed together with the widgets it groups via
        ``_set_row_visible(key, False)``.
        """
        lbl = QLabel(f"<b>{title}</b>")
        f = lbl.font()
        f.setPointSize(f.pointSize() + 1)
        lbl.setFont(f)
        lbl.setStyleSheet("QLabel { color: #444; }")
        # Height = text bounding-box + 10 px breathing room above/below.
        fm_h = lbl.fontMetrics().boundingRect("Mg").height()
        lbl.setFixedHeight(fm_h + 10)
        self._form.addRow("", lbl)
        if key is not None:
            self._row_indices[key] = self._form.rowCount() - 1

    def add_status_label(self, key=None):
        """Add an optional per-panel status / validation line.

        Stored on ``self._status_label`` for subclasses to update via
        ``self._status_label.setText("...")``.  De-emphasised by
        colour (#888) only -- font size inherits the lab baseline so
        it stays readable on 2K (per feedback_panel_font_baseline.md).

        Returns the QLabel.  Idempotent: a second call returns the
        existing label without adding another row.

        Min height accommodates ~7 wrapped lines so the multi-line
        far-field warning (case D: kelvin + outer both missing,
        explaining PMC reflection) plus 2-3 label/skin-depth hints
        below it display fully without QFormLayout clipping into
        the next section -- 2026-04-28 second Kubota report.
        """
        if self._status_label is not None:
            return self._status_label
        lbl = QLabel("")
        lbl.setWordWrap(True)
        lbl.setStyleSheet("QLabel { color: #888; }")
        fm_h = lbl.fontMetrics().boundingRect("Mg").height()
        lbl.setMinimumHeight(fm_h * 7 + 8)
        self._form.addRow("", lbl)
        self._status_label = lbl
        if key is not None:
            self._row_indices[key] = self._form.rowCount() - 1
        return lbl

    def _set_row_visible(self, key, visible):
        """Show / hide a form row and **collapse** its vertical space.

        Qt 6.4+ provides QFormLayout.setRowVisible() which truly removes
        the row height from the layout.  Without it, just calling
        setVisible(False) on the widgets hides them but keeps the gap,
        making the panel taller than it needs to be.
        """
        row_idx = self._row_indices.get(key)
        if row_idx is None:
            return
        if hasattr(self._form, "setRowVisible"):
            self._form.setRowVisible(row_idx, bool(visible))
            return
        # Fallback: widget-only hide (row height remains — Qt < 6.4)
        label_item = self._form.itemAt(row_idx, QFormLayout.LabelRole)
        field_item = self._form.itemAt(row_idx, QFormLayout.FieldRole)
        if label_item and label_item.widget():
            label_item.widget().setVisible(visible)
        if field_item and field_item.widget():
            field_item.widget().setVisible(visible)

    def add_line(self, key, label, default="", placeholder=""):
        w = QLineEdit(default)
        if placeholder:
            w.setPlaceholderText(placeholder)
        self._form.addRow(label, w)
        self._widgets[key] = w
        self._row_indices[key] = self._form.rowCount() - 1
        return w

    def add_combo(self, key, label, items, default=0):
        w = _NoWheelComboBox()
        w.addItems(items)
        w.setCurrentIndex(default)
        self._form.addRow(label, w)
        self._widgets[key] = w
        self._row_indices[key] = self._form.rowCount() - 1
        return w

    def add_spin(self, key, label, value=1, lo=1, hi=999):
        w = _NoWheelSpinBox()
        w.setRange(lo, hi)
        w.setValue(value)
        self._form.addRow(label, w)
        self._widgets[key] = w
        self._row_indices[key] = self._form.rowCount() - 1
        return w

    def add_check(self, key, label, default=False):
        w = QCheckBox(label)
        w.setChecked(bool(default))
        # Form layout: leave the left label cell blank — the checkbox
        # text itself acts as the label, so a duplicate column is
        # noisy and stacks oddly with the disable/enable toggles.
        self._form.addRow("", w)
        self._widgets[key] = w
        self._row_indices[key] = self._form.rowCount() - 1
        return w

    def add_browse(self, key, label, default="", filter_str="All files (*.*)"):
        row = QHBoxLayout()
        le = QLineEdit(default)
        # Mark this LineEdit as a browse-row absolute-path holder so
        # _refresh_browse_displays / val() know to round-trip through
        # the AnalysisWindow's display_path / resolve_path helpers.
        le.setProperty("_radia_browse_row", True)
        le.setProperty("_radia_browse_filter", filter_str)
        btn = QPushButton("...")
        btn.setFixedWidth(30)
        btn.clicked.connect(lambda: self._do_browse(le, filter_str))
        row.addWidget(le)
        row.addWidget(btn)
        container = QWidget()
        container.setLayout(row)
        row.setContentsMargins(0, 0, 0, 0)
        self._form.addRow(label, container)
        self._widgets[key] = le
        self._row_indices[key] = self._form.rowCount() - 1
        return le

    def _do_browse(self, line_edit, filter_str):
        # Default-open in the AnalysisWindow's working folder when the
        # field is currently empty; otherwise honour the existing path
        # so the user can re-pick a sibling file quickly.
        win = getattr(self, "_analysis_window", None)
        existing = (line_edit.text() or "").strip()
        if existing and win is not None:
            start_dir = os.path.dirname(win.resolve_path(existing))
        elif existing:
            start_dir = os.path.dirname(existing)
        elif win is not None:
            start_dir = win.working_folder
        else:
            start_dir = ""
        path, _ = QFileDialog.getOpenFileName(
            self, "Select file", start_dir, filter_str)
        if path:
            # Store display path: relative-to-folder when inside, abs
            # when outside.  val() round-trips back through resolve_path
            # so subprocess CLI still receives an absolute path.
            if win is not None:
                line_edit.setText(win.display_path(os.path.abspath(path)))
            else:
                line_edit.setText(path)

    def _refresh_browse_displays(self):
        """Re-render every browse-row's displayed path against the
        AnalysisWindow's current working folder.  Called after the user
        changes the folder so existing paths flip between relative and
        absolute as appropriate."""
        win = getattr(self, "_analysis_window", None)
        if win is None:
            return
        for le in self._widgets.values():
            if not hasattr(le, "property"):
                continue
            if not le.property("_radia_browse_row"):
                continue
            cur = (le.text() or "").strip()
            if not cur:
                continue
            le.setText(win.display_path(win.resolve_path(cur)))

    def add_browse_action(self, key, label, callback, fixed_width=None):
        """Append an extra action button to an existing browse row.

        ``key`` must refer to a row created by ``add_browse``.  The
        button is appended to the right of the existing ``...`` browse
        button so the row reads
            [ <line edit> ] [ ... ] [ <label> ]

        ``callback(line_edit)`` is invoked when the button is clicked,
        receiving the existing QLineEdit so the action can read or
        write the current path.

        Returns the QPushButton.  Raises KeyError if the key has no
        registered row index.
        """
        row_idx = self._row_indices[key]
        field_item = self._form.itemAt(row_idx, QFormLayout.FieldRole)
        container = field_item.widget()
        layout = container.layout()
        line_edit = self._widgets[key]
        btn = QPushButton(label)
        if fixed_width is not None:
            btn.setFixedWidth(fixed_width)
        btn.clicked.connect(lambda: callback(line_edit))
        layout.addWidget(btn)
        return btn

    def val(self, key):
        w = self._widgets[key]
        if isinstance(w, QLineEdit):
            txt = w.text().strip()
            # Browse-row paths are stored as display paths (relative
            # to the working folder when inside, absolute otherwise).
            # Resolve to absolute for downstream consumers (CLI args,
            # os.path.isfile checks).
            if w.property("_radia_browse_row") and txt:
                win = getattr(self, "_analysis_window", None)
                if win is not None:
                    return win.resolve_path(txt)
            return txt
        elif isinstance(w, QComboBox):
            return w.currentText()
        elif isinstance(w, QDoubleSpinBox):
            # QDoubleSpinBox must precede QSpinBox in this dispatch
            # because QDoubleSpinBox inherits from QAbstractSpinBox,
            # not QSpinBox; isinstance ordering is safe but explicit
            # so the intent is obvious.  Return formatted with the
            # spinbox's decimals so str() round-trip is stable.
            return f"{w.value():.{w.decimals()}f}"
        elif isinstance(w, QSpinBox):
            return str(w.value())
        elif isinstance(w, QCheckBox):
            return "1" if w.isChecked() else "0"
        return ""

    def save_state(self):
        state = {}
        for key, w in self._widgets.items():
            if isinstance(w, QLineEdit):
                state[key] = w.text()
            elif isinstance(w, QComboBox):
                # Save the SELECTED TEXT, not the index. Combo items can
                # be added / removed / reordered between releases (e.g.
                # the IH panel dropping "BEM-SIBC (WP)" 2026-04-12), and
                # a stale index would silently jump to the wrong item or
                # land out-of-range and leave the combo blank.
                state[key] = w.currentText()
            elif isinstance(w, QDoubleSpinBox):
                # Must precede QSpinBox check -- QDoubleSpinBox is not
                # a QSpinBox subclass but we want explicit ordering for
                # clarity.  Store as float; round-trip via setValue.
                state[key] = float(w.value())
            elif isinstance(w, QSpinBox):
                state[key] = w.value()
            elif isinstance(w, QCheckBox):
                state[key] = w.isChecked()
        return state

    def restore_state(self, state):
        if not state:
            return
        for key, val in state.items():
            w = self._widgets.get(key)
            if w is None:
                continue
            try:
                if isinstance(w, QLineEdit):
                    w.setText(str(val))
                elif isinstance(w, QComboBox):
                    # Two state encodings need to be supported:
                    #  - text   (new format, robust to combo edits)
                    #  - index  (legacy format from before 2026-04-12)
                    # If neither matches a current item we leave the
                    # combo at its panel-default selection rather than
                    # forcing an out-of-range index that blanks the
                    # widget.
                    if isinstance(val, str):
                        idx = w.findText(val)
                        if idx >= 0:
                            w.setCurrentIndex(idx)
                    else:
                        ival = int(val)
                        if 0 <= ival < w.count():
                            w.setCurrentIndex(ival)
                elif isinstance(w, QDoubleSpinBox):
                    w.setValue(float(val))
                elif isinstance(w, QSpinBox):
                    w.setValue(int(val))
                elif isinstance(w, QCheckBox):
                    w.setChecked(bool(val))
            except (ValueError, TypeError):
                pass

    def is_runnable(self):
        return True

    # ====================================================================
    # argparse-driven panel generator (POLICY 2026-05-30)
    # ====================================================================
    # Most calc_*.py panels are a thin wrapper around an argparse CLI:
    # every widget is mechanically derivable from action.dest /
    # action.choices / action.type / action.help.  The pair below
    # generates widgets from a parser AND inverse-generates the CLI from
    # the same parser, so adding `parser.add_argument('--new-arg', ...)`
    # to a calc script ALSO makes the widget appear in the panel without
    # touching panel code.  Eliminates the panel-cli-diff drift surface
    # by construction.
    #
    # Each calc_*.py exposes a `build_argparser() -> ArgumentParser`
    # factory (the same parser its main() uses for parse_args).  The
    # panel's __init__ then does:
    #     self.bind_argparser(build_argparser(),
    #         file_browse={"inp": ("FastHenry .inp:", "*.inp")},
    #         choice_map={"solver_method": [("LU", 0), ("BiCGSTAB", 1)]},
    #         labels={"freq_min": "Freq min [Hz]:"})
    # and build_command becomes:
    #     return self.build_command_from_parser(
    #         vol_path=vol_path,
    #         script_path=calc_script("calc_foo.py"),
    #         vol_flag="--vol",     # or None for panels that don't use --vol
    #         output_path=json_output(...))

    def bind_argparser(self, parser, *,
                       skip=("vol", "output"),
                       file_browse=None,
                       choice_map=None,
                       labels=None):
        """Auto-generate widgets from an argparse ArgumentParser.

        Dispatch (priority order):
          file_browse[arg] given  -> add_browse (Browse button + path)
          choice_map[arg] given   -> add_combo with display↔cli-value pairs
          action.choices=[...]    -> add_combo (display = value)
          store_true/store_false  -> add_check
          type=int                -> add_spin
          everything else         -> add_line (float/str/None)

        Tooltips come from action.help.  Records the parser so
        build_command_from_parser() can do the inverse generation.

        Args:
            parser: argparse.ArgumentParser (factory from calc_*.py).
            skip: arg dest names NOT to create widgets for -- the
                AnalysisWindow handles vol / output separately.
            file_browse: {arg_dest: (label, "Filter (*.ext)")}.
            choice_map: {arg_dest: [(display_text, cli_value), ...]}
                for display-name ↔ argparse-value bridging (e.g. show
                "LU" / "BiCGSTAB" but emit --solver-method 0 / 1).
            labels: {arg_dest: "Display label:"} overrides; otherwise
                the dest is auto-cased ("freq_min" -> "Freq min:").
        """
        import argparse
        self._bound_parser = parser
        self._bound_skip = set(skip)
        self._bound_choice_map = dict(choice_map or {})
        file_browse = file_browse or {}
        labels = labels or {}

        for action in parser._actions:
            key = action.dest
            if key == "help" or key in self._bound_skip:
                continue
            label = labels.get(key) or self._auto_label_for(action)

            if key in file_browse:
                f_label, f_filter = file_browse[key]
                self.add_browse(key, f_label,
                                default=str(action.default or ""),
                                filter_str=f_filter)
            elif key in self._bound_choice_map:
                pairs = self._bound_choice_map[key]
                displays = [p[0] for p in pairs]
                default_idx = 0
                if action.default is not None:
                    for i, (_, v) in enumerate(pairs):
                        if v == action.default:
                            default_idx = i
                            break
                w = self.add_combo(key, label, displays, default=default_idx)
                w._radia_choice_pairs = pairs
            elif action.choices:
                items = [str(c) for c in action.choices]
                default_idx = 0
                if action.default is not None and action.default in action.choices:
                    default_idx = items.index(str(action.default))
                self.add_combo(key, label, items, default=default_idx)
            elif isinstance(action, (argparse._StoreTrueAction,
                                      argparse._StoreFalseAction)):
                self.add_check(key, label, default=bool(action.default))
            elif action.type is int:
                default_val = int(action.default) if action.default is not None else 0
                self.add_spin(key, label, value=default_val,
                              lo=-(1 << 31), hi=(1 << 31) - 1)
            else:
                # float / str / default
                default_str = self._format_arg_default(action.default)
                self.add_line(key, label, default_str)

            if action.help and key in self._widgets:
                self._widgets[key].setToolTip(action.help)
        return self

    def build_command_from_parser(self, *, vol_path="", script_path,
                                  vol_flag="--vol", output_path=None,
                                  extra=()):
        """Inverse of bind_argparser: read bound widgets, emit CLI argv.

        Args:
            vol_path: AnalysisWindow's vol input (routed separately, not
                from a widget).
            script_path: full path to the calc_*.py to run.
            vol_flag: flag name AnalysisWindow's vol maps to (e.g.
                "--vol"). Pass None for panels that don't use --vol
                (PCB uses --inp instead).
            output_path: appended as --output <path> when set.
            extra: additional argv tokens at the end (rare).
        """
        if not hasattr(self, "_bound_parser"):
            raise RuntimeError("bind_argparser() not called -- "
                               "nothing to emit")
        parser = self._bound_parser

        cmd = [_PYTHON, script_path]
        for action in parser._actions:
            key = action.dest
            if key == "help":
                continue
            flag = action.option_strings[0] if action.option_strings else None
            if not flag:
                continue
            if vol_flag and flag == vol_flag:
                if vol_path:
                    cmd += [vol_flag, vol_path]
                continue
            if key in self._bound_skip:
                continue
            if key not in self._widgets:
                continue
            w = self._widgets[key]

            if hasattr(w, "_radia_choice_pairs"):
                idx = w.currentIndex()
                cmd += [flag, str(w._radia_choice_pairs[idx][1])]
            elif isinstance(w, QCheckBox):
                if w.isChecked():
                    cmd += [flag]
            elif isinstance(w, QComboBox):
                cmd += [flag, w.currentText()]
            elif isinstance(w, (QSpinBox, QDoubleSpinBox)):
                cmd += [flag, str(w.value())]
            elif isinstance(w, QLineEdit):
                text = w.text().strip()
                if text:
                    cmd += [flag, text]
                elif getattr(action, "required", False):
                    raise ValueError(f"Required argument {flag} is empty")
            # else: unsupported widget type; skip silently

        if output_path:
            # Only emit --output if the parser actually declares it.
            # (calc_main auto-adds at runtime, but a factory may omit;
            # emitting --output blind would fail argparse for those.)
            if any(a.dest == "output" for a in parser._actions):
                cmd += ["--output", output_path]
        cmd += list(extra)
        return cmd

    def _auto_label_for(self, action):
        """Derive a Display Label from action.dest (override via labels=)."""
        return action.dest.replace("_", " ").capitalize() + ":"

    def _format_arg_default(self, x):
        """Compact human-friendly default for QLineEdit text.

        str(1e9) is "1000000000.0" -- ugly default for a freq field.
        Python's 'g' format gives "1e+09" which is much closer to the
        source literal "1e9" the calc author actually wrote.  None
        becomes an empty string (no pre-filled text).
        """
        if x is None:
            return ""
        if isinstance(x, float):
            return f"{x:g}"
        return str(x)

    def build_command(self, vol_path):
        raise NotImplementedError


# ============================================================
# AnalysisWindow: main window with Run/Stop/GMSH
# ============================================================

class AnalysisWindow(QMainWindow):
    """Standalone analysis window with .vol input, parameter panel, Run/Stop."""

    def __init__(self, title, vol_path="", settings_key="default"):
        super().__init__()
        self.setWindowTitle(title)
        # Initial window size MUST be tall enough that QFormLayout
        # doesn't compress visible rows to their min widget heights
        # (which crops label text -- the "line spacing too narrow,
        # unreadable until resize" bug, 2026-04-29).  At 12 pt Segoe
        # UI baseline + 14 px QFormLayout vertical spacing, ~20 rows
        # of widgets need ~750 px just for the form.  Status label
        # (7 wrapped lines) ~110 px, output area 220 px, buttons +
        # margins ~80 px -> total ~1160 px panel content.  Use 1300
        # px to leave a small bottom margin.  Drop the prior
        # "<= 1000 px" guideline -- readability beats compactness.
        self.resize(720, 1300)
        self.setMinimumSize(620, 900)
        self._settings_key = settings_key

        icon = _icon_path()
        if icon:
            self.setWindowIcon(QIcon(icon))

        self._process = None
        self._last_msh = None
        self._panel = None  # set by subclass via _set_panel()
        self._vol_path = vol_path
        # Working folder = root for all per-panel file pickers.  Defaults
        # to the directory of the .vol the launcher passed in (set by
        # Cubit's startDetached at .jou's directory) or cwd otherwise.
        # All add_browse() rows below resolve their default-open dir +
        # display relative-to-this-folder when the picked file is inside.
        self._working_folder = (
            os.path.dirname(os.path.abspath(vol_path)) if vol_path
            else os.getcwd())

        self._build_ui(vol_path)

    def _set_panel(self, panel):
        """Set the parameter panel (call from subclass __init__)."""
        self._panel = panel
        self._panel_area.addWidget(panel)
        panel.validationChanged = self._update_run_state
        # Back-pointer so panel.add_browse() can default file dialogs to
        # the AnalysisWindow's working folder and display relative paths.
        panel._analysis_window = self
        self._update_run_state()

    def _build_ui(self, vol_path):
        central = QWidget()
        self.setCentralWidget(central)
        root = QVBoxLayout(central)
        root.setContentsMargins(10, 10, 10, 5)

        # Working folder picker -- root for all per-panel file pickers.
        # Replaces the historic "Model (.vol):" top row (radia 4.35.0).
        # Per-panel sections add their own .vol / .step / .sol / .bh
        # browse rows; all default to opening inside this folder and
        # display picked paths as relative when inside.
        self._folder_row = QWidget()
        folder_layout = QHBoxLayout(self._folder_row)
        folder_layout.setContentsMargins(0, 0, 0, 0)
        folder_layout.addWidget(QLabel("Working folder:"))
        self._folder_edit = QLineEdit(self._working_folder)
        self._folder_edit.setPlaceholderText(
            "Project folder (.vol, .step, .sol, .bh files live here)")
        self._folder_edit.editingFinished.connect(
            lambda: self._on_folder_changed(self._folder_edit.text()))
        folder_layout.addWidget(self._folder_edit, 1)
        folder_btn = QPushButton("Browse...")
        folder_btn.clicked.connect(self._browse_folder)
        folder_layout.addWidget(folder_btn)
        root.addWidget(self._folder_row)

        # Backward-compat shim: the old `_vol_edit` widget was the
        # single source of truth for the workpiece .vol.  After 4.35.0
        # subclasses own their own wp_vol picker inside the panel, but
        # we keep an empty hidden QLineEdit here so settings restore
        # (_apply_settings) and any third-party probe of `_vol_edit`
        # still works without crashing.  Subclasses that need the wp
        # .vol read it from their own per-panel widget directly.
        self._vol_edit = QLineEdit("")
        self._vol_edit.hide()
        self._vol_row = QWidget()
        self._vol_row.hide()

        # Splitter: panel | output
        splitter = QSplitter(Qt.Vertical)
        root.addWidget(splitter, 1)

        # Panel area (subclass inserts panel here).  Wrapped in a
        # QScrollArea so a tall form keeps every row at its natural
        # height -- no QFormLayout compression, hence no vertical text
        # clipping when the window is short (kubota 2026-05-29) -- and
        # the mouse wheel scrolls the FORM.  Combos/spins are
        # wheel-guarded (_NoWheel* above) so the wheel reaches this
        # scroll area instead of silently changing a selection.
        self._panel_container = QWidget()
        self._panel_area = QVBoxLayout(self._panel_container)
        self._panel_area.setContentsMargins(0, 0, 0, 0)
        self._panel_scroll = QScrollArea()
        self._panel_scroll.setWidget(self._panel_container)
        self._panel_scroll.setWidgetResizable(True)
        self._panel_scroll.setFrameShape(QFrame.NoFrame)
        self._panel_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        splitter.addWidget(self._panel_scroll)

        # Output
        out_group = QGroupBox("Output")
        out_layout = QVBoxLayout(out_group)
        out_layout.setContentsMargins(5, 5, 5, 5)
        self._output = QPlainTextEdit()
        self._output.setReadOnly(True)
        self._output.setFont(QFont("Consolas", PANEL_OUTPUT_FONT_POINT_SIZE))
        # Long error tracebacks + the new "Surface heat flux" summary
        # block can run 15-20 lines; give the output box a workable
        # minimum height so the user does not have to drag the
        # splitter every time (Kubota request, 2026-04-28).
        self._output.setMinimumHeight(220)
        out_layout.addWidget(self._output)
        splitter.addWidget(out_group)
        splitter.setSizes([300, 420])

        # Buttons
        style = self.style()
        btn_row = QHBoxLayout()

        self._run_btn = QPushButton(
            style.standardIcon(QStyle.SP_MediaPlay), " Run")
        self._run_btn.setFixedHeight(32)
        self._run_btn.clicked.connect(self._on_run)
        btn_row.addWidget(self._run_btn)

        self._stop_btn = QPushButton(
            style.standardIcon(QStyle.SP_MediaStop), " Stop")
        self._stop_btn.setFixedHeight(32)
        self._stop_btn.setEnabled(False)
        self._stop_btn.clicked.connect(self._on_stop)
        btn_row.addWidget(self._stop_btn)

        self._gmsh_btn = QPushButton(
            style.standardIcon(QStyle.SP_ComputerIcon), " Open GMSH")
        self._gmsh_btn.setFixedHeight(32)
        self._gmsh_btn.setEnabled(False)
        self._gmsh_btn.clicked.connect(self._open_gmsh)
        btn_row.addWidget(self._gmsh_btn)

        # "Show command..." -- preview the exact Python CLI the panel
        # would launch, without running it.  Pops a read-only dialog
        # with a Copy-to-clipboard button so the user can re-run the
        # command in a terminal, paste it into a batch script, or send
        # it to a colleague for diagnosis.
        self._show_cmd_btn = QPushButton(
            style.standardIcon(QStyle.SP_FileDialogContentsView),
            " Show command...")
        self._show_cmd_btn.setFixedHeight(32)
        self._show_cmd_btn.setToolTip(
            "Preview the Python CLI command this panel would run "
            "(without executing it).  Useful for batch scripting, "
            "copying into a terminal, or reporting issues.")
        self._show_cmd_btn.clicked.connect(self._on_show_command)
        btn_row.addWidget(self._show_cmd_btn)

        btn_row.addStretch()
        root.addLayout(btn_row)

        # Status bar
        self._status = self.statusBar()

    @property
    def working_folder(self):
        """Absolute path to the panel's working folder.  All per-panel
        ``add_browse()`` rows resolve their default-open dir + relative
        display against this folder."""
        return os.path.abspath(self._folder_edit.text() or self._working_folder)

    def resolve_path(self, p):
        """Return absolute path for ``p``.  If ``p`` is already absolute,
        return it normalised; if relative, resolve against the working
        folder.  Empty string maps to empty string."""
        if not p:
            return ""
        if os.path.isabs(p):
            return os.path.abspath(p)
        return os.path.abspath(os.path.join(self.working_folder, p))

    def display_path(self, abs_path):
        """Return the path string the user should see in the UI: relative
        when ``abs_path`` is inside the working folder, absolute otherwise.
        Empty string maps to empty string."""
        if not abs_path:
            return ""
        ap = os.path.abspath(abs_path)
        try:
            rel = os.path.relpath(ap, self.working_folder)
        except ValueError:
            return ap          # different drive on Windows -> abs only
        if rel.startswith(".."):
            return ap          # outside the folder -> abs
        return rel.replace(os.sep, "/")

    def _browse_folder(self):
        path = QFileDialog.getExistingDirectory(
            self, "Select working folder",
            self._folder_edit.text() or os.getcwd())
        if path:
            path = os.path.abspath(path)
            self._folder_edit.setText(path)
            self._on_folder_changed(path)

    def _on_folder_changed(self, path):
        """Hook for subclasses to react to a working-folder change.
        Default: refresh the panel's per-panel browse rows so their
        displayed paths re-render relative to the new folder."""
        self._working_folder = os.path.abspath(path) if path else os.getcwd()
        if self._panel and hasattr(self._panel, "_refresh_browse_displays"):
            self._panel._refresh_browse_displays()

    def _update_run_state(self):
        if self._process is not None:
            return
        runnable = self._panel.is_runnable() if self._panel else True
        self._run_btn.setEnabled(runnable)

    def _on_run(self):
        if self._process is not None:
            return
        # build_command() may probe its panel widgets directly (4.35.0+);
        # the legacy ``vol_path`` argument now passes the panel's own
        # wp-vol widget if it exposes one, else "" (so subclasses that
        # don't use a wp .vol receive an empty string).
        vol = ""
        if self._panel is not None and hasattr(self._panel, "wp_vol_path"):
            vol = self._panel.wp_vol_path()
        try:
            cmd = self._panel.build_command(vol)
        except ValueError as e:
            panel_log(f"_on_run: build_command FAILED: {e}")
            QMessageBox.warning(self, "Input Error", str(e))
            return

        panel_log(f"_on_run: working_folder={self.working_folder} vol={vol}")
        panel_log(f"  cmd: {' '.join(cmd)}")

        # Result Output Persistence Policy (2026-05-30): capture the
        # --output JSON path so _persist_output_log can mirror the
        # Output window to <base>_<suffix>.log next to it.
        self._last_output_json = None
        for i, tok in enumerate(cmd):
            if tok == "--output" and i + 1 < len(cmd):
                self._last_output_json = cmd[i + 1]
                break

        self._save_settings()
        self._output.clear()
        # Echo the exact command being launched so the user sees what
        # arguments the panel passed to python.  Both forms are useful:
        # the multi-line form is readable in the box; the single-line
        # form is one copy-paste away in the log line.  The "Show
        # command..." button reproduces this without running.
        single, multi = self._format_cmd(cmd)
        self._output.appendPlainText("=== Launching ===")
        self._output.appendPlainText(f"Radia version: {radia_version()}")
        self._output.appendPlainText(f"working dir: {self.working_folder}")
        self._output.appendPlainText(multi)
        self._output.appendPlainText(
            "(single line, copy-paste friendly:)")
        self._output.appendPlainText(f"  {single}")
        self._output.appendPlainText("=================\n")
        self._last_msh = None
        self._gmsh_btn.setEnabled(False)

        # Working dir = folder picker (4.35.0+); falls back to wp .vol
        # parent dir if folder is unset, then cwd.
        work_dir = self.working_folder
        if not os.path.isdir(work_dir):
            work_dir = os.path.dirname(vol) if vol else os.getcwd()
        if not os.path.isdir(work_dir):
            work_dir = os.getcwd()

        # Cleanup stale GMSH artifacts left by previous Runs from the
        # working directory. Without this the user can accidentally
        # open an old `inductance.geo` (full B-field box from a
        # previous Air=on run) when the current Run is Air=off.
        # We delete files the panel itself produces; the user's own
        # .msh / .geo files (anything not in the known list) are left
        # alone.
        for stale in ("inductance.geo", "inductance_B.msh",
                      "inductance_J.msh", "J_coeffs.npy",
                      "surface_mesh.vol",
                      os.path.basename(msh_output(vol, "_bem"))
                      if vol else ""):
            if not stale:
                continue
            p = os.path.join(work_dir, stale)
            if os.path.isfile(p):
                try:
                    os.remove(p)
                    panel_log(f"  cleaned stale: {stale}")
                except OSError:
                    pass

        self._process = QProcess(self)
        self._process.setWorkingDirectory(work_dir)
        self._process.readyReadStandardOutput.connect(self._read_stdout)
        self._process.readyReadStandardError.connect(self._read_stderr)
        self._process.finished.connect(self._on_finished)
        self._process.start(_PYTHON, cmd[1:])

        self._run_btn.setEnabled(False)
        self._stop_btn.setEnabled(True)
        self._status.showMessage("Running...")

    def _on_stop(self):
        if self._process:
            self._process.kill()
            self._process.waitForFinished(3000)

    @staticmethod
    def _format_cmd(cmd):
        """Render an argv list as (single_line, multi_line) strings.

        Single-line form: tokens joined by spaces, with any token
        containing whitespace double-quoted.  Copy-pastable into a
        terminal as-is.

        Multi-line form: one ``--flag value`` per indented line, joined
        with shell line-continuation (``^`` on Windows cmd/PowerShell,
        ``\\`` on POSIX).  Easier to read in the output box; copy-
        pastable into a batch script.
        """
        def _quote(tok):
            return f'"{tok}"' if (" " in tok or "\t" in tok) else tok
        single = " ".join(_quote(t) for t in cmd)
        lines = [_quote(cmd[0])]
        i = 1
        while i < len(cmd):
            tok = cmd[i]
            if tok.startswith("--") and i + 1 < len(cmd) \
                    and not cmd[i + 1].startswith("--"):
                lines.append(f"    {tok} {_quote(cmd[i + 1])}")
                i += 2
            else:
                lines.append(f"    {_quote(tok)}")
                i += 1
        cont = " ^" if sys.platform == "win32" else " \\"
        multi = (cont + "\n").join(lines)
        return single, multi

    def _on_show_command(self):
        """Display the Python CLI command this panel would launch.

        Builds the command via the panel's ``build_command(vol_path)``
        hook (the same one used by ``_on_run``), then pops a non-modal
        dialog with a read-only text box and a Copy-to-clipboard button.
        Does NOT execute the command.

        If ``build_command`` raises ``ValueError`` (missing input file,
        empty required field, etc.) the user sees the validation error
        message instead of a stub.  This mirrors ``_on_run``'s error path
        so the two buttons agree about runnability.
        """
        vol = ""
        if self._panel is not None and hasattr(self._panel, "wp_vol_path"):
            vol = self._panel.wp_vol_path()
        try:
            cmd = self._panel.build_command(vol)
        except ValueError as e:
            QMessageBox.warning(self, "Input Error", str(e))
            return

        line, multi = self._format_cmd(cmd)
        dlg = QMainWindow(self)
        dlg.setWindowTitle("Python command")
        dlg.resize(900, 360)
        central = QWidget()
        dlg.setCentralWidget(central)
        v = QVBoxLayout(central)
        v.addWidget(QLabel(
            "This is the exact CLI the Run button would launch.  "
            "Copy + paste into a terminal or batch script:"))
        text = QPlainTextEdit()
        text.setReadOnly(True)
        text.setFont(QFont("Consolas", PANEL_OUTPUT_FONT_POINT_SIZE))
        text.setPlainText(multi)
        v.addWidget(text, 1)

        row = QHBoxLayout()
        copy_line_btn = QPushButton("Copy single-line")
        copy_line_btn.setToolTip(
            "Copy as one line (handy for inline paste).")
        copy_line_btn.clicked.connect(
            lambda: (QApplication.clipboard().setText(line),
                     dlg.statusBar().showMessage(
                         "Single-line command copied to clipboard.", 4000)))
        row.addWidget(copy_line_btn)
        copy_multi_btn = QPushButton("Copy multi-line")
        copy_multi_btn.setToolTip(
            "Copy with one --flag per line (handy for scripts).")
        copy_multi_btn.clicked.connect(
            lambda: (QApplication.clipboard().setText(multi),
                     dlg.statusBar().showMessage(
                         "Multi-line command copied to clipboard.", 4000)))
        row.addWidget(copy_multi_btn)
        row.addStretch()
        close_btn = QPushButton("Close")
        close_btn.clicked.connect(dlg.close)
        row.addWidget(close_btn)
        v.addLayout(row)
        dlg.statusBar().showMessage(
            f"Working directory: {self.working_folder}")
        dlg.show()
        # Keep a reference so Qt doesn't garbage-collect the dialog as
        # soon as this method returns.
        self._show_cmd_dlg = dlg

    def _read_stdout(self):
        data = self._process.readAllStandardOutput().data()
        text = data.decode("utf-8", errors="replace").rstrip("\n")
        if text:
            self._output.appendPlainText(text)

    def _read_stderr(self):
        data = self._process.readAllStandardError().data()
        text = data.decode("utf-8", errors="replace").rstrip("\n")
        if text:
            self._output.appendPlainText(text)

    def _append_standard_summary(self, result):
        """Surface element count / DoF / detailed compute time / power /
        temperature for EVERY result, regardless of which calc_*.py
        produced it.

        calc_*.py emit these under several spellings (ndof vs wp_ndof,
        t_solve_s vs t_bem_solve_s, P_wp_W vs P_total_W, ...).  The older
        per-solver render cascade checked a single fixed spelling and
        silently showed nothing for the BEM-A path -- the data was in the
        JSON but never displayed (kubota 2026-05-29: "OUTPUT/JSON must
        record element count, DoF, compute-time detail; IH: heat + temp").
        This block uses the real keys so OUTPUT always shows ne / DoF /
        time, plus heat + temperature for the IH paths.
        """
        o = self._output.appendPlainText
        rv = result.get("radia_version")
        if rv:
            o(f"  Radia version = {rv}")
        ne = (result.get("ne") or result.get("n_elements")
              or result.get("wp_mesh_n_tris"))
        if ne is not None:
            nv = result.get("wp_mesh_nv") or result.get("nv")
            o(f"  Elements = {ne}" + (f", nodes = {nv}" if nv else ""))
        dof = (result.get("ndof") or result.get("wp_ndof")
               or result.get("n_dofs"))
        if dof:
            o(f"  DoF = {dof}")
        for k in ("P_wp_W", "P_total_W", "P_total", "P_wp", "wp_P_total"):
            v = result.get(k)
            if isinstance(v, (int, float)):
                o(f"  Heat (P) = {v:.4e} W   [{k}]")
                break
        # Temperature integral quantities (thermal analysis):
        # volume-averaged mean, plus max / min (kubota 2026-05-29).
        t_mean = result.get("T_mean_C")
        t_max = result.get("T_max_C", result.get("T_max"))
        t_min = result.get("T_min_C", result.get("T_min"))
        _tp = []
        if isinstance(t_mean, (int, float)):
            _tp.append(f"mean {t_mean:.1f}")
        if isinstance(t_max, (int, float)):
            _tp.append(f"max {t_max:.1f}")
        if isinstance(t_min, (int, float)):
            _tp.append(f"min {t_min:.1f}")
        if _tp:
            o("  Temperature [C] = " + ", ".join(_tp))
        times = {k: v for k, v in result.items()
                 if k.startswith("t_") and isinstance(v, (int, float))}
        if times:
            o("  Compute time (s):")
            for k in sorted(times):
                o(f"    {k:<24}{times[k]:9.2f}")
            o(f"    {'(sum)':<24}{sum(times.values()):9.2f}")

    def _persist_output_log(self):
        """Mirror the Output window verbatim to <base>_<suffix>.log next
        to the --output JSON. Result Output Persistence Policy
        (2026-05-30): every Run leaves a `.log` beside the `.json`,
        overwritten each Run, regardless of exit code."""
        if not getattr(self, "_last_output_json", None):
            return
        log_path = os.path.splitext(self._last_output_json)[0] + ".log"
        try:
            with open(log_path, "w", encoding="utf-8",
                      errors="replace", newline="") as f:
                f.write(self._output.toPlainText())
            panel_log(f"persisted output log: {log_path}")
        except OSError as e:
            panel_log(f"failed to write output log {log_path}: {e}")

    def _on_finished(self, exit_code, exit_status):
        remaining = self._process.readAllStandardOutput().data()
        if remaining:
            self._output.appendPlainText(
                remaining.decode("utf-8", errors="replace").rstrip("\n"))

        stdout_text = self._output.toPlainText()
        self._process = None
        self._stop_btn.setEnabled(False)
        self._update_run_state()

        panel_log(f"_on_finished: exit_code={exit_code}")

        if exit_code != 0:
            self._status.showMessage(f"Error (exit code {exit_code})")
            self._output.appendPlainText(
                f"\n*** Process exited with code {exit_code}")
            # Log the last ~20 lines so the failure is visible in the
            # panel debug log without the user needing to copy/paste.
            tail = "\n".join(stdout_text.splitlines()[-20:])
            panel_log(f"_on_finished: subprocess FAILED, tail:\n{tail}")
            self._persist_output_log()
            return

        # Find .msh in output for GMSH button
        result = None
        for line in reversed(stdout_text.split("\n")):
            line = line.strip()
            if line.startswith("{"):
                try:
                    result = json.loads(line)
                except json.JSONDecodeError:
                    pass
                break
        # Find the GMSH output file from the result JSON.
        # Check keys in priority order: gmsh_file > msh_output > msh_file
        gmsh_target = None
        gmsh_reason = ""
        if result:
            for key in ("gmsh_file", "field_gmsh_file",
                        "msh_output", "msh_file"):
                msh = result.get(key)
                if msh and os.path.isfile(msh):
                    gmsh_target = msh
                    gmsh_reason = key
                    break
            if not gmsh_target:
                gmsh_reason = "no GMSH output file in result"
        if gmsh_target:
            self._last_msh = gmsh_target
            self._gmsh_btn.setEnabled(True)
        panel_log(f"_on_finished: gmsh button = "
                  f"{'ENABLED' if gmsh_target else 'disabled'} "
                  f"({gmsh_reason})")
        if gmsh_target:
            panel_log(f"  -> {gmsh_target}")

        # Log result keys + headline numbers to panel debug log
        if result is not None:
            panel_log(f"_on_finished: result keys = "
                      f"{sorted(result.keys())[:20]}")
            if "error" in result:
                panel_log(f"  ERROR: {result['error']}")
            if "inductance_H" in result:
                panel_log(
                    f"  L = {result['inductance_H']*1e9:.3f} nH")
            if "coupled_dL_H" in result:
                panel_log(
                    f"  delta_L = {result['coupled_dL_H']*1e9:+.3f} nH")
            if "P_total_W" in result:
                panel_log(f"  P_total = {result['P_total_W']:.4e} W")
            if "wp_P_total" in result:
                panel_log(f"  wp_P_total = {result['wp_P_total']:.4e} W")

        # Display result summary in output window
        if result and "error" not in result:
            self._output.appendPlainText("\n--- Result ---")
            self._append_standard_summary(result)
            if "inductance_H" in result:
                L_nH = result["inductance_H"] * 1e9
                self._output.appendPlainText(f"  L = {L_nH:.2f} nH")
            if "n_dofs" in result:
                self._output.appendPlainText(f"  DOFs = {result['n_dofs']}")
            if "t_solve" in result:
                self._output.appendPlainText(
                    f"  Time: {result['t_solve']:.1f}s total")
            if "t_assembly" in result:
                self._output.appendPlainText(
                    f"    Assembly: {result['t_assembly']:.1f}s")
            if "t_lu" in result:
                self._output.appendPlainText(
                    f"    LU solve: {result['t_lu']:.1f}s")
            # BEM-SIBC workpiece results (calc_heating_bem)
            if "P_total_W" in result:
                self._output.appendPlainText(
                    "  --- Coil ---")
                self._output.appendPlainText(
                    f"  Coil radius:  "
                    f"{result.get('coil_radius_m', 0)*1e3:.1f} mm")
                self._output.appendPlainText(
                    f"  Coil current: "
                    f"{result.get('coil_current_A', 0):.2f} A")
                self._output.appendPlainText(
                    f"  Coil sigma:   "
                    f"{result.get('coil_sigma_Sm', 0):.4e} S/m")
                self._output.appendPlainText(
                    "  --- Workpiece ---")
                self._output.appendPlainText(
                    f"  Material:  {result.get('material', '?')}")
                self._output.appendPlainText(
                    f"  WP sigma:  "
                    f"{result.get('wp_sigma_Sm', 0):.4e} S/m")
                self._output.appendPlainText(
                    f"  WP mu_r:   "
                    f"{result.get('wp_mu_r', 0):.1f}")
                self._output.appendPlainText(
                    "  --- SIBC ---")
                self._output.appendPlainText(
                    f"  Frequency:  "
                    f"{result.get('frequency_Hz', 0):.0f} Hz")
                self._output.appendPlainText(
                    f"  Skin depth: "
                    f"{result.get('skin_depth_mm', 0):.3f} mm")
                self._output.appendPlainText(
                    f"  |Z_s| = {result.get('Z_s_abs_Ohm', 0):.4e} Ohm"
                    f"  (phase = {result.get('Z_s_phase_deg', 0):.1f} deg)")
                self._output.appendPlainText(
                    f"  Re(Z_s) = {result.get('Z_s_real_Ohm', 0):.4e}, "
                    f"Im(Z_s) = {result.get('Z_s_imag_Ohm', 0):.4e}")
                self._output.appendPlainText(
                    "  --- Results ---")
                self._output.appendPlainText(
                    f"  P_total = {result['P_total_W']:.4e} W")
                if "Q_total_var" in result:
                    self._output.appendPlainText(
                        f"  Q_total = {result['Q_total_var']:.4e} var")
                self._output.appendPlainText(
                    f"  H_t_rms = {result.get('H_t_rms_Am', 0):.4f} A/m")
                self._output.appendPlainText(
                    "  --- Solver ---")
                self._output.appendPlainText(
                    f"  Karl iterations = {result.get('n_iter', '?')}")
                self._output.appendPlainText(
                    f"  BEM DOFs = {result.get('ndof', '?')}, "
                    f"elements = {result.get('n_elements', '?')}")
            # FEM-SIBC results (calc_fem_kelvin)
            if "P_total" in result and "P_total_W" not in result:
                self._output.appendPlainText(
                    "  --- FEM-SIBC ---")
                self._output.appendPlainText(
                    f"  P_total = {result['P_total']:.4e} W")
                if "Q_total" in result:
                    self._output.appendPlainText(
                        f"  Q_total = {result['Q_total']:.4e} var")
                if "H_t_rms" in result:
                    self._output.appendPlainText(
                        f"  H_t_rms = {result['H_t_rms']:.4f} A/m")
                if "L" in result:
                    self._output.appendPlainText(
                        f"  L = {result['L']*1e9:.2f} nH")
                if "Z_s" in result:
                    self._output.appendPlainText(
                        f"  Z_s = {result['Z_s']}")
                if "delta" in result:
                    self._output.appendPlainText(
                        f"  Skin depth = {result['delta']*1e3:.3f} mm")
                if "ndof" in result:
                    self._output.appendPlainText(
                        f"  DOFs = {result['ndof']}, "
                        f"Elements = {result.get('ne', '?')}")
                if "iterations" in result:
                    self._output.appendPlainText(
                        f"  Karl iterations = {result['iterations']}")
                if "t_total" in result:
                    self._output.appendPlainText(
                        f"  Time = {result['t_total']:.1f}s")
            # Surface heat-flux statistics.  Emitted by calc_fem_kelvin
            # and calc_inductance (the two SIBC production paths) — same
            # schema for both, so this block does not need to know
            # which solver produced the result.  Useful as an
            # optimization filter ("does enough heat land where we
            # want it?") before paying for a full thermal solve.
            qmax = result.get("q_surf_max")
            qmean = result.get("q_surf_mean")
            qp95 = result.get("q_surf_p95")
            pcheck = result.get("P_total_check")
            if qmax is not None and qmean is not None:
                self._output.appendPlainText("  --- Surface heat flux ---")
                self._output.appendPlainText(
                    f"  q_surf_max  = {qmax:.3e} W/m^2  (hotspot)")
                self._output.appendPlainText(
                    f"  q_surf_p95  = {qp95:.3e} W/m^2"
                    if qp95 is not None else "  q_surf_p95  = n/a")
                self._output.appendPlainText(
                    f"  q_surf_mean = {qmean:.3e} W/m^2")
                if qmean > 0:
                    self._output.appendPlainText(
                        f"  hotspot/mean = {qmax/qmean:.2f}  "
                        f"(IH typical 2-10)")
                if pcheck is not None:
                    # Cross-check the surface integral against the
                    # scalar P (the JSON key name differs by solver).
                    p_main = result.get("P_total")
                    if p_main is None:
                        p_main = result.get("P_wp_W")
                    if p_main and abs(p_main) > 0:
                        rel = (pcheck - p_main) / p_main * 100.0
                        self._output.appendPlainText(
                            f"  integral check: P_int={pcheck:.4e} W "
                            f"({rel:+.2f}% vs P_main)")

            # BEM coil + workpiece SIBC/ESIM (calc_inductance.py with
            # --workpiece). Distinct from BEM-SIBC (WP) which uses
            # P_total_W; this path uses wp_P_total + wp_R_effective.
            if "wp_P_total" in result:
                self._output.appendPlainText(
                    "  --- Workpiece SIBC ---")
                self._output.appendPlainText(
                    f"  Model:    {result.get('wp_model', '?')}")
                self._output.appendPlainText(
                    f"  Material: {result.get('wp_material', '?')}")
                self._output.appendPlainText(
                    f"  Frequency: {result.get('wp_frequency', 0):.0f} Hz")
                self._output.appendPlainText(
                    f"  WP sigma:  {result.get('wp_sigma', 0):.4e} S/m")
                if "wp_delta_min" in result:
                    self._output.appendPlainText(
                        f"  Skin depth: "
                        f"{result['wp_delta_min']*1e3:.4f} mm")
                self._output.appendPlainText(
                    f"  Panels: {result.get('wp_n_panels', '?')}")
                if "wp_H_t_max" in result:
                    self._output.appendPlainText(
                        f"  H_t range: {result['wp_H_t_min']:.2f} - "
                        f"{result['wp_H_t_max']:.2f} A/m")
                self._output.appendPlainText(
                    f"  P_total = {result['wp_P_total']:.4e} W")
                if "wp_Q_total" in result:
                    self._output.appendPlainText(
                        f"  Q_total = {result['wp_Q_total']:.4e} var")
                if "wp_R_effective" in result:
                    self._output.appendPlainText(
                        f"  R_eff   = "
                        f"{result['wp_R_effective']:.4e} Ohm")
                if "wp_X_effective" in result:
                    self._output.appendPlainText(
                        f"  X_eff   = "
                        f"{result['wp_X_effective']:.4e} Ohm")
                # Coupled coil-terminal results.
                # Two cases:
                #   1. Linear SIBC (Dowell): full coupled BEM solve via
                #      bem_coupled_solver.CoupledBEMSolver. Reports
                #      L_air, L_total, Delta_L (sign is physically
                #      correct: <0 for non-magnetic Lenz screening,
                #      >0 for ferromagnetic flux concentration).
                #   2. Nonlinear SIBC (ESIM): uncoupled estimator,
                #      reports R only (no Delta L).
                if "coupled_L_total_H" in result:
                    L_air_nH = result.get(
                        "L_air_H", result.get("coupled_L_air_H", 0)) * 1e9
                    L_total_nH = result["coupled_L_total_H"] * 1e9
                    dL_nH = result["coupled_dL_H"] * 1e9
                    self._output.appendPlainText(
                        "  --- Coil terminal (with workpiece) ---")
                    self._output.appendPlainText(
                        f"  L (air)   = {L_air_nH:.3f} nH")
                    self._output.appendPlainText(
                        f"  delta L  = {dL_nH:+.3f} nH")
                    self._output.appendPlainText(
                        f"  L (eff)   = {L_total_nH:.3f} nH")
                    if "coupled_R_effective_Ohm" in result:
                        self._output.appendPlainText(
                            f"  R (added) = "
                            f"{result['coupled_R_effective_Ohm']*1e3:.4f}"
                            f" mOhm")
                    if "coupled_iterations" in result:
                        self._output.appendPlainText(
                            f"  iters     = "
                            f"{result['coupled_iterations']} "
                            f"(Picard, relax=0.5)")
                    if "coupled_delta_skin_m" in result:
                        self._output.appendPlainText(
                            f"  skin depth = "
                            f"{result['coupled_delta_skin_m']*1e3:.4f} mm")
                    # Per-panel curvature SIBC (Phase 5, 2026-04-12):
                    # Surface the local-R range and panel count so the
                    # user can sanity-check that the mesh-driven extractor
                    # picked up the workpiece geometry correctly.
                    if result.get("coupled_use_local_curvature"):
                        rmin = result.get("coupled_R_local_min_m", 0) * 1e3
                        rmax = result.get("coupled_R_local_max_m", 0) * 1e3
                        npan = result.get("coupled_n_wp_panels", 0)
                        self._output.appendPlainText(
                            f"  R_local   = [{rmin:.3f}, {rmax:.3f}] mm "
                            f"(per-panel, {npan} panels)")
                    elif "coupled_use_local_curvature" in result:
                        self._output.appendPlainText(
                            "  R_local   = global half-thickness "
                            "(per-panel curvature: off)")
                    self._output.appendPlainText(
                        "  (Coupled BEM: per-DOF f_back, validated"
                        " 2026-04-12 vs FEM-Kelvin SIBC at 0.3% on"
                        " copper / 1.7% on steel mu_r=100. See"
                        " examples/cubit_panels/inductance/"
                        "compare_bem_coupled_vs_fem_kelvin.py)")
                elif "coupled_R_effective_Ohm" in result:
                    self._output.appendPlainText(
                        "  --- Coil terminal (with workpiece, ESIM) ---")
                    self._output.appendPlainText(
                        f"  L (air-only) = "
                        f"{result.get('inductance_H', 0)*1e9:.3f} nH")
                    self._output.appendPlainText(
                        f"  R (added)   = "
                        f"{result['coupled_R_effective_Ohm']*1e3:.4f}"
                        f" mOhm")
                    self._output.appendPlainText(
                        "  (delta L not reported: ESIM is one-way only;"
                        " coupled BEM only supports linear Dowell SIBC.)")
                if "coupled_error" in result:
                    self._output.appendPlainText(
                        "  --- Coupled BEM ERROR ---")
                    self._output.appendPlainText(
                        f"  {result['coupled_error']}")
            elif "wp_error" in result:
                self._output.appendPlainText(
                    "  --- Workpiece SIBC ---")
                self._output.appendPlainText(
                    f"  ERROR: {result['wp_error']}")

            # Volume/area results (calc_volume, calc_surface)
            if "ng_volume" in result:
                self._output.appendPlainText(
                    f"  Volume = {result['ng_volume']:.6e}")
            if "vol_error_pct" in result:
                self._output.appendPlainText(
                    f"  Volume error = {result['vol_error_pct']:+.4e}%")
            if "ng_area" in result:
                self._output.appendPlainText(
                    f"  Area = {result['ng_area']:.6e}")
            self._output.appendPlainText("")

        self._status.showMessage("Done." if exit_code == 0 else "Failed.")
        self._persist_output_log()

    def _open_gmsh(self):
        if not self._last_msh:
            return
        import subprocess
        msh_path = self._last_msh
        # Ensure we open the .msh, not a .geo (legacy compat)
        if msh_path.endswith('.geo'):
            msh_candidate = msh_path.rsplit('.', 1)[0] + '.msh'
            if os.path.exists(msh_candidate):
                msh_path = msh_candidate
        # Delegate to panels/open_gmsh.py.  Two reasons:
        #   1. The launcher runs detached with CREATE_NO_WINDOW, so any
        #      gmsh failure (missing package, bad path, fltk crash) used
        #      to vanish silently.  open_gmsh.py wraps the gmsh calls in
        #      try/except and writes the traceback to the panel debug
        #      log so the user can see what happened.
        #   2. Passing a UNC msh path inside a ``python -c "..."`` literal
        #      is fragile (slash/quoting/escape issues on Windows shares).
        #      Argv passes the path as a real argument, no quoting.
        #
        # cwd: do NOT pass a UNC cwd to subprocess.Popen.  On 100号機
        # (multi-user Windows + W: SMB share) the .msh resolves to
        # ``//192.168.11.100/...`` and ``os.path.abspath`` normalises it
        # to ``\\192.168.11.100\...``, which CMD.EXE / CreateProcessW
        # do not reliably accept as a working directory.  GMSH was
        # silently failing to launch (Kubota, 2026-04-27).  GMSH does
        # not need cwd to find the ``.msh.opt`` companion -- it derives
        # that from the .msh path itself.
        launcher_script = os.path.join(_PANELS_DIR, "open_gmsh.py")
        cmd = [_PYTHON, launcher_script, msh_path]
        panel_log(f"_open_gmsh: launching {launcher_script}")
        panel_log(f"  file: {msh_path}")
        # Pass cwd only if it is on a local drive.  UNC cwd is the
        # silent-failure trigger described above.
        cwd = None
        msh_dir = os.path.dirname(os.path.abspath(msh_path))
        if not msh_dir.startswith("\\\\"):
            cwd = msh_dir
        subprocess.Popen(
            cmd,
            cwd=cwd,
            creationflags=(0x08000000 if sys.platform == "win32" else 0))

    # Settings
    def _settings_path(self):
        return os.path.join(_SETTINGS_DIR, f"radia_{self._settings_key}.json")

    def _save_settings(self):
        os.makedirs(_SETTINGS_DIR, exist_ok=True)
        data = {
            "working_folder": self._folder_edit.text(),
            # ``vol`` kept for backward-compat with older settings JSONs
            # written by radia <= 4.34.0; safe to drop in a future
            # cleanup once all panels have been opened at least once on
            # 4.35.0+ to migrate the wp .vol into panel state.
            "vol": self._vol_edit.text(),
            "panel": self._panel.save_state() if self._panel else {},
        }
        try:
            with open(self._settings_path(), "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
        except OSError:
            pass

    def _restore_settings(self):
        p = self._settings_path()
        if not os.path.isfile(p):
            return
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            return
        # Restore working folder first (the panel's restore_state may
        # display relative paths against it).
        wf = data.get("working_folder")
        if wf and not self._folder_edit.text():
            self._folder_edit.setText(wf)
            self._working_folder = os.path.abspath(wf)
        if not self._vol_edit.text() and "vol" in data:
            self._vol_edit.setText(data["vol"])
        if self._panel:
            self._panel.restore_state(data.get("panel", {}))

    def closeEvent(self, event):
        try:
            self._save_settings()
        except Exception:
            pass
        if self._process:
            try:
                self._process.kill()
                self._process.waitForFinished(3000)
            except Exception:
                pass
        super().closeEvent(event)


def apply_panel_base_font(app):
    """Apply the lab-standard panel point size to a QApplication.

    Inherits the family from the OS default (Segoe UI on Windows,
    system sans-serif on Linux/macOS) so the panels look native on
    each platform; only the point size is bumped to PANEL_BASE_FONT_POINT_SIZE.
    """
    f = app.font()
    f.setPointSize(PANEL_BASE_FONT_POINT_SIZE)
    app.setFont(f)


def run_app(window_class, vol_path=""):
    """Entry point helper: create QApplication + window, exec."""
    app = QApplication(sys.argv)
    apply_panel_base_font(app)
    vol = vol_path or (sys.argv[1] if len(sys.argv) > 1 else "")
    window = window_class(vol)
    window.show()
    sys.exit(app.exec())
