function runner = makeStreamFunctionAdjointDemoRunner()
%MAKESTREAMFUNCTIONADJOINTDEMORUNNER Create the library's runnable example.
runner = radia.topopt.makeStreamFunctionAdjointRunner( ...
    eye(2),[0.2;0.8], ...
    CurrentOperator=[1,1],CurrentLimit=0.9, ...
    InitialDesign=[0.7;0.7],LowerBounds=zeros(2,1), ...
    UpperBounds=ones(2,1),MoveLimit=0.2,MaxIterations=40);
end
