function runner = makeAdjointDemoRunner(options)
%MAKEADJOINTDEMORUNNER Create the runnable Simulink library default.
arguments
    options.Solver (1,1) string ...
        {mustBeMember(options.Solver,["mma","sqp"])} = "mma"
end
optimizerOptions = struct( ...
    "LowerBounds",zeros(2,1), ...
    "UpperBounds",ones(2,1), ...
    "MaxIterations",40, ...
    "MoveLimit",0.2*ones(2,1), ...
    "OptimalityTolerance",1e-7, ...
    "ConstraintTolerance",1e-7, ...
    "StepTolerance",1e-8);
runner = radia.topopt.AdjointRunner([0.7;0.7],@evaluateDemo, ...
    Solver=options.Solver,OptimizerOptions=optimizerOptions);
end

function evaluation = evaluateDemo(design)
evaluation = struct( ...
    "objective",(design(1)-0.2)^2 + (design(2)-0.8)^2, ...
    "gradient",[2*(design(1)-0.2);2*(design(2)-0.8)], ...
    "constraints",sum(design)-0.9, ...
    "constraint_jacobian",[1;1]);
end
