function runner = makeElectromagnetReferenceRunner(options)
%MAKEELECTROMAGNETREFERENCERUNNER Create a runnable preassembled VIM study.
%   This small operator is the deterministic Simulink/release smoke. Real
%   models pass their assembled air matrix and per-cell material operators
%   to makeElectromagnetAdjointRunner.
arguments
    options.Solver (1,1) string ...
        {mustBeMember(options.Solver,["mma","sqp"])} = "mma"
end

baseMatrix = [ ...
    5.0,-0.25,0,0; ...
    -0.25,5.2,-0.20,0; ...
    0,-0.20,4.8,-0.15; ...
    0,0,-0.15,5.1];
source = [1.0;0.9;0.7;0.4];
responseMatrix = eye(4);
cellMatrix = zeros(4,4,4);
cellStrength = [-2.4,-2.2,-2.5,-2.0];
for index = 1:4
    cellMatrix(index,index,index) = cellStrength(index);
end
targetDensity = [0.9;0.7;0.3;0.1];
targetMatrix = baseMatrix;
for index = 1:4
    targetMatrix = targetMatrix + targetDensity(index) * ...
        reshape(cellMatrix(index,:,:),4,4);
end
target = responseMatrix*(targetMatrix\source);

runner = radia.topopt.makeElectromagnetAdjointRunner( ...
    baseMatrix,source,responseMatrix,cellMatrix,target, ...
    ElementVolumes=ones(4,1),VolumeFraction=0.5, ...
    InitialDesign=0.5*ones(4,1),PenalizationPower=1, ...
    DensityRegularization=1e-8,MoveLimit=0.2,MaxIterations=80, ...
    Solver=options.Solver,OptimizerOptions=struct( ...
        "StepTolerance",5e-4,"OptimalityTolerance",2e-5, ...
        "ConstraintTolerance",1e-8));
runner.Metadata.reference_density = targetDensity;
runner.Metadata.source = "preassembled-electromagnet-reference-operator";
end
