function result = optimizeHCurlActivationAdjoint(initialActivation, operator, ...
        cellCurlGrams, frequenciesHz, rhs, conductivity, cellVolumes, ...
        volumeFraction, options)
%OPTIMIZEHCURLACTIVATIONADJOINT Native Eddy-Bubble adjoint with MMA or SQP.
arguments
    initialActivation (:,1) double ...
        {mustBeReal,mustBeFinite,mustBeBetween(initialActivation,0,1)}
    operator (1,1) radia.topopt.HCurlTopologyOperator
    cellCurlGrams double {mustBeFinite}
    frequenciesHz (:,1) double {mustBePositive,mustBeFinite}
    rhs double
    conductivity (1,1) struct
    cellVolumes (:,1) double {mustBePositive,mustBeFinite}
    volumeFraction (1,1) double ...
        {mustBePositive,mustBeLessThanOrEqual(volumeFraction,1)}
    options.Solver (1,1) string ...
        {mustBeMember(options.Solver,["mma","sqp"])}="mma"
    options.Weights (:,1) double ...
        {mustBeNonnegative,mustBeFinite}=ones(numel(frequenciesHz),1)
    options.RHSJacobian double=double.empty
    options.InductancePower (1,1) double ...
        {mustBeGreaterThanOrEqual(options.InductancePower,1)}=1
    options.OptimizerOptions (1,1) struct=struct
end
if numel(initialActivation) ~= numel(cellVolumes)
    error("radia:topopt:Shape", ...
        "initialActivation and cellVolumes must have equal length.");
end
volumeMax = volumeFraction * sum(cellVolumes);
evaluate = @(activation)localEvaluate(activation, operator, cellCurlGrams, ...
    frequenciesHz, rhs, conductivity, cellVolumes, volumeMax, options);
optimizerOptions = options.OptimizerOptions;
reserved = ["Solver","LowerBounds","UpperBounds"];
if any(isfield(optimizerOptions, reserved))
    error("radia:topopt:HCurlOptimizerOptions", ...
        "OptimizerOptions must not override Solver or activation bounds.");
end
optimizerOptions.Solver = options.Solver;
optimizerOptions.LowerBounds = zeros(size(initialActivation));
optimizerOptions.UpperBounds = ones(size(initialActivation));
args = namedargs2cell(optimizerOptions);
optimization = radia.topopt.optimizeAdjoint( ...
    initialActivation, evaluate, args{:});
result = optimization;
result.schema = "radia.hcurl.topopt.activation-adjoint/v1";
result.optimizer_schema = optimization.schema;
result.volume = cellVolumes.' * result.design;
result.volume_max = volumeMax;
result.volume_fraction = volumeFraction;
result.linearization = result.evaluation.payload.linearization;
end

function evaluation = localEvaluate(activation, operator, cellCurlGrams, ...
        frequenciesHz, rhs, conductivity, cellVolumes, volumeMax, options)
linearization = radia.topopt.linearizeHCurlActivationMultifrequencyJoule( ...
    operator, cellCurlGrams, activation, frequenciesHz, rhs, conductivity, ...
    Weights=options.Weights, RHSJacobian=options.RHSJacobian, ...
    InductancePower=options.InductancePower);
evaluation = struct( ...
    "objective", linearization.objective, ...
    "gradient", linearization.gradient(:), ...
    "constraints", cellVolumes.' * activation / volumeMax - 1, ...
    "constraint_jacobian", cellVolumes / volumeMax, ...
    "linearization", linearization);
end
