"""One-shot generator: introspect gmsh, write `gmsh_api.py`.

gmsh exposes a flat Python API: top-level functions + 9 sub-modules
(`gmsh.model`, `gmsh.view`, `gmsh.option`, `gmsh.plugin`,
`gmsh.graphics`, `gmsh.logger`, `gmsh.onelab`, `gmsh.fltk`,
`gmsh.parser`). We walk each, extract signatures + first-line
docstrings, and emit a markdown-shaped `.py` that the MCP server
loads as the bundled `api_reference` topic.

Run manually when bumping gmsh:
    python -m radia_mcp.gmsh_post._gen_api_reference
"""

from __future__ import annotations

import inspect
from pathlib import Path


SUBMODULES = [
	"model", "model.mesh", "model.geo", "model.occ",
	"view", "view.option",
	"option", "plugin", "graphics",
	"logger", "onelab", "fltk", "parser",
]


def _is_gmsh_native(obj) -> bool:
	mod = getattr(obj, "__module__", "") or ""
	return mod.startswith("gmsh")


def _first_line(doc: str | None) -> str:
	if not doc:
		return ""
	lines = [ln.strip() for ln in doc.splitlines() if ln.strip()]
	return lines[0][:200] if lines else ""


def _sig(obj) -> str:
	try:
		return str(inspect.signature(obj))
	except (TypeError, ValueError):
		return "(...)"


def _walk_module(mod_path: str):
	"""Yield (fqn, callable) for every public callable in a gmsh
	submodule, including nested classes. `mod_path` is relative to
	`gmsh`, e.g., "model.mesh"."""
	import gmsh
	obj = gmsh
	for part in mod_path.split("."):
		if not hasattr(obj, part):
			return
		obj = getattr(obj, part)
	for name in sorted(dir(obj)):
		if name.startswith("_"):
			continue
		attr = getattr(obj, name, None)
		if attr is None:
			continue
		# Skip ctypes / stdlib re-exports
		if not _is_gmsh_native(attr):
			# But allow classes / functions defined inline in gmsh.py —
			# these often have __module__ == 'gmsh' exactly
			if getattr(attr, "__module__", "") != "gmsh":
				continue
		if callable(attr):
			yield f"gmsh.{mod_path}.{name}", attr


def generate() -> str:
	import gmsh
	out: list[str] = []
	out.append('"""Auto-generated API reference for gmsh.\n\n'
	           'Generated by `_gen_api_reference.py` — do not edit by hand.\n'
	           'Regenerate when bumping gmsh in the environment.\n'
	           '"""')
	out.append("")
	out.append("API_REFERENCE = '''# gmsh Python API reference (auto-generated)")
	out.append("")
	out.append(f"gmsh version: {getattr(gmsh, 'GMSH_API_VERSION', '?')}")
	out.append("")

	# ---- Top-level functions (initialize, finalize, write, open, ...) ----
	out.append("## Top-level functions (`gmsh.xxx`)")
	out.append("")
	top_fns = []
	for name in sorted(dir(gmsh)):
		if name.startswith("_"):
			continue
		obj = getattr(gmsh, name, None)
		if obj is None or not callable(obj):
			continue
		if not _is_gmsh_native(obj):
			continue
		top_fns.append((name, obj))
	for name, fn in top_fns:
		sig = _sig(fn)
		doc = _first_line(inspect.getdoc(fn))
		out.append(f"### gmsh.{name}{sig}")
		if doc:
			out.append(f"- {doc}")
		out.append("")

	# ---- Per-submodule dumps ----
	for sub in SUBMODULES:
		entries = list(_walk_module(sub))
		if not entries:
			continue
		out.append("")
		out.append(f"## `gmsh.{sub}` ({len(entries)} callables)")
		out.append("")
		for fqn, fn in entries:
			shortname = fqn.split(".")[-1]
			sig = _sig(fn)
			doc = _first_line(inspect.getdoc(fn))
			out.append(f"### {fqn.replace(f'gmsh.{sub}.', f'gmsh.{sub}.')}{sig}")
			if doc:
				out.append(f"- {doc}")
			out.append("")

	out.append("'''")
	out.append("")
	out.append("def get_api_reference() -> str:")
	out.append('    """Return the bundled gmsh API reference."""')
	out.append("    return API_REFERENCE")

	return "\n".join(out)


def main() -> None:
	# gmsh must be initialized before some submodule attributes resolve
	import gmsh
	gmsh.initialize([], False)
	gmsh.option.setNumber("General.Terminal", 0)
	try:
		body = generate()
	finally:
		try:
			gmsh.finalize()
		except Exception:
			pass
	target = Path(__file__).with_name("gmsh_api.py")
	target.write_text(body, encoding="utf-8")
	line_count = body.count("\n")
	print(f"wrote {target} ({len(body)} bytes, {line_count} lines)")


if __name__ == "__main__":
	main()
