function coil = circularTurnStack(radius_m, turnCount, options)
%CIRCULARTURNSTACK Build a single-layer stack of circular PEEC turns.
arguments
    radius_m (1,1) double {mustBePositive,mustBeFinite}
    turnCount (1,1) double {mustBeInteger,mustBePositive}
    options.SegmentsPerTurn (1,1) double {mustBeInteger,mustBePositive} = 24
    options.Pitch_m (1,1) double {mustBePositive,mustBeFinite} = 3e-3
    options.WireWidth_m (1,1) double {mustBePositive,mustBeFinite} = 1.5e-3
    options.WireHeight_m (1,1) double {mustBePositive,mustBeFinite} = 1.5e-3
    options.Conductivity_S_per_m (1,1) double {mustBePositive,mustBeFinite} = 5.8e7
end

if options.SegmentsPerTurn < 8
    error("radia:peec:CoilResolution", ...
        "SegmentsPerTurn must be at least 8 for a circular turn.");
end
if turnCount > 1 && options.Pitch_m < options.WireHeight_m
    error("radia:peec:CoilOverlap", ...
        "Pitch_m must be at least WireHeight_m for stacked turns.");
end

segmentCount = turnCount*options.SegmentsPerTurn;
centers = zeros(segmentCount,3);
directions = zeros(segmentCount,3);
lengths = zeros(segmentCount,1);
polylines = zeros(options.SegmentsPerTurn+1,3,turnCount);
zValues = ((0:turnCount-1) - (turnCount-1)/2)*options.Pitch_m;
row = 0;
for turn = 1:turnCount
    theta = 2*pi*(0:options.SegmentsPerTurn)'/options.SegmentsPerTurn;
    vertices = [radius_m*cos(theta), radius_m*sin(theta), ...
        zValues(turn)*ones(size(theta))];
    polylines(:,:,turn) = vertices;
    for segment = 1:options.SegmentsPerTurn
        delta = vertices(segment+1,:) - vertices(segment,:);
        row = row+1;
        centers(row,:) = 0.5*(vertices(segment+1,:) + vertices(segment,:));
        lengths(row) = norm(delta);
        directions(row,:) = delta/lengths(row);
    end
end

if min(lengths) <= max(options.WireWidth_m,options.WireHeight_m)
    error("radia:peec:CoilSegmentAspect", ...
        ["Each PEEC segment must be longer than the conductor cross-section. " ...
         "Reduce SegmentsPerTurn or increase radius_m."]);
end

coil = struct( ...
    "kind", "circular_turn_stack", ...
    "radius_m", radius_m, ...
    "turn_count", turnCount, ...
    "segments_per_turn", options.SegmentsPerTurn, ...
    "pitch_m", options.Pitch_m, ...
    "wire_width_m", options.WireWidth_m, ...
    "wire_height_m", options.WireHeight_m, ...
    "conductivity_S_per_m", options.Conductivity_S_per_m, ...
    "centers_m", centers, ...
    "directions", directions, ...
    "lengths_m", lengths, ...
    "widths_m", options.WireWidth_m*ones(segmentCount,1), ...
    "heights_m", options.WireHeight_m*ones(segmentCount,1), ...
    "conductivities_S_per_m", ...
        options.Conductivity_S_per_m*ones(segmentCount,1), ...
    "polylines_m", polylines, ...
    "wire_length_m", sum(lengths), ...
    "segment_count", segmentCount);
end
