function result = seriesCoilProperties(coil, options)
%SERIESCOILPROPERTIES Compute uniform-current DC L and R from PEEC geometry.
arguments
    coil (1,1) struct
    options.AcaEps (1,1) double {mustBePositive,mustBeFinite} = 1e-10
    options.LeafSize (1,1) double {mustBeInteger,mustBePositive} = 16
    options.Eta (1,1) double {mustBePositive,mustBeFinite} = 3
    options.MaxRank (1,1) double {mustBeInteger,mustBePositive} = 80
end

required = ["centers_m","directions","lengths_m","widths_m", ...
    "heights_m","conductivities_S_per_m","segment_count"];
missing = required(~isfield(coil,required));
if ~isempty(missing)
    error("radia:peec:CoilSchema", ...
        "Coil geometry is missing field(s): %s", strjoin(missing,", "));
end
segmentCount = double(coil.segment_count);
if size(coil.centers_m,1) ~= segmentCount || ...
        size(coil.directions,1) ~= segmentCount || ...
        numel(coil.lengths_m) ~= segmentCount
    error("radia:peec:CoilShape", ...
        "Coil geometry arrays must agree with segment_count.");
end

totalTimer = tic;
manager = radia.HACApKPEECManager( ...
    coil.centers_m, coil.directions, coil.lengths_m, ...
    coil.widths_m, coil.heights_m, coil.conductivities_S_per_m);
cleanup = onCleanup(@() delete(manager));
buildTimer = tic;
ok = manager.build(AcaEps=options.AcaEps, ...
    LeafSize=options.LeafSize, Eta=options.Eta, ...
    MaxRank=options.MaxRank, PrintLevel=0);
build_s = toc(buildTimer);
if ~ok
    error("radia:peec:CoilBuild", ...
        "The HACApK PEEC inductance matrix build failed.");
end

matvecTimer = tic;
seriesCurrent = ones(segmentCount,1);
fluxLinkage = manager.matvec(seriesCurrent);
inductance_H = real(seriesCurrent.'*fluxLinkage);
matvec_s = toc(matvecTimer);
if ~isfinite(inductance_H) || inductance_H <= 0
    error("radia:peec:CoilInductance", ...
        "The PEEC series inductance must be finite and positive.");
end

resistance_Ohm = sum(coil.lengths_m ./ ...
    (coil.conductivities_S_per_m .* coil.widths_m .* coil.heights_m));
if ~isfinite(resistance_Ohm) || resistance_Ohm <= 0
    error("radia:peec:CoilResistance", ...
        "The conductor resistance must be finite and positive.");
end

wheeler_H = NaN;
if all(isfield(coil,["radius_m","turn_count","pitch_m"]))
    radiusInch = coil.radius_m/0.0254;
    lengthInch = max(0,(coil.turn_count-1)*coil.pitch_m)/0.0254;
    wheeler_H = 1e-6 * radiusInch^2*coil.turn_count^2 / ...
        (9*radiusInch + 10*lengthInch);
end
if isfinite(wheeler_H) && wheeler_H > 0
    wheelerRelativeDifference = abs(inductance_H-wheeler_H)/wheeler_H;
else
    wheelerRelativeDifference = NaN;
end

info = manager.info();
result = struct( ...
    "inductance_H", inductance_H, ...
    "resistance_Ohm", resistance_Ohm, ...
    "inductance_basis", ...
        "uniform-current DC partial inductance including internal term", ...
    "resistance_basis", "DC conductor resistance", ...
    "wire_length_m", sum(coil.lengths_m), ...
    "magnetic_energy_J_at_1A", 0.5*inductance_H, ...
    "wheeler_reference_H", wheeler_H, ...
    "wheeler_relative_difference", wheelerRelativeDifference, ...
    "segment_count", segmentCount, ...
    "hmatrix", info, ...
    "timing_s", struct( ...
        "build", build_s, "matvec", matvec_s, "total", toc(totalTimer)));
clear cleanup
end
