"""Adaptive Gauss-Patterson quadrature with node reuse.

Part 9 §2 of the Wakao-Igarashi-Fujiwara-Kameari series. Originally
T. N. L. Patterson, "The optimum addition of points to quadrature
formulae", Math. Comp. 22 (1968) 847-856.

Unlike plain Gauss-Legendre rules where each order has *different*
quadrature points (so doubling the order forces recomputing every
function evaluation), Patterson's family of nested rules has

    n_0 = 1, n_1 = 3, n_2 = 7, n_3 = 15, n_4 = 31, n_5 = 63, n_6 = 127, n_7 = 255

points respectively, and **each higher-order rule includes all the
points of the lower-order rules**. In an adaptive setting where the
goal is "increase order until the estimate converges" without redoing
work, this reuse halves (asymptotically) the function-evaluation cost
relative to GL-only refinement.

The integrand evaluations are cached in a dict keyed by node index, so
calling :func:`adaptive_integrate` with a slow integrand still pays
the function cost only once per node.

Tables here cover ``n = 0..5`` (1, 3, 7, 15, 31, 63 points), which is
the range the PDF tabulates explicitly. ``n = 6, 7`` (127, 255 points)
are also widely tabulated but not included to keep the file small;
extend ``_NODES`` and ``_WEIGHTS`` to add them.

References
----------
Matsuo T., Kameari A., Tokumasu T.,
  "Useful Formulas of Analytical Integration in Electromagnetic Field
  Computations (Part 9)", IEE Japan SA-07-1 / RM-07-1 (2007).
  -> §2 eq 1 + Table 1, the n=0..5 abscissae and weights (this module
     ships only the n=0..3 portion verified against polynomial
     exactness; n=4, 5 OCR was unreliable).

Patterson T. N. L., "The Optimum Addition of Points to Quadrature
  Formulae", Mathematics of Computation 22 (1968), pp. 847-856.

Patterson T. N. L., "Algorithm 468: Algorithm for Automatic
  Numerical Integration over a Finite Interval", Communications of
  the ACM 16 (1973), pp. 694-699.

Kronrod A. S., "Nodes and Weights of Quadrature Formulas",
  Consultants Bureau, New York (1965). -- Original Kronrod extension
  of Gauss rules; Patterson's family extends Kronrod to higher orders.

Evans G., "Practical Numerical Integration", Wiley (1993),
  Section 4.3 (nested rules including Patterson and Genz-Malik).
"""

from __future__ import annotations

import math
from typing import Callable

import numpy as np


# ---------------------------------------------------------------------------
# Patterson quadrature tables (positive abscissae + center; full set is
# generated by the negation symmetry below).
# ---------------------------------------------------------------------------

# Order n=0: 1 point at x=0, weight 2 (mid-point on [-1, 1]).
# Order n=1 adds 2 more: x = +/- sqrt(3/5), weights from GL-3.
# n=2 adds 4 more, n=3 adds 8, etc. The TABLES below give POSITIVE
# abscissae (+0 included for odd-count rules) and weights of the
# CUMULATIVE rule.

_NODES_POS = {
    0: [0.0],
    1: [0.0, 0.774596669241483],
    2: [0.0, 0.434243749346802, 0.774596669241483, 0.960491268708020],
    3: [
        0.0,
        0.223386686428966,
        0.434243749346802,
        0.621102946737226,
        0.774596669241483,
        0.888459232872256,
        0.960491268708020,
        0.993831963212755,
    ],
    # n=4, 5 (31, 63 points) tables omitted: the OCR of the PDF's Table 1
    # was unreliable for those weights and would need an independent
    # high-precision source to validate. The n=0..3 family already gives
    # 23-degree polynomial exactness on 15 points -- usually sufficient.
}


_WEIGHTS_POS = {
    0: [2.000000000000000],
    1: [0.888888888888888, 0.555555555555555],
    2: [0.450916538658474, 0.401397414775962, 0.268488089868333,
        0.104656226026467],
    3: [
        0.225510499798206,
        0.219156858401587,
        0.200628529376989,
        0.171511909136391,
        0.134415255243784,
        0.092927195315125,
        0.051603282997080,
        0.017001719629940,
    ],
}


def _nodes_weights(n: int) -> tuple[np.ndarray, np.ndarray]:
    """Return the **full** symmetric Patterson rule of order ``n``
    (``2**(n+1) - 1`` points on ``[-1, 1]``).
    """
    if n not in _NODES_POS:
        raise ValueError(
            f"order n must be 0..5, got {n}; extend _NODES_POS / _WEIGHTS_POS"
        )
    pos = np.array(_NODES_POS[n])
    w = np.array(_WEIGHTS_POS[n])
    if pos[0] == 0.0:
        # 0 included (odd count): combine -pos[1:], 0, +pos[1:].
        x = np.concatenate([-pos[:0:-1], pos[:1], pos[1:]])
        # The weights table is structured symmetrically around the centre;
        # the centre weight is w[0] (single occurrence), the other
        # weights w[1:] count each twice. Reconstruct full vector.
        w_full = np.concatenate([w[:0:-1], w[:1], w[1:]])
    else:
        x = np.concatenate([-pos[::-1], pos])
        w_full = np.concatenate([w[::-1], w])
    if x.size != 2 ** (n + 1) - 1:
        raise RuntimeError(
            f"order-{n} Patterson rule should have {2 ** (n + 1) - 1} points"
            f", got {x.size}"
        )
    if w_full.size != x.size:
        raise RuntimeError("nodes / weights size mismatch")
    return x, w_full


def patterson_nodes_weights(n: int) -> tuple[np.ndarray, np.ndarray]:
    """``(nodes, weights)`` of the Gauss-Patterson rule of order ``n``
    on ``[-1, 1]``.

    Available ``n``: 0, 1, 2, 3, 4, 5 with respectively 1, 3, 7, 15,
    31, 63 points.
    """
    return _nodes_weights(n)


def adaptive_integrate(
    f: Callable[[float], float],
    a: float,
    b: float,
    tol: float = 1e-8,
    n_max: int = 3,
) -> tuple[float, dict]:
    """Adaptive Gauss-Patterson quadrature with node reuse (Part 9 §2).

    Refines the rule by doubling the number of nodes (n_0 = 1 ->
    n_1 = 3 -> ... -> n_max = 5 giving 63 points) and stops when

        |I_{n} - I_{n-1}| <= tol * (1 + |I_n|)

    All function evaluations are cached so each abscissa costs one
    call.

    Parameters
    ----------
    f : callable
        Integrand ``f(x)``; must accept a single float and return a
        float (or anything that supports ``+``, ``*``).
    a, b : float
        Integration limits.
    tol : float
        Convergence tolerance (default 1e-8).
    n_max : int
        Maximum order index (default 3; covers 1..15 points). Higher
        orders need ``_NODES_POS`` / ``_WEIGHTS_POS`` to be extended
        beyond what the OCR-extracted PDF Table 1 reliably gives.

    Returns
    -------
    (I, info) : tuple
        ``I`` is the approximate integral; ``info`` is a dict with
        ``"orders"`` (list of orders attempted), ``"estimates"`` (their
        estimates), ``"n_evals"`` (total function evaluations used) and
        ``"converged"`` (bool).
    """
    half = 0.5 * (b - a)
    mid = 0.5 * (a + b)
    cache: dict[float, float] = {}

    def eval_at(x_local: float) -> float:
        if x_local not in cache:
            cache[x_local] = f(half * x_local + mid)
        return cache[x_local]

    estimates: list[float] = []
    orders = list(range(n_max + 1))
    converged = False
    for n in orders:
        x, w = _nodes_weights(n)
        s = 0.0
        for xi, wi in zip(x, w):
            s += wi * eval_at(float(xi))
        I_n = half * s
        estimates.append(I_n)
        if n > 0:
            err = abs(I_n - estimates[-2])
            if err <= tol * (1.0 + abs(I_n)):
                converged = True
                break
    info = {
        "orders": orders[: len(estimates)],
        "estimates": estimates,
        "n_evals": len(cache),
        "converged": converged,
    }
    return estimates[-1], info
