"""ESIM cross-formulation consistency check: scalar-potential BIE vs
HCurl FEM-Kelvin, nonlinear per-element AND uniform.

Backs SA-26-070 (八戸 2026-08) validation tier (vi) and the IGTE 2026
full-paper tier (vi).  Both outer-field formulations drive the SAME
1-D ESIM cell solver and the SAME Karl loop; this lane checks that the
end-to-end workpiece power P_wp agrees, and that the design-relevant
per-element/uniform ratio is reproduced across the two independent
implementations.

Two geometries x two impedance variants = the comparison matrix:

  A. Small cylinder (dia 20 mm x 20 mm), BH-knee point I=100 A f=50 kHz.
     BIE and FEM share ONE surface mesh (samples/ih_fem_kelvin_demo.vol),
     so this isolates the formulation with the mesh held fixed.
       per-element:  BIE ~1.338 W vs FEM ~1.312 W  (~+2 %)
       uniform:      BIE ~1.638 W vs FEM ~1.441 W  (~+14 %, aggregation
                     convention -- larger than per-element by design)

  B. Benchmark cylinder (dia 50 mm x 25 mm), deep-saturation point
     I=500 A f=10 kHz.  BIE uses its own 2150-tri surface mesh
     (samples/ih_bem_sample_p1.vol); FEM uses an INDEPENDENT volume
     mesh (ih_fem_kelvin_50mm.vol).  This isolates the formulation
     with the mesh NOT held fixed -- the harder test.
       uniform:      BIE ~162.4 W vs FEM ~161.1 W  (~+0.8 %)
       per-element:  BIE ~81.2 W  vs FEM ~74.3 W   (~+9 %, edge-adjacent
                     local |H_t| extraction convention dominates)
       ratio per/uniform:  BIE ~-50 %  vs FEM ~-54 %  (design-relevant,
                     reproduced independently -> "uniform over-predicts
                     P_wp ~2x in deep saturation")

Meshes are regenerated by make_meshes.py (requires Cubit).  This runner
does NOT import cubit (Cubit/NGSolve separation policy): it shells out
to the two production calc_*.py scripts and reads their JSON.

Per the Benchmark Policy, wall-clock timings are NOT part of the
committed golden record (they are meaningless on a contended LAB box);
only the physics (P_wp, H_t_rms, iterations, converged) is asserted.

Usage:
    python run_cross_formulation.py                 # run + assert + write results.json
    python run_cross_formulation.py --no-assert     # run + write, do not fail on band miss
    python run_cross_formulation.py --matrix A       # only the small-cylinder matrix
"""
import argparse
import json
import os
import platform
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
PANELS = os.path.join(REPO, "src", "radia", "panels")
SAMPLES = os.path.join(PANELS, "samples")

CALC_IND = os.path.join(PANELS, "calc_inductance.py")
CALC_FEMK = os.path.join(PANELS, "calc_fem_kelvin.py")
COIL_STEP = os.path.join(SAMPLES, "ih_fem_kelvin_demo_coil.step")

DEMO_VOL = os.path.join(SAMPLES, "ih_fem_kelvin_demo.vol")
BEM50_VOL = os.path.join(SAMPLES, "ih_bem_sample_p1.vol")
FEM50_VOL = os.path.join(HERE, "ih_fem_kelvin_50mm.vol")

BH_FILE = os.path.join(SAMPLES, "em_sample_bh.txt")

# --- Material / cell-problem constants (identical on both sides) ---------
SIGMA = 2e6
MU_R = 100
HALF_THICKNESS = 0.005

# --- Comparison matrix ---------------------------------------------------
# Each entry: label -> (geometry, operating point).  BIE and FEM runs of
# the same (geometry, point, variant) are compared.
MATRIX = {
    "A": {
        "name": "small cylinder dia20x20 (BH knee)",
        "bie_vol": DEMO_VOL,
        "fem_vol": DEMO_VOL,          # shared surface mesh
        "frequency": 50000.0,
        "current": 100.0,
        "max_iter": 30,
    },
    "B": {
        "name": "benchmark cylinder dia50x25 (deep saturation)",
        "bie_vol": BEM50_VOL,
        "fem_vol": FEM50_VOL,         # independent meshes
        "frequency": 10000.0,
        "current": 500.0,
        "max_iter": 40,
    },
}

# --- Golden bands (fractions) --------------------------------------------
# Agreement = |P_bie / P_fem - 1|.  Ratio = P_perpanel / P_uniform - 1.
BANDS = {
    "A_perpanel_agreement_max": 0.05,   # measured +2.0 %
    "B_uniform_agreement_max": 0.04,    # measured +0.8 %
    "B_perpanel_agreement_max": 0.15,   # measured +9.3 %
    "B_bie_ratio": (-0.60, -0.40),      # measured -50.0 %
    "B_fem_ratio": (-0.62, -0.46),      # measured -53.9 %
}


def _run_calc(script, out_json, extra):
    """Invoke a calc_*.py as a subprocess; return its parsed result dict."""
    cmd = [sys.executable, script, "--output", out_json] + extra
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        tail = "\n".join((proc.stdout + proc.stderr).splitlines()[-12:])
        raise RuntimeError("calc failed (rc=%d):\n  %s\n--- tail ---\n%s"
                           % (proc.returncode, " ".join(cmd), tail))
    with open(out_json, "r", encoding="utf-8") as f:
        return json.load(f)


def _bie(vol, frequency, current, max_iter, per_panel, tmp):
    extra = [
        "--coil-step", COIL_STEP, "--coil-solver", "peec",
        "--vol", vol, "--wp-label", "sibc",
        "--sigma", str(SIGMA), "--mu-r", str(MU_R),
        "--half-thickness", str(HALF_THICKNESS),
        "--frequency", str(frequency), "--current", str(current),
        "--coil-sigma", "5.8e7",
        "--impedance-model", "esim", "--bh-file", BH_FILE,
        "--esim-max-iter", str(max_iter), "--esim-tol", "1e-3",
        "--esim-relax", "0.5", "--esim-anderson-m", "5",
        "--h1-order", "1", "--wp-bem-backend", "intree-dense",
    ]
    if per_panel:
        extra.append("--esim-per-panel")
    d = _run_calc(CALC_IND, tmp, extra)
    return {
        "P_wp": d["P_wp_W"],
        "H_t_rms": d["H_t_rms_A_per_m"],
        "iterations": d["esim_iterations"],
        "converged": bool(d["esim_converged"]),
        "nv": d.get("wp_mesh_nv"),
        "radia_version": d.get("radia_version"),
    }


def _fem(vol, frequency, current, max_iter, per_panel, tmp):
    extra = [
        "--vol", vol, "--peec-step", COIL_STEP, "--peec-n-peri", "16",
        "--require-kelvin",
        "--frequency", str(frequency), "--current", str(current),
        "--material", "custom",
        "--sigma", str(SIGMA), "--mu-r", str(MU_R), "--bh-file", BH_FILE,
        "--half-thickness", str(HALF_THICKNESS),
        "--impedance", "esim", "--max-iter", str(max_iter),
        "--fes-order", "1", "--solver", "pardiso",
    ]
    if per_panel:
        extra.append("--esim-per-panel")
    d = _run_calc(CALC_FEMK, tmp, extra)
    return {
        "P_wp": d["P_total"],
        "H_t_rms": d["H_t_rms"],
        "iterations": d["iterations"],
        "converged": d["iterations"] < max_iter,   # FEM has no bool flag
        "ndof": d.get("ndof"),
        "radia_version": d.get("radia_version"),
    }


def run_matrix(keys, tmpdir):
    results = {}
    for k in keys:
        m = MATRIX[k]
        for vol in (m["bie_vol"], m["fem_vol"]):
            if not os.path.isfile(vol):
                raise RuntimeError(
                    "missing mesh %s -- run `python make_meshes.py` first"
                    % vol)
        print("== matrix %s: %s ==" % (k, m["name"]))
        cell = {}
        for variant, per_panel in (("uniform", False), ("perpanel", True)):
            bie = _bie(m["bie_vol"], m["frequency"], m["current"],
                       m["max_iter"], per_panel,
                       os.path.join(tmpdir, f"{k}_{variant}_bie.json"))
            fem = _fem(m["fem_vol"], m["frequency"], m["current"],
                       m["max_iter"], per_panel,
                       os.path.join(tmpdir, f"{k}_{variant}_fem.json"))
            agree = abs(bie["P_wp"] / fem["P_wp"] - 1.0)
            print("  %-9s BIE P_wp=%.4f (it=%d,conv=%s)  "
                  "FEM P_wp=%.4f (it=%d,conv=%s)  agree=%.1f%%"
                  % (variant, bie["P_wp"], bie["iterations"], bie["converged"],
                     fem["P_wp"], fem["iterations"], fem["converged"],
                     100 * agree))
            cell[variant] = {"bie": bie, "fem": fem, "agreement": agree}
        cell["bie_ratio"] = (cell["perpanel"]["bie"]["P_wp"]
                             / cell["uniform"]["bie"]["P_wp"] - 1.0)
        cell["fem_ratio"] = (cell["perpanel"]["fem"]["P_wp"]
                             / cell["uniform"]["fem"]["P_wp"] - 1.0)
        print("  ratio per/uniform:  BIE %.1f%%  FEM %.1f%%"
              % (100 * cell["bie_ratio"], 100 * cell["fem_ratio"]))
        results[k] = cell
    return results


def check_bands(results):
    """Return list of (name, ok, detail) for every applicable band."""
    checks = []

    def band(name, ok, detail):
        checks.append((name, ok, detail))
        print("  [%s] %s: %s" % ("PASS" if ok else "FAIL", name, detail))

    if "A" in results:
        a = results["A"]
        v = a["perpanel"]["agreement"]
        band("A_perpanel_agreement",
             v <= BANDS["A_perpanel_agreement_max"],
             "%.1f%% <= %.0f%%" % (100 * v,
                                   100 * BANDS["A_perpanel_agreement_max"]))
        # Qualitative: uniform diverges MORE than per-element (the point
        # of per-element -- it removes the aggregation-convention gap).
        band("A_uniform_diverges_more",
             a["uniform"]["agreement"] > a["perpanel"]["agreement"],
             "uniform %.1f%% > perpanel %.1f%%"
             % (100 * a["uniform"]["agreement"],
                100 * a["perpanel"]["agreement"]))
    if "B" in results:
        b = results["B"]
        band("B_uniform_agreement",
             b["uniform"]["agreement"] <= BANDS["B_uniform_agreement_max"],
             "%.1f%% <= %.0f%%" % (100 * b["uniform"]["agreement"],
                                   100 * BANDS["B_uniform_agreement_max"]))
        band("B_perpanel_agreement",
             b["perpanel"]["agreement"] <= BANDS["B_perpanel_agreement_max"],
             "%.1f%% <= %.0f%%" % (100 * b["perpanel"]["agreement"],
                                   100 * BANDS["B_perpanel_agreement_max"]))
        lo, hi = BANDS["B_bie_ratio"]
        band("B_bie_ratio", lo <= b["bie_ratio"] <= hi,
             "%.1f%% in [%.0f,%.0f]%%" % (100 * b["bie_ratio"],
                                          100 * lo, 100 * hi))
        lo, hi = BANDS["B_fem_ratio"]
        band("B_fem_ratio", lo <= b["fem_ratio"] <= hi,
             "%.1f%% in [%.0f,%.0f]%%" % (100 * b["fem_ratio"],
                                          100 * lo, 100 * hi))
    return checks


def _git_sha():
    try:
        return subprocess.check_output(
            ["git", "-C", REPO, "rev-parse", "--short", "HEAD"],
            text=True).strip()
    except Exception:
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--matrix", choices=["A", "B"], action="append",
                    help="run only these matrices (default: both)")
    ap.add_argument("--no-assert", action="store_true",
                    help="run + write results.json but do not fail on band miss")
    ap.add_argument("--output", default=os.path.join(HERE, "results.json"))
    args = ap.parse_args()

    keys = args.matrix or ["A", "B"]
    with tempfile.TemporaryDirectory(prefix="esim_xform_") as tmp:
        results = run_matrix(keys, tmp)

    print("\n-- golden bands --")
    checks = check_bands(results)
    n_fail = sum(1 for _, ok, _ in checks if not ok)

    radia_versions = sorted({
        r[v][s]["radia_version"]
        for r in results.values()
        for v in ("uniform", "perpanel") for s in ("bie", "fem")
        if r[v][s].get("radia_version")})

    record = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "hostname": platform.node(),
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "git_sha": _git_sha(),
        "radia_versions": radia_versions,
        "benchmark": "esim_cross_formulation_bie_vs_fem_kelvin",
        "material": {"sigma": SIGMA, "mu_r": MU_R,
                     "half_thickness": HALF_THICKNESS,
                     "bh_file": os.path.basename(BH_FILE)},
        "bands": BANDS,
        "results": results,
        "band_checks": [{"name": n, "ok": ok, "detail": d}
                        for n, ok, d in checks],
        "n_band_failures": n_fail,
        "timings_excluded_per_benchmark_policy": True,
    }
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2, ensure_ascii=False)
    print("\nresults -> %s" % args.output)

    if n_fail and not args.no_assert:
        print("FAIL: %d golden band(s) violated" % n_fail)
        return 1
    print("OK: all applicable golden bands satisfied")
    return 0


if __name__ == "__main__":
    sys.exit(main())
